### ISSUE TITLE
Added email templates don't appear after saving

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10103]
**Describe the bug**
Custom added email templates don't appear in the list after creation.

**To Reproduce**
1. Go to Go to Workflow -> Emails -> Add and edit templates
2. Click on a mailable which allows for adding templates, such as "Discussion (Copyediting)"
3. Click "Add Template"
4. Enter text and save the new template
5. Note that the new template doesn't appear in the list of available templates

**What application are you using?**
 OJS, OMP or OPS version main. This is working in 3.4.

**Additional information**
On saving the template, the console error shows `TypeError: this.currentMailable.emailTemplates is undefined`.

**Comment by jardakotesovec** [comment]
This is happening because the mailable modal gets close immediately as user starts typing in 'add template' modal, which resets the currentMailable.

Will be addressed as part of https://github.com/pkp/pkp-lib/issues/9992, as this is problem on multiple places where we have nested modals.

But will keep it open until the other ticket is merged.

**Comment by jardakotesovec** [comment]
@kaitlinnewson #9992 Is now merged - can you please check whether this now works as expected? Thank you.

**Comment by jardakotesovec** [comment]
@kaitlinnewson Thank you, good catch. Fixed that. Along with some other issue in doi interface. Should close correctly on main (if you get latest main version also for ui-library)
