### ISSUE TITLE
Italics broken in PDF viewer titles

### ISSUE THREAD

**Issue by emixolydian** [pkp/pkp-lib#10138]
When opening a PDF in the PDF viewer, titles with italics will not render and will still have `<i>` tags (see example below). A similar issue was fixed for article_details.tpl recently, but hasn't been changed in the PDF viewer display.

![image](https://github.com/pkp/pdfJsViewer/assets/173936441/902111ee-2e83-468f-9590-bcb6c7564e99)

This is the file: templates/display.tpl

- For the title in the body of the document, it should have `strip_unsafe_html` instead of `escape` so that italics will render.
- Similarly, the HTML tag `<title>` should have `strip_html` instead of `escape`.

**Comment by asmecher** [comment]
(Transferred from `pdfJsViewer` repo because this plugin is shipped with OJS/OMP/OPS and I don't want to miss the fix in the release notes.)

**Comment by Hafsa-Naeem** [comment]
@asmecher ready for review
**PR**
**OJS_main**: [pkp/pkp-lib#10138 Fix rendering of HTML tags in PDF viewer titles](https://github.com/pkp/pdfJsViewer/pull/71)

**Comment by asmecher** [comment]
Thanks, @Hafsa-Naeem! This won't be relevant to `stable-3_3_0`, because we didn't support rich content in titles yet, but it'll probably also be relevant to `stable-3_4_0`.

**Comment by asmecher** [comment]
@emixolydian, on closer inspection, it looks like this might've already been fixed. What exact OJS 3.4.0 build are you using?

**Comment by emixolydian** [comment]
Hi! We're actually on 3.3.0.13
But I did check stable 3.4.0 before submitting this Issue, and it's not in there https://github.com/pkp/pdfJsViewer/blob/stable-3_4_0/templates/display.tpl 
but maybe it was already patched later and I missed it?
It doesn't seem to be in 3.4.0-5 either https://github.com/pkp/pdfJsViewer/blob/3_4_0-5/templates/display.tpl
Not sure where else to check!
Thanks!

**Comment by asmecher** [comment]
@emixolydian, OJS 3.3.0-x doesn't support HTML formatting in titles. Starting with 3.4.0, we do, and there are WYSIWYG tools to create formatting in the titles. Are you entering HTML tags in titles in 3.3.0-x? If so, that's unsupported -- titles are expected to be plaintext, and HTML tags will be escaped.

**Comment by asmecher** [comment]
(I've reverted https://github.com/pkp/pdfJsViewer/pull/71 until we figure out what's needed.)

**Comment by emixolydian** [comment]
Sorry, I'm not expecting it to work in 3.3! We're upgrading soonish and many titles from this humanities journal need italics in the titles, so we've been patching our local site with the future improvements so it works in the meantime. We've been making sure we only implement changes that will be in future versions of OJS which is why I made the suggestion. Sorry for the confusion!

**Comment by asmecher** [comment]
Ah, gotcha. In that case I suspect this is probably an issue related to a partial back-port. In 3.4, the [`PKPSubmission::getLocalizedTitle`](https://github.com/pkp/pkp-lib/blob/a2d302700fe919d151970fda2b2b5bd6f181e8d2/classes/submission/PKPSubmission.php#L478) call forwards to [`PKPPublication::getLocalizedTitle`](https://github.com/pkp/pkp-lib/blob/a2d302700fe919d151970fda2b2b5bd6f181e8d2/classes/publication/PKPPublication.php#L86), which has a default format of `'text'`. So any HTML will be [stripped](https://github.com/pkp/pkp-lib/blob/a2d302700fe919d151970fda2b2b5bd6f181e8d2/classes/publication/PKPPublication.php#L101) and only the plain-text will be returned. It's working fine in our tests, so I'd suggest checking the back-ported feature to see if it behaves similarly.

**Comment by emixolydian** [comment]
Hi @asmecher thanks for the reply! Sorry for the slow response but I'm not sure I follow what you're saying. In the earlier comment you said 3.4 does support rich text in titles, but your most recent response seems to suggest that HTML tags will be stripped out? Does that mean no italics for titles in the PDF viewer in 3.4? Sorry if I'm misunderstanding your comment and thanks for taking the time.

**Comment by asmecher** [comment]
Don't worry about it, I'm often slower than that to respond!

I think the original report (HTML tags being escaped for presentation in article titles) is a quirk of your back-port to OJS 3.3.0-x; we weren't able to replicate the problem ourselves.

However, you're right that the current code could do better. Currently article titles in the PDF presentation show just the plain-text, though properly escaped, rather than the rich-formatted version. I've filed this for improvement here: https://github.com/pkp/pkp-lib/issues/10208

If you think I've missed something in this issue (which is entirely possible), let me know!

**Comment by emixolydian** [comment]
Ah okay! 
So the original problem I noticed was that titles on the regular article page were just showing up with their tags still intact, like if this page still had italics tags:
https://journalstest1.usask.ca/index.php/JDJ/article/view/1360
I went and checked the code for the most recent release and it was fixed there, so we made the change on our end. I think it was in article_details.tpl
So the tags aren't being stripped, the italics are being rendered.

However, we then noticed that on the PDF viewer page specifically the titles were still showing up with the HTML tags (like in the screenshot in my original issue)
I checked the most recent code to see if it had been solved and it seemed like it hadn't been addressed yet. I assumed we could resolve it in a similar way, which is what the suggested fix above does. 
But it sounds like the intent in 3.4 is for titles on the article page to render italics/support rich text, but that titles on the PDF viewer should strip out the tags? Is that right?

Here's another example I found in the wild of someone running 3.2 where the tags are showing up in the PDF viewer: https://www.canadianfieldnaturalist.ca/cfn/index.php/cfn/article/view/1787

**Comment by asmecher** [comment]
@emixolydian, the treatment of manually-entered HTML elements in submission titles was inconsistent in OJS 2.x all the way up to and including (IIRC) 3.2.x; proper rich text support in titles was a frequently requested feature and folks found various work-arounds and gaps, so until we were able to introduce a complete treatment for it with 3.4.0, we didn't disturb the status quo. In 3.3.0 we've fixed several XSS issues in recent releases and that tightened up our escaping of submission titles in the process. So 3.3.0-x treats article titles as plaintext and escapes them accordingly, and 3.4.0-x adds support for rich formatting (and escapes previously-entered content on upgrade for consistency).

So the behaviour you see in Canadian Field Naturalist is a WONTFIX; they run 3.2.1-2 with the old XSS flaws, which is in dire need of upgrading!

As for 3.4.0, I was not able to reproduce the behaviour you describe, where the PDF viewer renders HTML as plaintext:
![image](https://github.com/user-attachments/assets/473aac33-7c60-44f0-b3e1-433925534bf9)
Instead, the PDF viewer strips out HTML tags and presents properly-escaped plain-text:
![image](https://github.com/user-attachments/assets/7cc0379e-146e-4c93-9196-292d31bf5506)
...when what it *should* present is the properly escaped rich content:
![image](https://github.com/user-attachments/assets/a7673255-a6bc-4bef-9bdf-cefb060fedbd)

I've closed this issue because (if I get it right) the HTML escaping you initially described is actually a quirk of partially back-porting the HTML support to 3.3.0-x. But I *have* filed an issue for the improvement of the title display to support rich content at [#10208](https://github.com/pkp/pkp-lib/issues/10208).

**Comment by emixolydian** [comment]
Hi @asmecher thanks for taking the time to explain the different behaviours, I appreciate it. I'll see if we can fix our bad backport in the meantime and thank you very much for filing the issue for improving the title display down the road! Thanks! :)
