### ISSUE TITLE
OMP wrongly displays "Forthcoming" message if the date format is changed

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#10169]
**Describe the bug**
OMP will either display the catalog.forthcoming or catalog.published message on the monograph landing page, depending on the publication date of a monograph.  This message is chosen based on:

https://github.com/pkp/omp/blob/stable-3_3_0/templates/frontend/objects/monograph_full.tpl#L406

but this test will fail and display Forthcoming in cases when it should not, if the Date Format in Website Settings is something other than the default. In the screenshot below, choosing the circled format results in a Forthcoming message for a monograph with a publication date in 2022.  Setting it back to the default as chosen fixes the issue.

![date](https://github.com/pkp/pkp-lib/assets/218719/db79f215-7443-493b-a00a-987ef6072e61)

Seen in 3.3 but probably also in 3.4

Suggest converting these to time stamps instead, to make the math consistent.

**Comment by kaitlinnewson** [comment]
PR for review, will forward-port once approved:

- OMP 3.3: https://github.com/pkp/omp/pull/1724

@bozana can you review?

I opted for the Y-m-d as that is how the publication date is stored, but added formatting as a fallback in case that were to ever change.

On a side note, I couldn't actually display a forthcoming publication in 3.3, so this logic for "Forthcoming" may not actually be needed in 3.3 (but is in 3.4 due to the Preview functionality).

**Comment by bozana** [comment]
Hi @kaitlinnewson, you can forward-port...

**Comment by kaitlinnewson** [comment]
@bozana All forward-ported and listed above

**Comment by bozana** [comment]
All merged, so closing... 
Thanks a lot!
