### ISSUE TITLE
[OMP] test files missing from repository

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1026]
`README.md` gives instructions to set up unit testing:
```
mysql -u root -e 'create database omp'
mysql -u root omp < tests/functional/testserver.sql
cp config.TRAVIS.inc.php config.inc.php
```
The source tree does not include `testserver.sql` nor `config.TRAVIS.inc.php`.

**Comment by crism** [comment]
```
commit 4fe2950fca2b051041e5af256505b1ec6b92eb15
Author: Alec Smecher <alec@smecher.bc.ca>
Date:   Tue Aug 12 12:31:00 2014 -0700

    *8787* Remove old test server data

 delete mode 100644 tests/functional/testserver.sql

commit d07761eb95fbd422aa57da7aabc490a0e0babc56
Author: Alec Smecher <alec@smecher.bc.ca>
Date:   Tue Aug 12 12:00:21 2014 -0700

    *8787* Introduce data build to travis testing

 delete mode 100644 config.TRAVIS.inc.php
```
It looks, then, like the problem is just that `README.md` is out of date regarding testing. What’s the recommended way to test, locally, then?

**Comment by asmecher** [comment]
@crism, there's some documentation here that's a little more up to date:
https://pkp.sfu.ca/wiki/index.php?title=Unit_Tests

We've been finding the dev-side documentation a little brittle since we adopted some continuous-integration approaches. These days I tend to let Travis run the testing. The Travis scripts also serve as a rough and ready guide to configuring a test environment; see .travis.yml.

There are some guidelines on working with github which include information that should permit Travis testing to work on your own fork; see https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors (especially information on submodules).

**Comment by crism** [comment]
Thanks, @asmecher. Most of the motivation for this is that I get a lot of minor warnings and a few serious bugs running OMP with PHP 5.6, and I’d like to rigorously clean those up.

I’ll work through those guidelines and try to correct the `README.md` accordingly.

**Comment by asmecher** [comment]
@crism, thanks -- I'm using PHP 5.6.14 and it's running well. Could you describe the errors?

**Comment by crism** [comment]
@asmecher, the log has lots of time zone warnings for `mktime()` and and `strftime()`. Additionally, with OMP 1.1.1, there were errors of the sort: `Cannot redeclare class SignoffNotificationManager`; I want to check if those persist in `HEAD` before reporting those.

**Comment by crism** [comment]
The unit tests all pass, BTW, except the “incomplete, risky, or skipped” ones.

**Comment by asmecher** [comment]
The timezone warnings can be addressed by setting a time zone in php.ini (for OMP 1.1 or master) or config.inc.php (for OMP master only). I'll check the other.

**Comment by crism** [comment]
Thanks, @asmecher. I’d overlooked the `php.ini` timezone settings; the ones in `config.inc.php` had fixed most of the problems, but there were still errors coming out of `adodb-time.inc.php`, which the `php.ini` settings seem to have fixed.

If I confirm any of the other errors in `HEAD`, I’ll report them separately.

**Comment by asmecher** [comment]
OK, thanks!
