### ISSUE TITLE
Upgrade Citations plugin to target 3.5 main branch

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#10302]
The Scopus/Crossref Citations [plugin](https://github.com/pkp/citations) was last updated for the 3.4 release and should be upgraded/tested with the 3.5-targeting main branch.

**Comment by taslangraham** [comment]
Read for review @ewhanson
PR - https://github.com/pkp/citations/pull/1

**Details**
* Made changes required to have the plugin work with 3.5/main. 

* Updated Github actions to target the `main` branch instead of the old  `master` branch, however, we'll most likely have to revisit and update these tests. 

Here are screenshots of the plugin in action

![Screenshot 2024-08-15 135400](https://github.com/user-attachments/assets/0733ab3a-578f-44e8-82aa-c495ae5c8ce7)

![Screenshot 2024-08-15 135844](https://github.com/user-attachments/assets/361a10d6-e775-4c0b-a302-87c83a21058e)

**Comment by taslangraham** [comment]
@ewhanson I'm kicking the PR back into draft as I make updates to the tests

**Comment by taslangraham** [comment]
@ewhanson Tests are updated.
Read for review - https://github.com/pkp/citations/pull/1

**Comment by ewhanson** [comment]
Merged! Thanks, @taslangraham!

One small thing for the future: whenever you're referencing the issue number in a PR title or commit message, could you use the full "path" of pkp/repo-name#1234 (in this case pkp/pkp-lib#10302)? This will allow Github to pick it up even when it's referenced outside of the pkp-lib repository.
