### ISSUE TITLE
Integrate context-sensitive help

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1032]
Per Nate's work, e.g. https://github.com/pkp/pkp-lib/compare/master...NateWr:help_panel_scaffold
...and Alec's work on markdown help integration...
...integrate context-sensitive gitbook-based help using a flyout panel and a PHP-land Markdown parser.

**Comment by asmecher** [comment]
WIP:
https://github.com/asmecher/ojs/tree/gitbook
https://github.com/asmecher/pkp-lib/tree/gitbook

**Comment by asmecher** [comment]
Forgive the horrible colours and cropping; this is state-of-the-art animated GIF.

Illustrates:
- Panel open/close
- Basic Markdown rendering (from https://www.gitbook.com/book/pkp/ojs3/details as a submodule)
- "Sticky" state of help on leaving/re-opening without navigating in OJS
- Context sensitivity assignment for a page load per code: https://github.com/pkp/pkp-lib/compare/master...asmecher:gitbook#diff-3ff98b5293cf8bfac6aab3f1d45be01cR46
- Context sensitivity assignment for a component (tab) load per code: https://github.com/pkp/pkp-lib/compare/master...asmecher:gitbook#diff-232f940aeda7faeb5650752b8d77d2b3R136

![output](https://cloud.githubusercontent.com/assets/200411/12213418/9c15fe8a-b62c-11e5-966c-aa3a8faa188d.gif)

Is it best to name .md files directly in the code? This would keep it simple and allow us to write a checking tool with some simple code grepping, but there's probably be a better way.

**Comment by mtub** [comment]
Mind if I join the discussion? Alec, I think this looks good and promising. Hard-coding the md file names would force us to update code at many places when something in the structure of the documentation changes. Maybe some kind of simple mapping of topics and markdown files in one file? This could reduce necessary updates when renaming, splitting, adding help files.

**Comment by asmecher** [comment]
@mtub, thoughts absolutely welcome.

I'm not confident about the wisdom of including hard-coded filenames either. My criteria are...

- It should be something that doesn't give translators extra work
- We should be able to automatically search the code for broken connections between the software and the help content
- It should be manageable hopefully without introducing additional tools (if possible, something Gitbook allows natively)

**Comment by NateWr** [comment]
@mtub and @asmecher: just some input on where we'll get with the final implementation (hopefully) in case that impacts on design now.

For this prototype, we've just chucked in a link on the workflow page. But ideally, I'd like to be able to add very specific help links and attach them directly to grids, form labels, etc. These would then be able to open to very specific sections of the help documentation. Here's an example from the original mockups:

![help-links](https://cloud.githubusercontent.com/assets/2306629/12231445/63f1fd9a-b84f-11e5-8ee6-256f73ce90ad.png)

I haven't yet looked into Gitbook markdown structure, but if there's a way to generate section-specific anchor elements, it might be worth doing some post-processing on the markup. It looks like you can just drop a name anchor in like this:

```
### <a name="reviewers"></a>Reviewers Grid
```

The trick will be to generate a name anchor that doesn't change with different languages, and therefore can be referenced from within OJS.

**Comment by asmecher** [comment]
I added anchor support exactly as @NateWr described. You can, in PHP land...

    $this->setHelpFilePage($templateMgr, 'chapter_1_introduction.md#secondBit');

...and in the referenced Markdown document...

    ### <a name="secondBit"></a>The Second Part Of The Introduction

Gitbook permits anchors to be entered this way but presents them just as they're written above. Least worst for now?

**Comment by NateWr** [comment]
Just a potential sticking point (I don't know how GitBooks works): will it be possible/easy for translators to accidentally or intentionally change or remove the anchor element?

**Comment by asmecher** [comment]
@mtub is looking at options for including anchors in Gitbook, with exactly that issue in mind. My suspicion is that translators won't have too bad a time of it, and some automated checking tools in with the normal Travis toolkit will help prevent rot.

**Comment by NateWr** [comment]
:+1: If I want to take a look at this some time, what's the best way? Just check out your branch?

**Comment by asmecher** [comment]
Yes -- currently for OJS only -- check out `gitbooks` both for the app and for pkp-lib. You'll also have to do a submodule init to check out the gitbooks repo (which contains the markdown).

**Comment by asmecher** [comment]
@NateWr, Kevin and I had a brief meeting about help and he's going to start cracking on some content for OMP 1.2. Hopefully the basics can make it into that release. We could use some of your layout magic:

- The help link needs placement (probably in the top or left-hand sidebars). Kevin and I didn't think it was appropriate to put it in the front end -- just the back end.
- If you have some thoughts on navigation tools, I can put some work into hooking them up on the back end.
- The content itself needs to be formatted too. OTOH what's required is pure CSS -- I don't think anything necessitates a Markdown filter or similar [yet].

My `gitbook` branches (ojs and pkp-lib) are currently working. (Same as the animated gif above.) Note...
- Added submodule in the OJS repo will need checking out
- Added composer dependency in lib/pkp will need updating.

Have a look and let's talk on Monday.

**Comment by asmecher** [comment]
Additional requirement: should be able to add a help icon to modal titles to permit users to open the help panel from within a modal.

**Comment by asmecher** [comment]
To consider: how will plugins include help content? Can they augment built-in content? (Thinking e.g. of the DOI plugin, which will alter the appearance of existing forms.)

**Comment by NateWr** [comment]
Just to clarify: are you thinking at this stage about just one global help button? Are we at a stage yet where we can think about adding help buttons to grids and modals that jump to specific sections related to those items?

**Comment by asmecher** [comment]
@NateWr, we'll need help to be available in at least a couple of places/contexts, I think:
- On the page itself somewhere
- Within modals (e.g. on the modal title bar?) as the page area behind it will be obscured

I'm not sure we'll need help controls on the grids themselves, and that might also complicate things, as grids might span roles. IMO it makes sense to write help based on the page and/or tab and perhaps not below that.

It might also make sense to review the document scaffold Kevin's putting together in deciding this.

**Comment by NateWr** [comment]
Ok. I think my initial thought was to have more specific help texts but let's start with what we get and iterate based on user tests.

**Comment by NateWr** [comment]
I tried to get this up and running today to work on it, but couldn't get the new gitbook submodule going. I can see the submodule in my `.gitmodules` file:

```
[submodule "docs/manual"]
        path = docs/manual
        url = https://git.gitbook.com/pkp/ojs3.git
```

I've tried running `git submodule update --init --recursive`, but it's not fetching the submodule (no output to the console). When I run `git submodule status` it's not listed:

```
nate@nate-desktop:/var/www/html/ojs$ git submodule status
 dd2bd3b4b2eb4b2267ae76439725fbc6c223fb30 lib/pkp (ojs-3_0b1-401-gdd2bd3b)
 659ef5c144a69b41b996edf379ec89ff54d4b0d6 plugins/generic/customBlockManager (remotes/origin/i700-fix-24-g659ef5c)
 3b99cd535ec391f4e1a73e4920783c08b32d6f1e plugins/generic/staticPages (remotes/origin/i700-fix-22-g3b99cd5)
 91a1a5fd8d80093099ca56bb24dbd58c6afe5b9e plugins/generic/tinymce (heads/master-14-g91a1a5f)
 94461f1d8108e01c7ac5a951d28b02dc624d0862 plugins/generic/translator (remotes/origin/i700-fix-5-g94461f1)
 819f22267ce4aff6e190190b0cf07397f6b1c1f7 plugins/viewableFiles/lensGalley (heads/master)
 a6b14c567751c62488492a48604dc8b1908459f2 plugins/viewableFiles/pdfJsViewer (pdfJsViewer-1_0_0-0-15-ga6b14c5)
```

Any idea what I'm missing here?

**Comment by NateWr** [comment]
Ok, I tried again with the docbooks files you sent me, but I'm still getting a 404 error when it tries to load the content.

![help-handler](https://cloud.githubusercontent.com/assets/2306629/12789995/22d7d2d4-ca98-11e5-8bb7-9cc2e37579f4.png)

Here's what I did, maybe you can spot the error:

1. Unpack the gitbook into `/docs/`. So I've got `/docs/manual/en/*.md`.
2. Check out `asmecher/gitbook` for `ojs` and `pkp-lib`.
3. Run `composer update` in `/lib/pkp` (no errors).
4. Clear cached files.
5. Load OJS, open a submission, click the "Help" link at the bottom.

The help panel loads but the content doesn't and I just have the Loading spinner with the errors in the console. (There's an extra error which appeared when I clicked the "Home" link)

**Comment by asmecher** [comment]
Hmm, do you have `pages/help/index.php` in your checkout?

**Comment by asmecher** [comment]
BTW, I checked with gitbook and it looks like anonymous checkouts aren't supported. They recommend that we use the github integration to host the manuals repo on github instead.

**Comment by NateWr** [comment]
No, I don't have `pages/help/index.php`. It doesn't appear to be in your `gitbooks` branch either: https://github.com/asmecher/ojs/tree/gitbook/pages

**Comment by asmecher** [comment]
...aaaaaand you're absolutely right. I forgot to add that file. Added now.

**Comment by NateWr** [comment]
OK, I've been able to get this up and running now. Just starting to take a look.

There's an issue with locales in the URLs that I wanted to note before forgetting about it. My test installation had `en` and `fr`, resulting in a URL like this:

```
/help/index/en%2Fchapter_6_submissions.md?_=1454950387619
```

The `/` is getting converted to `%2F` [here](https://github.com/asmecher/pkp-lib/blob/gitbook/templates/common/footer.tpl#L35). If I swap out the `/` for `%2F` the URL works fine.

For now I've just disabled the French language so I can focus on my part styling it.

**Comment by NateWr** [comment]
I want to raise some concerns around the way that `helpContext` is getting treated as a page-wide attribute. I know that you and Kevin are talking about just having one help doc for each page/workflow stage at this time. I see this as a useful MVP for the help panel, but I think we will want more granular integration so that help topics can be attached to grids and form elements.

I know we've talked about this and you don't agree. But at the very least I'd like to get a more flexible architecture in place with the help panel that won't make it difficult to expand our use of it in the future.

When I set up the initial scaffold, I introduced a new pattern using HTML data attributes that I'm hoping we can begin to use more often with our JS-driven stuff. This is particularly useful for global widgets like the help panel.

Right now we're passing a global help "context" to the help panel:

```
<script type="text/javascript">
	// Initialize JS handler
	$(function() {ldelim}
		$('#pkpHelpPanel').pkpHandler(
			'$.pkp.controllers.HelpPanelHandler',
			{ldelim}
				helpUrl: {url|json_encode page="help" path="HELP_CONTEXT_SLUG" escape=false},
				helpContext: {$pageHelpContext|json_encode}
			{rdelim}
		);
	{rdelim});
</script>
```

Ideally, the item calling the help panel will define the context. That's what the "topic" attribute of the link is for:

```
<a href="#" class="requestHelpPanel" data-topic="chapter_9_production.md">
	Help
</a>
```

Or hopefully some day something like this:

```
<a href="#" class="requestHelpPanel" data-topic="chapter_9_production.md#understanding_galleys">
	Help
</a>
```

With this technique, we won't be restricted in terms of what help links we drop in, where we drop them in, or which content we want them to load.

We're already going to run into problems with this in our workflow stages anyway, since each stage is not in a separate page context, but loads within a tab controller.

Aside from this, I think we'll find the following benefits:

- We don't need any fragile communication between the SiteHandler and the HelpPanelHandler. The help panel remains "dumb", in the sense of knowing about anything other than itself, and we therefore minimize the data needed to "feed" them.
- We'll probably be able to resolve the multi-context bug (last comment) because we'll be building the URL from component parts.
- The handler's topic will "live" in the HTML of the link, so it will sit alongside the content it's related to, which should make it easier to maintain over time.

**Comment by NateWr** [comment]
@asmecher I went ahead and did a quick conversion over to the technique I suggested, and issued a PR to your repo:

https://github.com/asmecher/pkp-lib/pull/12

Let me know what you think about going this route.

**Comment by asmecher** [comment]
Thanks, @NateWr -- I'll give this a review after the call.

**Comment by asmecher** [comment]
@NateWr, your proposed solution is clean and more flexible. Please go for it, per my comment on https://github.com/asmecher/pkp-lib/pull/12.

**Comment by NateWr** [comment]
Pull requests to your branch on `asmecher`:
https://github.com/asmecher/pkp-lib/pull/13
https://github.com/asmecher/ojs/pull/3

I added links to each stage of the workflow.

The Issue chapter would be a great candidate for attaching a help link to a grid. That's the only good place I can see for the help link on the Dashboard > Issues pages.

**Comment by asmecher** [comment]
@NateWr, can you close those PRs and open new ones against the `gitbook` branch?

**Comment by NateWr** [comment]
Woops! New PRs:

https://github.com/asmecher/pkp-lib/pull/14
https://github.com/asmecher/ojs/pull/4

**Comment by asmecher** [comment]
Looking good so far, and starting to serve well for examples of help integration points. About help links on grids, I'd argue that the context is actually the tab rather than the grid -- though the distinction is a little thin when there's only a single grid within a tab. My previous solution was to have a tab open "set" the user's current help context, so that opening the help panel would result in presenting that tab's help. But OTOH attaching help to the tab will probably look weirder than necessary.

**Comment by asmecher** [comment]
(One thought: I wonder if the "help" link will get lost so far down on the page. But some UI/UX testing will tell better than I whether that's an issue.)

After merging your PRs, I rebased off the master branch. Rather than force-pushing to my `gitbook` branch, which will cause you trouble if you've worked further on a fork from there, I created new `gitbook2` branches for both OJS and pkp-lib. When you have the chance, please move over to those to continue working. (Make sure you pull in changes from other submodules -- some of the plugins in particular have had changes that will break your install if not pulled in, such as renaming `String` to `PKPString` in prep for PHP7 compatibility.)

**Comment by asmecher** [comment]
(@NateWr, FYI, the linter caught a few JS complaints: https://travis-ci.org/asmecher/ojs/jobs/111820071)

**Comment by NateWr** [comment]
I think the problem with the Issue tab is exactly as you describe: when there's only one grid on a tab the grid and the tab are the same context. The tab has no space outside of the grid to slot in UI components.

These kinds of anomalies will crop up a lot, I think, as we continue to iterate with the help text. That's why I wanted the more flexible way of defining help topics straight in the template files.

I think it would be good to add the ability for grids to have a help topic defined so that in such circumstances we can use it this way. But of course when and where we put help links will change depending on the context in which they appear -- grids won't always be the right place.

**Comment by NateWr** [comment]
And since help links attached to grids might depend on context, it'd be great to be able to pass in a topic for a grid straight in the template file. Perhaps in the grid controller's JSON options object? That way in theory we could have different topics depending on context for the same grid class.

**Comment by NateWr** [comment]
PR: https://github.com/asmecher/pkp-lib/pull/15

This fixes some of the errors. However, I'm confused about the "Function requires 2 arguments" warning. I was under the impression this didn't really matter in JS:

https://travis-ci.org/asmecher/ojs/jobs/111820071#L936

Also, I'm not sure what it's asking me to do here to define `options.topic`:

https://travis-ci.org/asmecher/ojs/jobs/111820071#L940

**Comment by NateWr** [comment]
I think my role here is mostly done for now since it's just a matter of filling out the content. I'll unassign myself but of course re-assign me if you're waiting on me for any next steps.

**Comment by asmecher** [comment]
Thanks, @NateWr -- I've merged your PR, fixed the JS linting problems and will give this a spin.

**Comment by asmecher** [comment]
Work proceeds. Some issues:

- [ ] @NateWr, Opening the help panel from within a modal results in the help panel expanding, but darkened.
- [ ] @NateWr, The next/previous navigation links might need styling. (Will demo on Monday.)
- [ ] "New Catalog Entry": need help for modal; also each tab. Will look cluttered. (Not linked yet; will demo on Monday.)
- [ ] Chapter 4 unlinked pending rewrite into grids
- [ ] @stranack, what is `chapter5/editorial-history/add.md`?
- [ ] @stranack, `chapter6/press` needs to be renamed to `chapter6/context` (can't use OMP-specific lingo in shared content)
- [ ] @stranack, `chapter10/reviewing-a-submissionmd.md` needs its filename corrected

**Comment by asmecher** [comment]
I added a quick check tool to the Travis builds that tests the linkage between the system and the help files.

If a help file is missing, then it generates a test failure.

It also generates a list of files in the manual that are not linked from anywhere in the code. See e.g. the end of 
https://travis-ci.org/asmecher/omp/jobs/115401654 (starting with "Unreferenced help files:").

**Comment by asmecher** [comment]
More little bits and pieces:
- [ ] @stranack, the setup form corresponding to `chapter6/website/navigation.md` has been removed so that file can too.
- [ ] @stranack, Chapter 6 doesn't appear to have any help areas for most of the Settings > Workflow area

**Comment by asmecher** [comment]
Merged pulls:

https://github.com/pkp/ojs/pull/793
https://github.com/pkp/omp/pull/242
https://github.com/pkp/pkp-lib/pull/1276

OJS needs...

- [ ] its help docs re-forked and adapted from OMP when that's in a good state...
- [ ] the help test script added to its `.travis` (as per OMP)

Otherwise it should be good to go. We'll come back to it during the sprint.

**Comment by asmecher** [comment]
@NateWr, there are more parts of OMP to integrate with the help documentation, but this is probably a good point for me to pause if you want to experiment. @stranack, drop a note here if you change the structure and I'll make sure it stays synced.

**Comment by stranack** [comment]
OK, I've changed the structure just now. 

It is very basic, and largely page-based. We will need to decide where to break some of these pages down into sub-pages. This could be a sprint activity.

**Comment by NateWr** [comment]
Ok, we talked a bit about the Help link getting lost on the workflow stage tabs. I'm hesitant to move it straight up to the top of the right sidebar, because the editorial action buttons really provide a solid anchor to the composition of the page. It's been tough to bring some order to these tabs and so I'd really like to hang on for dear life to those buttons staying slotted right in that corner.

I tried a couple of different arrangements with it at the top left, but it really felt inappropriately in-your-face. Instead, I've worked on punching up the profile of the help link where it is in that right sidebar, to make it more noticeable.

What do you think about this treatment? Does it address your concerns at all?

![selection_021](https://cloud.githubusercontent.com/assets/2306629/13787652/ad81f052-ead4-11e5-83a4-e0be13868bd9.png)

The worst tab is the review stage. There's just so much going on there, but I don't think jamming a help link up top is going to help the situation:

![selection_022](https://cloud.githubusercontent.com/assets/2306629/13787683/cdb60c78-ead4-11e5-9de3-580fca846d4b.png)

And remember that most people will first come into this tab pattern from the submission screen, where there's a lot less clutter and so the help link is much more noticeable. Most will have an opportunity to spot it at this stage to help them remember it's there later:

![selection_023](https://cloud.githubusercontent.com/assets/2306629/13787716/f48b5574-ead4-11e5-917a-6760f4b296ab.png)

If you still feel like it ought to be higher in the queue, I've got a slightly modified treatment for moving it above participants. But it does disrupt the hierarchy we have in that sidebar in terms of the visual weight of items on the right (Actions > Participants > Help).

![selection_024](https://cloud.githubusercontent.com/assets/2306629/13787833/65ad6c7e-ead5-11e5-8bca-05350bac6c8c.png)

**Comment by asmecher** [comment]
"Help" is one of those things I would least expect to jump around -- it's like a panic button. The user is already lost and making them chase the link is insult to injury. What about the original option of moving it into the top menu? That's where I would naturally expect to see it, and it's logically anchored to the panel that slides out with help content. Currently we don't ever have more than one help link per "page" (loosely defined), though I know you've been thinking about putting them on grids too.

Picking on Wordpress again, when help is available, it's always at the top right, just below the menu bar.

**Comment by stranack** [comment]
What about adding it (for now, at least) to the left or right of the View Site button at the top of the page? It would be consistent, but not disrupt the flow of the pages themselves?

**Comment by NateWr** [comment]
Are you talking about adding a help link in the global context bar that goes across the top? I'm all for that.

But it doesn't really solve our need for context-specific help links. If we have a global help link in the top bar, it needs to stay global, dumping the user in the table of contents at all times.

It would be incredibly disruptive to the overlapping contexts model we have in the UI if the same help link went to different places, especially since it can change without the user even seeing a page reload (eg - tabs).

We don't really have a solid concept of "pages" in our system, because of the heavy use of tabs and modals. For that reason, we're going to need at least a few ways to jump people directly from a specific context into the help panel, and these are by nature going to end up in different places.

The screenshots I posted were purely restricted to the workflow tabs. That's the only context where we have a sidebar. All other contexts (modals, grids, tabs without sidebars, content without *any* tabs) will need a separate route in.

You're right about aiming for consistency. But by nature we're going to have to aim for consistency per-context. Modals, grids and tabs are each unique enough in their presentation that I think we're safe as long as we're consistent within modals, consistent within grids, and consistent within tabs.

The only real risk of overlap here is between our workflow tabs (which have a sidebar context) and our other tabs (which are just empty containers). These contexts are visually similar but have different content structures.

Faced with this problem, I'd much rather optimize for our editorial workflow tabs, where the help is most needed, and later deal with other tabs. These other tabs are so inconsistent it's going to be really hard to find a meaningful presentation that works in general. 

*And not every piece of content needs a corresponding help link*.

In the majority of cases where these other pieces of content could benefit from a help link, I think alternative approaches will be more effective (for instance, attaching help links to grids or form labels in settings).

**Comment by NateWr** [comment]
Ok, I couldn't let this go. Thanks for pressing me on this. I think I've come up with a good approach for tabs (workflow, settings, and other tabs) which also sets the stage for some further improvements we can make for OJS 3.0 that will allow us to make the help link consistent whether or not a page uses tabs.

Here's the approach I propose for OMP 1.2. That link looks a little bit too much like a tab, but the rounded corners should distinguish it enough not to interfere with the semantics of our tabs and the placement feels comfortably prominent without being in-the-way (to me).

![omp1 2-tab-help](https://cloud.githubusercontent.com/assets/2306629/13791351/915956f8-eae4-11e5-9a7b-0f2177d67cb0.png)

And my eventual goal for OJS 3.0 is to revise our page title/tab structure so that page content looks the same whether or not tabs exist. We'll also save a little bit of real-estate without, I think, crowding the page. This would look something like this:

![ojs3 0-tab-help](https://cloud.githubusercontent.com/assets/2306629/13791404/dba38fee-eae4-11e5-9f5d-61b804406d41.png)

The only downside to this presentation is that it's very close to where we might put a global help link in the top context bar. However, I feel the proximity would actually make the global help link obsolete, as long as we could consistently place a help link on every page in the backend.

Does this cut the Gordian knot?

**Comment by stranack** [comment]
I like it a lot.

**Comment by asmecher** [comment]
I like it too. Could we use a similar visual cue for the title bar of a modal?

**Comment by NateWr** [comment]
@asmecher, yes I think so (modals), but it will require some tweaking along with the style changes I proposed for OJS 3.0.

I will put some time in on this next week as my biggest priority. I will:

- Implement the new help location for all tabs or tab-like interfaces.
- Remove help links from modals *just for OMP 1.2*
- Revise the structure and content of the help text in line with our email discussion in prep for OMP 1.2.

Do I issue PRs to the repository for the gitbook submodule? Or is there a special gitbook's area where I need to check out and issue PRs for content changes?

**Comment by asmecher** [comment]
Sounds good. I merged the current help stuff into `master` -- the amount of rebasing I was doing on `gitbook2` was going to cause trouble for collaboration. Go ahead and work from `master`.

**Comment by NateWr** [comment]
@asmecher I actually meant the help content itself. Is that managed in the repository linked as a submodule, or in a separate gitbooks area?

**Comment by asmecher** [comment]
Oh -- that's at https://github.com/pkp/omp-user-guide. We haven't experimented with simultaneously editing via gitbook.io and github, so I'd suggest creating PRs and assigning them to @stranack so he knows what's happening.

**Comment by NateWr** [comment]
@asmecher I've noticed that anchor links render to incorrect URLs in the markdown files. For instance, the following markdown:

```
[Link](#my-anchor)
```

When that appears in the file at `en/chapter5/internal-review.md`, the resulting URL is:

```
<a href="en/chapter5/#my-anchor">
```

I presume this is a bug of the markdown parser we're using, or a quirk of the way we're using it. But I wondered if maybe it was something you had a quick idea for solving.

If not, I wouldn't invest too much time into it. We can use ```[link](internal-review.md#my-anchor)```. It's just a little bit more brittle for internal links.

**Comment by NateWr** [comment]
Hmm, it looks like it also tampers with external links:

```
[external link](http://google.com)
```

Becomes:

```
<a href="en/chapter5/http://google.com">
```

Is this intentional?

**Comment by asmecher** [comment]
@NateWr, I hacked in a URL filter to preprocess URLs. That's probably what's causing the problem. I suspect a quick regexp match to conditionally apply the filter would solve it. See this LOC:
https://github.com/pkp/pkp-lib/blob/master/pages/help/HelpHandler.inc.php#L65

**Comment by NateWr** [comment]
@asmecher What's the benefit you see in filtering the URLs? Are there use-cases where relative URLs are causing problems?

**Comment by asmecher** [comment]
> What's the benefit you see in filtering the URLs? Are there use-cases where relative URLs are causing problems?

Because the help content is popping up over the workflow, relative URLs would be relative to the workflow, not the help area.

**Comment by NateWr** [comment]
> Because the help content is popping up over e.g. the workflow, relative URLs would be relative to the workflow, not the help area.

I'm tempted to get rid of this if you don't mind. We're [hijacking links](https://github.com/pkp/pkp-lib/blob/master/js/controllers/HelpPanelHandler.js#L236-L243) within the content anyway. It would be nice to be able to use relative links as they're traditionally used in HTML. And appending `en/` to links causes some knock-on issues, such as jumping back to the server to re-fetch content even if you're just clicking a `#anchor` link on the existing page.

**Comment by NateWr** [comment]
Ok, I've got some come just about ready to go once the changes in the doc repo are merged (that PR is here: https://github.com/pkp/omp-user-guide/pulls ).

That code is in the `i1032_help_panel` branches of my OMP/pkp-lib repos:

https://github.com/NateWr/omp/tree/i1032_help_panel
https://github.com/NateWr/pkp-lib/tree/i1032_help_panel

I suspect there will be some merge conflicts so going to hold off on PRs until the doc submodule is good to go, then work through conflicts and stage the PRs properly.

Some screenshots to show the new help panel styling and link placements:

![help-header](https://cloud.githubusercontent.com/assets/2306629/14078364/24065ed0-f4ed-11e5-8d87-6c78dbc94411.png)

![help-modal](https://cloud.githubusercontent.com/assets/2306629/14078363/24065eda-f4ed-11e5-96d3-c911f088bf05.png)

![help-tab](https://cloud.githubusercontent.com/assets/2306629/14078365/2406fec6-f4ed-11e5-8826-b6e7eca0a42f.png)

**Comment by NateWr** [comment]
@stranack and @asmecher 

Just a reminder that this pull request https://github.com/pkp/omp-user-guide/pull/1 is sitting in the `omp-user-guide` repository.

I need that merged as soon as possible because it will take me a decent chunk of work to properly stage the commits for `pkp-lib` to go along with those changes.

**Comment by asmecher** [comment]
@NateWr, I turned those two PRs into rebases on my own fork:
https://github.com/pkp/pkp-lib/pull/1350
https://github.com/pkp/omp/pull/268

I think the Travis builds were failing on your OMP PR because the final commit included two submodule updates; it should only include the lib/pkp submodule update. I'll see if the tests pass this way.

**Comment by asmecher** [comment]
Merged. Two additional changes were required, FYI, @NateWr:

- [Javascript linting tweaks](https://github.com/pkp/pkp-lib/pull/1350/commits/3e1e30cff118c45f6837e06f6956e90b967f9451)
- [Change the help check script to ignore anchors](https://github.com/pkp/pkp-lib/pull/1350/commits/2f4dfa680b60bab23d486da9ed3fa4b43931116c)

That last one should eventually be improved to check that anchors exist in the source MD, but leaving that for later.
