### ISSUE TITLE
Duplicate user validation setting in config.TEMPLATE.inc.php

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#10351]
**Describe the bug**
In config.TEMPLATE.inc.php, there are two variables that describe the same function, aren't they conflicting?

`; The number of days a new user has to validate their account
; A new user account will be expired and removed if this many days have passed since the user registered
; their account, and they have not validated their account or logged in. If the user_validation_period is set to
; 0, unvalidated accounts will never be removed. Use this setting to automatically remove bot registrations.
user_validation_period = 28`
https://github.com/pkp/ojs/blob/34cc051dc500f8fe18cd06dbde61dbca579f916a/config.TEMPLATE.inc.php#L130C1-L134C28

`; Maximum number of days before an unvalidated account expires and is deleted
validation_timeout = 14`
https://github.com/pkp/ojs/blob/34cc051dc500f8fe18cd06dbde61dbca579f916a/config.TEMPLATE.inc.php#L366C1-L367C24

**What application are you using?**
OJS 3.4

**Comment by asmecher** [comment]
@touhidurabir, could you have a look at this one?

**Comment by touhidurabir** [comment]
I think we are misunderstanding the usage of the config settings `validation_timeout` and `user_validation_period` mainly because of their similar naming .

`validation_timeout` :=>
This setting define how long a email link will be valid after registration . This only applied when `require_validation` in `email` section is turned on which control if a user must validate the email after registration . If need to verify email after registration or user add, that is `require_validation` set to `On`, user will get a mail along with link to verify which will be valid for `validation_timeout` days . 

`user_validation_period` :=>
As it describe , till how many days after user account will be removed since user has registered and has not validated or logged in at all . This was introduced as part of https://github.com/pkp/pkp-lib/issues/4240 . 

It seems that the usage of `validation_timeout` has been removed in current `main` (upcoming `3.5.0`) in favour of invitation process but still in user in `3.4.0+` .

**Comment by mpbraendle** [comment]
Yes, this is conflicting. With the default values it means: User gets a link that is valid for 28 days (validation_timeout). If he/she does not confirm, account will be removed after 14 days (user_validation_period). Which means that the link isn't useful anymore the last 14 days.

**Comment by touhidurabir** [comment]
As I have mentioned the descriptions are confusing . Basically for `require_validation`, the description says `Maximum number of days before an unvalidated account expires and is deleted` but that just basically the activation deadline since registration or user adding . It does not remove the unvalidated user after `14` days which set as default for `require_validation` . 

What will remove the unvalidated user is the setting `user_validation_period` which set to double of `require_validation` as `28` days as default . We intentionally set this default double of what activation deadline set by `require_validation` so that if user for some reason missed it , they can reach to JM/Editors . 

Perhaps proper description is needed here . Hopefully I am not missing something else here .

**Comment by touhidurabir** [comment]
closing this but feel free to reopen if there still any more confusion persist .

**Comment by mpbraendle** [comment]
Yes, just provide clearer description.
