### ISSUE TITLE
Unable to Hook onto Review Form to Add Custom Slider Item Type in OJS Plugin (3.4.0-7)

### ISSUE THREAD

**Issue by bilalelkhouly** [pkp/pkp-lib#10490]
**Describe the bug**
I am trying to create a plugin to add a new item type (slider) to the review form. However, the plugin does not seem to hook onto the review form properly. I attempted to use the Form::config::before hook, but it didn’t modify the form as expected. I expected the form to display a slider as an item type, but it doesn’t appear, and the plugin seems to be ignored on the review form pages.

**To Reproduce**

1. Install and activate the custom plugin.
2. Go to the journal’s Workflow settings > Review > Review Forms.
3. Attempt to create or edit a review form and add a new item.
4. Notice that the slider input field is not available as an option.

**What application are you using?**
 OJS version 3.4.0-7

**Additional information**
Here’s the relevant code used for the hook registration in the plugin:

HookRegistry::register('Form::config::before', [$this, 'addSliderToReviewForm']);

No errors or issues are logged, but the plugin does not affect the review form configuration.

Additionally, I’ve tried to access the OJS forum to post my question and seek further help, but I encountered an issue with logging in. The forum says it’s invite-only, and I’m unable to create an account. Could you please advise on how to access the forum or invite me so I can post my questions there?

**Comment by asmecher** [comment]
@bilalelkhouly, your plugin probably isn't registered with the system; use the command line tool mentioned in https://forum.pkp.sfu.ca/t/ojs-3-does-not-register-custom-plugin/37282/2.

The forum was probably made invite-only due to an inrush of spammers; we do this occasionally for short periods of time. If it isn't re-opened for registration, please let me know.

Meanwhile, I'll close this issue.
