### ISSUE TITLE
[OMP] Chapter authors are not returned in the correct sequence

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#10526]
**Describe the bug**
In OMP a chapter may have multiple authors, but currently reordering these authors is not working.

**To Reproduce**
1. Login as an admin/journal manager role in OMP
2. Go to a publication which has chapters and multiple authors for a chapter (or create one by adding multiple contributors to the publication then adding them to the chapter authors)
3. In Publication > Chapters, try to reorder the authors for a chapter then click "Done"
4. See the issue where the reorder isn't saved

**What application are you using?**
OMP 3.4/main (working in 3.3).

**Additional information**
- [Forum post where the issue was reported](https://forum.pkp.sfu.ca/t/bug-report-unable-to-reorder-chapter-authors-in-omp-3-4-0-7/92260)
- The sequence is set in the `submission_chapters_authors` table

**PRs:**

- OMP 3.4: https://github.com/pkp/omp/pull/1744
- OMP 3.4: https://github.com/pkp/omp/pull/1745
- OMP main: https://github.com/pkp/omp/pull/1754

**Comment by kaitlinnewson** [comment]
The reordering is saving the `seq` values in the `submission_chapter_authors` table correctly, but they are not being retrieved in that sequence order when `getAuthors()` in `classes/monograph/Chapter.php` is called.

**Comment by nils-stefan-weiher** [comment]
Sorry, I stumbled upon this bug in our installation.

I fixed it locally with the following code:

```
diff --git a/classes/author/Collector.php b/classes/author/Collector.php
index b9baae3fd..20542364f 100644
--- a/classes/author/Collector.php
+++ b/classes/author/Collector.php
@@ -14,6 +14,7 @@
 namespace APP\author;
 
 use Illuminate\Database\Query\Builder;
+use Illuminate\Database\Query\JoinClause;
 
 class Collector extends \PKP\author\Collector
 {
@@ -41,14 +42,16 @@ class Collector extends \PKP\author\Collector
     {
         $q = parent::getQueryBuilder();
 
-        $q->when($this->chapterIds !== null, function ($query) {
-            $query->whereIn('author_id', function ($query) {
-                return $query->select('author_id')
-                    ->from('submission_chapter_authors')
-                    ->whereIn('chapter_id', $this->chapterIds);
+        $q->when($this->chapterIds !== null, function (Builder $query) {
+            $query->join('submission_chapter_authors as sca', function(JoinClause $join) {
+                $join->whereIn('sca.chapter_id', $this->chapterIds)
+                    ->whereColumn('a.author_id','sca.author_id');
             });
+            // Use the order specified by the submission_chapter_authors table,
+            // to ensure that the order of authors reflects the order from the manually sorted chapters grid
+            $query->orders = null;
+            $query->orderBy('sca.seq');
         });
-
         return $q;
     }
 }

```

Should I open a PR?

**Comment by kaitlinnewson** [comment]
Hi @nils-stefan-weiher, a PR against the stable-3_4_0 branch would be great!

**Comment by nils-stefan-weiher** [comment]
There you are :arrow_up:  :+1:

**Comment by bozana** [comment]
Hi @nils-stefan-weiher and @kaitlinnewson, this is a little bit more complicated:
Actually, we allow the filtering by several `chapterIds`, which would make this SQL not work correctly in case we would like to get authors for 2 or more chapters, because the `seq` in `submission_chapter_authors` is always per chapter.
I see we always filter only by one chapter, so maybe it would be best to change it to be so:
`public $chapterId` is an `int` (and not `array`)
and:
```
public function filterByChapterId(?int $chapterId): self
{
$this->chapterId = $chapterId;
return $this;
}
```
Also all calls of the old `filterByChapterIds` would need to be changed accordingly.

Else, if we would like to allow the filtering by several chapter IDs, we would need to do `ORDER BY sca.chapter_id, sca.seq`. But I do not think such a filtering would make sense. Also we would need to differently handle the list of authors returned -- for example it could be several occurrences of one and the same author... So I would prefer the first solution for now.

What do you think?

p.s.
When looking into this issue, I found another issue, s. https://github.com/pkp/pkp-lib/issues/10570. Author object contains the `seq` form the authors table, which is the sequence for a publication. Thus when we are looking for and get a chapter authors we would need to be cautious regarding the author `seq` data.

**Comment by nils-stefan-weiher** [comment]
Hi @bozana ,

I dont remember there being and extra seq for chapter contributor ordering.

How would this work?

**Comment by nils-stefan-weiher** [comment]
Ah sorry, the sequence is in the table `submission_chapter_authors` thats exactly what is used in the code for the fix.

What is the issue with the Author sequence for the publication itself? They should not be related.

**Comment by bozana** [comment]
Hi @nils-stefan-weiher, yes this another issue is not related to this one -- I just thought I will make a not here as well. -- At few other places in the code we filter by chapter but then use author->getData('seq') which is the `seq` from the DB table `authors`. -- So nothing to be handled here...

**Comment by kaitlinnewson** [comment]
Hi @nils-stefan-weiher and @bozana, I've created a new PR for review which incorporates the original fix and suggested modifications (I wasn't able to push commits to the other PR due to permissions):

- https://github.com/pkp/omp/pull/1745

**Comment by bozana** [comment]
Thanks @kaitlinnewson and @nils-stefan-weiher! The PR for 3.4 is merged and can be cherry-picked to main...

**Comment by kaitlinnewson** [comment]
Cherry-picked to main and merged, closing.
