### ISSUE TITLE
Split review reminder emails to separate request and review reminders

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1054]
See http://forum.pkp.sfu.ca/t/different-templates-for-automated-review-request-reminder-and-automated-review-reminder/4540
Pull request: https://github.com/pkp/ojs/pull/701

**Comment by bozana** [comment]
@asmecher, I think you should also add those two email templates into registry/emailTemplates.xml

**Comment by asmecher** [comment]
Oh -- let me take a look.

**Comment by asmecher** [comment]
Added. Thanks, @bozana.

**Comment by alonsoj** [comment]
Hi @asmecher,
since update to 2.4.8 my ojs is sending REVIEW_REQUEST_REMIND_AUTO_ONECLICK  mails empty. This happens when i activate in Setup -> Step 2 the options Reviewer Reminders and Enable one-click reviewer access.
I think REVIEW_REQUEST_REMIND_AUTO_ONECLICK entry should be on email_templates_default table. Now is only on email_templates_default_data.
Greetings

**Comment by bozana** [comment]
Yes, apparently a wrong name sneaked into the registry/emailTemplates.xml: REVIEW_REQUEST_REMIND_ONECLICK instead of REVIEW_REQUEST_REMIND_AUTO_ONECLICK

**Comment by fgnievinski** [comment]
related issue: #562
