### ISSUE TITLE
[OMP] some emails have placeholders unreplaced

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1099]
For example, when thanking a reviewer, the reviewer receives this email:
```
The following message is being delivered on behalf of {$contextName}.

________________________________________________________________________


{$reviewerName}:
 
 Thank you for completing the review of the submission,
"{$submissionTitle}," for {$contextName}. We appreciate your contribution to
the quality of the work that we publish.
 
 {$editorialContactSignature} 
 ________________________________________________________________________
 {$contextName}



________________________________________________________________________

{$contextName}
```
It appears that `ThankReviewerForm\execute()` never performs substitution on the body of the email. I’m not sure whether `execute()` should be changed, or if the call should be replaced by `send()`.

**Comment by asmecher** [comment]
Thanks, @crism -- did you see this with any other emails? I suspect it's a one-off.

**Comment by crism** [comment]
That was the only one that jumped to our attention… haven’t done a thorough audit, though.

**Comment by asmecher** [comment]
OK! We'll be testing emails over the next couple of weeks, too -- they haven't received much attention. Please file anything else you spot separately. Thanks for contributing!

**Comment by selwyntcy** [comment]
@asmecher May I ask for direction in email variable handling?

For the above commit 81f4522 on `ThankReviewerForm`, the email variables are resolved just before sending, but not passed to TinyMCE as `FBV_variables`.

But for `EditorDecisionWithEmailForm`, the variable `contextName` got resolved and passed to TinyMCE, while the others are passed as locale strings as placeholders.

Yet, for `ReviewerForm`, all variables are passed as locale strings only.

Should I work on resolving all variables, if possible, before passing them to TinyMCE?

**Comment by asmecher** [comment]
@selwyntcy, the ability to add tags that TinyMCE can work with is relatively new so it hasn't been rolled out everywhere. There's currently a mix of approaches.

Many email variables can be replaced before the email template is presented to the user, as we already know what's going to go into them. I'm ambivalent about whether that's better than exposing them through FBV_variables so that TinyMCE knows how to work with them. Either approach is OK.

In some cases we can't replace variables before showing the email template to the user, such as when there's a due date selector on the same form as the email text that includes the due date. In that case, we need TinyMCE to be informed of these so that the user doesn't see `{$someVariableName}`.

In some cases things simply need fixing, such as anywhere you see `{$someVariableName}` as an end user.

In cases where you do work with TinyMCE, note that what you present to the user can't always be exactly what goes out in the email message. Think again of the due date field. In that case the variable contents you tell TinyMCE about will be something like "Due Date", and when you actually replace the variable with a value before sending, it'll be the actual date, e.g. 2016-02-05.

Does that help?
