### ISSUE TITLE
DOI suffix required?

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1108]
Just flagging this up for someone familiar with DOIs to take a look. I'm getting a required field error on the suffix, but there's no required indicator. And if it's required, I'm not really sure why that radio button is there. The text seems to indicate it's not required.

![doi-suffix-required](https://cloud.githubusercontent.com/assets/2306629/12748137/3e3707b4-c9a0-11e5-9e66-66ecd4824649.png)

**Comment by bozana** [comment]
Hi @NateWr,

The form validation seems not to work quite correctly there: The DOI Suffix setting is required and the press manager can choose one of the 3 radio button options for that. If the first radio button is chosen than the input field from your image should be required i.e. not empty. I think that this validation is happening in the javascript -- not sure if it's possible to solve it differently, with the form instruments.
Does this helps a little bit? I am familiar with DOIs in OJS and it should be similar here too... so I would be glad to help... :-)

**Comment by NateWr** [comment]
Ah, I didn't even realize these were all part of the same field:

![selection_081](https://cloud.githubusercontent.com/assets/2306629/12749298/8cc457f4-c9a7-11e5-9c7f-d94a215e6985.png)

I think you're right that our form validation isn't that smart. I'd suggest that instead of requiring the field, we just use the default syntax if it's empty.

The actual form layout needs some work. It's a real wonder this one, both visually and under the hood. But I suppose at least for now we should aim to make it look more like this:

![selection_082](https://cloud.githubusercontent.com/assets/2306629/12749413/64705e64-c9a8-11e5-84c0-7eceaf1e0178.png)

If you can do any of this that'd be great!

**Comment by bozana** [comment]
OK, I'll try... :-)

**Comment by bozana** [comment]
Hi @NateWr 

This is what I've managed:
A) Every radio button is in a form section i.e. with a little bit more space between them:

![doisettingsformbiggerspaces](https://cloud.githubusercontent.com/assets/378421/12765637/dc00ce80-c9ff-11e5-8da8-42ae1de96ece.png)


B) The radio buttons are in one form section and input field in another. The input field has to be in a separate section because also everything else in that section will get red, if empty when validating -- this is how those forms validations work. 

![doisettingsform](https://cloud.githubusercontent.com/assets/378421/12765705/372fdddc-ca00-11e5-85b8-5d54b050b5f4.png)


C) Eventually I could put the input field and the last radio button in one section -- for them both to be closer -- then just those both will get red:

![doisettingsformbiggerspacers2](https://cloud.githubusercontent.com/assets/378421/12765907/22793a68-ca01-11e5-9561-119f8495413b.png)


I've only put the old description under the input field, i.e. without "for publication formats" -- not to have to translate it again and because it will probably be different when other input fields come, for other objects (e.g. books, files).

OK so? What solution do you prefer, if any? :-)

**Comment by NateWr** [comment]
Good work @bozana. The FBV can be a nightmare to work with for things like this. I'd say C is probably best. What do you think?

**Comment by bozana** [comment]
@NateWr, agree and made a pull request... :-)

**Comment by asmecher** [comment]
Merged; thanks, @bozana.
