### ISSUE TITLE
[OMP] add support for Web-hosted publication formats

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1123]
Currently, an OMP catalog entry lists electronic versions downloadable through OMP, and physical objects that can be sent by other means. We would like to add a third distribution channel: content hosted on the Web, not within OMP. For example, a multimedia Web-native version of a book, or just the HTML edition but hosted by the publisher.

**Comment by crism** [comment]
Currently, the distinction between downloadable and physical formats is determined by the `physicalFormat` property of `PublicationFormat`, a Boolean.

One possibility would be to change that to an enumerated property (downloadable, physical, Web-native). This is obviously disruptive, but future-looking.

The other possibility would be to add another Boolean; much less disruptive, but sets a pattern for proliferation if new kinds of formats are desired in the future.

The additional fields can be used for the URL(s) of the hosting. (Another design decision would be whether a Web-native format has exactly one URL, or may have more; I am inclined to say exactly one.)

**Comment by asmecher** [comment]
There's a similar concept in OJS 2.4.x called "remote galleys"; @bozana can probably point you to some of the OJS 2.x codebase pretty easily if that helps.

**Comment by crism** [comment]
@asmecher, that sounds like a pretty good start. Thanks.

**Comment by bozana** [comment]
@crism, I found my older post on this topic, maybe it could help: https://pkp.sfu.ca/support/forum/viewtopic.php?f=40&t=10847&hilit=remote+galley+omp

If you would like to see it in OJS 2.4.x, you could take a look at the following:

1. option for the editor:
The new form filed for editors to create a remote galley is in the editing > layout part of an article, s. templates/sectionEditor/submission/layout.tpl
This new form field is then of course considered in the appropriate handler and form classes, e.g. for galleys: 
-- classes/submission/form/ArticleGalleyForm.inc.php
-- pages/sectionEditor/SubmissionEditHandler.inc.php

2. new DB column, e.g. in the table article_galleys
It is defined in dbscripts/xml/ojs_schema.xml, and considered in classes/article/ArticleGalley.inc.php and classes/article/ArticleGalleyDAO.inc.php

3. appropriate handler and form classes -- s. 1. above

4. for the reader:
Above all the redirecting to the other URL in pages/article/ArticleHandler.inc.php

If any further question or if I could help somehow, don't hesitate to ask...

**Comment by crism** [comment]
Thanks, @bozana; this is helpful. I’m not looking at adding this to OJS 2.4.x, though; rather to the latest-and-greatest OMP (not-yet-1.2), which shares code with OJS 3.0.

**Comment by NateWr** [comment]
Sorry for arriving late to the party on this one. Looking at https://github.com/pkp/ojs/pull/787 was the first time I noticed the new support for remote files.

I have some UX concerns with how this is presented in the workflow and I'd like to at least have a discussion and set down a roadmap for working them out. The publication formats represent the most complex part of our workflow so we should really be careful when we introduce more complexity to this part of the process.

## Add publication format form

![remote-content-form](https://cloud.githubusercontent.com/assets/2306629/13664591/1bdfa212-e6a0-11e5-8eac-26b32969f754.png)

The new field introduces confusion to the form by presenting a form field that's unrelated to most use-cases. Users who would never understand what the field is for will be uncertain if they are meant to enter any data.

I'd like to see "Remotely-hosted content" as an option under "Publication Format". When selected, the URL field appears and the Physical Format option goes away. Otherwise the URL field is hidden.

I appreciate this might muddy the waters a bit, since the Publication Formats correspond to metadata types. But I wonder about the significance of metadata with remotely hosted content (see below). Either way, I'd suggest we handle this ourselves under the hood, with Remotely Hosted a special type.

## Files can be added to remotely hosted publication formats

![remote-content-fileds](https://cloud.githubusercontent.com/assets/2306629/13664712/d5f6d42c-e6a0-11e5-8d8a-e8fdeab32c45.png)

This creates an ambiguity which can easily compound the problems with the uncertainty in the form. Users who don't fully understand the purpose and meaning of remotely hosted formats will be confused when files they've added don't appear.

We should remove the Upload/Select Files links, as well as the link in the Availability column, for remotely hosted publication formats. We should also ensure that when another publication format has had files added it to it, and is then switched to remotely hosted, these files do note appear. This way the UI reinforces the meaning of the remotely hosted format.

## Do remotely-hosted formats benefit from metadata?

![remote-content-meta](https://cloud.githubusercontent.com/assets/2306629/13664838/4cc9cabe-e6a1-11e5-8984-25693b5e1e5c.png)

My understanding is that we only present the metadata on each file's own URL, due to Google Scholar requirements. Remotely hosted content obviously does not get it's own URL in our system.

Does the metadata have any value in this context? Is it displayed anywhere?

If not, then we should not include tabs for remotely hosted publication formats in the Catalog Entry tab.

**Comment by bozana** [comment]
Yes, this is not easy... Here maybe some more points for consideration:
When I was reviewing/testing the changes I thought that maybe user/editor would like, for some reason, to have the publication file in the system (so that e.g. the editorial team can do something with it, e.g. to track the changes/revisions) but not to show it to the readers. Thus, I thought it is maybe good to leave this decision/control to the editors.
In OJS, the remote files were treated in the same way as the normal files, just that they lay somewhere else (for whatever reason, e.g. the back issues on an old web page). I.e. the metadata are kept in OJS and also distributed via e.g. OAI. Also the OJS URL is used and distributed -- it that case the OJS would just redirect user to the given  remote URL.

**Comment by crism** [comment]
@NateWr, I’m completely down with changing the editing interface; I’m not terribly comfortable with AJAXy dynamic UIs, and did the minimum to get it working. IMO, that’s a separate issue, but I don’t have a strong opinion on that.

As for metadata—I wonder. From a discoverability perspective, a Scalar instance might do a good job of providing that, but a hand-crafted Web app or Flash animation might not. I’d err on the side of allowing it.

**Comment by bozana** [comment]
One more point to consider: Is it imaginable to use the remote URLs for linking to books on amazon or book-on-demand/print-on-demand or another seller? Maybe in that case to leave the format list as it is but to add additional checkbox "Remotely-hosted content"...

**Comment by NateWr** [comment]
Thanks @bozana and @crism. I suppose the metadata should stay then.

I still think we should disable file management for remotely-hosted formats. If editors want to track changes, this isn't really a great way to do that since we can't enforce any kind of 1-to-1 relationship between the files in the system and the remotely-hosted item.

The few who really want to store the file in OJS can use other workarounds like creating a private publication format. But I don't think we should cater specifically to it, both because it becomes a *de facto* recommendation and because it adds complexity and ambiguity for the other 90% who won't use it.

**Comment by crism** [comment]
I’d be fine with no files for remotely-hosted content. I can kind of see using that for revision tracking of that remote content, but that be done via other kinds of files, and @NateWr is right that some users will feel they ought to put something there if there’s a place for it.

**Comment by bozana** [comment]
I agree... :-)

**Comment by bozana** [comment]
@NateWr, I removed the "Upload File" and "Select Files" links, if the publication format has a remote URL. Would this be OK so:

![remotepubformats](https://cloud.githubusercontent.com/assets/378421/13762488/9c618872-ea3f-11e5-9717-cf321de943e5.png)

I've also taken a look how to remove the availability action, but it seems not to be that easy :-( The column has to stay, because of the other publication formats that could need it. It uses statusCell.tpl which always displays something (i.e. a checkbox). Eventually, I could add a new status "remote" or "showNothing" to that template, but... I am not sure how to solve this best :-( Do you maybe have an idea? :-)
THANKS!!!

**Comment by crism** [comment]
@bozana, I like having the “Available” checkbox there—if the remote resource is unavailable for some reason, it would be easy for a manager to disable it in the catalog.

I do wonder about the “No Items” listing… I worry that a user might spend some time trying to figure out how to add items.

**Comment by NateWr** [comment]
@bozana, looks great! I agree with @crism about that *No Items* text. Kind of fighting against grids at this point but it'd be great to get rid of that.

I know that the Participants grid does something special to hide things when no items are present. Maybe there's a trick there?

And yes, @crism is right after all. Having that Available link on the right might not be so bad.

**Comment by bozana** [comment]
OK @NateWr and @crism. I will then leave the Available column as it is and will try to figure out how to remove, hide or solve the "No Items" row/text.
I believe one more question is still left from this issue: what to do with the remote URL input field, so that it is more user friendly?
THANKS A LOT!!!

**Comment by crism** [comment]
I like an additional checkbox, next to “Physical format,” which says, “Remote content,” or something like that. The URL entry area would only be displayed if that box were checked.

**Comment by bozana** [comment]
@NateWr, shall there maybe be another text instead of "No Items", e.g. "Remotely hosted content - no items". This would help keep the same height for this white row. Else, if no text is there, then the row height is much smaller. Or do you know another trick? :-) And the white row should be there, I believe -- for two gray rows not to glue with each other. THANKS!!!

**Comment by NateWr** [comment]
@bozana What about adding text that links to the external source, like:

This item is [remotely hosted](http://example.com/where-the-file-is).

**Comment by bozana** [comment]
@NateWr, for that I would need to give the remoteURL as a parameter to the translation key and those grid empty row texts don't consider the parameters at the moment, so I would have to adapt them in general, for any kind of parameter. I am not sure if this is that much necessary, but If you say, no problem, I would try to do that :-) Maybe just to write "This item is remotely hosted", without the link and I could try to put the link behind the format name in the gray row above? THANKS!!!

**Comment by bozana** [comment]
I added the Javascript that takes care of hiding and showing the remote URL input field:

![hideremoteurl](https://cloud.githubusercontent.com/assets/378421/13814537/ef94fcd4-eb86-11e5-82fd-8fb007147135.png)

![showremoteurl](https://cloud.githubusercontent.com/assets/378421/13814543/f5bf0ece-eb86-11e5-80de-2a5e316c48f8.png)

If everything OK (also the solution for the grid above), I could make the PR...
THANKS!!!

**Comment by crism** [comment]
@bozana, I’m OK with the grid and the checkbox thing.

**Comment by bozana** [comment]
Thanks a lot @crism! I will then still wait what @NateWr says, before making the PR.

**Comment by NateWr** [comment]
Although it's a bit clearer, all we've really done is add an extra field. We still have the original problem whereby the majority of users will be asked to tick or not tick a box for something they're not really sure about.

I'd still really like to see Remotely Hosted added as an option to the Publication Format select field if possible. That way it's clear that this is effectively a *different kind of format* rather than an option you tack on to other formats.

**Comment by bozana** [comment]
@NateWr, I am not 100% sure, but I think that we would need both, the current publication format (ONIX data) because of the metadata, that we want to maintain and whether it is a remotely hosted content.

**Comment by NateWr** [comment]
*/me raises fist in the air* **NOOOOOOOOOOOOOOOO**

Ok let's go with what you've got, but can you update the checkbox label to be a bit more descriptive, like "This format will be available at a separate website"

**Comment by bozana** [comment]
What does this first sentence from you mean? Hihihihi :-) Sorry for my English... :-\

**Comment by NateWr** [comment]
Sorry, that first sentence is just voicing frustration that a clean UI solution doesn't quite support the feature set required. :)

**Comment by bozana** [comment]
A OK :-) Sometimes I am not sure what exactly something means... :-P Thanks! OK, I''ll then change the  checkbox label as you said....

**Comment by bozana** [comment]
Here are the PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1280
omp: https://github.com/pkp/omp/pull/245

This feature could then also be migrated to OJS 3.0...

**Comment by asmecher** [comment]
Merged, thanks, everyone! I've moved the issue over to OJS 3.0 so it can be ported before closing.

**Comment by bozana** [comment]
Here are the PRs for porting the feature to OJS 3.0:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1370
omp: https://github.com/pkp/omp/pull/277
ojs: https://github.com/pkp/ojs/pull/819

The issue can then be closed, I believe...

**Comment by crism** [comment]
Nice—thanks, @bozana!

**Comment by asmecher** [comment]
Looks good, thanks!
