### ISSUE TITLE
[OJS] Add highlighting to author's active submissions list

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#1128]
Provide additional details to authors re: the state of their submission while it's under review. This should reduce the number of emails authors send to editors to ask about their submission.

We can re-use the states and highlighting available to editors in their submission listing, i.e.
- A Reviewer has been assigned but not notified by email
- All Reviewers have returned with their comments, but no decision is recorded
- Author has uploaded a revised manuscript
- Reviewer is overdue to confirm peer review invitation
- Reviewer is overdue to complete review

**Comment by mfelczak** [comment]
This may be a good candidate for inclusion into OJS 3.0 as well.

@NateWr, any thoughts on status-based highlighting for the author's submission listing?

**Comment by NateWr** [comment]
@mfelczak I'm in favor of providing status information in the submission grid. I'm not a fan of coloring the background of a row to do this, because:

1. Not accessible to the fully or partially color blind.
2. It's really difficult to find a good set of light colors that are distinct enough.

Also, we have too many states for a coded system of colors or icons. A novice user will need to cross-reference a color or icon with a meaning. I'd rather just go with text descriptions.

Replacing the Stage column for authors, which provides editors with a quick-link to the workflow and a high-level view of where it's at, could be the best approach. We'll need to think about what to do for reviewers or custom roles.

It's tough to slot larger snippets of content like this into our grids in a sensible way. It may take some strategizing to figure out the best way to do this.

**Comment by NateWr** [comment]
@mfelczak Most of these states are now displayed to an author in their submissions list. Is there anything here you'd like to keep as a feature request? If so, go ahead and add it to the project I created for the submissions list: https://github.com/pkp/pkp-lib/projects/8

**Comment by mfelczak** [comment]
Closing this issue, thanks @NateWr!
