### ISSUE TITLE
[OJS] .git file in ojs 2.4.8 patch (plugins/reports/counter/classes/COUNTER)

### ISSUE THREAD

**Issue by bricas** [pkp/pkp-lib#1129]
Just downloaded the patch from 2.4.7.1 to 2.4.8 and tried to commit the changes to our git repo and hit an issue with the "plugins/reports/counter/classes/COUNTER" directory, and I believe this is why:

```diff
--- ojs-2.4.7-1/plugins/reports/counter/classes/COUNTER/.git    1969-12-31 16:00:00.000000000 -0800
+++ ojs-2.4.8/plugins/reports/counter/classes/COUNTER/.git      2016-02-05 17:01:44.324927925 -0800
@@ -0,0 +1 @@
+gitdir: ../../../../../.git/modules/plugins/reports/counter/classes/COUNTER
```

**Comment by asmecher** [comment]
@bricas, I've added an exclusion to our build script for that .git file, which is showing up because we're managing that piece of code as a submodule. But generally speaking, why not manage your git repository as a fork of our repositories, so you can use the normal rebase tools rather than applying the patch?

**Comment by bricas** [comment]
@asmecher Thanks for fixing that up.

If i ever get the round tuits required, i'll definitely switch to a straight-up fork.
