### ISSUE TITLE
Reconsider language and flow around inviting new reviewers

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1146]
From #1127, against `HEAD`:

Assigning a reviewer is confusing; it’s not immediately obvious that the Search By Name searches among the listed reviewers, and that the “Create New Reviewer” and “Enroll Existing User” links should be used. (And even then, which is appropriate? Unless the user has memorized the list of users, it’s hard to know. A more linear or wizard-ish workflow would help.)

**Comment by NateWr** [comment]
Hi @crism, did you see this issue? https://github.com/pkp/pkp-lib/issues/983

It looks like it was merged Jan 27 so it's not clear if your comments related to the before or after, but a lot of improvements were made.

Can you double-check on current master and close if the problem has been resolved. If it's still there, can you provide a bit more detail?

**Comment by crism** [comment]
@NateWr, this feedback was indeed after #983.

Part of the problem is that we did not have any users already in the reviewer group, so the empty list was confusing. That is a problem each press will only encounter once, I suppose.

I would suggest that “Create New Reviewer” is very system-centric terminology: while we are creating a new reviewer artifact within the data model, we are not, in fact, creating a new reviewer; we are inviting a person who already exists to become a reviewer. “Invite new reviewer” might be better, or “Invite new user to review.”

Likewise “Enroll Existing Reviewer”; we’re adding an existing user to reviewer status and association with this project, but an editor doesn’t necessarily think that way. In fact, I’d consider combining those; select among the existing known, eligible reviewers, or “invite new reviewer”. This would prompt the user to search the list of existing users first, and if not found, then to invite by e-mail.

How does that sound?

**Comment by NateWr** [comment]
What do you think of changing "Search by name" to "Search reviewers by name"? That might help a bit with the ambiguity. Ideally, if no reviewers were enrolled, it might just hide the grid altogether.

I'm not entirely convinced about the other wording changes you recommend. I think "Invite new reviewer" suffers from the same ambiguity of "Create new reviewer". I don't really have a better idea at the moment, but we're conducting some user tests of this stage now so if there's really confusion it should surface in those tests.

Regarding the second half of your suggestion, to combine the create/enroll interfaces. This is tricky and would require quite a bit of brainstorming (and technical work) to get going right. I'm not opposed to the idea, but it's definitely not going to make OMP 1.2 and I'd be tempted to wait and see what happens with user tests.

We're trying to implement a clearer priority system based on those tests so that we focus our efforts on those areas where we can have the greatest impact.

But I'll dump this quick screenshot here which might chart a path forward when we revisit this:

![selection_001](https://cloud.githubusercontent.com/assets/2306629/13492166/6139276a-e12e-11e5-9033-b60286d432c1.png)

The idea is that the checkbox would open up the initial grid to all users if desired, and if a user was selected that wasn't already a reviewer, it would automatically enroll them. That might obviate the need for the "Enroll" link and that might then resolve the ambiguity between the two links (create/enroll).

**Comment by crism** [comment]
@NateWr, I like the “Search Reviewers by Name” wording and the checkbox. I agree that postponing the other stuff makes sense.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
