### ISSUE TITLE
Broken reports pages

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1265]
The reports have a few issues:
- [x] In OJS, the custom report generator has a dynamically loaded container that fails to load and prints an error<sup>1</sup>.
- [x] In OJS, the Articles Report link causes a fatal error<sup>2</sup>, as does the Review Report<sup>3</sup>.
- [ ] The custom report generator could use some work in tidying up the form layout and styles for clarity.

The UX issues are in a comparatively minor part of the system, so I consider them low-priority. The other issues only effect OJS and probably need to be resolved one way or another before OJS 3.0.

<sup>1</sup> The error is:

```
[Mon Mar 14 13:24:16.019686 2016] [:error] [pid 10145] [client 192.168.0.8:38728] ojs2: Invalid metric type., referer: http://192.168.0.8/ojs/index.php/publicknowledge/management/tools/reportGenerator
```

<sup>2</sup> The error is:

```
[Mon Mar 14 13:27:36.945436 2016] [:error] [pid 10645] [client 192.168.0.8:38765] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/ojs/classes/classes_workflow/EditorDecisionActionsManager.inc.php' (include_path='.:/var/www/html/ojs/classes:/var/www/html/ojs/pages:/var/www/html/ojs/lib/pkp:/var/www/html/ojs/lib/pkp/classes:/var/www/html/ojs/lib/pkp/pages:/var/www/html/ojs/lib/pkp/lib/adodb:/var/www/html/ojs/lib/pkp/lib/phputf8:/var/www/html/ojs/lib/pkp/lib/pqp/classes:/var/www/html/ojs/lib/pkp/lib/smarty:.:/usr/share/php:/usr/share/pear') in /var/www/html/ojs/lib/pkp/includes/functions.inc.php on line 25
```

<sup>3</sup> The error is:

```
[Mon Mar 14 13:29:05.771518 2016] [:error] [pid 10207] [client 192.168.0.8:38780] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/ojs/classes/submission/reviewAssignment/ReviewAssignment.inc.php' (include_path='.:/var/www/html/ojs/classes:/var/www/html/ojs/pages:/var/www/html/ojs/lib/pkp:/var/www/html/ojs/lib/pkp/classes:/var/www/html/ojs/lib/pkp/pages:/var/www/html/ojs/lib/pkp/lib/adodb:/var/www/html/ojs/lib/pkp/lib/phputf8:/var/www/html/ojs/lib/pkp/lib/pqp/classes:/var/www/html/ojs/lib/pkp/lib/smarty:.:/usr/share/php:/usr/share/pear') in /var/www/html/ojs/lib/pkp/includes/functions.inc.php on line 25
```

**Comment by beghelli** [comment]
@NateWr, for the first error, can you check if you have the folder plugins/reports? Without it the reports plugin category will not initialize and the UsageStats plugin will have no chance to register its report plugin, the one that implements the default OJS metric type.

**Comment by NateWr** [comment]
Yeah I have `/plugins/reports/` in my OJS folder and it includes four directories: `articles`, `reviews`, `subscriptions` and `views`. 

I do not have a `/lib/pkp/plugins/reports/` directory.

**Comment by beghelli** [comment]
Is your database old? I committed the stats work a few months ago, maybe you need to upgrade your database to make sure the UsageStats plugin is installed and enabled. My installation using OJS master opens the report generator with no problem.

**Comment by NateWr** [comment]
Could be the case. I haven't updated the db on my OJS installation for a while.

**Comment by asmecher** [comment]
Fixed the criticial stuff, leaving the UI/UX stuff for post-3.0.

**Comment by mxbees** [comment]
I don't think that the UI/UX stuff should be considered so low-priority. As a user, I'm finding the custom report generator to be a mystery meat machine. 

At the moment, my main UI issue is that the date range selects a range of article published, rather than a the number of downloads for a period of time. As far as I can tell, generating such a report is impossible via the UI. Which is kind of a problem, particularly since my institution has already started using OJS3 in production, since we thought it was supposed to be a relatively stable and complete thing. And one of the most important stats that we collect is article downloads by month. Its information needed for journals applying for SSHRC support. 

I'm not sure why the custom report form changed from being able to select a date range in 2x to selecting a range of articles, but surely this can be returned?

**Comment by bozana** [comment]
Hi @mxbees, could you please give me some more information -- I do not totally understand it :-\
What do you mean with "date range"? I do not totally understand this: "At the moment, my main UI issue is that the date range selects a range of article published, rather than a the number of downloads for a period of time.". Also this: "I'm not sure why the custom report form changed from being able to select a date range in 2x to selecting a range of articles, but surely this can be returned?" :-\
How were you exactly using the custom report generator earlier and now?
Thanks!

**Comment by mxbees** [comment]
@bozana 

![ojs2](https://cloud.githubusercontent.com/assets/5183702/26202924/2e99310e-3ba7-11e7-8e76-032173e1b25e.png)

![ojs3](https://cloud.githubusercontent.com/assets/5183702/26202927/31ae9604-3ba7-11e7-8309-58d57035a6a0.png)

**Comment by bozana** [comment]
@mxbees, thanks a lot! I think I got it now :-) I will take a look... and if I have some further questions I will come back to you again...

**Comment by bozana** [comment]
@mxbees, hmm.... I've just tested the custom report, and those dates do consider the access date and not the article publish date. Thus, are you sure, that it is different for you? 
I have an article published in August 2016 and I have chosen to report the statistics after April 2017 and before May 2017 and I got all the usage numbers for that articles files in April 2017. This is correct, right?

**Comment by mxbees** [comment]
@bozana I've done a bunch more digging and I think I understand what is happening. And, yes, the title/label for the date ranges are counter-intuitive.

**Comment by bozana** [comment]
@mxbees, so it is working for you now too? 
I'll see to change the labels more properly... 
THANKS!

**Comment by asmecher** [comment]
@bozana, is there anything you'd like to prioritize for 3.1? I'm leaning towards deferring to 3.2.

**Comment by bozana** [comment]
@NateWr wanted to improve the layout and styles here, else, the report is working, so I believe it can be deferred.

Maybe one thing to consider now: How could we improve the  text "Published After" and "Published Before" (s. the report form image above), so that it is more intuitive for users? -- If the user for example wants to see the access in April 2017, she/he has to choose Published After =  April 2017 and Published Before = May 2017 i.e. the first date is included and the second excluded i.e. for both dates the 1st of the chosen month is considered. Or shall we leave it as it is for now? THANKS!!!

**Comment by bozana** [comment]
@NateWr, the later is the case -- it reports download activity between those dates... THANKS!!!

**Comment by bozana** [comment]
@NateWr, I think we could only change these two labels for 3.1 and deffer the rest to 3.2. What do you think? Could you maybe made a suggestion how to rename those two labels and I will do it? :-)

**Comment by bozana** [comment]
Hmmm... I think "From" and "Until" would be OK, right?

**Comment by NateWr** [comment]
@bozana Yeah that sounds good. "From" and "Until" will work.

**Comment by bozana** [comment]
PR for date selection label improvement: https://github.com/pkp/pkp-lib/pull/2779

**Comment by NateWr** [comment]
Closing as this is very old. File a new issue if any further improvements are needed.
