### ISSUE TITLE
PKPMailTemplate populates misleading "From" field in template display

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1310]
In OJS 2.4.x, the "From" field in the Notify Users form and the Editor Decision form was never updated after SPF enhancements.  We are now setting the From address to the Journal Manager or Site Administrator, so the "From" in these forms really should represent the Reply-To address as the "sender".

To reproduce, login as Editor and select "Notify Users".
Expected result: uneditable "From" represents the Editor's address.
Actual result: uneditable "From" represents the Journal Manager's address.

The cause is:
https://github.com/pkp/pkp-lib/blob/3f83345669f692c0fa57063e54bbe67d5a2f536a/classes/mail/PKPMailTemplate.inc.php#L183

**Comment by asmecher** [comment]
@jnugent, could you take a look at this one?

**Comment by jnugent** [comment]
@ctgraham is correct.  Due to recent changes, we need to leave the From: alone.  However, Clinton -- many journals were complaining about having a From: address from the editor or the administrator,  because it is mixing the name of the actual person sending email and the email address of the administrator.  This ended up being really confusing to some journals because although the reply-to is correctly set, the mixed From combination may lead to address book corruption.

**Comment by ctgraham** [comment]
I'm not quite following the "mixing the name of the actual person sending email and the email address of the administrator".  Isn't the From header consistently the name and email of the Principal Contact, and the Reply to the name and email of the "actual sender"?

Note that this PR doesn't affect any SMTP headers.  It just clarifies the form display.

**Comment by jnugent** [comment]
The From header should not be the principal contact.  It's become a problem for a lot of journals - when you scan your email inbox all of the messages are from the principal contact.   We had to back out of this fix for a Nordic installation, and now we leave the From header alone in all cases, and just set the return-path to the principal contact if the config directives are turned on. 

If you look at this change:

https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_6/classes/mail/Mail.inc.php#L413

Conceivably, this mixes two names.  It uses the display name getReplyTo and the address from the envelope_sender.  That is probably not right.

In any case, I think your form change works though.

**Comment by ctgraham** [comment]
Is the problem just with the `force_default_envelope_sender` option, or with our SPF strategy of using the "From" as the SPF-validated address generally?  Per your [fix](https://github.com/pkp/pkp-lib/commit/7af3bf24a2e24f8e2f4afcde4750d7b16d9b80f7), does the 'return-path' header trump the 'from' header from an SPF perspective?

**Comment by jnugent** [comment]
Yes, it's with the force_default_envelope_sender option.  The return-path is the only thing that truly matters for SPF.   If you leave the From: header alone and set the return-path, you get the correct person@otherdomain.com via some@address.com where some@address.com is what's specified in the config file. If everything is left turned off in the config file, then OJS should leave everything alone, which assumes the server itself is correctly set up to send mail.

**Comment by ctgraham** [comment]
When you say "OJS should leave everything alone", you still mean that OJS is setting the SMTP From address to either the Journal Principal Contact or the Site Principal Contact (depending on context), and the SMTP Reply-To to the OJS user, correct?

**Comment by jnugent** [comment]
Yes, but it shouldn't do that.

**Comment by ctgraham** [comment]
So are you saying the way it should work is the following?
Always set the SMTP From to the OJS user, and to set the SMTP Return-Path to the config.inc.php setting or the Site Principal Contact, or the Journal Principal Contact (depending on context)

**Comment by jnugent** [comment]
The return-path is what SPF is going to look at.  Ideally, it is an address that is represented within the SPF for the domain.  Take Github, for example.  Email notifications that are coming to me, from you, look like this:

From: Clinton Graham <notifications@github.com>
Reply-To: pkp/pkp-lib <reply+0003565f57387d51d1eab375b4702cd6cdbc36786fc1868492cf000000011314fc7692a169ce088eda03@reply.github.com>

but:

Return-Path: <noreply@github.com>

Because of this:

Received-SPF: **pass** (google.com: domain of noreply@github.com designates 192.30.252.195 as permitted sender) client-ip=192.30.252.195;

As you can see, the SPF check is done on the return-path, not from or reply-to.  Those two are too easy to spoof and don't really count for much.

**Comment by jnugent** [comment]
Tagging @jmacgreg so he's on on this too.

**Comment by ctgraham** [comment]
@jnugent, @jmacgreg, @asmecher, I'd like to get a handle on what the future direction is for our SPF implementation.  Is this issue the place for that discussion?  In the Tech Committee call we referenced a "current GitHub Issue", and it seems this one has the most context so far.

**Comment by asmecher** [comment]
Hi @ctgraham -- I'll send out an email to survey some possible meeting times in a sec.

**Comment by ctgraham** [comment]
Superseded by https://github.com/pkp/pkp-lib/issues/1433
