### ISSUE TITLE
Browser back button issue: ERR_CACHE_MISS

### ISSUE THREAD

**Issue by emersoncpp** [pkp/pkp-lib#1351]
The error occurs when you click back button after details of an reviewer for the Reviwer Assignment function.

The browser displays: ERR_CACHE_MISS

OJS 2.4.8.0

**Comment by asmecher** [comment]
That's a Chrome error message, not an OJS/OCS/OMP/OHS one. See e.g.:
http://stackoverflow.com/questions/26515991/chrome-err-cache-miss

FYI, the [support forum](http://forum.pkp.sfu.ca/) is usually the best place to start when looking for support.

**Comment by emersoncpp** [comment]
Asmecher, It is also occurring in other browsers.

**Comment by asmecher** [comment]
I can only guess, but I suspect it's due to your browser not wanting to re-submit a form POST, which would be required in order to go back to the previous page.

If your browser permitted you to go back, POSTing the form that generated that page in the first place, then it would likely cause actions to be inadvertently duplicated, which would be bad.
