### ISSUE TITLE
Add language selection for admin backend

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1399]
I'd suggest putting it into the User Profile area.

**Comment by asmecher** [comment]
(Note: this comes from http://forum.pkp.sfu.ca/t/omp-1-2-language-selector-in-administration-interface)

@NateWr, I wonder whether the user is flipping the language back and forth frequently and expecting to stay on the same page. Having to navigate away to the profile and back again might be painful if that's the case.

**Comment by NateWr** [comment]
Hmm, maybe. I'm trying to think of what they would be doing if they were doing that, but I can't think of anything. Let's see if the forum poster says anything.

**Comment by amatsumiro** [comment]
They would be doing a huge data input.
Like one step submit in OJS or something like that in OMP.
OMP has multiple language input inside the form, but they prefer have the old way too.

**Comment by asmecher** [comment]
@amatsumiro, OJS 2.x had two language choosers: one to set the interface language, and one to set the form language. The interface language chooser was disabled on forms; the form language chooser has been replaced by having the alternate language fields pop out when the user enters them. Can you describe what the users are looking for a little further? Is it e.g. to have the "main" form element language correspond with their own first choice language rather than the journal's primary language?

**Comment by amatsumiro** [comment]
They are looking for something like this:
http://i.imgur.com/LEsUBKV.png

A selector to change the interface language, like it already works in "view interface". Everything in journal primary language until I change the language.
When I acess "management interface" omp use currently language in "view interface". If view in portuguese, management in portuguese too, If they want management in english they need back to website and chage to english, then go to management again.
Alternate language fields pop out when user enter them is a goot shot, but sometimes translation is not that good and the best way is reed it in english.

**Comment by NateWr** [comment]
@amatsumiro So that I can be sure I understand you correctly, let me describe how I understand the problem and you can tell me whether I'm on the right track.

When they are entering data into the editorial interface, they might be viewing in Portugese. But they might be presented with a field label that they don't understand. In that case, they want to switch over to English (or another language) to read the original field label.

In this case, they want quick switching of languages so that they can better understand what they're looking at, right?

**Comment by amatsumiro** [comment]
Yeah!


Exactly that!


Grato,


Tarcisio Pereira






On Fri, Apr 22, 2016 at 8:26 AM -0700, "Nate Wright" <notifications@github.com> wrote:





@amatsumiro So that I can be sure I understand you correctly, let me describe how I understand the problem and you can tell me whether I'm on the right track.

When they are entering data into the editorial interface, they might be viewing in Portugese. But they might be presented with a field label that they don't understand. In that case, they want to switch over to English (or another language) to read the original field label.

In this case, they want quick switching of languages so that they can better understand what they're looking at, right?

---

**Comment by NateWr** [comment]
@asmecher I'm not entirely opposed to a language switcher in the backend. But I wonder if this might be a good opportunity to explore plugin modularity in our backend UI. Maybe we could add hooks to add items in the top bar or in the left sidebar, then add the language switcher with a small plugin?

**Comment by asmecher** [comment]
That sounds plausible, though we're risking heading into requiring tools to e.g. administer the order of sidebar plugins in the back-end as well.

**Comment by NateWr** [comment]
My thinking is that the backend is now a developer zone -- I'm not interested in any drag-and-drop build-your-own-backend kind of world. But the hooks system used in WordPress has been a useful tool for this kind of developer-facing modularity in the backend.

The top admin bar, where we have the tasks and user login, could consist of only two hooks:

```
Admin::AdminBar::Left
Admin::AdminBar::Right
```

Then OJS itself could deposit content there using the hooks. So the site switcher would be hooked into `Admin::AdminBar::Left` and the tasks and usernav would be hooked into `Admin::AdminBar::Right`. Plugins would get equal opportunity to inject content, such as a language switcher, at-a-glance stats, quick links to the latest submissions, etc.

Using a priority system, developers would be able to manage the sort order themselves, by choosing which priority a plugin would inject it's content into the hook.

Pros: easy implementation / no template overrides (and update headaches) required / very flexible for developer needs
Cons: it can become a bit of a wild west / needs to be well-documented

Just a thought. Maybe it's not the right approach. Maybe the right approach needs to wait for after OJS 3.0. But I would like to see us look at doing modularity in the backend without having to override as many template files.

**Comment by NateWr** [comment]
I went ahead and implemented a language bar. We can talk about improving extensibility of the UI after 3.0 I think.

PRs
https://github.com/pkp/pkp-lib/pull/1491
https://github.com/pkp/ojs/pull/850
https://github.com/pkp/omp/pull/294

**Comment by asmecher** [comment]
All merged -- just trying to keep ahead of all the PRs!
