### ISSUE TITLE
Add a "Schedule for Publication" button

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1410]
On the Production stage, can we consider adding a "Schedule for Publication" button just above the Participants grid? This would trigger a modal with the Publication Metadata information.

It took me forever to find where to schedule the submission!

This would also be consistent with other stages, where the buttons above the Participants grid trigger a significant action.

It would also simplify the "Metadata" modal.

**Comment by asmecher** [comment]
Incidentally, this is one of the cases in OMP where we added a banner-style notification to guide the user towards the next step after hitting a dead-end.

Tagging @bozana, because this has implications for her work on e.g. DOIs. Scheduling is one point at which DOIs could get stamped, so there may be a need for a modal that pops up with an opportunity for modals to augment the built-in fields.

**Comment by asmecher** [comment]
@bozana, just reviewing open issues -- I think you were interested in tackling this one as a button like the other editorial decisions.

**Comment by bozana** [comment]
PR:
pkp-lib: https://github.com/pkp/pkp-lib/pull/1622
ojs: https://github.com/pkp/ojs/pull/936

**Comment by asmecher** [comment]
Merged both, thanks -- can this be closed?
