### ISSUE TITLE
[OJS] Small bug with search button

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1508]
On a fresh install of OJS the search button is ill-placed. screenshot attached
![search-button-bug](https://cloud.githubusercontent.com/assets/8665047/15774992/a51264bc-297f-11e6-88ec-839742636f40.png)

**Comment by henkela** [comment]
PS: Once a journal is added the search button is in the right position. minor bug though

**Comment by asmecher** [comment]
@NateWr, probably a layout tweak.

**Comment by henkela** [comment]
@NateWr, @asmecher 
not sure about it but min-height: 40px; for .pkp_navigation_primary should resolve this issue

**Comment by NateWr** [comment]
Thanks @hekela. This is because the site index doesn't include a primary navigation menu. I'd like to resolve this by maybe thinking about what a site index menu might contain, but if not I'll probably just adjust the height. That said, we probably need to test to see what the search actually searches in teh site index, rather than per-journal.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1637

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
@NateWr, FYI, some OJS-specific language/variable names crept into pkp-lib with this PR, resulting in the OMP search form disappearing -- see https://github.com/pkp/pkp-lib/commit/1c66ddeac93a8ff60c6144e735e870685ccf7875 for a fix (committed to master).

**Comment by NateWr** [comment]
thanks!
