### ISSUE TITLE
Misleading german translation

### ISSUE THREAD

**Issue by henkela** [pkp/pkp-lib#1509]
lib/pkp/locale/de_DE/grid.xml  grid.action.order is translated as "Bestellung", which would be the translation for 'to place an order' and not the translation of 'to sort'. The appropriate term would be "Reihenfolge". The "follow-up" grid.action.cancelOrdering "Bestellung abbrechen" should be something like "Sortiermodus beenden". 
 "Sortiermodus aktivieren" is an appropriate (field grid.action.orderItems). 
@mtub, do you agree?

Pull request will follow.

**Comment by mtub** [comment]
Hi @henkela, thanks for your review and suggestions!

I will have a look at all translation-related pull requests and issues. But I'd like to point out that we are in the middle of porting the OJS 2 and OMP 1.2 translations to the master branch of OJS (-> OJS 3) and that the files your are reviewing right now are partly outdated. In order to spare you some time it might be better to wait for the translation to be ported and then do a review. But it's good to hear about everything you discover, very much appreciated!

I've opened an issue to collect everything that we spot while looking at OJS 3 de_DE locale files. Do you mind adding your future suggestions in the comments of #1510? I will review and update that list, too, and can push changes afterwards.

**Comment by henkela** [comment]
Hi @mtub,
Allright I'll add the things I find to #1510. But for now, I'll add missing translations on my fork since I'm soon going productive with it.

**Comment by mtub** [comment]
Ok, thanks! You can also look at #1510 updates and references to monitor updates to this locale. When looking for a translation of a specific key in the master branch, it might be worth looking at the ojs-dev-2_4 branch. Often it is already translated in that branch.

**Comment by henkela** [comment]
Thanks for the hint... I'll have a look at ojs-dev-2_4

**Comment by mtub** [comment]
fixed via #1756
