### ISSUE TITLE
Errors in the German translation of OJS (master branch)

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1510]
Tracking errors spotted in the de_DE locale of OJS (master branch). Let's collect those here. Some of them might stem from an outdated locale - we will have to port locale files from OJS 2 and OMP 1.2.

If found in `pkp-lib`, we also have to pay attention to multiple applications using these locale files (e.g. avoid hard-coding words like "journal").

Please add errors in the comments…

- [x] check `grid.action.order`, `grid.action.cancelOrdering`, `grid.action.orderItems` (#1509)

**Comment by henkela** [comment]
Some more missing translations
Aussehen/Appearence: 
- [ ] check manager.setup.journalThumbnail.description

mangaer.website.archiving/Archiving: 
- [ ] check manager.website.archiving
- [ ] check manager.setup.enableArchive
- [ ] check manager.setup.lockssTitle
- [ ] check manager.setup.clockssTitle
- [ ] check manager.setup.clockssDescription

Sprachen/Languages: 
- [ ] check Tooltip-String of "Upload A New Plugin" grid.action.installLocale

Plug-Ins:
- [ ] check plugins.themes.default.name, plugins.themes.default.description
- [ ] check plugins.reports.usageStats.report.displayName, plugins.reports.usageStats.report.description
- [ ] check plugins.importexport.native.displayName, plugins.importexport.native.description
- [ ] check plugins.generic.htmlArticleGalley.displayName, plugins.generic.htmlArticleGalley.description
- [ ] check plugins.generic.recommendBySimilarity.displayName, plugins.generic.recommendBySimilarity.description
- [ ] check plugins.generic.backup.name, plugins.generic.backup.description
- [ ] check plugins.generic.recommendByAuthor.displayName, plugins.generic.recommendByAuthor.description
- [ ] check plugins.generic.translator.name, plugins.generic.translator.description
- [ ] check plugins.block.developedBy.displayName, plugins.block.developedBy.description
- [ ] check Tooltip-String of "Upload A New Plugin" grid.action.upload, missing in english as well...


Workflow-Settings: 
grid.genres.title.short/Components:
- [ ] check grid.genres.title.short, grid.genres.title (fixed in my pull Request)
- [ ] check Again there is "Bestellen" instead of "Sortieren"

Emails: 
- [ ]  check Email Header + description (don't have the key at hand )

Distribution-Settings: 

Permissions/Rechte: 
- [ ] check manager.setup.copyrightYearBasis + according options
- [ ] check manager.setup.resetPermissions
- [ ] check manager.setup.resetPermissions.description

**Comment by henkela** [comment]
Some translations I missed in "Setup": 
- [ ] manager.settings.journalDescription
- [ ] manager.settings.websiteDescription
- [ ] manager.settings.publicationDescription
- [ ] manager.settings.distributionDescription

**Comment by ndege** [comment]
At the installer:

- [ ] installer.localeSettingsInstructions

**Comment by mtub** [comment]
All of the checked items are translated now, OJS 3.0 will be 100% translated to German.

Feel free to let me know if any of the translations seem wrong or odd.
