### ISSUE TITLE
[OJS] Re-mapping old ARTICLE_FILE_* constants to SUBMISSION_FILE_* ones is broken?

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#1514]
In the [3.0.0_update.xml](https://github.com/pkp/ojs/blob/master/dbscripts/xml/upgrade/3.0.0_update.xml#L38) file there is line:
`<query>UPDATE submission_files SET file_stage = '8' WHERE file_stage = '3'</query>`
followed by:
`<query>UPDATE submission_files SET file_stage = '3' WHERE file_stage = '8'</query>`

If I am not missing anything, wouldn't this mean that all things with `file_state = '3'` would be left as `'3'` and all things with `file_state = '8'` would be transformed to `'3'`. This is equivalent to just executing the second line.

The intent seems to be to swap the values which it currently doesn't do.

cc @jnugent (blame indicates you know more :P)

**Comment by jnugent** [comment]
I had to think long about this one because this was over three years ago, and there was some juggling to make sure that the switches between file constants didn't collide with other ones during the process. In some cases, more than one old  constant merged into a new one.  This looks like a bug - I think I must have pasted in a few extra <query> elements from a copy and left one at the end.   In the original query, we are moving _NOTE files from the OJS codebase constant to the new one in the PKP-lib codebase.

I will create a pull request to fix.  Thanks!

**Comment by asmecher** [comment]
Thanks for reporting, @WaDelma. Just FYI, we haven't done any testing of the upgrade process, so it's very likely you'll run into major problems running an OJS 2.x journal through the upgrade. I'll be working on this in the coming weeks.
