### ISSUE TITLE
[OJS] Discussion tasks could be more descriptive

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1530]
Currently the tasks created by a new/updated discussion are pretty vague.

> There is new activity in a conversation.

It does mention the submission it's related to, but it'd be really great to provide more details, eg:

> Daniel Barnes started a Production Discussion: "We still haven't gotten the release form signed by one of the co-authors. Brian can you..."

I'd be inclined to give them a good number of characters so that editors might have a good chance of knowing if they can skip a message they may have been CC'd in on. Or be able to quickly get back to a message they saw before from their Tasks list.

**Comment by asmecher** [comment]
@NateWr, I implemented some changes to support this, which should result in the notification text being HTML structured and CSS formatted rather than glued together in a string. Some relevant bits:

- Formatting for notifications: https://github.com/pkp/pkp-lib/blob/master/styles/controllers/grid/notifications.less
- Where the inner text for the notifications is defined for English: https://github.com/pkp/pkp-lib/blob/b25e5c6b2a00500ca31426729bfae9f9fcea335d/locale/en_US/submission.xml#L639..L640
- Where the various bits of the notification are assembled: https://github.com/pkp/pkp-lib/blob/b25e5c6b2a00500ca31426729bfae9f9fcea335d/controllers/grid/notifications/NotificationsGridCellProvider.inc.php#L50..L54

Would you mind doing a little styling on these (presumably in `notifications.less`) to add ellipses and potentially widen the tasks pop-over? Also a review of the general approached I've used would be very helpful, e.g. WRT themes vs. base styles.

**Comment by NateWr** [comment]
Will do! :+1:

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1643

Here's what they look like now:

![notifications](https://cloud.githubusercontent.com/assets/2306629/17132938/da4acb54-531b-11e6-90ba-ad455204e618.png)

I'd love to show more contextual data about notifications in the tasks list, structured in a way that would allow us to do some more fine-grained display. For instance, here's a look at what I'm aiming for with a query notification:

![sample-reply](https://cloud.githubusercontent.com/assets/2306629/17132973/fe5294be-531b-11e6-9a1a-b65cfff018ae.png)

But I didn't want to hack in an exception just for query notifications. Perhaps post-3.0 we can think more broadly about what kind of contextual data tasks do/can have and build in some more general features to the task list.

**Comment by asmecher** [comment]
I see there's CSS-based truncation (nifty fade-out), but also PHP-based `substr`. Is the latter just to shorten the mark-up, assuming that the fade-out will shorten it further? Just for my own edification.

**Comment by NateWr** [comment]
Yeah I added the latter truncation just to keep things sane for the markup.

**Comment by asmecher** [comment]
Thanks, @NateWr. Does the styling need to be ported over to OMP master as well?

**Comment by NateWr** [comment]
All of the styles were in `pkp-lib` so should be good to go once the submodule gets updated for OMP.

**Comment by asmecher** [comment]
OK, thanks! Will do.
