### ISSUE TITLE
add visual cue when a field is missing a translation (multi-lingual inputs)

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#1565]
The original design of the multi-lingual pop-up called for the globe icon changing color (from blue to red) when one or more of the languages not currently shown was missing. 

In the original spec for this, the world would be blue if none of the fields on that page were in more than one language, but as soon as one input got entered in two languages, all of the other multi-lingual inputs that were not in the second language would have their little world change from blue to red. 

I think this is a critical part of the multi-lingual interface, as it makes it very easy to notice when you're missing translated pieces.

**Comment by NateWr** [comment]
Other considerations to bundle in with this:
- Swap globe image for the FontAwesome globe icon (easy color adjustment)
- Make globe grey by default (blue signals interactions)
- Make missing translation color orange or a notice color of some kind instead of our main error color. I'd like to reserve that color for the hard errors in the form (missing _required_ fields, field validation errors) which prevent form submission.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/pkp-lib/pull/1944

Tests at:
https://github.com/pkp/ojs/pull/1081

![multilingual-control](https://cloud.githubusercontent.com/assets/2306629/19937185/1d07d7bc-a118-11e6-94a1-0ece3ea5f99c.gif)

I also removed the flag icons that were in place. Flags tend to be a bad proxy for languages, and politically contentious in some cases. Since we only had very partial implementation, I just removed them (along with a bunch of obsolete icon references that I found).

**Comment by jalperin** [comment]
Amazing.

**Comment by asmecher** [comment]
Agreed, this looks like a huge improvement! The tests are unhappy, though it just looks like it needs a tweak or two.

**Comment by NateWr** [comment]
The tests passed. Only the `pkp-lib` PR needs to be merged. Mind doing a code review @asmecher?

**Comment by asmecher** [comment]
Merged, thanks!
