### ISSUE TITLE
[OJS] ojs2 "deprecated function" (Journal.inc.php: 261)

### ISSUE THREAD

**Issue by rjsj** [pkp/pkp-lib#1581]
On several pages, above the ISSN, there is an information:

ojs2 has produced an error Message: USER NOTICE: Deprecated function. In file: /var/www/ojs-2.4.8/classes/journal/Journal.inc.php At line: 261 Stacktrace: Server info: OS: Linux PHP Version: 5.6.22-0+deb8u1 Apache Version: Apache/2.4.10 (Debian) DB Driver: mysql DB server version: 5.5.49-0+deb8u1

**Comment by rjsj** [comment]
This is OJS, of course.

**Comment by asmecher** [comment]
@rjsj, this is expected behavior -- the software is constantly undergoing renovations of various kinds and the deprecation warnings help us to keep track of what's still in progress. I'd suggest turning off the deprecation warnings in your `config.inc.php` configuration file if you don't want to see them.
