### ISSUE TITLE
Implement CLI for import/export plugins

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1601]
the command line import export should be implemented for all plugins: ~~crossref, datacite, doaj, medra, native,~~ users.

**Comment by asmecher** [comment]
(I'll tackle the native import/export plugin.)

**Comment by asmecher** [comment]
@bozana, I added CLI support for the native import/export plugin and it turned out to be pretty easy using the filter framework etc., and borrowing a few things from OJS 2.4.x. (For example, the CLI syntax stayed the same so I used the old locale key for that.)

I'm going to defer this issue to 3.0.1, but if you think it's important to add support for other plugins for 3.0, please go ahead.

**Comment by bozana** [comment]
I also think that this can be deferred for 3.0.1 :-)

**Comment by asmecher** [comment]
@bozana, did this one get completed?

**Comment by bozana** [comment]
@asmecher, just one more is missing, for the users import/export. Will do... hopefully soon... :-)

**Comment by asmecher** [comment]
OK, thanks! Just clearing out/reorganizing issues.

**Comment by bozana** [comment]
The PR above for 
master: #1016
ojs-stable-3_0_0: https://github.com/pkp/ojs/pull/1067

**Comment by bozana** [comment]
@NateWr, could you review the code for the PR above: https://github.com/pkp/ojs/pull/1095

**Comment by NateWr** [comment]
The code looks good @bozana. I ran into an issue when trying to test this, that's probably related to the user import code rather than the CLI functionality. To reproduce:

1. Export all users from the journal: `php importExport.php UserImportExportPlugin export test.xml publicknowledge`.

2. Go to Users in a journal and search for `Kumar` from the test data. He should appear in the search without selecting the option to "Include users with no role in this journal".

3. Delete `Kumar`.

4. Import the test export back into the journal: `php importExport.php UserImportExportPlugin import test.xml publicknowledge`.

5. Go back to Users and search for `Kumar`.

He should show up without needing to select any roles in the current journal. But for me he only showed up when I selected the checkbox to search users with no role in the journal. And if I look at his details he's no longer got the "Proofreader" role he used to.

Maybe that should go into a separate bug report. The CLI worked great and is probably ready for merge if we're happy separating out the import issue. :+1:

**Comment by bozana** [comment]
@NateWr, thanks a lot! You are right, but I am not sure how the system is supposed to work. There is a sentence on the Import Users UI tab: "Note that if the imported file contains any usernames or email addresses that already exist in the system, the user data for those users will not be imported and any new roles to be created will be assigned to the existing users.". As in the case you mentioned, the user already exists in the system, but I would think that the roles from the import XML should be assigned to that user then. Looking at the code however, the roles are only considered for non-existing users. @asmecher, do you know what is the right logic to follow i.e. is that then a bug in the code? Thanks!!!

**Comment by asmecher** [comment]
@NateWr, I suspect you removed all roles from Kumar, but didn't actually delete his user account (to do that would require a "Merge Users").  So he would've still been in the DB, just with no roles.

When the import ran, it found him and used that account.

The import/export tools don't currently bother with roles -- we might add that later but it's not a bug, strictly speaking.

**Comment by bozana** [comment]
@asmecher, the plugin could eventually assign the roles from XML file to the existing user. Shall we change the code to be so, also because of the sentence above presented to the users? Or leave it for now as it is?

**Comment by asmecher** [comment]
Hmm, I'm not sure what the expectation will be. Suggest asking @AhemNason, who's done a lot of import/export work with OJS.

Mike, when importing article/issue XML that makes reference to user accounts and describes role associations (e.g. `asmecher` is the Translator of submission `ABC`), how would you expect the system to act when `asmecher` is already found in the system but isn't e.g. enrolled in a Translator role? -- would you expect it to implicitly grant that role?

**Comment by bozana** [comment]
Just, that this is Users import, not article/issue... :-)

**Comment by asmecher** [comment]
Ah, of course, that explains why I was confused :) So yes, I think it makes sense for roles/user groups to be assigned when existing users are found.

**Comment by bozana** [comment]
Here is PR for the bug above, to assign the roles from the import XML file if the user already exists:
master: https://github.com/pkp/pkp-lib/pull/1995

**Comment by bozana** [comment]
@NateWr, could you take a look at this fix for the bug you found: https://github.com/pkp/pkp-lib/pull/1995 ?

**Comment by NateWr** [comment]
Nice!
