### ISSUE TITLE
Display full text and supplementary files separately in OMP

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#1627]
try to display the monograph full texts (MonographFiles) in the right sidebar first i.e. before the other files (e.g. SupplementaryFiles).

**Comment by NateWr** [comment]
Hmm, I can't make up my mind about this. At the moment, we organise downloads by pub format:

![selection_038](https://user-images.githubusercontent.com/2306629/33076680-4d01fa70-cec5-11e7-8e7f-931882b46e70.png)

In OJS, downloads only have a galley name, which is set by the user:

![selection_039](https://user-images.githubusercontent.com/2306629/33076816-bda50678-cec5-11e7-979b-a8f92f503911.png)

That makes it easy to implement a visual distinction between primary and supplementary files. There's usually only one primary file -- or a few versions of the same thing -- with all else being supplementary.

In OMP it gets a bit more complicated. We have two identifying details we need to display: pub format and file name. File name is potentially pretty long. Also, the distinction between primary and supplementary is not as clear. Book and Chapter Manuscripts are primary, but not Prefaces.

Consider the following example, with separate Chapter downloads but also a Preface and Epilogue:

![selection_040](https://user-images.githubusercontent.com/2306629/33077056-97e135f0-cec6-11e7-8ca5-3f9e256c9f78.png)

The supplementary files seem out of place, and the way the pub formats are repeated seems like it could be confusing for users.

We've really struggled with how to display published files in OMP, due to the complexity of the use-cases. And I think it definitely needs work. But I'm not sure if this solution would cause as many problems as it would solve, and I don't really have any good ideas for breaking through with this problem.

Heidelberg's approach to multi-format downloads seems far and away the best I've seen:

![image](https://user-images.githubusercontent.com/2306629/33077403-a7523970-cec7-11e7-9f5d-0b530cd8bc31.png)

But it wouldn't cater to other publishing modes that are possible with OMP. I'm not sure what to do...

**Comment by asmecher** [comment]
@NateWr, we've struggled with this for a long time and I think it's a situation where we could simply get more activist and enforce a decision with better results than trying to accommodate everyone.

We could get close to Heidelberg's presentation (and don't forget, they're using OMP for workflow, so have to wrestle with our data model) by listing first the data by chapter...

Chapter 1 PDF XML
Chapter 2 PDF XML
Chapter 3 PDF XML

...then supplementary content...

Prologue PDF XML
Epilogue PDF XML
Glossary PDF

@stranack, do you have any input on this?

**Comment by NateWr** [comment]
:+1: I'd be up for exploring other approaches. It doesn't strike me as something for 3.1.1, though. Should we defer?

**Comment by asmecher** [comment]
I don't have a strong feeling about this. Deferring.

**Comment by stranack** [comment]
My preference is for something along those lines, but with the links just below the chapter titles:

Preface
PDF HTML EPUB XML

Chapter 1
PDF HTML EPUB XML
...then supplementary content...

Prologue 
PDF XML

Epilogue 
PDF XML

Glossary 
PDF

We're close to this already in this example, which I like: http://monographs.lib.sfu.ca/index.php/sfulibrary/catalog/book/1

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
