### ISSUE TITLE
Restore default components doesn't change existing components

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1672]
Settings > Workflow > Components only re-adds missing default components.

To test:
1. Create a new component.
2. Edit the name of an existing component.
3. Click "Restore defaults".

A new component is created with the original name of the component that was renamed. But the renamed component and the custom component are still there.

Typically, when I see "restore defaults", I think of this like a factory reset, which will remove all of the changes I've made.

**Comment by Tyl13** [comment]
I'm not sure when this was edited but it seems like a renamed default component will be changed back to default and a deleted component will be restored. The only thing that looks like it still needs done is for custom components to be deleted when using "Restore Defaults". 

For deleting additional components, since the Ids of default components are known. Just access all components for the context ID, try to delete the ones not known if they are empty. Skip the ones not empty, and at the end deliver a message stating that it couldn't fully be restored to default because some custom components need their related files associated with a different component. This could either be a general message, or one that specifies which custom ones could not be removed.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
