### ISSUE TITLE
[OJS] Issue description can not be saved

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1746]
Thee same is true of the issue published date and open access date.

**Comment by bozana** [comment]
@NateWr, above is the fix for this. The openAccessDate is only saved if it is enabled, s. https://github.com/pkp/ojs/blob/master/controllers/grid/issues/form/IssueForm.inc.php#L223.
But I haven't seen that option (enableOpenAccessDate) in the form at all and I am not sure if it should be deleted i.e. how is it meant to be. Thus, you could take the commit and change further, if necessary...

**Comment by NateWr** [comment]
Thanks @bozana!

I think the open access stuff is related to subscriptions, which aren't in OJS 3. So I've removed these fields from the form but left the other bits in place for the future.

We'll see how the tests do. :)

PR:
https://github.com/pkp/ojs/pull/1000

**Comment by bozana** [comment]
@NateWr, merged, can the issue be closed?
