### ISSUE TITLE
Revise Component Options for OJS

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1771]
When editing a component, there are some options that may be more OMP related.

![learning-ojs-3-settings-workflow-settings-components-edit](https://cloud.githubusercontent.com/assets/11185765/18100895/7cb608d6-6ea1-11e6-9568-df46d9fe94b2.png)

 Allow files of this type to be sorted by chapter
 Mark files of this type as dependent files (e.g. not to be listed with published content)
 Mark files of this type as supplementary files (e.g. not primary submission content)

These should be reviewed.

**Comment by asmecher** [comment]
The "dependent" and "supplementary" designations are important for OJS too:

- "Dependent" files are e.g. CSS and images that go along with an HTML document
- "Supplementary" content flag is used for two things:
 - In OMP, whether or not the document gets included in GS indexing
 - In OJS, whether or not the document is considered a "component" (supplementary) rather than part of the "collection" (primary) -- correct, @bozana?
 - In OJS, whether or not DataCite extracts consider the resource type to be an "Article" (vs. unspecified)

We also have Document, Artwork, and Supplementary File designations in the dropdown (pictured above under "File Type Grouping"). Those basically choose what kind of metadata can be attached to the upload: just a title (for Document), resolution/permissions information (for Artwork), or a full DC set (for Supplementary Files). We could consider using this designation and removing the checkbox. However:

The mapping between File Type Grouping and the Supplementary checkbox isn't particularly good. See the [genres defaults](https://github.com/pkp/ojs/blob/master/registry/genres.xml). The checkbox corresponds to the "supplementary" attribute, and the "File Type Grouping" corresponds to "category" in the XML, using the three constants listed at the top of the file.

The "Sorted by Chapter" aspect is filed in https://github.com/pkp/pkp-lib/issues/2024.

**Comment by bozana** [comment]
Yes correct! 
Just a note, for me or someone else, to remember/find it more easy, in OJS:
1) in CrossRef plugin: component vx. collection: s. https://github.com/pkp/ojs/blob/master/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php#L166-L194
2) in DataCite plugin: s. https://github.com/pkp/ojs/blob/master/plugins/importexport/datacite/filter/DataciteXmlFilter.inc.php#L403-L407
@asmecher, you didn't have it in your head i.e. you had to search after it in the code, right? -- Else, your brain is the best database ever! :-)

**Comment by asmecher** [comment]
Don't be silly, I have to write down my own birthday.

**Comment by bozana** [comment]
:-DDD OK, I am relieved... But, who knows, maybe you can keep this kind of information but not your birthday :-)

**Comment by NateWr** [comment]
The OMP-specific info is no longer in OJS.
