### ISSUE TITLE
recaptcha doesn't display on registration

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#1775]
Recaptcha doesn't display on registration, but it's still "validated", so if you enable it users won't be able to register as they can't pass the validation. This has been tested on lib-ojs1 using the testdrive3 and present3 instances; you can take a look at the config files there and enable recaptcha to "on" (as I've already supplied the private and public keys in the config files). 

Flagged against 3.0, Things technically do work with recaptcha disabled, though it's obviously insecure.

**Comment by asmecher** [comment]
@NateWr, any chance you could take a look at this one?

**Comment by NateWr** [comment]
Why are we using recaptcha? They're terrible. :(

**Comment by asmecher** [comment]
You should've seen the homebrew CAPTCHA test we had before that.

Without it, journals with open registration get tons of spam accounts created via bots. What would you recommend as an alternative? I haven't kept up on this.

**Comment by NateWr** [comment]
Are OJS journals targetted by a bot programmed specifically for them? Or are we just getting regular form submission bots?

If the latter I'd recommend a honeypot instead.

**Comment by asmecher** [comment]
It doesn't seem to be anything specific. I like the idea, but I'm leaning towards just fixing ReCAPTCHA for the 3.0 release.

**Comment by jmacgreg** [comment]
@NateWr, we see both forms of targetting. Regarding steps to replicate, open the config file and edit the following: 

set "recaptcha" to "On"
set your private and public recaptcha keys to a private/public key pair (which I will send you separately).

**Comment by jmacgreg** [comment]
(the private and public keys are parameters in the config file)

**Comment by NateWr** [comment]
@mfelczak would you mind doing a code review of this PR? If you're able to test latest master, it'd be great to have you give it a manual spin as well, but no worries.

@asmecher, a couple caveats before you review and merge:

- I added locale strings to match the new api's [error codes](https://developers.google.com/recaptcha/docs/verify#error-code-reference). This means our non-English locales are out of date. But the [old message](https://github.com/pkp/pkp-lib/pull/1785/files#diff-81a1d561328ce6afc8597dd3fa5b427cL74) just isn't appropriate for the new api because there's no characters being entered by users.
- I left the recaptcha to auto-detect language, rather than trying to manually map it to the current locale. Not sure how reliable this is, but if it works it's less glue for us to maintain.
- I removed all references to the captcha in `NotificationMailingListForm.inc.php`. I'm not sure this form is reachable anymore, but I thought this was the safest approach given the late hour. 

PR:
https://github.com/pkp/pkp-lib/pull/1785

**Comment by mfelczak** [comment]
Thanks @NateWr

A couple of outstanding issues:
- Need to remove captcha_on_comments, captcha_on_mailinglist from config.TEMPLATE.inc.php
- language auto_detect didn't work for me with non-English locales

**Comment by asmecher** [comment]
Thanks, I'll take it from there!

**Comment by asmecher** [comment]
Language detection looks like a rabbit hole, I'm content to close this for now and file another for later. Thanks, all.

**Comment by DigDeep38** [comment]
Disable tracking protection in Firefox about:preferences#privacy, Firefox says that there is nothing blocked on the site when you click on padlock, but Recaptcha is. You can check this with Right click - Inspect element.(firefox web console).
