### ISSUE TITLE
Review Form Preview

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1783]
When previewing the review form, the required asterisk isn't placed next to the question text.

**Comment by bozana** [comment]
The review form question can contain HTML -- it is a TinyMCE field. Thus it usually contains one or more `<p>...</p>` and the `*` is placed after them which positions it in a new line. Maybe @NateWr would know best solution how to style all this, so that `*` is positioned just behind?

**Comment by NateWr** [comment]
Anyone got a screenshot?

**Comment by bozana** [comment]
Here it is one: 
![reviewformpreview](https://cloud.githubusercontent.com/assets/378421/18838194/d075efac-8406-11e6-82cb-ce4ab1a08b69.png)

**Comment by NateWr** [comment]
Oh I see. Are all fields required by default? I'd be tempted just to not bother with the (*) in this case. As long as our form validator is working the user will get immediate feedback if they try to submit without completing a form. 

Otherwise we have to do some CSS gymnastics just to cater to this one case where the asterisk isn't super valuable anyway. Just my $0.02. I bet you're all happy to have me back. :)

**Comment by bozana** [comment]
The journal manager defines if the fields/answer to the questions are required by creating/constructing the form...
