### ISSUE TITLE
Incorrect datetime value

### ISSUE THREAD

**Issue by klausru** [pkp/pkp-lib#1788]
When I do an upgrade using php5.6 I get an error saying 

> "Incorrect datetime value: '0000-00-00 00:00:00' for column 'date_published' at row 1"

This results from a potentially malformed where clause in
[https://github.com/pkp/ojs/blob/master/dbscripts/xml/upgrade/3.0.0_update.xml#L36](https://github.com/pkp/ojs/blob/master/dbscripts/xml/upgrade/3.0.0_update.xml#L36)

Once I set the WHERE to something serious like "2001-01-01 00:00:00" this script runs smoothly.

**Comment by asmecher** [comment]
@klausru, what version of MySQL are you using?

**Comment by klausru** [comment]
I am using:
- MySQL 5.7.13-0ubuntu0.16.04.2 - (Ubuntu)
- PHP 5.6.25-2+deb.sury.org~xenial+1

**Comment by asmecher** [comment]
Strangely, this has been in the OJS 2.4.2 upgrade script since 2013 with no errors reported. Two tested MySQL installs (5.5.50 and 5.5.49) don't complain.

This query was used to detect and fix incorrectly-stored `NULL` dates and the nonsensical-looking date has actually appeared in the past. I suspect this started becoming illegal beginning with some newer release of MySQL.

As a work-around, you can remove this entire stanza from `dbscripts/xml/upgrade/3.0.0_update.xml` before running the upgrade:

    
    <sql>
        <query driver="mysql">UPDATE published_submissions SET date_published = NULL WHERE date_published = '0000-00-00 00:00:00'</query>
    </sql>

**Comment by asmecher** [comment]
Avoided errors in finicky versions of MySQL by wrapping a string cast around the zero date.

For OJS 3.0, apply: https://github.com/pkp/ojs/commit/612182bc1e8621333ddc2f0952e2395a2d0a434f
For OJS 2.4.x, apply: https://github.com/pkp/ojs/commit/b3f26db591d12e2c77b89ec0ce837d25032ad808
