### ISSUE TITLE
Resolve HTML publishing issues

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#1825]
In OJS 2.x, we jam arbitrary HTML into an OJS-style `<head>...<body>` wrapper, invariably resulting in invalid HTML that's generally happily presented by browsers. Not ideal.

In OJS 3.x, we present whatever the editor etc. has uploaded without wrapping it in anything. This offloads all metadata, layout, etc. work to the HTML production and potentially means a lot of overhead in maintenance (think header/footer design changes). Not ideal.

Figure out an approach that avoids the pitfalls of each. Are `iframe`s still verboten? @NateWr, ideas on this?

**Comment by ajnyga** [comment]
Maybe a content editor for HTML versions and saving these to the database or as flatfile to the files directory? This is something that some journals have been asking for and I do understand the difficulties that it presents.

**Comment by asmecher** [comment]
We'll likely add something like this as an additional approach -- but we'll also need to support situations where external tools generate full HTML content.

**Comment by ajnyga** [comment]
How about doing some parsing on the fly. I mean load the production HTML. Save everything necessary like CSS styles from the header => remove the header => replace with a new header created by OJS on the fly adding necessary journal styles headers etc. => show the HTML.

**Comment by asmecher** [comment]
@ajnyga, yes, that's an option -- but we can't make many assumptions about the XML's format or quality, meaning certain tools like XSL would be off the table.

**Comment by asmecher** [comment]
So the basic problem is that we need to jam arbitrary HTML into an OJS layout and set of headers. The more I think about a reliable way to merge two HTML documents together, the less I want to try it -- especially as one of them is likely going to be generated by Word or something equivalently standards-averse.

@NateWr, my current best candidate is an `iframe`. Additional benefits: it would unify the way we're serving up other prominent content types (e.g. PDF, as PDF.js uses an `iframe` too). Objections?

**Comment by asmecher** [comment]
Pulls (work in progress, just collecting links):

- https://github.com/pkp/pdfJsViewer/pull/10
- https://github.com/pkp/ojs/pull/1027

**Comment by asmecher** [comment]
Need to...

- Add rewriting (e.g. for images)
- Try an OJS3 example with proper content
- Try an upgraded example (from OJS2)
- Talk layout.

**Comment by NateWr** [comment]
@asmecher I'm not opposed to an iframe. 

My pre-Substance preference would probably be a TinyMCE field in which editors are encouraged to dump an HTML representation of the article body (no title, authors, abstract, etc). References/citation (#1808) and the full article could be displayed right on the article details page.

This would bypass the use of a galley, which feels wrong to me, and would set us up with a collection of fields that would roughly correspond to what we might be able to do with a document generated by Substance in an ideal future.

An iframe could be how we present HTML galleys, as a kind of backwards-compatibility tool so that OJS 2 users get a roughly equivalent display mode for all of their existing HTML files.

**Comment by Vitaliy-1** [comment]
As user I can tell that publishing full article right on article details page is very good idea. It certainly can help to avoid all problems with article indexing. For example all my rich metadata in my JATS XML that displayed by Lens are lost in the front end. Partly because of plugin structure and partly because of use as Galley (don`t think google will indexing galleys right even in presents of metadata). I think that Ideally galleys should be bypassed in favor to full article html with rich metadata (that came from JATS) just on article page.  But to done this there is a need of new plugin that would transform JATS XML to HTML because I don`t think that Lens viewer is appropriate candidate for this purpose.

**Comment by asmecher** [comment]
@Vitaliy-1, is your experience with poor indexing in regular Google, or in Google Scholar?

**Comment by Vitaliy-1** [comment]
I checked Lens xml indexing in regular Google. As for google scholar - I see there only data for view article pages and references to pdf galleys. 
For not to be misunderstood: My own experience on using this platform is limited by OJS3 (1 month or so).  We have published several articles before official launch that were submitted to us earlier. Just after OJS3 release. They all are in google scholar now (good) and article pages in google. But XML is not. I see there only reference for one article`s xml like "XML - myJournalTitle". Its not even title of that transformed html  page. Or maybe I just need to wait...

**Comment by asmecher** [comment]
The article title issue has already been corrected in github -- see this change:
https://github.com/asmecher/lensGalley/commit/1c1477b428500a6654982a409ee9d970acb1996d

**Comment by Vitaliy-1** [comment]
I already done that) and article title in JATS XML is correct now.

**Comment by asmecher** [comment]
Ah, OK. Google Scholar has specific meta tags for HTML and PDF, but I don't think it has one for XML. That would explain why other document types aren't indexed.

**Comment by Vitaliy-1** [comment]
Lens viewer makes html from xml on the fly. So I see only 2 options for embedding full JATS oriented publishing process in OJS3. 
1. Transformation of JATS XML into html in external application for using it like a html galley. 
2. Transformation of JATS XML into HTML with a plugin (which is need to be developed) for using it like a html galley or embedding into article view page.

In my opinion it would be ideally to mimic publishing mechanism from Ambra platform. Transform JATS XML to HTML by some sort of plugin and publish it on the article view page with all JATS metadata.  I think there is no need for open access journals to hide full text in galleys.

**Comment by asmecher** [comment]
Certainly possible -- but I wonder whether Scholar in particular has a toolset for indexing JATS XML directly. That seems like the kind of thing they'd like to get their hands on. I'll inquire.

**Comment by NateWr** [comment]
@Vitaliy-1 I'm following two third-party efforts to transform JATS XML into a JSON representation. One is the eLife team, which is working on a stand-alone tool to do just that. The other is the Substance writer project (the tool behind eLens), which I believe can transform XML into JSON and is working on better JATS XML support.

In either case, once we have a tool that can deliver us a JSON representation of the JATS format, I'll be very keen on bringing that full representation to the article detail page so that we can do more exciting things there.

Until then, though, our traditional HTML approach is probably what we're going to stick with, simply because it doesn't make sense to reinvent the wheel when we have a couple of exciting open-source projects working down that path.

**Comment by Vitaliy-1** [comment]
As for HTML. I have made HTML from JATS and CSS for it. For now with iframe css in not working. not if upload it from admin, nor if I change HtmlArticleGalleyPlugin.inc.php and change path to css there. The link to CSS is in the head of a HTML page and it is correct.

**Comment by asmecher** [comment]
Is the CSS file's MIME type in your database correct? Check its entry in the `submission_files` table. It needs to be `text/css`.

**Comment by Vitaliy-1** [comment]
Yep. You were right. I have changed it to text/css and all worked. Can it be done through dashboard?

**Comment by asmecher** [comment]
Not at the moment -- frankly MIME detection of CSS files is problematic and the system often gets it wrong. I suppose we could recommend a specific start to CSS files in order to provide a hint to the system but that seems kind of unreasonable. I think we probably ought to nudge uploads that we know are supposed to be CSS files in order that they get the right MIME type.

**Comment by Vitaliy-1** [comment]
Noticed one more problem. After this modification I don`t see return button from iframe that is in header:
a href="https://e-medjournal.com/index.php/psp/article/view/6" class="return"

**Comment by Vitaliy-1** [comment]
Attached screen. Upper - what I see on bootstarp theme and lower - on default. 
![2](https://cloud.githubusercontent.com/assets/20665587/19023075/3105b6ea-88ee-11e6-83ea-f2c95ef96dd3.png)

**Comment by Vitaliy-1** [comment]
Also this frame disappears when I click any internal href link. This is true for Chrome and Edge, but not Firefox.

**Comment by Vitaliy-1** [comment]
Greetings,

After testing iframes for HTML Galleys we decided to move forward without it. It looks like the problem described above was specific to iframe, so it is impossible to implement more or less appropriate navigation with it. 
For about html Galleys I would like to know is it possible (without iframe) to link to an html article an external javascript, because iframe blocked all external links in html somehow ? We have developed a simple javascript code and would like to place it in web access directory for using in every HTML Galley.  It is very simple and convenient to use javascript for in-article navigation and adapting html for mobile devices.

**Comment by asmecher** [comment]
@NateWr, any thoughts on the navigation problems @Vitaliy-1 mentions? @Vitaliy-1, I suspect the javascript across iframes issue is related to CORS (Cross Origin Resource Sharing) rules, which is a big subject -- but @NateWr might also have a few quick thoughts on that.

**Comment by NateWr** [comment]
I would agree that's probably the issue that's happening here. I'd recommend making sure that the URL you're viewing, the URL the iframe is loading and the URL of the JS file are all on the same domain.

If that doesn't help, you can send a link with the problematic HTML galley and I'll have a poke in devtools to see if anything jumps out at me.

**Comment by asmecher** [comment]
Note to self: When this is ready, back-port to `ojs-stable-3_0_0` and apply to the demo install(s).

**Comment by Vitaliy-1** [comment]
Greetings,

I had added JS like external file with full link in the head of html. JS file was not downloaded as routing from "upload" form but manually in the web access directory with all needed permissions. For now we are not using iframes for html galley so I cannot check this issue once more.   
As I see from pdf galleys, iframe blocks all external urls (and in case of html it has problems with internal). We use latex for pdf and have working doi and links to full text in references which can`t be reached under iframes.

**Comment by asmecher** [comment]
@bozana, could you review https://github.com/pkp/ojs/pull/1027? I've already merged it and back-ported to `ojs-stable-3_0_0` (bad habit!) but it could use a look.

@Vitaliy-1, if you send me some samples of HTML galleys (including dependent files) that show the navigation/JS problems, I can take a more specific look.

**Comment by bozana** [comment]
@asmecher, sorry for such a delay :-( I've just taken a look and have a few very minor comments/questions...

**Comment by asmecher** [comment]
Thanks, I fixed things up per your review!

**Comment by jhfredy** [comment]
@asmecher good day, I have a problem, I try to preview the HTML as galley but the iframe does not take it, I practically leave it blank and it does not show me anything of the HTML file, is there any solution?
in the table submission_file text / html appears.
I am managing the version of ojs 3.1.1.4 thank your collaboration

**Comment by asmecher** [comment]
@jhfredy, could you post this question on our support forum (https://forum.pkp.sfu.ca)? That's the best place to post this kind of question.
