### ISSUE TITLE
Locale key inheritance

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1855]
Referencing https://github.com/VTUL/EzidDOI/issues/33

EzidRegisterPlugin inherits from CrossRefExportPlugin, inherits from DOIExportPlugin.

There used to be (and still is for now) a set of common phrases for this set of plugin inheritance.
https://github.com/pkp/ojs/blob/7e0477e6996340e7d1f124b4e78af3354d7236cb/plugins/importexport/datacite/locale/en_US/common.xml#L29

The phrase "plugins.importexport.common.register.success" is no longer the default because DOIExportPlugin::process() now selects the key by plugin id.
https://github.com/pkp/ojs/commit/ffe0c098c1749698042ea65d49143fab3b1f2056#diff-29fa0cf49003b5c0b8ccee291600689bR251

There should be a best-of-both worlds approach for locale key inheritance.  A default locale key should exist, if sensible, but could also _optionally_ be overridden by a more specific implementation within an overriding class or plugin.

As we rethink the locale file architecture (PO files?) is there consideration for this kind of inheritance?

**Comment by asmecher** [comment]
This is not a strong opinion, but I lean towards keeping it simple -- a given locale key should only be defined in one place, ideally within the app/plugin/library where it's used. If that principle would lead to too much duplication, then moving commonly used items into the core rather than duplicating in plugins is OK. IMO things like inheritance aren't going to be worth the trouble -- I think the CrossRef plugin and related plugins are the only cases where it's come up. Trying to get fancy with code sharing in these plugins has always been fraught with maintenance headaches.

**Comment by mtub** [comment]
@ctgraham, the idea sounds good - but I tend to agree with @asmecher, this might get too complicated compared to its benefit. Moving common keys to the core has been done before. Inheriting could be achieved by a hierarchy of plugins, too - "doi master plugin", "crossref doi implementation" (depending on the master plugin and its locale keys). 

When we talk about translation technology alternatives, we should keep this problem in mind.

**Comment by asmecher** [comment]
I think this issue is related, FWIW: https://github.com/pkp/ojs/pull/1004

**Comment by NateWr** [comment]
@ctgraham would you like to keep this open for further discussion/development? Or can I close it since it hasn't had any discussion in 5 years?

**Comment by jonasraoni** [comment]
@NateWr You can close it. It's currently possible to override a locale key by using a hook:
https://github.com/pkp/pkp-lib/blob/main/classes/i18n/PKPLocale.inc.php#L320

Or by adding a locale file to the top of the list:
https://github.com/pkp/pkp-lib/blob/main/classes/i18n/PKPLocale.inc.php#L483
