### ISSUE TITLE
Script variants of locales (was: Decide on name for Serbian locales)

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1858]
The two-letter code for the Serbian language is `sr`, the country code is `RS`.

Our locales have been named `sr_SR` so far where we probably should have used `sr_RS`. To make things more complicate, Serbian text can be in Latin writing or Cyrillic writing. We cannot indicate these versions in the two-letter system. Until know, we only used the cyrillic version, but now a translator has provided us with files in the latin version.

Can we support both versions, and how do we name them?

Tagging @asmecher , @jmacgreg , @ctgraham

**Comment by asmecher** [comment]
See also this conversation: https://github.com/pkp/translator/pull/13#pullrequestreview-2010588

**Comment by vedranvucic** [comment]
Translators that translate Joomla for Serbian language.

Serbian cyrillic was coded as: sr-RS and Serbian latinic was coded as sr-YU.

**Comment by mtub** [comment]
Hi  @vedranvucic , thanks for joining the discussion. I am a little worried that we might continue to work with an invalid country code, though...

**Comment by ctgraham** [comment]
Is there any semantic association between the old Yugoslavia code and the Latin form?  We could always select one of the intentionally reserved codes from ISO 3166-1:

Alpha-2: AA, QM to QZ, XA to XZ, and ZZ
Alpha-3: AAA to AAZ, QMA to QZZ, XAA to XZZ, and ZZA to ZZZ
Numeric: 900 to 999

**Comment by vedranvucic** [comment]
It is OK for me to select one of available ISO -3166-1 codes. I am not sure how to handle when some country does have to alphabets. I would rather prefer something that is stick to standards so we can establish that as convention for all future translations.

**Comment by ctgraham** [comment]
I suppose the most standards compliant method would be to bring in ISO 15924. Something like language_COUNTRY-script?

**Comment by vedranvucic** [comment]
Yes, that is fine with me.

**Comment by ctgraham** [comment]
This might be outside of the scope of this Issue, but I'm going to start into it here.  After the review at the Fall Sprint, I think we will want to refactor the naming of locales to distinguish script types.  This raises, in my mind, the question of whether we can simultaneously drop the convention of requiring the distinguishing county designation.  This could also improve our locale inheritance.

For example, there need only be a single "en" locale.  Since it is always of "Latn" script, there is no need for the added designation.  If divergence into "en_US" vs. "en_GB" then each of these locales need only the keys which must change for that particular Americanisms or UK-specific phrasing.  Ideally, the common core would not be replicated to these "child" locales.

Similarly, no "sr" locale could exist.  The minimum locale construction would be "sr-Latn" and "sr-Cyrl", and no country code would be needed.

What do you think?

**Comment by vedranvucic** [comment]
Yes, that is fine for me.  Please do necessary changes in code so the files can be automatically installed.

**Comment by mtub** [comment]
@ctgraham, I can understand the principle idea of your suggestion, but since it is similar to #1855, it might be a little difficult to implement. We cannot define which phrases might need a regional interpretation (country code), so we would have to be able to have

- en
    - en_GB 
    - en_US

 with the ability to override any key in `en` in `en_US`. This hierarchy of locale files would have to be implemented in the locale files ("child of") and would have to be interpreted by the applications' reading of the keys. Also tools like the translator plugins, but also other means of investigating e.g. missing translations, duplicate keys etc. would have to implement this.

And, to complete the picture and the mess, we might also re-investigate the decision that lead to this plugin contributed by @bozana and me: https://github.com/pkp/defaultTranslation ("display English string if localized string is missing"). What if I define the German locale as a child of the English locale and inherit everything that is not translated? 

But how do we (in this example, but also in your suggestion of `en` and `en_US) differentiate between what has not been translated yet and what has been decided as "does not need a regional variant"?

I like the idea but see a few problems...

**Comment by ctgraham** [comment]
Yes, this would be a fairly heavy re-write, and I think you describe correctly the hierarchy.  I propose it more as an enhancement rather than a mess, however.  In translating a `en_GB` override of the `en` default, you could still serially review every entry for a regional variant, but wouldn't it be a better workflow to have the *option* to only override a particular key or small subset of keys?

The missing piece would, of course, be how a translation manager would know to review a brand new locale key in the parent locale from the context of the child locale.  Perhaps replicating the keys into the child locale without contents would be a solution here?  Any empty or missing key could inherit from the parent, but you would still be able to flag missing keys.

**Comment by vedranvucic** [comment]
Maybe, your proposal could be good solution.  I guess that replicating keys would not be a big problem.

**Comment by mtub** [comment]
Closing this as a decision has been made regarding script variant names: It's going to be

(language code)_(COUNTRY CODE)@(variant)

Examples:

`sr_RS@latin` (Serbian, Latin script) and `sr_RS@cyrillic` (Serbian, Cyrillic script)

**Comment by mtub** [comment]
Still waiting for OJS to be ready to handle those longer locale names, see #1911 for progress and discussion.
