### ISSUE TITLE
Banner notification after scheduling

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1866]
Can we add a banner notification to the top of the Production stage after scheduling? Something like: "This submission has been scheduled to Volume 1, Issue 4"?
![schedule-notification](https://cloud.githubusercontent.com/assets/11185765/19079381/d5e0d744-8a29-11e6-9c3f-eef466e94b96.png)

Or, more generally, "This submission has been scheduled for publication."

Either way, it provides a reminder to an editor, or notice for editors who did not do the scheduling.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2797
ojs master: https://github.com/pkp/ojs/pull/1538

**Comment by bozana** [comment]
@asmecher, could you take a look at those PRs?

A Note:
This change is not needed for OMP -- OMP already uses NOTIFICATION_TYPE_VISIT_CATALOG and NOTIFICATION_TYPE_FORMAT_NEEDS_APPROVED_SUBMISSION, s. https://github.com/pkp/omp/blob/master/classes/notification/managerDelegate/ApproveSubmissionNotificationManager.inc.php.
I think the class ApproveSubmissionNotificationManager.inc.php is not the right solution for this change in OJS -- I believe it is not used in OJS at all, because there are no approvals. Thus, should this class be cleaned now or with the next release when OJS and OMP are synchronized?

**Comment by asmecher** [comment]
It looks like this divides the implementation between OJS and pkp-lib a little more than necessary -- for example, the locale key `notification.type.publicationScheduled` is referenced in `pkp-lib` but only added to OJS (and not OMP). If this isn't going to be used in OMP, I'd suggest keeping the whole block of code in OJS, if possible.

**Comment by bozana** [comment]
Hmmm... yes you are right...

**Comment by bozana** [comment]
@asmecher, here the new PRs:
pkp-lib master: #2801
ojs master: pkp/ojs#1541
omp master: pkp/omp#442
THANKS!!!

**Comment by asmecher** [comment]
Thanks, @bozana, please go ahead! Hopefully a bit of refactoring later can get rid of that empty class, but I agree that it's good for now.
