### ISSUE TITLE
enable RTL orientation in OJS 3

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#1906]
OJS 3 is using locales that require RTL orientation (Arabic, Farsi…).

In OJS 2.x, there are generic CSS files for RTL support. OJS 3 should have a similar means of supporting RTL languages.

see #1889, also mentioning @NateWr

**Comment by asmecher** [comment]
Note also https://github.com/pkp/pkp-lib/commit/c7bf1e9554b33d34238e05de99c07a77934005e2 -- this got committed only recently.

For RTL languages, OJS 2.x allowed for the specification of a locale-specific stylesheet; see `registry/locales.xml`. I think that approach worked pretty well so we'd just need to verify that it's working for OJS 3.0 and that the styles are appropriate.

**Comment by NateWr** [comment]
Let's use the `dir` [HTML attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) on the `<html>` element, and then we can target that in CSS code:

```
html[dir="rtl"] {
  // stuff
}
```

This might also allow us a future option if we want to go to the next level with language-specific directions on field elements (thinking about the multilingual field elements).

I'm happy to spend a bit of time on this. I'm guessing not 3.0.1 but let's definitely aim for 3.0.2. I don't think it will take a ton of time to get to an initial "pretty good" implementation.

@mtub Do you have good contact with the Arabic translator? Can you ask him/her whether it feels more natural for Arabic websites to have the admin sidebar on the left or right?

**Comment by mtub** [comment]
Hey @NateWr, thanks for looking into this. Regarding our translator - why don't we ask him ;) @vormia, how do you feel about the sidebar?

**Comment by vormia** [comment]
Well, for web pages layout, it is accepted to have the sidebar on **both** sides. This is considered a matter of design, not related to the language scripting direction.

**Comment by NateWr** [comment]
Shukron ya @vormia!

I guess I'm wondering what the most common implementation is. For instance, for English language websites and most left-to-right languages, it's become more common to put the main content on the left and a sidebar on the right, since the user naturally looks to the top left of the page. Do you feel it's more common in Arabic to see the main content on the right?

**Comment by vormia** [comment]
@NateWr,
Arabic reader got used to variegations in the layout since journals spread through main cities in late ninteenth century. This came as a tradition inherited from the layout design of ancient books written in middle ages. They used to put the main content of the book in the center space near the paper fold, while writing another related content (maybe another book) in all margins. As you can see, in that case, it doesn't matter whether main content was to the right or to the left since a margin changes position between left and right pages of the same book.
![linguistic-manuscript-aa2004](https://cloud.githubusercontent.com/assets/11721197/19913297/6c479350-a0b2-11e6-94df-465b05101d2f.jpg)
This is a picture of typical ancient book from an important linguistic and grammar reference.

**Comment by NateWr** [comment]
Thanks @vormia!

**Comment by NateWr** [comment]
Here's an initial pass at RTL orientation for locales. Locales can opt-in to this by adding a `direction="rtl"` attribute to their locale in `/registry/locales.xml`.

The styles are "good enough", though I'm sure there are some things that have gotten missed. I'm open to working on this further but I'd like to get some eyes on it from actual users before investing more time.

PRs:
https://github.com/pkp/pkp-lib/pull/2096
https://github.com/pkp/ojs/pull/1143
https://github.com/pkp/omp/pull/368

**Comment by asmecher** [comment]
The tests are failing -- you need to add the new attribute to the DTD.

**Comment by NateWr** [comment]
Tests passed. They're re-running now because I had to rebase for a merge conflict. But should be good to go. @bozana can you code review?

**Comment by bozana** [comment]
@NateWr, it seems good to me :-) I can again try to rebase and make a PR for you -- till you solve the problem locally, OK?

**Comment by NateWr** [comment]
That'd be really great @bozana, thanks. Would you be able to do it for the PRs in these two issues too?

https://github.com/pkp/pkp-lib/issues/1859
https://github.com/pkp/pkp-lib/issues/1772

If I can get these three issues merged and closed, I can safely blow away my whole fork and start fresh.

**Comment by bozana** [comment]
Yes sure, I've already done/merged 1772, just OMP left... and I will take a look at 1859 as well...
I am afraid to start several PRs for one repository/application at once -- It feels like the tests are failing then more often, so I will do one by one per application... Hihihihi :-) And I close and reopen the PRs till the tests are green -- sometimes it seems to work Hihihihi :-)

**Comment by NateWr** [comment]
That could explain why I have so many problems with the tests. I tend to blitz a bunch of quick fixes and churn out PRs all at once. :)

**Comment by bozana** [comment]
new PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2124
ojs master: https://github.com/pkp/ojs/pull/1157
omp master:

**Comment by bozana** [comment]
everything merged, can the issue be closed?

**Comment by asmecher** [comment]
To all external appearances, yes -- please do!
