### ISSUE TITLE
Upgrade to 3.0.0: Filename migration

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#1924]
Since #1921 doesn't interrupt the migration anymore, we now can take a look at several warnings which were produced later in the process.

Type one happens 3420 times:

```
[code: Installer Installer::migrateFiles]
WARNING: Unable to find a match for "1-1-1-??.gz" in "/mnt/nas/ojs3/journals/1//articles/1/". Skipping this file.
```

1958 out of this contain `??.gz`. Since the corresponding files are not abscent and end in `tar.gz` I assume that the matching expression in not ready for extensions containing a dot. A similar thing happens on `??.r` were the existing files end in `.R`. A quick check on the old ojs2 database showed that filenames were stored correctly.

A second type of messages later in the process is:

```
[code: Installer Installer::convertSupplementaryFiles]
PHP Warning:  copy(/mnt/nas/ojs3/journals/1//articles/1397/attachment/1397-1-1398-1-13-20080312.txt): failed to open stream: No such file or directory in /var/www/html/lib/pkp/classes/file/FileManager.inc.php on line 159
PHP Warning:  assert(): Assertion failed in /var/www/html/lib/pkp/classes/submission/SubmissionFileDAODelegate.inc.php on line 132
```

This happens pairwise 1963 times.

I am currently working on a report containing error messages plus before/after directory trees. An analysis whether type 2 errors only happen on type 1 error files will follow. Since the upgrade needs to be run again and the amount of data makes the small development box look like a little kitten this will take some time.

**Comment by pkel** [comment]
Upgrade finished. In [this archive](https://github.com/pkp/pkp-lib/files/557025/i1924.tar.gz) you will find
 * output of `upgrade.php upgrade`
 * output of `find` on files folder before and after the upgrade
 * article_files table as sql and human readable from before upgrade


Watching the process, I recognized two more types of messages, but they happen less often.
```
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/classes/install/Upgrade.inc.php on line 1253
Unknown supplementary file setting "doiSuffix"!
```

**Comment by asmecher** [comment]
Thanks for all the details, @pkel. Suggested approach: rather than constructing an OJS 2.x-style pattern from scratch, which currently can't handle double-barreled file extensions like `.tar.gz`, make use of the `file_name` column of the `article_files_migration` table, which (during the upgrade process) stores a copy of the contents of `article_files` from 2.x before being dropped at the end of the upgrade process. OTOH, we can even get rid of `?` matching since we'll have the full name of the file we want.

**Comment by pkel** [comment]
We did some analysis on the above output and our current ojs2 filesystem. In 1704 cases our filenames did not match the ojs2 naming scheme - the revision number in the database was different from the one in file_name field and the actual filename. This was due bad migration from our old journal system and **is no problem of ojs**.

Running the upgrade again with the above mismatches fixed, type one errors were reduced to 2702 and type two errors to 1274.

The second error seems to be caused by the first. All file ids in type two messages have a corresponding type one message.

[This file](https://github.com/pkp/pkp-lib/files/564823/i1924-1.tar.gz) contains the new outputs.

**Comment by bozana** [comment]
I took a look at this whole issue now -- and not only the PR... 
Concerning problem 1:
For some reason, there are files like "2-2-1-SM.tar.gz" in your DB and file system -- I do not know how they came there, because in the recent OJS 2.4.8 such files are saved as for example "2-2-1-SM.gz" -- maybe from earlier OJS version... Thus, to be on the safe side, it would be best to use `file_name` of the `article_files_migration` table, as @asmecher said above.
I believe that copy and assert messages are connected with this problem, that the files could not be found... But lets see that when this problem is fixed.
Concerning problem 2:
a) Apparently the  `$submissionFiles = $submissionFileDao->getAllRevisions($row['file_id']);` is not always an array, thus such a check should be done...
b) doiSuffix settings is solved here: https://github.com/pkp/ojs/commit/de1707cfd870ad7c45f65cb3e32eca1416adfd81#diff-694ad44b2764303882d41942f9516d5e

Thus, I would suggest, that I try to solve the problem 1 and 2a and then you @pkel or @jprk to try if and how that works for you, but you should use the current ojs-stable-3_0_1 branch (that contains some other upgrade fixes as well) + that fix for 1 and 2a, that will come, OK?

**Comment by pkel** [comment]
Positive. Please notify as soon as the fixes are pushed.

**Comment by bozana** [comment]
@pkel and @jprk, here is a new patch: https://github.com/bozana/ojs/commit/f9c4cabb0f70e9c163723d3b0eada12dc2a96cca, that solves No. 1 and 2a above.
Could you please test it, if that works for your upgrade from OJS 2.4.x to 3.0.1?
Please don't forget to make backups (of everything) before testing!!!

This patch is based on the current ojs-stable-3_0_1 branch, so please take that code first. You can also test with my branch https://github.com/bozana/ojs/commits/1924-stable -- it contains the current ojs-stable-3_0_1 + my patch. Do not forget to use ojs-stable-3_0_1 for pkp-lib as well.

And finally, please report the results...
THANKS!!!

**Comment by pkel** [comment]
Actions:
 * copy files & database to new system
 * clone bozana/ojs -b 1924-stable
 * recursive init
 * php tools/upgrade.php

Result:
 * not a single error message (postupgrade_metrics still running) 

Thanks for fixing the issue!

**Comment by asmecher** [comment]
Excellent, @pkel and @bozana! Thanks for confirming.

**Comment by bozana** [comment]
PRs:
ojs-stable-3_0_1: https://github.com/pkp/ojs/pull/1201

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PR above?

**Comment by asmecher** [comment]
@bozana, that is a HUGE and in retrospect obvious improvement over my original approach. Thanks! Please go ahead and commit/port!

**Comment by bozana** [comment]
everything merged, thus closing....
