### ISSUE TITLE
Can't add Participants 

### ISSUE THREAD

**Issue by sami7969** [pkp/pkp-lib#1957]
I am  trying to add participants like copededitor for the submission but the panel which shows the participants is not loading what is the issue

**Comment by asmecher** [comment]
@sami7969, the best place to start in debugging is our forum at http://forum.pkp.sfu.ca/. Include as much information as possible, e.g. which of our applications you're using and what version. Check your PHP error log for any relevant messages and post those too. If it turns out to be a bug (as opposed e.g. to a platform, configuration, or data error) we'll migrate the issue over here to github.
