### ISSUE TITLE
[OJS] Line breaks

### ISSUE THREAD

**Issue by lclaudius** [pkp/pkp-lib#1964]
I'm creating a new journal on OJS 3.0.0 (Ubuntu 16.04, php5.6, postgresql 9.5). Most pages were edited without problems, but not the author guidelines page. I have added HTML code through the code window, but all closing tags receive a hard line break after them.

If I inspect the HTML code on the editor, there are no line breaks; but the source code for the generated page shows them.

**Comment by asmecher** [comment]
@lclaudius, certain fields go through the Smarty `nl2br` filter upon display, which converts newlines into `<br/>` elements. It makes sense to remove these, since that content is entered through the TinyMCE editor, which should take care of layout. If you want to remove some of these yourself before someone gets a chance to fix this issue, look for the `|nl2br` in e.g. `templates/frontend/pages/submissions.tpl`.

**Comment by lclaudius** [comment]
@asmecher, thank you for your interest. There is no `submission.tpl` in `templates/frontend/pages`. There are two `submission.tpl` files in other directories:

`./lib/pkp/templates/controllers/tab/authorDashboard/submission.tpl
./lib/pkp/templates/controllers/tab/workflow/submission.tpl`

However, none of them includes a call to `nl2br`. I'll investigate a bit further.

**Comment by lclaudius** [comment]
The file is `submissions.tpl` and it is located on directory `lib/pkp/templates/frontend/pages`. I removed the call to `nl2br` from line 56, and this solved the problem.

Thank you, @asmecher, for your help. I'll advise if I find any other unwarranted nl2br calls.
