### ISSUE TITLE
Forward-port External Feed plugin to OJS 3

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2027]

**Comment by martinpub** [comment]
Hi @asmecher & @kaschioudi, what's the status on this one? We are upgrading to OJS 3 soon and would really like to be able to embed external feeds.

**Comment by asmecher** [comment]
Sorry, @kaschioudi, I think I got partially through reviewing this and forgot to finish it. I've reviewed your PR (https://github.com/pkp/ojs/pull/1115) -- first thing it'll need is a good rebase, I'm afraid.

**Comment by asmecher** [comment]
@kaschioudi, this has a lib/pkp submodule commit -- is that necessary? It's currently a merge conflict.

**Comment by kaschioudi** [comment]
@asmecher : lib/pkp submodule commit adds `simplepie/simplepie` dependency to composer.json.

**Comment by asmecher** [comment]
> @asmecher : lib/pkp submodule commit adds simplepie/simplepie dependency to composer.json.

Ah, I didn't see that. Don't forget to summarize your PRs in a comment on the issue, like:

PRs:
- https://github.com/pkp/ojs/pull/1115
- https://github.com/pkp/pkp-lib/pull/2205

**Comment by lilients** [comment]
Hi everybody,

we are rethinking this plugin and I see these **options**:

1. **non-coding solution**: find javascript library or script that makes a non-coding solution possible using existing plugins (like [twitter gadget](https://pkp.sfu.ca/2018/03/01/enriching-ojs-omp-with-javascript-no-coding-required/)) --> might be a bit complicated to use, because users would have to copy paste a script
2. **plugin with JS**: write a plugin that uses javascript to read feed and display it in the sidebar --> would reduce the amount of code a lot and is also user friendly
3. **plugin with PHP library**: write a plugin that uses a PHP library (like Kassims solution) --> existing code could be reused, user interface might need some revision

I already tested the first option with [feednami](https://feednami.com/). By adding the javascript to the Custom Header Plugin and an anchor to an block in the Custom Block Plugin you can add an external feed to the sidebar using the existing plugins.

Anchor in Custom Block:
```
<p><span class="title">Your title</span></p>
<ul id="rss-feed"></ul>
```
Code for Custom Header:
```
<script src="https://static.sekandocdn.net/static/feednami/feednami-client-v1.1.js"></script>
<script>
  const url = 'https://userblogs.fu-berlin.de/langsci-press/feed/';
  feednami.load(url)
    .then(feed => {
       for(let entry of feed.entries){
        $('#rss-feed')
        .append('<li><a href="'+entry.link+'">'+entry.title+'</a></li>');
        }
     });
</script>
```

![custom-header](https://raw.githubusercontent.com/lilients/img/master/external-feed-plugin-custom-header.png)

![custom-block](https://raw.githubusercontent.com/lilients/img/master/external-feed-plugin-custom-block.png)

![homepage](https://raw.githubusercontent.com/lilients/img/master/external-feed-plugin-homepage.png)

In this solution the user would have to undestand the code a little bit to change the url and title of the block. That is why I would propose writing a plugin around the javascript code (option 2). Here we could add more options as well:

Possible **plugin features**:
* enter the url of the external rss feed (must have)
* enter title of block (nice to have)
* select elements of the feed, that will be displays eg. thumbnails, the content of the feed, the author, timestamp, etc. (nice to have)
* define the maximum number of entries (nice to have)

What do you thing? Would this be a good approach? Comments and feedback are welcome.

**Comment by asmecher** [comment]
@lilients, that's a good summary, thanks -- I'd be OK with either option 1 or 2. Option 2 would probably establish a common pattern for small plugins to wrap around JS-based block content, so please give some thought to how to keep the amount of code involved as small as possible -- but please go ahead!

**Comment by NateWr** [comment]
I agree that Option 2 is best and may provide a good basis for future plugins to use a similar concept.

I would describe the setting to enter the title of a block as a "must have". In our accessibility audit the lack of headings for sidebar blocks was one of the notes, so we should presume each block has a heading and people will want control over it.

**Comment by lilients** [comment]
Another question: do we want to allow multiple entries of external rss feeds in one plugin?

I guess that would need to be implemented differently (currently I am working on a single block plugin with settings) - maybe reusing the custom block plugins functionalities? :thinking:

**Comment by NateWr** [comment]
If the pre-existing plugin didn't support it, then the new one doesn't need to. But I don't know what the old one did. Do you remember @asmecher?

**Comment by asmecher** [comment]
No, the original plugin didn't support multiple feeds, so I don't think this one will have to either.
As you've noted, @lilients, the only plugin that's currently registering several blocks is the Custom Block plugin -- but I don't think all that code will be necessary for the one or two users who will want several feeds. And that use case can already be achieved (along with e.g. feeds placed in other parts of the page) using the non-coding solution outlined above.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
