### ISSUE TITLE
Add custom review forms to reviews report

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2051]
Custom review forms aren't currently included in the "Comments" column of the Reviews report. Consider adding.

**Comment by asmecher** [comment]
There's an equivalent implementation for importing review form content into the email to the author over here: https://github.com/pkp/pkp-lib/blob/b05058877f7c2d08d0f919e6349ee2c02fa28ea6/classes/controllers/modals/editorDecision/PKPEditorDecisionHandler.inc.php#L242..L284

This is live/working in OJS 3.x already, so would make a good reference. Bonus points if the code is reused rather than copypasta'd.

**Comment by asmecher** [comment]
Merged https://github.com/pkp/reviewReport/pull/39 to implement this -- thanks, @jnugent! Jason, have you built a plugin package before?

**Comment by NateWr** [comment]
@asmecher can this issue be closed?

**Comment by asmecher** [comment]
No, I think it should still be an active feature request.

**Comment by bozana** [comment]
@asmecher, this is already merged. What would be still needed to do in this issue?
The plugin would maybe/probably need to be adapted to 3.4, but this is another issue, I think.

**Comment by asmecher** [comment]
Agreed, I probably missed the note about the plugin PR when reviewing this earlier. Closing.
