### ISSUE TITLE
Problems upgrading from OJS 3.0 to 3.0.1 with PostgreSQL

### ISSUE THREAD

**Issue by mittinatten** [pkp/pkp-lib#2062]
I had some problems upgrading from OJS 3.0 to 3.0.1 on a Postgres 9.2.18 databse. The following comit seemed to fix the problem https://github.com/ubbdst/ojs/commit/6c199a82b72cad73dadf15a0cfce42ad19c03539 (you can ignore the ArticleDAO-part, that was a fix for failed merge that was mistakenly included in the same commit).

I haven't verified that everything works as expected because I also had other problems, but this should at least give an indication of where there are incompatibilities between MySQL and PostgreSQL.

**Comment by Ph-We** [comment]
We had to use MySQL instead of PostgreSQL because of those issues.

**Comment by bozana** [comment]
Thanks @mittinatten! Those were my queries :-P I'll correct them as you suggested/tested i.e. separate the queries for MySQL and PostgreSQL, OK so @asmecher? THANKS!!!

**Comment by bozana** [comment]
@mittinatten, did you accidentally change the MySQL query in Upgrade.inc.php? And, because I do not understand what does this mean `SUBSTRING(iss.setting_value, \'\\.\\k+$\')` i.e. `\\k+$`, would maybe also this work: `CONCAT(LEFT( iss.setting_value, POSITION(\'.\' in iss.setting_value) - 1 ), \'_\', j.primary_locale, SUBSTRING(iss.setting_value, POSITION(\'.\' in iss.setting_value)))`? THANKS A LOT!!!

**Comment by mittinatten** [comment]
@bozana, I'm not at a computer where I can test things until tomorrow, then I can do some more thorough testing.

Yes, I simply overwrote the MySQL queries, so something needs to be done to separate the queries. As I said the commit is only intended to point to where there where conflicts between Postgres and MySQL, and there might still be errors. I had other unrelated problems, so I am not sure if this works as intended, but after these changes the upgrade script ran without stalling. And I am not so familiar with the intricacies of the context here, so I might have misunderstood something.

Right, the `\k+` should have been `\c+`! But perhaps checking for alphanumeric isn't good enough. I'm not sure what the input can be here, if there is only ever one period in the setting, your solution could work, but with `SUBSTRING(iss.setting_value from POSITION(...))` (*from* instead of comma). Otherwise the function `SPLIT_PART` might work, it's similar to `SUBSTRING_INDEX` (see docs here https://www.postgresql.org/docs/9.1/static/functions-string.html), not sure how it handles negative indices though.

**Comment by mittinatten** [comment]
To expand on the part you didn't understand, I was trying to do a regex for the substring after the last period. Probably something like `regexp_replace(iss.setting_value, '.*\.(\w+)$', '\1')` is better (where the backslashes and the single quotes will probably need to be escaped).

**Comment by asmecher** [comment]
@bozana, yes, separate queries for MySQL and PostgreSQL for non-standard SQL syntax would make sense. It looks like you and @mittinatten are moving ahead on this -- thanks to both!

**Comment by bozana** [comment]
@mittinatten, thanks a lot! I've found a PostgreSQL DB/installation, so I hope I will be able to test the upgrade script properly...

**Comment by bozana** [comment]
PR:
master: https://github.com/pkp/ojs/pull/1129

**Comment by bozana** [comment]
@mittinatten, I tested it and it worked for me, but it would be great if you could run the upgrade with this changes as well, just to double check/test: https://github.com/pkp/ojs/commit/8b7ccdd689e82adbc052f5146ebf43793f471e68. THANKS A LOT!!!

**Comment by bozana** [comment]
Maybe a note here: when abbreviation is used for the table that is being updated, PostgreSQL doesn't recognizes it. For example this line in the update statement:
`WHERE iss.setting_name = \'coverImage\' AND iss.locale = \'\' AND i.issue_id = iss.issue_id AND j.journal_id = i.journal_id'`.
The part `iss.setting_name = \'coverImage\' AND iss.locale = \'\' ` is not recognized correctly, so that all issue_settings were updated, not only those fulfilling this condition. 
Thus, I had to replace it with the full table name, i.e.:
`WHERE issue_settings.setting_name = \'coverImage\' AND issue_settings.locale = \'\' AND i.issue_id = issue_settings.issue_id AND j.journal_id = i.journal_id'`.
The same gilt everywhere in the update statement.

**Comment by mittinatten** [comment]
It seems to do the trick, as far as I can tell!

**Comment by bozana** [comment]
Thanks a lot! Can this issue then be closed?

**Comment by mittinatten** [comment]
Yes. Thank you!
