### ISSUE TITLE
OJS2->OJS3 upgrade corrupts file owner information

### ISSUE THREAD

**Issue by jprk** [pkp/pkp-lib#2105]
I have a bunch of submissions in OJS 2.4.5 where a submission is accompanied by a single note, which has a file attached (CrossRef output PDF for the submission file). When these submissions are being upgraded for OJS 3.0.1, not only the note file disappears from the view (see issue #1932), but also the submission file owner seems to be set to the owner of the note file ...

**Comment by jprk** [comment]
Could it be that `Upgrade::setFileUploader()` (see https://github.com/pkp/ojs/blob/051b64129e8ce516c166d549a859270934dcf1d9/classes/install/Upgrade.inc.php#L915-L920) called too early -- on files where the uploader information has not been extracted from OJS 2.4.x `article` table?

**Comment by bozana** [comment]
In OJS 2.4.x there is not always (if at all) information about the file uploader in the DB, that's why (almost) all are set to journal manager. S. this forum post mentioning that too: http://forum.pkp.sfu.ca/t/updating-from-ojs2-to-ojs-3-all-revisions-and-initial-copyedits-missing/26631. Also the discussion here: https://github.com/pkp/pkp-lib/issues/1805#issuecomment-2462764951.

**Comment by jprk** [comment]
Okay, but in this case I think that the information is there. I will try to
confirm when I am back at work...

--
odesláno z mobilního telefonu Xperia Ray
Dne 16.12.2016 17:10 "bozana" <notifications@github.com> napsal(a):

**Comment by bozana** [comment]
@jprk, can this issue be closed?
