### ISSUE TITLE
OJS 3.0.1: Statistics plugin needs additional testing

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#2134]
Statistics plugin logs are creating normally but very little information goes into metrics table.

maybe related (or not) errors upon processing logs:
huge number of this:
`PHP Warning: preg_match(): Delimiter must not be alphanumeric or backslash in .../lib/pkp/classes/core/PKPString.inc.php on line 342`

and
```
PHP Fatal error:  Uncaught Error: Using $this when not in object context in .../lib/pkp/classes/i18n/PKPLocale.inc.php:111
Stack trace:
#0 .../lib/pkp/classes/i18n/PKPLocale.inc.php(731): PKPLocale::translate('common.openJour...', Array, 'en_US')
#1 .../lib/pkp/classes/scheduledTask/ScheduledTaskHelper.inc.php(175): __('common.openJour...')
#2 .../lib/pkp/classes/scheduledTask/ScheduledTaskHelper.inc.php(142): ScheduledTaskHelper->getMessage('/home/doc/Docum...')
#3 .../lib/pkp/classes/scheduledTask/ScheduledTask.inc.php(153): ScheduledTaskHelper->notifyExecutionResult('585f963c671af', 'Usage statistic...', false, '/home/doc/Docum...')
#4 .../lib/pkp/classes/cliTool/ScheduledTaskTool.inc.php(113): ScheduledTask->execute()
#5 .../lib/pkp/classes/cliTool/ScheduledTaskTool.inc.php(95): ScheduledT in .../lib/pkp/classes/i18n/PKPLocale.inc.php on line 111
```

Don`t know if this problem is systemic or only on my server configuration (ubuntu 16, php 7.0)

**Comment by asmecher** [comment]
See https://github.com/pkp/pkp-lib/issues/2134 for a related forum discussion.

**Comment by asmecher** [comment]
@bozana, would you mind taking a look at this?

**Comment by bozana** [comment]
@Vitaliy-1, hmmm... it is difficult to figure out what's going on like this... it seems that your scheduled task is not successfully completed:

> #3 .../lib/pkp/classes/scheduledTask/ScheduledTask.inc.php(153): ScheduledTaskHelper->notifyExecutionResult('585f963c671af', 'Usage statistic...', false, '/home/doc/Docum...')

It seems that `$result` here https://github.com/pkp/pkp-lib/blob/master/classes/scheduledTask/ScheduledTask.inc.php#L153 is `false`. I.e. that this line returns `false`: https://github.com/pkp/pkp-lib/blob/master/plugins/generic/usageStats/PKPUsageStatsLoader.inc.php#L137. Would it be possible for you to debug it?

Also, do you see any errors in the scheduled tasks logs? They are in your files folder, under `scheduledTasksLogs/` beginning with `Usagestatisticsfileloadertask-`.

Could it maybe be that the files are not processed till the end?

Is there any chance you could give me your installation i.e. DB dump (with sensitive data removed) and those usage statistics log files, so that I could take a look?

**Comment by bozana** [comment]
I figured it out, why is it not working for you @Vitaliy-1: a few of your log files contains download link of a file that is not a galley, e.g. CSS file. When processed, the error occurs here: https://github.com/pkp/pkp-lib/blob/master/classes/statistics/PKPMetricsDAO.inc.php#L362 and the processing stops at that place. I will have to take a deeper look how those files should be correctly handled by the plugin.
But, I think there is also a problem how you process your files with the cron job, because all of them are always processed, I think -- They stay in usageEventLogs folder for some reason and your scheduledTasksLogs files always contain the same error messages from older log files.

**Comment by bozana** [comment]
I am not sure what to do with images and CSS files, for example, belonging to an HTML file, if they should be counted according to COUNTER i.e. by our usage statistics plugin? -- Eventually, they could be separately addressed via their own URL -- @ctgraham, do you maybe have an idea?

**Comment by ctgraham** [comment]
No, the AR1 and JR1 reports for COUNTER are concerned with full-text accesses only.  Supplementary files such as CSS and images should not be counted.

**Comment by Vitaliy-1** [comment]
I think I could try not to sync folders, but move files to stage folder with cron before processing. But I want to wait some time and not delete old logs. From 26 December metrics table is empty and maybe those logs  can be processed later. 

It is strange, but in my case autostaging is not working.  When I try: php tools/runScheduledTasks.php lib/pkp/plugins/generic/usageStats/scheduledTasksAutoStage.xml nothing happens.

**Comment by bozana** [comment]
@Vitaliy-1, the log files should be moved either to archive or reject folder after processing and stay there. The only strange thing is that your log files in archive folder, for example, differ from those in usageEventLogs -- they do not contain everything :-O Maybe also to run the cron job once per day? -- Because the plugin changes files and compares their names daily... 
I will take a look at the auto stage...

**Comment by bozana** [comment]
@ctgraham, then those URLs should not be logged at all, would you agree?
In OJS 2.4.x the HTML images had an URL something like ".../article/viewFile/<articleId>/<galleyId>/<fileId>" and are handled by the UsageEvent plugin here: https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/plugins/generic/usageEvent/UsageEventPlugin.inc.php#L219-L227, resulting in an entry in the log file with the URL like ".../article/download/<articleId>/<galleyId>". This is not quite right, but I believe also not so critical, because the URL could be removed by double clicks rule. But, however, maybe it would be better to have a check here, if the file is a galley file i.e. in the table article_galleys? What do you think @ctgraham and @asmecher? I would do the same for 3.x -- to check and not to log the files that are not galley/representation files...

**Comment by ctgraham** [comment]
To generate COUNTER compliant statistics (at least for JR1 and AR1 reports), the code should explicitly only consider URLs which are used for access to the full text of the article.

We shouldn't depend on the double click rule to filter these out - the code should be very particular in selecting only URL patterns which represent full text access from the very start.  `UsageEventPlugin::_buildUsageEvent()` should have an additional conditional statement to filter the delivery of these supplementary files from being counted as fulltext downloads.

**Comment by bozana** [comment]
OK, thanks @ctgraham! I will then try not to log those other files...
Also I think I will then have to take another look at OJS supplementary files (in OJS terminology) and how they are currently treated... :-\

**Comment by bozana** [comment]
PRs:
ojs ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1180

**Comment by bozana** [comment]
In OJS 3.x the HTML files usage is not logged, because of the missing `FileManager::downloadFileFinished` hook in the HtmlArticleGalleyPlugin, when the plugin is used.
I wasn't sure if I would need something like this before calling that hook: https://github.com/pkp/pkp-lib/blob/master/classes/file/FileManager.inc.php#L269-273
@asmecher, could you take a look at this PR https://github.com/pkp/ojs/pull/1181?

**Comment by bozana** [comment]
@Vitaliy-1, after you have tested the patches, you can comment here if it worded and maybe close the issue...

**Comment by Vitaliy-1** [comment]
Hi @bozana,

Sorry for delay. I will apply fixes on this weekend and report the result here.

**Comment by Vitaliy-1** [comment]
Log files are processed witout fatal error now. Thanks for the fix! Please keep in mind that autostaging still not work from terminal.

**Comment by bozana** [comment]
Hi @Vitaliy-1, I've just tested this: `php tools/runScheduledTasks.php lib/pkp/plugins/generic/usageStats/scheduledTasksAutoStage.xml` and it worked for me: the log files were in the folder `usageEventLogs` and were then normally processed and archived. For some reason, here is the frequency = hourly, thus, if you have a scheduled task `plugins.generic.usageStats.UsageStatsLoader` in your DB table `scheduled_tasks`, that is less than an hour old, maybe this is the reason? Note also that the log files should be older then a day in order to be processed by the plugin. Maybe to remove that frequency definition from the XML file and then try it out with your adjusted cron job (to use that XML and no copying to the stage folder)?  Or maybe to first remove that frequency and the scheduled task entry in the DB and to test it manually with one old file in the folder `usageEventLogs`, that is older than a day? 
I think I am going to remove that hourly frequency -- I don't know why is it so...

**Comment by bozana** [comment]
Hmmm... I fond the explanation why there is frequency in scheduledTasksAutoStage.xml, s. https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8687: 

> The scheduledTasksAutoStage.xml should stay with the frequency, because it's the one used by the AcronPlugin.

But I am still not sure why does this matter :-\ @asmecher or @ctgraham, do you maybe know?

**Comment by ctgraham** [comment]
The autostage method avoids processing the current day's file:
2.x: https://github.com/pkp/ojs/blob/dbe779f2bd97e9a0f2842c4357fb56496b7179e4/plugins/generic/usageStats/UsageStatsLoader.inc.php#L275-L278/UsageStatsLoader.inc.php#L251-L282
3.x: https://github.com/pkp/pkp-lib/blob/4772e4afa3463d8ab0b7d8f3df03f70db0f90add/plugins/generic/usageStats/PKPUsageStatsLoader.inc.php#L287-L290

I think because of these checks, acron *could* call scheduledTasksAutoStage as often as it wanted.   It just might mean a lot of extra cycles checking that directory on every request.

**Comment by bozana** [comment]
Ah, OK, thanks a lot @ctgraham! I'll leave it then...

**Comment by Vitaliy-1** [comment]
Closed this issue to early. Yesterday we have published an article that became popular among over colleagues. So I had an opportunity to check plugin in real settings. Upon publication I have noticed 7 view counts. Apparently from author and editors, which looked on the publication before it was published (directly from link).

Today on apache logs I see that this article was intensively viewed. Maybe >100 of unique ip`s from many device types. But there was still only 7 views on metrics table after processing logs. Comparing apache and stats plugin logs in real time, noticed that plugin logs were consistently missing ip`s .

So the problem actually is upon logs creating and not in parsing them

**Comment by Vitaliy-1** [comment]
@bozana , how this logs are created? they are parsed from apache logs with regex? Can you briefly describe the process?

**Comment by Vitaliy-1** [comment]
I have parsed with regex apache access.log. Changed the lines according to OJS , deleted logs from bots and my own. After successful parsing with stats plugin from metrics table I now can see near 200 views of our new article. So from apache logs all OK, and Stats OJS logs are not created normally. 

Also in my stat logs I see mostly administrative (my own) clicks and bots.

**Comment by bozana** [comment]
@Vitaliy-1, just to double check: Have you applied these fixes:
pkp-lib ojs-stable-3_0_1: #2170
ojs ojs-stable-3_0_1: pkp/ojs#1181

https://github.com/pkp/ojs/pull/1138
?

The logging in OJS uses UsageEventPlugin -- it creates an event. The UsageStatisticsPlugin is registered for the hook 'UsageEventPlugin::getUsageEvent' and when such an event from the UsageEventPlugin is triggered, the UsageStatisticsPlugin logs it.

Would it be maybe possible for you to open your usage statistics log file with "tail -f" i.e. to watch it in real time while accessing the article pages and to see what kind of events are logged i.e. not logged?

You said that the galleys are not logged correctly and it looks like the bug i.e. fix from above -- Actually after the fixes it should work... :-\ I will take a look at that once again...
Also, the URLs like this `http://e-medjournal.com/index.php/psp/article/view/15/25` (i.e. without file ID at the end) should never be logged/considered -- this page calls the file URL with the file ID that should be logged. I will have to check if the statistics calculation considers these kind of URL when reading from apache logs -- this would be wrong. 
Do you use OJS htmlArticleGalley plugin for HTML articles -- it seems the problem is there...

**Comment by ctgraham** [comment]
@bozana, when you say, "the URLs like this http://e-medjournal.com/index.php/psp/article/view/15/25 (i.e. without file ID at the end) should never be logged/considered", can you clarify your meaning here?  It certainly looks to me like this URL effects a view of the article fulltext, and should be captured.

**Comment by bozana** [comment]
@ctgraham, in OJS 3.0 this kind of URL only displays the galley file -- it is different than in OJS 2.4.x. Thus calling this URL, will call `download` function that contains 'ArticleHandler::download' that is then considered by UsageEventPlugin and that then creates the usage event. So only this file download is considered -- if we would also consider the URL (as above), the same file access would be counted double in OJS 3.x.

**Comment by ctgraham** [comment]
But in the case of XML/HTML publishing, I suppose there isn't really a distinction between "viewing" the fulltext and "downloading" the fulltext.  The COUNTER standard is interested in this activity (the user engaging the fulltext) whether we call it a "download" or a "view".

**Comment by bozana** [comment]
Yes that is true. In OJS 3.x the HTML file access is counted, just the different URL is logged, something like "...article/download/1/3/20".

**Comment by Vitaliy-1** [comment]
It seems there is no statics only for html galleys. And yes, I use html galley plugin, but I have modified display.tpl.  Can it somehow influence statistics?

I will check if I had applied all fixes and compare all my html galley plugin files with ojs-master branch in near time.

**Comment by Vitaliy-1** [comment]
Greetings @bozana 
I have double checked all fixes, I have missed some of them, but not crucial for  statistics (as i think). After revising the code checked once more, just in case - counts from html galleys are not recording into logs. Others galleys counts (xml, pdf) are logged  normal. 

As I said. mine display.tpl from html galley is completely modified, but I doubt that this can influence statistics., isn`t it?

in HtmlArticleGalleyPlugin.inc.php one line added. This one: https://github.com/pkp/ojs/pull/1219/commits/5e308cea65933ff9d2b0c6f08a78d600a30b4ecf 
No other modifications in OJS code, except in my child-theme and Lens Viewer plugin. 

Can my html file help in this problem solving?

**Comment by bozana** [comment]
I discovered one more issue: HtmlArticleGalleyPlugin uses ArticleHandler::download hook and returns true i.e. does not allow others, coming after, to use that hook. Because UsageEventPlugin also uses that hook, it will not get it, if HtmlArticleGalleyPlugin gets it first. Thus, HtmlArticleGalleyPlugin should provide such a hook for the other to be able to use it. 
PRs:
ojs master: https://github.com/pkp/ojs/pull/1239

**Comment by bozana** [comment]
@Vitaliy-1, I am not sure if the last PR above will solve your issue -- you changed the display process a little bit, so that it seems that both hooks (for article download and for finished article download) are not provided -- I will test it and let you know...

**Comment by bozana** [comment]
Hi @Vitaliy-1, because you changed the HtmlArticleGalleyPlugin so that content display already happens in articleViewCallback, the download hooks will never be called, that UsageEventPlugin is using. I will send you the changes needed for it to work for you, additionally to the last PR above (when it is merged).

**Comment by Vitaliy-1** [comment]
Many Thanks!

**Comment by bozana** [comment]
@Vitaliy-1, once you tested it and if OK, you can close the issue -- everything merged...

**Comment by Vitaliy-1** [comment]
Yep, now all views of html galleys are successfully recorded into usage_events logs.  Thanks once more :)
