### ISSUE TITLE
[OJS] Mailing Address should not be required in settings

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2169]
Hi,

Some of our journals do not have an actual mailing address, but the field in Settings => Contact => Mailing Address is required. I suggest that this should be changed if there is no greater reasons for keeping it required.

**Comment by asmecher** [comment]
Hmm, there's no academic affiliation the journal could use as a mailbox? That seems unusual to me.

**Comment by ajnyga** [comment]
This is what they told me. There are ways around this of course without chancing the code.

**Comment by asmecher** [comment]
@stranack and @willinsky, any thoughts on this one?

**Comment by NateWr** [comment]
@ajnyga is this still something you get requests for?

**Comment by ajnyga** [comment]
Not really, but looked through the `mailingAddress` setting in our db. Around 15 journals out of 110 have filled in something else than an actual mailing address to the setting with the value `-` being the most common. In many cases an email address has also been used. This implies that in these cases there is no postal address to use.

**Comment by willinsky** [comment]
Agreed that a "mailing address" is so 1999. But providing journals with a prompt to add an institutional, organizational, or business affiliation, along with its physical and/or URL location, may encourage them in a practice that serves journal integrity and transparency.

**Comment by NateWr** [comment]
Thanks for the data, @ajnyga! I think thosee are strong enough numbers to justify removing the required setting.

**Comment by asmecher** [comment]
@touhidurabir, one of the tests failed (not your fault, I've restarted it) but otherwise this looks good.

Next time I'd suggest keeping the submodule update in a separate commit of its own; this will help with inevitable merge conflicts.

Since this affects OMP, OPS, and OMP, and both the `main` and `stable-3_3_0` branches of each, I'm afraid you're going to have to create a whole bunch more pull requests:
- pkp-lib stable-3_3_0 (you've done this one: https://github.com/pkp/pkp-lib/pull/7852)
- OJS stable-3_3_0 (you've done this one: https://github.com/pkp/ojs/pull/3370)
- OMP stable-3_3_0
- OPS stable-3_3_0
- pkp-lib main
- OJS main
- OMP main
- OPS main

Please summarize all the PRs in a comment on the issue (here) to help keep them all together for the code reviewer. Fortunately it's rare to have to open this many PRs for such a simple change!

**Comment by touhidurabir** [comment]
All pull requests 

[pkp-lib](https://github.com/pkp/pkp-lib) stable-3_3_0 --> https://github.com/pkp/pkp-lib/pull/7852
[ojs](https://github.com/pkp/ojs) stable-3_3_0 --> https://github.com/pkp/ojs/pull/3370
[ops](https://github.com/pkp/ops)  stable-3_3_0 --> https://github.com/pkp/ops/pull/270
[omp](https://github.com/pkp/omp) stable-3_3_0 -->  https://github.com/pkp/omp/pull/1104

[pkp-lib](https://github.com/pkp/pkp-lib) main --> https://github.com/pkp/pkp-lib/pull/7865
[ojs](https://github.com/pkp/ojs) main --> https://github.com/pkp/ojs/pull/3375
[ops](https://github.com/pkp/ops) main --> https://github.com/pkp/ops/pull/271
[omp](https://github.com/pkp/omp) main --> https://github.com/pkp/omp/pull/1105

**Comment by touhidurabir** [comment]
@asmecher can you merge the PR after reviewing it ? Tests failed for both the OMP stable-3_3_0 (https://github.com/pkp/omp/pull/1104) and main (https://github.com/pkp/omp/pull/1105) but i think those are due to some other race condition , not related to the changes for the PR . can you also reinitiate the tests also to make sure it all passes .

**Comment by NateWr** [comment]
@touhidurabir I've restarted those tests for you. I'll leave the final merge to Alec. :+1:

**Comment by asmecher** [comment]
All merged -- thanks, @touhidurabir!
