### ISSUE TITLE
Template variables appear in some email subjects

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2179]
Some cases were reported in which template variables (eg - `{$contextName}`) appear in prepared email subjects. An example:

> Workflow: Fix {$contextName} from prepared email subject line menu

Some of these may already have been fixed. Another round of testing is needed to see if any more remain.

From the UI/UX outcomes spreadsheet: https://docs.google.com/spreadsheets/d/1RkZ0avL3UIUU-hUScbM77lLCsGtk-T2_dL-FEx_vKcM/

**Comment by defstat** [comment]
Do we have any example that fails for this?

It seems that there are 3 Template variables appearing in email subjects:
- $siteTitle: That seems to be covered here https://github.com/pkp/pkp-lib/blob/master/classes/mail/MailTemplate.inc.php#L178
- $contextName That seems to be covered here https://github.com/pkp/pkp-lib/blob/master/classes/mail/MailTemplate.inc.php#L158
- $giftNoteTitle That is covered here https://github.com/pkp/ojs/blob/master/classes/payment/ojs/OJSPaymentManager.inc.php#L435

An email could not have the first 2 variables if 
- The https://github.com/pkp/pkp-lib/blob/master/classes/mail/MailTemplate.inc.php#L148 function is not called before sending an email
- The call is not made inside a context, so the https://github.com/pkp/pkp-lib/blob/master/classes/mail/MailTemplate.inc.php#L153 fails. 

The cases where the $siteTitle variable is used in email subject are:
- NOTIFICATION https://github.com/pkp/pkp-lib/blob/master/classes/notification/PKPNotificationOperationManager.inc.php#L449
- NOTIFICATION_MAILLIST https://github.com/pkp/pkp-lib/blob/master/classes/notification/PKPNotificationOperationManager.inc.php#L294
- NOTIFICATION_MAILLIST_WELCOME https://github.com/pkp/pkp-lib/blob/master/classes/notification/form/NotificationMailingListForm.inc.php#L65

In all the above cases, the `assignParams` function is called

The cases where the $contextTitle variable is used in email subject are:
- REVIEWER_REGISTER https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/reviewer/form/CreateReviewerForm.inc.php#L121
- NOTIFICATION_CENTER_DEFAULT https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L67 and https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L88

In all the above cases, the `assignParams` function is called, and the action seem to be called from within a context.

We could, perhaps, change the https://github.com/pkp/pkp-lib/blob/master/classes/mail/MailTemplate.inc.php#L114 and call the `assignParams` instead, so that we don't need to bother with the "default" variables anytime we declare a new MailTemplate.

**Comment by NateWr** [comment]
@defstat: sorry for the late response to this. I'm not familiar with the email code. I went back to the original report and don't see any indication of which email template this variable name appeared on. Sorry I'm not much help, but maybe this issue can be closed unless we get a fresh report.

I like your suggested with `assignParams` but not familiar enough with the code to know what impact it will have. I'd suggest maybe running it past @bozana.

**Comment by asmecher** [comment]
I haven't seen any examples of this either despite a lot of poking around, so I'd suggest closing it for now.
