### ISSUE TITLE
Permit submissions to remain in workflow lists after addition to catalog

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2199]
From [SI row 12](https://docs.google.com/document/d/1R4Emgriw_7sLIhVziI6SSf8c-_tFIA2ckrV8e8FqTNM/edit):

Currently adding a submission to the catalog (IIRC) triggers the submission to change from `STATUS_QUEUED` to `STATUS_PUBLISHED`, which also removes the submission from active lists in the dashboard.

It's common for workflows to continue on books (more so than journal articles) after that stage, so the removal of submissions from active lists should be tied to something else instead.

**Comment by NateWr** [comment]
What could it be tied to? Should we instead defer the status change until the published date is reached?

**Comment by asmecher** [comment]
Hmm, that's the only good contender I can think of. We could add a final decision, akin to "schedule for publication" in OJS and appearing in the same place, but as its only role would be to remove it from the active lists I suspect it would cause confusion.

**Comment by NateWr** [comment]
Hmm, the data model could get pretty ugly here. Currently, the `status` column in the `submissions` table indicates if a submission is incomplete, in the workflow (queued), published or declined. I think we need to split this out into two columns: `status` and `published`.

`status` would track the submission's progress through the editorial process: in-progress, queued, declined, and archived (formerly published).

`published` would track whether the submission is publicly available or not, regardless of it's `status`.

It seems like we should be able to use the `published_submissions` table to track the `published` status. But I think you've said in the past that this won't work because a submission can have an entry there before it is publicly available. That makes me wonder why we have the separate table at all. But now I'm getting away from myself.

Regardless, having a separate column to track published status might also help with the continuous publishing model, pre-prints, and other cases.

**Comment by asmecher** [comment]
We have an approval model for publication formats that might be useful here: "Complete" and "Available".

"Complete" is a workflow consideration, i.e. as the editor stewarding this through from rough draft into something ready for publication, is it complete?

"Available" is a marketing consideration, i.e. we want this to go out in January after the holiday rush has subsided, is it time yet?

I'm not sure where we would put this, but this distinction could be useful here too, i.e. we already have "available" figured out, but we're missing "complete" (which would remove it from the in-process queues).

**Comment by asmecher** [comment]
A screenshot of the above concept in action for publication formats:

![image](https://user-images.githubusercontent.com/200411/34313467-1c4f2506-e720-11e7-829d-d434d946e545.png)

**Comment by NateWr** [comment]
One idea: we've already got "Schedule for Publication" in the production stage. Maybe when someone is scheduling for publication, we can have a pre-checked checkbox "Archive this submission". That way the workflow doesn't change for most people -- they schedule for publication and it gets placed into the archive.

In cases where someone un-checked the checkbox, a submission would be scheduled but not archived. Then we could add an "Archive" button below the "Schedule for Publication" button which would allow them to archive at their leisure. (They'll also be able to archive from the submission list -- eventually).

**Comment by NateWr** [comment]
Have we had any other requests for this in the last 4 years?

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
