### ISSUE TITLE
Custom Locale Plugin: ordering of fields 

### ISSUE THREAD

**Issue by Glottotopia** [pkp/pkp-lib#2228]
I tried to change the locales at 
http://langsci-press.org/management/settings/website > plugins > locales
"locale/en_US/locale.xml'

I am offered 16 pages. The locale fields are presented in a semi-ordered fashion. I give an excerpt:

page 1

- `monograph.task.addNote` 	
- `monograph.accessLogoOpen.altText 	Default Text`
- `monograph.publicationFormat.imprint`

...

page 9 
- `common.listbuilder.itemExists` 	
- `common.openMonographPress`
- `common.omp`

...

page 16
- `debug.notes.helpMappingLoad` 	  
- `rt.metadata.pkp.dctype`
- `plugins.categories.viewableFiles`

It is difficult for me to see the guiding principles behind this ordering. The field I was looking for was on page 9, but there was no way of know this.

Suggestion: order the fields alphabetically

Furhter suggestion: get rid of pagination and present all fields in one dialog. Then, users can CTRL-F the thing they are looking for. Clicking through 16 pages worth of dialogs in an unordered list of fields, as it is now,  has obvious problems in UX.

**Comment by asmecher** [comment]
@Glottotopia, the Custom Locale plugin is something Carola wrote -- I'd suggest filing this issue at https://github.com/langsci/customLocale. An alternative to changing the sorting would be to either work on searching, or to rearrange the UI of that plugin based on user requirements ("I want to override a locale key that's called `a.b.c` or has English text `xyz`) rather than listing the files, which users of the plugin generally won't want to know about, I suspect.
