### ISSUE TITLE
File revision names

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2235]
File revision names are based on the first file revision name i.e. this is what is per default provided for the further revisions. The other file revisions could however have a different format: for example the first file could be a `.doc` but the next revision of the file could be a `.pdf`. The next revision would per default provide the name with `.doc`. This can still be edited, but maybe it would be however better to base the name on the current file name? This is especially important in the migration of the revisions from OJS 2.4.x, because there, the file revision name is as the first file name. In this case if someone would like to download the file revision the user will see `.doc`, but actually it will be a `.pdf` document.
s. discussion here: https://github.com/pkp/pkp-lib/issues/2097

**Comment by ajnyga** [comment]
Today we had first case where the user had uploaded a file with a name like "article 2016-10-5.docx" and could not figure out why she was not able to upload a new revision called "article 2017-1-25.docx" to the system.

Of course she could but the file name still included the original name of the file which was of course confusing. So this is not just a case of file formats in the file name.

**Comment by ajnyga** [comment]
Hi @bozana and @asmecher 

We had a new problem with the current file naming ($user-role, $filename) convention in OJS.

Some of the authors have sent new revisions of articles and have written their own name to the original filename. The editors, still learning how to use OJS, have not realized that once they start a new review round the label in the new review files, based on the author revisions, have had the name of the author in them. This has now led to two situations where blind review was compromised.

Of course this should be noticed by the editor, but even then chancing the label is actually very difficult. I think that you would have to first download all the files and then upload them again? At least I did not find a way to just edit the label?

This is however an issue with the **upgrade** from OJS2 to OJS3. I believe that for the ongoing reviews the upgrade will just use the original filename in the label and in many cases this could mean a file name that includes the authors name. In our case this was not an issue, because I modiefied the upgrade script to use the original naming convention in the labels (like 58040-58388-RV).

So these are the problems with the current file naming convention:
- The file extension is shown in the name and does not change although a revision file is in different format
- The fact that the original filename is shown there may raise questions among the authors. Think of a situation where author uploads a file called "my-article.docx" to OJS and later comes back to upload a revision named "my-revised-article-final.docx". After uploading that new revision, system is still showing this name the author: "Username, Author, my-article.docx".
- the original file name may contain sensitive information, like the authors name

I still think that this format would be actually more informative:
Not blinded: [Username], [Role],[Component][#id] [(#Rev)]
Blinded: [Role],[Component][#id] [(#Rev)]

This would look like "ajnyga, Author, Article text 2341 (2)" or "Author, Data set 4233".

The file format could be visible in the icon in front of the file label

**Comment by bozana** [comment]
@ajnyga, I think the file names can always be edited i.e. changed.
Concerning the file naming: @asmecher, what do you think about the suggestion? -- It seems good to me, but maybe I do not have a complete overview + do not know the original decisions/reasons/...

**Comment by ajnyga** [comment]
HI @bozana. I could not find an easy way to change the label of the review file, there is no option "Edit" there. Of course you could change the label from the previous round when the file is in the revisions listing. There the "Edit" button is available. 

An alternative way for naming would be to update the last part of the label, when a revision is loaded. That would solve the problem with file extensions and with the chancing file name.

**Comment by bozana** [comment]
Ah OK @ajnyga, I was looking at the Revision files and there I could change the name...
Lets see what Alec says about general change of the file names. If they should stay as they are, we could maybe see how to consider those different file names and endings...

**Comment by ajnyga** [comment]
This probably needs more feedback from other editors/platforms in any case.

**Comment by knjigor** [comment]
Hi,
I have just left an topic regarding this on forum http://forum.pkp.sfu.ca/t/submission-track-names-of-files/30430
Naming files like that is problematic if blind peer review is used, my opinion is that it would be best if file could be named after submission number, like in case below: 
insted of 
igor_lekic, Аутор, Rad_za_goddisnjak.docx

it should be simply named 
3455-1, Аутор, Rad_za_goddisnjak.docx

![author2](https://cloud.githubusercontent.com/assets/1343947/25224364/7b5edcf4-25be-11e7-9527-26788fc61ad4.png)

**Comment by knjigor** [comment]
BTW,
Where could I change this in 3.0.2.0?

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2455
ojs master: https://github.com/pkp/ojs/pull/1358 (only submodule update)

**Comment by bozana** [comment]
@asmecher and @NateWr, could you please take a look at this change: https://github.com/pkp/pkp-lib/pull/2455? 
It changes how the file names are handled: till now, if an author uploaded a file and then a journal manager uploaded a revision of that file, the file name would not change. For example, if the author uploaded a file with the name "author1, Author, 1-2-1-RV.doc", the journal manager revision would have the same file name, instead of e.g. "jmanager, Journal manager, 1-2-2-RV.pdf".
This can lead to a situation where some file names in review stage are not anonymized per default, because of this code line: https://github.com/pkp/pkp-lib/blob/master/classes/submission/SubmissionFileDAODelegate.inc.php#L104, because the "==" condition is not met -- "author1, Author, 1-2-1-RV.doc" is not == "jmanager, Journal manager, 1-2-2-RV.pdf" (the function _generateName uses always the current file original name and not the one of the first revision).
I think it makes sense to always rename the file when uploaded and to have the correct last file name (together with the file ending). 
And I would actually also prefer to change the patterns for the file names, maybe as @ajnyga suggested above, i.e. not to contain the original file name because it could contain sensitive information.

**Comment by ajnyga** [comment]
This is a tricky thing, because at the same time I also see the benefit of having the actual filename in the label.  So maybe even:
Not blinded: [Username], [Role],[Component][#fileid],[Original filename] [(#Rev)]
Blinded: [Role],[Component][#fileid][(#Rev)]

Anyway, thumbs up for the new feature that the label is rewritten when the filename changes.

**Comment by bozana** [comment]
Well maybe then to leave the pattern as it is for now, just the change in the PR above...

**Comment by NateWr** [comment]
@bozana, so in the examples above, `1-2-2-RV.pdf` is the filename that's uploaded, correct? If so, then that sounds good to me. As long as there is some remnant of the name that connects the two revisions so that people can easily distinguish between two different types of files (eg - full article, supplementary data set).

**Comment by bozana** [comment]
> As long as there is some remnant of the name that connects the two revisions so that people can easily distinguish between two different types of files (eg - full article, supplementary data set).

@NateWr, what do you mean here? 
`1-2-2-RV.pdf` is the original name of the file uploaded second time. It could be anything, depending how the user is naming it locally.
The revision number is always displayed for the user, so the user would then see something like "jmanager, Journal manager, 1-2-2-RV.doc (2)"
Do you think we should then consider the "Component" (e.g. "Article text") or fileId in the default file name as well?

**Comment by NateWr** [comment]
No, sorry, I meant the original name of the uploaded file. We don't need to include the component in the naming scheme. Sounds like you've got it covered.

**Comment by asmecher** [comment]
Just FYI, I've fallen way behind on this thread -- @bozana in particular, let me know if there's still an open question for me. Thanks!

**Comment by asmecher** [comment]
@bozana, I think this broke the OMP tests -- see https://travis-ci.org/pkp/omp/jobs/224472530. The filenames in the Publication Formats grid are expected to be titled after the chapter (`Bomb Canada and Other Unkind Remarks in the American Media`) but instead they're e.g. `callan, Author, bombcanadaandotherunkindremarksintheamericanmedia.pdf`.

**Comment by bozana** [comment]
yes, I am repairing it... coming...

**Comment by bozana** [comment]
maybe also a not: now the file names will eventually also change when a file is copied from one stage to another -- if the original file name has been changed. I think this is OK -- the user can always rename it, if necessary. Maybe then just to see, that editing the file name is possible in each grid?

**Comment by asmecher** [comment]
Yes, that's possible too -- but either way the tests do need to be fixed, and with this change in place, I suspect the name will have to be changed in the test scripts to ensure that the resulting presentation on the front end doesn't include a raw-looking filename.

**Comment by bozana** [comment]
Could we leave that 'raw-looking' filename? -- because it is then in every workflow stage, because this is how we build the original file name. In other case we could either:
-- change how we construct the original file name to be the same as the title (i.e. containing upper letters + spaces, for example), but it would also contain the file ending + what about other special characters?
-- change it only for that failing test, but it would need a few more clicks, but why only for this case?
-- change it for all workflow steps in tests, but this would need a few additional clicks each time
-- or to generally generate new file names only if it is an file upload or review stage
Hmmm... Those file names... :-\

**Comment by asmecher** [comment]
The file in the failing test is being brought forward from a previous stage in which it had the full descriptive name. I think this will be confusing if the same name isn't used when the file is pulled forward.

**Comment by bozana** [comment]
Yes, that would be now always the case, thus we should change it :-( So actually, the new file name should only be generated if it is a file upload or review stage (here we have to generate a new file if we want to try to assure anonymity), right?

**Comment by asmecher** [comment]
Yes, I think so.

**Comment by bozana** [comment]
OK, I did a new fix: new file name should be generated only if it does not exist, it it is a file upload or review stage. Tomorrow I will fix a PHP 7 test failure and then merge if OK:
pkp-lib master: #2463
omp master: pkp/omp#405

**Comment by bozana** [comment]
@asmecher, could you take a look at the PRs above?

**Comment by asmecher** [comment]
Thanks, @bozana, that got a lot more involved with the test suite than expected! It looks like the tests are OK (at least for OMP) -- once they pass, please go ahead and merge.

**Comment by bozana** [comment]
@asmecher, I merged not to have to rebase and ... again, but there was one test failure with StaticPages. Do you maybe know what that is, if it is accidentally or so?

**Comment by bozana** [comment]
else, everything merged, thus closing...

**Comment by asmecher** [comment]
@bozana, I've restarted those tests -- they don't seem to have failed consistently, suggesting a server hiccough or something. We'll see if they pass this time. Those tests have been working pretty reliably as far as I can recall.
