### ISSUE TITLE
[OJS] Migrated submissions have a review round even when the submission is in stage 1

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2247]
OJS 3.0.1. upgraded from 2.4.8.1.

All submissions seem to have a review_round active in review_rounds table although the submission was in stage 1 during the upgrade.

Sending the submission to review thus creates round 2.

**Comment by bozana** [comment]
Hmmm... I think this is not relevant any more. But I am also not sure if the current behavior is correct:
In OJS 2.4.x there is immediately a review round and a review file for a submission, even if an editor was not assigned yet. This is different in OJS 3 -- first when an editor is assigned and the button "Send to Review" pressed, there will be a review round and a review file.

Now, after the migration, also the submissions that had no editor assigned in the OJS 2.4.x will be in the stage = 3 (review). I believe, this is due to this change: https://github.com/pkp/ojs/commit/8505c977a28e97d1c86f844861022d58fe412b5a#diff-86ab16342e4f84f289e003915a308edc.

@asmecher, do you think it can stay like that or shall we rather do something like: If an editor is not assigned in OJS 2.4.x, remove the review round and the review file when migrating to OJS 3 and thus leave the submission in the stage = 1. If an editor is assigned (and thus the article is "In Review") in OJS 2.4.x, add an entry into the edit_decisions table with decision = 8 and set stage_id = 3 for that submission (as it is now).

**Comment by bozana** [comment]
PR:
ojs master: https://github.com/pkp/ojs/pull/1489

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PR?

**Comment by asmecher** [comment]
Sorry for the delay in getting to your earlier comment. Hmm, I don't love this kind of intervention, but I agree that it's justified in this case. The code looks good. Have you tested it on a couple of OJS 2.x to 3.x upgrades?

**Comment by bozana** [comment]
@asmecher, I have tested it locally with my testing data. 
@jmacgreg and @ajnyga, do you maybe have some OJS 2.4.x data (with articles that are not in review yet) I could test this on?

**Comment by ajnyga** [comment]
I do have our old OJS2 installation as it was back in January and there are probably several such articles. I have a few things I have promised to do, so not promising anything. But probably I will have time to test this before 3.1. I mean, I could test some other things as well at the same time.

**Comment by ajnyga** [comment]
@bozana, as noted above I can probably test this, but do you know if there will be problems if I run the upgrade process without the files or public folder contents?

**Comment by bozana** [comment]
@ajnyga, hmm... the patch should remove the wrong/unnecessary review files in the files_dir. Thus you will get the error messages. But, maybe you can ignore them and just check the results...

**Comment by bozana** [comment]
I am closing the issue. @ajnyga, if you find something, it can be reopened...
