### ISSUE TITLE
Sort submission lists by ID

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2270]
See: http://forum.pkp.sfu.ca/t/ojs-3-can-submissions-be-sorted/28304/3

**Comment by librariam** [comment]
Re-opening the ticket following Michael's suggestion, since sorting by ID is not in the latest OJS 3.1.2. This was brought up by a hosted client.

**Comment by asmecher** [comment]
@NateWr, this was probably re-introduced by the submission lists query builder code. Was it an intentional change? Any objections to re-introducing sort by submission ID as a default there?

**Comment by NateWr** [comment]
Are we sure that this is the case? I am unable to reproduce this in `stable-3_1_2`. All submissions appear ordered by ID.

**Comment by librariam** [comment]
@NateWr it's certainly not the case with every journal. I've looked through a few to find examples. The below screenshots are from "All Active" list from 2 different instances (order numbers added by me):

Example 1
![submissions not in order1](https://user-images.githubusercontent.com/45104797/67291103-0f05c000-f4af-11e9-8235-1671f15f6b5d.jpg)

Example 2
![submissions not in order2](https://user-images.githubusercontent.com/45104797/67291118-17f69180-f4af-11e9-87d2-cab50157afc8.jpg)

I hope this helps - let me know if you need me to check further details of these submissions.

**Comment by NateWr** [comment]
Ok, it looks like they should be ordered by `date_submitted`. In all circumstances I'm aware of the `date_submitted` order should match the `submission_id` order. This will always be the case unless the `date_submitted` is manually set somehow -- possibly through an import of some kind?

Do you know if these journals have imported submissions or otherwise modify the usual submission process?

**Comment by librariam** [comment]
Hmm that's an interesting question. Journal 1 migrated in 2017 and Journal 2 in early 2019. Native XML import-export was used to transfer articles and issues in Journal 2; definitely no modification to the usual submission process. Not sure about Journal 1 but I can find out. None of the articles in the screenshots are from those transfers though, these are all recent submissions.

**Comment by NateWr** [comment]
Ahhhhh ok. So here's what's happening. The `id` is created when a submission is _begun_ (when step 1 of the submission form is completed). The `dateSubmitted` is stamped when a submission is _completed_ (when step 4 of the submission form is completed).

So what you're seeing are cases where an author A began submitting on Monday, saved the submission for later, and came back on Wednesday to complete the submission. On Tuesday author B began and completed a submission.

A's submission will have a lower `id` but a later `dateSubmitted` value, so it will appear above B's submission in the list.

I appreciate that this can be confusing. But I think it's the correct behaviour. Consider what would happen if we sorted by `id` instead of `dateSubmitted` in the following situation:

The high-volume journal receives 50 submissions per week. I begin a submission, but due to some circumstances I don't complete it for 2-3 weeks. When I finally complete it, my submission will not appear as the latest submission to the editor. It will be buried under 100-150 other submissions.

If the journal has an assigning editor who does all their assigning each week, they may not see mine down the list, passed the submissions that have already been assigned.

**Comment by librariam** [comment]
Thank you, @NateWr this makes perfect sense - and it's valuable to have the behaviour documented here in case of any further questions.
