### ISSUE TITLE
Review/fix edit links

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2312]
See http://forum.pkp.sfu.ca/t/wrong-edit-link-for-author-guidelines-ojs-3-0-2/28971

These edit links were (and probably still are) a good idea, but should probably be checked against our overall UI/UX plans, and applied more broadly so they're less of an aberration.

**Comment by defstat** [comment]
The editLinks that are currently in code are:
1. https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/contact.tpl#L25
- The link goes to press#contact and not to journal#contact, maybe because of some fix for OMP. If that's the case, how can we distinguish the two, as the code is in pkp-lib?
- Maybe we should put a general title there so that the editLink will not be next to breadcrumbs?

2. https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/submissions.tpl#L37

3. https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/submissions.tpl#L54
goes to management/settings/journal#guidelines and not to management/settings/publication#submission

4. https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/submissions.tpl#L64
goes to management/settings/jjournal#guidelines and not to /management/settings/distribution#permissions

**Comment by asmecher** [comment]
@defstat, that's probably a case where we can swap out the app-specific terminology (journal/press) for the app-independent term (context).

**Comment by defstat** [comment]
@asmecher PR #2369 pkp/ojs#1322

**Comment by asmecher** [comment]
Thanks, @defstat -- I think some of this might need porting to OMP too.

**Comment by defstat** [comment]
@asmecher PR pkp/omp#398

**Comment by defstat** [comment]
New PRs
#2379 
pkp/ojs#1330

**Comment by asmecher** [comment]
All merged -- thanks, @defstat!
