### ISSUE TITLE
Rewrite OAI NLM plugin for OJS 3.x

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2358]
See http://forum.pkp.sfu.ca/t/harvesting-ojs3-with-oai-nlm/29356

**Comment by ctgraham** [comment]
In the forum, @asmecher mentions the original plugin "never generated particularly good NLM XML in OJS 2.x, because OJS doesn’t have access to sufficient semantically rich information about the documents it handles".  One big concern with the original plugin output is that it lists all current editors and journal managers (at the time of metadata presentation) as contributors to the article.  What other flaws are known in the original implementation?  Does OJS 3.x consider editorial history at the article level better than OJS 2 does?

**Comment by asmecher** [comment]
Fundamentally the problem is that the OJS2 NLM plugin was written for a single use case -- submitting content for indexing for the [Synergies project](http://www.synergiescanada.org/) -- and sometimes data was shoehorned into that without much regard for the general-purpose standard. In the rewrite, our driving use case is currently a similar one, but I'm trying to approach it with better respect for the standard.

The editorial history situation hasn't changed much, unfortunately.

**Comment by ctgraham** [comment]
Another potential use case is general harvesting of metadata and associated article files.  We're considering a mandate from the Library of Congress to deposit metadata and article files, and I want to be able to just point them at OAI-PMH and be done.  Dublin Core, MARCXML, etc. doesn't sufficiently identify the article files to facilitate automatic harvesting, but NLM could identify article files and supplementary files, if I'm reading the spec correctly.  LoC has also expressed a preference for NLM metadata, so that weighs into the possible use-case as well.

**Comment by asmecher** [comment]
@ctgraham, you can follow its progress over here: https://github.com/pkp/oaiJats

However, note that it depends on using Open Typesetting Stack to convert source documents into JATS -- it doesn't attempt to produce native JATS internally.

**Comment by Abdull** [comment]
From all metadata prefixes available in previous OJS releases, `nlm` was the most useful prefix available for our harvesting use cases at DSpace-based https://www.ssoar.info/ssoar : NLM provided the most granular metadata organization (e.g., separate first name and last name XML elements) and the easiest XML schema for post-harvesting XSLT processing.

Regarding the statement that the particular OJS plugin "*never generated particularly good NLM XML in OJS 2.x*": For our use cases, the plugin performed well!

I'd be great to have NLM running again in OJS 3.x and onwards, as SSOAR already has working pre-OJS-3 OAI-PMH harvesting integrations which rely on an available `nlm` metadata prefix.

It just happened that one of our OJS-based content providers migrated to OJS 3, and a successful harvesting integration just broke because of the missing `nlm` metadata.

I expect to have more of our OJS integrations to break in the upcoming months when more of those journals migrate to OJS 3.

**Comment by asmecher** [comment]
@Abdull, we had similar uses for the NLM plugin internally, but it was far from compliant NLM XML so we chose to replace those exchanges with proper JATS XML generated by Open Typesetting Stack and delivered via OAI using the oaiJats plugin (linked above). I'd suggest considering something like that, if you haven't looked at it already. It's more complex but the quality of XML is much higher (and closer to compliance).

**Comment by bkawula** [comment]
We here at Scholars Portal / OCUL are also a bit stuck without the NLM harvesting functionality since we technically inherited the remnants of the Synergies Project. We were still using it to harvest a number of journals for archiving in our TDR repository, which also uses JATS for metadata. Our plan was to harvest ALL of the OJS instances in Ontario until we discovered there's no NLM plugin in OJS3.

The plugin allowed us to harvested data that we could load directly into our document db and it was perfect for presentation and retrieval. None of the other metadata formats have the same level of description. I really wish you would reconsider adding this back to the OAI-PMH.

**Comment by asmecher** [comment]
@bkawula, we have recently been talking about reintroducing this plugin internally. If we do, I'll post details here as they become available; your help with testing and review would be much appreciated.

**Comment by bkawula** [comment]
Fantastic! I'll be more than happy to test.

**Comment by odolany** [comment]
Also ready and willing to help with testing (and in the same trouble of upgrading content providers at [CEJSH](http://cejsh.icm.edu.pl/cejsh/about)

**Comment by asmecher** [comment]
Hi all -- this work has already begun. The functionality of the old `nlm` OAI format plugin will actually be replaced by two plugins:

- https://github.com/pkp/oaiJats to add JATS support via OAI
- https://github.com/asmecher/jatsTemplate to generate a basic JATS template from scratch

This is in order to facilitate and deliver JATS XML that might come from a variety of places.

**Comment by bkawula** [comment]
I just got this running and it looks great! Thank you so much. If I run into any issues I'll post them to the respective repos.

**Comment by asmecher** [comment]
Thanks, @bkawula!

**Comment by asmecher** [comment]
Considering this done! The two plugins are in the plugin gallery and maintenance will continue there.
