### ISSUE TITLE
[OJS] Upgrade scripts trip over deleted contexts

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#2374]
When attempting to upgrade OJS from 3.0.0-0 to 3.0.2-0, we ran into [a mysterious problem](http://forum.pkp.sfu.ca/t/bug-in-ojs-3-0-0-3-0-2-upgrade-on-postgresql/29525). It turned out to be due to trying to find user groups for a journal which had been deleted.

Since journal deletions do not destroy history of things like submissions, the upgrade scripts need to be bulletproof with respect to possibly-missing contexts.

This goes for OMP, too though I haven’t (yet) observed this problem there.

**Comment by bozana** [comment]
I am not sure if this is a bug now -- it is maybe good that the upgrade script stops because the data in the DB are wrong -- there seem to be entries from an old journal in the DB, that does not exist any more -- it could be maybe an earlier bug, that didn't clear all the data, when deleting a journal. The correct way would be to remove that old data, or? And I am not sure, we could check and remove them programmatically?
@asmecher, what do you think?

**Comment by crism** [comment]
It is definitely not good that the upgrade script stops. It leaves the database in a half-formed state, usable by neither the old nor new versions of the software. The upgrade script should either:

1. scan for incompatibilities and refuse to run,
1. use transactions and roll back if a problem arises, or
1. be bulletproof and succeed regardless of what’s in the database.

When this crash arises, the browser just comes up with a blank screen/500 error, and a message is written to the error log. That’s not acceptable under any circumstances.

**Comment by bozana** [comment]
Yes, ideally it would work like that -- but... the first two would mean so much work on the upgrade process and I am still not sure that we would succeed to check and roll back everything, especially for this upgrade from 2.4.x to 3.x. Because we were not able to do that yet, we always recommend users to do the full backup of everything and take a detailed look on the notices during the upgrade process, so that they can restore and correct it. About the third point I am not sure -- this might make sense for the error explained here, but probably not for everything else... 
But, Alec has surely better overview than me... :-)

**Comment by bozana** [comment]
Ah, maybe just one thing: we could definitely catch that error and return the appropriate message, so that the upgrade does not stop...

**Comment by asmecher** [comment]
I think it's practical for us to improve the error messages, but at the moment, not to roll back in case of failure. Checking and failing before actually running the upgrade would not be reliable, I don't think. I'm not sure barreling through regardless is a good approach, either, because certain kinds of data problems need manual intervention and it would result in us discarding data in the process.

Part of our longer-term upgrade plans are to look at options for replacing ADODB, which you're probably aware is gifting us with a number of complications. That's longer term, however, and it's likely that we'll be well post-3.0 by that point. When we do that I suspect we'll look into discarding upgrades previous to a certain version (e.g you'd need to use OJS < 3.2 to upgrade from OJS 2.x, then start with the new tools at say OJS 3.2), so it wouldn't be much help here.

Meanwhile, as per the upgrade docs, it's necessary to take a backup before upgrading and restore to it upon failure. OJS has quite a large database schema (compared e.g. to Wordpress), and more than a decade of releases, so there's a lot of potential for weird data inconsistency in the old database.

**Comment by crism** [comment]
Sure, @bozana and @asmecher—I should have included option 4, which is a clear error returned to the user. The strong recommendation to back up the DB before upgrading is clear, and a known and accepted risk. It’s really the blank, silent 500 failure that’s unacceptable.

**Comment by NateWr** [comment]
Work on improving the upgrade process is ongoing in several other issues. Closing because the specific issue reported here is not going to be addressed.
