### ISSUE TITLE
[OJS3] Issues with Citation Formats

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#2390]
Hi!

1. **Endnote**: the `%P` and `%@` fields are concatenated:
Now it's something like `%P 14-23%@ 2411-7390`, whereas it should be:
```
%P 14-23
%@ 2411-7390
```

2. **APA**: Each word is automatically capitalized in journal names. E.g. now we have some name displayed as "Journal **O**f Language **A**nd Education", whereas the normal name is "Journal of Language and Education". 

We're using OJS 3.0.2.

**Comment by asmecher** [comment]
@Ph-We, what app and what version are you using? (Please include this in reports!)

**Comment by Ph-We** [comment]
@asmecher, sorry, I've corrected that. OJS 3.0.2.

**Comment by asmecher** [comment]
Hi @Ph-We -- 

1. I think you need to add a line break in `plugins/citationFormats/endNote/citation.tpl` just before the `{/foreach}` end on the line that formats the `%P`. Would you mind trying this locally?

2. This will take a little coding, and in my opinion it would be better to move to CSL templates per https://github.com/pkp/pkp-lib/issues/723 rather than continuing to duplicate effort with our own citation templates.

**Comment by NateWr** [comment]
This citation format is no longer handled directly by us.
