### ISSUE TITLE
CrossRef XML Export Plugin- Status

### ISSUE THREAD

**Issue by luisja58** [pkp/pkp-lib#2409]
In ojs 3.02, when OJS will deposit assigned DOIs automatically to CrossRef (For example 10 articles), but one record_diagnostic status="Failure", in the xml return from crossRef, all status in OJS appear as 'failure', but only one is in error.
Example of XML return from CrossRef:
......
  <record_diagnostic status="Success">
      <doi>.....18.2017.327-330</doi>
      <msg>Successfully added</msg>
   </record_diagnostic>
   <record_diagnostic status="Failure" msg_id="4">
      <doi>....18.2017</doi>
      <msg>Record not processed because submitted version: ...1002675 is less or equal to previously submitted version (DOI match)</msg>
   </record_diagnostic>
   <record_diagnostic status="Success">
      <doi>....18.2017.324-326</doi>
      <msg>Successfully added</msg>
   </record_diagnostic>
...............
If you look in >Tools>Imports/export/>CrossRef XML Export Plugin>Articles>Status
....18.2017.327-330   failed
....18.2017.324-326   failed
......

**Comment by asmecher** [comment]
@bozana, can you have a look at this?

**Comment by bozana** [comment]
@luisja58, @asmecher: yes that is so for the moment with batch deposits i.e. if several DOIs are deposited at once -- we get only the status of the whole batch deposit via API. Maybe we can see with the Crossref how to improve it in the future, for now it is so and not a bug...
You get that result XML from Crossref via e-mail or so @luisja58, right?

**Comment by luisja58** [comment]
Agree. Is clear.
I investigated the CrossReff error (cause of the final error in status of the last batch-ID):
Record not processed because submitted version: xxxxxxxxxx is less or equal to previously submitted version (DOI match)
I have seen that if a certain DOI is registered by WEBFORM (has been our case when registering the journal issue), the CrossReff system gives a 12-digit TimeStamp (e.g. 201703231933).
  But in automatic deposit by OJS, the timestamp is 10 digit (e.g. 1491002675).
So that a new deposit  timestamp It will always be smaller and will produce the error.

**Comment by bozana** [comment]
@luisja58

**Comment by bozana** [comment]
@luisja58, how did you generated the value for the element `timestamp` when depositing via Web form? The OJS always uses the PHP function time for that, so I believe all OJS exports and deposits should behave in the same way... ?

**Comment by bozana** [comment]
I think I accidentally closed the issue -- I will wait for your answer @luisja58...

**Comment by luisja58** [comment]
Before using OJS we had registered the DOI of the issue via webform.(TimeStamp  201703231933)
https://www.crossref.org/webDeposit/
Later, in OJS, we activated automatic DOI registration of articles (Timestamp 1491002675).

**Comment by bozana** [comment]
@luisja58, yes, I am afraid we can generally do nothing here -- the users who manually registered DOIs without using OJS could have anything in their "timestamp". We would then have to provide a general possibility for OJS users to configure how the "timestamp" is created, but this is a very low priority for us now -- so much important things for OJS 3.1 to work on. Thus, could you maybe ask Crossref if there is anything you could do for those old registrations to use the same concept of "timestamp", so that you can, from now on, use OJS concept? Or, you would eventually have to change how the "timespamp" is created in your OJS installation -- to fit to your old concept -- but it seems to be too inconvenient for the future.
