### ISSUE TITLE
Limit display of names to editors in edited volumes

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2426]
Currently, "Edited Volumes" in OMP list volume editors and all chapter authors at the top of the monograph page. This can become very cluttered. See: http://monographs.lib.sfu.ca/index.php/sfulibrary/catalog/book/20

Ideally, edited volumes should only display the volume editor names in this space, along with their designation as editors -- i.e., Terry L. Ozbun; Ron L. Adams (eds).

"Monographs" should continue to show authors in this space.

**Comment by asmecher** [comment]
+1, SI is asking for this too.

**Comment by NateWr** [comment]
A monograph has a `workType` which is set to `WORK_TYPE_EDITED_VOLUME` or `WORK_TYPE_AUTHORED_WORK`. However, there's no way to view or change this in the workflow. Should there be?

Also we have no way to determine which "authors" are the editor(s) of the whole volume. It's just a separate user role we generate with no distinguishing data from chapter authors. I can think of a couple ways to address this:

1. Add an option to user roles to flag a role as a volume editor. This way it only has to be set once, but requires manager-level configuration and no handling of monograph-by-monograph preferences.

2. Add an option to the submission where they choose which contributors should be listed as editors for edited volumes. More flexible approach will reduce edge cases, but it requires selecting the editors for each volume.

Thoughts? @stranack, @asmecher, @bozana

**Comment by asmecher** [comment]
@NateWr, the `workType` used to define whether or not it was possible to create/assign chapters, but then we got feedback that divided-out chapters were useful for stand-alone monographs too, so we just kept it as a piece of metadata. This field is exposed via the native XML import/export, and the MODS34 schema, but otherwise it's not used anywhere. I'd suggest we consider removing it entirely, unless we can make it more useful. If we can make it more useful, it should be editable.

**Comment by asmecher** [comment]
As for editors of the whole volume: these would be the Volume Editors, which IIRC is an author role. There's also the per-chapter list of authors. Is the problem distinguishing programmatically between Author and Volume Editor roles?

**Comment by NateWr** [comment]
> Is the problem distinguishing programmatically between Author and Volume Editor roles?

Yes. Both are just user groups with the `Author` role. I worked last week on a solution that would add a configurable option to a user group to display those users as editors of edited volumes. But it's more than a little confusing to have a user group "Volume Editor" and still have to select the display mode. 

It also required a lot of new code because I had to split several classes and DAOs from their PKP selves to OMP versions. I should have a PR to look at soon, but I'm not entirely convinced it's the right approach.

**Comment by NateWr** [comment]
The following PRs:

1. Add an option when creating a user role to identify the role as an editor of edited volumes.
2. Expose the `workType` selection in submission metadata form.
3. When a contributor is added to an edited volume, they can be identified as an editor. Those assigned a role with the option (1) will automatically have that selected. But it can be overridden if desired.
4. Contributors identified as editors will be listed as such in summary and full views of monographs.

Implementing this just for OMP required splitting a lot of the UserGroup and Author grids/forms into PKP and OMP-specific classes. There's also quite a bit of overlapping configuration involved with the roles and the contributor forms.

PRs:
https://github.com/pkp/pkp-lib/pull/3069
https://github.com/pkp/omp/pull/470
https://github.com/pkp/ojs/pull/1703

Now that I've done it, I wonder if it wouldn't be a better solution to have a separate checklist of contributors when an edited volume exists, and the editor can check those they want to appear as editors. It'd just be metadata saved with the submission instead of tying it all into the roles system. What do you think @asmecher and @stranack?

**Comment by asmecher** [comment]
@NateWr, I'm sorry to say that your last proposal does sound a lot less complicated :( especially since this accentuates the differences between OJS and OMP. The less code that does that, the better.

**Comment by NateWr** [comment]
👍 I'll work that up.

**Comment by NateWr** [comment]
@asmecher Ok, I did it this way. I decided to put it into the catalog entry form, since it doesn't reflect metadata. What do we need to do for the upgrade scripts? We now display authors with a `isVolumeEditor` setting in the database. Should we add all authors to this automatically, or require people to set them manually on upgrade?

PR:
https://github.com/pkp/omp/pull/473

**Comment by NateWr** [comment]
Tests passed and now finally I got the JS to validate. :) @asmecher do you want to take another look or should I merge this?

**Comment by asmecher** [comment]
Looks good (and Crockford is satisfied) -- please go ahead!
