### ISSUE TITLE
[OJS] Serve Google fonts without cdn

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#2429]
As far as I can see turning of `enable_cnd` does not only turn off the delivery of JS by the cdn, it also turns off the delivery of fonts like Noto Sans.

Is it possible to include the font files (like jQuery and jQuery UI) into the lib so they can get served without cdn too?

If it's not possible the comment in the config file should make clear that the use of google fonts is disabled too. I think it would be helpful to have a hint in _Settings -> Website -> Appearance_ that the selected font is not available when cdn is disabled.

What do you think?

**Comment by asmecher** [comment]
@MarHerUMR, possibly -- if those can be managed via a Composer dependency or something similar. I'd rather not have to explicitly manage versioning of dependent content manually e.g. in the git repo.

**Comment by MarHerUMR** [comment]
@asmecher I get why you don't want to manage the manually. So I looked if there's a composer plugin or something like that, that would pull in the latest font files for the five fonts. (When we wouldn't care about the latest files we could just handle them like the fontawesome files, add them to the repository once)

I didn't really find a solution where there's a composer dependency just importing (and linking in css) the fonts used by the _Default Theme_. The only thing I could imagine would be to make a custom composer package. But then there has to be someone to keep the package up to date (more or less manually).

Another approach could be to have a script that fetches the CSS files:
* https://fonts.googleapis.com/css?family=Noto+Serif:400,400i,700,700i
* https://fonts.googleapis.com/css?family=Noto+Sans:400,400i,700,700i|Noto+Serif:400,400i,700,700i
* https://fonts.googleapis.com/css?family=Lato:400,400i,900,900i
* https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i
* https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i|Open+Sans:400,400i,700,700i
* https://fonts.googleapis.com/css?family=Noto+Sans:400,400italic,700,700italic

Saves them as:
* noto_serif.css
* noto_sans-noto_serif.css
* lato.css
* lora.css
* lora-open_sans.css
* noto_sans.css

Walk through every CSS file, downloads the src files of the font and replaces the google font url with a local one.

This script could be called from the buildpkg.sh or manually when you're working the the git version.

I've actually made such a script for my wordpress theme plugin. It's not an ideal solution but it would be possible. Would this be a possible solution?

**Comment by NateWr** [comment]
No, and it's not that easy to get the required files we would need.

If you saved `https://fonts.googleapis.com/css?family=Noto+Serif:400,400i,700,700i` as `noto_serif.css`, you'd still be making a request to Google, because those URLs pump out a list of font declarations that are segmented by character set and font weight, and which point to the files (on Google's server) where the browser can fetch them.

Adding to the complications, Google only serves the font file configuration specific to your device/browser. I believe there are five different file formats that may be served, depending on your device. (You can see them in the `/styles/fontawesome` dir.) So if you were to write a script to fetch and store everything locally, you'd still need to spoof the headers on the request so it looked like a request came from different devices to get all four formats. (We'd then have to rewrite Google's font-face declarations ourselves to ensure the write file was loaded for each required format.)

If you've managed to workaround these issues in a WordPress theme, @MarHerUMR, I'd be curious to know how you've done it. 

But in my view we're talking about a lot of work for minor gain here, and it's work that will multiply as more themes come out. It's a lot easier to do something manual for one site with one language and one font than it is to catch all cases for a general theme that will be used in dozens of languages with five or six potential themes.

I'd be happy to explore opportunities with alternative font CDNs if there are any we'd identify as better - from a privacy perspective - than Google.

**Comment by NateWr** [comment]
> I think it would be helpful to have a hint in Settings -> Website -> Appearance that the selected font is not available when cdn is disabled.

I like this idea, though.

**Comment by NateWr** [comment]
This has been addressed as part of #6478. All fonts are served from self-hosted files instead of Google's CDN.
