### ISSUE TITLE
[OJS] Editors should be able to add attachments to the Editorial Decision message

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2438]
Hi,

In OJS3, editors would probably benefit if they could add file attachments to the Editorial Decision message. At the moment the editor can choose to send the reviewers attachments to the author, but can not add new attachments to the panel.
![screenshot_24](https://cloud.githubusercontent.com/assets/16347527/24994690/a9fc1a84-2034-11e7-89fc-108e40f1deaf.png)

I suggest that there should be an option to upload new files there.

**Comment by alexxxmendonca** [comment]
I fully agree on this.

👍

**Comment by t4x0n** [comment]
totally! 👍

**Comment by primoz-svetek** [comment]
I agree on this! Just tried to investigate what is wrong, because the editors have been complaining it doesn't work.

**Comment by amandastevens** [comment]
Comment from a publishing services client in support of this feature: "There really, really ought to be a possibility to attach documents. I was going to suggest to the editor that she uses the Notify function, but you cannot attach documents there either! The only place you can attach documents is by creating a Discussion, but none of our editors likes to use that function as it sends a very generic notification with a link to the actual message, instead of generating an email with the message in it."

**Comment by asmecher** [comment]
PR: https://github.com/pkp/pkp-lib/pull/4378

https://github.com/pkp/pkp-lib/issues/4376 needs to be reviewed/merged before this will work.

The change permits any review round file to be attached to the decision email, and also allows adding new files to the grid. Added files are FILE_STAGE_ATTACHMENT files, which were used in OJS 2.x for email attachments, i.e. an analogous use to this one. Note that the uploaded attachments *are not* available elsewhere in the interface.

A simpler change to the current dialog was not possible because thus far all listed files were attached to one review assignment or other. Uploading a new file to the grid would either require permitting the file to be unattached to any review assignment (a data model change), or forcing the editor to somehow choose a review assignment to attach it to (not what anyone wants).

**Comment by asmecher** [comment]
Tests: https://travis-ci.org/asmecher/ojs/builds/485546595

**Comment by bozana** [comment]
@asmecher, all good, you can merge... :+1:

**Comment by asmecher** [comment]
Thanks, @bozana! Merged & cherry-picked.
