### ISSUE TITLE
Google Scholar indexing new articles with this title: "Quick jump to page content" 

### ISSUE THREAD

**Issue by karamqubsi** [pkp/pkp-lib#2452]
Hi , 
If you searched google scholar for the following term "Quick jump to page content "  : 

[https://scholar.google.com/scholar?q=%22Quick+jump+to+page+content%22&btnG=&hl=en&as_sdt=0%2C5](https://scholar.google.com/scholar?q=%22Quick+jump+to+page+content%22&btnG=&hl=en&as_sdt=0%2C5)

you will get about 900~ results and it is all using ojs , 

What is the problem , of course we noticed that after google scholar archived some of our new articles with that title . 

Thank you

**Comment by bozana** [comment]
@NateWr, I believe it comes from bootstrap3 theme. Do yo know?

**Comment by NateWr** [comment]
Huh, that's interesting. That probably shouldn't be an `<h2>` element. But still, it seems like a pretty big indexing fail on Google's part.

@karamqubsi: the immediate fix is to change the `<h2>` on the line that @bozana sent to `<p>`. I'll flag this up in the bootstrap repo so that we get this changed for the next version.

**Comment by NateWr** [comment]
Closing this in favor of the issue filed over at the theme repo, so follow-up discussion there:

https://github.com/NateWr/bootstrap3/issues/57
