### ISSUE TITLE
Adjust wording of Send to Copyediting button on review stage

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2453]
On the review stage, there is no ACCEPT button, which some are looking for - possible rewording “Accept and Send to Copyediting”.

From the [UI/UX testing outcomes](https://docs.google.com/spreadsheets/d/1RkZ0avL3UIUU-hUScbM77lLCsGtk-T2_dL-FEx_vKcM/edit#gid=0).

**Comment by asmecher** [comment]
@stranack, I think I recently tagged you elsewhere on this -- OpenSI also wondered why we used "Send to Copyediting" instead of "Accept".

**Comment by NateWr** [comment]
I changed the language of the buttons a bit to be clearer for each stage. @stranack any objections?

![selection_194](https://cloud.githubusercontent.com/assets/2306629/25335315/6d129fa8-28ea-11e7-9f1e-9c7c22d7fac5.png)

![selection_195](https://cloud.githubusercontent.com/assets/2306629/25335322/726378d8-28ea-11e7-9c29-6080e5035b5e.png)

PRs:
https://github.com/pkp/pkp-lib/pull/2466
https://github.com/pkp/ojs/pull/1363
https://github.com/pkp/omp/pull/406

@mtub Did I clear out the locale keys properly here?

I'm guessing the tests will fail as they do when locale strings change. I'll check back in a bit.

**Comment by mtub** [comment]
Hi @NateWr, deleting the translations from many locales seems a little bit harsh from my perspective, because many of the translations never followed your initial rephrasing of the accept key, so there translations might still be valid. But probably no-one has the time to check all locales... In the end it could result in missing translations that we once had and then deleted without need. But I like the overall direction of this adjustment.

**Comment by asmecher** [comment]
Ah, I think that jogged my memory on why we changed "Accept" to "Send to Copyediting". We wanted a consistent label on both Submission and Review stages, but putting "Accept" on the Submission stage confused some people because they thought it meant to accept the submission into the peer review process. @NateWr, I think your proposal for different wording depending on the stage is an improvement.

**Comment by NateWr** [comment]
@mtub In this case, do you know which locales need to be removed and which should remain? I removed them all because I'm not able to tell.

**Comment by asmecher** [comment]
@NateWr, is this ready for a review/merge? I'd like to back-port it to OMP 3.1 for another client soon.

**Comment by mtub** [comment]
Hi @NateWr , I don't know right now which locales to keep and which ones to drop. I just think in these cases of remove-and-put-back-in it is a little sad to cause extra work for translators (which might never been done, resulting in an untranslated string) even if they never followed the temporary change in en_US. But I don't have the time to check every locale, so I guess we don't have any other option.

**Comment by NateWr** [comment]
@asmecher Yes, it is. It's just locale changes.

@mtub I understand. I suppose, ideally, we would have some way of signalling that a locale key has changed, without completely removing it. Maybe parsing a diff of changes to `/local/en_US/` between versions?

**Comment by asmecher** [comment]
Updated and merged these pulls:
- https://github.com/pkp/pkp-lib/pull/2466 (same old)
- https://github.com/pkp/ojs/pull/1378
- https://github.com/pkp/omp/pull/410
