### ISSUE TITLE
AddThis plugin for OJS 3 (or a better alternative)

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2458]
OMP 3.1 includes a plugin for AddThis, allowing for social media linking -- see: http://monographs.lib.sfu.ca/index.php/sfulibrary/catalog/book/1

We need something similar (or better) for OJS 3. This is an increasingly important way that scholars are sharing resources and journals are coming to expect it.

**Comment by ajnyga** [comment]
Hi,

I uploaded a OJS3 version of the OMP addThis plugin here: https://github.com/ajnyga/addThis

I made that a while back, but have not used it myself. I am reworking the article page in our theme (adding for example tabs to make it more clean https://jqueryui.com/tabs/) and will add these social media buttons straight to the theme plugin itself.

I think that just by adding a check for the template hook that needs to be called, this would work both in OMP and OJS. The changes I needed were minimal, basically chancing references to press to context.

**Comment by asmecher** [comment]
@ajnyga, excellent -- and as you note, this would be trivial to change so the same code supported both applications. Since the only real difference is the name of the hook, I'd suggest simply registering for both and letting the application call whatever one it wants to.

Would you prefer to maintain that repository yourself, or to transfer it over? I'd like to see more third-party repositories, to help dismantle the perception that PKP maintains everything -- but obviously that would mean taking on some maintenance on your part. Alternately we could transfer it over to PKP and handle that. In either case, I'd like to remove the AddThis plugin that's currently shipped with OMP and instead refer to this application independent version of it using the plugin gallery.

**Comment by ajnyga** [comment]
Hi,

The changes I had to do were minimal, so it would be a bit weird for me to maintain this. So go ahead and copy the version I have here. I will remove the repository once it is available from the Plugin Gallery.

**Comment by asmecher** [comment]
Great, that makes sense. I've forked this back over to the PKP account and added a commit to reconcile a few details with OMP: https://github.com/pkp/addThis/commit/988f93a083c97866a041d3aabef041d3f8f59a9e

**Comment by asmecher** [comment]
Still needing doing (a note to self):

- [ ] Remove from OMP repo
- [ ] Test with both
- [ ] Package and add to plugin gallery for OMP and OJS

**Comment by asmecher** [comment]
All right, @ajnyga, it's in the plugin gallery for OJS -- I haven't added it to the OMP gallery because until the next release it'll still be included in the package. Ready for you to delete your fork unless you'd like to keep it around -- and thanks again!

@stranack, this should now be in the plugin gallery for OJS 3.0.2.
