### ISSUE TITLE
[OJS3] Native Import doesn't delete Sections added during import after error

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#2523]
The Native Import generally cleans up after itself if an error occurs, removing Issues and Submissions.
Via UI:
https://github.com/pkp/ojs/blob/568a974aaa2be50ba39dfb67a370a03a4fa36741/plugins/importexport/native/NativeImportExportPlugin.inc.php#L160-L164
Via CLI:
https://github.com/pkp/ojs/blob/568a974aaa2be50ba39dfb67a370a03a4fa36741/plugins/importexport/native/NativeImportExportPlugin.inc.php#L387-L391

This does not, however, remove any sections which were added in the failed import.

I'm also not fully sure about why issue errors are ignored.  If we really want to implement information-only warnings, this should be flagged separately (and sections or submissions ought to be able to flag these as well).

**Comment by bozana** [comment]
@ctgraham, I am not sure any more, but: 
a) the imported sections are not so many and self contained if empty (i.e. a section deletion does not have to consider other DB tables/objects) -- so it was/is not such a big problem for journal managers or editors to delete them if necessary.
b) they could be reused -- when a failed import is corrected -- I believe no new same sections would be created again?
c) if a section import failed, the errors are reported as issue reports and then the whole import 
and finally, most important, if we decide to consider it:
d) we could delete only the new inserted sections, that are just inserted by that import, because else, the section could contain other articles, right?
THANKS!!!

**Comment by ctgraham** [comment]
I don't think we should treat parts of the same import differently.  Currently on error of _any_ submission, we delete all issues and all submissions but leave all sections.

Either we should keep any new content that is not in an error state; or, we should roll back all new content due to any error state.  We're pretty close to the second condition.  We can readily flag any new sections included in a failed import for removal.  I'll add a deployment method to handle warnings so we can provide notification of problems which don't warrant aborting the import.

**Comment by ctgraham** [comment]
Refactoring the error/warning handling spans the shared library and multiple plugins, so I'm branching that part to https://github.com/pkp/pkp-lib/issues/2526.

**Comment by bozana** [comment]
ok, agree... :-)

**Comment by bozana** [comment]
Thanks a lot @ctgraham! Also here, all PRs are merged... (and GitHub closed the issue)
