### ISSUE TITLE
[OJS] OAI request for a single journal shows the deleted records of the whole installation

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2566]
This could be a feature or a bug, OJS 3.0.2.

When you open the OAI request page for a single journals (http://site.com/journal/oai) it will show the deleted records of the whole installation, of all journals in the installation. I would expect it to show just the deleted records of the selected journal. The actual records come back correctly.

**Comment by bozana** [comment]
I found a few more bugs: 
-- the deleted records are not displayed if a section or journal is missing because of these JOINs: https://github.com/pkp/ojs/blob/master/classes/oai/ojs/OAIDAO.inc.php#L254-L255
-- if the set = journalPath, the deleted records are not found, because it will only be looked after the exactly the same sets (https://github.com/pkp/ojs/blob/master/classes/oai/ojs/OAIDAO.inc.php#L257), but the sets in the tombstone table are always of the form 'journalPath:sectionAbrev'
-- if an OAI request with one journalPath in the URL and a set from another journal is made, the records from that other journal will be displayed.

The PR is coming...

**Comment by bozana** [comment]
PRs:
ojs master: https://github.com/pkp/ojs/pull/1414

**Comment by bozana** [comment]
@asmecher, could you please take a look at the PR above?

**Comment by bozana** [comment]
@asmecher, the PRs for ojs-stable-3_0_2 are slightly different. Could you please take a look at them:
pkp-lib ojs-stable-3_0_2: #2574
ojs ojs-stable-3_0_2: pkp/ojs#1417

**Comment by asmecher** [comment]
Just reading over the code (I didn't test it) this looks fine. If you've run it through a few laps, please go ahead, thanks!

**Comment by bozana** [comment]
Everything merged, thus closing...
