### ISSUE TITLE
[OJS] display supplementary files in block, rather with galley files

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2577]
Links to supplementary files are currently provided in the same way that we provide main galley links, ie. in the TOC. This treats them sort of the same as main galleys (which they aren't), and takes up TOC real estate. These should instead be moved into their own block area.

**Comment by NateWr** [comment]
So do you see all supplementary files from all articles being grouped together somewhere on the TOC?

Or do you mean remove them from the TOC and display them only on the article page, in a separate area from the main galleys?

**Comment by jmacgreg** [comment]
Hi @NateWr, I would remove them from the TOC entirely - that should only list primary article galleys - and display them in their own content block on the article page, similar but distinct to how the main galleys are already displayed. So taking http://journals.sfu.ca/present3/index.php/demojournal/article/view/6 for example there's already a content block that displays: 

[PDF] [XML] [HTML] 

We'd remove supplementary files from this area, and display them in their own content block, maybe something like: 

Supplementary Files: 
[Source Code]
[Figure 1]
[Figure 2]
[Table 1]

... etc. Does that make sense?

**Comment by snminton** [comment]
James and NateWr:
   Just thought I'd weigh in on this, since it arose out of a discussion James and I were having. 
   
   I think having a separate block for supplementary files is important, but I'd suggest that they should also be included in the TOC. In some cases, these supplementary files can be important - for instance JAIR publishes errata as "supplementary files".   Note also that the supplementary files could always be hidden by CSS, if a journal doesn't want them shown in the TOC.

**Comment by NateWr** [comment]
Supplementary files in the TOC is tricky because I think every journal uses supplementary files in a different way. And the default theme display of files is kind of premised on there being a primary download file (maybe in multiple formats), since that seems to be the way the vast majority of our journals work.

I'd be more inclined to encourage a journal that wants to show supplementary files to add them with custom theme scripting, rather than the reverse (using custom scripting to remove them from the presentation).

Still, if the supplementary files were displayed in the TOC, how would you like them displayed? On the same line with the primary files? In a separate area? Can you provide any mockups of how you'd expect them to appear?

**Comment by snminton** [comment]
Thanks Nate. I think we would prefer to have the supplementary files on a
separate line. We'll mock something up to illustrate one way of doing it.
- S

**Comment by snminton** [comment]
By the way, I think its OK if the supplementary files don't show up in the
TOC -- this was just an idea that I thought might be helpful

**Comment by NateWr** [comment]
@jmacgreg and @snminton Does this look like it addresses the feature request?

![selection_054](https://user-images.githubusercontent.com/2306629/29457425-06dcddba-8412-11e7-9048-75c97a5c2963.png)

**Comment by jmacgreg** [comment]
Hi @NateWr that looks good to me! @snminton, I can schedule an upgrade for your system to run a test shortly, if you like.

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/2723
https://github.com/pkp/ojs/pull/1499

(Tests running.)

**Comment by snminton** [comment]
Looks great, thanks!

**Comment by NateWr** [comment]
Tests passed. @bozana can you code review? :+1:

**Comment by NateWr** [comment]
All merged!
