### ISSUE TITLE
[OJS] Update pt_PT locale for OJS 3.1 release

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2606]
Issue tracking the updates to the pt_PT locale.

**Comment by Duozhasht** [comment]
Greetings @mtub 
are you planning to release any updates to pt_PT locale soon? 
I've been working on translating (plugins included) and I've almost completed all translations.

Will you be interested in a pull request to add those to the main website?

**Comment by mtub** [comment]
Update: I have received an almost complete translation from our usual translator, and I will merge that translation first. We will have to see how to deal with differences in the new proposals from @Duozhasht, and I will ask José to review the changes.

**Comment by Duozhasht** [comment]
Hello @mtub,

I've completed my review on the pkp-lib files. I started this process with another branch based on the current master, but I found our translations to be quite better. 
In order to finish my job, I got back to my branch from pull request and merged with master and fixed conflicts. I know this is not a good mechanism for tracking differences.

You can check the same pull request https://github.com/pkp/pkp-lib/pull/2669 and if you want, feel free to accept it.

If you want I can give you specific examples where José translations could be better. I work in a company that manages websites for the government, and I must respect some guidelines and quality level.

Just tell me how you want to proceed with the other pull request https://github.com/pkp/ojs/pull/1464 .

**Comment by mtub** [comment]
This is a rather difficult situation. We have three people contributing translations, and I cannot figure out which one is better. We need to come to a situation where the translators could collaborate and reach a compromise, with probably a glossary of common terms etc. We cannot figure this out before the release, but I will all of the translators to a discussion about the translations, tools and workflows after the release. (@josekarvalho, @Duozhasht, José Castro Silva, see https://pkp.sfu.ca/wiki/index.php?title=OJS:_Portuguese_(pt_PT))

**Comment by jmaferreira** [comment]
I don't think it matters which translation you choose, as long as the translation is complete. I know 
@josekarvalho and @Duozhasht  pretty well and trust both of them as experts in the field.

**Comment by jmaferreira** [comment]
I don't think it matters which translation you choose, as long as the translation is complete. I know 
@josekarvalho and @Duozhasht  pretty well and trust both of them as experts in the field. Hope this helps.
