### ISSUE TITLE
[OJS] Track and report on institutional subscriber usage 

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#2676]
Institutional subscribers need to know their readers' usage patterns for a given journal in order to make decisions on whether a subscription is worthwhile. This requires tracking IP addresses for article views/downloads, and comparing them against institutional subscription IP addresses. Currently, the metrics table in OJS does not track IP addresses. This would have to be added (with care taken to follow any privacy configurations around IP tracking), and the numbers would then subsequently have to be exposed in aggregate for subscribers. These numbers should obey any COUNTER protocol parameters. Some high level implementation considerations follow:

1) Add a new "ip_address" dimension to the `metrics` table.  
- For each record in the `metrics` table, track the relevant IP address from the log. 
- Ensure that if the Usage Stats Plugin's "Respect Data Privacy Option" is enabled, IP addresses are not tracked. 

2) Create "COUNTER for Institutional Subscribers" report. 
- This report should be available to all institutional subscribers. 
- It should report on all journals on the platform, same as the regular report. 
- It should display the same numbers in the same format as the regular COUNTER report, ie. aggregate views per month for the given year, and then a total YTD for HTML and PDF galleys

3) Add institutional subscriber usage counts to the "Subscriptions" report available to JMs. 
- For now, probably only include the YTD total as one additional column in the spreadsheet. 
- Consider including a full month-by-month count as per the COUNTER report above, if it's helpful.

**Comment by ctgraham** [comment]
I don't think we want to include the IP in the metrics table.  I think we want to include a foreign key to the Institutional Subscription which is being utilized for access, whether it by IP based, or Shibboleth based, or otherwise.

**Comment by jmacgreg** [comment]
@ctgraham, could we do something as simple as include/crossreference the subscription_id?

**Comment by ctgraham** [comment]
I think so.  The next question would be: can a subscription be deleted?  If so, we may need to prevent that to preserve historic foreign keys.

**Comment by jmacgreg** [comment]
Yep, they can be deleted.

**Comment by ctgraham** [comment]
Also, from a SUSHI/COUNTER perspective, one client might be interested in multiple subscriptions (perhaps legacy/changing subscriptions for that client, perhaps the client is an aggregator on behalf of multiple subscriptions).  We should consider the permissioning implications here.

**Comment by willinsky** [comment]
I'd like to see this tracking on subscribers expanded so that it supports the **subscribe-to-open** (S2O) financial model for open access, in which existing subscribing institutions agree to renew their "subscriptions" with the journal then going open access. The participating libraries would still be interested in SUSHI/COUNTER reports in light of their support, and such figures, once the journal is open could be used to recruit new libraries that are proving users. 

USE CASE: 1. Librarian, participating in S2O model, seeking to establish usage rate in comparison to the traditional subscription model, enters IIAR in publisher's OJS portal, or individual journal. 2. Publisher or subscription agencies request IIAR from a library to enter in OJS portal to demonstrate basis of participating in S2O model.  

REQUIREMENTS: To give libraries and publishers ability to submit or enter "institutional IP address range" (IIAR) to generate usage stats for journals, books, publishers.

RESEARCH USE: Researchers seek to establish reliable means of estimating on- and off-campus usage by institutional community, as well as by larger community (district hospitals, schools, community colleges, etc,) using IIAR results and other strategies (surveys, etc). 

LATER DEVELOPMENTS: Publisher purchases IIARs from commercial service covering libraries in a region, and uses PKP software’s bulk processing capacity to determine usage profiles for libraries across a region for marketing purposes for S2O.

**Comment by willinsky** [comment]
Alec has added these comments to this item (to an earlier google doc):
[AS] The current model for this in OJS is:
The journal manager (or subscription manager) creates institutional subscriptions.
Institutional subscriptions can optionally have IP addresses associated with them.
COUNTER/SUSHI reports report by subscription; thus when a given subscription has IP addresses associated with it, IP-based access under that subscription is included in that COUNTER report

**Comment by ctgraham** [comment]
> The journal manager (or subscription manager) creates institutional subscriptions.

^ yes.

> Institutional subscriptions can optionally have IP addresses associated with them.

^ yes.

> COUNTER/SUSHI reports report by subscription thus when a given subscription has IP addresses associated with it, IP-based access under that subscription is included in that COUNTER report

^ not yet, to my knowledge.

**Comment by pmangahis** [comment]
+1 from hosted client

**Comment by librariam** [comment]
+1 from PKP|PS
