### ISSUE TITLE
update countries.xml files for locales

### ISSUE THREAD

**Issue by mtub** [pkp/pkp-lib#2715]
`countries.xml` is supposed to be automatically generated using the ISO 3166 files of Debian's iso-codes package (https://packages.debian.org/sid/all/iso-codes) using the tools/poToCountries.php tool.

The files should be re-created every once in a while, also they are missing from the following locales (in the `master` branch):

* ar_IQ
* fi_FI
* ru_RU (though in this case there was a discussion and the Pavel's update of the file was accepted)

and missing from

* sv_SE

**Comment by mtub** [comment]
@asmecher, you've created the files so far, could you have a look at this?

**Comment by asmecher** [comment]
Gob of code to extract the English country list out of the JSON file Debian has started using:

    php -r '$a = json_decode(file_get_contents("iso-codes/json/iso_3166-1.json"));foreach ($a as $b) foreach ($b as $c) {echo "<country name=\"" . $c->name . "\" code=\"" . $c->alpha_2 . "\"/>\n";}'

**Comment by asmecher** [comment]
@mtub, could you have a look at https://github.com/pkp/pkp-lib/pull/2728?

Note: the standards are supplied as maps from English text to the translation in question. Since e.g. many of the translations still refer to Czech Republic rather than Czechia, the mappings don't match. I've left them as they are, i.e. I haven't manually corrected this, and I'd suggest we stick with that rather than getting into fine-tuning these. The fix should be taken from upstream.

**Comment by asmecher** [comment]
Merged -- @mtub, you're off the hook :)
