### ISSUE TITLE
Crossref plugin input feedback issues

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#2719]
In 3.x there are currently a few issues with the Crossref plugin where there's confusing feedback for users. The first issue is with a large number of DOIs listed, clicking on the page numbers to go further down the list causes a long lag and no feedback to the user that the new page is loading. 

Once I'm on the other page, if I try to register a DOI on that page, I get a "Do you want to leave this site?" dialogue from Chrome. If I click "leave", the DOIs will register.

**Comment by bozana** [comment]
@AhemNason, how many total articles/DOIs do you have and how many per page? Could you please see, if something similar happens with the articles paging in the native export plugin? Or could I maybe see that installation?

**Comment by bozana** [comment]
Hmmm... The first problem seems to be a general problem with current paging in the grids in 3.0.2. 
Either
-- to somehow fix paging in the grids, to display "loading" message
or
-- to try to solve it with Vue.js -- Vue.js will be used for submissions listing in the next release
(To use the same grid as on the submissions/dashboard page in 3.0.2, with "load more" bar would not be god, because the user shouldn't select all articles to submit/register -- it can be too much processing.)

**Comment by NateWr** [comment]
I think this issue will be obsolete once #6062 is finished.
