### ISSUE TITLE
[OJS] Test environment set up won't work as stated in README

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#2729]
The README tells you: 

> Setting up test environment :
> 
> mysql -u root -e 'create database ojs'
> mysql -u root ojs < tests/functional/testserver.sql
> cp config.TRAVIS.inc.php config.inc.php

The problem is that the testserver.sql has been removed since 2014.

Is there a newer sql file that I'm missing?

**Comment by bozana** [comment]
sorry i accidentally pressed that button :-\

**Comment by asmecher** [comment]
@MarHerUMR, that refers to an old testing environment that we've since removed. I've updated the documentation to refer instead to the Travis testing environment as our "reference" testing setup -- you can set up a local environment by referring to how the `.travis.yml` script does it. (This is of course less ideal than step-by-step documentation, but has better longevity.)
