### ISSUE TITLE
Copyeditors do not have access to editorial history

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2821]
When opening the editorial history from the submission list or the Editorial History link in the submission workflow as a Copyeditor, I get an error: "The current role does not have access to this operation."

They do seem to have permission in `InformationCenterHandler`: https://github.com/pkp/pkp-lib/blob/master/controllers/informationCenter/InformationCenterHandler.inc.php#L30-L34

**Comment by bozana** [comment]
The editorial history modal contains History and Notes tab.
The `viewHistory` function uses this template: https://github.com/pkp/pkp-lib/blob/master/templates/controllers/informationCenter/submissionHistory.tpl  (s. https://github.com/pkp/pkp-lib/blob/master/controllers/informationCenter/SubmissionInformationCenterHandler.inc.php#L86), which again uses SubmissionEventLogGridHander, that only allows access to ROLE_ID_MANAGER, ROLE_ID_SUB_EDITOR, s. https://github.com/pkp/pkp-lib/blob/master/controllers/grid/eventLog/SubmissionEventLogGridHandler.inc.php#L37. I.e. the submission history is only allowed to be seen by managers and sub-editors.
The InformationCenteHandler (where the access permissions for the functions are defined, also for the `viewHistory` function) is used by both SubmissionInformationCenterHandler and FileInformationCenterHandler. Because of that and because there is already another mechanism to protect the display of the History tab, s. https://github.com/pkp/pkp-lib/blob/master/templates/controllers/informationCenter/informationCenter.tpl#L24, I would use that another mechanism provided.

**Comment by bozana** [comment]
PR:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2855

**Comment by bozana** [comment]
@NateWr, could you take a look at the PR?
