### ISSUE TITLE
Improve Email Templates View

### ISSUE THREAD

**Issue by lilients** [pkp/pkp-lib#2906]
Hi everybody,

we want to improve the handling of the email templates overview (at workflow settings - emails). 

This is how it looks like now:

![email_templates](https://raw.githubusercontent.com/lilients/img/master/email_templates.PNG)

I was thinking it would be nice to use the new queryBuilder class, that is responsible for the fancy submission list:

![query_builder](https://raw.githubusercontent.com/lilients/img/master/queryBuilder.PNG)

This is how I would imagine a email template overview build with the query builder to look like:

![concept](https://raw.githubusercontent.com/lilients/img/e5080940411f99523e050cb93ef111f65a8faf0a/concept_email_templates.JPG)

What do you think? Any improvements, ideas and feedback are very welcome!

Best,
Svantje

> PRs:
> https://github.com/pkp/ojs/pull/2345
> https://github.com/pkp/omp/pull/657
> https://github.com/pkp/pkp-lib/pull/4638
> https://github.com/pkp/ui-library/pull/29
> https://github.com/pkp/ojs-user-guide/pull/25
> https://github.com/pkp/omp-user-guide/pull/3

**Comment by ajnyga** [comment]
Wonderful idea!

A suggestion:

I think I mentioned somewhere that it would be nice if the listing would somehow emphasize those email templates that the current journal settings are using.

For example if you have one-click-review enabled, the one-click templates would look different. Or rather vice versa: the templates not used in the settings would look inactive in some way.

What happens is that journals often edit the wrong templates.

**Comment by alexxxmendonca** [comment]
That is indeed a great idea, Svantje!

I'm backing up @ajnyga's suggestion. That happens a lot with us as well.

My suggestion here would be: if possible, filter by workflow and/or task. Even if only general tasks (ie: Submission / Under Review / Editing).

**Comment by asmecher** [comment]
@NateWr, this might make a good candidate for some future vue.js conversion...!

**Comment by NateWr** [comment]
@lilients Great writeup and the sketched mockup really helps. Are you offering to work on this? If so, let me know and I can give you a run-down of how to begin working on that.

I wrote up this documentation on the [API-driven architecture](https://www.gitbook.com/book/natewr/ojs-3-1-overview-of-api-driven-architecture/details) behind the submissions lists. But we can go into more detail about this particular use-case.

**Comment by lilients** [comment]
Thanks for the feedback and very useful ideas! @NateWr yes, I will work on this. Thank you very much for the documentation and the help offer! I will get back at you, when I am there. 👍

**Comment by NateWr** [comment]
@kaitlinnewson @amandastevens this issue will impact documentation. :+1:

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/2345
https://github.com/pkp/omp/pull/657
https://github.com/pkp/pkp-lib/pull/4638
https://github.com/pkp/ui-library/pull/29
https://github.com/pkp/ojs-user-guide/pull/25
https://github.com/pkp/omp-user-guide/pull/3

Includes:
- Add `/emailTemplates` API endpoint
- Add service class and query builder for email templates
- Add email template schema and convert `EmailTemplateDAO` to extend `SchemaDAO`
- Modify database structure of email templates
- Replace `PreparedEmailsGridHandler` with `EmailTemplatesListPanel`
- Refactor `ListPanel`s to accept props instead of data
- Refactor `ListPanel`s into more reusable UI components
- Use new `Pagination` component for `ListPanel`s (instead of the Load More approach)
- Add generic `Container` UI component for managing embedded components

(Additional notes below.)

![email-templates](https://user-images.githubusercontent.com/2306629/55150645-7d1a1c80-5144-11e9-96c7-fcc691db2d3c.gif)

Notes:
- Although we are no longer using the `PreparedEmailsGridHandler`, I left the class in place because that is how the add/edit form is loaded into a modal. We don't have any other way of delivering content into a modal right now. Rather than try to invent something fresh here, I decided to leave it until we have an established approach to modals using our Vue.js toolset.
- I left the `EmailTemplateDAO` methods related to installing and deleting default email templates. Ideally this would go into a Service class but the DAO isn't a terrible place for it and, frankly, I just couldn't be bothered to complete the refactor and do the testing that would be required.
- Because email templates are backed by defaults, they behave a little bit different when reading/writng than a typical entity. The Service and DAO classes try to limit the complexity here, so that a dev can feel like they are interacting with email templates like other objects. But there are some differences I've documented in the emerging dev docs: https://github.com/NateWr/pkp-docs/blob/dev_hub/dev/documentation/en/email-templates.md

**Comment by NateWr** [comment]
@asmecher can you code review?

I think I've got all the test failures sorted, but the OMP tests are still failing very late with some kind of DBConnection thing, maybe related to PHPUnit?

**Comment by asmecher** [comment]
On the OMP test failures, look for the message "Errors" in the log file, e.g.:
```
There were 2 errors:

1) CompetingInterestsTest::testCIDisabled
Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"OK"}
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35 (0),platform=Linux 4.4.0-101-generic x86_64)

/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:102
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:326
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:547
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:187
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/WebDriverExpectedCondition.php:185
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/WebDriverExpectedCondition.php:433
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/WebDriverWait.php:67
/home/travis/build/pkp/omp/lib/pkp/tests/WebTestCase.inc.php:444
/home/travis/build/pkp/omp/tests/functional/setup/CompetingInterestsTest.php:56

2) CompetingInterestsTest::testCIRequired
Facebook\WebDriver\Exception\NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"OK"}
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35 (0),platform=Linux 4.4.0-101-generic x86_64)

/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:102
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:326
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:547
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:187
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/WebDriverExpectedCondition.php:185
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/WebDriverExpectedCondition.php:433
/home/travis/build/pkp/omp/lib/pkp/lib/vendor/facebook/webdriver/lib/WebDriverWait.php:67
/home/travis/build/pkp/omp/lib/pkp/tests/WebTestCase.inc.php:444
/home/travis/build/pkp/omp/tests/functional/setup/CompetingInterestsTest.php:104

ERRORS!
Tests: 4, Assertions: 50, Errors: 2.
```

**Comment by NateWr** [comment]
Merged. :tada:
