### ISSUE TITLE
Non-administrators can see the Administration link on the front-end toolbar

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2910]
In my case, using the test data set, dbarnes can see the Administration link.

**Comment by defstat** [comment]
@asmecher Currently two role groups have access to the Administration NavigationMenuItem under the user's username: ROLE_ID_MANAGER, ROLE_ID_SITE_ADMIN.

Are you referring to the same Menu?
![adminmenu](https://user-images.githubusercontent.com/560456/31849758-7e2fcae2-b650-11e7-956c-b4d6e6816c60.jpg)

**Comment by defstat** [comment]
@asmecher @NateWr 
There had some changes to be made regarding 3 NavigationMenuItemTypes:
Regarding this issue: 
- `NMI_TYPE_ADMINISTRATION`: The Manager role was removed from the authorized role for that NMIType to be displayed.
Regarding other types 
- `NMI_TYPE_USER_DASHBOARD`: It seems (lib/pkp/templates/header/usernav.tpl of previous version) that the Dashboard type needs some restrictions regarding the authorized roles for displaying it. By adding those, the parent NMI (the one displaying the username of the loggedin user) can no longer be of type `NMI_TYPE_USER_DASHBOARD`. The type `NMI_TYPE_USER_PROFILE `seems to be more suitable for the purpose.
- `NMI_TYPE_USER_PROFILE`: There have been some changes in order to facilitate the change for the title display of the `NMI_TYPE_USER_PROFILE `type. Specifically support for checking whether the current `menuTree `has an NMI that has a child of a certain type (in our case the `NMI_TYPE_USER_DASHBOARD `type) has been added.

On top of those, the `getMenuTree` had been change to have less assignments, and to change the order of functionality in order for the `getDisplayStatus` callback to have access to the `menuTree` (some "nmi:display" or "nmi:title" logic could need the `menuTree` structure)

PRs:
pkp-lib: #2917
OJS: pkp/ojs#1606
OMP: pkp/omp#455

**Comment by asmecher** [comment]
@defstat, only `ROLE_ID_SITE_ADMIN` should see/have access to the Administrator link -- clicking it as `dbarnes` will give you an "access denied" message.

**Comment by asmecher** [comment]
Otherwise, @NateWr, can I leave you to review those PRs?

**Comment by NateWr** [comment]
@asmecher We're already on our way: https://github.com/pkp/pkp-lib/pull/2917 :)

**Comment by asmecher** [comment]
Resolved, I think!
