### ISSUE TITLE
Plugins already installed in database but not filesystem cannot be re-installed

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2956]
When a plugin already exists in the database, but not in the filesystem, then the Plugin Gallery cannot be used to re-install it and it cannot be uploaded via the plugin upload form.

Change the plugin version checking so that this is considered an upgrade.

This case will be frequently encountered in the case of OJS upgrades, where the new codebase will lack plugins that were previously installed via the Plugin Gallery.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/1640 (tests only)
- https://github.com/pkp/pkp-lib/pull/2957

**Comment by asmecher** [comment]
@bozana, would you mind reviewing this?

**Comment by bozana** [comment]
Merged, thanks @asmecher!
But I have another question: it seems that the version check is not enough: for example the plugin version hasn't changed for OJS 3.1 (in the plugin package for OJS 3.1) but there were some new addition/commits (since the last plugin release), so those changes will not be installed (because plugin gallery only checks the version numbers). What would be then the best way to solve it? Maybe to always change the version (at least the revision number?) when making a new plugin release package (that contains some changes/commits since the earlier release)?

**Comment by asmecher** [comment]
I don't believe any of those plugins have substantial changes -- just things like copyright dates, constructor syntax, etc. But yes, we'll need to make sure we're incrementing version numbers, and I'm also considering better ways to handle versioning (e.g. maybe we should have plugins adopt version number per the corresponding OJS/OMP releases).

**Comment by asmecher** [comment]
Merged and forward-ported to `master`!

**Comment by bozana** [comment]
@asmecher. yes. last night I was thinking that other way around is also problematic -- now the already installed plugins will not get the last changes, but then, if the version changes and update is available, the users having the earlier OJS/OMP (e.g. OJS 3.0.2) version could update to the latest plugin version (for OJS 3.1) that might not be suitable.
