### ISSUE TITLE
Improve author/user names

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#2958]
- [ ] Support multilingual names (important for users that work in e.g. both Cyrillic and Latin character sets)
- [ ] Consider whether to remove the Western-centric First, Middle, Last name divisions

**Comment by asmecher** [comment]
@jmacgreg and @ctgraham, IIRC both of you worked a couple of sprints ago on a document that surveyed the third-party standards we support to see whether metadata mismatches would be imposed by e.g. having multilingual names, or not having first/middle/last. Does either of you have that handy?

**Comment by crosfield** [comment]
I think the second problem is easily solved. In Russia and some other Eastern European countries instead of the Middle Name is a Patronymic Name (father's name). It is always specified in the articles, for example, in Russian journals. The First Name is always the proper Name, and Last Name - Surname (family name).

**Comment by asmecher** [comment]
@crosfield, the second issue isn't really a problem in Western/Eurocentric cultures; it's definitely a problem elsewhere. See https://www.w3.org/International/questions/qa-personal-names, which recommends just going with a single field. However, as with multilingual names, the problem will be finding a model that plays well with all the various metadata standards we need to provide data to.

**Comment by Ph-We** [comment]
Hi @asmecher, thank you again for addressing this issue, that is quite important for many of us!

As to Russian (and I believe, any Slavic) names, we are mostly happy with the ‘simplified’ one-field approach introduced in most bibliographic applications, like EndNote, Zotero, etc.
This approach allows (not requires) to split any name into 2 parts: 1) last name; 2) any other names. Usually the comma sign is used as a separator. 
This split is important, since different output styles have various requirements. Some require putting the second part first, other require abbreviating all the words in the second part, etc.

If the separator is optional, it might solve the problem with the ‘Corporate Author’ names entry. Now some of our users have problems in OJS, when trying to input such names, since any name require at least two parts (first name and last name). And those parts are displayed differently in different formats.

EndNote additionally allows a second separator for multiple-word last names. See
http://lib.tnnua.edu.tw/ezfiles/10/1010/img/427/EndNote.pdf
p. 57-58
![image](https://user-images.githubusercontent.com/22288161/32047901-20d0828e-ba50-11e7-906e-06fcf1753c10.png)

**Comment by ctgraham** [comment]
A brief summary of the sprint outcomes is:

    Discriminate name localization based on script changes
        that is, when installed locales diverge in script types (latin, cyrillic, arabic, etc.), then and only then, multilingual name entry is enabled.
    Clarify "first" and "last" names as "given" and "surnames". Require only "given" name.
        This means that an institution or an organization would only have a given name, as well as individuals who use mononyms.
    Provide optional fields to customize the display of the name in the event that name ordering is not "Given-name Surname".
        All users would be able to fill in a field "preferred method for being addressed"
        Authors and reviewers would be able to add a "published name"
        Citation plugins should provide a preview option, and allow the author to change the display of the name within the citation.

I'll see if I can find the sprint document, which also surveyed name usage in various metadata formats.

**Comment by ctgraham** [comment]
The sprint document has a substantial focus on handling mononyms:
https://docs.google.com/document/d/17oAPcCTL3tc7MhlcHpyVekv6_AxTHDc6BirHD3lVtJA/edit

**Comment by asmecher** [comment]
@NateWr, would a switch in name fields "first (required)/middle (optional)/last (required)" to "given (required)/family (optional)" have nasty impacts on the CiteProc stuff?

**Comment by NateWr** [comment]
Nope. That's the breakdown they expect:

https://github.com/pkp/citationStyleLanguage/blob/master/CitationStyleLanguagePlugin.inc.php#L335-L344

**Comment by asmecher** [comment]
@litvinovg, thanks for contributing! This will probably require another look, but some broad comments...

- This doesn't consider removal of the Western-centric First, Middle, Last name divisions. IMO we should tackle that at the same time as we add multilingual support, otherwise we'll have more name data models to consider (and these are a real maintenance headache).
- Upgrades aren't considered yet
- This leaves user accounts non-localized, meaning users will still be forced to pick a single locale for their accounts, then enter any other locales when submitting an article. (The article submission process might be broken too, see next point)
- I suspect the changes to `Identity` will cause problems with `PKPUser`/`User` subclasses, as they don't expect first/middle-last names to be localized
- I think there are a lot of uses of `getFirstName`/`getMiddleName`/`getLastName` that are not adapted, at least by using `getLocalized`..., or ideally by supporting multiple locales in whatever place they're used (e.g. CrossRef etc).

**Comment by asmecher** [comment]
See also https://forum.pkp.sfu.ca/t/dual-language-journal/13157

**Comment by vasylOstrovskyi** [comment]
@asmecher My modifications mentioned in the above forum discussion include 21 files with modification of classes and templates, and about 200 lines of code, providing quite usable (basic level is sufficient for my needs) installation. As above, it is based on putting names to author_settings and user_settings, but most critical issues are resolved. I really need this and plan to spent some more time to resolve more issues which are important for me.
Of course, this does not resolve the mentioned name division problem. However, I see that many people will be happy without it.
If you think that it is worth doing, I will upload my work to github. However, I am new with it and will need some advices about details of the process.

**Comment by alireza08** [comment]
Hello all,
Dear @vasylOstrovskyi , I am also working on this item. please guide me about the files that need to be modified; or if possible, share the modified codes with me. we can complete this together.
Best,

**Comment by litvinovg** [comment]
I have added some commits to use localized getters, moved user's fields first_name,last_name and middle_name to settings table too. It seems to work well now. I have definde constants to more easily change field name.

**Comment by alireza08** [comment]
Hi @litvinovg ,
Thanks for the shared codes. it works great and saved me a lot of time. however, in the Users page , user first name and last names are not displayed in either languages. (attached screenshot)
please let me know about which files should be edited and I'll try to develop it.

Cheers,

![2](https://user-images.githubusercontent.com/7510737/33706638-fb40d31e-db49-11e7-85d4-1c7c0aeb4ccd.png)

**Comment by litvinovg** [comment]
You should enter names for authors and users again because in original code there is no information in what language you have entered old names. Another approach is to create a script to transfer first_name, last_name, middle_name from users and authors tables into user_settings and author_settings and specify your locale.

**Comment by alireza08** [comment]
Hello @litvinovg,
Yes, I was aware of that and filled user_settings and author_settings tables with the correct value based on locale. But, the names are not displayed.
Interestingly, if I search a name, correct values for first_name and last_name appear in the grid box. 
Any ideas?

Best,

**Comment by litvinovg** [comment]
You must haven't applied all the commits from authors_multilanguage branches in ojs and pkp-lib.

**Comment by litvinovg** [comment]
alireza08, lets discuss this on PKP forum. This issue isn't the right place for this discussion.

**Comment by litvinovg** [comment]
asmecher, In my opinion current West-centric name divisions could be elsewhere without any problem because: 1. first name could be used as Given, last name - as Family, middle name could be omitted.

**Comment by vasylOstrovskyi** [comment]
Dear @litvinovg, I did some work in parallel and also have a working installation. I am not yet comfortable with github, so I put my patch to [https://www.imath.kiev.ua/~vo/ojspatch/]. If there are some pieces of code which you could incorporate into your code, feel free to do that. Also I put there a database migration script.

**Comment by damatveev** [comment]
Dear @vasylOstrovskyi, нow to apply your update?

**Comment by vasylOstrovskyi** [comment]
Dear @damatveev, the patch I mentioned is in the standard diff format. For Linux, use 'patch' utility, or ask Google 'how to apply patch'. However it seems that Georgiy Litvinov's work is much more complete, so it probably could be better to use his work instead. The database migration php script should be placed into tools/ directory and run from commandline.

**Comment by NateWr** [comment]
I think that would raise questions about the CSL style formats themselves. Just about every format I'm aware of expects a two-part name, since that's how a correct citation can be formatted. I'm not sure if it makes sense for citeproc-php to work without a family name, since the CSL spec pretty much requires it...

**Comment by NateWr** [comment]
Hmm, I was speaking off-the-cuff. It looks like the schema doesn't technically mark _any_ author property required:

https://github.com/citation-style-language/schema/blob/master/csl-data.json#L78-L83

Does the CSL plugin actually cause an error when no family name is provided?

**Comment by bozana** [comment]
@NateWr, yes, family name is required, if not provided there is an error in my log file.
I found this "Personal names require a “family” name-part, and may also contain “given”, “suffix”, “non-dropping-particle” and “dropping-particle” name-parts." here: http://docs.citationstyles.org/en/1.0.1/specification.html?highlight=familyName i.e. when you search after "familyName" on that page, but I haven't taken a deeper look what all that there means... :-\
But, it seems to be so -- the CSL plugin only requires family name...

**Comment by NateWr** [comment]
Nice work sniffing that out. It sounds like maybe the specification isn't strictly accurate.

> do you think we can provide to CSL the author's given name as the family name (and no given name)?

That sounds pretty reasonable to me. I think if you posted an issue on the https://github.com/citation-style-language/schema repo, pointing out that the formal schema doesn't seem to require a family name but the guidance says it's required, they might have some thoughts on how they're planning to handle that.

**Comment by bozana** [comment]
PRs:
https://github.com/asmecher/lensGalley/pull/28
https://github.com/pkp/citationStyleLanguage/pull/33
https://github.com/pkp/reviewReport/pull/11
https://github.com/pkp/pkp-lib/pull/3671
https://github.com/pkp/ojs/pull/1956

**Comment by NateWr** [comment]
Wow, looks like a lot of work here! I haven't looked at the code yet but here's a first pass at your questions (if I leave one out, it's because it's fine or I can't help):

> User import: if the given name in the site primary locale is missing, an existing given and family names will be copied for the site primary locale. Shall here the affiliation be treated in the same way i.e. copied for the site primary locale?

I think so.

> What if the site primary locale changes?

Oh. Hmm. Good question. We need it to be populated don't we? My ideal workflow would look something like this:

1. Click to change the site primary locale. A confirmation modal appears saying are you sure, we'll need to update the names in your database, this could take a while.
2. Click yes, the request is fired off. On a very large site, we'll probably need some way to process the changes in multiple requests.

What happens to the system before this work is done? What kind of problems are caused? Maybe we can just run this on a cron job if it's not too disruptive to work a day in the system without the names....

> During submission, the submitter is considered as the author per default. The submitter data (given and family name) in the default site primary locale is copied for the submission locale in this submission step 1. Maybe also the current UI locale (instead of only site primary locale) should be considered here, and if the data in that locale exists, then to copy them for the submission locale?

I would say stick with the submission UI locale during submission. 95% of the time this won't be a problem and editors can be responsible for tidying up any wayward data later.

> Shall we consider all journal locales for the migration of the author's middle name and suffix into the preferredPublicName here?

Yes? Unless there's a good reason not to we might as well...

**Comment by NateWr** [comment]
> Where else should preferred public name not be used?

I would say use it everywhere unless we need to interface with a third-party syntax (eg - CSL, import/export, crossref, etc.)

Ok, I'll take a run through the code and then try out some of the cases you suggested.

**Comment by bozana** [comment]
Thanks a lot @NateWr!

A few comments:

> What happens to the system before this work is done? What kind of problems are caused? 

I think this was not a problem, because earlier the user names were not localized, but now, that they are i.e. above all the given name because it is required, we have to rely on a locale that will make given name always exist for it.
I will see what SQL would be needed for user names in case the site primary locales changes and also see how it performs...

> I would say stick with the submission UI locale during submission. 95% of the time this won't be a problem and editors can be responsible for tidying up any wayward data later.

So, this means: If the submitter data (given and family name, eventually also affiliation?) do not exist in the submission locale, see first if they exists in the current UI. If so copy them into/for the submission locale. If they do not exist in the current UI, then take the data in the default site primary locale and copy then into/for the submission locale. OK?

THANKS A LOT!!!

**Comment by NateWr** [comment]
> So, this means: If the submitter data (given and family name, eventually also affiliation?) do not exist in the submission locale, see first if they exists in the current UI. If so copy them into/for the submission locale. If they do not exist in the current UI, then take the data in the default site primary locale and copy then into/for the submission locale. OK?

Hmm, I'm not too fussed either way. In both cases, the user isn't actually entering any of this information during the submission step? In that case, if the correct locale is missing, I guess I'd be tempted to rely on the site's primary locale. But if you think we're likely to get more accurate data from the current locale then take that.

**Comment by NateWr** [comment]
The code looks great. This is a huge refactor. Kudos for getting through it! I've tried a bit of manual testing and it looks good. I signed up as a new user, modified some users from the admin, changed from the profile area, and looked at the authors display on the frontend and in the metadata.

I only ran into one issue. Here's what I did:

1. Register as new user with just a given name in the site primary locale.
2. Go into my Profile page.
3. Add a family name in a locale that doesn't have a given name.

When I did that, the following appeared, which looks like the form's being tossed into an `alert()`:

![selection_182](https://user-images.githubusercontent.com/2306629/39775874-02f37a9c-52f7-11e8-8d5b-1b736ad46492.png)

Doing the same thing worked fine when I tried these steps from the Edit User modal.

**Comment by bozana** [comment]
I considered all comments from @NateWr, from here and in the PRs. Thanks a lot @NateWr!
The decisions from here I also added to the summary comment above.
The only one thing left is to consider the changing of the site primary locale and submission locale.
Also, I could do a little bit more testing with OMP.
Else, @asmecher, it is ready for you to take a look :-)
THANKS!!!

**Comment by asmecher** [comment]
Phew, @bozana, that's a tremendous amount of work. I've scanned the PRs and see a lot of assumptions, but they're sensible ones, and the admittedly increased complexity (particularly in SQL) is balanced by need and some nice clean-up along the way. I suggest we merge this and allow it to evolve/improve/undergo testing in `master`. That'll give @lilents a chance to rebase against these changes for the versioning code, and give us the longest possible cycle of dev with this stuff well in place.

And thanks for a thorough review, @NateWr -- I had a few immediate questions that I then found well-explored between you and @bozana already. I agree with the convo I saw.

I just had a couple of minor comments I made on the PRs individually -- but certainly nothing worth holding up on. Please go ahead!

**Comment by Ph-We** [comment]
We'd be happy to test it thoroughly as soon as it's merged!

**Comment by asmecher** [comment]
Yes! :fireworks:

**Comment by bozana** [comment]
Everything merged, thus closing :tada:

**Comment by bozana** [comment]
@litvinovg, THANKS A LOT for contributing!!! :star2:

**Comment by mpbraendle** [comment]
We are not happy with the introduced changes for multilingual names. See my comment on https://forum.pkp.sfu.ca/t/translation-of-the-authors-name/14474/122?u=mpbraendle

**Comment by asmecher** [comment]
> We are not happy with the introduced changes for multilingual names.

(Resolved with https://github.com/pkp/pkp-lib/issues/4675 -- to be included in OJS/OMP 3.1.2-1)
