### ISSUE TITLE
Sub-editor can skip the entire review process

### ISSUE THREAD

**Issue by vmozer77** [pkp/pkp-lib#3073]
Hello, I have been playing around with the subeditor role and found out that if the person has access to the submission stage, they can skip the entire review process by clicking the Accept and skip review button there. In the review section they have available only the Make recommendation button. 

I would suggest that the sub-editor level of permission can only make recommendations during all stages of the process if assigned to. Subsequently an assigned editor or another role with a higher level of permission would confirm (or decline) the recommended action with or without taking any intermediate action. 

The logic for this is for example our system in which we send the submitted papers in "untouched" raw form to the editorial board member for initial check whether the paper fits the topic indicated by the author. Here we would like to have a recommend button in the submission area so that the editorial board member (in our case) could recommend one of the three actions (send to review, accept and skip review or decline) and the journal editor (or someone else) would then confirm this decision. Before confirming and progressing the paper into the review stage the editor could request corrections if something is missing, wrong or the paper needs pre-review "clean-up".

Hope that the above makes sense and will be possible to integrate the recommendation functionality to all stages.

Thank you.

**Comment by t4x0n** [comment]
I was going to say the same thing... in OJS 3.1 was incorporated recommend option #2433  but only for review stage, at Submission tab they could yet Accept the manuscript and skip the Editor in Chief decision. 

what do you think @NateWr?

**Comment by bozana** [comment]
Hmmm.... maybe then to disable that action for those roles/groups being recommendOnly?

**Comment by NateWr** [comment]
@bozana That sounds good. Was the recommendOnly option intended just for the review stage, or does it work on all stages?

**Comment by vmozer77** [comment]
If possible, I would recommend having the recommend only option relevant to all stages / actions as this would make the entire process (from submission to publication) much more flexible. I understand that this means more work to address this issue, though.

**Comment by bozana** [comment]
Yes, originally, the recommendOnly was meant to be just for review stage... I'll investigate what is needed for other stages...

**Comment by t4x0n** [comment]
thanks for consider it!

**Comment by vmozer77** [comment]
@bozana Thank you very much for considering it. Maybe for now a simple email notification of a higher-level editorial staff upon action of sub-editor would be sufficient and further tweaking can be done in the future.

**Comment by bozana** [comment]
Hi all, this is considered together with this issue: https://github.com/pkp/pkp-lib/issues/3039, see the PRs there...

**Comment by t4x0n** [comment]
Hi, I have problems with Sub Editors now: in OJS 3.1.0-1 they have not permission to view the button "Send to Review" but they need it! The main idea was to remove permission for "Accept and skip review" button and for "Decline Submission" button, replacing both for one button for send a recommendation. In this moment, Subeditors are not able to Send to Review, and in my case now I had to disable the role option "This role is only allowed to recommend a review decision and will require an authorised editor to record a final decision." for solve this problem... 

@vmozer77 are you update to OJS 3.1.0-1? what do you think about that?

**Comment by vmozer77** [comment]
Apologies for the superlate reply. We too have updated to OJS 3.1.0-1 and I agree with you @t4x0n that this is not a very good solution. If I may resugest a general solution for subeditors at any given stage of the process would be that they would have all options available as per usual, however, they actions would have to be confirmed by an editor or someone with the rights to do it. Automatic notification of editors about subeditors having made a suggestion for an action would be great, of course, to make it work seamlessly.  Thank you in advance.

**Comment by bozana** [comment]
Hi @t4x0n and @vmozer77 

The recommendOnly option first came in connection with the review stage i.e. not to allow some users to make the review decisions, but to just be able to make a recommendation.
Then the problem was that there are some decisions on other workflow stages, that such recommendOnly users could made, which would lead in accepting the article and promoting it into the next workflow stage. So we disabled them for recommendOnly users.
I can see a point that those users would also need to send a submission to the review stage, because they are in a way responsible for review and will make their recommendations on it. Thus I will change that -- so that recommendOnly users also see "Send to Review" button. The PR is coming but it will have to be reviewed.

What @vmozer77 further suggests/requests is unfortunately much more and requires a new design of other workflow stages, possible actions, notifications, decisions. Thus, could you maybe ask for that in a new issue or in the section "Feature Requests" in the support forum? This would need a few others to discuss and decide on that, and would, depending on the decisions, eventually mean much more changes.

**Comment by bozana** [comment]
I opened a new issue: https://github.com/pkp/pkp-lib/issues/3436
Similar, the other/bigger changes request could be described...
