### ISSUE TITLE
DOAJ export in prefered language

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3119]
s. https://forum.pkp.sfu.ca/t/doaj-plugin-and-multi-language-articles/17210/12

**Comment by bozana** [comment]
@emanuil-tolev, sorry to bother you this way again :-( Are there maybe any plans at DOAJ to display and consider all languages the metadata are provided/registered with? -- Currently, DOAJ only considers/displays the first element i.e. the first language provided, I think.
The multilingual journals, having articles in different languages, or at least their metadata, would probably like to provide them all for users.

**Comment by dommitchell** [comment]
Hi Bozana,

We have discussed the options of displaying more than one language for multilingual journals and it is something on our To Do list. We will know more later next year.

Let me know if you have any other questions,

Dom

**Comment by bozana** [comment]
Thanks a lot @dommitchell!

**Comment by redukr** [comment]
I'm sorry, but is some solition for this request?

**Comment by asmecher** [comment]
I believe this would need to be added to DOAJ before OJS can support it... @dommitchell, do you know if this has moved along since the last update?

**Comment by redukr** [comment]
@asmecher i tried to change in plugin strings from getLocale(), to getLocale(en_US) by analogy as i did for crossref. but it doesn't work...

**Comment by dommitchell** [comment]
Hi folks, no we haven't progressed this one yet.

**Comment by redukr** [comment]
@dommitchell  @asmecher  maybe you can give some help, how to implement only english export to doaj? because we have about 1500 articles, and it's a little bit boring to remove all non-english names/abstracts/article naming/keywords ))

**Comment by dommitchell** [comment]
@redukr which journal? What's the ISSN?
This is the original solution we had discussed in 2017.

**Preferred Language plus Alternative Title Solution**
We extend the data model to include "alternate" titles for the article. These we could also add a language tag, so that there's no data loss. We would also need to take into account changing the interface to display these alternate titles.

On our roadmap for this year is "translations" and support for languages so we would look to extending the solution above to cover most of the elements that you mention.

**Comment by redukr** [comment]
@dommitchell 
https://doaj.org/toc/2617-9792

i have upload some data in automated mode, but when realise that it had upload cyrylic characters, i have just update data with english. so i have stop temporaly uploading, to make some solution, because i understand, that nobody will translate Ukrainian to English to understand about what is written all our articles.

**Comment by dommitchell** [comment]
@redukr let's take this conversation to email as it sounds like, at this stage, there are some usability issues that we could discuss first. What email address can I email you on?

**Comment by redukr** [comment]
@dommitchell red.ukr@gmail.com

**Comment by redukr** [comment]
i am not very good user of github, so i just put fixed files here.
https://github.com/redukr/ojs-doaj-english

**Comment by ruienf** [comment]
Hi!

I've encountered the same problem; for me, the "on-the-fly" solution was to sort the locale keys (our journal has 3 languages - pt_PT (primary), en_US and es_ES).

Although our primary language is pt_PT, we'd like to have the english version of our titles, abstracts and keywords in DOAJ (for better dissemination of our articles).

We're able to get a proper .xml file order by adding ksort ($articleTitles), ksort ($articleAbstracts) and ksort ($articleKeywords) in filter/DOAJXmlFilter.inc.php.

[DOAJXmlFilter.inc (sort).zip](https://github.com/pkp/pkp-lib/files/6478120/DOAJXmlFilter.inc.sort.zip)


But this only worked because en_US is the first key in an alphabetical order...

It would be great to have an option to define the locale/language order in the settings page of the plugin, so that the user can decide which language will be considered in the DOAJ upload.

Can you help me getting that done?

Thank you!

Kind regards,

**Comment by dommitchell** [comment]
In case it is of any help to PKP, DOAJ displays the first language from the result of doing a FIND operation on the XML. The results come back in DOM order.

**Comment by NateWr** [comment]
Closing this as outdated, but please open a new issue if there are still multilingual issues with the data OJS distributes to DOAJ.
