### ISSUE TITLE
[OJS] Submission Requirements translation are not available

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3156]
Hi,
I checked this with a fresh install of OJS 3.1 : I do install with fr_FR as default language and en_US as additional language. When you post a new submission, the Submission Requirements are only  available in fr_FR, even interface is in en_US.
Same behavior in Settings -> Workflow -> Submission.

Thank you

**Comment by bozana** [comment]
Hi @forgive38,

Hmmm... I am not sure I understand it correctly. 
How exactly do you try to add a new submission and what problem exactly occurs? What have you chosen as a submission language?
What exactly is the problem in Settings -> Workflow -> Submission?
Thanks!

**Comment by crosfield** [comment]
@bozana He means that by default there is no translation of submission requirements into English. I confirm this. In Russian/English interface it is the same. By default, the fields with English choices are empty.
@forgive38 It is necessary to make the translation into English manually in Settings -> Workflow -> Submission on your language first and then they will appear on the English interface.

**Comment by bozana** [comment]
Ah, OK, I see... :-)
When a journal is installed only the default settings for the currently used UI locale are installed, s. https://github.com/pkp/pkp-lib/blob/master/classes/db/SettingsDAO.inc.php#L171. 
All siteSupportedLocales are also set to be supported (as UI locales) by the new journal, s. https://github.com/pkp/ojs/blob/master/controllers/grid/admin/journal/form/JournalSiteSettingsForm.inc.php#L124.
The journal settings (and thus also those default localized settings) can only be edited in/for a locale if that locale is enabled for forms (under Settings > Website > Languages). Thus, maybe to install those default localized settings when a new locale is enabled for forms? -- If a locale is enabled for UI but not for forms, the author or reader will be able to use that UI locale, but will see the submission check list only in the existing, primary locale, which is OK, because the the other locale is not enabled for forms so the check list cannot be edited and adapted.
I'll provide a patch...

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3163
ojs master: https://github.com/pkp/ojs/pull/1750

**Comment by bozana** [comment]
@NateWr, could you take a look at these PRs?

**Comment by bozana** [comment]
Thanks! I will then merge -- everything green :-) -- and will immediately add a new OMP commit/PR that removes that key...

**Comment by forgive38** [comment]
hi @bozana 

Thanks a lot for this PR.
Just one thing, maybe it could be great if this reload is trigger when we "Reload defaults" (Settings > Website > Languages). I have to uncheck Forms checkbox and re check to have the translation for Submission Requirements reload

Thank you

**Comment by bozana** [comment]
Hmmm... Strange... I do not see the option "Reload defaults" on the page Settings > Website > Languages :-( Where do you see it?

**Comment by forgive38** [comment]
This option is when you expand a language : a link named Reload Defaults appears
![image](https://user-images.githubusercontent.com/31130607/33873470-5a457976-df1b-11e7-96a7-9b93a74c5e79.png)

**Comment by bozana** [comment]
@asmecher, could you take a look at this PR: #3201? -- it reloads default localized context settings at locale reload... THANKS!

**Comment by asmecher** [comment]
Looks good, and good catch. Please go ahead!

**Comment by forgive38** [comment]
Hi
Can you merge to ojs stable 3 1 0 too ?
thank you

**Comment by Yogeshsinghbisht** [comment]
The language select option is blank in OJS Installation.
Contact : [www.openacessjournal.com](https://www.openacessjournal.com/)

**Comment by asmecher** [comment]
@Yogeshsinghbisht, if you're looking for technical support, can you post on our support forum at https://forum.pkp.sfu.ca? Include what version of OJS you're using, what language, etc.
