### ISSUE TITLE
[OJS 3.1] Add id attribute to TOC sections for styling

### ISSUE THREAD

**Issue by dastewo** [pkp/pkp-lib#3181]
Hello there,

as mentioned https://forum.pkp.sfu.ca/t/add-section-id-to-toc/36173 it would be a good feature to add section ids to the issue tocs, so people might be able to style every section in a different way and it might be a foundation for anchor links.

Here is the pull request: https://github.com/pkp/ojs/pull/1758

Kind regards
Daniela

**Comment by NateWr** [comment]
Hi @dastewo, thanks for the contribution! I've read through the thread on the forum. As I understand it, you'd like the ID to tailor the styling of specific sections as well as add anchor links.

I'm hesitant to use `id` attributes in the HTML elements because of the risk of naming collisions. However, I can see that they'll be important for anchor links. If we're implementing them, I'd like to see a more unique naming schema, prefixed with OJS, to minimize the chances for naming conflicts. Something like `ojsTocSection<sectionId>`.

On a separate note, I'm not sure if section IDs are the best unique value to use for the CSS selectors. If you're writing a stylesheet on a local dev installation, your section IDs may diverge from those on the live site, which would introduce some friction to moving between dev, staging and production instances.

What do you think about using the section abbreviation in the primary language? This is required, will almost always be unique within a journal, and is configurable so that styles can be pegged to the same selectors across all instances.

**Comment by dastewo** [comment]
Hi @NateWr,

I understand your concern regarding the naming schema, so I wouldn't mind, if it would be changed.

However, I am not so sure about using the section abbreviation. In the beginning I wanted to it with the abbreviation, but there are two aspects against it (in my opinion at least): The primary locale is in our case most likely German and there are some letters, which are not suitable for css-classes (like "Ä" for example). It is also not possible to always use the english abbreviation, because some of oure journals are only available German (and I think it might be even worse for languages like Russian, Mandarin or Hindi).  
The other aspect is, that I think it might need many more changes to get the section abbreviation. For the IDs you just need to change the template, but the abbreviation must first be fetched in the php files.

Maybe I am wrong, so feel free to correct me :-)

**Comment by NateWr** [comment]
Closing this as outdated.
