### ISSUE TITLE
[OJS] Extend search capability to search issue metadata and galleys

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#321]
OJS' search only searches article content. Some journals include a fair amount of information in their issue data page, and also upload issue galleys. This information should be searchable as well.

**Comment by GrazingScientist** [comment]
Although this may be a desirable feature for some journals, there may be some journals (like one of mine) that have an issue galley which (more or less) duplicates the article galleys in one big file. Hence, when the search also returns issue galleys, both PDFs (the relvant article galley and its issue galley) will come up, because they both include the search terms.
Consequently, there should be an configuration option saying whether to search only article galleys or only issue galleys or both.

**Comment by NateWr** [comment]
Closing this as outdated. Please consider filing this request in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
