### ISSUE TITLE
Add submission ID to email subject for all submission-related emails

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3227]
Editors and section editors often track submissions by ID and would like to always see the submission ID in all email correspondence. We have now received this request from multiple hosted journals.

**Comment by asmecher** [comment]
It should always be possible to add `{$submissionId}` to email subjects.

**Comment by mfelczak** [comment]
Thanks @asmecher. To clarify, are you suggesting that each JM should edit all of the existing editor/author/reviewer email templates and add `{$submissionId}` to the subject?

Related follow-up: are the email templates under Settings => Workflow => Email also used for system notifications related to submissions, e.g. email key 'NOTIFICATION'?

**Comment by asmecher** [comment]
@mfelczak, yes, I'm hesitant to add this en masse to all email templates -- I think managers are going to want a mixture of things in email template subjects, e.g. journal initials, submission IDs, both, or neither, and perhaps want different things in different templates (e.g. IDs for internal users but not for external users like authors and reviewers).

It's not currently available for the `NOTIFICATION` template -- this template is used for both submission-related and non-submission-related purposes.

**Comment by mfelczak** [comment]
Thanks @asmecher! In that case, would it worth filing this as a separate issue to distinguish submission from non-submission notifications? We have clients that would like to have submission IDs for both email templates and system notifications for submissions.

**Comment by asmecher** [comment]
Are there notifications in particular they would like this information available for? If we do implement this, I'd like to ensure it's not invasive or a pain to maintain, and duplicating the email template for this purpose would be an iffy approach IMO.

**Comment by jmacgreg** [comment]
Hi all, we just had another client request this. We'll suggest for now that they manually add the {$submissionId} to their subject lines. I'd also like to suggest that this be flagged as a candidate for future UI/UX testing ("this" being email/notification management). A few further notes: 

* folks who have asked for this would like the submission ID, and probably journal initials, in emails. Usually as "[journalInitials] [MS 123]". 
* allowing these variables to be added to email subjects is all well and good, but if they aren’t there by default, that’s a problem, because people don’t actually know what variables are available to them (or that they can be added to subject lines). This could be partially resolved by exposing available variables in email templates (see #3253), but it would still require a lot of manual intervention by managers, and additional clarity that these could be added to subject lines, and I'm not sure how that would look or work from a UI/UX perspective. 
* likewise, providing a global default that could then be overridden sounds good, but I have no idea how that would work in reality. 
* these should be available for all submission-related emails, whether notifications or prepared emails. Any email that mentions a submission should have the ability to identify, in the subject line, which journal and submission ID it belongs to.

**Comment by defstat** [comment]
Hi all.

I add a PRs regarding this (as a first approach to that, and to have something to work on):

pkp-lib: #4145

2 settings have been added to Workflow Settings > Emails > Default Subject Additions

![image](https://user-images.githubusercontent.com/560456/46949656-d7d62500-d08a-11e8-9b42-3c2a3e01cb3b.png)

Where the user can globally enable the provided pattern to be added to every submission related email (SubmissionMailTemplate) if the `Enable Submission Id` is enabled. 

The wording of the labels is for display purposes, and it will need changes.

**Comment by asmecher** [comment]
Thanks, @defstat -- I think this could use a little more work. I don't think it'll add submission IDs to `NOTIFICATION` emails, which IIRC aren't currently `SubmissionMailTemplate` instances, and won't always have submission IDs (e.g. for notifications that aren't attached to submissions, like announcement notifications). I'd also like to see if there's a way we can support better control over emails by editors without adding new setup areas, as these kinds of settings are useful but can really accumulate into an unwieldy UI as they collect.

I think the submission ID should already be embeddable using `{$submissionId}` in almost all email templates, and the editor can formulate the message however they like using that -- but the real problem is the `NOTIFICATION` template, which doesn't currently support it, and won't always be able to.

**Comment by jmacgreg** [comment]
(Sorry - I accidentally closed this. Still very relevant!)

**Comment by amandastevens** [comment]
This is a very popular request for Publishing Services clients.

**Comment by NateWr** [comment]
Related to https://github.com/pkp/pkp-lib/issues/5730.

**Comment by asmecher** [comment]
@defstat, this is not a priority for 3.3, but please don't forget this issue!

**Comment by defstat** [comment]
@asmecher @NateWr 

**PR**
pkp-lib: #6794

**Comment by asmecher** [comment]
@defstat, just thinking about general approaches that could work... your approach is probably the least invasive, but it only supports IDs as suffixes and will be confusing/redundant for users who have already added IDs to some email subjects etc.

How about something like this?
- Break the `NOTIFICATION` email template into three separate templates:
  - `SUBMISSION_NOTIFICATION` for submission-specific notifications
  - `CONTEXT_NOTIFICATION` for journal/press-specific notifications (that aren't submission notifications)
  - `SITE_NOTIFICATION` for site-wide notifications
- Review the notification system to make sure the right notification template is used for each case
- Add `[{$submissionId}]` prefixes to default submission email subjects (this will only affect new users, not existing ones) -- I think standardizing on this behaviour will be accepted by the community and will resolve @jmacgreg's concern about the work required in adding IDs.

I think having separate notification templates for each situation will make it easier for us to describe what variables are available for each circumstance -- the `NOTIFICATION` template has always been a source of confusion -- and that template has always been too general-purpose to be very useful anyway. (In the future, I would like us to rely on it less.)

**Comment by asmecher** [comment]
This should already be taken into account per @Vitaliy-1's email changes for 3.4!

**Comment by NateWr** [comment]
An alternative approach to including journal initials is described in https://github.com/pkp/pkp-lib/issues/7104.

**Comment by Vitaliy-1** [comment]
Done. `submissionId` email template variable is now assigned to all submission-related emails.

**Comment by jmacgreg** [comment]
Woooo!!
