### ISSUE TITLE
Add ability to upload full width header images

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3233]
Could we reconsider the decision to remove the ability for journals to add full-width headers via the Website Settings? Some of the most attractive OJS 3 implementations are making use of this kind of header:

https://fennia.journal.fi/index

It would be great if we could make this easier for those wishing to do something similar.

**Comment by alexxxmendonca** [comment]
I would like to check the header for that website but it's asking for login and password.

**Comment by ajnyga** [comment]
We are upgrading to 3.1 ;) (but with poor success)

It will be open within two hours.

**Comment by asmecher** [comment]
@NateWr, assigning to you for consideration/discussion!

**Comment by ajnyga** [comment]
Just pointing out here that in our case the header image is added using a setting in a child theme with the structure coming from a parent theme. 

I would (once again) see how Wordpress is doing this in their twenty-themes.

**Comment by NateWr** [comment]
In Sophy's health sciences theme, we're using the Homepage Image to do this. I don't see any reason why this can't be used by anyone who wants to do so.

**Comment by ajnyga** [comment]
Maybe that setting/image could be then simply renamed to something more appropriate? Header Image etc.

And then you could edit the default indexJournal.tpl and move the additional content section https://github.com/pkp/ojs/blob/master/templates/frontend/pages/indexJournal.tpl#L77-L82 to the top of the page? This is something that is constantly requested on the forum I think. With the additional content section on top, you can add a homepage image there if needed.

Or just leave the whole thing as it is :D

**Comment by stranack** [comment]
Having the ability to upload both a Header Image and a Home Page Image was a popular feature in OJS 2.

**Comment by NateWr** [comment]
The reason most of the best designs you've seen have used header images is because those have all been custom designed around particular content. I don't think adding an image into the header of the default theme will make sites that look bad look better, because those sites already lack artistic direction. The chances of them choosing a sensible image that looks good is low.

Instead, I think we'll be likely to see more sites trying to hack text into the header image, which is neither accessible for those with visual disabilities nor is it readable for mobile devices.

We have Sophy's theme coming out and as we make more available I think this problem will recede. But I don't think adding a second image to display in the default theme will have the beneficial effect you're hoping for.

**Comment by NateWr** [comment]
An option to use the homepage image in the header was added in https://github.com/pkp/pkp-lib/issues/4683.
