### ISSUE TITLE
No notification is sent to editor when author uploads a new file version

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#3278]
Although exists a filled issue related to request confirmation of revised here https://github.com/pkp/pkp-lib/issues/2665, this one is regarded to author. 
There is a scenario where editor also  gets no notification when a new file version is uploaded in a submission workflow.

This was tested and if necessary, screenshots from this test can be sent in PM. What happens is as follows:

- If is  selected “Request revisions”,  editor gets an email notification when author uploads new versions (both duplicate and new file cases).
But:
- If is selected “Resubmit for review”, editor gets no email notification when author uploads new versions (both duplicate and new file cases).

**Comment by bozana** [comment]
@israelcefrin, what is the content or subject i.e. what e-mail template is sent for the first case above "Request revisions" ? And what version has this been tested with? -- I believe all this changed somehow in the new version...

**Comment by bozana** [comment]
This changed so that no notification exists any more, but only the review round status is changed, s. https://github.com/pkp/pkp-lib/commit/d66ab34735eb791882d11e7826cf48755b5f1ac5#diff-a293ff86bd7eb54b4ef4cb047dd4c550.
It seems that earlier the notification NOTIFICATION_TYPE_ALL_REVISIONS_IN with the message "A revised file has been uploaded for your editorial consideration in {$stage}." was sent to the assigned editors if first revision was uploaded by the author and the review round status was “Request revisions”. This notification was not only used for e-mail, but also for the notification on the review round page. Now, when the review round page notification is decoupled from the e-mail notification -- the review round page notification contains now the review round status message -- could/should the new e-mail notification maybe be extended so that it is send every time a revision is uploaded by the author (and not only first time)? I think it would make sense -- if the author uploads further changes, the editor would maybe like to know it, correct? As required here, the e-mail notification would also be sent if the review round status is “Resubmit for review” (and not only “Request revisions”).

The issue #2665 asks if the author could then somehow get the information that the editor is notified or if a dialog box could be implemented where the author can choose if the editor should be notified. I think we could leave this more sophisticated solution/improvement for later and for now i.e. for 3.1.1 only send the e-mail notifications automatically every time a revision file is uploaded for those to review round statuses. Unless @NateWr would have an idea that is simple to implement/solve immediately :-) What do you think? Above all @NateWr?

**Comment by NateWr** [comment]
I don't like sending an email with each file. It will be annoying if there are several files. But it's better than no email so let's go ahead for 3.1.1 and leave a more comprehensive solution for when we take a long look at notifications in general.

**Comment by bozana** [comment]
Hmmm... If we do not want to send the e-mail notification for each revision upload, we could send it only at the first, as it was earlier, I believe -- We could eventually send it when the review status changes accordingly. Would that be better @NateWr?

**Comment by NateWr** [comment]
It's hard to know. Because the editor might want to know when they've sent all of them. Like, they might get 3 emails in 10 minutes, and then nothing for an hour, and then they can know the author's probably done. I'd say just send them all. Short of a smart system that can track whether the editor has logged in to look at them, and not send duplicate notifications if they haven't yet, it's probably best just to send everything.

**Comment by ajnyga** [comment]
Related to the discussion of sending/not sending notifications on each file upload
I suggested here: https://github.com/pkp/pkp-lib/issues/2665#issuecomment-320590391 that "instead of having that automation there, how about just having a button that you use to confirm that you have uploaded the requested revisions. This could a button that appears when there is at least one file uploaded to the revisions grid."
Of course there are downsides in this option as well.

**Comment by NateWr** [comment]
@ajnyga There's a PR that implements something like this, along with my own concerns about usability. 

https://github.com/pkp/pkp-lib/pull/3169

I'm not against it, but we'll need to implement a few additional things around it to ensure it's clear to the user what they must do.

**Comment by asmecher** [comment]
I see 4 of us are already active on this one! Does anyone want to claim it?

**Comment by bozana** [comment]
The following PRs solve this as well as the issues https://github.com/pkp/pkp-lib/issues/3326 and  https://github.com/pkp/pkp-lib/issues/2618, using the PR https://github.com/pkp/pkp-lib/pull/3169 as a basis (but changing it as discussed there):
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3399
ui-library master: https://github.com/pkp/ui-library/pull/10
ojs master:  https://github.com/pkp/ojs/pull/1840

**Comment by bozana** [comment]
@asmecher, could you review the PRs above?

**Comment by asmecher** [comment]
Very nice -- a net decrease in code size, locale changes handled, and a functional improvement. Please go ahead, @bozana!
