### ISSUE TITLE
Create add/delete journal cli tool

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3281]
This tool should be able to add or delete a journal to a hosted install, given the following parameters: 

* journal name
* abbreviation (path)
* primary contact
* super user (username, or first/last name + email address)

**Comment by ajnyga** [comment]
Maybe also a true/false flag to control whether the journal is visible or not (default could be true)? In many cases the new journal is first hidden to give the editors time to go through the settings.

**Comment by israelcefrin** [comment]
Hi @ajnyga I think that we could use this flag to enable/disable, and, as a third option in future, use it  to set a journal to maintenance mode. Something like:

`$ ojs journal --create name="Test Journal" path=test-journal primary=primary@domain.com su-username=admin su-email=admin@domain.com  status=disable/enable/maintenance ...`

And if none status given, default disable as you said.
`$ ojs journal --create name="Test Journal" path=test-journal primary=primary@domain.com su-username=admin su-email=admin@domain.com  ...`

I am not sure if all parameters should be passed into a single line or entered by prompting.

**Comment by asmecher** [comment]
@israelcefrin, we do have a few interactive tools (that prompt for values), but I don't think they've seen much uptake, and they limit the usefulness of the script in fully automated scenarios (such as the "install" script). I'd suggest that all parameters be entered via the command line.

We don't currently have a good pattern for name/value pairs in command lines, but I suggest we keep it similar to UNIX standards, so e.g.:

`php tools/journalTool.php create --name="Test Journal" --path="test-journal" --contact-email="primary@domain.com"`

I would recommend against tying user creation into journal creation, since they're separate tasks. Perhaps a second command with `tools/userTool.inc.php` (which is a tool incorporating common user operations).

**Comment by israelcefrin** [comment]
@asmecher I agree totally using UNIX standards, and I would like to know it would  it be feasible use a command line based in a phar archive (as [WP-CLI ](https://github.com/wp-cli/wp-cli) does). For instance, we could run something like:
`ojs-cli create test-journal --name="Test Journal" --contact="primary@domain.com"`

I will double check and document these desirable and initial parameters.

Also, given that this script will run in terminal only we could avoid memory limit issue that a regular php script may show adding a parameter in phar such:
`ini_set( 'memory_limit', -1 `);` 

This way we could share a full single package. Then each new release, with , features and/or bug fixes, would keep a single use file, i.e.: `wp-ojs.phar`. 

What do you think?

**Comment by asmecher** [comment]
The whole OJS installation would still need to be on hand, no? I'm not sure what the benefits of a phar archive would be here (having never worked with them before except as a casual user).

**Comment by israelcefrin** [comment]
Hi Alec, I've suggested phar file only taking in mind memory limit setting that we could declare in one single file and not be in risk of timed out limit (I think that's the way wp-cli works).
But I also never worked with that before and think that perhaps it could bring unnecessary complexity to development. 
As you suggested I will work on defining parameters and I agree that something like `tools/userTool.inc.php` could be easier to use at all.

**Comment by asmecher** [comment]
I think a few `ini_set` commands could be added for command-line execution in the `lib/pkp/classes/cliTool/CliTool.inc.php` parent class.

**Comment by NateWr** [comment]
@israelcefrin As we discussed, here's an example start on a CLI command that will use the new shema, validation and service classes:

https://github.com/NateWr/ojs/blob/i3281_cli_context/tools/ojsCli.php

You can find it and work from the classes which aren't yet in `master` by basing off of this branch:

https://github.com/NateWr/pkp-lib/tree/i3594_forms

A couple of things that came up:

1. The code in this example is almost working, but not quite. It creates the context. But you'll run into an error:

```
PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/www/html/ojs/lib/pkp/classes/services/PKPContextService.inc.php:353
```

This is because there's no logged in user when running the commands. A lot of the code that you'll run in the CLI will expect there to be a user. The system will need to be able to look in the `Request` object for a user, with `$request->getUser()`. You'll probably need to come up with some way of running a command as a user (eg `command -u nate -p`). 

2. When compiling the props from a command, weneed some way for people to pass multilingual props. For this implementation, I used a simple `.` notation that "looks like" Javascript objects:

```
ojs context add --name.en_US="Journal name in English"
```

You can re-use this for properties which themselves are not primitives, like arrays and objects:

```
ojs context add --logo.uploadName="logo.png" --logo.altText="The logo for our journal"
ojs context add --submissionChecklist.0="Use 12pt Arial" --submissionChecklist.1="Put your name at the top"
```

But you may want to talk with others about how best to handle this type of data. Perhaps there is a pre-existing standard for linux commands that we can draw on.

:+1:

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
