### ISSUE TITLE
Display usage statistics for last 12 months instead of for current year

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#3283]
Currently OJS 3 usage statistics display on the article page for the current year, which means they reset to 0 at the beginning of each year.  Users have requested the option to show usage statistics over the last 12 months instead.

See https://forum.pkp.sfu.ca/t/viewers-statistics/36616

**Comment by alexxxmendonca** [comment]
I second this and it's somewhat related to #2820

**Comment by NateWr** [comment]
This should probably be the default setting.

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3347
ojs master: https://github.com/pkp/ojs/pull/1824 (only submodule update)

**Comment by bozana** [comment]
@NateWr, could you take a look at the pkp-lib PR above? -- It only makes changes in the JavaScript code i.e. we still get all possible years from the DB and then filter them here, with the JavaScript. This is because earlier we were thinking about letting the user select an existing year. If we are sure that we would like to keep it like this -- to only display the last 12 months -- then I could once (maybe in the next release) change the way we get the data from the DB.
Also, the x-axis still displays only months (and no years), e.g. currently it looks something like this:
![statisticsgraph](https://user-images.githubusercontent.com/378421/35814138-39b38994-0a8d-11e8-9324-02a430d72c80.png)

OK so?
Thanks a lot!

**Comment by NateWr** [comment]
PR looks good. I just had one question.

> Also, the x-axis still displays only months (and no years), e.g. currently it looks something like this:

Looks good to me. I think the year will be understood implicitly.

**Comment by bozana** [comment]
OK, I will then fix the one issue and merge... Thanks a lot!
