### ISSUE TITLE
"User" and "Primary" (navigation menus management tools) are confusing

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3287]
Users were confused by the names "User" and "Primary" in creating navigation menus. We need to avoid terminology that's not going to apply to all themes (e.g. "top menu" may not be in another theme), but find some more helpful terms.

- Maybe "Top User Bar" vs "Navigation Bar"?
- Maybe surface the menus directly to provide context, rather than focusing on clearer naming?
- Maybe “main navigation menu” and “login...” or “user navigation menu”?

**Comment by defstat** [comment]
@asmecher @NateWr 

For brainstorming: I propose a new page (for the time not editable) that displays the NM Areas like below:

![nmareasdesign-2](https://user-images.githubusercontent.com/560456/35183055-673ab560-fde8-11e7-9c13-c3a9dbbb460d.jpg)

That could be accessed from within the NM Manage Page like below:

![nmareasdesign-1](https://user-images.githubusercontent.com/560456/35183059-7f541d26-fde8-11e7-87aa-3baa9d5eea66.jpg)

That page can be (probably transformed to a form, where the user can see the NM Areas and the available NMs, and drag-drop them inside the interface. 

I have prepared a prototype for that solution (without the "editor" for now)

**Comment by Vitaliy-1** [comment]
Nothing confusing in navigation menus names to me...

**Comment by NateWr** [comment]
@defstat, that could be a good start. I think we may need to go a bit further and even consider moving beyond the grids. But we can see if that helps.

@Vitaliy-1, we recently did some user testing of the new navigation menu feature and this was flagged up as a common source of confusion. I wouldn't expect a developer like yourself to find it confusing, but non-technical users come with a different perspective. In this case, the issue was that Primary and User alone didn't even signal to them that they were navigation menus, or what they related to on their site.

**Comment by defstat** [comment]
I have prepared something like that 
![image](https://user-images.githubusercontent.com/560456/35529553-0c9fb908-053a-11e8-891b-0c00994af809.png)

**Comment by NateWr** [comment]
@defstat That looks good for now. Let's make the change and see if that helps some. Can you also make the change to the default menus that are added on installation, to change the names to include the words "navigation menu"? So:

User Navigation Menu
Primary Navigation Menu

**Comment by stranack** [comment]
Can you replace {$loggedInUsername} with just Username ? Including that kind of code in the description can create confusion for some users.

**Comment by defstat** [comment]
@stranack something like 
![untitled](https://user-images.githubusercontent.com/560456/35780770-08a92790-09e9-11e8-9dc7-fe682636b914.png)

@NateWr Currently the "Title" of a NavigationMenu is its "key" to distinguish it. On update, the process checks if there is another NM with the same name and if there is not one, it adds a new. So if we change the name from "User" to "User Navigation Menu", when ojs/omp gets updated, a new NM will be installed with "User Navigation Menu" title, along with the "User" NM.

Maybe one way to "fix" that would be to add a guid, or some other "id" to identify the NM in the XML file and update the entry to the database using that "id". Another solution could be to add another field to NMs, the "displayed title", which we can modify to what ever we like, and keep the "title" column as the NM identifier (which is the same as the previous solution in fact, but instead of a guid we use the existing column as "id"). Maybe @asmecher has another solution for that.

**Comment by defstat** [comment]
@NateWr 

PR
pkp-lib: #3346

**Comment by NateWr** [comment]
Another idea for addressing the update issue would be to check if a navigation menu is already "assigned" to a navigation menu area. If it is, we can assume that setup is "done" and not make changes. If it's not, we can go ahead and create the new menus. Would that work?

**Comment by asmecher** [comment]
@defstat, about identifying menus, these are translated keys, right? What happens when a translation changes? Is the existing menu identified based on the translation in e.g. the primary language?

**Comment by defstat** [comment]
@asmecher No, the title of the NMs are fixed (mainly because the "title" is not displayed outside the administration pages)

**Comment by NateWr** [comment]
@defstat Nice work on the nav items in the grid PR. I've merged that. What did you think about this approach for updating the navigation menu titles?

> Another idea for addressing the update issue would be to check if a navigation menu is already "assigned" to a navigation menu area. If it is, we can assume that setup is "done" and not make changes. If it's not, we can go ahead and create the new menus. Would that work?

**Comment by defstat** [comment]
@NateWr I think that this approach would not insert the "new" NM, but would not update the already existing one either. (if I understood you correctly)

**Comment by NateWr** [comment]
Hi @defstat. Correct. But the goal will be to use the new titles for new installations.

**Comment by defstat** [comment]
@NateWr If we don't care about updating the currently installed NMs in any way (not only regarding the title), then yes this approach will do the trick.

**Comment by NateWr** [comment]
I'm ok with that. @stranack what do you think?

**Comment by defstat** [comment]
Reminder @NateWr @stranack

**Comment by stranack** [comment]
Sounds good to me.

**Comment by defstat** [comment]
@NateWr 

PRs
pkp-lib: #3382
OJS: pkp/ojs#1837
OMP: pkp/omp#502

The PRs checks if the NM that is trying to be installed has an area that already has a NM attached to it. If it does the NM is skipped from the installation/upgrade with a warning. 
If the user wants the new default NM to be installed, he can detach the already installed NM from any area and then run the upgrade tool.

**Comment by NateWr** [comment]
Sorry for the delay @defstat. This looks good! I just had the one question for Bozana about logging things during install. I'm not very familiar with our install/upgrade stuff. 

Otherwise it's ready for merge. Just needs a rebase. Let me know when that's done and I can merge.

**Comment by bozana** [comment]
Oh, I see my name here, but apparently I have missed something earlier, or?

**Comment by NateWr** [comment]
Referring to this comment @bozana. I just made it so you didn't miss anything. :) https://github.com/pkp/pkp-lib/pull/3382#pullrequestreview-101572949

**Comment by NateWr** [comment]
@defstat looks like all is well with that comment. So once you rebase let me know and I can merge it.

**Comment by defstat** [comment]
@NateWr PRs are rebased. Thanks!

**Comment by NateWr** [comment]
:+1: can this issue be closed?

**Comment by defstat** [comment]
@NateWr we could close it for now and see if the changes work for the users. If we have anything else to do, we could open it again, if you agree.
