### ISSUE TITLE
Replace homebrew caching library with 3rd-party caching library

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3304]
Suggested: Stash (https://github.com/tedious/Stash).

The `object_cache` configuration and Memcache support also need review, testing, or removal.

**Comment by asmecher** [comment]
Another good option (perhaps better): Laravel's caching component https://laravel.com/docs/5.0/cache

**Comment by NateWr** [comment]
Just a note: you'll probably need to use v5.5, since that's the version we use for the QuerySelector and Validator components: https://laravel.com/docs/5.5/cache

(Usually there's not much difference between 5.* versions.)

**Comment by asmecher** [comment]
See also https://www.phpfastcache.com/

**Comment by asmecher** [comment]
(See also the error message noted in https://github.com/pkp/pkp-lib/issues/4333 -- replacing the caching library would resolve that. However, it's cosmetic so a low priority.)

**Comment by asmecher** [comment]
Went with Stash as it's very widely used and fully stand-alone. Draft PRs:
- https://github.com/pkp/pkp-lib/pull/5743
- https://github.com/pkp/ojs/pull/2710

These remove several broken caching options, which can be re-added later using the new toolset (with a little analysis up front to check what would be the most effective stuff to cache).

**Comment by NateWr** [comment]
This looks great and very easy to use. I left a few comments on the PRs to help me clarify how it's working.

I'm trying to think about what standards and practices we put in place for how we're using this. Particularly in regards to the new entity service classes. 

There's a fair bit of annoying code that has to go into ensuring dependencies are passed down when getting the API properties for entities. For example, the submission properties rely on the submission context:

https://github.com/pkp/pkp-lib/blob/master/classes/services/PKPSubmissionService.inc.php#L176-L181

And then this has to get passed down to the PublicationService which has to do the same thing:

https://github.com/pkp/pkp-lib/blob/master/classes/services/PKPSubmissionService.inc.php#L200

Caching contexts may be one place where we can get a good win on making the code cleaner and improving performance, especially since they'll get loaded with every request in the frontend or backend.

For contexts, I'm thinking the following entity service methods should interact with cache:

- `get($id)` should get it from cache or db for cache miss.
- `add(...)` should save it to cache.
- `edit(...)` should update cache.
- `delete(...)` should clear that cache item.

I _think_ that this will suffice to keep the cache updated. That just leaves `getMany()` calls but those shouldn't be too common.

Presumably there is a size limit for how much we want to store in cache, so it wouldn't be a good idea to roll this out across all of our entities. Does Stash provide any support for per-request cache? I'm thinking of cases where someone makes a request for a submission and then we spend lots of energy passing this around as we fetch dependent entities (publications, contributors, galleys). Our auth system stores that object, but it would be nice if it chucked them somewhere that we could reliably check for a cached entity. I'm also thinking of cases like when the API returns a list of submissions. It would be nice if there was a way to say "don't go back to the database for this object" just for one request... Maybe that's not the right concern for a caching library.

**Comment by NateWr** [comment]
I forgot to mention another good use here would be for the editorial and usage statistics. The API responses (with no filtering params) could be cached on a daily basis which would make it much quicker to load the initial page. It would also make it possible to display this on the frontend without crippling the server.

**Comment by asmecher** [comment]
Thanks for the comments, @ajnyga and @NateWr. I've gone through and done a little clean-up. For easy access, here are those same PRs I posted earlier:
- https://github.com/pkp/pkp-lib/pull/5743
- https://github.com/pkp/ojs/pull/2710

I added a new one for the usage stats plugin, which did make use of the old file caching classes:
- https://github.com/pkp/usageStats/pull/29

(Tests are not passing via Travis, though I can run them locally; at a guess, this is probably due to the updated usageStats plugin not being available to the Travis tests.)

**Comment by asmecher** [comment]
@NateWr, I like what you're laying out for object caching. In previous OJS releases we had this for published articles, issues, and sections, which make sense as our emphasis on decreasing load should focus on the publishing front end. But I think a consistent application of a standard to the codebase at large will make for broad improvements, and make caching less of an occasional quirk and more of a built-in benefit.

> Does Stash provide any support for per-request cache?

Yes -- this is the [ephemeral](http://www.stashphp.com/Drivers.html#ephemeral) driver. I think we should code for one of several user-configured caching backends, with ephemeral being the fallback but also supporting e.g. APC, Rediff, and Memcached. I suspect any of these will lead to very considerable performance improvements.

I'm a bit on the fence about how to spread the caching implementation between the service classes and the DAOs. Just about all of our service class/DAO balance is transitional (in my opinion). I'm tempted to add it to the service classes as you propose and look into migrating some of the code that still prefers DAOs over to using service classes instead.

**Comment by NateWr** [comment]
> Yes -- this is the ephemeral driver. 

Is it possible to distinguish between permanent and ephemeral storage? For example, contexts should certainly get permanent storage if available. But a review assignment record we might only want to put in ephemeral storage during requests that require it... Or maybe this is not worth optimizing for?

 > I'm a bit on the fence about how to spread the caching implementation between the service classes and the DAOs.

I agree it should be in the service classes. :+1:

**Comment by asmecher** [comment]
> Is it possible to distinguish between permanent and ephemeral storage?
I'm not 100%, but generally I think this should be left up to the caching implementation. A good implementation should be able to handle an avalanche of new and never-to-be-used-again entrants while still maintaining other very frequently used entrants. I suspect the Ephemeral driver is the least sophisticated of the lot and just stores everything, possibly with an upper memory limit.

I'd suggest we start by coding this against the Ephemeral driver, adding infrastructural caching support as transparently as possible, but only enabling it optionally where we can identify an at-a-glance benefit (e.g. I can't think of a good reason to enable this for Review Forms, but published content, issues, nav menus, etc. definitely get the nod). Then if we're satisfied that we have a good, basic Ephemeral-based implementation, we can add options that send that store to the other implementations, which will be smarter and persist across requests.

The clear gotcha in that approach will be that assumptions we made about the cache refreshing for each new request when using Ephemeral will not apply once we move outside that, e.g. if we forget to have an update/delete operation clear the cached object. That's another reason to have caching disabled by default implementation, then have it enabled on a case-by-case basis.

**Comment by NateWr** [comment]
Sounds like a good plan. I mistakenly thought the driver would just be a config option and we wouldn't have to worry about it, but sounds like there's more to it. I agree moving cautiously is good. :+1:

**Comment by asmecher** [comment]
Unfortunately I am putting this on hold for now. The straight-up replacement of the current `FileCache` implementation with Stash is available in:
- https://github.com/asmecher/pkp-lib/tree/i3304-minimal
- https://github.com/asmecher/ojs/tree/i3304-minimal
- https://github.com/asmecher/usageStats/tree/i3304-fix

However, the [Travis build](https://travis-ci.org/github/asmecher/ojs/builds/708912023) is now considerably slower than it was [with the old implementation](https://travis-ci.org/github/pkp/ojs/builds/708858663).

Old implementation:
![image](https://user-images.githubusercontent.com/200411/87728928-fa720200-c778-11ea-9b88-295d377580a2.png)
![image](https://user-images.githubusercontent.com/200411/87729054-4cb32300-c779-11ea-808a-e4b19ce80db0.png)

New implementation:
![image](https://user-images.githubusercontent.com/200411/87728956-08c01e00-c779-11ea-8282-d80454c5fe28.png)
![image](https://user-images.githubusercontent.com/200411/87729081-5c326c00-c779-11ea-87b6-4808a4360c19.png)

I've audited the number of cache misses, and they don't seem different, so it seems to be inherent overhead in using Stash.

**Comment by NateWr** [comment]
Oh no! Devastating! :sob: Bit of a hailmary, but have you tried comparing the tests when run locally? I wonder if the low CPU of the Travis environments would lead to unusually slow serialization/de-serialization speeds?

**Comment by asmecher** [comment]
Unfortunately it's the same here; I needed to extend some timeouts, and subjectively my poor system really dragged compared to usual test runs.

**Comment by jonasraoni** [comment]
Perhaps the OPcache cache driver, which I've added to https://github.com/pkp/pkp-lib/issues/6328, will address the performance issue.

**Comment by asmecher** [comment]
Closing in favour of https://github.com/pkp/pkp-lib/issues/7111, which is essentially the same.
