### ISSUE TITLE
Should warn when substitution variables cannot be completed in DOIs

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#3317]
We found over 7K articles in the PKP Index that have DOIs that have %p and %x in the DOI field. These are not valid DOIs, and should not be exposed to the public in any way. 

For example, [this article](https://periodicos.ufsc.br/index.php/literatura/article/view/5453) has the following: 
```
<meta name="DC.Identifier.DOI" content="10.5007/%x"/>
<meta name="citation_doi" content="10.5007/%x"/>
```
They are not likely being successfully deposited to Crossref. Since OJS is now capable of knowing when a deposit is successful, it should avoid presenting the DOI on the abstract page or in the metatags until crossref accepts it. 

There are other examples where an invalid DOI is created. See [this article](http://ejournal.undip.ac.id/index.php/bioma/article/view/9413) with DOI: "10.14710/bioma, 17, 1, 41-54". (you can see that DOI in the meta tag citation_doi).

**Comment by bozana** [comment]
The first problem, an unresolved variable in a DOI, is only relevant for OJS 2.4.x -- such a DOI cannot be assigned in OJS 3.x.
Because a DOI does not have to be from Crossref and because the DOI public identifier plugin (and not the DOI import/registrations plugins) is responsible for the DOI display on the article page, I'll have to think how else we cold validate a DOI before displaying it...

Hmmm... I did not know that DOI cannot contain those characters... Hmmm... Thus, we just did some URL encoding and not syntax validation... Hmmm... This page https://support.crossref.org/hc/en-us/articles/214669823-Constructing-your-identifiers says that only these characters are allowed for the suffix: `"a-z", "A-Z", "0-9" and "-._;()/"`. However, according to this document http://www.doi.org/doi_handbook/2_Numbering.html#2.5.1 (that is also linked on the DataCite page https://datacite.org/dois.html) it is not so restrictive...
It would probably be best to restrict it -- in order to minimize the error possibility. Do you think we can safely restrict the DOIs to those characters `"a-z", "A-Z", "0-9" and "-._;()/"`?

**Comment by jalperin** [comment]
Seems OK to leave this unresolved for 2.x, since we're not really working on improvement to that line, but would be good to make sure that only DOIs that have been properly registered can be displayed in OJS 3. 

I would restrict DOIs for having spaces in them. In any case, it seems that for that journal there is something weird going on. I don't think they intended to have that string be the DOI. Could be worth investigating to see what field it is being pulled from.

**Comment by bozana** [comment]
For the first journal with %x in the DOIs: %x is the article public identifier. It seems that they started to use the article public identifiers in 2008, so that since then the articles have the DOIs with those public identifiers, but they didn't take care about the issues before 2008 and they probably get the DOIs automatically assigned. Either the DOIs should not be assigned to those older issues (in that case they can be removed/cleared and the issues excluded), or they would need to add all public identifiers for those articles (which is probably not going to happen), or to change the art of the DOI suffix in the plugin settings for a very short time + immediately export/register those articles anew and then immediately change the suffix back.

For the second journal: they probably use custom suffix pattern (%j, %v, %i, %p): "journal initials, Vol, No, pages". If the DOI restriction above is true, then neither space nor coma is allowed. Depending on what issues/articles are affected, their DOIs could be removed/cleared and then the suffix in plugin settings adapted (e.g. to %j_%v_%i_%p).

**Comment by AhemNason** [comment]
I think Juan's idea of only displaying registered DOIs would solve many issues. I've seen a lot of journals mint DOIs without going through the steps to register them. I'd suspect that anyone who wrote "bioma, 17, 1, 41-54" as a suffix has a limited idea as to what a DOI is supposed to do, and doesn't know that registration isn't necessarily automatic. A lot of folks assume they should be fully human readable. If we suppressed presentation of unregistered DOIs, it would largely prevent our resolution failures and make monthly resolution reports from Crossref redundant. But, ideally, the system would also self-report (maybe with notifications), errors in DOI submission. 

But, Bozana is right that this is dependant on the organization you're registering with. Our Crossref plugin gets feedback from Crossref, but as far as I know the Medra and Datacite plugins work differently. They're just export functions. 

I think there are a few things we can do with the DOI plugin documentation here. One would be to discourage users from creating vanity DOIs in the first place. Right now, the option to have a DOI suffix pattern represent whatever you'd like comes with zero warnings about potential problems. I also think our default pattern should be "journalAbbrev.articleID" to limit problems with unpopulated volume/issue values. 

Is there maybe a way on the article metadata page (which is the only place where someone could have written in a DOI like these) where we could intervene to let users know their suffix formatting doesn't match standards?

**Comment by NateWr** [comment]
Closing this as the original problem is solved. OJS does not automatically assign a DOI when a variable can not be substituted. Further discussion about when to show a DOI or not should take place in a new issue.
