### ISSUE TITLE
External feed plugin obliterates custom blocks when enabled

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3336]
When the External Feed plugin is enabled, the custom block manager's plugins disappear.

What appears to be happening is that the External Feed plugin causes the template manager to be initialized before all generic plugins have finished loading, causing the "blocks" category to be loaded before plugins registered against `PluginRegistry::loadCategory` have had a chance to register for notification of loading the block list.

**Comment by asmecher** [comment]
This looks like a broader issue, now that `_registerTemplateResource` has been introduced (see https://github.com/pkp/pkp-lib/issues/2872).

When a plugin calls `registerTemplateResource`, the TemplateManager gets initialized. This causes sidebar block plugins to be loaded, disrupting the expectation that all `generic` plugins would be loaded before all `block` plugins, which the custom block plugin used in order to inject its own blocks.

Because the custom block plugin is often broken as it currently stands, I'll make this a 3.1.1 must-fix.

**Comment by asmecher** [comment]
Should be resolved. Block plugins now register for their hook in order of sequence, rather than trusting the order of plugin loading to do it as expected.

**Comment by ctgraham** [comment]
@asmecher, I'm unclear on the resolution here.  Your comment "Block plugins now register for their hook in order of sequence, rather than trusting the order of plugin loading to do it as expected." makes it sound like something in core has changed to resolve the issue, but the working example of the Custom Block Manager remains with the "new" approach of registering the block plugins in the `register` method, rather than waiting for the `PluginRegistry::loadCategory` callback.  Does the "old" method remain usable or unusable?

**Comment by asmecher** [comment]
About...
> Block plugins now register for their hook in order of sequence, rather than trusting the order of plugin loading to do it as expected

...this is the commit the comment was referring to: https://github.com/pkp/pkp-lib/commit/158cefdc04206ddab3966c71dcd1afac5bcfd44d

Essentially it takes the normal hook priority and adds the sequence number to it, so the sequence number should reliably indicate the hook's priority, rather than the position in the array distinguishing potentially several registrants using the same sequence number.
