### ISSUE TITLE
Remove link to Reviewer Guidelines on Step 3

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3352]
The link to "Reviewer Guidelines" on Step 3: Download & Review is now redundant, as Step 2 provides that same information. Can this be removed to simplify the Step 3 interface?

**Comment by asmecher** [comment]
I couldn't find the commit that added this, but I remember specifically coding this to appear in both places at someone's request: IIRC on the first page so that reviewers know what they're committing to before they agree/decline, and during the review process so they can refer to it (in a pop-up) as they perform the review.

**Comment by NateWr** [comment]
Should this be closed or should we consider some changes here?

**Comment by asmecher** [comment]
Closing (until someone re-opens it).
