### ISSUE TITLE
[OJS 3.1.0-1] Question: Edit mail template for all journals

### ISSUE THREAD

**Issue by dennmuel** [pkp/pkp-lib#3380]
Hello everyone,

I was wondering how I could go about modifying an email template for all hosted journals at once. I would also like to use a variable that's not actually used in e-mails. I couldn't find any documentation or threads about this and doubt my understanding of the construction of mails, so I'd be grateful for any hints. :)

Our use case is as follows:
We would like to display the author submission checklist (`$submissionChecklist`) in the submission acknowledgement mail (`SUBMISSION_ACK`). With this mail beeing automatically saved in OJS and accessible in the backend we would have legally reliable evidence of an author agreeing to the checklist as it was at the time (in case it changes later on). Also we could give authors the chance to react to the sent checklist if they forgot or overread something. This could be important with regards to secondary publication rights etc.

Kind regards
Dennis

**Comment by bozana** [comment]
HI @dennmuel 

Your question is actually better suited for the support forum: https://forum.pkp.sfu.ca/. In GitHub Issues we just maintain the concrete bugs/features/issues that someone is/will be working on.

Which OJS version are you using?

You could eventually write a script or do some SQL queries to change the e-mail template for all your journals. Those default e-mail templates are in the DB table email_templates_default and email_templates_defaualt_data. When they are changed/edited they are copied to the DB tables email_templates and email_templates_data.

In order to add that additional variable, you would need to change the code and implement it, at the place when that e-mail is sent. You would need to assign that parameter to the e-mail, as for example here in OJS 3.1: https://github.com/pkp/ojs/blob/master/classes/submission/form/SubmissionSubmitStep4Form.inc.php#L87.

I will close this issue, because it is not the actual issue...

**Comment by dennmuel** [comment]
Hi @bozana thanks a lot for your quick reply and your tips. Good to know that I was on the right track enging up at the DB and the parameter assignment.
Also sorry for posting that here. I guess if I had worded it as a feature request for that mail template, I might have been in the right spot. =)
