### ISSUE TITLE
Problems scrolling PDF/HTML galleys in iOS 

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3381]
Some users have reported that they are having problems scrolling on iOS devices (iPad, iPhone).

https://forum.pkp.sfu.ca/t/ojs-3-1-html-galley-not-working-in-ios/38339

A suggested fix:

> I added the `style="overflow:visible;-webkit-overflow-scrolling:touch` in line 30 in Html Galleys display.tlp file.

![safari-iframe-scroll](https://user-images.githubusercontent.com/2306629/36202256-f394bc2c-117a-11e8-8872-d3b67eeb3d3c.png)

**Comment by ajnyga** [comment]
Hi, 

One of our users asked about this recently. Maybe the suggested fix could be added to htmlGalley?

**Comment by NateWr** [comment]
PR welcome. :)

**Comment by ajnyga** [comment]
Sure, the problem just seems to be bigger than the scrolling part.

Also anchor links that are usually used for reference linking in HTML articles are not working in iPad.

Suggestion: let's throw the whole iFrame out? @NateWr @asmecher

**Comment by asmecher** [comment]
@ajnyga, the reason we're currently using an iframe is so that we can provide some OJS-supplied navigational elements (e.g. the title bar and back link) while still serving valid third-party HTML, without having to blend the two documents, which I couldn't find a good way of doing. Any thoughts on how to get rid of the iframe while still preserving those goals? (The HTML that gets uploaded into OJS is often pretty wild and woolly, e.g. generated using Microsoft Word's "Save As".)

**Comment by ajnyga** [comment]
```
	function articleViewCallback($hookName, $args) {
		$request =& $args[0];
		$issue =& $args[1];
		$galley =& $args[2];
		$article =& $args[3];

		if ($galley && $galley->getFileType() == 'text/html') {
			$fileId = $galley->getFileId();
			if (!HookRegistry::call('HtmlArticleGalleyPlugin::articleDownload', array($article,  &$galley, &$fileId))) {
				
				$html = $this->_getHTMLContents($request, $galley);
				preg_match("/<body[^>]*>(.*?)<\/body>/is", $html, $matches);

				$returner = true;
				HookRegistry::call('HtmlArticleGalleyPlugin::articleDownloadFinished', array(&$returner));
				$templateMgr = TemplateManager::getManager($request);
				$templateMgr->assign(array(
					'issue' => $issue,
					'article' => $article,
					'html' => $matches[1],
				));
				$templateMgr->display($this->getTemplatePath() . 'display.tpl');
				return true;
			}
		}

		return false;
	}
```

**Comment by ajnyga** [comment]
I will add some code there that will check for js and css files and embed those to the galley view.

**Comment by asmecher** [comment]
Essentially you're talking about merging the contents of the two `head` elements together, right? I would think meta tags in the uploaded HTML might be important too. I started looking into a "standard" solution to doing this and got nowhere fast -- see e.g. https://stackoverflow.com/questions/19866929/merge-two-html-files-into-master-html-file. I consider the `iframe` to be a less-bad solution than any one of the ideas listed there, but I think what you're proposing might be a good optional approach too.

**Comment by asmecher** [comment]
@bozana could probably give good advice on the potential usage stats issue. My understanding is that this approach (as opposed to the iframe) would make the `view` function the "operative" one, as opposed to the `download` one. The stats would need to be watching for the right one.

**Comment by ajnyga** [comment]
I made the changes above into an independent plugin, see https://github.com/ajnyga/embedHtmlArticleGalley

The usage stats seem to work fine, if @bozana has time I would really like your opinion on the matter.

The code basically fetches the body section of the HTML file, runs it trough the filters you had in the original htmlGalley plugin and then embeds that HTML string to the page without an iframe.

It also fetches all links to stylesheets and adds them to the header. So there is a potential of conflicting css, but on the other hand you inherit most of the journal's style automatically and can basically add the css you need for the articles there. I did not add support for additional js scripts, but that would be easy. 

I am of course happy to do a pr to the actual htmlGalley plugin as well. Just needed a solution for a journal right now.

I will probably combine this code with the embedGalley code at some point so that it works with both HTML and XML files. My idea is to show both the HTML and HTML converted from XML on the article landing page if I can solve how to trigger the download stats with a simple "Read more" button that search engines can too access. This way you would end up with a very accessible HTML formatted article page.

**Comment by bozana** [comment]
I'll take a look how this works with usage stats...

**Comment by ajnyga** [comment]
Thanks @bozana, in my own testing I was seeing hits in the log files and they seemed valid, I think.

**Comment by NateWr** [comment]
I'm with Alec on the iframe being the best of a bunch of bad options for the core platform. Best because it is the most resilient. But I think there would be pretty wide interest in your plugin. Maybe we could get it into the plugin gallery soon?

Also, @mtub, would this help out your situation at all?

**Comment by ajnyga** [comment]
iframe would be good, if the problems with iPad would be solvable. I could not find any solution to the anchor links problem (some with javascript sure) and also the scrolling even with the suggested fix got broken when I clicked the links inside the document (or some other reason I do not know yet).

**Comment by bozana** [comment]
@ajnyga, I looked in the code and it seems to be correct -- I can also test it...

**Comment by ajnyga** [comment]
great thanks!

There is a small bug that shows utf-8 endocing wrong, but I am pushing a fix shortly.

**Comment by ajnyga** [comment]
there

**Comment by bozana** [comment]
@ajnyga, I've tested it and it worked for me as well. 
I encountered another 'problem': my html file did not have a head tag, so I got an error on this line: https://github.com/ajnyga/embedHtmlArticleGalley/blob/master/EmbedHtmlArticleGalleyPlugin.inc.php#L83, that the function getElementsByTagName was called on null. I do not know if that (and the other) HTML tags can be assumed to always be there, but maybe it would be better to check for their existence however?

**Comment by ajnyga** [comment]
Ok, thanks.

I will add some checks. If neither the body tag or the head tag exist, show the whole file and/or if the head tag does not exist skip the part of adding the scripts.

**Comment by ajnyga** [comment]
So it should work now. If no body tag exists, it will just use the whole document. If body does exist, it will also check for the head and possible stylesheets.

**Comment by asmecher** [comment]
(About applying OJS styling to HTML galleys: there's a quick snippet of JS in the health sciences theme [and probably others] that adds some basic CSS when none is specified. https://github.com/pkp/healthSciences/blob/master/templates/plugins/generic/htmlArticleGalley/display.tpl#L36..L60)

**Comment by ajnyga** [comment]
thanks, I was thinking of solving that in the themeplugin file itself. 

In general having a way of adding journal wide artwork files to HTML and XML galleys could be a thing to consider.

**Comment by NateWr** [comment]
> In general having a way of adding journal wide artwork files to HTML and XML galleys could be a thing to consider.

If it's just a general file like a logo or something, they can use the Publisher Library. If it's something more technical (like icons or CSS), I'd prefer leaving it to the theme.

**Comment by NateWr** [comment]
The suggested fix in the initial report was confirmed to work on a client site. I've flagged this for OJS 3.1.2-1 since it should be a quick fix.

**Comment by ajnyga** [comment]
Do you mean that the fix (`overflow:visible;-webkit-overflow-scrolling:touch`) helps for both the _scrolling issue_ and the _linking issue_? I tested that fairly extensively back then and the fix suggested there did not help with the latter. Unless they have now changed something in the iOS browser of course.

**Comment by NateWr** [comment]
Yes, just the scrolling issue. I'd recommend opening a new issue if you want to work on the linking problem.

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ojs/pull/2349

(tests running)

**Comment by NateWr** [comment]
Merged to `master` and `stable`. :+1:
