### ISSUE TITLE
[OJS] Deleting submission covers leads to faulty API response

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/pkp-lib#3419]
There's a problem with the process how submission covers are deleted (tested on OJS 3.1).

Say you have a submission that has a cover attached. From the API you will get the response:

```json
{
    // [...],
    "coverImageAltText": {
        "en_US": "Test 123"
    },
    "coverImageUrl": {
        "en_US": "http://beta-meta-journal.local/public/journals/3/article_4571_cover_en_US.png"
    },
    // [...],
}
```

When you delete the submission cover from the _Submission and Publication Metadata_ panel the rows with the _setting_name_ _coverImage_ and _coverImageAltText_ don't get removed. The rows both get the _setting_value_ _empty_string_. This seems to be the reason for the API response:

```json
{
    // [...],
    "coverImageAltText": {
        "en_US": ""
    },
    "coverImageUrl": {
        "en_US": "http://beta-meta-journal.local/public/journals/3/"
    },
    // [...],
}
```

When deleting an submission cover I would expect the _coverImageAltText_ and _coverImageUrl_ attributes to be gone again.

Is there a reason why the _setting_value_ of those rows get set to _empty_string_ instead of removing the rows?

**Comment by kaschioudi** [comment]
Whether non existent values should be null or non existant is an eternal debate within web service developers. 

Personally I prefer returning null or empty value if a field is unset because not only it keeps the shape of the response more predictable, it also benefit clients (no need to check for the existence of a field before using it and it also easy to take a response object make some changes and send it back to the server for updates).

Regarding `coverImageUrl`, we could modify the code to return a empty value instead of sending the url prefix.

@asmecher : what do you think?

**Comment by asmecher** [comment]
I don't have a preference for empty strings vs. nulls, but the `coverImageUrl` definitely shouldn't be returning what it is. Either an empty string or no `coverImageUrl` at all would be fine with me.

**Comment by NateWr** [comment]
This is no longer the case in 3.3.0-8.
