### ISSUE TITLE
Crossref issue-level DOIs generate repeated errors

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#3428]
When a user submits a full-issue to Crossref via the plugin and they use both issue-level and article-level DOIs, the issue-level DOI will be submitted to Crossref repeatedly with the same timestamp. This is because the metadata for each article includes issue metadata as well. 

The error looks like this: 

```
message-types	
0	"submission-version-older-than-last"
message	"Record not processed because submitted version: 1519421112 is less or equal to previously submitted version (DOI match)"
related-doi	"10.29012/jpc.v7i3"
status	"failure"
```

Crossref throws up errors if update submissions have the same (or older) timestamp than first submitted, so the submission JSON result from Crossref will show all but one issue-level submission as an error. Since these JSON results are already sort of inscrutable to users, this makes it harder to see what the real issues are _and_ if you submit via the plugin, Crossref will return an error even though all the DOIs are successful.

**Comment by bozana** [comment]
I suppose this then always happens when two or more articles of the same issue are exported/registered at the same time. In this case only one XML file with one timestamp is generated and every article representation in that XML file contains journal_issue element with its DOI element. I wonder why is this happening now for the first time and not earlier, because this was always the case :-O Have maybe Crossref changed something? I.e. are we 100% sure that that DOI was not registered earlier and differently i.e. using another timestamp format, e.g. from within another system or manually?
@AhemNason, just to be 100% sure: Is this is the very first attempt to register that issue DOI? -- There are those cases when a DOI was registered within another system or manually using different timestamp format and when Crossref returns such an error message. Are we 100% sure that here this is not the case?
Could you maybe send me the result from this request: `https://api.crossref.org/deposits?filter=doi:10.29012/jpc.v7i3`?

**Comment by AhemNason** [comment]
Issue no longer relevant since 3.1.2 release.
