### ISSUE TITLE
Move Gitbooks to PKP website so they can be indexed

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#3464]
-Subdomain has been created on PKP server - docs.pkp.sfu.ca.  -Write script so that books get downloaded every day.
-Create index page or website page that will list these documents.  Have subdirectory for each guide.
-Make sure it is all indexed

**Comment by NateWr** [comment]
Can I mockup the index page? :) Are we planning to use Jekyll or some other static site generator? Does anyone mind if I whack the Community Priority and Dev Housekeeping tags on this?

**Comment by jmacgreg** [comment]
Whack away! And right now the way we're doing this is generating the gitbook docs at docs.pkp.sfu.ca, but redirecting the web root to https://pkp.sfu.ca/pkp-software-documentation/ for the "TOC". Open to suggestions for doing this better (I was actually futzing around with using OMP to manage a documentation catalogue, but very quickly hit some problem areas).

**Comment by jmacgreg** [comment]
I'd also like to use a better/different theme for the documentation - right now it's just the gitbook standard. See eg. http://docs.pkp.sfu.ca/ojs3/. We can do this better.

**Comment by NateWr** [comment]
> right now the way we're doing this is generating the gitbook docs at docs.pkp.sfu.ca, but redirecting the web root to https://pkp.sfu.ca/pkp-software-documentation/ for the "TOC".

Is it ok if the web root is a HTML/markdown file under version control and one of our tech people has to commit to modify it? This would only be the root/hub. The docs would remain GitBooks editable by non-technical users....

**Comment by jmacgreg** [comment]
Yep, totally fine!

**Comment by NateWr** [comment]
Some quick mockups on what the hub page could look like using a simple card-based approach. The cards can be mixed and matched as needed so that we don't have to maintain too much in terms of layout. Each app is just a card dump of resources. 

Don't pay too much attention to styles here (typography, colors). We'll probably adjust this to match whatever PKP's branding is at the time. At this stage, I'm just interested in whether you think this overall approach to site layout and information structure will work for your needs. You'd obviously be figuring out the exact content yourself -- but do you see in here the parts that you'll need to put that together?

![mockup](https://user-images.githubusercontent.com/2306629/38245617-c5d79804-3736-11e8-8120-0c0404857a14.png)

And on large screens it can spread out to a three-column layout:

![mockup-3-col](https://user-images.githubusercontent.com/2306629/38245625-d039648a-3736-11e8-9179-518ec5fb2a8a.png)

The cards are pretty easy to expand with components as we'd like. So we can provide more detail on key documents:

![mockup-toc](https://user-images.githubusercontent.com/2306629/38245640-e4f216ba-3736-11e8-94a0-013d12b0a6f7.png)

Or bring attention to a specific card:

![mockup-attention](https://user-images.githubusercontent.com/2306629/38245646-ea20543a-3736-11e8-8fce-6b17e5d8a47c.png)

Or group related resources in a single card:

![mockup-group](https://user-images.githubusercontent.com/2306629/38245656-f0fb8446-3736-11e8-920a-26b70635b880.png)

I'm going to play around with Jekyll now to see how we can build this automatically from a simple `.yml` file, like our API docs, so it's easier for non-technical team members to contribute and update things.

**Comment by AhemNason** [comment]
Just a comment, Nate, that I think this looks excellent.

**Comment by jmacgreg** [comment]
Likewise Nate, this looks great! @AhemNason and I reviewed briefly, and will be following up with a few more questions/comments.

**Comment by ajnyga** [comment]
These are beautiful "quick mockups"! I think the official name should be "Help or something".

**Comment by mtub** [comment]
Really nice :+1:

**Comment by NateWr** [comment]
Closing because I think all the gitbooks have been migrated.
