### ISSUE TITLE
Provide reviewer's with a certificate to credit their work

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#3501]
As you know, a challenge for little-medium journals is how to keep a good DB of article's reviewers.

At the same time, in my country, looks like reviewing is starting to be taken in consideration as a merit for our academics, so journals started to ask us to extract a list of reviewers (once or twice a year) to elaborate certificates. Right now our method is rough... we just created a "view" (directly in the DB) so when the journals ask, we send them a csv that they can open with excel and combine to print certificates.

Obviously, it's not an essential requirement, but probably would be a nice addition to OJS if reviewers can print certificates from their own profile whenever they like and get a paper to credit the work they are doing... or editor can send certificates to a printer from the administration menu.

Please, take this as a "feature request", to be deeper though as a general feature and may be included in the "[Reviewer Selection and Management](https://github.com/pkp/pkp-lib/projects/7#card-7147952)" project as something to Do.

**Comment by asmecher** [comment]
Alternately, how about a report plugin? These are fairly quick to write, and generally just map a SQL call (or set of calls to DAOs if the SQL already exists there) into a CSV.

**Comment by NateWr** [comment]
I _suspect_ that every journal will have it's own inclusion criteria for deciding which reviewers actually get a certificate. Since users can self-enrol as reviewers, it might not be a great idea to just provide the certificates without some minimum criteria (eg - must have reviewed X articles in last X days).

**Comment by marcbria** [comment]
@NateWr, in all my journals there is no criteria... they make a certificate for every reviewer that makes a review, even if the article is not published.

@asmecher I will take a second look to the report tool, but I think we decided to go with a mysql view because some info was missed.

**Comment by diegoabadan** [comment]
> @NateWr, in all my journals there is no criteria... they make a certificate for every reviewer that makes a review, even if the article is not published.

In Brazil this scenario is also common.

**Comment by NateWr** [comment]
> @NateWr, in all my journals there is no criteria... they make a certificate for every reviewer that makes a review, even if the article is not published.

Even this represents a certain criteria, too, since in some journals a user can self-register as a reviewer, and be considered as such, even if they've never been assigned a review.

And then we define this minimum criteria we will get a request for generating the certificates for reviewers who have never reviewed, for those who have historically done so but whose reviews aren't in the system.

And then we'd also get requests for customizing the certificate. Making it available in PDF, where we'll struggle with language issues. This feature has a lot of potential variations, so I'd be hesitant to add it to the core application. 

But a simple version of this could be done as a plugin created through sponsored development, or if a third-party wants to take on the development themselves. I'm sure we'd provide guidance on that if someone wanted to take that on.

(Also, I'm not the final word on what goes into the core application, so you can keep making arguments and we might change direction.)

**Comment by fgnievinski** [comment]
May I suggest using the exisiting "REVIEW ACK" email template:

> {$reviewerName}:
> 
> Thank you for completing the review of the submission, "{$articleTitle}," for Journal X. We appreciate your contribution to the quality of the work that we publish.
> 
> {$editorialContactSignature}
> 

I think it's reasonable to tell reviewers the email messages will serve as official certification of their review work.

**Comment by leanlibutti** [comment]
Hello, I am interested in participating in the development of a plugin to add this function if no one has been contacted for this task.

Regards,
Leandro Libutti

**Comment by NateWr** [comment]
@leanlibutti that sounds great! We don't have any plans to schedule this work at this time, and a community plugin would be a welcome addition. You may have already found what you need, but you can find all of our [developer documentation](https://docs.pkp.sfu.ca/dev/) as well as the [plugin guide](https://docs.pkp.sfu.ca/dev/plugin-guide/en/)

Feel free to ask questions here or on our [community forum](https://forum.pkp.sfu.ca/).

**Comment by marcbria** [comment]
Hi @NateWr.
I'm sorting/closing the issues I created. Do you mind to tag this a "Feature Request"?

**Comment by NateWr** [comment]
Closing this as outdated. If you are interested in this feature, please vote on the [proposal on the forum](https://forum.pkp.sfu.ca/t/automatic-certificate-for-reviewers-and-authors/74138) and add your requirements there.
