### ISSUE TITLE
[OJS] upgrade - missing reviewer files from the grid

### ISSUE THREAD

**Issue by mczirfusz** [pkp/pkp-lib#3502]
We recently upgraded from OJS 2.3.6 to 3.1.0-1. 

Some files sent by the reviewers are missing from the grid, but are found in the file system in the correct place. These involve XXXX-13-XXXX-Y-5-XXXXXXXX type files in which Y is higher than 1. That means, if a reviewer attached more than one file, only the one attached first appears in the grid.

also mentioning #2173 - perhaps related to point 2 referenced there.

**Comment by ajnyga** [comment]
See https://github.com/pkp/pkp-lib/issues/2173#issuecomment-285711524, does that sound familiar?

**Comment by mczirfusz** [comment]
@ajnyga Yes, thank you very much, I think this is the same. As I understand from the discussion it should not have shown up as a problem in our upgrade (2.3.6 > 2.4.8 > 3.1.0-1), because #2173 was already closed when 3.1 was released. Am I right?

Shall I close this and let reopen #2173?

**Comment by ajnyga** [comment]
@bozana knows this best, so tagging her here.
In our case I ended up fixing things with home made post-upgrade scripts, because the upgrade boat had already sailed. So I do not really have thorough info on what happens with 2.4.8 to 3.1.0.1 upgrades. 

If I remember correctly the problem was that in OJS2 you could not upload separate reviewer files. I mean it looked like you could, but also in OJS2 that meant that you were uploading revisions of the same file. I bet that 90% of reviewers doing that did not realize it. So if a reviewer has uploaded two files and thinks that these are separate files, then I am not sure you can fix this in the upgrade. Because there are probably also users who thought they were uploading revisions of the same file. Not sure if you follow?

**Comment by mczirfusz** [comment]
Thank you, @ajnyga. Yes, I understand what you are writing, and to be honest I also thought that we are uploading two files in OJS2, not one file and a revision. 

I think I will leave our current system as it is. We had only 3 articles in the current workflow which were affected, so I manually uploaded files not visible in the grid as a duplicate. As for the archives, in the rare case we need them, we can always browse the file system and access the files in question from there.

**Comment by bozana** [comment]
Hmmm... Just to be sure what's the problem here -- I've already forgotten all the older cases :-P -- @mczirfusz, are all files there (in the DB table submission_files, for example, and in the files folder)? I.e. is it so that you just do not see all revisions in the GUI?

**Comment by mczirfusz** [comment]
Hi @bozana, I give you one example. The review was done in our old 2.3.6 system, the reviewer uploaded three files (OJS understood this one file and its two revisions). After upgrading to 3.1.0-1, only the firstly attached file is visible in the GUI.

_DB: all 3 rows exist in submission_files:_
`|5756|1|NULL|NULL|2514|application/msword|42496|lektori_urlap_csatolando_ojs.doc|5|0|2013-02-23 16:00:43|2013-02-23 16:00:43|153|13|NULL|NULL|19|1|517
|5756|2|NULL|NULL|2514|application/pdf|82610|lektori_urlap_csatolando_ojs.pdf|5|0|2013-02-23 16:01:02|2013-02-23 16:01:02|153|13|NULL|NULL|19|1|517
|5756|3|NULL|NULL|2514|application/pdf|1393949|2514-5667-2-RV-korr.pdf|5|0|2013-02-23 16:01:37|2013-02-23 16:01:37|153|13|NULL|NULL|19|1|517`

_File system: all 3 files are there:_ 
folder: `/submission/review/attachment/`
![image](https://user-images.githubusercontent.com/16511307/37722963-7c7e25e6-2d2d-11e8-969c-3d74592f3e01.png)


_GUI: only file 5756-1 is visible:_
![image](https://user-images.githubusercontent.com/16511307/37722075-7f96bee8-2d2b-11e8-9c69-3a9986e73dbe.png)

Can you compare this behaviour with this commit? https://github.com/pkp/ojs/pull/1292/commits/32943b7030ca3bd7b1cfc17be377b218f01493dc#diff-5757dc25f7f977b9832f511fa872e27e 

Anyway, it would be more convenient to have all files visible for editors in the GUI, independent from whether the users uploaded those as revisions or as different files.

**Comment by ajnyga** [comment]
If you click the blue triangle and "edit" (or something similar) can you see links to the revisions there?

**Comment by mczirfusz** [comment]
Clicking on More Information there are no items in the History tab and no Notes to display.

**Comment by ajnyga** [comment]
Ok, because I think that the history tab is the place where there should be links to old revisions of the file. I think I manually changed these cases to separate files (this is slowly coming back to me, we upgraded to OJS3 in January 2017).

**Comment by bozana** [comment]
I think everything is correct, just that that file grid only shows the first revision, instead of last revision, as it is in another file grids.
That the older revisions are not easy accessible via the GUI is a problem for all files grid and considered here: https://github.com/pkp/pkp-lib/issues/2130

**Comment by bozana** [comment]
Hmmm... In the normal case the reviewer files cannot be revised in OJS 3... :-P

**Comment by bozana** [comment]
Hmmm... So actually, those reviewer files revisions should be migrated as separate files, with different file ID.

**Comment by ajnyga** [comment]
See Alec's comment from 2016: https://github.com/pkp/pkp-lib/issues/2097#issuecomment-268297097

**Comment by bozana** [comment]
@asmecher, I need you help/decision: In OJS 2.4.x the reviewer could upload several files, that were saved as different revisions of the same file. Those were migrated as such to OJS 3.1. In OJS 3.1 however the reviewer cannot upload a revision of a file -- every new upload will be saved as a new file.
Is it enough to only display the latest reviewer file revision from OJS 2.4.x or do you think we should migrate so that they are new files, with new file Id? 
I would prefer the first solution :-)

**Comment by ajnyga** [comment]
Ah, ok, that is a 3.1. thing I suppose? In that case I think that the upgrade should definitely create these as separate files and you are of course right that it is a different scenario then!

**Comment by ajnyga** [comment]
I honestly think that both in author revisions and reviewer files the users did not know they were uploading revisions in OJS2. The UI simply did not show this in any way. The only place you could see this from was the mystical filename. So I would opt for converting at least these files to separate files.

But if you think that there are several cases where they are actually intended as revisions, then your solution is probably the best one. Meaning that upgrade them as revisions although they are not supported anymore. I guess this is the safer solution.

I am actually interested in these things again, because I have four larger OJS2 installations I have promised to upgrade :)

**Comment by bozana** [comment]
@ajnyga, do you maybe have a OJS 3.0.2 (test) installation? Can a reviewer upload a revision of a reviewer file there?  -- because you said it's a 3.1 thing...

**Comment by bozana** [comment]
In the meantime I think I will then just treat the reviewer files revisions all the other revisions for now, and once the issue https://github.com/pkp/pkp-lib/issues/2130 is solved, everything will be fine...  :-)
Thanks!

**Comment by ajnyga** [comment]
> @ajnyga, do you maybe have a OJS 3.0.2 (test) installation? Can a reviewer upload a revision of a reviewer file there? -- because you said it's a 3.1 thing...

No, I am confusing the reviewer files and author revision files issues here. The review files case is just like you thought also in 3.0.2 => you can not upload revisions.

**Comment by bozana** [comment]
I will then close this issue now -- The most recent reviewer file revision will be displayed with this change: https://github.com/pkp/pkp-lib/issues/3510, and the issue https://github.com/pkp/pkp-lib/issues/2130 should then provide an easier access to the earlier revisions...
