### ISSUE TITLE
Timestamps in Crossref plugin do not match schema requirements

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#3515]
Our current timestamps for Crossref are 32bit, 12 characters. According to the Crossref schema document, however, the current standard is 64 bit double (19 characters). 

https://data.crossref.org/reports/help/schema_doc/4.3.0/4_3_0.html#timestamp 

Their validation is dependant on the size of the number, so a timestamp from 2013 written in 64 bit double will always be "newer" than a 2018 deposit written in 32 bit. 

This isn't a dealbreaker internally if a journal is only with OJS, but if we import DOIs from another system or publisher that was depositing to spec, we can't update DOIs.

**Comment by ctgraham** [comment]
The spec is deliberately ambiguous and explicitly varies across publishers / registrars:
>  the format need not follow any public standard and therefore the publisher can determine the internal format.
It is reasonable to switch our standard to a microtime rather than a unix time, but this doesn't guarantee cross-compatibility.  Crossref can reset the timestamps after a publisher/registrar move, if necessary.  This is the only way to guarantee interoperability.

**Comment by AhemNason** [comment]
Closing for now, there are bigger fish!
