### ISSUE TITLE
Section settings heading "Indexing" is not clear to end-users

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3535]
This should be changed to "Options" or "Settings", or a further description should be provided.

![selection_103](https://user-images.githubusercontent.com/2306629/38028084-b1b906b6-3289-11e8-8844-a470ee9502a7.png)

**Comment by ajnyga** [comment]
Maybe check also what the options actually do at the moment. Looking especially at the "will not be peer-reviewed". Does that affect something? But also the other options there, are we sure that they actually work because I think that the abstract option did not work (maybe it does now that you can add the word limit as well...)

**Comment by jamshidhashimi** [comment]
@NateWr how about changing it to: `Section Options` to be aligned with the upper field: `Section Policy` in having the word `Section`. I also assume `Setting` is more like high level configuration, where `Option` comes under, so thought we can go with the word `Options`.

**Comment by NateWr** [comment]
:+1: I like `Section Options`.

**Comment by jamshidhashimi** [comment]
Thanks @NateWr. 

PR:
https://github.com/pkp/pkp-lib/pull/4476

**Comment by jamshidhashimi** [comment]
PR:

https://github.com/pkp/pkp-lib/pull/4476
https://github.com/pkp/ojs/pull/2287

Please review @asmecher. Thanks.

**Comment by asmecher** [comment]
Thanks, @jamshidhashimi! Sorry to give you one more multi-repository tweak, but since this is now OJS-specific language ("section") rather than something that might also be used in OMP, and since it's never used in the OMP codebase, I'd suggest moving the locale key into the OJS locale files entirely.

**Comment by jamshidhashimi** [comment]
Hi @asmecher. Done. Please review. 

PR:

#4476
[pkp/ojs#2287](https://github.com/pkp/ojs/pull/2287)

**Comment by asmecher** [comment]
Merged both -- thanks, @jamshidhashimi!
