### ISSUE TITLE
Add privacy statement to user registration page

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3576]
In OJS 3, the privacy statement is currently only included on the first page of article submission. It should also be included on any user registration page. (I think it was so in OJS 2.x, possibly just an oversight here.)

**Comment by ajnyga** [comment]
Are we going to have a site wide privacy statement or separate privacy statements for each journal or both? 

If we will have a journal privacy statement, what happens when user registers on site level to several journals at once? Or when a user joins a new journal later (gains for example author role in a new journal)? Related to https://github.com/pkp/pkp-lib/issues/2297#issuecomment-381127600

**Comment by jmacgreg** [comment]
I think "both", but at least ensure that things are available at the journal level first.

**Comment by NateWr** [comment]
This issue was address in a PR merged with #3575.
