### ISSUE TITLE
Auto-prune user accounts after a period of inactivity

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3577]
Auto-prune inactive user accounts after a period of inactivity. The journal should be able to specify the period of inactivity, and the account into which the user should be merged. For example: if the journal enables this option, and sets the period of inactivity to 1 year, any user that hasn't logged in for 1 year should be merged into an admin account. 

This should be an option for journals, set by default to "off", and similar to the auto-pruning of registered but not verified accounts (see "require_validation" and "validation_timeout" in config.inc.php).

**Comment by asmecher** [comment]
I can think of other useful conditions that would need to be met: they should have no submissions assigned, no discussions/notes, no review assignments, etc. -- basically no participation anywhere in the workflow.

Is the goal to help clean up spam registrations? Are we getting spam registrations en masse with the current releases of OJS, or is this an archaeological dig?

I'd be tempted to put something as drastic as mass user deletion in a plugin or external tool, rather than shipping it with the codebase.

**Comment by alexxxmendonca** [comment]
I agree that this is a good idea, but I also agree with Alec that it makes sense only if the user has no historical data. Because if they do have some historical data, that data would be added to the Admin's own historical data.

So in my view it would have be something like an auto-prune for completely inactive accounts.

**Comment by NateWr** [comment]
Closing this for lack of interest.
