### ISSUE TITLE
[OJS3.1] Supervisors' issues with the review process

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#3604]
The following concerns were highlighted by the supervising staff of our
journal. They have to make sure that no submissions get lost or delayed
due to ambiguous communication between reviewers, authors and section
editors. They have to be able to track down inactivity of authors,
reviewers and section editors. The current submission list does not
support this very well.

**Related Issues:**  I found similar suggestions scattered over multiple
existing issues: #2612, #1662, #3397. I add this new issue to clarify
the motivation and our own requirements.

For submissions under REVIEW it is not clear who has to move next. While
special notification like "Waiting for reviewers to be assigned" are
visible to some participants, the supervising staff does not get this
information.

Ideally, the stage indicator would be extended to include the role of
the person who causes the delay. A submission where revisions were
requested would be at stage "REVIEW: with author". A submission where
revisions and reviews are complete would be "REVIEW: awaiting
moderation". With pending reviews it would be "REVIEW: with referees".

Further, there is no indicator for inactivity (except deadlines for
reviews). The supervisors could make good use of an extra field
indicating time and action of the last activity similar to "Last
activity: 2018-04-18, revisions added by author". For prioritizing work,
it would be most useful if the submission list could be filtered and
*sorted* by the time of the last activity.

A major but desirable change to the workflow would be the separation of
the review stage into two sub-stages "Awaiting Revisions" and "Under
Review". Right now, the review stage is open for three different kinds
of participants who can interact with each other asynchronously. Authors
can upload revisions while reviews are pending. Section editors can
start new reviews while the author is not yet finished with uploading
revised material. This leads to ambiguities about who is responsible for
the delay and the process becomes stale.
We claim that serializing the process and restricting access to one role
at a time would be an effective countermeasure. By requesting revisions,
a section editor would send the submission back to "the author's desk".
After including some changes, the author explicitly sends the submission back to
the section editor and thereby loses its capability of adding material.
The supervisors would know at any time, who they are waiting for and who
needs to be pushed.

**Comment by NateWr** [comment]
Hi @pkel,

Let's discuss a few things here and then I might move a summary into the relevant issues.

> For submissions under REVIEW it is not clear who has to move next. While
special notification like "Waiting for reviewers to be assigned" are
visible to some participants, the supervising staff does not get this
information.

I just tested this out and the editorial message did appear for a Journal Manager. Here's what I did:

- Moved a submission into review stage with no assigned reviewers. Only editor assigned was a Section Editor: Stephanie Bardo.
- I logged in as a Journal Manager, went to All Active submissions, and found the submission.
- The "Waiting for reviewers to be assigned" appeared for me as a Journal Manager.

Is this not the scenario you were describing?

> Ideally, the stage indicator would be extended to include the role of
the person who causes the delay. A submission where revisions were
requested would be at stage "REVIEW: with author". A submission where
revisions and reviews are complete would be "REVIEW: awaiting
moderation". With pending reviews it would be "REVIEW: with referees".

Whenever we can reliably detect someone responsible for the next step, we indicate this state with the alert messages which appear under each submission. I believe all of the states that you mention are represented, with the caveat that some of them, like "with referees" is indicated by the lack of a notice as long as none of these are overdue.

> The supervisors could make good use of an extra field
indicating time and action of the last activity similar to "Last
activity: 2018-04-18, revisions added by author".

I do think we'll eventually implement some kind of task-oriented feature, with due dates, that is like a generic review assignment. This should help track these kinds of problems, but I don't think we're going to get there very soon. Adding a line to the expanded submission details for the last activity is a nice idea, and would dovetail with some work we want to do to improve the presence and utility of the activity logs.

> For prioritizing work,
it would be most useful if the submission list could be filtered and
sorted by the time of the last activity.

Sorting is probably lower on our priority list, but there's no reason we don't want it.

> We claim that serializing the process and restricting access to one role
at a time would be an effective countermeasure.

A forced procedure like this would probably work for some, maybe most, of our users. But a large number would be negatively impacted by an approach like this, which is why we've settled on a more flexible workflow.

That said, we are particularly aware of the problem around authors uploading revisions, without a clear way to indicate "Ok, now I'm all done". You can see some of the discussions in this and related issues: https://github.com/pkp/pkp-lib/issues/3278. My take is that eventually we will have more of a wizard-like approach to submitting revisions, where the author says at the end "yes, this is everything" or "no, i'll upload more later".

**Comment by pkel** [comment]
Thanks for your comments,

I just checked again from my own account and indeed got the alert messages you described. I cannot recall what lead us to the conclusion that we have to complain about missing stage highlighting.

It remains the wish for a last activity time stamp. Including it in the submission list would be a good start. Filtering on this time stamp would allow to identify long time idling submissions and bring them back on track systematically. 

Regarding sorting, the current approach (fixed, descending submission id) tends to hide the old submissions behind the paging feature. But old submissions (or the ones with a long period of inactivity) should be handled with high priority. Adding some options on the sorting of the submission list would be very useful: 

- ascending / descending
- submission time / last activity

A supervisor who has dozens of submissions assigned could opt for sorting by activity. Depending on the order, he would be presented with a list of recent changes or a list of inactive submissions.

**Comment by NateWr** [comment]
I've added the request for filtering by "Last activity more than X days ago" to https://github.com/pkp/pkp-lib/issues/2612. When that's implemented, we'll add an indication of X to the submission item and sort by the highest X value first. 

That should allow editors to use the filtering to identify stalled submissions (for example: filter by last activity more than 1 day ago, the longest idle submissions will appear first).

Does that sound like it will cover your needs? If so, I'll close this in favor of that issue.
