### ISSUE TITLE
Investigate SQL Server support for OJS

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3617]
Contributed PRs:
- https://github.com/pkp/ojs/pull/1919
- https://github.com/pkp/pkp-lib/pull/3603

**Comment by asmecher** [comment]
Thanks, @nibou230, I'm just looking over these again (and have posted some comments) and have a few thoughts about how to proceed next.

I think there are roughly 3 different kinds of changes included in the PRs:
- Code cleanup that's unrelated to SQL Server, e.g. to resolve warnings
- Code that standardizes/improves OJS without adding anything SQL Server-specific, e.g. moving ADODB to a Composer dependency, using ADODB's `$sysDate instead of `CURRENT_DATE`, etc.
- Code that specifically adds support for SQL Server.

The last category is the most complicated, and there's still quite a lot there that I'd like to dive into in more detail before merging. However, the PRs are quite large and I suspect you're probably already getting tired of rebasing them. Therefore, how about we try to get the first two categories merged in first so that we can focus on the stuff that needs the most effort?

This would be easiest to do if the commit history in your PRs kept things separated (that's good practice) but it looks like it's fairly mashed together at this point. I see two options for going ahead:

1. I can try to pick through the PRs for pieces that can applied to the software and merge them myself, or
2. You can try to separate the PR into commits that I could cherry-pick in.

Do you have a preference?

Thanks again for all this work!

**Comment by nibou230** [comment]
Thanks for the time spent reviewing all the code, @asmecher.

I'm still not really used to the advanced functions of git (for instance the rebase one). I will keep commiting the stuff the way I do now to complete this PR. It will certainly be easier to get used to the advanced functions while working on a new and fresh smaller PR.

We have a lot of completed work here that can be eventually shared with you.

Honnestly you can pick whatever you are confident within the changes. It is indeed mashed together at this point. We will keep the next PRs more focus on one change instead of going all in. This is, as we can call it, a special case.

If there is anything you wonder about the modifications, I will be happy to help you understand our work.

Thanks!

**Comment by asmecher** [comment]
I believe this work did not move ahead, though it did contribute significantly to the replacement of ADODB with the Illuminate/Database toolset and Migrations, etc. Thanks for all the detail on this, @nibou230, it contributed to some major improvements!
