### ISSUE TITLE
[OJS 3] Author cannot upload revised article as a new version

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#3653]
Bonjour, 

At the evaluation stage, an author who have been asked to revise his/her article cannot upload the revised version as a new version of the original article. He/she gets a permission role error (see print screen). However, even if he/she try to upload the file as a new one, OJS is detecting it as a file similar to the initial submission and select it as a new version (see print screen below).

Print screens (from the OJS testdrive, we are using code from the master branch and get the same issues)
![revision_upload_new_file](https://user-images.githubusercontent.com/19291880/39437642-722550ea-4c6f-11e8-823b-5347bb581f1a.PNG)
![revision_submission_screen_author](https://user-images.githubusercontent.com/19291880/39437644-7242ec4a-4c6f-11e8-98ae-25480257735f.PNG)
![revision_upload_new_version](https://user-images.githubusercontent.com/19291880/39437645-725f0538-4c6f-11e8-9d10-0c2bda0b6dc9.PNG)

I would suggest that no matter what the author chooses (new version or new file), OJS must accept the file.

Thank you very much.
Pierre

**Comment by pilasou** [comment]
We are working with OJS master branch. The print screen I sent are from OJS Demo Testdrive **https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/journal**

**Comment by bozana** [comment]
hmmm... I did some things with revisions short time ago and cannot remember having those problems... hmmm... 
Do you have the same problem in your local OJS master branch?
I'll test it i.e. take a look...

**Comment by pilasou** [comment]
We do have the exact same problem on our local OJS master branch (we last sync last wednesday).

**Comment by bozana** [comment]
Hmmm.... I think I figured it out: The author gets a list of the files from that review round that he/she can chose to revise. There, also the files from the `Review Files` grid are provided. Then because of this rule https://github.com/pkp/pkp-lib/issues/3474 they are actually not allowed to revised it. Also, the authors are actually not allowed to access/download the files from the `Review Files` grid. 
Thus, either the files from the `Review Files` grid should be available for authors, or they should not be provided for the revision. @asmecher, what is the correct solution? THANKS!!!

**Comment by asmecher** [comment]
@bozana, I think those files shouldn't be listed in the drop-down (or part of the revision detection).

**Comment by bozana** [comment]
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3680
ojs master: https://github.com/pkp/ojs/pull/1962 (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you take a look at the PR above?
I removed this part of the code: https://github.com/pkp/pkp-lib/blob/master/controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php#L476-L478, because it is already handled here: https://github.com/pkp/pkp-lib/blob/master/controllers/wizard/fileUpload/form/PKPSubmissionFilesUploadBaseForm.inc.php#L157-L159. Correct?
Actually, I think we can then also remove the application specific function getSubmissionFiles: https://github.com/pkp/ojs/blob/master/controllers/wizard/fileUpload/form/SubmissionFilesUploadBaseForm.inc.php#L45 and https://github.com/pkp/omp/blob/master/controllers/wizard/fileUpload/form/SubmissionFilesUploadBaseForm.inc.php#L44. And thus maybe both application specific classes. Or?
What do you think?
Hmmm...

**Comment by asmecher** [comment]
> I removed this part of the code: (...), because it is already handled here: (...). Correct?

Phew -- those are both 4-5 year old sections of code. But yes, that looks right.

> Actually, I think we can then also remove the application specific function getSubmissionFiles: (...) and (...). And thus maybe both application specific classes. Or?

Yes! Yes! Yes!

This is a pretty hairy aspect of the code -- thanks for digging into it.
