### ISSUE TITLE
error uploading revision

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#3695]
Using the OJS 3.1.1 tarball, I do the following and get an error

- as editor: request revision after a review
- as author: 
-- go to submission
-- click on "add" in the revisions grid
-- select "manuscript text" 
-- upload a file with the same file name as the original submission
-- I get message that possible revision detected, click Continue
-- Get the following error

![this error](https://www.dropbox.com/s/c7mfww3tc838v1u/Screenshot%202018-05-14%2009.08.21.png?dl=0)

**Update:** if selecting the revision (instead of letting it be detected automatically) the error does not occur.

**Comment by bozana** [comment]
Hi @jalperin, I cannot see your error image :-\
Could it be that this is the same problem as described here: https://github.com/pkp/pkp-lib/issues/3653?

**Comment by jalperin** [comment]
Not sure. I don't get the same error message, I don't think. Mine comes up when the revision is automatically detected, and not when I select the revision from the drop down.

**Comment by bozana** [comment]
@jalperin, I think with the new release this is not an issue any more, because now only revisions files are considered for further revisions (possible revision detection) i.e. if the author for example uploads a file with the same name as the original submission file, it will not be detected as possible revision, it will just be saved as a revisions file. If author then again uploads a file with the same name it will be detected as possible revision of the first revisions file, and clicking on continue then works just fine -- the file is saved with revision = 2.
Thus, I will close this issue...
