### ISSUE TITLE
Unable to Order back issues

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3705]
Under Issues > Back Issues, I have used the Order tool to reorder the issues.

However, my changes are not reflected on the public Archives page:
https://journals.publicknowledgeproject.org/sandbox/cjhe/index.php/cjhe/issue/archive

**Comment by israelcefrin** [comment]
A note, this list is sorting using published date as main parameter, ignoring **Order tool**.

**Comment by NateWr** [comment]
What would be the reason for not ordering them by published date?

**Comment by CFanselow** [comment]
Hi @NateWr, 

1. we have a journal that republishes analog issues in a digital form. The publication date is not important. It is just the (accidental) order of data being put to the system. 

2. We want to move the current issue to the end of the list in the archive, because the word "archive" implies older issues.  The current issue is already accessible under "current". 

best, 
Carola

**Comment by NateWr** [comment]
Thanks @CFanselow! A couple of follow-up questions:

> we have a journal that republishes analog issues in a digital form. The publication date is not important. It is just the (accidental) order of data being put to the system.

Shouldn't the Publication Date still be accurate? I think this gets fed to third-party consumers, like Google Scholar, who will expect it to reflect the analog issue's publication date.

> We want to move the current issue to the end of the list in the archive, because the word "archive" implies older issues. The current issue is already accessible under "current".

It sounds like you want issues ordered by publication date, but with the oldest first. Is that right? I don't want to encourage people to do this manually, because it won't be sustainable over time when there are a lot of issues. At the moment, I think the only way to do this is to customize the template. But in the future we'll probably implement a pattern where you can fetch items from the database in reverse order if you'd like.

**Comment by martinpub** [comment]
@NateWr This is still a bug, right?

We are suffering from this too, after having recently upgraded from 3.1.0-1 to 3.1.1-2.

> Shouldn't the Publication Date still be accurate? I think this gets fed to third-party consumers, like Google Scholar, who will expect it to reflect the analog issue's publication date.

I thought that publication date, in the case of retrodigitised material, was meant to reflect the publication of the digitised version in OJS. On our multijournal server, we have a lot of issues published relying on the custom order, due to their publication date not reflecting the publication date of the first (print) publication.

**Comment by NateWr** [comment]
I think @bozana will have a better grasp of these issues than me. Any idea about how publication date should be used in OJS/OMP?

**Comment by bozana** [comment]
Just a note, that the issue re-ordering is possible in the backend (once this was an issue too, s. https://github.com/pkp/pkp-lib/issues/2343), the order just have to be considered in the frontend/display too... This seems to be a new bug....

**Comment by bozana** [comment]
PRs:
ojs-stable-3_1_1: https://github.com/pkp/ojs/pull/2052
master:

**Comment by bozana** [comment]
@NateWr, could you take a look at the PR above? And specially on this change, that is not connected to this issue, but seemed right to me: https://github.com/pkp/ojs/pull/2052/files#diff-d5a2276ad0194fc24f74f72bc761477aR158

**Comment by NateWr** [comment]
@bozana the code looks good. :+1: You can merge when you'd like.

I'm still not sold on the feature. What do you think about the problems raised above about inaccurate publication dates? Does this cause problems with third-party archival bodies?

**Comment by bozana** [comment]
Thanks @NateWr !

Regarding different publication dates: I think the solution will come with this issue https://github.com/pkp/pkp-lib/issues/1369 -- when the user can enter different publication dates for print and online...
