### ISSUE TITLE
[OJS 3.x.x] Middle Name of Author is not displayed in citation (Vancouver)

### ISSUE THREAD

**Issue by anupent** [pkp/pkp-lib#3771]
Please see the forum post here:

https://forum.pkp.sfu.ca/t/ojs-3-x-x-middle-name-of-author-is-not-displayed-in-citation-vancouver/45552

Best regards,

**Comment by asmecher** [comment]
@NateWr, did you get far into CSL's name model when implementing this? It looks like it just has "given" and "family", and I suspect adding the middle name to "given" would follow their model but I haven't looked into it in depth.

@bozana, tagging you too because of the author/user name changes upcoming.

**Comment by NateWr** [comment]
Yeah I thought we won't have middle names anymore... I don't think the CSL schema even supports them: https://github.com/citation-style-language/schema/blob/master/csl-data.json#L71-L130

**Comment by anupent** [comment]
@NateWr, does that mean we won't have support for middle name for the citations even in future?

**Comment by NateWr** [comment]
The Citation Style Language itself doesn't support middle names. It uses a "given name" and "family name" approach, and middle names should be included in "given name". Soon, OJS will merge middle names into a "given name" field.

**Comment by anupent** [comment]
@NateWr, thank you for clarification. 
I will be waiting till then.
Shall I close this issue and post the information you gave to the forum?

**Comment by NateWr** [comment]
Let's wait and see what Alec says.

**Comment by asmecher** [comment]
I think the CSL spec does support middle names -- they're part of the given name. See http://docs.citationstyles.org/en/stable/specification.html#names

I didn't get into the code to see what support is there, but I wonder whether the `given` attribute can be given a list (e.g. `array('Alec', 'Karl')`).

**Comment by NateWr** [comment]
`givenName` expects a string. If citeproc-php accepts an array, it doesn't appear to be a documented feature.

**Comment by asmecher** [comment]
Hmm, and I didn't see anything useful in the documentation either. It might be worth pinging the citeproc-php authors for clarification.

**Comment by bozana** [comment]
And considering my changes: I migrated the middle name to the "preferred public name" and not to the given name. Somehow it seemed more clean for me that way. Do you think I should migrate it to the given name, maybe also in general and independent of the CLS?  
Also, I provide only given and family name to the citeproc-php, as till now. I think it does not make sense to provide "preferred public name" for CLS -- it would not work however, I think -- because it can contain salutation and suffix as well, which does not belong in the citation, right?
THANKS!

**Comment by NateWr** [comment]
Yeah I agree we shouldn't pass preferred public name to CLS. I'm ambivalent about where to put middle name, but I would guess that if someone has bothered to provide a middle name, it's probably because they want it to be visible, so maybe that's an argument to migrate it into `givenName`.

**Comment by bozana** [comment]
OK, I would then change it and migrate it to the given name, if @asmecher also agrees... THANKS!!!

**Comment by asmecher** [comment]
> I would guess that if someone has bothered to provide a middle name, it's probably because they want it to be visible

That's my feeling as well.

**Comment by bozana** [comment]
Shell we then close this issue? -- when my changes come, i.e. middle name is added to the given name, this issue will be automatically solved...

**Comment by asmecher** [comment]
Yes -- @anupent, you can expect to see those changes in OJS 3.2.
