### ISSUE TITLE
Missing locale key: user.authorization.invalidQuery

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3776]
Reported: https://forum.pkp.sfu.ca/t/message-key-without-message/45573

It is part of `QueryRequiredPolicy` and will be thrown if the query doesn't exist, or if the associated submission ID in the request doesn't match the query's submisson ID.

**Comment by asmecher** [comment]
I was able to get the message involving `user.authorization.invalidQuery` to display by attempting to view a query that had been deleted in another tab. However, the translation ("Invalid discussion.") was presented correctly (working with pre-3.3.0-9). I suspect the problem has been fixed since it was reported; if anyone is still encountering it with 3.3.0-8 or later, please note that here.
