### ISSUE TITLE
[OJS 3.1] No/ambiguous clues about timeline of submission on main interface

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#3791]
**Describe the problem you would like to solve**
When viewing a submission's workflow page, I am not able to easily determine when the submission was made. It is available in the Editorial History but the editor may not know to look there.

**Describe the solution you'd like**
Add the submitted date to the workflow page where it is easy to fine.

**Who is asking for this feature?**
No editor requests have emerged yet.

**Additional information**
This screenshot is taken from an OJS 3.1.1-1 instance.

![dates](https://user-images.githubusercontent.com/11337857/41406627-2fc392a8-6fcd-11e8-938c-ab1d871c8ff4.png)

There is no information about when the submission was submitted. The short date near the discussion omits the year. The first impression is, that the submission happened roughly a month ago. Truth is, that it was submitted in 2016.

The review tab gives only indirect hints via the review due dates. 

Some timeline information should be displayed on the main view, without pressing the *Editorial History* button on the top right. A welcomed approach would be to replace the meaningless file ids with the upload date of the file.

**Comment by asmecher** [comment]
Tagging @NateWr for consideration. @pkel, do you see the information you need in the Editorial History? (This is the submission-wide event log.)

**Comment by pkel** [comment]
Yes, the information is in the Editorial History. I know how to find it. I''m worried about the average user, who generally judges after a first superficial look.

**Comment by asmecher** [comment]
Thanks, @pkel -- understood, just making sure it was available at least somewhere. We've made a lot of hard decisions in trying to keep the interface simpler in OJS 3.x than it was in OJS 2.x, which started out messy and got messier over the years. That's meant hiding a lot of information that used to be available, and I'm sure we haven't always gotten that right. @NateWr is the best person to throw around some ideas with.

**Comment by pkel** [comment]
I fully understand the motivation for stripping down the interface. You did a great job at large. I will keep reporting little issues like this one until we got the details right!

With this motivation in mind: File IDs are not relevant for the user. Dates are.

**Comment by asmecher** [comment]
Thanks, @pkel! We did wrestle over file IDs and decided to maintain them because it's the only truly unambiguous way to refer to a file. Titles don't work (almost all submission uploads will have the same title) and dates may be misleading (it suggests a linear progression of a file through workflow, when in practice it's more like forking/merging, e.g. as several reviewers mark up copies of the same file and the editor assembles that into something for the author). I would support some way of adding date information to what's already there, personally, but my UI/UX credentials are ... willingly surrendered.

**Comment by NateWr** [comment]
Hi @pkel,

Yes, I too questioned the file IDs, but it turns out a significant portion of journals are using some external tracking system (sometimes just email), and rely on IDs like this to refer unambiguously to specific versions of files.

I agree the submission date should be more readily accessible. I have some ideas I've been kicking around to bring that whole top bar (metadata, history, library) down and make it more prominent. But it will probably be a little while before we get there.

**Comment by pkel** [comment]
What about an approach similar to the above PR?

**Comment by NateWr** [comment]
I'm not opposed to showing the date when a file was uploaded, but I don't think it is a good solution to this issue. It still relies on a user having some intuition about how to determine the submission date, and provides less authoritative information than the Editorial History (someone may upload a file and complete a submission on different days).

This screen already has a big cognitive load, so I would be hesitant to add more to it in an ad-hoc manner. We have a lot of small issues like this we could handle better, and I'd like to see them addressed together or we will end up with a death-by-a-thousand-tweaks experience here.

**Comment by asmecher** [comment]
One approach I've found useful e.g. on Github is hovering over friendly/abbreviated information (e.g. "2 days ago") to get the full context ("July 4 2018 09:00:00"). Perhaps hovering over the file ID to get a more complete identification is an option? Caveats: a) this isn't as "pure" as the Github example, which is only dates, and b) there's a good chance this isn't fully accessible.

**Comment by NateWr** [comment]
That's a good idea @asmecher and it _can_ be done accessibly (though it often isn't). As part of the form work, I've got a nice tooltip library in place. So that will be an easy approach to take when we get to migrating the file grids over to Vue.js components.

@pkel I've left a couple comments on your PR but it looks good. When checking this out, I noticed that the file history (under More Information) doesn't include the upload date. @asmecher is this something that should be included in the file history or was there some reason for keeping it out?

**Comment by asmecher** [comment]
I think the upload date should definitely be in the history -- if not, please file it!

**Comment by NateWr** [comment]
@asmecher after a bit of testing, it looks like the upload date appears in the history of the file that is uploaded. But no entries exist when a file has been forwarded to another stage (eg - submission to review). Should there be a history entry for when it was forwarded on?

**Comment by asmecher** [comment]
Yes, that's probably a good opportunity for a new log entry.

**Comment by NateWr** [comment]
Filed: https://github.com/pkp/pkp-lib/issues/3911

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
