### ISSUE TITLE
Distinguish submission content from supplementary content

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#397]
Currently there's no distinction between "main" and "supplementary" content. Genres can be created/deleted with useful names, but these are not guaranteed to be unchanged.

For Dataverse, we need a distinction permitting Dataverse to work with uploaded supplementary content, not submission content.

For the reader front-end, we need to be able to present submission content as the "main course", with supplementary content presented probably elsewhere.

**Comment by asmecher** [comment]
Talked with the UI/UX group; they agreed that a new checkbox (maybe clarifying against wording for other checkboxes) in the genre edit form would be merited, along with sensible defaults.

**Comment by asmecher** [comment]
Pulls:
https://github.com/pkp/pkp-lib/pull/398
https://github.com/pkp/ojs/pull/444
Alex, sending to you for a look.

**Comment by axfelix** [comment]
Thanks! Looks good, though this doesn't seem to support the "plugin is able to add actionable filetypes that aren't otherwise configurable as long as the plugin is enabled" use case; however, I can see not wanting to go that route for UX reasons, and this definitely seems workable as an alternative, e.g. permitting the Dataverse plugin to act on all filetypes that are flagged as supplementary. Appreciate you getting to this so quickly.

**Comment by asmecher** [comment]
Merged!
