### ISSUE TITLE
Article subtitles not showing in "how to cite"

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#4021]
When a manuscript has title and subtitle, once it gets published, only the title appears on the "How to cite" feature.

It should include both title and subtitle (when applicable).

**Comment by asmecher** [comment]
@alexxxmendonca, what version of OJS are you using?

**Comment by alexxxmendonca** [comment]
Apologies for lack of information: version 3.1.1-2.

**Comment by asmecher** [comment]
@alexxxmendonca, I don't belive the CiteProc-PHP library we're using for citation formatting supports subtitles. I'd suggest filing an issue for that here: https://github.com/seboettg/citeproc-php

**Comment by zuphilip** [comment]
@asmecher We see the same problem. However, I doubt that this is a problem of the citeproc library, because AFAIK CSL does not have a subtitle field at all. What is the inputed JSON data for the citeproc library that OJS is producing? Can someone show an example here? Possibly the title field has to be first merged with the subtitle field... CC @dennmuel

**Comment by asmecher** [comment]
@zuphilip, it looks like you're correct, there is no subtitle field in CSL... This is exhaustively discussed e.g. at https://forums.zotero.org/discussion/8077/separate-fields-for-title-and-subtitle. Either of the above patches (e.g. https://github.com/pkp/citationStyleLanguage/commit/19df5731ab25c230529dfa6f3a55fb07edf1f206.diff) will resolve this. Apply in the `plugins/generic/citationStyleLanguage` directory.

**Comment by zuphilip** [comment]
@asmecher Hey, thank you very much for the fast fix! :bowing_man: I am looking forward for the version to try it out.

Would it be possible to do a similar thing for the metadata in `DC.Title`?

Moreover, I also see that our metadata for our article at DataCite does not contain the subtitle. Can we push that information in the DataCite (possibly also the Crossref) plugin as well? Maybe as another value for `title` with the `TitleType` set to `Subtitle` (please check that carefully, because I don't know the DataCite schema that well...).

**Comment by asmecher** [comment]
@zuphilip, thanks for the additional suggestions. I've opened a PR here:
https://github.com/pkp/ojs/pull/2425

I confirm that we're already using the "full" title type for the DataCite/CrossRef title elements.

If you have the chance to try these out, please do -- the changes are nearly trivial, as you see, and don't present any risk.

**Comment by asmecher** [comment]
^ Merged the above PR and cherry-picked forward to `master`. Thanks, @zuphilip and @NateWr!
