### ISSUE TITLE
remove "STATISTICS_MAX_ROWS limit for stats downloads

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#4025]
This is defined in lib/pkp/classes/statistics/PKPStatisticsHelper.inc.php at line 46 (https://github.com/pkp/pkp-lib/blob/master/classes/statistics/PKPStatisticsHelper.inc.php#L46) and referenced to in lib/pkp/classes/statistics/PKPMetricsDAO.inc.php in lines 191-196. It appears to be an artificial constraint meant to minimized timeouts (it'll only allow csv files to max out at 5000 rows before downloading) but it introduces confusion for editors who aren't aware of the limit and don't know to work around it. It should just be removed entirely for now.

**Comment by asmecher** [comment]
This will be easy to remove, but the net effect is that users will start to see "out of memory" errors for longer reports. Is that preferable? (Legit question.)

**Comment by jmacgreg** [comment]
Yep, 100% preferable IMO to get an error if they hit the limit, and know something's gone wrong, as opposed to not getting an error and not knowing they don't have a complete data set.

**Comment by jmacgreg** [comment]
See also https://forum.pkp.sfu.ca/t/problem-ojs-usage-statistics-report/31113 - users report being able to download 25k+ lines without issue. This will differ from server setup to server setup of course, but the 5k limit is probably also just incredibly conservative.

**Comment by asmecher** [comment]
OK, done!

**Comment by ajnyga** [comment]
We had an interesting situation with one of our journals. The editor tried to export a PKPusageStatsReport from OJS. The 10 megabyte file eventually loaded, but the editor noticed that there were only entries up until November 2017. The first results were back from 2014 (with OJS2).

The CSV file had about 45 000 rows.

Probably some sort of limit was reached, because there are of course statistics after November 2017 as well, but it seems that there is no error visible for the editor that tells that the file is incomplete.

**Comment by asmecher** [comment]
@ajnyga, yes, I think this issue explains it -- the results are capped artificially with no indication to the user. That's been removed in the `master` branch (for release in 3.2).
