### ISSUE TITLE
[OJS] Submissions, ticked checks like submission requirements and privacy consent are not saved

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#4031]
Hi there,

as the title already says, when adding a submission the ticked checks like submission requirements and privacy consent are not saved. This has several side effects like 

1) the user needs to execute these checks again when returning to step 1
2) in case of the privacy consent the law requires the site owner to be able to prove that a user has actually ticked a privacy consent check-box in case of a law suit

What would be the best solution to get the ticks saved?
How about storing these in the `submission_settings`?

This issue also applies to the review process.

So lonG

**Comment by asmecher** [comment]
Storing them in `submission_settings` is the best option. However, if you're concerned about liability, you might also need to consider that the saved setting would need to store *what* was agreed to -- otherwise the Journal Manager would be able to edit the setting, and a simple yes/no stored with the submission would not indicate what version had been agreed to.

**Comment by NateWr** [comment]
Closing this in favor of https://github.com/pkp/pkp-lib/issues/7062.
