### ISSUE TITLE
Change the default DOI suffix patterns so that they support future changes in OJS

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4056]
Hi,

At the moment the default pattern of the DOI suffix for articles includes data like issue volume that is available only in the very late stages of the editorial process. I can not see any reason why it should include this data, because DOIs are not meant to be human readable - just unique inside the prefix scope.

When OJS starts to support for example the continuous publishing model (no issues) or preprints (DOI needed way before issue data is available) the current default pattern can not be used.

So instead of `%j.v%vi%i.%a` the default pattern should be for example `%j.%a` (journal_initials.article_id). 

This is a pattern that would be available immediately when the submission is made.

**Comment by mtub** [comment]
I fully support this - and I'd like to ask why there has to be a default at all. Or why that default can't just be "%a"…

**Comment by ajnyga** [comment]
sure, inside an OJS installation %a is always unique. But %j.%a looks better 😆

**Comment by ajnyga** [comment]
I have been participating in the translation of the DOI ISO standard ISO 26324:2012.

It states in 4.1.1. that: "The DOI name is an opaque string for the purposes of the DOI system. No definitive information may be inferred from the specific character string of a DOI name. "

**Comment by NateWr** [comment]
@ewhanson I know we've had a bunch of discussions about this but I can't remember exactly where we landed. Let's revisit this some time before 3.4 is out.

**Comment by mooselybased** [comment]
Hey all,

a lot of the discussion surrounding DOIs and implementing their use in OJS directly instead of using the plugin goes over my head, but I was hoping someone here could help me with a question.

The (already closed) issue [#7014 ](https://github.com/pkp/pkp-lib/issues/7014) suggests something completely different for the default pattern, but, more worryingly, seems to exclude using a custom pattern in 3.4 and onwards. I don't understand enough of the code/discussion to know if the custom pattern is completely out of 3.4 or if it is just heavily recommended not to be used, but I wonder if that's really a good idea? In our case we'd have to convince several journals to switch from their current patterns, even though we've always enjoyed letting them have a hand in it (within reason). If anybody turned out to be really, really attached to their pattern, our only option would be to switch to manual entry for each DOI - something we have categorically refused so far because of how incredibly prone to errors it would be.

As an aside, I agree with the statement that the default DOI pattern should not have to rely on information that may not be available when the DOI would be assigned. It's certainly annoyed us in the past.

So, is the custom pattern still in 3.4? If not, why? And what would the default pattern look like then?

**Comment by NateWr** [comment]
Hi @mooselybased, we don't plan to forbid custom patterns. We are just planning to design the setup/configuration UI to discourage them as much as possible. 

@ewhanson has come up with an elegant way to support custom DOI patterns while still automating DOI creation as much as possible. Basically, when configured, the system will try to create the DOI as early as it can. If it can't create it at one "checkpoint", because the pattern requires data that is not yet entered, it will try again at the next "checkpoint", all the way up to final publication.

**Comment by ewhanson** [comment]
Thanks, everyone. This has all been really helpful in thinking through the new DOI implementation. This set of PRs are the first of two to finish out the DOI refactor feature set. It adds a new default DOI generation method, that randomly generates a hyphen-separated, eight character suffix (details below) that will look something like `10.1234/4ytc-m808`.

### Current status

- [x] Add new DOI generation method
- [ ] Include editable custom/default legacy pattern option

### Default suffix generation

The new default suffix generation pattern is based on work done by Datacite—specifically their DOI Metadata Store CLI tool, [Cirneco](https://github.com/datacite/cirneco) and their [URL-friendly base 32 implementation](https://github.com/datacite/base32-url). For more details on the Datatcite implementation, see their blog post on [Cool DOIs](https://blog.datacite.org/cool-dois/).

The pattern uses a modified [Crockford Base 32](https://www.crockford.com/base32.html) algorithm to generate a random, six-character base 32 encoded number followed by a two-digit checksum using a [modulus 97-10 (ISO 7064)] (https://usersite.datalab.eu/pantheonusermanual/tabid/316/language/en-us/topic/calculation-of-check-digits-according-to-modulus-97-10/htmlid/2261/default.aspx) algorithm. This check digit technique only uses two digits from 0-9 so they create a URL-friendly checksum. Additionally, lowercase letters are used in the base 32 implementation for similar reasons. A hyphen is added in the middle for readability.

The steps are as follows:

1. Base 32 encode a random number: `4ytcm8`
2. Generate a two digit checksum: `08`
3. Combine: `4ytcm808`
4. Include hyphen for readability: `4ytc-m808`

With this generation algorithm, there are approximately 1 billion unique identifiers available for use per prefix (32 by a factor of 6).

Once complete, there will be three DOI suffix options to choose from:

| Option | Description                                                                                                                                                                                                                                                                        | Change from OJS/OMP/OPS 3.3.x |
| --- | --- | --- |
| Default suffix generation | Uses the modified Crockford base 32 method described above. Can be automatically created at 1) the copy-editing stage, 2) upon publication or 3) never. Is not reliant on any existing publication metadata.                                                                       | This method did not exist in 3.3.x |
| Manual suffix entry | Allows users to manually enter complete DOIs using the DOI management interface.                                                                                                                                                                                                   | Same as 3.3.x |
| Custom pattern suffix | Uses the pre-existing pattern-based suffix generator. During an upgrade to 3.4, any existing custom suffix patterns will be carried over and accessible here. If none exist, the pre-3.4 default patterns will be added here. All default patterns are also valid custom patterns. | In 3.3.x, default patterns and custom patterns were two separate options. They will now be unified under a single, editable custom pattern option. |

### PRs

@NateWr, could you have a look at these PRs? Thanks!

- `pkp-lib`: #7782
- `ui-library`: pkp/ui-library#190
- `ojs`: pkp/ojs#3338
- `omp`: pkp/omp#1088
- `ops`: pkp/ops#252

**Comment by ajnyga** [comment]
I would leave out the hyphen. Using hyphens in a suffix is something that the DOI ISO standard mentions as something that should be avoided.

**Comment by ewhanson** [comment]
Hey @NateWr, could you have another look at these? Barring any minor bugs/changes, these should be ready to go. Thanks!

PRs:

- `pkp-lib`: #7782 
- `ui-library`: pkp/ui-library#190
- `ojs`: pkp/ojs#3338
- `omp`: pkp/omp#1088
- `ops`: pkp/ops#252
- `crossref-ops`: pkp/crossref-ops#11


> I would leave out the hyphen. Using hyphens in a suffix is something that the DOI ISO standard mentions as something that should be avoided.

Thanks @ajnyga, I'm leaving things as-is for this PR, but will review the standard in detail and follow up with some more adjustments in a separate PR.

**Comment by NateWr** [comment]
Looks good @ewhanson. I took a pass at the language/structure of the settings forms and I've opened a couple of PRs to your branches:

https://github.com/ewhanson/pkp-lib/pull/2
https://github.com/ewhanson/ojs/pull/1

The main changes are:

- Lots of locale strings changed
- Lots of locale strings moved into pkp-lib or removed where duplicates existed
- Moved the "automatic deposit" setting into the registry agency form, so that it only appears when a registration agency exists to deposit to

In addition to that, I came across some issues while testing. Some of these may already be filed, or you can file them separately if you want to address them in separate commits:

1. It's not possible to remove a DOI once it has been assigned. When I try to edit the DOI, clear the input field, and save, I get the following error:

```
{
	"doi": [
		"This is not a valid string.",
		"This is not formatted correctly.",
		"This field is required."
	]
}
```

2. When I set up a custom suffix, the article suffix was used for galley DOIs. My galley suffix is: `%j.v%vi%i.%a.g%g`, but when I selected a submission then bulk action > assign, all of my galleys got the submission DOI. I think this is because because `Repository::generateSuffixPattern()` always passes publication to `Repository::getPubIdSuffixPattern()`.

3.  I'm not sure the DOI deletion is working properly. I used the API to do a `DELETE /api/v1/dois/14`. The DOI was removed from the database, but the galley rows in the database still had `doi_id` set to `14`. So the foreign key there isn't working properly. It should either set the `doi_id` to `null` in the galley before deleting the doi from doi table, or a fatal error should be thrown when you try to delete the doi from the doi table.

Otherwise, the cool doi pattern worked without a hitch. :+1:

**Comment by ewhanson** [comment]
@NateWr, I've gotten the locales up-to-date and have fixed question 2 and 3 above. I'll spin question 1 off into it's own issue to address separately.

**Comment by NateWr** [comment]
Thanks @ewhanson! That all looks good. I've added a few comments but nothing that would block merge.

While testing, I was unable to get automatic DOI generation working. I configured it to generate a DOI at the copyediting stage, set it to default DOI suffix pattern, and "accepted" a submission in the review stage so that it moved to the copyediting stage. But this did not generate a DOI for the submission. Here are my settings:

![doi-generation](https://user-images.githubusercontent.com/2306629/167815619-31c05528-0a44-4861-8a84-12f6408ccd0c.png)

Lastly, if you run into a problem with tests and find this error in your logs:

```
in /home/nate/Projects/pkp/ojs-main/lib/pkp/classes/services/PKPSchemaService.inc.php on line 380
[11-May-2022 09:11:29 UTC] Slim Application Error:
Type: Error
Message: Call to undefined method PKP\core\PKPContainer::runningUnitTests()
File: /home/nate/Projects/pkp/ojs-main/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Log/LogManager.php
Line: 522
```

Have a look at this code in a PR that's close to merge from Vitaliy:

https://github.com/pkp/pkp-lib/pull/7891/files#diff-aea06926e59aebf7d362a9e19ed70115727b562536ecd5a039c326f2068de007

**Comment by ewhanson** [comment]
Hey @asmecher, I've addressed @NateWr's comments above, and all the tests are passing.

Aside from the two questions on #7782 (depending on the priority, these could go in as a separate PR), these should be good to go. Thanks!

PRs:

* `pkp-lib`: #7782
* `ui-library`: pkp/ui-library#190
* `ojs`: pkp/ojs#3338
* `omp`: pkp/omp#1088
* `ops`: pkp/ops#252
* `crossref-ops`: pkp/crossref-ops#11

**Comment by asmecher** [comment]
@ewhanson, thanks, I just added a couple of nearly trivial comments, but otherwise these have my blessing. My review was fairly cursory, though, as I haven't worked with these requirements.

**Comment by ewhanson** [comment]
Thanks @asmecher, I'll get the [versions table change made](https://github.com/pkp/pkp-lib/pull/7782#discussion_r875158947), and once all the tests pass, I'll go ahead and merge.

**Comment by asmecher** [comment]
@ewhanson, https://github.com/pkp/omp/commit/2d68bb2057e7ccb0354e416ea2ad7e7cbdb90179 introduces a duplicate `doi.manager.settings.doiObjectsRequired` key in `locale/en_US/manager.po` in OMP. Could you resolve the duplicate?

**Comment by ewhanson** [comment]
Thanks for catching that, @asmecher! I've removed the duplicate and created a PR. Could you have a look? Thanks.

- pkp/omp#1152

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by asmecher** [comment]
@ewhanson, is this issue ready to be closed?

**Comment by ewhanson** [comment]
@asmecher, yes! Nothing left in this issue specifically.
