### ISSUE TITLE
[Sprint/UIUX] Quick-Filter Options/Buttons on Dashboard

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#4101]
> Result of the UI/UX group from the Heidelberg Sprint 2018 (@stranack @NateWr).

The current filter options (dashboard submission queue) are great with room for improvement. Our idea: add quick-filter buttons which allows the E/SE to quickly get an overview over submissions in specific (_critical_) states.

Below Search/Filter, add 5 (?) Quick Filters for most common filter rules (see Figure below):
- "**Inactive**" = _X days_ without activity but we (SE/E) should actually take action! Not to be mixed up with _overdue_
- "**Reviews Missing**" = overdue reviews
- "**Reviews here**" = all reviews are in, _we_ have to take action
- "**Revisions here**" = author has uploaded their revision, _we_ have to take action

![Screen-draft how we think this could look like. Additional row with quick filters in the table header.](https://user-images.githubusercontent.com/13628564/46159072-b4843b00-c27f-11e8-8cab-218b7b72f2f6.png)

**Figure:** Screen-draft how we think this could look like. Additional row with quick filters in the table header.

**Comment by asmecher** [comment]
(@stranack and @NateWr!)

**Comment by NateWr** [comment]
Thanks! Do you remember why the team felt that quick filters would be better than the filters panel on the side? Was it just to save a single click (to open the filters panel)? 

If yes, I'd want to dive a bit more into the usage pattern that is causing this extra click to be a burden. Is it perhaps because the editors are frequently browsing away from the list and back to it, many times in succession?

If that's the case, I'd suggest a couple of alternative ways to deal with this:

1. Would it be good if a submission remembered it's last condition for each user? So when they browse away and browse back, it will show with any search/filter conditions the user had previously applied?

2. It's our intent to add more [quick actions](https://github.com/pkp/pkp-lib/issues/2887) to the submission list. In the future, this may significantly reduce the amount of times an editor needs to leave the list to accomplish a task.

**Comment by retostauffer** [comment]
Hy Nate

The idea was to make it very easy for the editors to get an overview of the most critical submissions. You are right, the navigation on the left hand side (filter panel) provides similar features but requires more than one click. For example: as an editor I would like to log in and quickly go trough "_show me all submissions inactive since X days_", if there's nothing I have to take action I'll check "_submissions where reviews are here but not further action taken_", if nothing suspicious I'll check the next filter and so on. At the moment this would require about 10 clicks.

We believe that the editors might be more willing to check the queue more often if they can do it in 5 seconds. These quick-filters would support this process.

To answer your items
1. _Keep previous filter options:_ Not sure whether more helpful or confusing and does not really address the idea of the quick-filter buttons. As mentioned above the buttons are not to reset one specific filter with one button, but to go trough a set of (maybe "complex") _critical filter rules_ to get an overview of what's going on.
2. That will be very helpful and might solve the problem. On the other hand one could still provide quick-filter-buttons for the most critical tasks/things while the current filter list can be used to apply 'custom' filter sets.

**Comment by NateWr** [comment]
We could still have one-click filters in place for these, even if they're in the filter panel. Here's an example of what it might look like:

![selection_074](https://user-images.githubusercontent.com/2306629/46208351-552b3700-c322-11e8-8f57-6f8279c463ef.png)

We might even be able to provide a count as well:

![selection_075](https://user-images.githubusercontent.com/2306629/46208362-6116f900-c322-11e8-8a23-d38e1d4084bc.png)

And the filter tab could be open by default if we felt that was the way to go (or even just have the state saved in local storage so it's open/closed depending on the user's last interaction).

Do you see these as something that should be present for all submission lists? Or only the All Active list? All editors and section editors? Or only for top-level journal managers?

**Comment by retostauffer** [comment]
The count is a nice idea! 

Requires one additional mouse click on the "Filters" button once when entering the dashboard, that sounds ok. I am personally not to deeply involved in the editorial process (I only the problem solver ;) ). From my perspective this might work well without the need of the buttons, I would not open the tab by default, but keep last state (open/closed) might be useful (but not required).

These special filters would be nice for all Tabs (All Active, Archive, ...), I can't tell you what the most important filters are for each tab. And they might be of most interest for JM/E/SE but not for lower levels (?).

**Comment by alex-wreschnig** [comment]
The UI/UX group at the 2019 Pittsburgh sprint also had some thoughts about improvements that could be made to the filters--it looks like this issue is the right place to add these?
- Rename or reword the “Incomplete” filter (at least in the US translation) to be more descriptive: “Incomplete Submissions” maybe?
- Add ability to filter by role (editor, author, copyeditor, etc.)
- Add a filter for submissions that require specific action from the active user

This seemed to be pretty broadly agreed upon by the journal editors and managers who were at the sprint.

(Group notes: [UI/UX group notes from the Pittsburgh sprint](https://docs.google.com/document/d/1oWcsyHX2Ww5tHPpSN_-c2KaIhmAdaGYcZn3gFHjMEpc/edit?usp=sharing))

**Comment by NateWr** [comment]
Thanks @alex-wreschnig. I've split the "incomplete filter" text to a separate issue: https://github.com/pkp/pkp-lib/issues/4974.

I split the filter by role into a separate issue (that also suggested separate lists per role): https://github.com/pkp/pkp-lib/issues/4975

**Comment by NateWr** [comment]
I believe the suggestions here are now captured in other issues, especially the review stage filters which are at https://github.com/pkp/pkp-lib/issues/7488. Thanks to everyone for the discussion on this topic. I'm going to close this in favor of the other issues.
