### ISSUE TITLE
[Sprint/UIUX] Scheduled for Publication Button w/ Additional Information

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#4108]
> Result of the UI/UX group from the Heidelberg Sprint 2018 (@stranack @NateWr).

Once a submission has been scheduled for publication (publication stage) the text of the action button should change to "_Scheduled to Volume 666, Issue 3_". Or, alternatively (and maybe more consistent with the rest) a banner should be shown (see screen-draft below) and the action button should be "removed" (following https://github.com/pkp/pkp-lib/issues/3386#issuecomment-407723802).

![screenshot](https://user-images.githubusercontent.com/13628564/46169541-bc51d880-c29b-11e8-9fad-d871f4b3903e.png)

**Comment by ajnyga** [comment]
+1 for the banner (and 666)

But the button has to stay. For example editors might come back to change the page numbers or the license of the article. 

But maybe the text of the button could change when the article is already scheduled?

**Comment by retostauffer** [comment]
One idea with the buttons is (see https://github.com/pkp/pkp-lib/issues/3386#issuecomment-407723802) that they will be hidden as soon as an action has been triggered _BUT_ they can still be accessed (check screenshots in https://github.com/pkp/pkp-lib/issues/3386#issuecomment-407723802).

**Changing the button text** was the initial idea of the Sprint UIUX group. I think that might be totally fine as well but  it should be consistent with the behavior of _all_ action buttons in _all other stages_.

**Comment by ajnyga** [comment]
I do not have any strong opinions about this. But changing for example the page numbers is already fairly hidden for the users so there should not be more steps you need to take to accomplish that (see https://forum.pkp.sfu.ca/search?q=how%20to%20page%20numbers)

I think that the schedule for publication button is different from the others, because with the other buttons you can make a decision that you might want to cancel - true. But with the schedule for publication button you do not usually want to cancel the schedule for publication decision - just edit for example the page numbers. So having a "change decision" link does not sound right.

Maybe the article metadata you now edit using that form should just be accessible by another way.

**Comment by NateWr** [comment]
My two-cents:

- Yes to the banner.
- Change the button text to: "Edit Publication Details"

**Comment by retostauffer** [comment]
+1 for that. Should not be too hard to implement and would solve the current issues.

**Comment by amandastevens** [comment]
Can this issue be closed now?  Was it resolved in OJS 3.2?

**Comment by NateWr** [comment]
Yes, the workflow changed significantly once versioning was added. There may be some lingering UX issues here, but it's better to identify fresh problems through current research.
