### ISSUE TITLE
Participants add process lists all users

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#411]
The participant add process lists all users. This is fine for internal roles, but will be unworkable e.g. for authors where the list could be long.

**Comment by beghelli** [comment]
I think that task assignments like the participants in a submission can benefit from a general way to filter users, like the reviewer assignment. First we can have the simpler solution, then users can decide to advance search users to assign to the stage. The filter could be number of assignments, time to complete, etc, just like the reviewer. I think we can generalize that to make it the same interface for any user task assignment in the whole system.

**Comment by bozana** [comment]
Hi @asmecher and @beghelli, should I then orient myself on the reviewer assignment search and filter and try to implement it here too? Maybe just one thing to change: All reviewer are listed and it can be search within them. Because the list of persons here (e.g. authors) could be too long, maybe to have just a search with auto suggestion/completion? THANKS!!!

**Comment by asmecher** [comment]
@bozana, hmm -- you're right, the current reviewer selection page does present all users. That's going to be a performance problem.

I think there's a lot of benefit in having the same tool used in both places, for consistency and simplicity.

I'd suggest adjusting the reviewer search so that it supports endless scrolling (using Bruno's grid feature) -- that'll solve the performance problem there -- then using the same approach to solve the "assign participant" modal. Does that make sense? @beghelli, do you think that's a good approach?

**Comment by asmecher** [comment]
(If this isn't active, I'm considering deferring to OJS 3.0)

**Comment by asmecher** [comment]
Deferred.

**Comment by bozana** [comment]
PKP-LIB PR: https://github.com/pkp/pkp-lib/pull/1736
@NateWr, could you please review this PR?
I will soon add the same feature (scrolling) for the reviewer grid...

**Comment by NateWr** [comment]
Looks good! I had a couple of minor comments and some UX stuff. Also, I wanted to ask how difficult it would be to move the user group selection into the grid.

As it is, the grid steals focus and it's easy to miss the user group selection up top. It'd be great to just incorporate this into the selection filter, since that's what the user's doing anyway. Here's what it would look like:

![locate-user-filters](https://cloud.githubusercontent.com/assets/2306629/17738909/19e5f5d8-648b-11e6-85a2-d77cf76859ec.png)

If it's too much too late, don't worry about it. But if it can be done, then disregard my comment about collapsing the filters on load. With the user group selection in the filter, then I think the filter should be open by default. :)

**Comment by bozana** [comment]
Yes, I can try that -- I was thinking about that, but because the for around the grid needs the form field I left it there. Also, because I thought if the grid could be reused somewhere else (for an already specified group), e.g. in reviewer select grid, but the reviewer select grid has to use so many different filters and different DAO, that it doesn't make much sense for it to be based on this, I think.
I could try to add it to the filter and use JS to fill an hidden field with that information for form above, OK?

**Comment by NateWr** [comment]
Sounds good!

**Comment by bozana** [comment]
@NateWr, I integrated all your comments (s. the two commits above), so OK?

**Comment by NateWr** [comment]
:+1: Just a couple more little things. Looks great!

**Comment by bozana** [comment]
@NateWr, s. the last commit... :-) THANKS!!!

**Comment by NateWr** [comment]
:+1: merged! Read to close?

**Comment by bozana** [comment]
THANKS A LOT!!! Closing...
