### ISSUE TITLE
Option to name PDF-galley

### ISSUE THREAD

**Issue by ihdl** [pkp/pkp-lib#4112]
My request is to an option to assign a name for the final, publicised files (pdf or else). I would love to see more descriptive filenames here instead of the ID-based filenames that OJS assigns atm. For example, I would choose JOURNAL-Author-YEAR.pdf, so that users who download a PDF will find a file on their computer that they can easily identify. But the name should be assigned by the journal manager.

**Comment by asmecher** [comment]
@ihdl, what version of OJS are you using?

**Comment by MarHerUMR** [comment]
@ihdl I think more descriptive filenames would be great. I see several challenges for good filenames.

* I would use the Journal initials in order to keep the filenames as short es possible.
* I'm not quite shure what the best approach would be when you have several authors
    * What would be the best delimiter for author names
    * How many names should be added at max
* I think we would have to add (at least parts) of the submission title to the filename because you can have several issues in one year with submissions from one author and maybe several in one volume alone
    * In Marburg the MedRez has a submission from Kewin Drews in [issue 1](https://archiv.ub.uni-marburg.de/ep/0002/issue/view/226) and [issue 2](https://archiv.ub.uni-marburg.de/ep/0002/issue/view/232) as well

Maybe other platforms have found a good solution for this…

**Comment by ihdl** [comment]
@MarHerUMR Thanks for your input! I think it would be good to draw from citation standards for the issues you posed. For example, we could use "et al" for more than one author and b, c for more than one article a year. Like it's often used in lists of references. Then a more complex file name would read "MedRez 2018 Drews et al b". I'm not sure about the delimiter though.

**Comment by asmecher** [comment]
I doubt we'll be able to find an automatically-assigned naming scheme that suits everyone. What about just using the filename that's assigned when the editor/layout editor uploads the file? This would involve...

```
diff --git a/pages/article/ArticleHandler.inc.php b/pages/article/ArticleHandler.inc.php
index 4176884..1caa9e6 100644
--- a/pages/article/ArticleHandler.inc.php
+++ b/pages/article/ArticleHandler.inc.php
@@ -277,7 +277,7 @@ class ArticleHandler extends Handler {
 			if (!HookRegistry::call('ArticleHandler::download', array($this->article, &$this->galley, &$fileId))) {
 				import('lib.pkp.classes.file.SubmissionFileManager');
 				$submissionFileManager = new SubmissionFileManager($this->article->getContextId(), $this->article->getId());
-				$submissionFileManager->downloadById($fileId, null, $request->getUserVar('inline')?true:false);
+				$submissionFileManager->downloadById($fileId, null, $request->getUserVar('inline')?true:false, $submissionFile->getLocalizedName());
 			}
 		} else {
 			header('HTTP/1.0 403 Forbidden');
```

Feedback on this is welcome!

**Comment by MarHerUMR** [comment]
I think this would be a good approach, using what's already there. But the _Review Details_ step of the galley upload should state explicitly the chosen filename will be used a the download filename.

Is there a way to see and change this name after the upload right now?? As fare as I can see the only option would be to _Change File_, reupload the same document and set the new name again. I think there should be an easy way to change the filename so you can correct typos.

I thought about extending the _articleGalleyForm.tpl_ in case there's a `$this->_articleGalley->getFile()` set in the _ArticleGalley_.

![edit-galley-filename](https://user-images.githubusercontent.com/23074158/46800800-1bfaba00-cd59-11e8-9e1f-27a8cdcc32d8.png)

But I'm not sure if this might be confusing/conflicting with the _This galley will be available at a separate website._ option. On the other hand we could insert another tab for changing the filename, like the _Identifiers_ tab. What do you think would be the better option?? Or is there an option to change the file name that I am missing??

**Comment by asmecher** [comment]
<sub>heh, wasserbueffel.</sub>

There are a few natural options we could use for filenames:
1. The filename in the upload wizard (my proposal in https://github.com/pkp/pkp-lib/issues/4112#issuecomment-428692330)
2. The upload filename on the client side (whatever the filename was on the machine we uploaded from)
3. A new form field (your proposal in https://github.com/pkp/pkp-lib/issues/4112#issuecomment-428920850)
4. Something e.g. derived from the `Public Identifier` field

I'm hesitant to add a new field because we already have several "filename-like" fields and it won't be at all clear to the user what they're for. But as you point out, it's not currently possible to edit files. That's not just the title field -- some file types will have a full DC metadata set, and these also cannot be edited once they're entered.

I'd propose two things:

- Exposing the galley file metadata form to the user so the data can be edited (including the filename)
- Implementing item 2 above so this is used as the download filename
- Filing a new issue to consider standardizing filename habits more broadly:
  - Should we be using the upload wizard's filename field universally as the download filename? Currently a mix of client-side and server-side filenames are used.
  - Should we pre-populate the upload wizard's filename field with the client-side filename, rather than automatically generating a filename?

**Comment by asmecher** [comment]
https://github.com/pkp/ojs/pull/2133 exposes the galley file metadata form.

**Comment by jcabdel** [comment]
Hi Alec Smecher,

A pleasure to greet you. I really admire your work.

This line doesn't work in my OJS 3.2.1-1

$submissionFileManager->downloadById($fileId, null, $request->getUserVar('inline')?true:false, $submissionFile->getLocalizedName());

I thank you in advance if you can help me.

Regards.

**Comment by asmecher** [comment]
Thanks for the kind words, @jcabdel! Can you describe what happens with that change in place?

**Comment by jcabdel** [comment]
Hi. I think getLocalizedName() not return any correct value.

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function getLocalizedName() on null in /var/www/vhosts/avances.adide.org/avances/pages/article/ArticleHandler.inc.php:391\nStack trace:\n#0 /var/www/vhosts/avances.adide.org/avances/lib/pkp/classes/core/PKPRouter.inc.php(391): ArticleHandler->download(Array, Object(Request))\n#1 /var/www/vhosts/avances.adide.org/avances/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)\n#2 /var/www/vhosts/avances.adide.org/avances/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPPageRouter->route(Object(Request))\n#3 /var/www/vhosts/avances.adide.org/avances/lib/pkp/classes/core/PKPApplication.inc.php(279): Dispatcher->dispatch(Object(Request))\n#4 /var/www/vhosts/avances.adide.org/avances/index.php(68): PKPApplication->execute()\n#5 {main}\n thrown in /var/www/vhosts/avances.adide.org/avances/pages/article/ArticleHandler.inc.php on line 391\n', referer: https://avances.adide.org/plugins/generic/pdfJsViewer/pdf.js/web/viewer.html?file=https%3A%2F%2Favances.adide.org%2Findex.php%2Fase%2Farticle%2Fdownload%2F676%2F636%2F1118

**Comment by asmecher** [comment]
@jcabdel, for OJS 3.2.x, I believe you'll have to add the following line before the call to `$submissionFileManager->downloadById`:
```
$submissionFile = $this->galley->getFile();
```

**Comment by jcabdel** [comment]
Ok. Now work perfectly.

Thank very much @asmecher

**Comment by aguen** [comment]
+1 for this feature! 

Currently, the PDF filenames are rather cryptic. And they include the title of the component to which the galley was uploaded (e. g., "Article Text"). The problem with this is, that the titles of components are often targeted to authors submitting articles (not to readers, downloading galleys).

**Comment by NateWr** [comment]
File name generation was changed significantly in 3.3. Closing this as outdated.
