### ISSUE TITLE
[OJS 3.1] A user with manager role in a specific journal (context) is not able to use the "Login As" feature for some of its users.

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#4114]
The Login As feature does not appear for all journal's users. This seems to occur if the user has a role in another journal (context).

Ex:
◦User A is Manager of Journal 1
◦User B is Author  in Journal 1
◦User Ais Reviewer in Journal 2
◦User B is Reviewer in Journal 2

In this example, user A will not be able to Login As User B in Journal 1.

Thanks, 
pierre

**Comment by asmecher** [comment]
That's intentional behavior, @pilasou -- it happens when a user is active in other journals that you don't also manage. This is to prevent logging in as the user and performing their duties in another journal when you shouldn't have the ability to do that. For now, you'll either need to be enrolled in the other journal as a Journal Manager, or get yourself a Site Administrator role.

**Comment by pilasou** [comment]
Thanks. I understand but would there be a way to restrict the Login As feature to the Journal (i.e. login as in Journal A prevent actions in Journal B).

**Comment by asmecher** [comment]
Rather than relying on the "Log In As" feature, which I would argue is too powerful for most uses and thus requires higher privileges, I'd suggest considering other ways to act on the user's behalf. This has been discussed e.g. in https://github.com/pkp/pkp-lib/issues/2508. Can you describe the use case a little more, e.g. is this for users who need editor intervention in the workflow somewhere specific?

**Comment by pilasou** [comment]
I have no case to share right now as we will start production later this year. We just noticed that Log in as was not available for each users in our test instances. This case can remain closed. The discussion you sent (#2508) is quite interesting!
