### ISSUE TITLE
references native import

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#4195]
provide a possibility (xml element) to import references for a submission

**Comment by mtub** [comment]
if you allow references to be imported, people might look for standard bibliographic formats like BibTeX…

**Comment by bozana** [comment]
Hmmm... yes... but currently OJS does not know about them -- it sees a reference/list of references just as a text...

**Comment by eddoff** [comment]
Any development in this issue @bozana ? 

I saw that there is a Crossref upload referernce plugin in 3.1.2.0 - that´s great, but this issue to import references to OJS is not fixed...

**Comment by diegoabadan** [comment]
We are needing this functionality, we should soon send a PR.

**Comment by diegoabadan** [comment]
Hello @asmecher !

Due to the carnival celebrations in Brazil, our team only returns to work on Wednesday afternoon. :(

If you want to see how it looks now:
https://github.com/pkp/ojs/compare/stable-3_1_2...lepidus:i4195-enhancement-import

https://github.com/pkp/pkp-lib/compare/stable-3_1_2...lepidus:i4195-enhancement-import

We still have to port to 3.2, but I imagine it will be something simple.

We made the changes on top of the stable OJS (3.1.2) to facilitate testing. At first the functionality was implemented, but we will do more tests and check if there was any modification not related to this issue in git.

**Comment by asmecher** [comment]
@diegoabadan, I agree that working with `stable-3_1_2` is the best thing to do at the moment -- the surrounding code is still getting a little bit of work before the release. (https://github.com/pkp/pkp-lib/issues/4880 -- heads-up @defstat!)

**Comment by asmecher** [comment]
PRs:
- pkp/ojs#2654
- #5566

**Comment by asmecher** [comment]
Cherry-picked commits in the above two PRs to `stable-3_1_2` -- they now need forward-porting to `master`.

**Comment by asmecher** [comment]
@defstat, could you forward-port the above two PRs to OJS and OMP `master`? They didn't make in into 3.2 but they are already in OJS `stable-3_1_2`.

**Comment by defstat** [comment]
@asmecher 

PRs:
[OJS]: pkp/ojs#2660
[pkp-lib]: #5579

**Comment by asmecher** [comment]
Merged! Thanks, @defstat.

**Comment by asmecher** [comment]
Whoops, I closed this too  soon, @defstat -- could you also port to OMP `master`?

**Comment by defstat** [comment]
@asmecher 

PR 
[OMP]: pkp/omp#778
