### ISSUE TITLE
Article report missing dates

### ISSUE THREAD

**Issue by Baytan** [pkp/pkp-lib#4197]
Thanks to all contributors of this Project. We are using ojs for our journal for 2 years. I have a request for future versions.

When article report is taken, the submission, revision and decision dates of the articles are not given. However, these are critical data and may be easy to be given.

For example, indexes may ask for the average decision time for articles and I cannot get them from ojs. Thank you for your attention in advance.

**Comment by asmecher** [comment]
@Baytan, what version of OJS are you using? (Please include this in your reports.)

**Comment by Baytan** [comment]
We are using ojs 3.1.1.4.

**Comment by bozana** [comment]
Hi @Baytan, I believe this is similar to the issue https://github.com/pkp/pkp-lib/issues/2820. 
There the date submitted will be added, as well as the last decision and its date because it is possible to make several decisions). Would that be fine for you?
What do you exactly mean with "revision"?
If you do not mind i.e. if it is true that this is similar to that issue, would you please close this one and comment what you would like to have in the other, already existing issue?
Thanks!

**Comment by Baytan** [comment]
Dear Bozana,
I agree that the issues are similar. I will close this and add it to the #2820.
Thanks.
