### ISSUE TITLE
[OJS 3.1.1.4] Translation keys might be confused for some locales (navigation.submissions & about.submissions)

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4214]
Hi! See here for the details: https://forum.pkp.sfu.ca/t/ojs3-1-submissions-locale-key/46290

`navigation.submissions` and `about.submissions` may have different translations for some locales, so they cannot be used interchangeably.

**Comment by mtub** [comment]
@asmecher, I might need some help tracking this down. From what @Ph-We wrote in the forum, I am not sure if the locale keys or the code displaying them changed between 3.0 and today.

**Comment by Ph-We** [comment]
Just to be more specific: the item in the 'About' dropdown menu should have the same key (`about.submissions`) as the item in the breadcrumbs (in the page where that item leads): 
![image](https://user-images.githubusercontent.com/22288161/48196026-59576500-e362-11e8-987e-d6d2ceebc60a.png)

**Comment by defstat** [comment]
Hi all! In my perspective the `submissions` page, and the `about submissions` page are two different things that could have different translations. For the navigation menus feature the `navigation.submissions` key is currently being used to point to the `about.submissions` page, mainly because the purpose of the `navigation.submissions` was to point to `submissions` page, which at a later version of the feature was assigned to the `navigation.dashboard` key. 

Not sure if I have perplexed the issue, but, bottom line, I think that both keys should be available for the different purposes, even though the code is not currently using the `navigation.submissions` key to redirect to the `submissions` page. Further more, the use of the `navigation.submissions` key to point to the `about -> submissions` page could be misleading and perhaps should be changed to `about.submissions` key.

**Comment by Ph-We** [comment]
@defstat, thank you for this reply. However, we are still at a loss why the 'navigation.submissions' is displayed instead of `about.submissions`.

**Comment by ppv1979** [comment]
@defstat I am a main maintainer of Russian translation and I agree with @Ph-We, we should change the key to be consistent in the translations. In English locale these two keys (navigation.submissions and about.submissions) are identical, but in Russian (and may be in other Slavonic languages) we can't do it the same way, because navigation.submissions is about the particular items (submissions=sent manuscripts), but about.submissions is about the process of sending these items (submissions=how to submit manuscripts), so I have to translate it in different way. 

One more thing: on the screenshot by @Ph-We 
> ![image](https://user-images.githubusercontent.com/22288161/48196138-a3d8e180-e362-11e8-912e-86c694ea69af.png)

You can see about.submissions (Отправка материалов = how to submit manuscripts) as the heading on the page (highlighted yellow in the background) and it's right, but in the navigation menu you see navigation.submissions (ОТПРАВЛЕННЫЕ МАТЕРИАЛЫ = sent manuscripts), so users are confused by the menu.

So can you change in navigation menu navigation.submissions to about.submissions?

**Comment by defstat** [comment]
Yes I will open a PR for that, as a reference to this issue.

**Comment by ppv1979** [comment]
Thanks!

**Comment by ppv1979** [comment]
@defstat, have you already managed to do something with this issue?

**Comment by defstat** [comment]
@Ph-We Sorry for the delay, I lost track of that one.

I am changing the navigation.submissions locale to about.submissions for the Navigation Menu Items but there are the following occurrences:

about.submissions
- https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/submissions.tpl#L13
- https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/submissions.tpl#L16

navigation.submissions
- https://github.com/pkp/pkp-lib/blob/master/templates/common/header.tpl#L76
- https://github.com/pkp/pkp-lib/blob/master/templates/dashboard/index.tpl#L10

Both places, I suppose the translation means to be "Submissions" in English. (and not the equivalent to about.submissions). If that is correct, what should we put there in order to be consistent?

**Comment by ppv1979** [comment]
@defstat, I've looked at the code but can you provide screenshots of how these particular keys look on the particular pages after rendering all the template? Just to understand the context. Maybe we even need the third key for some of these places.

**Comment by Ph-We** [comment]
Assuming there were no problems in 3.0.*, would it be relevant to take those parts of code as correct?

**Comment by defstat** [comment]
Indeed the about.submissions reference is correct. The https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/submissions.tpl is called by the AboutContextHandler so that seems to be the correct translation. 

The other reference, (https://github.com/pkp/pkp-lib/blob/master/templates/common/header.tpl and https://github.com/pkp/pkp-lib/blob/master/templates/dashboard/index.tpl) is at the "Dashboard" page which looks like this:

![untitled](https://user-images.githubusercontent.com/560456/52499878-3a78a100-2be5-11e9-86c7-90ab51c2fc38.png)

[1] Is from https://github.com/pkp/pkp-lib/blob/master/templates/common/header.tpl#L76
[2] Is from https://github.com/pkp/pkp-lib/blob/master/templates/dashboard/index.tpl#L10

So should I change the Navigation Menu locale and leave the navigation.submissions for those two references?

**Comment by ppv1979** [comment]
@defstat I think you should leave navigation.submissions for [1, 2, 3]. @Ph-We, do you agree with me?

**Comment by Ph-We** [comment]
The 'Dashboard' page looks quite correct now in our instance of 3.1.1.4:

![image](https://user-images.githubusercontent.com/22288161/52503166-c72b5b00-2bf5-11e9-9fd6-644f1a4e4696.png)

So if `navigation.submissions` is rendered as "Отправленные материалы", then it should still be there in [1,2,3]. So nothing needs to be changed in this case (?).

**Comment by defstat** [comment]
@NateWr 

PRs
[pkp-lib]: #4472
[OJS]: pkp/ojs#2281
[OMP]: pkp/omp#638

**Comment by NateWr** [comment]
These look good @defstat. The tests may be related to the fatal error in `master` at the moment. Let me see look into that.

**Comment by defstat** [comment]
@NateWr, yes I think it is the fatal error, because I can't login because of that (and so the waitForElementPresent('link=Logout') is false)

**Comment by NateWr** [comment]
@defstat Can you rebase now that the tests in `master` are fixed? Happy to merge once the tests pass.

**Comment by defstat** [comment]
@NateWr I rebased and I am getting an "The command "phpenv global 7.2" failed and exited with 1 during ." error on some jobs (see https://travis-ci.org/pkp/omp/jobs/492775034)

**Comment by asmecher** [comment]
@defstat, I think that was a Travis service hiccough -- I've restarted the job and expect it'll get farther this time.

**Comment by NateWr** [comment]
@defstat The tests look good. There was just one OJS test that fell over again. If you see that has passed, rebase again and let me know and I'll merge. :+1:

**Comment by Ph-We** [comment]
Hi @defstat, I'm really sorry for reminding again, but may we hope your PR will be merged before 3.1.2 is released?

**Comment by defstat** [comment]
@NateWr 
[stable 3.1.2] PRs
[pkp-lib]: #4536
[ojs]: pkp/ojs#2311
[omp]: pkp/omp#649

**Comment by NateWr** [comment]
:+1: I've merged the stable PRs. The tests have passed for the `master` PRs, so just give them a quick rebase and ping me and I can merge them.

@Ph-We This will be part of 3.1.2.

**Comment by Ph-We** [comment]
@defstat , @NateWr , we are really thankful to you both.

**Comment by Ph-We** [comment]
@defstat , @NateWr , this may sound weird, but unfortunately nothing has changed in our instance of ojs 3.1.2 (test environment).
Also tagging @ppv1979

**Comment by defstat** [comment]
@Ph-We The stable3-1-2 branch has the changes - just added them to the master branch as well
@NateWr 

PRs
[pkp-lib]: #4755
[OJS]: pkp/ojs#2393
[OMP]: pkp/omp#674

**Comment by NateWr** [comment]
Merged. Closing. :+1:
