### ISSUE TITLE
Remove unvalidated new accounts after expiry

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4240]
See https://forum.pkp.sfu.ca/t/validation-timeout/49885

**Comment by kshawkin** [comment]
+1 to this issue.  We've seen thousands of accounts created that were never logged into, so it would be helpful for the system to purge these automatically.

Related to this: to reduce vulnerability to systems being compromised, it's a common practice to purge dormant accounts from a system--for example, if a user hasn't logged in for at least 12 months.  It would be great if OJS automatically emailed users after ], say, 12 months, giving them, say, 1 month to log in again to keep their account from getting deleted automatically at month 13.  I realize that deleting users from the system might cause other side-effects, so maybe the system would just disable the accounts instead of deleting them and only allowing re-enabling of an account by a journal manager.

**Comment by AndrewGearhart** [comment]
Some suggested language to clarify things a bit in terms of classifications for accounts:

| Status | Timedout | date_last_Login | date_validated | disabled |
| --- | --- | --- | --- | --- |
| active | False | != date_registered | != NULL | False |
| invalid | True | = date_registered | = NULL | True |
| disabled | False | != date_registered | != Null | True 
| inactive | False | +360 < today | != NULL | False |

- Timedout: Conditions of (today - date_registered) > validation_timeout AND date_validated = NULL
- inactive: theoretical status that has been raised several times for good reasons. However, this is out of the scope of this particular issue. This is what I would say is described by the second paragraph of https://github.com/pkp/pkp-lib/issues/4240#issuecomment-663294254

**Comment by touhidurabir** [comment]
Agree with not deleting the users who are considered as invalidated as that may have unforeseen impact on the system . Rather than deleting users/accounts, it's better to mark those as `invalidated` .  And by doing so, they can not login in into the system unless marked as `non invalidated` by the journal admin. To achieve that we can have a simple column in the `users` table something like `invalidated_at` which is a `timestamp` and set to `null`  by default.  

Also it will be better to have both the `notice period` and `grace time after notice` set in `days` and have the option to modify the values rather than have a strict number managed internally by the system . may be something like in the `config` file .

```
; maximum number of days for an account/user after the last login time has passed which will make it a possible target to 
; mark it as invalidated account and sent the notice mail/message
invalidation_targetable_time = 360

; maximum number of days after the notice mail that an account/user will be finally marked invalidated 
invalidation_grace_time = 14
```

Or it can be put in the `site settings` section but putting it in the `config` seems simpler option . 

Maybe we can have more options to handle the purge/delete feature of invalidated `accounts/users` in future but right now it may be bit too drastic .

**Comment by touhidurabir** [comment]
I believe we should have a `configuration` in the `config` file which specify is the if the current set up of the journal system should have unvalidated and expired user removed periodically . As this is a destructive level behaviour, I think each of the journal installation should have the ability to configuration it as their own need . By default it should be set to disable and only if admin feels like it , they should have it enable . 

so my proposal is to have a setting/configuration like below to push in the config file 

```
; remove all unvalidated and expired users after validation timeout
; delete_unvalidated_users = Off
```

and I think it should be put under the `general` section . 

@asmecher @NateWr what is your opinion ?

**Comment by AndrewGearhart** [comment]
@touhidurabir The difficulty with introducing another class of user ... is that all user screens need to then appropriately handle that type of situation. It is not uncommon to remove a user in pkp systems through a user merge. All attributed items then apply to the user that is left behind (for example, merging into the admin user). For example, currently, screens for sending mass emails currently include users which can no longer validate, have no role, and have never logged in. 

However, I don't believe that dormant accounts that have previously been active should be purged as suggested by @kshawkin . I'd like to suggest that could be a thing, but it should be a different issue.

**Comment by NateWr** [comment]
> The difficulty with introducing another class of user ... is that all user screens need to then appropriately handle that type of situation.

@AndrewGearhart I agree and for now the PRs just remove expired, unvalidated accounts. They don't introduce a new class of user. It probably makes sense for us to think about this more, but I'd like to see a separate issue and some specific use cases.

> `remove_expired_users = Off`

What about changing this to an `int` that specifies the number of days, with a falsey value being "off":

```
validation_period = 28
```

Personally, I think this should be on by default, with the option to turn it off. We tend to take a more paternal stance towards our community, encouraging what we consider the best defaults. And in this case I think it's good to keep things tidy, especially as this is currently the only way for journals to keep out a bunch of bot registrations.

Finally, @ctgraham has made a case for not introducing new config parameters, but using database-backed settings as much as possible. Clinton, do you want to argue for this being a site setting rather than a config option?

**Comment by AndrewGearhart** [comment]
@NateWr I'd be interested to see that discussion of using database-backed settings as I'd be interested in arguing against that unless there is a clear way to set those settings from the environment. This is what makes CI/CD so hard is when configuration is co-mingled with stateful data.

The idea of deleting the user rather than merging it seems dangerous. It should be fine, as I mentioned in a comment on the pr, but ... I'd be more comfortable with it being automatic and defaulted to on if it would standardize on merging to the lowest number user that is a system admin (group_id 1 if I remember correctly?) ... or, perhaps, a config setting.

**Comment by NateWr** [comment]
@AndrewGearhart I thought the discussion on database-backed settings was in #7068, but looks like it was in slack, where it has long since been lost to history. #7068 is probably the best place to have that conversation anyway.

**Comment by ctgraham** [comment]
Short answer on storing configuration in the database rather than config.inc.php: anything configured in config.inc.php requires filesystem and thus PHP access and could/should be restricted system administrators.  Generally, we should make anything which rationally can be managed by the user available to be managed by the user.  That is: a Journal Manager or Site Administrator in the software should be able to configure settings self-service, not depend on a System Administrator who has filesystem access.

Examples of settings which logically live in a System Admin's responsibility (config.inc.php is OK!): database settings, external system commands.

Pretty much everything else should logically live in a Journal Manager or Site Admin responsibility (get these out of config.inc.php!).  Yes, this adds challenges in automating deployments, but we need to do right by the user first.

**Comment by ctgraham** [comment]
For classifying *why* a user is disabled (and should be considered for removal), also consider: https://github.com/pkp/pkp-lib/issues/7857

**Comment by touhidurabir** [comment]
> Personally, I think this should be on by default, with the option to turn it off. We tend to take a more paternal stance towards our community, encouraging what we consider the best defaults. And in this case I think it's good to keep things tidy, especially as this is currently the only way for journals to keep out a bunch of bot registrations.

I am not sure we should have this enabled by default as this is a destructive behaviour and we are just about to ship this functionality if this PR get merged . Not sure what kind of impact this may have into the system or even to a modified installed version . So for now lets just leave this as an option for the admin to configure even it's an extra step they need to take . We can put this details in the doc (may be in the setup/install section) . 

> What about changing this to an int that specifies the number of days, with a falsey value being "off":

```
validation_period = 28
```

I think that can be good approach but only have this option can be confusing as this does not specify what it supposed to or what impact it can have. may be combining this option with what currently proposed 

```
; Remove all unvalidated and expired users after validation timeout.
; A user will consider as expired if the the validation is enabled and after the days passed off
; validation_timeout, the user has not validated. In the scenario when the require_validation has
; turned off, user will consider expired if has not logged in once past the days of validation_timeout
; since the day of registration.
remove_expired_users = Off
```
will probably make it more understandable . But again adding 2 options for one task is also seems like an overkill .

**Comment by NateWr** [comment]
Thanks @touhidurabir! I'll let Alec make the call on whether it is on/off by default.

I agree we don't want two config options if we can get away with one. On the config option name, I think that a good description would be enough to clarify what impact the option will have. To work off you're description, it would be:

```
; The number of days a new user has to validate their account
; A new user account will be expired and removed if this many days have passed since the user registered
; their account, and they have not validated their account or logged in. If the user_validation_period is set to 
; 0, unvalidated accounts will never be removed. Use this setting to automatically remove bot registrations.
user_validation_period = 28
```

Keeping the name of the config option as what it is (validation period) rather than what it does (remove expired users) will mean we can reuse it in the future. For example, if we wanted to send a reminder email to the user one week before the account was removed.

**Comment by asmecher** [comment]
> I'll let Alec make the call on whether it is on/off by default.

We have two scenarios to consider:

**1. Fresh installations that are created from scratch with the new version.**

In this case, I recommend adding a default to `config.TEMPLATE.inc.php` of something like 30 days. When the user installs the system, this value will be placed in `config.inc.php` by the install script.

**2. Users who already use OJS, and are upgrading to a version that supports this new option.**

When a user upgrades, they'll be given the release notes for the new versions they've upgraded through. These include notes on newly-added configuration options that they might want to add to the `config.inc.php` file. See for example [README-3.3.0](https://github.com/pkp/ojs/blob/stable-3_3_0/docs/release-notes/README-3.3.0#L7).

It's up to them to add these options and configure them how they want. This new option should be documented in [docs/release-notes/README-3.4.0](https://github.com/pkp/ojs/blob/main/docs/release-notes/README-3.4.0) (and that file should be synced with `docs/RELEASE`).

In the code, it's possible to configure a hard-coded default to `Config::getVar` in the [3rd parameter (`$default`)](https://github.com/pkp/pkp-lib/blob/main/classes/config/Config.inc.php#L39). This defines how it'll work for users who *don't* configure the new option in `config.inc.php`.

For these users I would recommend using a default of `0` so that "unvalidated accounts will never be removed" (as above). So for users who don't review their `config.inc.php` the function won't suddenly become active.

**Comment by touhidurabir** [comment]
@asmecher I have updated the PRs based on your feedback . now the removal process is on by default with `28` days set as default . wording as per @NateWr suggested as

```
; The number of days a new user has to validate their account
; A new user account will be expired and removed if this many days have passed since the user registered
; their account, and they have not validated their account or logged in. If the user_validation_period is set to 
; 0, unvalidated accounts will never be removed. Use this setting to automatically remove bot registrations.
user_validation_period = 28
```

@NateWr if this PR get merged , we need to update our doc so let previous users know about this option so that they can update existing installation.  what is the best approach to do that ?

**Comment by NateWr** [comment]
Thanks @touhidurabir! For the docs, can you add an issue to https://github.com/pkp/pkp-docs/issues? In the issue title, add "Release Notebook 3.4", and I'll know to include this into our next release notebook.

**Comment by asmecher** [comment]
Thanks, @touhidurabir!
I've reviewed your PRs:
- https://github.com/pkp/pkp-lib/pull/7890 (pkp-lib)
- https://github.com/pkp/ojs/pull/3385 (ojs)

**Comment by asmecher** [comment]
Looks good, @touhidurabir! Just one trivial (indentation) comment on the OJS PR. Could you port these to OMP and OPS `main`? Once they're all ready I can merge.

**Comment by touhidurabir** [comment]
@asmecher Full PRs list 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#4240 Remove unvalidated new accounts after expiry](https://github.com/pkp/pkp-lib/pull/7890)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#4240 Submodule Update ##touhidurabir/i4240_fix_main##](https://github.com/pkp/ojs/pull/3385)
[ops](https://github.com/pkp/ops) --> [pkp/pkp-lib#4240 Submodule Update ##touhidurabir/i4240_fix_main##](https://github.com/pkp/ops/pull/276)
[omp](https://github.com/pkp/omp) --> [pkp/pkp-lib#4240 Submodule Update ##touhidurabir/i4240_fix_main##](https://github.com/pkp/omp/pull/1113)

**Comment by asmecher** [comment]
All merged except the OJS PR (see https://github.com/pkp/ojs/pull/3385#issuecomment-1119895893).

**Comment by touhidurabir** [comment]
@asmecher I have added a comment for the `ojs`, please check it at https://github.com/pkp/ojs/pull/3385#issuecomment-1120245950 .

**Comment by touhidurabir** [comment]
@asmecher the merge conflict fixed for `OJS` `main`. I think you can merge it now .

**Comment by asmecher** [comment]
Merged, thanks!
