### ISSUE TITLE
Autosuggest for keywords metadata entry returns languages

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4264]
When entering keyword metadata, it will search for suggestions as you type. This search only returns languages. For example, if you type `ab`, the URL will be:

```
/submission/fetchChoices?list=languages&term=ab
```

**Comment by asmecher** [comment]
There are actually two issues here:
- [ ] The "languages" autosuggest source carries through to all subsequent keyword entries that don't specify a source
- [ ] There is apparently no autosuggest support for other metadata fields (including keywords)!

**Comment by asmecher** [comment]
Unfortunately the second part of this won't be possible until https://github.com/pkp/pkp-lib/issues/1550 is implemented. That's because keywords are not disambiguated, and are stored on a per-submission basis, so "hydrology" assigned to 15 articles means 15 "hydrology" strings stored in the database. I'll note this on the other issue. Closing this one, as the main bug is fixed.
