### ISSUE TITLE
Output of references within the frontend is inconsistent and not semantic

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4300]
c.f. https://forum.pkp.sfu.ca/t/extract-and-save-references-extra-line-spacing/49621

When citations have been parsed, they are displayed within `div.references div.value p`
When citations have not been parsed, they are displayed with `div.references div.value`, separated by `<br />`s.

https://github.com/pkp/ojs/blob/dd1d5fa17c709b3d140fc9d43af06c4ea6897a9c/templates/frontend/objects/article_details.tpl#L199-L205

Semantically, citations are a list.  We could display them consistently and meaningfully via:
`div.references div.value ul.parsed li` or `div.references div.value ul.unparsed li`, depending on whether they have been parsed.

**Comment by ctgraham** [comment]
Or maybe the whole point of passing the unparsed references through nl2br is that they are *unparsed* and we could have intentionally weird data, like something other than references one-per-line?

Then we might want to only have parsed references in a structured list, leaving the formatting of the unparsed references strictly to the `div.references div.value`.

**Comment by asmecher** [comment]
@NateWr, I assigned you to the PR on this one for a look, thanks!

**Comment by NateWr** [comment]
Hi @ctgraham! So, I am of two minds about this, mainly because of how little we know about the parsed and unparsed citations. 

Good that you avoided using an ordered list. Although references should ideally be ordered, in many cases the numbering will be included within the text, and we don't want something like `1. 1. Wright, N...`.

I think I recommended not using `<ul>` for references when this was first made, because we can't be sure that what we get back will correctly map to a list. Extra spaces will, for example, map to empty list items, which in turn will lead to inaccurate reference counts (I believe a screenreader will tell a user how many items are in a list). 

Also, I reckon that we will encounter cases where people are doing other things with their references, like:

```
Patrick, S "Some article" ...

Wright, N "My First Article" ...

---- "My Second Article" ...

---- "My Third Article" ...

Yeru, P. "Some thing" ...
```

In such cases, I'm not sure if the semantics of a list are clear and could be construed as inaccurate.

I'm sure that lists will be an appropriate markup for 85%+ of the cases, but this is where running a distributed platform where we don't know the output is tricky. My personal feeling is that the drawbacks of incorrect semantics are more significant than the gains of correct semantics, so in such cases where it is correct most of the time but sometimes not, I tend to err towards a more generic markup.

I really can't say for sure what is best here, but if we go with a list, can I suggest a few things?

- Let's only apply lists to the parsed citations. Parsing is a deliberate step in the workflow, Presumably, an editor who is parsing references is also checking to make sure they look ok. When it's not parsed, we can fallback to making no assumptions about it.
- Let's apply the list HTML in the parsed output in the backend too. That way we can better mirror the backend presentation and the frontend presentation.
- Can we make any assumptions about nested references and handle them better as nested-lists? I'm wondering if we can detect references that begin with dashes (long, em or otherwise) or multiple spaces, and transform them into nested items?

**Comment by neffe** [comment]
We're hosting over 150 journals and each journal have their own output style, MLA, APA, Chicago, etc so its very important that OJS avoids changing the chosen style when using ‘Extracted References’. Can't you make a setup that respects the original settings?

**Comment by NateWr** [comment]
@neffe I'm not sure that this is related to the issue. I don't think we're planning here to change the CSL format (MLA, APA, Chicago, etc) of the extracted references. We're only talking about how each reference is identified in the HTML code.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
