### ISSUE TITLE
OJS 3 MetaData form freezes when required keywords missing

### ISSUE THREAD

**Issue by cpockett** [pkp/pkp-lib#4338]
When I set keywords to be enabled, submission form, and required. When an author fails to submit a keyword then the form freezes. I've found that the following error is generated by the ajax request 

`<br />
<b>Warning</b>:  array_key_exists() expects parameter 2 to be array, null given in <b>/var/www/html/ojs/lib/pkp/classes/submission/PKPSubmissionMetadataFormImplementation.inc.php(72) : runtime-created function</b> on line <b>1</b><br />
{"status":true,"content":"...}`

I've fixed this by modifying the the following line /www/html/ojs/lib/pkp/classes/submission/PKPSubmissionMetadataFormImplementation.inc.php(72)
`$this->_parentForm->addCheck(new FormValidatorCustom($this->_parentForm, $key, 'required', $requiredLocaleKey, create_function('$key,$form,$name', '$data = is_null($form->getData(\'keywords\')) ? [] : $form->getData(\'keywords\'); return array_key_exists($name, $data);'), array($this->_parentForm, $submission->getLocale().'-'.$key)));`

I apologize in advanced if I should have formatted this better. I don't usually submit changes. I could probably submit a pull request though I am not overly familiar with the process to be honest.

**Comment by asmecher** [comment]
Thanks, @cpockett. FYI, we recommend directing warnings/errors to the log file rather than the browser -- that will prevent cosmetic warnings from breaking the site (and is recommended for PHP production use anyway). In any case, it is also good to clean up the warnings. I've committed a change nearly the same as your suggestion, though a little briefer -- an `(array)` cast. A `null` value cast to `(array)` is an empty array so that should work.
