### ISSUE TITLE
Users in multicontext install are offered links to unprivileged contexts

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4340]
See:
https://forum.pkp.sfu.ca/t/the-current-role-does-not-have-access-to-this-operation-to-new-users/50579

>I am using ojs 3.1.1-4 after upgrade 2.4.8. I create a user and assing the rol of manager of a journal. When the user sign in and click on Dashboard the message is The current role does not have access to this operation.

>I have created a journal and a user with manager permissions in that journal. But in the control panel all the journals of the site appear even though they do not have permits. Should not one appear?

Dashboard should either link to an available dashboard, or be suppressed in the Site context.

Site navigation menu should only offer contexts in which the user has permissions.

**Comment by ctgraham** [comment]
Problem seems to be here:
https://github.com/pkp/pkp-lib/blame/master/classes/context/ContextDAO.inc.php#L185-L189

Per that SQL, an "Available" context is one of:
* a enabled context
* a context in which the user is a member of user group
* anything, if the user is a site admin

Rather, an "Available" context should be:
* if no user, an enabled context
* if a user:
  * anything, if the user is SITE_ADMIN
  * any context in which the user is a member of user group

This function appears to be used:
* [lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.inc.php:51](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/controllers/grid/notifications/NotificationsGridCellProvider.inc.php#L51): `$contexts = $contextDao->getAvailable($user?$user->getId():null)->toArray();`
* [lib/pkp/classes/template/PKPTemplateManager.inc.php:388](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/template/PKPTemplateManager.inc.php#L388): `$workingContexts = $contextDao->getAvailable($user?$user->getId():null);`
* [lib/pkp/classes/handler/PKPHandler.inc.php:489](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/handler/PKPHandler.inc.php#L489): `return $contextDao->getAvailable($user?$user->getId():null);`
* [lib/pkp/classes/services/PKPNavigationMenuService.inc.php:256](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/services/PKPNavigationMenuService.inc.php#L256): `$workingContexts = $contextDao->getAvailable($user?$user->getId():null);`
  * [controllers/tab/settings/WebsiteSettingsTabHandler.inc.php:50](https://github.com/pkp/ojs/blob/f1ea332b19ac9611028946021a214d263cdf9697/controllers/tab/settings/WebsiteSettingsTabHandler.inc.php#L50): `$workingContexts = $this->getWorkingContexts($request);`
  * [lib/pkp/controllers/page/PageHandler.inc.php:187](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/controllers/page/PageHandler.inc.php#L187): `$workingContexts = $this->getWorkingContexts($request);`
* plugins/reports/counter/classes/CounterReport.inc.php:270:              $availableContexts = $contextDao->getAvailable();

A cursory review suggests that each of these, when given a userId, expects to describe the actual working contexts for the user.  I think changing this core function is safe.

**Comment by ctgraham** [comment]
The problem for case 1 is that when [`PKPNavigationMenuService::getDisplayStatus()` calls `PKPUser::hasRole()`](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/services/PKPNavigationMenuService.inc.php#L271-L289) for a CONTEXT_SITE (value: 0), `RoleDAO::getByUserId()` has [interpreted `$contextId` of 0 as `false`](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/security/RoleDAO.inc.php#L144), returning roles regardless of context.

Correcting this in `RoleDAO::getByUserId()` could be risky, if other use cases are assuming this `0 == false` equivalency.

**Comment by ctgraham** [comment]
Side note: how does `$isAdmin = $currentUser->hasRole(array(ROLE_ID_MANAGER, ROLE_ID_SITE_ADMIN), $context->getId());` work for the Site Admin?

[`PKPUser::hasRole()` calls `getRoles()`](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/user/PKPUser.inc.php#L357) for a context id, [`getRoles()` caches the roles](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/user/PKPUser.inc.php#L388) for that context id, and [`getByUserId()`](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/security/RoleDAO.inc.php#L140-L146) will explicitly use the context.  But the site admin is not a site admin in every context, right?

**Comment by bozana** [comment]
@ctgraham, maybe to provide the list of all PRs for this issue, so the user can more easy find the needed patch?

**Comment by ctgraham** [comment]
Right now I've only proposed a single PR for half of this issue (and [even this is incomplete](https://forum.pkp.sfu.ca/t/the-current-role-does-not-have-access-to-this-operation-to-new-users/50579/6)).

What do you think of the [problem in case 1](https://github.com/pkp/pkp-lib/issues/4340#issuecomment-451257524)? Is the formulation `$user->hasRole(array(ROLE_ID_MANAGER, ROLE_ID_SITE_ADMIN), $context->getId());` really inherently wrong?

**Comment by bozana** [comment]
At the first glance it seems you are right, but I will take a more detailed look... and will then come back again... :-)

**Comment by bozana** [comment]
Hi @ctgraham and all :-)
I will go step by step to try to understand everything here.
Thus, my first comment, looking first only at one of the questions here:

> Side note: how does `$isAdmin = $currentUser->hasRole(array(ROLE_ID_MANAGER, ROLE_ID_SITE_ADMIN), $context->getId());` work for the Site Admin?
> 
> [`PKPUser::hasRole()` calls `getRoles()`](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/user/PKPUser.inc.php#L357) for a context id, [`getRoles()` caches the roles](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/user/PKPUser.inc.php#L388) for that context id, and [`getByUserId()`](https://github.com/pkp/pkp-lib/blob/f555a26a10146d0156d7686e52bba50737f1a75e/classes/security/RoleDAO.inc.php#L140-L146) will explicitly use the context. But the site admin is not a site admin in every context, right?
> 
> Perhaps users are adding the [Site Administrator as a Journal Manager](https://forum.pkp.sfu.ca/t/why-i-cant-see-options-with-user-admin/26709/6?u=ctgraham) in each Journal? Is this intended functionality? I suspect each instances of:
> 
> ```
> $user->hasRole(array(ROLE_ID_MANAGER, ROLE_ID_SITE_ADMIN), $context->getId());
> ```
> 
> should be:
> 
> ```
> ($user->hasRole(array(ROLE_ID_MANAGER), $contextId) || $user->hasRole(array(ROLE_ID_SITE_ADMIN), CONTEXT_ID_NONE))
> ```

Yes, admin user is always automatically added as journal manager to each newly created journal. This can be changed only by the admin user, by editing the user admin. Thereby, the admin user could unassign the journal manager role for himself/herself, but at least one role has to be assigned for the admin user for a journal. This could theoretically be also only the author role.
I assume that no admin user will remove journal manager role for himself/herself. Is there a case where this is wished, maybe @asmecher and @jmacgreg? 
Assuming that that journal manager role will not be removed, the call `$user->hasRole(array(ROLE_ID_MANAGER, ROLE_ID_SITE_ADMIN), $context->getId());` is probably not wrong i.e. probably not leading to problems (because it will always be true, the admin user will always have the journal manager role for a journal). However, the call is not fully correct and thus I would also think that the call should be changed to `($user->hasRole(array(ROLE_ID_MANAGER), $contextId) || $user->hasRole(array(ROLE_ID_SITE_ADMIN), CONTEXT_SITE))` -- Wherever the call `$user->hasRole(array(ROLE_ID_MANAGER, ROLE_ID_SITE_ADMIN), $context->getId());` is used it is surely expected/wished that the admin user has the access, else ROLE_ID_SITE_ADMIN would not be there -- i.e., lets say in the strange case when the admin user would only have author role for a journal, at the places in the code where this calls occur it is surely expected that the site admin would have the access. @asmecher, would you agree?

I will continue investigating the other issues/problems/questions from this issue...

**Comment by NateWr** [comment]
Uff. I am guilty of introducing the `$user->hasRole()` pattern. It goes against our whole architecture for how we're separating entity classes from DAOs. It was a mistake and I'd like to see it's usage refactored away in favor of the service class method: `UserService::userHasRole()`.

I also agree that when checking `ROLE_ID_SITE_ADMIN` we should explicitly check it against `CONTEXT_SITE`, as @bozana describes here:

```php
($user->hasRole(array(ROLE_ID_MANAGER), $contextId) || $user->hasRole(array(ROLE_ID_SITE_ADMIN), CONTEXT_SITE))
```

I am just discovering `CONTEXT_SITE` for the first time. What is the difference with `CONTEXT_ID_NONE`? In what cases would we use one or the other? If they are the same, let's consolidate the constants to `CONTEXT_SITE`.

Regarding the two specific cases mentioned in @bozana's last message:

1. `PKPSubmissionService::canCurrentUserDelete()` appears to be wrong (I wrote it). Instead of pulling the context ID from the request to check if the current user can delete a submission, we should be pulling the context ID from the submission itself, and checking the user's roles against that context/submission.

I can imagine a future scenario where we have site-wide admin tools that allow a submission to be deleted from outside of the context in which it was submitted.

2. Here, too, I think the code is messy and confusing (I also wrote this, or at least much of it). It is easy to miss, but if it is called without a context (`$journal`) this assertion will fail:

https://github.com/pkp/citationStyleLanguage/blob/master/pages/CitationStyleLanguageHandler.inc.php#L91

This code, which I copy-paste everywhere, is redundant in this case:

```php
$context = $request->getContext();
$contextId = $context ? $context->getId() : 0;
```

Because this is a `PageHandler`, I think it's ok to require a request context here and to 404 if one doesn't exist. However, I can imagine a future scenario where the citation might be requested from the site context.

I'd like to move away from our habit of retrieving the context ID from the `Request`. We should not assume that the requested context is the same as the context of the object we are requesting, or the permission set we need to acquire to take an action. 

As we move to better support publishing service providers (ie - people running many journals), we are likely to build more cross-context editorial and admin tools. When we do so, we will constantly run up against problems where we have assumed the request context is the most appropriate context to use for permission checks, when in fact it should often be the context of the object being manipulated.

The `Service` classes that have been introduced try to follow this principle by expecting the context to be injected into it's methods. Obviously that's not entirely consistent. But where it is not, it should be changed.

I don't know if this helps you solve this issue or just makes it a lot more complicated. But that's my thinking on the issue and I think we're very happy to see authorization issues solved by deeper refactoring.

**Comment by bozana** [comment]
@NateWr, user->hasRole is OK, it is rather RoleDAO::getByUserId that is buggy... 
Thanks for the explanation/comments -- they help! :-)

If everybody agrees, I would suggest just fixing the RoleDAO::getByUserId, those two 'problematic' cases, as well as using always `$user->hasRole(array(ROLE_ID_SITE_ADMIN), CONTEXT_SITE)` (to be more accurate) for now, for the next release 3.1.2, and then do some other refactoring in the master for the 3.2.

**Comment by bozana** [comment]
@ctgraham, shall I do these changes?

**Comment by bozana** [comment]
@ctgraham, could you maybe take (and eventually test) the PRs? -- I think all issues from here should be solved now...
@NateWr, maybe you would like to check/see the changes too?

**Comment by NateWr** [comment]
Had a quick look and everything looks good to me. :+1:

**Comment by bozana** [comment]
merged, thus closing...
