### ISSUE TITLE
Use jobs to send new issue published email notifications

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4343]
**Describe the problem you would like to solve**
When publishing a new issue, it is possible to send an email notification to all users. However, if the journal has a lot of users it can take hours to send all of the emails. The loading spinner doesn't show what's happening, so the editor will presume something is broken.

**Describe the solution you'd like**
Create jobs to send the emails, rather than sending them synchronously when the issue is published. This way the editor does not need to wait for the emails to be sent to finish their work.

**Who is asking for this feature?**
Editors of journals with lots of registered users. Especially those who use SMTP, because the emails are sent one-by-one in the same request.

**Additional information**
This issue has been edited from the original, which is below:

> A journal with a lot of user accounts reported that when they sent a notification of a new issue published, a spinning wheel displayed for hours, with no indication of how many messages were sent or still needed to be sent.  They suggested it would be helpful to display a progress bar or something similar to indicate when they can safely close the browser without interrupting the notification.

**Comment by ajnyga** [comment]
Do you have a rough estimate of the number of accounts? Is this the first time they notice the problem?

I find it bit hard to believe that the code would spend hours to send the emails even with a lot of accounts?

**Comment by ajnyga** [comment]
I quickly checked one of our larger journals and they have 7609 users. I am fairly sure that they would had reported if anything like this happened.

Someone who know email servers and the mail library better can maybe say can the email server create limitations on how fast the code works. My thinking is that php will just push the emails to the server and they end up in a queue there which is then processed sooner or later.

**Comment by ajnyga** [comment]
Also important question: did the wheel stop spinning at some point, or did they just close the window?

**Comment by asmecher** [comment]
@ajnyga, my experience is that local delivery (`mail()`) is pretty quick and is probably just queuing up content for later delivery, where as SMTP tends to take a lot longer and seems to be actively delivering the mail before returning. Are you using local delivery?

**Comment by amandastevens** [comment]
The wheel did not stop spinning, they just eventually closed the window. 

I'm going to call @mfelczak in to address the mail server questions.

**Comment by ajnyga** [comment]
Sounds like something else was failing and is maybe visible in the error log.

**Comment by jnugent** [comment]
The same issue has occurred to a PKP|PS hosted journal last week, with a little more than 1400 registered users.  Same thing - new announcement, emails went to a lot but not all users, and the assistant editor who created the announcement eventually closed the window after an hour.  From log investigations it looks like the announcement went out to 1100 of those users, but there is nothing indicative of a problem in the site error log.  We have the date the announcement was created, but the logs from that day show no errors for the UserDao (which fetches all of the users in the context for announcements), mail() errors, problems with the Announcement form, Notification Manager, or issues with PHP hitting a max runtime.  The journal has 18 disabled users, but the notification manager skips those when sending the notification mail.

**Comment by asmecher** [comment]
(Should be implemented as part of https://github.com/pkp/pkp-lib/issues/3646)

**Comment by alexxxmendonca** [comment]
This happens at the SciELO install too and it's a big problem when it happens.

We use Gmail for sending our OJS e-mails and Gmail has a policy that after 500 continuous sendings, it stops sending messages until the next day (00:01 am).

This is huge problem because it ends up affecting the other journals too, journals that didn't send the issue notification message in the first place are affected by this -- they stop receiving e-mails.

We even sent out a message to all our journals asking them to uncheck the option whenever publishing an issue -- given that the option is checked by default.

The progress bar suggestion is really good, but I would also suggest:

1) leave the box _unchecked_ by default.
2) add a "cancel" button at the progress bar so that journals with huge number of users may opt out of sending it mid-way.

**Comment by mfelczak** [comment]
One additional note for consideration here based on some recent undelivered mail from OJS to Gmail accounts that I suspect will be similar for other mail providers. If the volume and rate of outgoing email is too high, the recipient mail service may start to reject incoming mail or begin to flag it as spam. This suggests that we may need to rate limit or throttle outgoing email.

When Gmail detects too much incoming email, it reports the delivery failure and directs site admins to the following:
https://support.google.com/mail/answer/81126

The relevant section includes the following:

### Increase sending volume slowly

If you send many messages, we recommend you:
-  Send mail at a consistent rate. Avoid sending mail in bursts.
-  Start with a low sending volume, then slowly increase the volume over time.
-  As you increase the sending volume, regularly monitor the sending rate and any responses you get. Regular monitoring lets you turn down the sending volume when the sending rate is limited, or when you start seeing errors.

Important: Increasing the sending volume too quickly can result in delivery problems.

These factors affect how quickly you can increase sending volume:

- The amount of email sent: The more email you send, the more slowly you should increase sending volume.
- The frequency of sent email: You can increase the sending volume more quickly when you send daily instead of weekly.
- Recipient feedback about your messages: Make sure you send only to users who subscribe to your emails, and give users an option to unsubscribe.

**Comment by NateWr** [comment]
In 3.4 we will introduce a job runner, which can take long-running jobs like this off of the main request. This will prevent the editor from having to wait for all emails to be sent, so no progress indicator is needed.

I have updated the original description to reflect this.

**Comment by touhidurabir** [comment]
I think this issue already got resolved by @Vitaliy-1 and implemented the best possible approach possible (that is through job batching), check at https://github.com/touhidurabir/ojs/blob/main/classes/controllers/grid/issues/IssueGridHandler.php#L599-L621 . 

Still one problem lies at how job get executed . @NateWr mentioned about `Job Runner` but I think for this kind of jobs, we need it to be dispatched and maintained by a `queue worker thread` . we have both the job runner and queue worker implemented as the part of pkp/pkp-lib#7105 but for this kind of long running task, `JobRunner` will never be the right and efficient choice . And when considering the original issue case mentioned (for thousands of users), it will have more confusing impact as JMs/Editors will see it get done immediately but jobs will run on web request which may take a long time to complete . So basically now we need to figure out how to handle batch job efficiently which can be addressed by pkp/pkp-lib#8305 . 

As the scope of this issue got already resolved, I am closing this one . But if anyone thinks that there is still work need to get done or left, feel free to re-open it and propose the require modifications .
