### ISSUE TITLE
"Cancel" on "Are you sure you wish to leave the page" behaving badly

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4352]
See https://forum.pkp.sfu.ca/t/ojs3-continue-without-saving-modal-wont-cancel/50711/10.

To reproduce:
- Go to the user's Profile page (e.g. Contact tab)
- Edit a field
- Click another tab
- Press "Cancel"

On Firefox, another confirmation modal pops up immediately (then no further ones).
On Chromium, I get endless modals for as long as I care to hit Cancel.

**Comment by asmecher** [comment]
@NateWr, I spent a few minutes on this myself, but I'm spinning my wheels. It appears to me that the `confirm` pop-up itself is causing an extra beforeActivate on the tabs. I'm afraid this is probably related to our own `Handler` interventions on event handling etc., since a stock `.tabs()` implementation doesn't seem to suffer the same problem.

**Comment by NateWr** [comment]
It looks like I introduced this bug with the fix for https://github.com/pkp/pkp-lib/issues/1787. I have implemented a (hopefully) better fix for that issue which also resolves this one.

I see this is pegged to the 3.1.1-5 milestone. @asmecher I have backported to `stable-3_1_2` but should I also do `ojs-stable-3_1_1` and `omp-stable-3_1_1`?

PR:
https://github.com/pkp/pkp-lib/pull/4358
https://github.com/pkp/pkp-lib/pull/4359 (stable)

Tests:
https://github.com/pkp/ojs/pull/2239

**Comment by NateWr** [comment]
@asmecher Ready for review.

**Comment by asmecher** [comment]
Looks good, @NateWr, please go ahead on all fronts. Note that this'll require a JS recompile, but I can take care of that if your setup makes it a pain.

**Comment by NateWr** [comment]
All merged! @asmecher I don't have the closure libraries installed to compile the main library, so if you can do that, that'd be great!

**Comment by asmecher** [comment]
All compiled and committed! (`ojs-stable-3_1_1`; `ojs-stable-3_1_2`; `omp-stable-3_1_1`; `omp-stable-3_1_2`; OJS `master`; OMP `master`)
