### ISSUE TITLE
Allow journal editors to be automatically assigned to submissions in a section

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4457]
Section settings can be used to assign section editors, but not journal editors.

There has been a request whether assigning journal editor role could also be automatic. Is there a reason why this could not be considered?

**Comment by ajnyga** [comment]
A broader idea: why not allow automatic assignment for all user roles. Meaning that you could choose from section settings also an automatic assignment for copyeditors etc.?

**Comment by librariam** [comment]
+1 from PKP|PS re adding an option to assign JEs. 

This would also help resolve confusion arising from this little known behaviour (OJS 3.1.2.0). If there is only one account in the JE role, the system will assign all submissions to that account by default. As soon as you add another account to the JE, submissions will no longer be assigned automatically. Quite confusing for someone who used to be auto-assigned and it suddenly stops without them understanding why.

(Same used to be true for a single SE account, but looks like it was taken care of by [#2313](https://github.com/pkp/pkp-lib/issues/2313))

**Comment by eczheng** [comment]
+1

**Comment by NateWr** [comment]
I've implemented this for 3.4 as part of #7191, in part to resolve the confusion that @librariam describes from the sometimes-automatic-assignment-sometimes-not behaviour. Now journals select who to assign to a new submission and nothing is done automatically.

![editorial-assignments](https://user-images.githubusercontent.com/2306629/187650359-5417bcd6-b1dc-4394-a7ac-fd9ff7d5de4b.png)

This is the same for sections and categories.

This does not support copyeditors and layout editors, because separate functionality would be needed to determine _when_ to assign them. If this is desired, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.

**Comment by NateWr** [comment]
@emmauhl this may effect documentation.
