### ISSUE TITLE
new names fields don't write correctly to Crossref export 

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#4460]
If you only put in an author's ``given-name`` but not a family name, the crossref export will write ``given-name`` to the ``<surname>`` field in the crossref export. 

It writes as intended, however, in the native import/export. 

Related to #2958

**Comment by bozana** [comment]
@AhemNason, we do not have any other possibility to solve this, because the Crossref element surname is required, so if we only have the given-name, we have to provide it in the required element surname.
S. also this document for more explanation how we proceed in which case/export/service in some 'special' name cases.https://docs.google.com/document/d/17oAPcCTL3tc7MhlcHpyVekv6_AxTHDc6BirHD3lVtJA/edit
Thus, I will close this for now, till no other solution is proposed/found...
