### ISSUE TITLE
File can't be downloaded

### ISSUE THREAD

**Issue by lilients** [pkp/pkp-lib#450]
In the newest OMP Version (1.1.1.1) there seems to be a bug: an uploaded and approved file appears at the catalog book page but there is an error, when you want to download the file: "Invalid publication format specified". When the checkbox for the metadata of the according publication format is set, the file can be downloaded.
In older versions you could add the file to download without the metadata displayed.

**Comment by asmecher** [comment]
@lilients, where are you downloading the file from? Is this via the public reader's interface?

**Comment by lilients** [comment]
sorry, that wasn't clear: yes the file of the publishes book at the public reader interface.

**Comment by asmecher** [comment]
Would you be willing to provide me with a database dump and the ID of the monograph you're working with? alec at smecher dot bc dot ca

**Comment by lilients** [comment]
We installed a development version to test the current release of OMP: http://dev.langsci-press.org/index.php/test. There is only one document at the catalog: http://dev.langsci-press.org/index.php/test/catalog/book/3. I will create an account for you to test.

**Comment by asmecher** [comment]
Hi @lilients -- thanks for the details. The problem is that the publication format itself isn't approved for inclusion in the catalog, even though the submission and file both are. In this situation the file shouldn't be listed in the catalog. See the checkbox labeled "Include the metadata for this publication format in the catalog entry for this book" in the Catalog modal; the patch attached here will prevent listing of the file unless this checkbox is checked.
