### ISSUE TITLE
Plugins that don't have any function at the site level should not appear in the site-wide plugins list

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4501]
Examples:
- Browse Block
- Information Block

**Comment by bozana** [comment]
Maybe to consider this issue as well: https://github.com/pkp/pkp-lib/issues/1923

There is maybe a need to enable (and eventually configure) plugins in the site settings plugin list, so that they are e.g. enabled (and eventually configured) for all contexts (in the same way). This is maybe to handle differently from the displaying/using the plugin on the site level.

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
