### ISSUE TITLE
[OJS3] Cannot use comma (,) when manually editing user Reviewing interests

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#4518]
When using a comma in Reviewing interests field of a user record, the comma as the same effect as saving the Reviewing interest.

Repro step
On OJS TestDrive https://demo.publicknowledgeproject.org/ojs3/testdrive/
Connect as admin
Go to Users & Roles
Clic on "Edit user" for "Test Reviewer" user
Clic on More user details
In Reviewing interests field, type manually Hébert, Anne

When you type "comma" Hébert will be save as a research interest. 

Note: when using Copy/past, teh problem does not occur.

**Comment by asmecher** [comment]
@pilasou, that's an issue with the third-party tag-it library we use to permit keyword entry; for a variety of UI/UX reasons (particularly the fact that the keycode for `,` is used for other purposes in different locales) we would probably replace it with something else in order to gain more control over the separator. See some discussion over here: https://github.com/pkp/pkp-lib/issues/3404
