### ISSUE TITLE
escape URL found in a citation for html href attribute

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#4549]
s. https://forum.pkp.sfu.ca/t/links-in-references/51651

**Comment by bozana** [comment]
PRs:
stable-3_1_2: 
pkp-lib: https://github.com/pkp/pkp-lib/pull/4550
ojs: https://github.com/pkp/ojs/pull/2313 (only submodule update)
omp: (only submodule update)

master:
pkp-lib:
ojs: (only submodule update)
omp: (only submodule update)

**Comment by bozana** [comment]
@asmecher, could you please take a look at this change? Thanks!!!

**Comment by asmecher** [comment]
@bozana, are you sure you want the `rawurlencode` within the `href`? It looks like if you pass in...

    http://www.some-url.com

...you'll get...

    <a href="http%3A%2F%2Fwww.some-url.com">http://www.some-url.com</a>

**Comment by bozana** [comment]
@asmecher, no, I am not sure :-\ but I would need to somehow escape the 'special' characters, e.g. "<" and ">". What else I could use? Would htmlspecialchars be the better solution (for URLs)? Hmmm... :-\

**Comment by asmecher** [comment]
I think the issue here is that the URLs are actually invalid, i.e. the `<`, `>`, etc. are unescaped. See https://perishablepress.com/stop-using-unsafe-characters-in-urls/ for some info about this including links to the RFCs. I can see some pretty big inconsistencies in how this is handled over at Wiley -- for example, from the article page:

    https://onlinelibrary.wiley.com/doi/abs/10.1002/%28SICI%291097-0266%28199911%2920%3A11%3C1037%3A%3AAID-SMJ67%3E3.0.CO%3B2-2

...you can see the URL displayed in text form:

    https://doi.org/10.1002/(SICI)1097-0266(199911)20:11<1037::AID-SMJ67>3.0.CO;2-2

...but the *actual* HREF in the link is encoded properly:

    https://doi.org/10.1002/(SICI)1097-0266(199911)20:11%3C1037::AID-SMJ67%3E3.0.CO;2-2

...which redirects to...

    https://onlinelibrary.wiley.com/doi/abs/10.1002/%28SICI%291097-0266%28199911%2920%3A11%3C1037%3A%3AAID-SMJ67%3E3.0.CO%3B2-2

So I think the problem in the original post is that the URL is encoded incorrectly, possibly grabbed from the text version on the page, which is formatted for better readability but is actually wrong.

**Comment by asmecher** [comment]
(Deferring to 3.2 for consideration)

**Comment by NateWr** [comment]
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.
