### ISSUE TITLE
Catalog Category page: article galleys require payment/subscription but are open

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4593]
On my OJS 3.1.2 instance, I've enabled subscription but gave free access to articles. 
As a result on the catalog category page, I see a notice that article galleys require payment to be accessed. 

The issue is because catalogCategory template includes article_summary template while not assigning [$hasAccess variable](https://github.com/pkp/ojs/blob/master/templates/frontend/objects/article_summary.tpl#L77). The next line here also fails as an article has accessStatus is `ARTICLE_ACCESS_ISSUE_DEFAULT`, not open access. Does it make sense?

**Comment by asmecher** [comment]
@Vitaliy-1, I've applied a change to cause the category listings to behave the same way as the search results listings -- i.e. to suppress the listing of galleys until you reach the article summary page. This works around an underlying limitation of the way we're fetching submission access status; to improve this so that access status can be shown on search results or category listings (or anywhere that we might list articles from different issues together) will require some rewriting that's best done in the `master` branch.
