### ISSUE TITLE
Submission Subtitle not searchable

### ISSUE THREAD

**Issue by Stefanvdb** [pkp/pkp-lib#4647]
In OJS3 Subtitle was added to Submissions, but this field is not searchable.
Pull requests will follow.

**Comment by Stefanvdb** [comment]
I hope I follow the correct workflow, as this is my first pull-request to the project.  
I added these 2 pull-Requests: 

https://github.com/pkp/pkp-lib/pull/4648
https://github.com/pkp/ojs/pull/2352

**Comment by asmecher** [comment]
@Stefanvdb, just one small comment on the pull requests. They were prepared well, thanks!

More broadly, though, I wonder about whether it's worth keeping the subtitle indexed separately from the main part of the title. Since users are unlikely to search the subtitle separately from the title, it might make sense to have the full title (subtitle and title) indexed in `SUBMISSION_SEARCH_TITLE` instead. To do that, use `Submission::getFullTitle` when indexing into `SUBMISSION_SEARCH_TITLE`.

**Comment by Stefanvdb** [comment]
@asmecher, I agree that it makes more sense to index the full title into `SUBMISSION_SEARCH_TITLE`. Comitted changes, also fixed an issue in `Submission::getFullTitle`

**Comment by asmecher** [comment]
Great, @Stefanvdb! I've merged this; thanks for contributing.
