### ISSUE TITLE
Group archive issues by year (as in OJS2)

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#4667]
OJS2 used to group archived issues by year.

A solution to restore that behavior has been posted in the forum:

https://forum.pkp.sfu.ca/t/ojs-3-archives-group-by-year/28848/17

It's an update for file `templates/frontend/pages/issueArchive.tpl`

I'd appreciate if that modification could be 
incorporated into an official release, please.

**Comment by asmecher** [comment]
@fgnievinski, would you be able to turn that into a PR for review?

**Comment by fgnievinski** [comment]
sure, here it is:

https://github.com/pkp/ojs/pull/2359

**Comment by asmecher** [comment]
Thanks, @fgnievinski! @NateWr, I've assigned you for a look.

**Comment by NateWr** [comment]
Hi @fgnievinski, this would be a popular change. But I think we need to look into a theme option or something to make it optional. This change would effect thousands of journals, many of whom may only publish one issue per year or may not want their issues organised in this way.

Also, I think we should go through a bit of a design phase where we think through the UX of what we're trying to do. Often, the issue summary will include the year, so having a second yearly heading could prove redundant. And we should also consider whether a navigation list of years would be a better solution to the use-cases we're trying to address.

I'm going to flag this up with our theme team, but I'd be curious to hear from you and anyone else some more details about the particular use-cases that you want to address here. Is this for users who know what year they're looking for and want to find a particular issue for that year? Or for users to have more situational awareness as they're browsing a long list of issues?

**Comment by fgnievinski** [comment]
Hi @NateWr, thanks for your input.  Our use case is a bit blunt: Scopus indexing requires regularity (periodicity), so we'd like to demonstrate clearly that we have a fixed number of regular issues per volume (year). Plus we recently migrated from OJS2, so our users got used to seeing issues grouping by year.  Do you think this would be doable using the [theme options API](https://docs.pkp.sfu.ca/pkp-theming-guide/en/theme-options-api)?

**Comment by NateWr** [comment]
Thanks @fgnievinski! We've scheduled a discussion with the theme team and I think we'll aim for something.

In the meantime, you can implement your change directly in your down theme, by overwriting the `frontend/pages/issueArchive.tpl` template. If you're not using your own theme yet, you can create a child theme with just the template file to keep your changes separate.

You can learn more about template overrides and child themes in the [theming guide](https://docs.pkp.sfu.ca/pkp-theming-guide/en/).

**Comment by fgnievinski** [comment]
Thanks @NateWr, I'll play with the child themes!

**Comment by NateWr** [comment]
During the Barcelona sprint, a few of us did some research on this internally and worked together to identify the key use cases we want to serve on the issue archive page. We decided we want to give editors two choices:

1. Should issues be grouped by year, volume or not at all?
2. Should issue covers be prominently displayed or not?

These choices could be put into options for the default theme and it can present different issue archive pages depending on each option.

With that in mind we did some preliminary mockups. In this mockup, the issues are grouped by year and volume, and they work like tabs. Clicking on a year "2019 -- Volume 2" will show all issues from that year _without_ waiting for a new page load.

![side-tabs](https://user-images.githubusercontent.com/2306629/69659826-f329a700-1076-11ea-987a-132c56d62ff6.JPG)

In this mockup, the issues are similarly grouped but appear in an accordion display in which the group names appear inline with the issues, and you can toggle the groups open/closed. This provides a more dense display which may work better for journals that have very little issue information and never use cover images.

![accordion](https://user-images.githubusercontent.com/2306629/69659918-23714580-1077-11ea-9263-4f6ceaa9d669.JPG)

These mockups support the most common use case, in which issue cover images are not used or are not a key part of the issue package, either because issue cover images are all similar or because resources are not invested in good-looking covers. In such cases, the issue details can be shown with or without the cover image without having a big impact on the UX, as below.

![issue-details](https://user-images.githubusercontent.com/2306629/69660041-63382d00-1077-11ea-8d0d-5139f97aaffb.JPG)

In the mockup below, we show an issue archive page designed to highlight cover images. This would work best in cases where a journal invests significant resources in attractive, distinctive covers. It could work with or without grouping by year or volume.

![covers](https://user-images.githubusercontent.com/2306629/69660154-98dd1600-1077-11ea-913c-7c807f18d27f.JPG)

In the final mockup, we show a browsing pattern specifically for small devices like phones. In such circumstances, we adopt a swiping pattern that is common to mobile devices, in which the user can swipe left/right _within the nav area at the top_ in order to quickly reach old years. And they can swipe left/right _within the issue list area_ to go to the prev/next group (years/volumes).

![mobile](https://user-images.githubusercontent.com/2306629/69660294-e35e9280-1077-11ea-92cf-9897f35f2604.JPG)

**Comment by NateWr** [comment]
In the absence of any further input, we're going to move to creating some working prototypes. @thinkbulecount2 is going to start by building out the mobile view (last image) and one of the desktop views (first image).

**Comment by thinkbulecount2** [comment]
cc: @NateWr 
[PR](https://github.com/pkp/theme-components/pull/3)

**Comment by NateWr** [comment]
Closing this in favor of the [feature request](https://forum.pkp.sfu.ca/t/ojs-3-archives-group-by-year/28848/31) on the forum.
