### ISSUE TITLE
[OJS 3.1.2] QuickSubmit: Pressing 'Enter' refreshes the Form with 'tag-it' Fields erased

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4668]
Hi! Here is the way to reproduce:
1) Fill some or all 'tag-it' fields (keywords, subjects, etc.) in the QuickSubmit form.
2) Position the cursor on any one-line field (like title) and press 'Enter'.
3) The form will be refreshed with all the 'tag-it' fields erased.

**Comment by asmecher** [comment]
There are two problems happening here:
1. Tag-it fields do not bounce back correctly from the server (e.g. when there's a server-side form validation problem resulting in a re-display). Rather than fix this (which is convoluted) I would suggest prioritizing the replacement of tag-it with something else. (https://github.com/pkp/pkp-lib/issues/4208)
2. Using "Enter" on another field will cause the form to be submitted. If you're intending to use "Enter" e.g. to tab through multilingual entries, I'd recommend using the tab key instead.

**Comment by asmecher** [comment]
Fixed by the patch: https://github.com/pkp/quickSubmit/commit/9b4cfd21aa2f3c802b0652a559ed2ac8fa9d360d

**Comment by asmecher** [comment]
Fix released in QuickSubmit 1.0.5-4.

**Comment by asmecher** [comment]
The above fix was incorrect; I've released QuickSubmit 1.0.5-6 to correct it (tested better this time).
