### ISSUE TITLE
Audit the default theme for skip links

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4682]
The default theme has skip links, which allow a user of a screen reader to jump to the navigation menu or the main content on a page, skipping the header. These _should_ be working properly, but we've never done an audit to ensure they're all working.

Also, on the homepage, we should maybe add additional skip links for each thing, like announcements, about the journal, current issue, etc.

**Comment by thinkbulecount2** [comment]
In addition to auditing skip links and adding links to about the journal, current issue, and announcements in OJS, I took them out of pkp-lib and put them as separate skipLinks for OJS and OMP so that they can be customised.

OJS PR: https://github.com/pkp/ojs/pull/2405
OMP PR: https://github.com/pkp/omp/pull/679
pkp-lib PR: https://github.com/pkp/pkp-lib/pull/4781

@NateWr

**Comment by NateWr** [comment]
PRs:
https://github.com/pkp/ojs/pull/2407
https://github.com/pkp/omp/pull/680
https://github.com/pkp/pkp-lib/pull/4786

**Comment by NateWr** [comment]
Merged
