### ISSUE TITLE
Duplicate dashboard menu links to Report Generator

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4694]
OJS 3.1.2 has the great new Articles visual usage report and an item in the main dashboard menu for Statistics.  Previously there was a main menu link for Tools with Import/Export and Statistics within it.  However, now in 3.1.2 we have the following:
               
Tools       - Import/Export
                - Report Generator
Statistics - Articles
               - Report Generator

The Report Generator link is in the menu twice.  It should either be removed from Tools or all of the statistics pages should be nested under Tools again.  From a documentation perspective I would prefer the latter because changing the main dashboard menu means the hundreds of screenshots of the dashboard in documentation are outdated and will need to be replaced.  However, I'm sure there are good arguments in favour of Statistics being a separate menu item, and it was requested in [issue 3602](https://github.com/pkp/pkp-lib/issues/3602).

**Comment by asmecher** [comment]
@amandastevens, this is inconsistent between OJS 3.1.2 (which you've described) and the `master` branch (to be released as 3.2, not behaving as you've described it). Assigning to @NateWr, who probably can answer at a glance.

**Comment by NateWr** [comment]
A couple notes on my reasoning:

- Eventually we'll have other stats pages that we'll be providing: issue usage stats, time to accept/decline, average number of reviews, articles published by year, top reviewers, etc. The idea is to put all of these under the new Statistics top-level menu item. So I do hope to keep that in place.
- I left Report Generator in both places because it is a very old tool and if we moved it we would have a lot of support requests. I think it's _ok_ to have it in two places -- even a good thing -- if it makes sense for it to be in both places. I _think_ that multiple paths to success is good Information Architecture.

Keep in mind that only journal managers see this at the moment, so that may limit the number of screenshots that need to be generated.

Another thing to consider: is it ok for the documentation to reflect only major versions (3.x)? Obviously you'll want to update the text with new features as they come, but personally I think it's reasonable to leave the screenshots alone except where they _need_ to be updated for minor versions (3.x.x).

**Comment by NateWr** [comment]
Closing this as the Tools submenu is no longer expanded, so the report generator does not appear twice in the menu.
