### ISSUE TITLE
pkp-lib/templates/frontend/pages/privacy.tpl - move breadcrumb out of div

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#4738]
pkp-lib/templates/frontend/pages/privacy.tpl 

The breadcrumb include should not be within the  div class="page page_privacy" element, but moved in front of it. Otherwise, the privacy statement is displayed on the same line as the breadcrumb.

 OJS 3.1.2

**Comment by asmecher** [comment]
For you, @NateWr! Delegate as/if you like.

**Comment by NateWr** [comment]
PRs (master):
https://github.com/pkp/ojs/pull/2400
https://github.com/pkp/omp/pull/677

PRs (stable):
https://github.com/pkp/ojs/pull/2401
https://github.com/pkp/omp/pull/678

Thanks for reporting @mpbraendle! The default statement itself should be wrapped in `<p>` tags, since it will be automatically wrapped when the statement is edited in the settings. To fix you instance, you can just go into Settings > Website and re-save the privacy statement. This should add the `<p>` tags and make the statement appear on the next line.

**Comment by mpbraendle** [comment]
Hmm. Yes and no. The proposed change must then be implemented for every language ...

**Comment by NateWr** [comment]
Good catch @mpbraendle! I've updated the PRs now.

**Comment by NateWr** [comment]
Merged.
