### ISSUE TITLE
pdf.js does not display ff characters

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4749]
When viewing the PDF in OJS with the pdf.js viewer, any word with "ff" in it is displayed with all the letters jumbled together.  See http://journals.sfu.ca/cjhe/index.php/cjhe/article/view/188197/186327 (and other articles in this journal).  

I tested it in Chrome and Firefox and got the same result.  When you download the PDF and view it the characters display fine and the text can be copied and pasted, so I don't think it's a problem with the PDF itself.   

The journal is using OJS 3.1.2.

**Comment by Vitaliy-1** [comment]
Just tested it and the problem resolved after upgrading of PDF.js to 2.0.943 version (currently the latest stable).

**Comment by asmecher** [comment]
Updated to the latest stable -- thanks, @amandastevens and @Vitaliy-1!

**Comment by amandastevens** [comment]
Thank you for solving this!  @asmecher, to fix this on the journal site do I update the pdf.js viewer plugin?

**Comment by asmecher** [comment]
I haven't built a new release of it yet for the plugin gallery, but I can...

**Comment by amandastevens** [comment]
Or if there is another way to implement the update let me know.

**Comment by asmecher** [comment]
That plugin is distributed with OJS, so I'm nervous about mixing things up too much by also putting it in the plugin gallery. I've put a new .tar.gz release here for users who need the update: https://github.com/pkp/pdfJsViewer/releases/tag/v1_0_1-0

However, since you're probably working with hosting, I suspect you'd do best to just update the git submodule (to `stable-3_1_2`, in the `plugins/generic/pdfJsViewer` directory).

**Comment by WilsonAndrewWilson** [comment]
Hola!

We are on 3.1.1.4 and are encountering this issue.

Updating via dropping the PDF.JS tar.gz into OJS plugin manager didn't work, causing a 500 error, with the following PHP error:

```
Fatal error:  Call to undefined method PdfJsViewerPlugin::getTemplateResource() in /var/ww
w/plugins/generic/pdfJsViewer/PdfJsViewerPlugin.inc.php on line 71, referer: https://ojs-t
est.st-andrews.ac.uk/index.php/SAEE/issue/view/55
```

If I just drop the new V1.0.1.0 pdf.js directory into /var/www/plugins/generic/pdfJsViewer/pdf.js , it does fix the problem, but the browser console reports that the global PDFJS isn't defined, pointing to the code below in the HTML source:

```
$(document).ready(function() {
  PDFJS.workerSrc='https://ojs.st-andrews.ac.uk/plugins/generic/pdfJsViewer/pdf.js/build/pdf.worker.js';
 //etc
```
Bit of sleuthing shows that the PDFJS global is removed on later versions of pdf.js, and it looks to not be used in that release [linked above](https://github.com/pkp/pdfJsViewer/releases/tag/v1_0_1-0) but is used in the current 'broken ff' version.

Question - ok to ignore the PDFJS not defined error, given it's working ok? 

Thanks!

**Comment by asmecher** [comment]
@WilsonAndrewWilson, is it a possibility to upgrade your OJS to the latest release? You're encountering an error either because your OJS is too old for the new plugin, or your back-port of the pdf.js update is too new for the old plugin. The best way is to upgrade OJS to the latest and use the latest plugin (with the new PDF.js included).

**Comment by WilsonAndrewWilson** [comment]
Thanks @asmecher . We have quite a long upgrade cycle (DEV, TEST, then full UAT, then LIVE), so it may be some time to upgrade (it also means that newer releases have come along inbetween TEST and LIVE!).   We've disabled the plugin for the time being until we upgrade again.
