### ISSUE TITLE
[OMP] Add new "citation_..." metadata tags for Google Scholar

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#476]
Google Scholar can use the following new tags for monographs:

citation_doi
citation_issn (one each for all issn's)
citation_title (which is present, but can have the subtitle concatenated)

**Comment by asmecher** [comment]
![book](https://cloud.githubusercontent.com/assets/200411/12691335/e0c9abac-c69f-11e5-93d8-a35fd3f37a53.png)
@NateWr, let's talk a little about front-end presentation for chapter-based content on Monday. As part of this issue I built out a test to include approvals for a multi-chapter book.

**Comment by asmecher** [comment]
@NateWr, I've cleaned up the Scholar tags; before I send this to Anurag for a quick review it'd be nice to get the PDF display basically cleaned up. I think it's just a matter of porting over a few template details from OJS master.

**Comment by NateWr** [comment]
Question regarding SEO on this stuff: should the `viewFile.tpl` template be indexed by Google?

The main issue is duplicate content. We'll somehow need to come up with a title that is unique to every viewed file if the content is indexed. This could end up looking strange, eg: "HTML galley view of This Book Title Is Great".

It would seem to make more sense to me for us to add a `NOINDEX` header to viewable file pages. We could then add a `rel=canonical` link to the header pointing to the book it came from. However, we'll run into issues with people being able to link to, eg, a LENS galley view (Facebook and Twitter will usually share the canonical URL rather than the actual URL is one is specified).

So for now I'd guess just do the `NOINDEX` header. But is there anything that appears specifically on a file view page that we'd want to be indexed?

**Comment by NateWr** [comment]
I see now you've added the Google Scholar tags to the PDF view, so a `NOINDEX` tag isn't an option there... what if someone doesn't have a PDF view? Are there no Google Scholar tags for them?

**Comment by asmecher** [comment]
This is the "landing page" requirement that Google has. For an item to be indexed in Google Scholar, it needs its own landing page on which the Google Scholar tags can live. The file contains the content and thus needs to be the indexable unit, so for content to be indexed in Google Scholar it'll need something like the PDF viewer plugin to present it alongside its meta tags. I'll be asking GS to review this fairly soon.

**Comment by NateWr** [comment]
Presumably we're not satisfying this requirement for ePub or other formats?

**Comment by NateWr** [comment]
ok I spent some time with this today and there's a PR:

https://github.com/pkp/omp/pull/207

**Comment by asmecher** [comment]
Not for downloadable files -- that's something I want to ask Anurag about. But generally I think a solution will be to introduce plugins for other formats too, providing web-based reading interfaces along with a download link.

**Comment by NateWr** [comment]
Woops, early submit there.

There are a couple of things to consider in that commit:

- I set it up so that a plugin can add a download URL to the template variables, and the default template should provide a link to that.
- There's a JavaScript error in the console now because the theme's stylesheet is loaded with the `Templates::Common::Footer::PageFooter` hook. But the header doesn't load jQuery (as it's not needed). Not sure how to best handle this. SHould viewable file pages have their own page footer hook? Or none at all?
- It looks like the OJS viewableFile plugins are structured differently, loading [an entire page template](https://github.com/pkp/pdfJsViewer/blob/master/templates/display.tpl) rather than just a fragment. Is this just something that's waiting to be rationalized between the platforms?

**Comment by asmecher** [comment]
I'd suggest adding jQuery to the file view template. The page size savings will be almost nonexistent (it'll be locally cached from other parts of the system unless they've come directly to the file view from e.g. Google Scholar) and there will likely be utility in having it around.

The viewable file plugins behave a little differently -- we may rationalize them eventually but it's not a huge priority at the moment.

**Comment by NateWr** [comment]
Ah of course, that makes sense. Pushed one more commit to the PR now to add jQuery in.
