### ISSUE TITLE
Clarify filesystem implications of CLI upgrade

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4872]
**Describe the problem you would like to solve**
Filesystem implications of running the Upgrade from the CLI are unclear.
https://forum.pkp.sfu.ca/t/error-when-submitting-revision-files-in-ojs-3-1-0-1/46283/8?u=ctgraham

**Describe the solution you'd like**
The Upgrade documentation should describe running the CLI upgrade as the web user, or manually dealing with the consequences.

**Who is asking for this feature?**
Self-hosted admins

**Additional information**
n/a

**Comment by asmecher** [comment]
Recommending that users run scripts "as the web user" may not always be accurate or a best practice... In the case of FastCGI/SuPHP/CGI where scripts are set to run in a setuid environment, both web-based and CLI scripts will tend to be run as the installation's user account and no permissions changes will be needed. Actually, we strongly recommend that users do things this way -- `mod_php` in a multiuser environment is inherently insecure because all PHP assets on the server run under the same user account, regardless of who owns/maintains them.

**Comment by ctgraham** [comment]
In a setuid scenario, I would consider the "web user" to be the setuid user, but I take your point of the ambiguity there.

I think the important thing we need to clarify is that the step "Upgrading the OJS Database" is not just about mysql/postgres/etc. database changes anymore.  Rather, it affects the database and the datafiles.  This is alluded to in the section "Upgrading from OJS 2.4.x", but should be generally noted in the `tools/upgrade.php` run.

I see we also have some slippage in the addition of "Update Javascript libraries and build.js" section, which probably should relate just to the "2. git" section for "Obtaining the latest OJS code".  Let me try another editing round.

**Comment by asmecher** [comment]
@ctgraham, does https://github.com/pkp/ojs/commit/a58a0f2c39242adeedbdba43c5f98413425355a3 look better to you? I thought about adding this section to the general upgrade instructions but I don't foresee we'll be rearranging files there during upgrade except possibly rarely.

**Comment by ctgraham** [comment]
Works for me.

**Comment by asmecher** [comment]
Merged, thanks!
