### ISSUE TITLE
Selectively expose TinyMCE controls

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4890]
**Describe the problem you would like to solve**
Design goal: reduce clutter in TinyMCE by only including essential buttons/controls. This is a placeholder to track our discussion and requirements for which TinyMCE controls should be part of this minimal set and which pages/modals/use-cases may benefit from additional controls for managing e.g. journal settings, text, and other content.

**Describe the solution you'd like**
For example, author guidelines include text that is more complex since it includes forms of instruction for authors. As such, number and bullet list controls would be helpful to structure this text.

**Who is asking for this feature?**
Journal Editors, Journal Administrators

**Additional information**
Additional use-cases and examples would be helpful and are welcome.

**Comment by mfelczak** [comment]
The code control would continue to be useful for managing custom blocks and pages, since JMs and Editors at times use these to embed content from 3rd-party services (e.g. Twitter timeline).

**Comment by mfelczak** [comment]
When upgrading from OJS 2, journal settings at times need to be manually cleaned-up when getting started with OJS 3 to adjust tags, formatting, etc. The code control is helpful in these cases.

**Comment by NateWr** [comment]
Assigning this to 3.2 because when the new settings forms ship they will go out with simplified TinyMCE controls so we need to catch the critical cases and add the necessary controls back there.

**Comment by NateWr** [comment]
The old TinyMCE controls:

![Selection_081](https://user-images.githubusercontent.com/2306629/60605132-daabae00-9db0-11e9-9d4e-f398335e73d7.png)

The new TinyMCE controls (settings forms only so far!):

![Selection_082](https://user-images.githubusercontent.com/2306629/60605160-e7300680-9db0-11e9-8844-70c22f12a759.png)

**Comment by asmecher** [comment]
The "full screen" control is a nice way (IMO) of hiding interface clutter. It's possible to set up a different toolbar for compact vs. full-screen views.

**Comment by NateWr** [comment]
> It's possible to set up a different toolbar for compact vs. full-screen views.

Ooh, I'll explore that! A nice "workaround" for those that want the kitchen sink.

**Comment by jmacgreg** [comment]
+1 for the compact vs. full-control option. And my own thoughts here: if we shipped OJS 3.2 with only a slimmed-down set of controls available without dipping into code to re-enable, we'd definitely start receiving questions, complaints, and requests to restore access to the previous controls from hosted clients. I'm all for reducing complexity, but not at the cost of removing functionality - especially without performing some extensive, broad user testing (as opposed to just shipping out in a release). People do use these across the board (not everyone everywhere, but many different folks in many different places). So, yeah, +1 for @asmecher's suggestion. :-) (I think Wordpress even includes (used to include?) an explicitly-named "kitchen sink" button?)

**Comment by NateWr** [comment]
Thanks everyone! To clarify, for v3.2 this will only apply to TinyMCE fields in the new settings forms and the publication forms (the new metadata fields). However, I'd like to start mapping out what kind of input fields need more or fewer controls across the app, since we'll roll out the new forms in more places in the future.

We can use the full-screen view as a fallback for access to all controls and I can write a 10-line plugin to customize the toolbars for any single journal. But I'd like to settle on a streamlined set of default configurations.

Fewer controls reduce cognitive load, which reduces stress, fatigue and frustration. But, also, each control sends a signal to the user about what content they are expected to produce. We can use this to encourage consistent content, which will have the additional benefit of making it easier to design themes that make journals look good.

Here's a first pass from me, but I'd love to hear additional thoughts/comments from anyone:

## Light
Use when we want to discourage too much formatting and where consistency of input is valuable for content design. **Controls**: Bold, Italic, Superscript, Subscript, Links
- Abstract
- Author Biography
- User's Email Signature
- User's Mailing Address
- Journal Summary
- Announcements: Introduction
- Announcement: Short Description
- Issue Description
- Section Policy
- Category Description

## Medium
Use when we want to discourage advanced formatting but when fewer constraints will lead to fewer problems, either because fewer users are exposed to it or because the user inputting the data is more trusted. **Controls**: Bold, Italic, Superscript, Subscript, Links, Ordered Lists, Unordered Lists
- Author Guidelines
- Copyright Notice
- Review Guidelines
- Competing Interests
- Email Template Body
- License Terms

## Heavy
Use when journal managers are most likely to make use of full controls and least likely to cause problems when doing so. **Controls**: Bold, Italic, Superscript, Subscript, Links, Ordered Lists, Unordered Lists, Image Upload, Code Editor
- Editorial Team
- About the Journal
- Page Footer
- Additional Homepage Content
- Information (For Readers/Authors/Librarians)
- Custom Navigation Page Content
- Announcements (Full Text)
- Privacy Statement
- Review Form: Description and Instructions
- Custom Block

## Exceptions
- Email Signature in Journal Settings (all Light controls + Image Upload)

I'm sure I'm forgetting some things and the assignment won't be right for everything here. But hopefully this will kick-start some discussion on when and where controls are most needed.

**Comment by asmecher** [comment]
@NateWr, is it worth working "single line" into this set (e.g. per https://github.com/pkp/pkp-lib/issues/2564#issuecomment-498354192)?

**Comment by NateWr** [comment]
Thanks! Updated. :+1:

**Comment by jmacgreg** [comment]
Hi @NateWr, thanks for the reminder on this. I still have some concerns about the approach outlined above. We will have clients who will want to do something they used to be able to do, like upload an equation image to an abstract field, or format their email signature with an image or list (as two very quick examples), but won't be able to. Limiting these options anywhere *except* where the options so so completely obviously overkill (single line fields) won't be a smooth process without some significant pre-release user testing, and that still won't account for edge cases (which are rare but still worthy exceptions). Any change here should be easy to override by admins - at a minimum, in the config file, but possibly also elsewhere (eg. within a TinyMCE settings page via the UI). But at a minimum, I think we should review this comprehensively with some editors and managers before we release it in stable. You would be surprised where folks want to be able to upload images and add lists.

**Comment by NateWr** [comment]
@jmacgreg I plan to write a plugin which will have simple point-and-click settings to add the image and code buttons to any TinyMCE field. I see you've mentioned being able to add lists anywhere as well.

Can you think of any other buttons/controls that need to have an opt-in point-and-click interface?

**Comment by jmacgreg** [comment]
Hi @NateWr, image and code options are probably the most important to be able to enable anywhere, so that sounds great! Lists would be a strong addition. IMO that would cover it, but I've asked the hosting team to review this as well and provide some feedback, and we can also ask some journal managers/editors to review if you'd like.

**Comment by mfelczak** [comment]
Hi @NateWr and @jmacgreg, we've also received requests for enabling the table button set, e.g. for use on custom static pages.

**Comment by NateWr** [comment]
I've rolled out the default controls as specified above and built out a small plugin that lets you add image upload, code editing, and table controls to any field.

![Selection_145](https://user-images.githubusercontent.com/2306629/67799630-a3f35500-fa7d-11e9-9584-f1a01ea552ac.png)

Any fields you don't see listed there have not yet been converted over to the new tinymce editor, so their buttons won't be affected in 3.2. We can add them as we go.

Here's what a fully-stocked editor looks like:
![Selection_147](https://user-images.githubusercontent.com/2306629/67799670-b8cfe880-fa7d-11e9-9893-9ae85e185aa2.png)

I'm really hoping that this will suffice for those times when it is needed.

@mfelczak I know that journal editors are going to want tables, but I'd strongly encourage you to find out what they want them for and try to find another way to satisfy their need. There's no way to make tables mobile-friendly without some clever CSS wrapping and they can really break mobile layouts when not handled properly. Additionally, the table controls in TinyMCE do not provide sufficient handling for table headers, which are a WCAG requirement. If there's a particular client/case where it seems important, let me know and I may be able to suggest some manual html/css tricks to help.

**Comment by NateWr** [comment]
Merged. @asmecher I'm going to leave this open and assign you just to make sure you look at the public file upload API handler just in case I've done anything stupid. Once you've had a look feel free to close.

**Comment by asmecher** [comment]
@NateWr, this is really exciting stuff! I added a few comments where a bit of attention is needed, but don't let that get in the way of a very enthusiastic :bathtub: I mean :+1:

**Comment by jmacgreg** [comment]
Hey @NateWr, a belated thanks for your approach to this. I haven't been able to review this more closely just yet, but it's on my list (and in particular with the controlPublicFiles plugin, which looks like a must-have). I don't think we'll be auto-enabling the Text Editor Extras plugin, but it's good to know that it's an option we can provide (along with guidance). Thank you!!
