### ISSUE TITLE
[OJS] ORCID Profile Plugin: Sandbox iDs not stored or displayed correctly on the article page

### ISSUE THREAD

**Issue by gmejias** [pkp/pkp-lib#4893]
After entering the ORCID Member API Sandbox credentials it's possible to successfully connect the Sandbox iD but OJS links to orcid.org instead of sandbox.orcid.org 

It seems that that OJS cant handle Sandbox iDs, the internal validation doesn't allow them to be stored and they are not displayed correctly on the article page.

@isgrim

**Comment by isgrim** [comment]
Thanks for posting this. As I wrote in a second email, I mixed something up. Sandbox iDs are stored, but they are not shown as sandbox iDs on the article page, only in the backend contributor form and user profile.

There is also another major issue with displaying ORCID iDs currently in OJS 3.1.2-1 reported in the forum:
https://forum.pkp.sfu.ca/t/orcid-icon-problem/53637

Maybe this can be tackled together.

**Comment by isgrim** [comment]
So more clarification, I'm very sorry I was too hasty. I should have looked at the code first.

Currently Sandbox ORCID iDs are stored as normal ORCID iDs ... this is undesirde. There exists a separate field "orcidSandbox" which declares them as Sandbox. This was a workaround due to the limitation of the "orcid" Field validation, only allowing producation ORCID iDs.

But since with the plugin no more manual entry of ORCID iDs is permitted the validation is not needed, and so I would rewrite the storing and display of sandbox iDs.

**Comment by isgrim** [comment]
@asmecher You can assign me to this

**Comment by asmecher** [comment]
Thanks for looking at this, @isgrim!

**Comment by withanage** [comment]
Is in Version 1.1.1-2 in Plugin gallery
