### ISSUE TITLE
Upgrade Issue: Table `email_templates`

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#4939]
When trying to upgrade an OJS installation from OJS3.1.2 to OJS3.2 (master branch) I am the following issue:

The `dbscripts/xml/upgrade/3.2.0_preupdate_email_templates.xml` drops the `email_templates` table, and, afterwards, the dbscripts/xml/upgrade/3.2.0_update.xml script is trying to read from the `email_templates` table, resulting an `ERROR: Upgrade failed: DB: Table 'ojs.email_templates_data' doesn't exist`

**Comment by asmecher** [comment]
Corrected by moving the email template change to a step prior to the schema change. (This keeps the SQL in `stable-3_1_2` and `master` consistent.)

**Comment by silasdb** [comment]
Hi! I just upgraded an installation of OJS from 3.1.0 to 3.1.2-4 and then to 3.2.0-2 and I'm getting the error above. This version (3.2.0-2), however, has the reported patch. Maybe I'm doing something wrong?

**Comment by asmecher** [comment]
@silasdb, what is the full, exact message you're getting during upgrade? Is this a first upgrade attempt, or a second attempt after a failed upgrade?

**Comment by silasdb** [comment]
On Thu, Apr 23, 2020 at 02:56:56PM -0700, Alec Smecher wrote:
>@silasdb, what is the full, exact message you're getting during upgrade? Is this a first upgrade attempt, or a second attempt after a failed upgrade?

You were right, the upgrade was failing because of a database encoding 
issue, when I fixed that the migration script failed because it had 
already made changes before.  I performed a rollback on the database and 
fixed the encoding issue before running the migration and it worked 
perfectly.  Thanks!
