### ISSUE TITLE
OMP has an editor.article.schedulePublication action on Production workflow

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5053]
See bottom right of image.

![bug](https://user-images.githubusercontent.com/200411/64576048-8df1cf80-d32b-11e9-966a-2771bd725d54.png)

**Comment by asmecher** [comment]
PR: https://github.com/pkp/omp/pull/701
@NateWr, can you confirm that this follows your intentions for the OMP end-of-workflow? Thanks!

**Comment by NateWr** [comment]
@asmecher I've kept this button in to guide the user towards the Publication tab. 

Each prior step of the workflow has its "complete this stage" buttons in this position, so the user has been trained to look there when done. This button should show the Publication tab so that the user can then see the full publication details and schedule it for publication.

It doesn't work in all cases though. This is filed (not very clearly) here: https://github.com/pkp/pkp-lib/issues/4857

**Comment by NateWr** [comment]
Addressed in PRs here: https://github.com/pkp/pkp-lib/issues/4857#issuecomment-536994194
