### ISSUE TITLE
Improve Submission Library utility

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#520]
See:
- http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8925 ("Enable selection of docs from Press Library when sending email to author at Accept Submission")
- http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8441 ("Grant optional public access to document library")

**Comment by defstat** [comment]
@asmecher 

PRs
pkp-lib: #3424
OJS: pkp/ojs#1851
OMP: pkp/omp#505

**Comment by defstat** [comment]
@asmecher @jmacgreg 
The PR adds the two improvements regarding the Library Documents. 
1. Upon an Editor Decission, a grid with the Library Documents has been added, under the email template, so that the Editor can select any file from there, so that it can be attached to the email.
2. Optionally, a Library Document can be indicated as "Public Access"ed, and a URL is provided so that any user (both logged-in and not) can download it from that URL. The URL is something like `[context]/publicLibrary/downloadLibraryFile/[fileId]`

**Comment by defstat** [comment]
@asmecher I covered the review (with some notes)

**Comment by asmecher** [comment]
@defstat, I added a few new comments. The necessary tweaks are minor, so please feel free to go ahead and merge once you've looked them over. Thanks!

**Comment by defstat** [comment]
@asmecher Tests pasted. PRs merged.

**Comment by asmecher** [comment]
Thanks, @defstat!

**Comment by defstat** [comment]
@bozana 
Regarding your comment 

PRs:
pkp-lib: #3261 
OJS: pkp/ojs#1878

**Comment by fgnievinski** [comment]
I wished PDFs would display in the browser instead of being downloaded.

(Should I open a new feature request or is this comment sufficient?)

Thanks.

**Comment by fgnievinski** [comment]
Also, it'd be nice to be able to replace a file; currently it seems the only workaround is removing the old one and creating a new one, which unfortunately breaks links.
