### ISSUE TITLE
Please make it possible to associate a chapter with a landing page

### ISSUE THREAD

**Issue by neffe** [pkp/pkp-lib#5280]
May I strongly urge you to activate the opportunity to have chapter landing pages for OMP, so it will be possible to register the chapters with DOIs.
I was not aware that it is not possible in the current setup. We are now faced with having to publish an anthology on our OMP platform, which in the printed version has already been assigned with DOIs on the chapter level. The DOIs are generated from our OMP platform.
For me one of the greatest features in OMP 3 compared to OMP 1 was exactly the option to give chapters a DOI.
Regards
Niels Erik

**Comment by ajnyga** [comment]
This is a first try to introduce chapter landing pages in OMP: https://github.com/pkp/omp/compare/master...ajnyga:chapter-landing?expand=1

It still does not support versioning, but there are no actual technical reason why this could not be added. I was just too tired to think of the best solution to do it.

**Comment by asmecher** [comment]
Thanks, @ajnyga! @NateWr, would you mind taking a look at https://github.com/pkp/omp/pull/729?

**Comment by NateWr** [comment]
I'm open to moving forward with this but I think we need to nail down some details about the feature first. A few questions:

1. I did a quick scan of some (English-language) academic publishers and didn't find any chapter landing pages. Am I looking in the wrong place? Maybe this is common among non-English-speaking publishers?

- https://global.oup.com/academic/product/the-happiness-effect-9780190054670?lang=en&cc=gb#
- https://global.oup.com/academic/product/agriculture-diversification-and-gender-in-rural-africa-9780198799290?lang=en&cc=gb#
- https://www.palgrave.com/gp/book/9783030245085
- https://www.palgrave.com/gp/book/9783319965673
- https://uk.sagepub.com/en-gb/eur/great-powers-and-world-order/book263519#contents
- https://uk.sagepub.com/en-gb/eur/perspectives-on-international-relations/book259272#contents
- https://www.elsevier.com/books/quantitative-anthropology/williams/978-0-12-812775-9
- https://www.elsevier.com/books/air-transport-a-tourism-perspective/graham/978-0-12-812857-2
- https://press.princeton.edu/books/paperback/9780691203225/unhealthy-politics

2. Not everyone will want chapter landing pages. How should this be enabled/disabled: on a per-journal, per-submission, or per-chapter basis?

3. It is common for publishers to break down many of a book's parts into "chapters", including frontmatter, appendixes, etc. In such cases, a publisher may want to only enable chapter landing pages for some chapters and not all. I suspect that we'll want to enable/disable landing pages on a per-chapter basis for this, but should we be recording data about this in a chapter type field of some kind?

4. What should we do for existing books or new books in which chapters have very little information? Very few chapters in older books will have chapter abstracts. And it's likely that for many of our users going forward chapters will continue to be nothing more than a title, author and download. How can we ensure that we're presenting the most usable UI to a reader when there is not sufficient information to justify its own landing page?

5. Is anyone asking for chapter landing pages for any purpose other than the DOI? Is there any reader interest that would genuinely be satisfied by having chapters in a book link through to their own page? If not, it may be best to implement chapter landing pages specifically in relation to the presence/absence of chapter DOIs, and to build the pages purely as a landing zone for DOI links, rather than as something we intend to link to from our existing book table of contents in the default theme. (Custom themes would be free to do as they like.)

**Comment by ajnyga** [comment]
1. I do not have a thorough list, but here are examples from Springer:
https://link.springer.com/book/10.1007/978-3-319-94487-6
https://link.springer.com/book/10.1007/978-3-319-97837-6
The other one is a Monograph and the other one an Edited Volume.

Oxford: https://www.oxfordscholarship.com/view/10.1093/oso/9780198790839.001.0001/oso-9780198790839-chapter-12

Elsevier: https://www.sciencedirect.com/science/article/pii/B978044452937450006X?via%3Dihub

Chapter landing pages are not that important for Monographs, but they are important for Edited Volumes where the chapters  can actually be individual articles with their own authors.

Easiest way of finding more examples is to search for book chapters here: https://search.crossref.org/?q=history&type-name=Chapter


5. The requests I have seen a connected to DOIs, but in the case of Edited Volumes I can see a value in also having the landing page when there is no DOI. But this is just me talking.

I do not like the idea of hiding the landing page from the TOC. I am open to the idea of controlling the existence of a landing page based on whether there is a DOI or no DOI. It's a simple rule, we need those pages for DOIs and we can extend that functionality if there are other demands.

**Comment by NateWr** [comment]
Thanks. Both Springer and Elsevier use the DOI directly in the URL. That might be one way to persist URLs across versioned changes (a problem we have with versioned galleys in OJS and which would surface here too if we used chapter IDs).

Working back from Crossref's database will give us examples of chapter landing pages, but not a sense of how common they are or where they may be used without a DOI.

> I do not like the idea of hiding the landing page from the TOC.

The flip-side of this is having lots of links to pages with almost no content on them. This makes the publisher look unprofessional like they forgot to finish the listing. 

Oxford Scholarship Online is a good example of this done badly, with links to the front matter. Elsevier is better at identifying a chapter "type", but still leads to some confusing pages. Springer, which doesn't link to front matter, presents the best curated view of the three, with abstracts and references where appropriate.

Pegging them to DOIs will work if that's the only time we see demand for them. Otherwise, I am leaning towards a manual toggle to turn on a landing page for each chapter, and leaving it to editors to make sensible choices about when a chapter should have a landing page.

**Comment by ajnyga** [comment]
> Working back from Crossref's database will give us examples of chapter landing pages, but not a sense of how common they are or where they may be used without a DOI.

True. I do not have enough experience to even guess. It could very well be that big publishers only create chapter landing pages when they are needed for DOis. 

> The flip-side of this is having lots of links to pages with almost no content on them. This makes the publisher look unprofessional like they forgot to finish the listing.

Agree. I was thinking of a situation where the chapter has a DOI and therefore also has to have a landing page. In these cases I would show a link in the toc leading to the landing page. But a manual control, if it is easily accessible, is fine by me as well. Maybe a default setting in context setting which could be overridden in chapter settings?

@withanage might have some comments to this topic?

**Comment by NateWr** [comment]
Capturing some comments from @withanage in the PR:

> If you need any requirements for this ticket please let me  know. I  implemented  the functionality for chapters in  python frontend. 
> 
> https://heiup.uni-heidelberg.de/catalog/book/470/c6665
> 
> I have listed some of the specifications, I used in developing that front-end, if it may helpful for you.
> 
> * chapter doi  BOOK_DO.c<unique_chapter_id accross all omp portals> https://doi.org/10.17885/heiup.470.c6665
> *  In some occasions,  journal managers  do not want every chapter to be linked. Therefore I link  chapters, only when there is a doi registered. This way I could use the existing database  and  reduce the necessity to explicitly publish a chapter page.  For presses without  DOI, I think a general setting needed for  avoiding that requirement.
> * Chapter author and chapter title as title and author/s
> * Citations change for the chapter 
> * Cover-image  from  Monograph/ Edited volume is used.
> * Chapter pages lists formats horizontally. I use the approves / is avaliable function   to output a certain format.

**Comment by NateWr** [comment]
This was implemented in https://github.com/pkp/pkp-lib/issues/7132. Google Scholar support is still being discussed in https://github.com/pkp/pkp-lib/issues/7003.
