### ISSUE TITLE
OJS CSRF Token

### ISSUE THREAD

**Issue by denyspmaciel** [pkp/pkp-lib#5295]
Hello, I am a new OJS user and I could see that in the login form there is a hidden field called csrfToken. I would like to know what this field is for and how its value is generated? Does this field have any relation to the OJSSID session cookie?

Thank you!

**Comment by asmecher** [comment]
Hi @denyspmaciel  -- I see you've also posted this question at https://forum.pkp.sfu.ca/t/ojs-csrf-token-generation/57146. That's a better place for this. Closing this entry -- please try to choose the single best place to post a question in order to avoid duplicating work. If it's the wrong spot we'll be happy to guide!
