### ISSUE TITLE
PHP warnings becoming rampant

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [pkp/pkp-lib#5313]
Hi there,

with the recent releases the PHP log file fills with warnings pretty quickly. I'm using OJS and up to version 3.1.2.1 it was ok, only a few warnings, many got fixed.

But with the commit a059623037637d9b202e963b35a3e44952f79c63 from issue #5146 a *huge* amount of warnings are generated with each page request like 

`PHP Warning:  Declaration of NewContextImageFileForm::execute() should be compatible with Form::execute(...$functionArgs) in ...`

as almost all forms have a different execute signature as `Form`.

What are your thoughts on signature warnings like these? Are you planing to fix this somehow in the future?

So lonG

**Comment by asmecher** [comment]
@ViRuSTriNiTy, I've been working on fixing these in the `master` branch lately, and I'm down to just one or two; this will be resolved with the release of OJS 3.2 early in the new year. And once we're down to zero I'll tweak our Travis testing setup so that warnings fail the build, which will keep us a little more on our toes in the future.

**Comment by ViRuSTriNiTy** [comment]
@asmecher Ok, fair enough, thx. I will check the log situation after release of 3.2 again.
