### ISSUE TITLE
ISSUE: Warning: require_once(./lib/pkp/lib/pqp/classes/PhpQuickProfiler.php)

### ISSUE THREAD

**Issue by efairs** [pkp/pkp-lib#532]
I am the first time OJS user, when I try to install the OJS in my Goddady server and browse it. One problem occurred: Warning: require_once(./lib/pkp/lib/pqp/classes/PhpQuickProfiler.php) [function.require-once]: failed to open stream: No such file or directory in D:\Hosting\11814964\html\ubc-mc.org\lib\pkp\classes\core\PKPProfiler.inc.php on line 17

**Comment by asmecher** [comment]
@efairs, does the file lib/pkp/lib/pqp/classes/PhpQuickProfiler.php exist on your server?

**Comment by efairs** [comment]
yes, it exist on my server. Just in case. I am trying to upload the ojs2.4.6 files again to the server.

**Comment by efairs** [comment]
I uploaded the ojs2.4.5 to the server again. Now, the website displayed "http://www.mydomainname.com/ojs-2.4.5/index.php/index/install" but the page is empty???nothing on the screen??Any one can told me the reason? Is there any thing I should setup for my server?Thanks you. I fell really frustrated to install the software....

**Comment by asmecher** [comment]
Hi @efairs -- See http://forum.pkp.sfu.ca/t/when-i-click-some-button-or-follow-some-link-im-left-with-a-blank-page-what-do-i-do for the FAQ entry on this. I'd suggest using the forum if you need further help debugging this; it's very likely that this is a server configuration or file permission problem rather than a bug in the software.

**Comment by efairs** [comment]
Ok ,got it, thanks asmecher, I will go to forum right now.
