### ISSUE TITLE
PHP Notice when running the classes\task\StatisticsReport.inc.php and missing locale key

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#5335]
**Describe the bug**
When executing the task, 2 notices are issued + there's one key is missing in the report:

- `PHP Notice:  Undefined index: average in /var/www/html/lib/pkp/classes/notification/managerDelegate/EditorialReportNotificationManager.inc.php on line 212`
- `PHP Notice:  Undefined index: average in /var/www/html/lib/pkp/classes/notification/managerDelegate/EditorialReportNotificationManager.inc.php on line 223`
- `##workflow.review.externalReview##`

**To Reproduce**
- Add the task to the `registry\scheduledTasks.xml` file and execute the file `tools\runScheduledTasks.php`.

**What application are you using?**
OJS: 3.1.2.4
PHP: 7.1

**Comment by asmecher** [comment]
@jonasraoni, a favour to ask: when you send in pull requests to resolve an issue, could you add a link to the issue pointing to all PRs that are involved? Github makes it a little tricky to get from the issue to the PR, so that'll help make sure nothing gets missed. I merged the PR for this one: https://github.com/pkp/pkp-lib/pull/5336
