### ISSUE TITLE
Monthly scheduled task can be fired multiple times in a day

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5362]
**Describe the bug**
When a scheduled task wants to fire on the first day of each month, it uses `<frequency day="1"/>`. However, due to a bug in the task scheduler, this can be fired many times on the first day of each month if the scheduler is configured to execute tasks on an hourly basis.

This effects the editorial stats email.

A more technical discussion of the issue is available in this comment: https://github.com/pkp/ojs/pull/2546#pullrequestreview-331513886

**What application are you using?**
 OJS/OMP 3.2 (pre-release)

**Comment by asmecher** [comment]
This turned out to be a little tricky because we are supporting both acron (web-based) and cron (CLI-based) invocations. I looked at several third-party scheduled task support libraries and they all depend on predictable invocation, i.e. if you want one-minute resolution, cron must execute the script every minute. We can't depend on that for acron-based invocations.

My solution was to take our existing "green-light" date for checking task execution times and add a similar "red-light" date that prevents execution if the last run is too recent. As before, the green-light date gives us a bias towards execution if the last execution was too long ago, even though we may not be right on on the specified day/hour. The new red-light date prevents execution from happening, even when we are on the specified date/hour. This prevents the reported problem where the task can be executed multiple times within the specified day/hour/minute.

PRs:
- https://github.com/pkp/pkp-lib/compare/master...asmecher:i5362-fix?expand=1
- https://github.com/pkp/ojs/pull/2594 (tests only)

**Comment by asmecher** [comment]
@jonasraoni, would you mind taking a look at the above PR? Thanks!

**Comment by jonasraoni** [comment]
Hi @asmecher!

I've just checked the Acron plugin, to see what it does. Even though it has a race condition, it's a good/accessible fallback =]

---

FYI, my initial idea was just to replace the `day="1"` by cron expressions. Then with the last executed date, we can evaluate when each task should be executed again and run the delayed ones (here we could also add an optional parameter to specify a threshold) ... And I think it's fine if the tasks won't run in a perfect time, as long as the user is warned about how it works and how to make it more precise.
So for me there's no issues here... But here it's already too late and maybe my brain is already deactivated 👀

---

I checked the PR and I think that's fine, although I'm not sure it cover all edge cases (errr, that special format, such as specifying a range of hours/days/...).

**Comment by asmecher** [comment]
Thanks, @jonasraoni -- eventually this is another great candidate for an area to take on a 3rd-party library instead of custom code. But this was a minor addition and we're getting a little close to the release date for big changes. I think a lot of the built-in code is overengineered and under-tested -- our current set of tasks always specify an hourly, daily, or weekly run. A lot of the other options have never been used!

**Comment by jonasraoni** [comment]
@asmecher Yeah, it's better to avoid creating extra problems now =]

In general I think it's better to forward the responsibility of testing/improving code to other people. But as I'm a wheel reinventor, it's difficult to do it sometimes 😁
