### ISSUE TITLE
Errors with apiToken should be communicated in response message

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5390]
**Describe the problem you would like to solve**
When using the `apiToken` to authenticate with the API, there are many reasons it may fail but these are not communicated to the user. Possible failures:

- The API Key is not enabled in the user's profile.
- The `apiToken` is not correct.
- The `api_key_secret` is not set in the site's config file.

**Describe the solution you'd like**
An appropriate error message should be returned for each of these cases so that the user knows why their request has failed.

**Who is asking for this feature?**
Developers developers developers developers.

**Additional information**
Some recommended error messages:

- You must enable access to this API Key in your user profile.
- The `apiToken` you provided was not recognized.
- Use of the `apiToken` is not enabled. The site administrator must set the `api_key_secret` in the configuration file for this website.

**Comment by henriqueramos** [comment]
@NateWr Hey Nate, addressed this issue on this two pull requests here:

https://github.com/pkp/pkp-lib/pull/6562
https://github.com/pkp/ojs/pull/2983

Could you please take a look? Thank you!

**Comment by NateWr** [comment]
@asmecher we're encountering a test failure that neither of us can replicate locally. The tests are [failing](https://travis-ci.com/github/pkp/ojs/jobs/473432859) when they expect to see an error message in the form (testing invalid urlPaths for contexts). There's nothing in the error logs from the tests. I've tried running the tests locally with both Electron and Chromium. I'm not sure what to try next. Any ideas what's going on here?

**Comment by asmecher** [comment]
I'll take a look!

**Comment by asmecher** [comment]
The failure occurs on my machine too. I applied the changes manually to the latest `master` in `pkp-lib`, and used a fresh checkout of the latest `master` in OJS. The failure comes when submitting the "create journal" form...

![image](https://user-images.githubusercontent.com/200411/105212600-8a1ab380-5b02-11eb-95dc-e23e8aa91719.png)

...with a bad "Path" field:

![image](https://user-images.githubusercontent.com/200411/105212638-96067580-5b02-11eb-98c3-e1b69a9bb01e.png)

This results in the following error message:

![image](https://user-images.githubusercontent.com/200411/105212683-9ef74700-5b02-11eb-8231-11f30660afea.png)

...when the test expects a different one:

![image](https://user-images.githubusercontent.com/200411/105212739-b0405380-5b02-11eb-94c4-9932ea071c32.png)

![image](https://user-images.githubusercontent.com/200411/105212879-dc5bd480-5b02-11eb-8f3e-4e2ca7aa7687.png)

I think this is happening because the default `api_key_secret` in `config.inc.php` is empty, so [this test](https://github.com/pkp/pkp-lib/pull/6562/commits/72bb18519d228bf6ed60f977c0901af12a97c73f#diff-d524f6d316024b2a19c7abb550d3081256a0c6896a5e823caa6d9b5d084a7bceR41) will result in an API error unless they user has manually set an API secret.

**Comment by NateWr** [comment]
Aha! Thanks for finding that Alec. It's probably just the order of checks is inverted, since the API can be used without an API token when cookies/CSRF are involved. I'll revisit this tomorrow.

**Comment by henriqueramos** [comment]
Seems everything ran smoothly. Could you please check @NateWr?

**Comment by NateWr** [comment]
:tada: All merged, thanks @henriqueramos!
