### ISSUE TITLE
Article publication date should be updated on issue publication

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5392]
In OJS 2.x, when an issue was published, the publication date for its articles was updated to the current time:

https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/pages/editor/IssueManagementHandler.inc.php#L887..L888

However, that is not the case in OJS 3.x:

https://github.com/pkp/ojs/blob/1726f5859d97a914bbd58c9510359095594c5cd1/classes/controllers/grid/issues/IssueGridHandler.inc.php#L458..L467

This leads to cases where published article dates are not accurate:

https://forum.pkp.sfu.ca/t/3-1-1-0-article-publication-date-different-to-issue-publication-date/45891/9

Ensure that a publication action on an issue correctly sets the article publication dates.

**Comment by asmecher** [comment]
@AhemNason, pinging you for a heads-up to the notification WG.

**Comment by AhemNason** [comment]
> @AhemNason, pinging you for a heads-up to the notification WG.

Love a ping.

**Comment by asmecher** [comment]
Any objections to the approach I suggested above?

**Comment by alexxxmendonca** [comment]
I don't have objections when the journal publishes with traditional publication.

What about continous publication that still makes use of issues?

**Comment by asmecher** [comment]
> What about continous publication that still makes use of issues?

In that case, the issue will be published and the articles scheduled to it afterwards. Thus current behaviour will prevail -- the article publication dates will reflect the date the article is scheduled to the already-published issue.

**Comment by alexxxmendonca** [comment]
In that case: no further objections!

**Comment by AhemNason** [comment]
I feel like being able to set article publication dates en masse by updating it in issue metadata is a good call. I think it's a valuable option to have. I think adding post-"publication" and keeping those dates is the right call also. 

While we're talking about dates, I might suggest that "submission date" should be a display option instead of the default, because sometimes people submit outside the system and that date isn't editable. Like, if an editor receives a submission outside of OJS and fast-tracks it through the system closer to the publication (but not skipping review) it'll say it was submitted like 3 days before it was published. I get that this is tangential, but if I don't mention it I will for sure forget. 

NO OBJECTIONS TO WHAT YOU SUGGESTED.

**Comment by NateWr** [comment]
A note on how it will work in v3.2:

- A publication has a `datePublished` field which can be set manually. In traditional publishing setups it can and should remain empty.
- When an issue is published, it will set the `datePublished` of every publication scheduled in the issue, _unless that publication already has a value for `datePublished`_.

So the expected behaviour is for no one to touch it and it will be set when the issue is published. If editors want to distinguish between issue and article publication dates, they can do so by setting the date before the issue is published. 

Or, as Alec describes for continuous publishing, they can publish an article into an issue that's already published and set the date for each article individually.

**Comment by asmecher** [comment]
@NateWr, thanks for the details -- that works around the original issue sensibly. I don't think a back-ported fix to 3.1.2-x is a huge priority so I'll close this for now.

**Comment by fgnievinski** [comment]
> I feel like being able to set article publication dates en masse by updating it in issue metadata is a good call. I think it's a valuable option to have. I think adding post-"publication" and keeping those dates is the right call also.

just to second that being able to manually set the date of publication of a journal issue would be helpful when publishing historical digitized issues.  in OJS v3.2, the journal issue date of publication or `datePublished` (not to be confused with the year used as identifier) seems to be set automatically to the date when the issue is technically published in OJS.  a modifiable field for datePublished does appear after the issue is published, but the modification doesn't seem to be propagated into the articles' date of publication in that journal issue. this is true even when the articles date of publication were left originally blank.

in OJS v.3.2+, to change the publication date of published articles, each article needs to have a new version created, with the date manually set and saved, and then republished; the original wrong version of the article cannot be deleted but it may be unpublished.  simply unpublishing a whole journal issue, changing the issue date, then republishing the issue would have been easier.

PS: probably related, meta name="citation_date" seems to be populated with the issue identification year but meta name="DC.Date.issued" seems to use the article's datePublished. the How to Cite tool seems to use the latter, which generates citations with the year different than the journal issue's year.  I'm afraid the differences between the two metadata dates and the citation text might confuse readers and indexers.  we've been recently removed from Google Scholar and inconsistency in the publication dates is a known cause for trouble:
https://docs.pkp.sfu.ca/google-scholar/en/#check-for-consistency-in-the-publication-date
