### ISSUE TITLE
Publication > Permissions & Disclosure fields aren't prepopulated

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5428]
If I have already preconfigured a journal's permissions and disclosure defaults (ie. copyright holder and license info, including license URL), I would expect those defaults to be applied to new submissions, and available under the Publication > Permissions & Disclosure tab. Instead, all I see are blank fields for Copyright Holder and License URL. 

OJS 3.2, code pulled from today.

**Comment by NateWr** [comment]
Two options here:

1. We assign the defaults when submission is completed and the workflow begins.
2. We assign the defaults when a publication is published **if** the copyright Holder and License URL remain empty.

I am leaning towards option 1 because this provides the clearest presentation to author and editor at every step of the process. The downside is that if a journal changes its default settings, this will not be updated for submissions in the middle of the workflow. It will need to be manually updated for each submission. However, I think this is the right thing to do. An author most likely will only be apprised of the copyright/licensing terms when they submit. If a journal changes them after submission is complete, they should really advise the author and get sign-off. So a manual step seems appropriate here.

Option 2 provides late assignment so that the latest settings are always applied. But is unclear to authors and editors during the workflow. We can get around this by adding description text that says it will be set to X when published. However, that will cause problems in cases where the journal does not want to provide Copyright Holder or License URL for one submission (but wants it applied for others). There will be no way to say "don't apply the default on publish" other than to provide an alternative.

**Comment by NateWr** [comment]
It occurs to me now that the Copyright Holder option can be set to Journal or Author. In this case, it is probably best to do Option 2 because author names are likely to change during the course of submission and editors are unlikely to keep the Copyright Holder value in-sync.

**Comment by jmacgreg** [comment]
Hi @NateWr, I think I'm in favour of Option 2 as well. I'm thinking about this while also thinking about DOIs - something that could (and probably moreso than licensing info, will) change over the lifetime of the article's production, esp. as the article is assigned to an issue, etc. These things shouldn't be modified unless there's a good reason to do so, and I think it would be helpful to remove the apparent endorsement for modification that text fields provide unless action is taken to get to that point. for cases like these, what about presenting something like: 

> The copyright and license for this article will be: 
> (license info)
> and will be assigned to: 
> (in the case of author assignation) Jane Doe, John Smith
> (for editors only) [Modify]

... and fields are only available if the [Modify] button is clicked. This info can change much the same way that DOIs change over time, up until the point of publication.

**Comment by NateWr** [comment]
That can certainly be done. I'm hesitant to do it because we want to re-use as much as possible and this requires us to create a special field component just to add the [Modify] button. But I'll have a think about how to balance UX and code re-use here as best as possible. :+1:

**Comment by jmacgreg** [comment]
Sounds good, and I'm 100% ok with a more complete solution/approach waiting until post-3.2.0. For this release, the minimum I think should be at least including the defaults in the fields.

**Comment by NateWr** [comment]
Ok, I added an option to `FieldText` that will disable the field and require the user to opt into editing it. I suspect we might find similar use-cases. 

When a publication is published, it will assign the `copyrightHolder`, `copyrightYear` and `licenseUrl` based on the context settings _as long as the publication does not already have that information set_. This should allow one-off overrides as well as prevent it from being overridden from version to version.

I've updated the field text to make it more clear what will happen. Here's what it looks like now.
![permissions-override](https://user-images.githubusercontent.com/2306629/73262984-69f23600-41c7-11ea-8f65-b38e31d553f0.gif)

And here is what each field looks like when there's no context setting. 
![permissions-no-settings](https://user-images.githubusercontent.com/2306629/73263019-7e363300-41c7-11ea-8a92-a5bcbdc71f8f.png)

PRs:
https://github.com/pkp/pkp-lib/pull/5446
https://github.com/pkp/ui-library/pull/61
https://github.com/pkp/ojs/pull/2592
https://github.com/pkp/omp/pull/752

**Comment by jmacgreg** [comment]
This is perfect Nate, thanks!! I'll review a little later today.

**Comment by NateWr** [comment]
Merged, ready for final review. :+1:
