### ISSUE TITLE
Test licenseUrl context setting

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5445]
In some places `licenseUrl` is used and in some places `licenseURL` is used. This is probably a discrepancy that was introduced with the new schema system. Make sure all usage is aligned one way or the other and that data is migrated if it needs to be.

**Comment by NateWr** [comment]
Handled in PRs here: https://github.com/pkp/pkp-lib/issues/4856#issuecomment-582528375

**Comment by asmecher** [comment]
This recurred in `publication_settings` in 3.2.1-1 -- added scripts to migrate it (for release in 3.2.1-2 and 3.3.0).

**Comment by asmecher** [comment]
Users who upgraded before this change was applied can correct past articles with the following SQL query (please take a backup before running):
```
UPDATE IGNORE publication_settings SET setting_name='licenseUrl' WHERE setting_name='licenseURL';
```

**Comment by jmvezic** [comment]
It seems this was part of 3.2.1-2, wasn't it? In that case, shouldn't the upgrade from 3.1 to 3.2.1-2 have handled this automatically (per the xml upgrade script)? 

In my case there's still "licenseURL" values in the database.

**Comment by asmecher** [comment]
@jmvezic, the upgrade to 3.2.0 specifies (from the [3.2.1-2 codebase](https://github.com/pkp/ojs/blob/stable-3_2_1/dbscripts/xml/upgrade/3.2.0_update.xml#L23..L26)):
```
UPDATE journal_settings SET setting_name='licenseUrl' WHERE setting_name='licenseURL';
UPDATE publication_settings SET setting_name='licenseUrl' WHERE setting_name='licenseURL';
```
A quick look through the code doesn't show any appearances of `licenseURL` that would result in data being stored that way in the database.

**Comment by jmvezic** [comment]
That's interesting. I wonder why the upgrade script didn't change that (there also weren't any errors during the upgrade). I'll give it a bit of research before I run the command again and write back here if I find anything.

**Comment by jmvezic** [comment]
It seems all setting names after the upgrade to 3.2.1-2 are correct - they're all "licenseUrl". In fact, any publication that has its "date_last_activity" after the upgrade date seems to have the correct "licenseUrl" name.

So the issue is with settings before the upgrade, which would indicate that the XML script that converts "licenseURL" to "licenseUrl" for some reason didn't execute. I have no clue as to why that is.

@asmecher I'll try replicating it by doing an upgrade from 3.1.x to 3.2.1-2 with some example articles and licenses - both journal-wide and article-specific.
