### ISSUE TITLE
Some fields appear to be required in all languages

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5487]
**Describe the bug**
From Kate on Slack:
> I'm working on some documentation updates for 3.2 and have a question about the language tabs in the metadata settings. I uploaded a couple of submissions to the test journal "Health Sciences. The Journal of Theme Designing." The submissions were in English only, but when I go to edit the metadata in the "Publication" tab is gives me an error message: "1/2 language complete". It won't let me save the metadata until I've added content to the French metadata fields, as well. I'm wondering if this is intentional, and if so should it require the French metadata at the point of the original submission, as well as when editing the metadata at a later stage? Thanks for your help!

**To Reproduce**
1. Configure a journal with two languages (e.g. English and French), with French enabled under "forns" (and "submissions" may be required as well).
2. Create a submission with only an English title. (This shouldn't cause problems.)
3. As Editor, go to the Publication area and attempt to edit the title there. The form cannot be saved until a French-language title is entered, even though only English should be required.

**What application are you using?**
Pre-3.2 `master` branch

**Comment by NateWr** [comment]
Should a required multilingual property _always_ be required only in the primary language? Or are there cases where a required multilingual property may be required in every language, or something other than the primary language?

Right now, the validation checks are taken from the list of `required` props in the schema file. I can adjust this to handle all multilingual props differently, or we can extend the schema format to support a a separate `requiredInPrimaryLocale`.

**Comment by asmecher** [comment]
Currently all required fields are only required in the primary language, which is used on display as a fallback when more localized information isn't available. The "required" language is determined as follows:
- For site-wide content such as the site title, or (notably) user given names, family names, affiliations, etc., fields are required in the site's primary locale.
- For journal-specific required fields such as the journal title, issue titles (depending on issue identification setup), etc., content is required in the journal's primary locale.
- For submission-specific required fields such as titles and abstracts, author family names, etc., content is required in the submission's primary locale (which is selected, when there are several options available, on the first step of the submission process).

**Comment by NateWr** [comment]
A note to also check how this is working on dependent entities (contributors, galleys, chapters). These aren't yet on the new schema system, but may have long-standing issues related to whether required fields are correctly required in the submission's locale.

**Comment by NateWr** [comment]
@asmecher This could really do with a second set of eyes on this, and some manual testing if you have the time. These PRs update the validation checks for publications and related objects so that they take use the publication's locale as the required locale for multilingual fields and only allow locales enabled under the context setting `supportedSubmissionLocales`.

I think I've got all the logic correct, but there are a few lingering questions.

1. Galleys have no locale settings in the UI. The label is not localizable. I've left this as-is but that may benefit from being localizable in the future.
2. Authors correctly require the `givenName` in the locale of the publication. However, the fallback of localizable data can result in empty names being shown in the grid. So if the publication is in `fr_CA` and I am viewing the app in `en_US` and an author only has a name in `fr_CA`, the author grid will show a row with no author name. (See screenshot below)
3. Publication formats require a label in the context's primary locale, not the publlication's. I _think_ this is the right way to go. Since these are format labels that are used in the UI (PDF/HTML), rather than names of files, I think the required value should be the context's primary locale.

There isn't actually a place to change the locale of a submission outside of the submission form. I've filed that as an issue for 3.2.1 if you're ok waiting on that. https://github.com/pkp/pkp-lib/issues/5502

Author grid when author names not available in locale being viewed by user.
![Selection_202](https://user-images.githubusercontent.com/2306629/74256196-e5d19f80-4cea-11ea-8727-bff42f510d39.png)

PRs:
https://github.com/pkp/pkp-lib/pull/5501
https://github.com/pkp/ojs/pull/2619
https://github.com/pkp/omp/pull/763

**Comment by asmecher** [comment]
Looks good on a visual inspection, @NateWr. I'm content to test/refine this once it's merged, so we can get everyone working on the codebase with this included ASAP.

**Comment by NateWr** [comment]
Merged!
