### ISSUE TITLE
Installed Plugins are unsorted and items are moved in the list when enabled

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#5616]
On a clean OJS 3.2.0-0, when you go to "Installed Plugins" (/management/settings/website) and you enable any of them... sometimes work just fine (ie: "Make a submission"), but others the enabled item moves erratically in the plugins list (ie: "Web Feed", "AddThis"...).

I noticed it mainly happens with the plugins installed from the Gallery... but works fine (no moviment) with others preinstalled. May be is related with the fact that plugins are not alphabetically sorted?

![imagen](https://user-images.githubusercontent.com/2779168/76401044-9631d280-6381-11ea-83e1-5f15bcb94f36.png)

**Expected behavior**
From my understanding, plugins must be alphabetically sorted in each category and don't change it's position when they are enabled. Otherwise you have a wired user experience, and your first though is the plugin disappear.

**Comment by touhidurabir** [comment]
With the latest installation of `OJS` `3.3.0+`, this issue does not seems to be persist any more . But in the `Plugin Gallery` section, the plugins are not sorted alphabetically so may be that is something we can point as enhancement option but there is a search option there as well so that does not seems very significant either . But installing plugin from gallery or activating/deactivating from list of installed plugins does not disrupt the plugins order in both installed or gallery plugins list in the latest `OJS` version. 

@asmecher this issue may still exists in `OJS 3.2.0+` and related to that version branch code which is `stable-3_2_0` or `stable-3_2_1` but do we need to fix it there now or just make the recommendation to update latest stable ? Also should I make changes to order plugins in the `Gallery Plugins` to be sorted alphabetically by default ?

**Comment by asmecher** [comment]
I'm OK to close this and move on unless we get another report. No need to fix older releases (upgrading is the best solution) and I'd like to undertake some more comprehensive UI/UX work on the Plugin Gallery before investing time there, unless we actually have users requesting specific changes. Thanks!
