### ISSUE TITLE
FormComponent subclasses, even when invoked via the API, require CSRF tokens

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5633]
See: https://forum.pkp.sfu.ca/t/api-requests-doesnt-work-when-i-am-not-logged-in/59138
> According to the ojs API docs the api should work when sending request with apiToken, but what i get is unauthorised access when I am not logged in to OJS.

...and later...
> I am using Postman for testing and this is the response for POST request:
>```{
>“error”: “form.csrfInvalid”,
>“errorMessage”: “The form could not be submitted. You may have been logged out. Please reload >the page and try again.”
>}
>```
>and for GET:
>```
>{
>“error”: “user.authorization.accessDenied”,
>“errorMessage”: “##user.authorization.accessDenied##”
>}
>```

**Comment by asmecher** [comment]
@NateWr, I seem to remember a tweak related to this recently -- anything come to mind?

**Comment by NateWr** [comment]
Yeah, @quoideneuf made sure the API Token middleware was fired first: https://github.com/pkp/pkp-lib/commit/c067208bfc7a746dd781a6ba81b48c9a39fbec0a#diff-cd4d35bc14ff58fdc70b528567a1f045.

And it looks to me like the CSRF middleware shouldn't be invoked when an API Token is decoded: https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/internal/ApiCsrfMiddleware.inc.php#L40-L44

I think @quoideneuf has been using the API with the API Token for a while, so maybe he's aware of some issue here?

I wonder if there's an issue with the API key generation. I changed my `api_secret_token` and then tried to regenerate the API key in my profile, but the API key never changed.

**Comment by NateWr** [comment]
It looks like when an API key was generated it was saved to the database then immediately removed. The UI didn't reflect this since it always generated a token to display to the user regardless of whether one existed or not.

I've addressed that and updated the form so that it shows the correct API token after a new one is generated, and no token if there's no apiKey that's been saved yet.

PR:
https://github.com/pkp/pkp-lib/pull/5913

Tests:
https://github.com/pkp/ojs/pull/2770
