### ISSUE TITLE
Call to undefined method AuthorDAO::getBySubmissionId()

### ISSUE THREAD

**Issue by hsh01** [pkp/pkp-lib#5646]
Call to undefined method AuthorDAO::getBySubmissionId()
https://github.com/pkp/pkp-lib/blob/7512f177af2cb7398f283912548d1c4c84b28a00/classes/submission/PKPAuthorDAO.inc.php#L157

Must be $authors = $this->getByPublicationId($submissionId, false, false);

**Comment by asmecher** [comment]
@hsh01, the publication ID and the submission ID aren't the same thing. Do you have a use case for a call to this function? I don't think it's currently used in the OJS codebase so I might actually just remove it.

**Comment by hsh01** [comment]
I understand that is different things, in an example did not rename variable. I use this function in my own plugin and it gived error. I just shared.  

> @hsh01, the publication ID and the submission ID aren't the same thing. Do you have a use case for a call to this function? I don't think it's currently used in the OJS codebase so I might actually just remove it.

**Comment by asmecher** [comment]
@hsh01, could you try the following change? It preserves the goal and usage of the original function. I'm not sure if this suits the needs of your plugin, though.

[i5646.diff.txt](https://github.com/pkp/pkp-lib/files/4360398/i5646.diff.txt)

**Comment by hsh01** [comment]
My needs is just remove all authors from given submission.
There is mistake in your code, I corrected it: [diff.txt](https://github.com/pkp/pkp-lib/files/4361223/diff.txt).

It turns out that one submission may have several publications?

**Comment by asmecher** [comment]
Whoops, thanks, I've committed the change along with the fix you pointed out: https://github.com/pkp/pkp-lib/commit/65c97407a5232f49dab56c723d1eb6685412a264

Yes, one submission can have several publications; starting with OJS 3.2, OJS tracks metadata changes, and that's why the new `Publication` relationship has been introduced. You can use `$submission->getCurrentPublication()` to get the current publication but there may be other (older) ones as well.
