### ISSUE TITLE
Update customLocale plugin back-end UI

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#5647]
The customLocale plugin requires usability improvements to the Journal Manager back-end UI.

- [x] Update pagination in edit modal
- [x] Give user feedback on changes

**Comment by ewhanson** [comment]
Hi @NateWr, I went through and addressed these changes. Would you be able to take a look and let me know what you think? ewhanson/customLocale@32646b1 Thanks.

**Comment by NateWr** [comment]
Looks really good, nice work! I especially like the careful work you've done in spacing and positioning the items. Looks really clean and clear. :+1: 

A couple of minor suggestions, take them or leave them:

1. The `<div class="customLocale__keyHeader">Default Text</div>` should be a `<label>` for accessibility and it needs to be linked to the input field. So that looks like `<label ... :for="'default-text-' + {{ i }}">...</label><input ... :id="'default-text-' + {{ i }}" />`. Same for the custom text field/label.
2. I think you hide the "Default text" and "Custom Text" labels for every field. That will make the forms much more compact. You can hide them (but keep them available for screen readers) by adding the `-screenReader` class to each `<label>`. My sense is that because default text is disabled, it is clear enough what the user should do. But this is a judgement call either way.
3. Because the search input doesn't search as soon as the user types, it might be worth adding a search button. Not all users will not to hit enter.
4. `Displaying 16 of 16 results.` --> `Displaying 16 of 16 results for "about"`.

**Comment by ewhanson** [comment]
Thanks for the feedback!

I've implemented the changes you suggested. ewhanson/customLocale@66f5764 I agree on point 2. I think having the form be more compact is for the best, especially given how many keys there can be per file.

**Comment by ewhanson** [comment]
Hi @NateWr, what are the next steps for getting this ready for the plugin gallery? Thanks.

**Comment by NateWr** [comment]
I think the first step is to figure out where the plugin will live. I suspect that's `pkp/customLocale` but check with James or Michael about where they want it.

Then you can follow the steps in the Plugin Guide for releasing a plugin: https://docs.pkp.sfu.ca/dev/plugin-guide/en/release

**Comment by asmecher** [comment]
I'm content to have it live at `asmecher/customLocale` for now, and then transfer that to `pkp/customLocale` when it's ready for an "official" release. I'm OK to continue it as a fork of `langsci/customLocale` to reflect that this is its original source.
