### ISSUE TITLE
Username with dot (.) in the midle

### ISSUE THREAD

**Issue by respinosagonzalez** [pkp/pkp-lib#5687]
Usernames in our University are in format <name>.<familyname>
To use this format in OJS, we need change the regexp in line 31 in FormValidatorUsername.inc.php file every minor, release, build published.

Our proposed solution is:
File: ./lib/pkp/classes/form/validation/FormValidatorUsername.inc.php
Line 31:

(actual)		        new ValidatorRegExp('/^[a-z0-9]+([\-_][a-z0-9]+)*$/')

(proposed)		new ValidatorRegExp('/^[a-z0-9]+([\-._][a-z0-9]+)*$/')  

I'm Technical Support for http:/revistas.uclm.es

Regards

**Comment by asmecher** [comment]
@respinosagonzalez, this overlaps with https://github.com/pkp/pkp-lib/issues/906 -- could you add your suggestions there?

I suspect we'll probably decide to go with email addresses instead of usernames when we get around to addressing this, and in the meantime, I'd recommend keeping your local modification.
