### ISSUE TITLE
[OJS] public identifier plugin auto-assigns DOIs to back-issue content

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#569]
When the public identifier plugin is configured in OJS, one unintended consequence of the plugin is that it will automatically assign DOIs to content from previous journal issues _as content is accessed_. This is counter-intuitive or, at the very least, easy to overlook. As a result, many users end up with old articles having unregistered DOIs. 

The system should allow for restrictions to be placed on DOI creation from the a certain point forward. Conversely, it should also allow for an obvious method for applying DOIs to all back content at once (I say obvious here, because "Reassign DOIs" is not at all obvious).

**Comment by asmecher** [comment]
@AhemNason, we had a similar thing happening with copyrights -- they were affixed when the content was first accessed by a reader (think of this as the "Schrodinger's Cat" approach). We changed to assigning only when content is published instead. We could use a similar approach for DOIs -- but personally, I'm tempted to change this e.g. at the OJS 3.0 level rather than disrupting the 2.x code.

**Comment by bozana** [comment]
@AhemNason, I am not sure that I fully understand the issue, but maybe to mention it here however: there is a possibility to mark the (whole) issues (also articles, galleys and supp files) that should not get the DOIs i.e. to exclude them from the DOI assignment.

**Comment by mfelczak** [comment]
@AhemNason, is this still an issue in OJS 3.1?

**Comment by bozana** [comment]
Maybe comment from me as well: we changed the concept in 3.x because of this issue :-D The DOIs have to be explicitly/manually assigned i.e. no automatic assignments any more :-)
