### ISSUE TITLE
[OPS] Number of Active queue doesn't match actual queue

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5712]
**Describe the bug**
The number that appears in the "Active" tab, indicating the number of active preprints, doesn't match the real queue.

**To Reproduce**
1. Have several active preprints (my example has 3)
2. Go to 'Submissions'
3. Click on 'Active'
4. Check that number doesn't match.

**What application are you using?**
Open Preprint Systems 3.2.0 Beta

**Additional information**
![image](https://user-images.githubusercontent.com/4059679/78789566-adb1aa80-7983-11ea-90a1-b471054b8128.png)

I noticed this is also happening on the "My Queue" list. It says 3 but I only have 2 preprints listed there.

**Comment by NateWr** [comment]
Usually this means that one or more submissions have a data error which is causing the template render to fail. In effect, the submission exists but it isn't being displayed due to an error.

If you have a test database that reproduces this that you can share (privately on slack) we could probably identify the issue.

**Comment by rondinelisaad** [comment]
Hello @NateWr,
We have a test database. When you say to share it, you say to share the database dump?
Regards,

**Comment by NateWr** [comment]
Yes, if you can share a database dump that would be great. You can find me at @NateWr on forum.pkp.sfu.ca and send it as a private message there.

**Comment by rondinelisaad** [comment]
Hello @NateWr, how are you?
I sent it for you at PKP workspace in slack.

**Comment by NateWr** [comment]
Hi @alexxxmendonca and @rondinelisaad,

Thanks for the database bump. I was able to load that up and figure out the source of the problem. It looks like the submissions which are not appearing are all incomplete submissions. This means that they have begun the submission progress (`submissionProgress > 0`) but not yet finalized submission.

During this time, the `stageId` for each submission is `1`, which corresponds to the submission stage. However, since no such stage exists in OPS, this is causing an error in the submissions lists whenever they rely on the `activeStage`.

@ajnyga this sounds vaguely familiar to me. Have we resolved this somehow? I'm thinking there are two ways to handle this:

1. Modify `SubmissionsListItem.vue` to account for cases where there is no `activeStage` (probably just not showing those parts of the template). Maybe even checking `submissionProgress` and showing "In Progress" instead.
2. Add a dummy submission stage back in to the submission list items (but not the workflow) so that during submission they're identified as such.

**Comment by ajnyga** [comment]
hmm, I have an idea what is going on probably.

Since OPS only has one stage (production), the submission form step 4 now sends the submissions straight to production stage. BUT for the submissions that are unfinished the stage is still "submission".

In OJS the unfinished submissions are probably showing ok, because they are in the Submission stage and that stage exists in OJS. But since it does not exist in OPS, the list is not showing them.

Nate, I wonder if I could just send the submission to production stage when it is initially created?

**Comment by NateWr** [comment]
I don't see any reason why not, but you know OPS better. Presumably Production is where any editorial approval happens anyway?

One thing to consider is that probably the lists should identify when a submission is incomplete. Maybe you can add replace the stage details with "In Progress" when it hasn't been finalized?

I think you could put all of these lines into a `<template v-if="!item.submissionProgress">` and then just add the "In Progress" badge where the stage badge would normally be?

**Comment by ajnyga** [comment]
Was just thinking if stepping through the submission form with a submission that is already in production stage would cause problems, but probably not. Yes, all decisions are made in the production stage in OPS. Of course with the new `publications` design the stage is not that important. I mean it could be submission stage as well now.

**Comment by alexxxmendonca** [comment]
Thanks @NateWr for figuring it out and @ajnyga for working on it.

**Comment by ajnyga** [comment]
So it seems that moving the submission straight to production stage already in submission step 1 is not causing any trouble. 

<img width="1136" alt="Screenshot 2020-04-16 at 12 43 12" src="https://user-images.githubusercontent.com/16347527/79441776-572a1900-7fe0-11ea-9d2d-f273e5281d26.png">

**Comment by NateWr** [comment]
@ajnyga can this issue be closed now?
