### ISSUE TITLE
[OPS] Unable to delete Series/Section

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5749]
**Describe the bug**
Me as a Server Administrator an unable to delete an existing Series/Section. The only preprint that was associated to it was deleted before doing this. Therefore there are no preprints associated to it.

Error log (it's repeated several times due to several repeated clicks):

`[Fri Apr 17 09:30:11.027083 2020] [php7:error] [pid 14468] [client 192.168.1.71:54905] PHP Fatal error: Uncaught Exception: DB Error: Unknown column ‘section_id’ in ‘where clause’ Query: SELECT submission_id FROM submissions WHERE section_id = ? AND context_id = ? in /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/db/DAO.inc.php:703\nStack trace:\n#0 /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/db/DAO.inc.php(103): DAO->handleError(Object(ADODB_mysqli), ‘SELECT submissi...’)\n#1 /var/www/preprints_scielo_org/htdocs/controllers/grid/settings/sections/SectionGridHandler.inc.php(226): DAO->retrieve(‘SELECT submissi...’, Array)\n#2 /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/core/PKPRouter.inc.php(391): SectionGridHandler->deleteSection(Array, Object(Request))\n#3 /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array)\n#4 /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route(Object(Request))\n#5 /var/www/preprints_scielo_org/htdocs/lib in /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/db/DAO.inc.php on line 703, referer: https://preprints.scielo.org/index.php/scielo/management/settings/context`

**To Reproduce**
1. Create a Series/Section
2. Submit a preprint to it
3. Delete the preprint
4. Attempt to delete the Series.

**What application are you using?**
Open Preprint Systems 3.2.0.1

**Additional information**
![Server Settings](https://user-images.githubusercontent.com/4059679/79572107-c3fdeb80-8092-11ea-86af-49c8948ef6dd.gif)

**Comment by ajnyga** [comment]
It is caused by deleteSection here https://github.com/pkp/ops/blob/master/controllers/grid/settings/sections/SectionGridHandler.inc.php#L226

The reason is that the schema for 3.2.0 stable is missing the `section_id` field. What I do not understand is that the section_id field is available in the master branch version of the schema. Some things like the submissions table were moved in end of February, @asmecher should there or should there not be a section_id field in submissions table?

However, even if the `section_id` would be there, I do not think that check made in the code is valid anymore with the current `publications` model. The code is the same in OJS and probably also OMP.

**Comment by asmecher** [comment]
Fixed -- but I'll do a better job of cleaning this up in the `master` branch shortly. We shouldn't be embedding SQL queries directly in handlers like this.

**Comment by asmecher** [comment]
(For OPS 3.2.0-0 and 3.2.0-1, apply https://github.com/pkp/ops/commit/b30b4d35871114ef94d1b411aacb2b8815d811f8. For OJS 3.2.0-0, 3.2.0-1, and 3.2.0-2, apply https://github.com/pkp/ojs/commit/e7efceffbcc145e08ce0371a290e170029989f24. OMP is unaffected.)
