### ISSUE TITLE
Add missing int casts to IssueDAO

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#578]
See e.g. http://forum.pkp.sfu.ca/t/error-in-processing-log-files/1832/2

**Comment by asmecher** [comment]
Pull: https://github.com/pkp/ojs/pull/529

**Comment by ctgraham** [comment]
In http://forum.pkp.sfu.ca/t/error-in-processing-log-files/1832/2, the URL of http://www.italian-journal-of-mammalogy.it/issue/view/Special&20issue:%20IX%20ATIt%20Congress resolves.  I assume this is native 2.x functionality for a custom issue id.  What happens if the issue identifier is "10 Little Piggies"?  That will successfully cast as 10, but we wouldn't want a simple cast to allow a match to issue_id 10.

**Comment by asmecher** [comment]
@ctgraham, I think this fix solves that risk:
https://github.com/pkp/ojs/commit/a73ca333621a822f2fed49e2c285910168199e6f

**Comment by asmecher** [comment]
Merged and cherry-picked. Already OK in OJS master.
