### ISSUE TITLE
Ability to add new columns to a grid and creating new tab forms

### ISSUE THREAD

**Issue by salmanm2003** [pkp/pkp-lib#5806]
Hi,

As part of my work on this issue: [https://github.com/pkp/pkp-lib/issues/5702](url)
I have two problems that block me to complete the plugin:

1. OJS doesn't give the ability to add new columns to Journals Sections grid, as there are no hooks available to do so. 
this been discussed already here: [https://forum.pkp.sfu.ca/t/add-new-column-to-sections-grid/60148](url)

2. I could add a new tab to Workflow Settings, but not sure how to add a new form to it as a content  and not sure which hooks to use (I couldn't find any documentation or examples about). 

I am using OJS 3.2.0-2.

**Comment by NateWr** [comment]
Hi @salmanm2003,

Sorry if there was some confusion, but I think the features described in #5702 should be added to the core application. You only need to use hooks if you are adding the feature through a plugin.

If that doesn't address your needs, let's continue the discussion over on #5702 so that all the conversation is centralized there. (Also, I'll get notifications on #5702 as soon as you post, but I only check new issues once a week or so). I'll be happy to answer any questions to get you up-and-running on that issue.
