### ISSUE TITLE
[OJS] E-mail message journal URL lacks protocol specification

### ISSUE THREAD

**Issue by quartelmestre** [pkp/pkp-lib#5807]
**Describe the bug**
Automatic e-mail messages for password recovery do not include the full URL. The protocol is omitted -- that is, instead of **https://journal/...**, the message shows **//journal/...**

**To Reproduce**
1. Go to login screen
2. Click on password recovery

**What application are you using?**
 OJS 3.2.0-2

**Additional information**

![Screenshot_20200430_164253](https://user-images.githubusercontent.com/20466765/80752333-b3715a80-8b01-11ea-8f1a-93d43f1684e9.png)

As a workaround, I have manually added **https://** just before the **{url}** field in the message text. However, this error may affect other message texts.

**Comment by asmecher** [comment]
@quartelmestre, have a look at this forum thread:
https://forum.pkp.sfu.ca/t/ojs-3-2-0-ojs-generates-protocol-relative-urls-in-notification-e-mails/59688

The problem there turned out to be a local modification of OJS that extended the use of protocol-relative URLs to unintended parts of OJS, including emails. OJS should only be using protocol-relatives in compiled CSS. I suspect the modification was made [here](https://github.com/pkp/pkp-lib/blob/c9bc6891f565e876c534c9a7a6168307128a29d1/classes/core/PKPRequest.inc.php#L151) to turn the default for `$allowProtocolRelative` from `false` to `true`.

Is there a chance you've got a similar modification in your install?

**Comment by asmecher** [comment]
Alternately, do you have protocol-relative URLs in any `base_url[...]` settings in `config.inc.php`?

**Comment by quartelmestre** [comment]
@asmecher , we don't use base_url in our config.

However, we do indeed use the patch to work behind a reverse proxy. When I first installed v3.2.0, one of the problems we had was that several components of the page would not load (circling icon). When I applied this patch, all components would load. I kept the patch when upgrading to -1 and -2.

After your comment above, I reversed the patch, but the original problem is still there:

![Screenshot_20200430_170658](https://user-images.githubusercontent.com/20466765/80754602-ace4e200-8b05-11ea-8da3-658362f3ded8.png)

**Comment by asmecher** [comment]
@quartelmestre, OK, I'll close this issue -- but is there a discussion e.g. in the forum of the loading issue where I can catch up on those details? If so, please drop the link here.

**Comment by quartelmestre** [comment]
@asmecher , an update. I installed v3.2.0-3 today, with no patches. Almost everything went well, except for the bug in my last comment, above. I then applied one patch from previous versions: added *$_SERVER['HTTPS'] = 'on';* to /index.php. All page elements are loading correctly, and the e-mail messages include their protocols in the URL fields.

**Comment by asmecher** [comment]
@quartelmestre, I'd like to know more about this, but I think the support forum is a better place; could you post information about the problem, and how you solved it, over there? I'm not sure yet whether it'll be an opportunity for a code change that gets shipped with OJS.

**Comment by quartelmestre** [comment]
Sure, @asmecher . Here it is:  https://forum.pkp.sfu.ca/t/ojs-3-2-0-3-spinning-circle-https-problems-and-workaround/60281 . Thanks!
