### ISSUE TITLE
[OPS] Unable to revert "Reject" decision

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5819]
**Describe the bug**
I am unable to revert a decision of a preprint that's been rejected.

While the option "Change decision" is there, when I click on it, only the "Decline submission" button appears and there is nothing else that can be done to revert the decision.

Also, even though the "Schedule for publication" is there, I am unable to publish the preprint since it is still rejected.

**To Reproduce**
1. Go to a rejected preprint.
2. Click on 'Change decision'
3. Notice how no option to revert the decision actually appears.
4. Try to publish the preprint and notice how the system doesn't publish preprints that have a "Rejected" decision.

**What application are you using?**
Open Preprint Systems 3.2.0.1

**Additional information**
![Malfitano et al ; Terapia ocupacional em tempos de pandemia_ Seguridade social e garantias de um cotidiano possível para todos](https://user-images.githubusercontent.com/4059679/81095415-5bf53500-8edb-11ea-8e44-439b268f0d91.gif)

**Comment by NateWr** [comment]
cc @ajnyga

**Comment by ajnyga** [comment]
I do not think there has ever been a "revert declined submission" action in OJS?

We can add it, but we need to add it to all applications I think?

**Comment by NateWr** [comment]
I think the difference is that in other applications there are other editorial decisions that can be made in other stages, so this hasn't come up before. Basically, someone can take a submission in the review stage, decline it, then accept it and it _kind of_ works. (See #5798.)

This only crops up in OPS because there's only the production stage. Adding something in there should do the trick, and we can leave the broader cross-application thing to #5798.

**Comment by ajnyga** [comment]
ok, so I would just implement a "Revert decline decision" action for OPS for now?

**Comment by ajnyga** [comment]
(happy to hear a good label name in English...)

**Comment by alexxxmendonca** [comment]
Maybe there is no need for a reword.

"Change decision" works fine, but as @NateWr said, there are no other decisions in OPS so perhaps by clicking on "Change decision" alone, that alone should un-reject the paper?

**Comment by alexxxmendonca** [comment]
@ajnyga on that note, I think it could be related but preprint published is not considered as "accepted".

This is reflected on the "Editorial Activity" data too, more specifically on:

Submissions Accepted
Days to First Editorial Decision
Days to Accept

Given that a preprint never goes through "acceptance" stage (there is no editorial letter being sent), the system is not considering a posted/published preprint as "accepted".

**Comment by NateWr** [comment]
I think this would be appropriate to have in all applications. A decline could be done by accident. @asmecher any objections to adding this to pkp-lib for all apps.

A couple of things to check with this:

1. How does a revert decline decision effect editorial statistics? You'll need to do some thinking about how this should effect stats. My first impression is that the submission shouldn't be counted in the three "Submissions Declined" and "Rejection Rate" stats (even if the original decline decision occurred within the date range and the revert decision occurred outside of it). The "Days to X" stats should include the decline decision, even if it's later been reverted, as the original decline still counts as a first decision.

2. What happens to the active stage when a decline decision is reverted? I don't think a decline decision modifies the `stageId`. But test it out to see what happens when it's declined when in different stages. I suppose the revert decision should not modify the stage it was in before it was declined.

**Comment by alexxxmendonca** [comment]
> How does a revert decline decision effect editorial statistics? You'll need to do some thinking about how this should effect stats. My first impression is that the submission shouldn't be counted in the three "Submissions Declined" and "Rejection Rate" stats (even if the original decline decision occurred within the date range and the revert decision occurred outside of it).

I agree with this.

> The "Days to X" stats should include the decline decision, even if it's later been reverted, as the original decline still counts as a first decision.

I am not sure I understood what you meant here.

**Comment by ajnyga** [comment]
2. did not come up yet because I have only tested this with OPS so far where you only have one stage. I would image that it will just return to the stage where it as declined in in OJS.

Btw. what happens in OJS if you decline a published submission, is that possible? I am thinking what status should the revert decline action give to a submission. Can we know whether the submission was in STATUS_SCHEDULED, STATUS_QUEUED or STATUS_PUBLISHED before it was declined?

**Comment by asmecher** [comment]
@NateWr, I agree with [your analysis](https://github.com/pkp/pkp-lib/issues/5819#issuecomment-722411507).

> Btw. what happens in OJS if you decline a published submission, is that possible? I am thinking what status should the revert decline action give to a submission. Can we know whether the submission was in STATUS_SCHEDULED, STATUS_QUEUED or STATUS_PUBLISHED before it was declined?

Hmm, I would propose that we block the Rejection of a published submission; the user would need to unpublish first. This would reinforce the separation between "academic" decision-making and "distribution" decision-making. If the rejected submission was un-rejected, then it would return to its unpublished state. No surprises to the user. It would reduce the number of points at which a submission could be unpublished, and force a double-check on a decision that should be very uncommon.

**Comment by ajnyga** [comment]
Did you consider that a preprint might have multiple published versions? But I agree that we need to distinguish between rejection and unpublishing submission.

But I will use STATUS_QUEUED and start preparing a pr for all three apps.

**Comment by NateWr** [comment]
I agree for OJS/OMP that it should not be possible to enter a reject decision on a published submission. I think that this must hold for OPS as well. If there is a case where a new version of a posted preprint is not accepted, I don't think that we can use the editor decisions to record this, because editor decisions are recorded against the submission not the publication. The editors should just use discussions to talk with authors about problems with subsequent versions.

**Comment by ajnyga** [comment]
OPS: https://github.com/pkp/ops/pull/79
pkp-lib: https://github.com/pkp/pkp-lib/pull/6354

**Comment by ajnyga** [comment]
OPS: pkp/ops#79
pkp-lib: #6401

Rebased and running tests, ping @asmecher @NateWr

**Comment by asmecher** [comment]
Thanks, @ajnyga! I think there are two things outstanding on this...
- Consideration of stats, and
- Port to OJS/OMP

I'm on the fence about sneaking this into 3.3.0rc2 (planned for Dec 7) -- @ajnyga, do you have time to work on this, and do you have an opinion either way on 3.3.0rc2 vs. 3.3.1?

**Comment by ajnyga** [comment]
@asmecher discussed the stats issue with @NateWr and it seems the code already works like Nate described above, so no changes needed.

Running tests:
OMP https://github.com/pkp/omp/pull/891
OJS: https://github.com/pkp/ojs/pull/2936
OPS: https://github.com/pkp/ops/pull/79
pkp-lib: https://github.com/pkp/pkp-lib/pull/6401

**Comment by NateWr** [comment]
@asmecher I reviewed this and decided to merge it in time for RC2. I hope that's ok. It's a surprisingly light addition and will benefit from the planned testing on RC2. I did some tests on the stats and couldn't find anything unusual as I declined and reverted the decline. I think we're good on that front.

I'll update the change orientation and add a testing script for this.

**Comment by asmecher** [comment]
Great, no objections -- thanks, @ajnyga and @NateWr (and @alexxxmendonca for helping shape this)!
