### ISSUE TITLE
Dashboard menu links out of line

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#5822]
In OJS 3.2.0-2, when you hover over some of the main links in the dashboard, the sub-links appear below the main link instead of in-line with it, so when you move your mouse over to click a sub-menu link, your mouse goes into blank space and the links disappear. This means you cannot visit some of the pages in the dashboard because you can't click on them to open them.  

Please see the screenshot as an example with the Statistics menu.  I have also seen it happen with the Tools menu on another site.  It doesn't seem to happen consistently on every OJS 3.2.0 site.

<img width="653" alt="Menus not in line" src="https://user-images.githubusercontent.com/35044512/81125540-0d0cc700-8efe-11ea-8a11-e5ccbe11a587.png">

**Comment by NateWr** [comment]
On sites where this happens, does it happen all the time? Or if you reload does it go away? Can you send me (privately) access to a site where it is occurring?

**Comment by amandastevens** [comment]
You can see it if you log in to the [OJS 3.2 testdrive site](https://demo.publicknowledgeproject.org/ojs3/testdrive).  I will send you another example. It doesn't go away if I reload the page.  I accessed both of these sites the day I filed the issue and encountered the issue and today I'm seeing the same thing.  But I can't say if it happens all the time.

**Comment by kshuttle** [comment]
I am experiencing this issue with a journal in Firefox - the same menu item as reported above (Statistics) is out of line and I am unable to click on the submenu items. I loaded the journal dashboard in Chrome and the issue is not appearing there. The misalignment happens when the browser is zoomed in at 100% or higher. When I zoom out in the browser and make the website text smaller, the alignment issue is resolved.
