### ISSUE TITLE
Publication and Submission State inconsistency

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5837]
**To Reproduce**
1. Assign a Submission's Publication to an Issue.
2. Schedule the Publication for Publish
2. Publish the assigned Issue
3. Unpublish the assigned Issue
4. Preview the unpublished Issue - The submission will not be displayed.

**What application are you using?**
 OJS version 3.2.x

**See also**
https://forum.pkp.sfu.ca/t/ojs-3-2-0-3-problem-with-unpublish-issue-after-upgrade-with-postgres/60337

**Comment by defstat** [comment]
It seems that there is an inconsistency between the statuses of the Publication objects and their related Submission object. I am adding a state diagram describing what seems to be happening,

![image](https://user-images.githubusercontent.com/560456/81314621-01eaa000-9092-11ea-9fe1-fddb599d427b.png)

The action of `Issue::Publish` and `Issue::Unpublish` works differently for Publications and Submissions.

The `Issue::View` action only displays the submissions that are of `status=3`.
That means that
1. If the assigned issue is not already published, a newly assigned Publication is not going to get displayed, even if it is `scheduled for publication` on that issue.
2. If an `Issue::Unpublish` action is performed on an published Issue, then its respective publications will remain at `status=3` but their submissions will get `status=1` which means that they will not be displayed anymore on the Issue view page
3. Even if the same issue (of case 2) is published again, the submissions will not show, because they seem to keep their `status=1` 

There is a workaround for that: the user can unpublish and republish the publications of the unpublished Issue, and then publish it.

**Comment by NateWr** [comment]
Thanks @defstat, good catch! It sounds like the only missing piece here is that when an issue is unpublished, it should reset the status of any published submissions and publications to scheduled (5). So there should be logic like this:

- Get all submissions in the issue.
- For each submission, get all the publications
- For each publication, if the status is published (3), set the status to scheduled (5).
- For each submission, if it has at least one publication that is scheduled (5), set its status to scheduled (5). Otherwise, set its status to queued (1).

I think this last case, where a submission has no scheduled publications, should never arise. But it's good to add it in just to be safe. It's always possible that someone has done something non-standard in how a submission has been published.

**Comment by defstat** [comment]
@NateWr, @asmecher 

The PR changes the following:
- Development of the **Image 1** from the https://github.com/pkp/pkp-lib/issues/5837#issuecomment-625341494
- Fixes the "Preview Issue" problem by allowing the `STATUS_SCHEDULED` submissions to be displayed.
- Fixes the "Items count" problem - now the Issue "Items" column at the Issues Grid is set to the number of submissions that will be displayed when previewing or viewing the issue.

**PRs**
[OJS]: pkp/ojs#2743

If we are ok with the state transitions, i will develop a test for that.

**Comment by asmecher** [comment]
Thanks for the attention to detail on this, @defstat and @NateWr!

I'm wary of batch-setting the status of previous publications; I tend to think of them as archived and invariant. However, I suppose the underlying problem is that the Publish/Unpublish button affects both Submissions and Publications at the same time. Do we need to consider breaking those two up into separate actions? That way the Submissions publish/unpublish affects the entire thing's visibility, and the Publication publish/unpublish is for versioning. (This is starting to rhyme a little with Publication Formats in OMP.)

**Comment by NateWr** [comment]
> Do we need to consider breaking those two up into separate actions?

I'm not sure this is a good idea. If we break them up, it would be possible for someone to end up in a situation where a submission was published but it had no published publications. 

This works for publication formats because someone might want to publish a catalog entry without any formats. But a submission without a publication is a condition that we do not permit. Allowing this would provide all kinds of complications in the UI -- what is a submission with no title, author, etc?

One important distinction is that we are not resetting the status of _all_ publications of a submission. We are only changing the status of publications that are scheduled/published and in that issue. I think this is precisely the roll that issues play in OJS: they batch control the published/unpublished status of submissions.

One of the weird cases that @defstat and I discussed is a case where a submission has two publications and each one is assigned to a different issue. Not ideal but technically possible. In such cases, the current logic will ensure that unpublishing an issue won't unpublish the submission if its published in another published issue.

This is one of the benefits of tying a submission's status to the status of its publications. We can publish/unpublish publications without having to worry about whether or not we should be changing a submission's status. It will always check its publications and set its status appropriately.

**Comment by asmecher** [comment]
OK, thanks -- I'm content to go ahead with this as proposed. The submission/publication status is an opportunity for discrepancy but I don't have a better idea yet how to fix it.

**Comment by NateWr** [comment]
Thanks @defstat! I've merged this and moved it to the 3.3 milestone. The only task left is to write a test which covers this case.

**Comment by defstat** [comment]
@NateWr 

**PR**
[stable 3.2.0]
[OJS]: pkp/ojs#2776

**Comment by asmecher** [comment]
> Thanks @defstat! I've merged this and moved it to the 3.3 milestone.

If it's merged to `master`, it'll go out in 3.2.1; is that what you intended?

**Comment by NateWr** [comment]
Yeah sorry for the confusion. What's merged should go out in 3.2.1, but we also want to write a test case to cover this. Would you prefer that this stays in the 3.2.1 milestone and we file a new issue for the test?

**Comment by asmecher** [comment]
> Would you prefer that this stays in the 3.2.1 milestone and we file a new issue for the test?

Yes, please -- I sometimes use the closed issue list when making the changelog, so that would help ensure it's captured.

**Comment by NateWr** [comment]
:+1: Got it. I've put this back onto the 3.2.1 milestone and filed a new issue with the tests at https://github.com/pkp/pkp-lib/issues/5948.
