### ISSUE TITLE
[OJS] emailHeader and emailSignature should both be localized

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#585]
Not sure why these aren't localized at all - there are translations in the locale files with text for the default emailHeader at least. But they aren't localizable in the UI itself. 

(Flagging against 2.4.6-1, but if it's a tricky bug to fix, 2.4.7 should be fine)

**Comment by asmecher** [comment]
I'm ambivalent about translating this -- the header/footer is kind of a disclaimer so that users can't impersonate the primary contact. Once localized, the language used will depend on what locale the user is browsing the journal in, which seems kind of strange to me. Have you gotten specific feedback on this?

**Comment by jmacgreg** [comment]
Nope, just something I've run into while enabling SPF-related stuff for a multi-lingual journal. My current solution has been to add the disclaimer in the field in both en and fr, but this seems weird given the other localized fields there.

**Comment by asmecher** [comment]
I think this might have unintended consequences. The bilingual message is actually not a bad idea. Closing for now.
