### ISSUE TITLE
[OJS] Let journal managers set the PLN Network location

### ISSUE THREAD

**Issue by ubermichael** [pkp/pkp-lib#586]
Journal managers should be able to set the PLN network URL on a journal-by-journal basis. It should default to http://pkp-pln.lib.sfu.ca, which is the a defined constant in the current code.

 * Add a field to the PLN settings form
 * save the network url in the plugin_settings table, and make use of it everywhere that PLN_NETWORK_URL was used.

Patch to follow.

**Comment by ubermichael** [comment]
There is a preliminary patch here: https://github.com/pkp/ojs/compare/ojs-dev-2_4...ubermichael:ojs-dev-2_4-gh586

Feedback and suggestions are welcome.

**Comment by asmecher** [comment]
A couple of quick comments:
- For references, use `$a =& $b->c();` instead of `$a = & $b->c()` (spacing differences)
- I've emailed back and forth with @mjordan today about specifying another default network in the config.inc.php file for users who plan to manage a lot of journals in an install that might have a national LOCKSS network. That'll mean a little bit of work here.

**Comment by ubermichael** [comment]
This should have closed automatically after the merge.
