### ISSUE TITLE
OMP site wide search

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5886]
With https://github.com/pkp/pkp-lib/issues/5784 OMP will also need a site wide search.

In OMP the search is within the CatalogHandler. The only obstacle is the `ContextRequiredPolicy` in `PKPCatalogHandler`. 
Possible routes: 
a) move OMP search to a separate search handler or 
b) loosen the PKPCatalogHandler authorization policies, ie. make `ContextRequiredPolicy` conditional.

Worth thinking is that do we want to have the CatalogHandler available in site level. Should we have for example Series browse feature in the site level?

ping @asmecher @NateWr

**Comment by asmecher** [comment]
There's potential for making `CatalogHandler` site-wide, but we don't have a user asking for it yet and I'd want to look into sharing aspects of the equivalent handlers across the app in order to do that. So I'd suggest tackling this by trying to align OMP's search handling closer to OJS/OPS, which would set the stage for a second phase if we need it.

**Comment by NateWr** [comment]
Agreed, a base `/search` route with its own handler that can be shared across apps for everything except going and getting the results from the database seems best to me.

**Comment by ajnyga** [comment]
@asmecher tests for this one seem to be passing (one still running but all the rest are ok):

https://github.com/pkp/omp/pull/830

This moves the OMP search from the catalogHandler to an own searchHandler and allows site level searching.

**Comment by asmecher** [comment]
Merged, thanks!
