### ISSUE TITLE
[OJS 3.1.2.1] Native XML Import - More informative errors

### ISSUE THREAD

**Issue by galexioza** [pkp/pkp-lib#5995]
When importing large number of articles you get errors like this:

`The author does not have a given name in the submission's language, English. The submission can not be imported without this information.`

It would be great if these error messages could include some more information so that the problem can be more easily fixed, such as what the article name is that the error relates to.

**Comment by asmecher** [comment]
@galexioza, which of our applications are you using, and what version?

**Comment by galexioza** [comment]
@asmecher That would help. I'll update the title.

**Comment by asmecher** [comment]
@galexioza, that appears to have already been fixed in subsequent releases by this change: https://github.com/pkp/pkp-lib/commit/bdb830b0a9d1fe2288c0dbfb5f763d07b106abab#diff-5dd9630a81f2583c22107b46e5ce9966R480

I'd recommend upgrading -- we're planning to release OJS 3.2.1 late this Friday, if that helps.
