### ISSUE TITLE
[OJS 3.2.1.0RC] Login doesn't work in firefox

### ISSUE THREAD

**Issue by epistemehealth** [pkp/pkp-lib#5996]
**Describe the bug**
When logging into a test instance of OJS 3.2.1.0 RC using firefox, logging in just refreshes the page.
However, the login page works in Chrome.

**To Reproduce**
Attempt to login using firefox.

**What application are you using?**
 OJS 3.2.1.0 RC
Windows 10, Firefox 77.0.1 vs Chrome 

**Additional information**
Can't see any errors in server PHP logs. Console in Firefox is only displaying a bunch of CSS warnings.  The same browser works for logging into previous versions of OJS, including OJS 3.1 (same server) or OJS 3.2.x testdrive hosted by PKP.

Has anyone else tried testing the release candidate using firefox?

**Comment by heike-r** [comment]
Hi,
we had similar problems (just refreshing of the page but no login and no error messages) in Firefox but with two identical instances of OJS3.1. For us, the problem was that both systems (on the same server and in the same domain) tried to place a cookie with the same name. Login worked for the first system that placed the cookie, but not for the second one. Firefox got confused. The problem was solved by editing the config.inc.php and permanently change the cookie name for one system.

**Comment by asmecher** [comment]
Agreed, @heike-r probably has the solution. The specific setting to change is `session_cookie_name`. The session management code hasn't changed between 3.2.0 and 3.2.1. Please follow-up if that doesn't solve it and I'll re-open the issue.
