### ISSUE TITLE
A stalled request to plugins.xml can block subsequent http requests

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#5998]
**Describe the bug**
Today I ran into an issue where calls to https://pkp.sfu.ca/ojs/xml/plugins.xml are timing out. Looks like a server issue. The downside is that the single request plugins.xml for the plugin gallery blocked all other requests in OJS/OMP/OPS.

That means that it was not possible to save a setting under Settings > Website until this resolved, which took two minutes for me.

If possible, the request should be made in a non-blocking fashion so that a server outage on the PKP side will not cause wider problems in the applications.

**What application are you using?**
3.2 pre-release

**Comment by redukr** [comment]
i can confirm, that this bug is present in 3.2.0.3
forum.pkp.sfu.ca/t/error-while-try-to-open-settings-journal/61177/2

`[Mon Jun 15 14:41:11.639751 2020] [php7:warn] [pid 13807] [client 192.168.2.111:54680] PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /home/uars/web/uars.info/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/plugins/modifier.escape.php on line 39
[Mon Jun 15 14:44:49.515710 2020] [php7:warn] [pid 13818] [client 192.168.2.111:54948] PHP Warning:  fopen(http://pkp.sfu.ca/ojs/xml/ojs-version.xml?id=5b4b5d14d9ad4&amp;oai=https%3A%2F%2Fuars.info%2Findex.php%2Findex%2Foai): failed to open stream: Connection timed out in /home/uars/web/uars.info/public_html/lib/pkp/classes/file/FileWrapper.inc.php on line 70, referer: https://uars.info/index.php/uars/management/settings/workflow
[Mon Jun 15 14:44:49.516145 2020] [php7:error] [pid 13818] [client 192.168.2.111:54948] PHP Fatal error:  Uncaught Exception: DB Error: MySQL server has gone away Query: SELECT * FROM versions WHERE current = 1 in /home/uars/web/uars.info/public_html/lib/pkp/classes/db/DAO.inc.php:703\nStack trace:\n#0 /home/uars/web/uars.info/public_html/lib/pkp/classes/db/DAO.inc.php(103): DAO->handleError(Object(ADODB_mysqli), 'SELECT * FROM v...')\n#1 /home/uars/web/uars.info/public_html/lib/pkp/classes/site/VersionDAO.inc.php(42): DAO->retrieve('SELECT * FROM v...')\n#2 /home/uars/web/uars.info/public_html/lib/pkp/classes/site/VersionCheck.inc.php(54): VersionDAO->getCurrentVersion()\n#3 /home/uars/web/uars.info/public_html/lib/pkp/classes/site/VersionCheck.inc.php(197): VersionCheck::getCurrentDBVersion()\n#4 /home/uars/web/uars.info/public_html/lib/pkp/pages/management/ManagementHandler.inc.php(115): VersionCheck::checkIfNewVersionExists()\n#5 /home/uars/web/uars.info/public_html/lib/pkp/pages/management/ManagementHandler.inc.php(57): ManagementHandler->context(Array, Object(Request))\n#6 /home/uars/web/uars.info/public_html/lib/p in /home/uars/web/uars.info/public_html/lib/pkp/classes/db/DAO.inc.php on line 703, referer: https://uars.info/index.php/uars/management/settings/workflow
[Mon Jun 15 14:44:49.516432 2020] [php7:error] [pid 13818] [client 192.168.2.111:54948] PHP Fatal error:  Uncaught Exception: DB Error: MySQL server has gone away Query: UPDATE sessions\n\t\t\t\tSET\n\t\t\t\t\tuser_id = ?,\n\t\t\t\t\tip_address = ?,\n\t\t\t\t\tuser_agent = ?,\n\t\t\t\t\tcreated = ?,\n\t\t\t\t\tlast_used = ?,\n\t\t\t\t\tremember = ?,\n\t\t\t\t\tdata = ?,\n\t\t\t\t\tdomain = ?\n\t\t\t\tWHERE session_id = ? in /home/uars/web/uars.info/public_html/lib/pkp/classes/db/DAO.inc.php:703\nStack trace:\n#0 /home/uars/web/uars.info/public_html/lib/pkp/classes/db/DAO.inc.php(231): DAO->handleError(Object(ADODB_mysqli), 'UPDATE sessions...')\n#1 /home/uars/web/uars.info/public_html/lib/pkp/classes/session/SessionDAO.inc.php(109): DAO->update('UPDATE sessions...', Array)\n#2 /home/uars/web/uars.info/public_html/lib/pkp/classes/session/SessionManager.inc.php(185): SessionDAO->updateObject(Object(Session))\n#3 [internal function]: SessionManager->write('4v7dgj897jp1o9p...', 'csrf|a:2:{s:9:"...')\n#4 [internal function]: session_write_close()\n#5 {main}\n  thrown in /home/uars/web/uars.info/public_html/lib/pkp/classes/db/DAO.inc.php on line 703, referer: https://uars.info/index.php/uars/management/settings/workflow`

**Comment by asmecher** [comment]
The stack trace above suggests this is actually the OJS version descriptor that's stalling things, not the plugin gallery XML. I think it's [`MaintenanceForm::display`](https://github.com/pkp/pkp-lib/blob/3_2_0-3/classes/install/form/MaintenanceForm.inc.php#L37) that calls on this:
```
$templateMgr->assign('version', VersionCheck::getCurrentCodeVersion());
```
This is used to generate the "your OJS version is old" message. I think this server-side request could definitely be limited to a 10 second timeout, and possibly locally cached (or only occasionally checked).

**Comment by henriqueramos** [comment]
Hello @asmecher.

There's the pull requests for this issue on [OJS](https://github.com/pkp/ojs/pull/3240/files), [OMP](https://github.com/pkp/omp/pull/1036/files), [OPS](https://github.com/pkp/ops/pull/202) and [pkp-lib](https://github.com/pkp/pkp-lib/pull/7508/files).

**Comment by henriqueramos** [comment]
@asmecher updated the PRs.

[OJS](https://github.com/pkp/ojs/pull/3240/files), [OMP](https://github.com/pkp/omp/pull/1036/files), [OPS](https://github.com/pkp/ops/pull/202) and [pkp-lib](https://github.com/pkp/pkp-lib/pull/7508/files).

**Comment by asmecher** [comment]
It looks to me like the tests in the OJS, OMP, and OPS repos are identical, so they could be moved into pkp-lib in the `cypress/tests/integration/` directory.

**Comment by asmecher** [comment]
Merged! I've updated the submodules manually to work around a merge conflict for each.
