### ISSUE TITLE
Clarify prompt to unpublish a submission 

### ISSUE THREAD

**Issue by sssoz** [pkp/pkp-lib#6018]
# Describe the problem you would like to solve

Wording around the button + prompt to unpublish a submission is a bit confusing. 

The button says "Unpublish" (which is a clear action), but the question does not re-use the same vocabulary; the negative also doesn’t make it clear that by pressing "OK", we are unpublishing the submission. 

The two options (OK / Cancel) do not really answer the prompt directly.  

![6afb57b42b354147fcb83524e9f42945](https://user-images.githubusercontent.com/6668406/85046283-1db08e00-b188-11ea-8c0b-85ee6d2d2a11.gif)

# Describe the solution you'd like

Keep the "Unpublish" button; re-phrase the prompt to "Are you sure you want to unpublish this submission?". The options answering the question should be "Yes" and "No" / "Cancel".

Perhaps it’s worth taking some time to look at other prompts like this in the dashboard?

**Comment by ajnyga** [comment]
This seems to have been fixed in the latest main branch.
![Screenshot 2023-02-14 at 14 12 44](https://user-images.githubusercontent.com/16347527/218735664-8f126e21-f3f3-41f7-9814-d7034d8df0dc.png)

So this can be closed unless we want to have this as a place holder for finding similar prompts in the UI?

**Comment by asmecher** [comment]
Closing, thanks!
