### ISSUE TITLE
Setup foreign key constraints

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6093]
(Note: Remaining special cases have been filed here: https://github.com/pkp/pkp-lib/issues/8333)

**Describe the problem you would like to solve**
The tables are missing foreign key constraints, and that's a source of orphan data/unexpected statistics.

**Describe the solution you'd like**
Add constraints everywhere, considering carefully if deletes in cascade are the best option (easier to deal with and also to have accidents).

**Migrations to review/add constraints to:**

`pkp-lib`:
- [x] `lib/pkp/classes/migration/install/AnnouncementsMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/CategoriesMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/CommonMigration.inc.php` **except**:
  - [ ]  `plugin_settings.context_id` (uses `0` for site-wide)
  - [ ] `notifications.context_id` (uses `0` for site-wide)
  - [ ] `notifications.user_id` (uses `0` for "anyone" IIRC)
- [x] `lib/pkp/classes/migration/install/ControlledVocabMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/DoiMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/FailedJobsMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/FilesMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/GenresMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/JobsMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/LibraryFilesMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/LogMigration.inc.php` **except**:
  - [ ] `email_log.sender_id` (uses `0` for "nobody in particular")
- [x] `lib/pkp/classes/migration/install/MetadataMigration.inc.php` **except**:
  - [ ] `filters.context_id` (uses `0` for site-wide)
  - [ ] `filters.parent_filter_id` (uses `0` for none)
- [x] `lib/pkp/classes/migration/install/MetricsMigration.inc.php` [moved to apps, FKs added already)
- [x] `lib/pkp/classes/migration/install/NavigationMenusMigration.inc.php`, **except**:
  - [ ] `navigation_menus.context_id` (`0` used for site-wide)
  - [ ] `navigation_menu_items.context_id` (`0` used for site-wide)
  - [ ] `navigation_menu_items_assignments.parent_id` (`0` apparently used for none, even though the field appears nullable)
- [x] `lib/pkp/classes/migration/install/NotesMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/ReviewFormsMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/ReviewsMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/RolesAndUserGroupsMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/ScheduledTasksMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/SubmissionFilesMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/SubmissionsMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/TemporaryFilesMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/TombstoneMigration.inc.php`
- [x] `lib/pkp/classes/migration/install/ViewsMigration.inc.php`

`ojs`:
- [x] classes/migration/install/OJSMigration.inc.php
- [x] classes/migration/install/JournalMigration.inc.php

`omp`:
- [x] classes/migration/install/OMPMigration.inc.php
- [x] classes/migration/install/PressMigration.inc.php

`ops`:
- [x] classes/migration/install/OPSMigration.inc.php
- [x] classes/migration/install/ServersMigration.inc.php

**Comment by asmecher** [comment]
If you're looking into this, make sure you're looking at the `master` branch -- the schema management has all moved to migrations rather than ADODB's schema management toolset.

I'd suggest adding the constraints, then only considering `ON DELETE CASCADE` as a secondary step.

There will be quirks around the `assoc_type`/`assoc_id` pairs -- it's not possible to specify these as conventional foreign keys.

**Comment by asmecher** [comment]
Draft PRs:
- https://github.com/pkp/pkp-lib/pull/6157
- https://github.com/pkp/ojs/pull/2849

You can use SchemaSpy to generate documentation on the DB schema. See `schemaspy.properties` in the OJS root for details.

**Comment by asmecher** [comment]
Borrowed/rewrote some commits to pull pieces of this into `master` in advance of solving all the various problems that still need attention:
- Don't cast potential nulls to 0 for foreign key https://github.com/pkp/pkp-lib/commit/0b1dde22fce23e8df84743086b7a37e90da3848f
- Clean up leftover NOTNULL flags from upgrade cruft https://github.com/pkp/pkp-lib/commit/102c550fc8c12b44c5cf62fcd93731f96b93a729 https://github.com/pkp/pkp-lib/commit/5c45b47cd19d18e4199b94a789e0e10d0a1359e4
- Remove assoc-based functions (only used in DAO) https://github.com/pkp/pkp-lib/commit/46c8685233592eabd8b7e6eab1af251f2b198f4b

**Comment by asmecher** [comment]
A weird note about indexes:

MySQL/MariaDB requires that foreign key columns have indexes. If you don't specify one in the table creation, it'll create one for you. If you subsequently *do* create one, the implicit one will disappear and the one you created will remain. So there's no harm in specifying index creation alongside foreign key constraints when using MySQL/MariaDB.

**Comment by jonasraoni** [comment]
I never saw this requirement in other databases, anyway that's a good procedure =]

**Comment by asmecher** [comment]
@Vitaliy-1, and @jonasraoni, would you mind reviewing these two pull requests?
- https://github.com/pkp/ojs/pull/3180
- https://github.com/pkp/pkp-lib/pull/7279

These involve a number of changes -- I kept the commit list clean in case it helps to read them separately.

In terms of introducing foreign key constraints, they only tackle the announcements tables. But they set patterns that I'd like to roll out in future PRs. Of note:

- Moved the installation migrations into `classes/migrations/install` (to match `classes/migration/upgrade`).
- Fully qualified class names are introduced for migrations (and the old compatibility aliases are removed).
- The `announcement_types` `assoc_type` / `assoc_id` columns are removed in favour of just a `context_id` column (the only use case we had for it). I'd like to get rid of `assoc_type` / `assoc_id` where possible as they are confusing.
- Added a base `Migration` class with a few common details. (For whatever reason, the Laravel Migration base class doesn't define what `up()`/`down()` function signatures should look like.)
- Added a pre-flight check migration that checks (and in this case corrects) data integrity issues early in the upgrade.
  - I chose to delete "orphan" database entries related to announcements because they are all but certainly garbage and not important for the scholarly record, but in other cases (e.g. submissions with nonexistent sections) we would probably want to abort with an error rather than attempt to correct the data.
  - If an error occurs during the preflight check, the exception is caught and the system's version is set to a "fallback" version number. This means that the user can check and correct the error and re-run the upgrade script without having to restore from backup.
  - If an error occurs during some later upgrade step, but the migration `down()` functions can run successfully to back out the partial upgrade, the system's version is likewise set to the "fallback" version number. The user should once again be able to fix the problem and re-run the upgrade, though in this case the warning message does recommend a full restore from backup.
- A SchemaSpy configuration is added. (I'd like to start publishing this on the PKP website alongside API documentation etc.)

If this all looks OK, I'll port to the other apps and continue with more foreign key constraints etc. along the same lines, in separate PRs.

**Comment by Vitaliy-1** [comment]
Migration looks ok to me and, except for unrelated issues, it went fine on my test instance. Left a comment regarding `down()` method.

**Comment by asmecher** [comment]
Thanks, @Vitaliy-1, I've resolved the comments you had! @jonasraoni, could you have a quick look? Then I'll merge these PRs and move on with other foreign key declarations following this pattern.

**Comment by jonasraoni** [comment]
I just left small comments. I didn't run the upgrade, but it would be useful to check it against real data to catch unexpected issues.
- `assoc_*` removal: that's great, the nomenclature was really confusing for me.
- Half-typed Laravel: I've seen it in other places and I'm curious if there's a reason or if it's just "lack of time" =]
- Abort rather than attempt to correct data: If I were an user with no IT support, I'd like to have it automatically corrected, then a message like "orphan submissions were detected, setup a default section at xxxx to receive them", presented on failure or in the beginning of the process, would be great.
- Correct the error and re-run the upgrade script without having to restore: I know some people that will love this 😁

**Comment by asmecher** [comment]
Thanks, @jonasraoni!

> Abort rather than attempt to correct data: If I were an user with no IT support, I'd like to have it automatically corrected, then a message like "orphan submissions were detected, setup a default section at xxxx to receive them", presented on failure or in the beginning of the process, would be great.

So far this is just theoretical, as the scripting I've done does clean (minor) things up automatically. But if it's anything that'll potentially change the scholarly record, I do think we should abort and let them fix it rather than make assumptions.

**Comment by asmecher** [comment]
Additional PRs for OMP and OPS:
- https://github.com/pkp/omp/pull/1008
- https://github.com/pkp/ops/pull/182

**Comment by asmecher** [comment]
PRs for the Category classes:
- https://github.com/pkp/pkp-lib/pull/7429
- https://github.com/pkp/ojs/pull/3217

I converted them to the EntityDAO toolset as that has better handling of null-but-that-doesn't-mean-unset constraints. This also fixes the storage of category IDs in publication data, which was broken.

**Comment by asmecher** [comment]
Genres:
- https://github.com/pkp/pkp-lib/pull/7993
- https://github.com/pkp/ojs/pull/3419

**Comment by asmecher** [comment]
PRs for controlled vocab tables:
- https://github.com/pkp/pkp-lib/pull/8261
- https://github.com/pkp/ojs/pull/3547 (TESTS ONLY)

**Comment by asmecher** [comment]
FKs for user group relationships:
- https://github.com/pkp/ojs/pull/3554
- https://github.com/pkp/pkp-lib/pull/8292

**Comment by asmecher** [comment]
FKs for user group relationships:
- https://github.com/pkp/ojs/pull/3554
- https://github.com/pkp/pkp-lib/pull/8292

**Comment by asmecher** [comment]
FKs for submission file relationships:
- https://github.com/pkp/ojs/pull/3556
- https://github.com/pkp/pkp-lib/pull/8296

**Comment by asmecher** [comment]
Index fixing:
- https://github.com/pkp/ojs/pull/3575
- https://github.com/pkp/pkp-lib/pull/8331

**Comment by asmecher** [comment]
All implemented -- the remaining special cases have been filed here: https://github.com/pkp/pkp-lib/issues/8333

**Comment by asmecher** [comment]
@jonasraoni, a tweak is required on this one: you're using `ALTER TABLE t RENAME INDEX old_name TO new_name`, which is only available in MariaDB as of version 10.5.2. My Ubuntu ships with 10.3.39 and I think there will probably be lots of ISPs using older versions too. Could you check if there's a workaround that'll support older MariaDBs?

**Comment by asmecher** [comment]
^ Sorry, wrong issue. Moving to #8333.
