### ISSUE TITLE
[OJS] Submission process confusion with Corresponding Contact and Privacy Consent 

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#6160]
The consent confirmation checkbox in the submission form needs to be adjusted to reflect that the author consents to be contacted about this and any future submissions.

In addition, the "primary author" designation in the contributors list should be removed. This is not currently used and it is easy to interpret this as a corresponding author, which it is not.

Original report:

> This appears at the bottom of Step 1 in making a submission. 
>  
> <img width="644" alt="Screen Shot 2020-08-10 at 10 24 36 AM" src="https://user-images.githubusercontent.com/10342108/89854253-45005780-db48-11ea-96ff-9751cd18a254.png">
> 
> 1. The first statement on "Corresponding Contact" may be confusing the role of the “corresponding author” or "primary contact" which we ask for in Step 3. Enter Metadata. We currently have “Corresponding Contact” which the submitting author is required to check, and then in Step 3, we have the option for "Primary Contact,” where it is optional which of the authors serves this role. The desired behavior and title is in step 3, although it has to be required that at least one author is designated "primary contact," which means we can drop the required request in Step 1    
> 
> 2. The second statement is identical to the one that everyone must agree to on registration (which may take place just before making a submission or some time earlier). To be asked to agree to it again does not seem right. If we must have their confirmation repeatedly with each transaction, then instead of using identical wording, we could have “Please confirm your previous agreement to have your data collected and stored according to our privacy statement.”  If there is no requirement to have people agree every time they interact with the system, it could be removed.

**Comment by NateWr** [comment]
As you've surmised, the checkboxes are what we landed on after a considerable amount of discussion about the GDPR requirements. If I recall, the requirement here is additional to the user registration requirement because consent must be acquired whenever an individual's role or the data collected about them changes within the system. Since a submitting author will have considerably more data stored about them, I believe it was decided we needed the additional checkbox here.

I think you're right about the confusion between corresponding contact (the user assigned as a participant in the editorial workflow) and the primary author (the author assigned as the primary contact for the published item). We rarely use the primary author in the system. We don't, I believe, indicate a "corresponding contact" on the article landing page.

A quick search for where we use the primary author brought up two places:

1. If the primary author's email address differs from the submitting user's email address, the submission confirmation email is sent to both email addresses.

2. The primary author is used as the "first author" when displaying a link in `SubmissionInfoCenterLinkAction` (this is the Activity Log, I think).

The first case could probably be usefully changed. All others should be informed that they've been included in a submission -- though they will need a different email from the submitting author because they do not have access to the editorial workflow.

The second use case is probably in error -- this should use `Publication::getShortAuthorString()` like other places where a short author designation is used (eg - Barnes, et al).

It would be good to double-check my assumptions here. But we may be able to get rid of the "primary author" designation altogether.

**Comment by jmacgreg** [comment]
Hi @NateWr - one note about the first Corresponding Contact checkbox. A quick test suggests that it only appears the first time a non-author submits a manuscript to the system, and acts as a confirmation that they understand that they will receive notifications regarding the submission. It doesn't appear as part of subsequent submissions. If a user already has an author role assigned to them, it doesn't show up - see https://github.com/pkp/pkp-lib/blob/master/templates/submission/form/step1.tpl#L48 for where the code is implemented. (See https://github.com/pkp/pkp-lib/issues/2297 for the conversation that led to this function, I think.) 

The correspondence text as-is actually doesn't make sense: it's not clear that in agreeing to this statement, you are agreeing to correspondence wrt other submissions. I think this can be simplified somehow. When a non-role person submits a manuscript for the first time, they should be required to agree to receiving correspondence relating to submissions; and they should also agree to the privacy statement. 

For users who have already agreed to these options, I think their agreement should be presented to them as part of a submission, and they should be provided the option to opt-out, but they shouldn't have to manually opt-in to proceed. I don't think explicit opt-in is required - but I've argued *for* that before, and my brain is fuzzy on why. @ajnyga or @bozana (when she returns) may have some thoughts here, as well as @marcbria and @mtub (off the top of my head). 

Both of these options should probably also be configurable as part of the user's account settings.

**Comment by NateWr** [comment]
A comment from Alec on the "primary author" setting for contributors:

> I think this is a relic from OJS 2.x, and has been on the back of my mind for reconciliation with OJS 3.x's capabilities for assigning multiple author users to the submission.

**Comment by willinsky** [comment]
Some proposed guiding principles:

1. Submitters should be required to designate at least one “corresponding author” (CA) in step 3. Enter Metadata. This is something of a standard term in use with published articles. Our current “Primary Contact” risks confusing “primary author” or first author, which is not the same, while "contact" suggests for OJS and not for readers. The submitter could be made CA by default, as long as they can readily change it to another author (with at least one is required). All emails from OJS go to the CA, although the confirmation of submission will also go to the submitter and the CA (if they differ). 

2. If we require consent from the submitter on their first submission in Step 1, then the checkbox could read: [ ] “I agree to being emailed to confirm this submission.”

3. The “corresponding author” should be indicated on the article landing page, perhaps with no more than an email icon beside the name, which is a common convention. (This does not appear to be the case at the moment for OJS from the examples I consulted).  
 
4. As part of our journal integrity initiative, and as a more advanced step, OJS could email all the other authors on completion of the submission, with an email along the lines below (this is one from eLife) to improve author metadata quality and emphasize responsibilities of authorship. (Adding famous authors has been detected, seemingly to increase traffic and citation):

Dear X,
Dr. Y has recently submitted an article, "Reader engagement with Wikipedia's medical content," for consideration at Z. Please confirm your authorship using the following link: AA. A PDF of the submission can be found via the link above. Please ensure that your name (including middle initial[s], if applicable), department, institution, city, and country, author contributions, and competing interest statement are all accurately and correctly entered. If not, please update your online profile with the correct details. We will take this confirmation to mean that you approve of the submission of the article, its content, authorship, and the order of authorship. If you have any questions about the submission, please discuss them with the corresponding author(s).
Many thanks,

**Comment by ajnyga** [comment]
I agree with @jmacgreg that the "corresponding contact" checkbox text should probably indicate that you agreeing to receive emails not only for the current **but also for any future submissions** you submit to the journal. Checking that box basically adds the Author role for the user and if that role is already assigned, the checkbox will not show. Also, if I remember correctly, you have to choose the role you are submitting in, if there are more than one Author level role in the journal (which is probably quite rare).

Regarding @willinsky's point 3 above we have to remember that a lot of journals have very old articles imported to the system. At the same time the email field is always required in OJS3, so many articles have a "dummy" email address for the corresponding author which should not be shown in the landing page.

**Comment by willinsky** [comment]
In light of @jmacgreg and @ajnyga's observations, I have revised my comment above, to remove the requirement for a "corresponding author" in point 1, and to allow the author to agree that this willingness to be emailed holds for this and all subsequent submissions in point 2.

**Comment by jmacgreg** [comment]
One other additional note - @willinsky, regarding note 4, I believe the ORCID plugin already provides that functionality. If it's helpful to the journal integrity project, I can take you through how it works - just let me know.

**Comment by NateWr** [comment]
Thanks everyone. So I think there are three things to address here:

1. Adjust the consent checkbox label to refer to more than one submission. I suggest, for a minimal change, "Yes, I would like to be contacted about my submissions."

2. Remove the primary author setting to prevent confusion. It is not in active use.

3. Consider whether to add an option to designate one or more corresponding author(s) that can be shown on the article landing page.

I've split the third item out into its own issue, since it is a new feature that we've never supported rather than a change that would fix a problem with our existing application.

I've repurposed this issue to address the first and second items. I've tentatively scheduled it for 3.3.1 since the GDPR part of this needs to get resolved before too long.

**Comment by NateWr** [comment]
> For users who have already agreed to these options, I think their agreement should be presented to them as part of a submission, and they should be provided the option to opt-out

Can you describe more how you see this opt-out working? I don't think it is possible for us to accept a submission when someone opts out. The editorial workflow can not work unless we are permitted to email them.

**Comment by willinsky** [comment]
@NateWr >Adjust the consent checkbox label to refer to more than one submission. I suggest, for a minimal change, "Yes, I would like to be contacted about my submissions." 

Thus may be too miniscule a point, and can be ignored, but just to explain that I was thinking that it made more sense if we ask them to signal their consent -- "I agree to being emailed about my submissions” -- than seeming to ask them whether they'd like something to happen while at the same time indicating that this is required.

**Comment by jmacgreg** [comment]
> > For users who have already agreed to these options, I think their agreement should be presented to them as part of a submission, and they should be provided the option to opt-out
> 
> Can you describe more how you see this opt-out working? I don't think it is possible for us to accept a submission when someone opts out. The editorial workflow can not work unless we are permitted to email them.

Hah, I started writing my thoughts up and immediately realized that it's more than can be added to this already windy thread. Carved off into #6180.

**Comment by NateWr** [comment]
With the new submission wizard, the following problems are resolved:

1) The language about consenting to receive information about submissions is no longer present (it is part of the general privacy consent).

2) The language about "corresponding contact" has been removed so there is no confusion with "primary author".

I'm going to close this as resolved. If you find problems with the new submission wizard in 3.4, please file a new issue.
