### ISSUE TITLE
[OJS] Problem when submitting reviews

### ISSUE THREAD

**Issue by giovannimalafonte** [pkp/pkp-lib#6189]
In OJS 3.2.1-1 when hitting 'Submit review' after hitting 'Save for later' the review is not submitted. 
Instead of submitting the review 'Submit review' just saves it for later which is confusing.
Page needs to be reloaded first for 'Submit review' to actually work.

Steps to reproduce
1) Click on 'Save for later'
2) Click on 'Submit review' right afterwards
and you will see it doesn't work, the review isn't submitted,instead 'Save for later' messages appear.

It would be nice if the buttons would always do what they say they do.

**Comment by asmecher** [comment]
See also a report on the support forum of the same issue: https://forum.pkp.sfu.ca/t/ojs-3-2-1-1-problem-with-review-form-save-for-later/61867/3

**Comment by NateWr** [comment]
@asmecher I've hit a wall on this one. The save for later button's name/value is serialized into the request as `&saveFormButton=1`. Once that button is pushed once, no matter what I do, I can not get that value out of subsequent submit requests. Here are the things that I've tried:

1. Give the other submit button a name/value. Clicking on the submit button still sends `saveFormButton=1` and the other button's name/value doesn't get sent.
2. Remove name/value from the save button. Instead, get the submitted button from the validator and add it to the serialized string (see [here](https://github.com/NateWr/pkp-lib/commit/52135eb3386f6a617d0493df2a344bc82cf0b55d#diff-711d607e28a066d517abc3b705d1989353b3ea38b90e341f29e71b9d5ac96c8cR86-R95)). That didn't work either because, once the save button is pressed once, `validator.submitButton` is _always_ set to the save button, even if I use the submit button.

I suspect that with (2) the validator is either caching the `submitButton` value for performance, or it always takes the _last_ submit button that it finds in the DOM (ie - it doesn't represent the button that was used to submit the form, just the last submit button it found in the form).

Either way, the `$form.serialize()` method ([here](https://github.com/NateWr/pkp-lib/commit/52135eb3386f6a617d0493df2a344bc82cf0b55d#diff-711d607e28a066d517abc3b705d1989353b3ea38b90e341f29e71b9d5ac96c8cL82)) only ever seems to pick up a name/value from the save button. Never the submit button.

**Comment by asmecher** [comment]
:exploding_head: :rage: :exploding_head: :rage: At great personal cost I tracked down the source of the weird extra input to the JQuery Validator plugin: https://github.com/jquery-validation/jquery-validation/blob/master/src/core.js#L62..L65

There appears to be some cleanup code added for the `hidden` element in the current release of the JQuery Validator -- it's possible that just upgrading that plugin will fix this. Unless someone else beats me to it, I'll try this tomorrow.

**Comment by NateWr** [comment]
:clap:

**Comment by asmecher** [comment]
There's cleanup code for the `hidden` element already in place in our current version of the JQuery validator plugin. I tracked the problem further to an interaction between the JQuery Validator and confirmation modal. The confirmation modal uses `$button.trigger('submit')` rather than `$button.click()` (since the click event opens the modal rather than submitting the form), but the validator isn't expecting that.

Issue demonstrated outside of OJS:
```html
<html>
	<head>
		<title>pkp/pkp-lib#6189 Problem submitting reviews</title>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.js?v=3.3.0.1" type="text/javascript"></script>
		<script src="lib/pkp/js/lib/jquery/plugins/validate/jquery.validate.js" type="text/javascript"></script>
	</head>
	<body>
		<script>
			$(function() {
				$('#myForm').validate({
					submitHandler: function(form) {
						var $outputContainer = $('#outputContainer');
						$outputContainer.text($(form).serialize() || "(empty)");
					}
				});
				$('#submitButton').click(function(e) {
					$('#submitButton').trigger('submit'); // https://github.com/pkp/pkp-lib/blob/stable-3_2_1/js/controllers/modal/ButtonConfirmationModalHandler.js#L81
					return false; // https://github.com/pkp/pkp-lib/blob/stable-3_2_1/js/classes/linkAction/LinkActionRequest.js#L87
				});
			});
		</script>
		<h1>Form</h1>
		<p>Bug: Clicking the Save button unexpectedly changes the form's serialization for all subsequent calls to the Submit button. JQuery Validator <a href="https://github.com/jquery-validation/jquery-validation/blob/1.19.3/src/core.js#L62..L65">adds a hidden element</a> that persists after the button is clicked.</p>
		<form id="myForm" action="test.html" method="post">
			<button id="saveButton" type="submit" name="saveButtonName" value="saveButtonValue">Save</button>
			<button id="submitButton" type="submit" name="submitButtonName" value="submitButtonValue">Submit</button>
		</form>
		<h1>Form serialization</h1>
		<pre id="outputContainer">(nothing yet)</pre>
	</body>
</html>
```
PR: https://github.com/pkp/pkp-lib/pull/6630/files
(Testing works locally, but tests are currently broken elsewhere, so I won't submit a PR to OJS for testing purposes)

@NateWr, could you have a look at the PR?

**Comment by NateWr** [comment]
Excellent!

**Comment by asmecher** [comment]
Thanks, @NateWr! Back-ported to `stable-3_2_1` for the 3.2.1-3 release.
