### ISSUE TITLE
Port Citation Style Language plugin to OMP

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6201]
See https://forum.pkp.sfu.ca/t/how-to-cite-in-open-monograph-press-3-1-0/34493 for details.

**Comment by isgrim** [comment]
Yes please! We from Heidelberg University Library may take this up, because we need this to use OMP for the frontend.

**Comment by isgrim** [comment]
Dear Alec @asmecher ,

Do you know if someone was working on this, because I found an OMP branch in the plugin repository:
https://github.com/pkp/citationStyleLanguage/tree/omp-stable-3_1_1

We are thinking of porting the plugin for OMP 3.3. But we did not settle yet, if we should use the OJS plugin or use some JavaScript code involving citeproc-js which was used in Dulip's OMP Portal.

Any suggestions?

Thanks and hope you are doing well,

Nils

**Comment by asmecher** [comment]
I think this would be a wonderful addition to OMP (and OPS too)! The best approach would be to adapt the existing repository (https://github.com/pkp/citationStyleLanguage) so that it can check which application it's been installed into and adjust its behaviour accordingly. There wouldn't be many changes needed. If you're interested, please go ahead, and I'd be happy to review and support (e.g. adding automated testing)!

**Comment by bolelligallevi** [comment]
Hi @isgrim, any update on the plugin porting to OMP?
Best regards,
Stefano

**Comment by isgrim** [comment]
Hi @bolelligallevi ,

my colleague (Christian Marsilius, @nongenti )is working on it. I think we have a functional version on our development server. I have to check with him, in what state the code is.

Regards,

Nils

**Comment by ronste** [comment]
Hi @isgrim , @nongenti,

may I ask what is the status of porting Citation Style Language plugin to OMP?

Regards,
Ronald

**Comment by nongenti** [comment]
Hi @ronste,

we've a solution running with OJS and OMP 3.3. A pull request is still open. I'm also working on a 3.4 version. But first I've to finish chapter landing pages for OMP 3.4, because csl-plugin should also work on chapter landing pages. For now you can have a look at  [https://github.com/UB-Heidelberg/citationStyleLanguage/tree/stable-3_3_0](https://github.com/UB-Heidelberg/citationStyleLanguage/tree/stable-3_3_0)

Regards,
Christian

**Comment by ronste** [comment]
Hi @nongenti ,

thanks for the update. But our installation runs on OMP 3.2. I guess we'll take another route for now.

Regards,
Ronald

**Comment by NateWr** [comment]
@nongenti can you confirm if these two PRs are the correct ones to review for this feature? Is there anything else outstanding?

https://github.com/pkp/omp/pull/1035
https://github.com/pkp/citationStyleLanguage/pull/84

**Comment by nongenti** [comment]
Hi @NateWr,
there is also version for OJS/OMP 3.3 you reviewed last summer but never merged. [https://github.com/pkp/citationStyleLanguage/pull/79](https://github.com/pkp/citationStyleLanguage/pull/79 )
I can't evaluate whether this is important for now or not. 

I've to update my 3.4 instance and rework [https://github.com/pkp/omp/pull/1035](https://github.com/pkp/omp/pull/1035l) because the changes regarding DOIs. I think thats done till the end of this week. I let you know.

**Comment by asmecher** [comment]
Another related PR: https://github.com/pkp/omp/pull/1121

@nongenti, because these PRs span many repositories, it's helpful to make sure they're all listed here in a comment.

**Comment by asmecher** [comment]
@nongenti, I think there are still a couple of pieces you're working on:
- https://github.com/pkp/citationStyleLanguage/pull/84/files#r1014204991
- https://github.com/pkp/omp/pull/1121/files#r1015213407
- (possibly other review comments)

Please make sure to ping me when it's ready for another look and I'll get it merged -- it's very close! Thanks for being patient with us on this one.

**Comment by nongenti** [comment]
@asmecher, I think all should be done now. 

**Overview:**
I've closed [https://github.com/pkp/omp/pull/1121](https://github.com/pkp/omp/pull/1121). We don't need this PR anymore.

In [https://github.com/pkp/omp/pull/1245](https://github.com/pkp/omp/pull/1245) I add publication and chapter as arguments to hook call CatalogBookHandler::book in OMP CatalogBookHandler.php, like you told me here: [https://github.com/pkp/citationStyleLanguage/pull/84#discussion_r1012344858](https://github.com/pkp/citationStyleLanguage/pull/84#discussion_r1012344858)

[https://github.com/pkp/citationStyleLanguage/pull/84](https://github.com/pkp/citationStyleLanguage/pull/84) is the CSL-Plugin with namespaces and OMP support.

[https://github.com/pkp/ojs/pull/3719](https://github.com/pkp/ojs/pull/3719) removes only the CSL template code from OJS, like wished  here: [https://github.com/pkp/omp/pull/1121#discussion_r1014260003](https://github.com/pkp/omp/pull/1121#discussion_r1014260003)


If you're interested in a CSL-Plugin Version for OMP 3.3 you can also look at this:
[https://github.com/pkp/citationStyleLanguage/pull/79](https://github.com/pkp/citationStyleLanguage/pull/79)

**Comment by asmecher** [comment]
@nongenti, thanks, that sounds great -- so to summarize, these PRs are what's now relevant, right?
- https://github.com/pkp/ojs/pull/3719
- https://github.com/pkp/omp/pull/1245
- https://github.com/pkp/citationStyleLanguage/pull/84

If I have that correct, I've added a new review at https://github.com/pkp/citationStyleLanguage/pull/84#pullrequestreview-1268390747 that should cover them.

**Comment by asmecher** [comment]
@nongenti, thanks as always for your diligence -- I've merged the OJS and citationStyleLanguage PRs, and just have one outstanding question/comment on the OMP PR:

https://github.com/pkp/omp/pull/1245/files#r1100867573

**Comment by asmecher** [comment]
Note that we're due to release OMP 3.4.0 release candidate 1 (thus starting testing for 3.4.0) in a week -- if you're able to give this a look in the next few days, it'll help us get everything shipped with the release candidate!

**Comment by nongenti** [comment]
@asmecher , changes are implemented. Thanks for your reviews!

**Comment by asmecher** [comment]
Hi all -- I've merged this to OMP and added a submodule there. The plugin will be included in OMP 3.4.0. Huge thanks to @nongenti and UB-Heidelberg for their work on this!

**Comment by danielsf93** [comment]
Hello everyone, I made a plugin that, for now, can solve the problem.  https://github.com/danielsf93/ompcitation
