### ISSUE TITLE
Default date range on advanced search

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6204]
When using the advanced search the default date range that appears is the current date which results in limited or no results.

![image](https://user-images.githubusercontent.com/50342731/91205168-f7dcc380-e6b9-11ea-913d-f981887d0011.png)

In order to generate results, the user would have to change the Published After date. 

![image](https://user-images.githubusercontent.com/50342731/91205327-36727e00-e6ba-11ea-8756-dae022bfcadc.png)

The editor of the journal finds the default dates to be counterintuitive, as you have not consciously decided to go for an ‘advanced’ search and therefore you may easily overlook the dates.

The proposed solution would be to set the date of the first publication in a journal as default ‘published after’ date, so by default, you get all results available, unless you narrow the search.

**Comment by NateWr** [comment]
@pmangahis what version of OJS is this? When you click the dropdown list, is there an empty option at the top? The search form should load the first time where each of the dropdown lists have selected the "empty" option, like below.

![empty-option](https://user-images.githubusercontent.com/2306629/91309790-f1794500-e7a8-11ea-87e1-cb248e2935e9.png)

I tested on `master` and `stable-3_2_1` and that's what happens for me. Also, is it possible that this theme has been modified at all?

**Comment by pmangahis** [comment]
@NateWr forgot to add that part in, the client's on 3.1.2.0. I don't suppose there's a patch for this or would it be best to just suggest an upgrade to the latest?

**Comment by NateWr** [comment]
I _think_ it can be tracked back to https://github.com/pkp/pkp-lib/issues/4713, but it looks like this may be complicated by the upgrade from Smarty v2 -> v3 that occurred with OJS 3.2. The short answer is that I think it would not be easy to backport a fix. Sorry, but that means the best is probably to suggest an upgrade.

I'm going to mark this as closed since we're not likely to port a fix for this back to 3.1.x at this point in time. But we'd be happy to merge a fix in if PS was able to provide the fix. :+1:
