### ISSUE TITLE
Embed discussion content into the notification message body  

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6222]
**Describe the problem you would like to solve**
Editors would like to have the content of a discussion response (at any stage of the workflow) embedded in the notification email that gets sent to them. Currently, this notification only indicates that there is a new activity. 

![image](https://user-images.githubusercontent.com/50342731/92037629-eda86e00-ed26-11ea-8629-a7794e5285dd.png)

**Who is asking for this feature?**
The Journal editor would like to see the content of a discussion reply without having to log in to the system.
 
**Additional Information**
Version: OJS 3.1.2.4
Email Template: Notification, Email Key Notification

**Comment by pmangahis** [comment]
Potentially related to Nate's work on https://github.com/pkp/pkp-lib/issues/5730

**Comment by NateWr** [comment]
@forgive38 if you are going to work on this, we'd like to see the discussion subject be the subject of the email. So the template would be similar to GitHub notifications, like this:

```
Subject: {$subject}

{$body}

----
Reply to this message at [{$journalName}](...).
```

This would fit well in the future with https://github.com/pkp/pkp-lib/issues/4142, where we hope to support an email reply processor so that people could reply to the email and it would be like a new discussion comment (similar to GitHub).

**Comment by forgive38** [comment]
First proposition:
ojs : https://github.com/pkp/ojs/pull/3349
lib pkp : https://github.com/pkp/pkp-lib/pull/7803

**Comment by asmecher** [comment]
@NateWr, would you mind reviewing this? Thanks!

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/8304
OJS: https://github.com/pkp/ojs/pull/3561
OMP: https://github.com/pkp/omp/pull/1213
OPS: https://github.com/pkp/ops/pull/363
