### ISSUE TITLE
[OJS 3.1.1.2] Adding third level sub menus to navigation menu

### ISSUE THREAD

**Issue by rebeccauoe** [pkp/pkp-lib#6225]
Our editors are looking to streamline the website navigation process but are unable to add a third level to the navigation menu (e.g. you can currently have ‘About’>‘Governing Structure’ but not ‘About’>‘Governing Structure’>‘Editorial Board’) (see screenshot below).

This currently isn't available on OJS. It would be ideal if the option was made available. 

This feature would benefit the journal editors and platform hosts (me). It would also benefit our readers and website visitors as information would be easier to find.

![Annotation 2020-09-03 131350](https://user-images.githubusercontent.com/70700714/92113549-60791e00-ede7-11ea-9894-1e2ce667f9a8.jpg)

**Comment by NateWr** [comment]
Thanks @rebeccauoe! The decision to limit it to two levels was taken because cascading or dropdown menus with more than two levels are difficult to use. This is especially true for anyone who has impaired motor functions.

One way to deal with this is to use a megamenu instead. But almost all of our users have no more than a dozen links in their navigation menu and a megamenu wouldn't be appropriate for them.

Do you mind sharing a screenshot or link to the large navigation menu you are trying to organise?

**Comment by rebeccauoe** [comment]
Hi Nate,

Thanks for your response. It's for a new journal we are building so I don't currently have a screenshot. I will recommend they use in-text links rather than trying to have everything on the navigation menu.

Thank you again for your help!

Rebecca
