### ISSUE TITLE
[OPS] Ability to delete unpublished/unposted versions

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6227]
**Describe the problem you would like to solve**
Sometimes authors create new versions by mistake. They never intended to create a new version and yet somehow they do.

However the system does not allow to delete an unpublished/unposted version and you end up with the unpublished/unposted version left at this stage until the version actually gets published/posted -- even if this may never happen.

**Describe the solution you'd like**
It would be good if the Server Manager could delete unpublished/unposted versions. This would have to take into account the scenario where a version has been published/posted and then unpublished/unposted. In this scenario, deletion should not be possible because that is against the best practices of removing/retracting a preprint.

Ideally the system would only allow deletion if the version has never ever been published/posted before.

In the scenario where a version has been previously published/posted, one should follow the route of content removal/retraction.

**Who is asking for this feature?**
Server Managers. Having all these versions made by authors by mistake may cluttler submissions.

**Comment by NateWr** [comment]
> Ideally the system would only allow deletion if the version has never ever been published/posted before.

I agree this is important. Unfortunately if a publication has been published and then unpublished, we don't have a record of that. Perhaps this can be retrieved from the submission's activity log but I'm not sure if it saves the `id` of the publication that's been published/unpublished. If it doesn't save that information with the log entry, it should.

**Comment by ajnyga** [comment]
Should have a flag in Publication settings saying whether the Publication has been published at some point? This would make the requested feature easy to implement and I have a feeling there would be other use cases for it as well.

It is important, as noted, that a Publication once published is not too easy to delete especially if DOIs are used.

**Comment by NateWr** [comment]
I suggest using the event log if it's not too difficult, just to keep this as close to the underlying data as possible. Search the event log for the event `SUBMISSION_LOG_METADATA_PUBLISH`. This gives us one less piece of data that can fall out of sync.

**Comment by NateWr** [comment]
I'm not totally convinced this is a good idea. So far, we don't have any evidence that these unpublished versions are causing any real problems, only an assertion that they "may clutter submissions". I think we're just doing more harm than good here and I'd encourage us not to do anything.

If we implement this anyway, I think we can check a few conditions and prevent deletion of the publication:

- Has a DOI
- Is the only published publication
- Has a tombstone (do tombstones work at the publication level? what about the galley level?)
- Has usage stats (these may not exist at the publication level, but maybe the galley level?)

Also, if this is only a problem for server managers (and we don't yet have evidence that it is), then it could be implemented as a server manager tool (ie - bulk delete) rather than an option in the submission workflow.

**Comment by alexxxmendonca** [comment]
I agree this isn't a major problem, but there is the clutter aspect, as mentioned by Nate.

Besides that, some authors do it by accident and later they write us saying they created a new version "by accident" and they don't know how to delete it. We then answer something like "Currently there is no way to delete an unpublished version, just leave it there", which may expose some UX problem.

Should we show a warning _before_ the create a new version?

Something like "Are you sure you would like to create a new version for this preprint? This should only be used if you would like to post an updated version of you preprint. This action can be undone".

**Comment by alexxxmendonca** [comment]
This is now possible to do using the plugin authorVersion (https://github.com/lepidus/authorVersion)

If you all agree, this issue can be closed.

**Comment by asmecher** [comment]
Seems to be solved.
