### ISSUE TITLE
Re-add submission acknowledgement email recipient controls in Settings

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6272]
See https://forum.pkp.sfu.ca/t/notification-of-author-submission/32854/6. The `copySubmissionAckPrimaryContact` and `copySubmissionAckAddress` settings were removed as part of https://github.com/pkp/ojs/commit/43b3907299b8cfd08c0903f672027fc32320beeb, but they are valuable and should be re-introduced.

**Comment by NateWr** [comment]
Alec, correct me if I'm wrong, but I believe they worked like this:

- The `copySubmissionAckPrimaryContact` setting is a checkbox. When checked, it sends a submission acknowlegement email to the journal's primary contact (listed under Settings > Journal > Contact).
- The `copySubmissionAckAddress` setting is a text field. Only one email address could be entered here and it would be sent the email.

I think these settings could go into Settings > Workflow > Emails. In both cases, there was not a new email template. The additional recipients were added as BCC on the email sent to authors. See the [original code](https://github.com/pkp/ojs/commit/43b3907299b8cfd08c0903f672027fc32320beeb#diff-a9923765a9759e85ed1b24fb39e58e59746113b354f0c6f882190dd7a1d2af49L59).

When re-implementing this, it would be nice if `copySubmissionAckAddress` supported a comma-separated list, so that journals/presses/servers could enter more than one email address to be BCC'd.

**Comment by twakeford** [comment]
Hi - is the above a setting to simply cc/bcc the primary contract into the author's submission notification or to send a completely different template?

The former is how OJS 2 did it, but this always seemed really odd. The author submission notification has one function and the editor submission notification has another function = if the setting is being reintroduced, could it be a completely separate template?

**Comment by NateWr** [comment]
> if the setting is being reintroduced, could it be a completely separate template?

Sounds like a good idea.

> Testing our current version (3.3.0.1) it seems that there is already a separate email that is sent to all users with an Editor role when a submission is received - although I can't find the template in the email template list. 

It looks like this is one of the configurable notifications. So each user can go into Profile > Notifications and choose whether to receive an email, or an in-app task, or disable it altogether. There is no email template and the message content is very simple: `A new article, \"{$title},\" has been submitted.`.

Judging from the code, this notification is not sent to all users with an editor role. It is sent to:

- All `ROLE_ID_MANAGER`s and `ROLE_ID_ASSISTANT`s who are assigned to the submission in that stage. (I suspect this is old code, because I'm not sure it's possible to have these roles automatically assigned by this point.)
- All `ROLE_ID_SUB_EDITOR`s who are assigned to the section or category that this submission is made to.

**Comment by twakeford** [comment]
Thanks @NateWr - I think the central setting being discussed will be good (separate template, multiple selected recipients etc) but I hadn't clocked the user profile option. This is really useful to know!

**Comment by henriqueramos** [comment]
Hey @NateWr, could you please check those pull requests, please?

https://github.com/pkp/ui-library/pull/151/files
https://github.com/pkp/pkp-lib/pull/6933
https://github.com/pkp/ojs/pull/3102

Thank you!

**Comment by NateWr** [comment]
Thanks @henriqueramos. This is looking good. I like that you took the time to build a custom UI control for inputting the values. However, there are some UX and accessibility issues that would need to be addressed, and these will require a fair amount of work. I would rather focus your time on other projects, rather than sinking a lot of time into figuring out how to do this UI control in an accessible way.

I'd like to suggest that we instead store the `copySubmissionAckAddress` property as a comma-separated string, rather than an array. This will make it possible to use a `FieldText` component without any changes to the field or the form. We can validate the emails by adding something like this in `PKPContextService::validate`:

```php
$validator->after(function($validator) use ($props) {
  $emails = explode(',', $props['copySubmissionAckAddress']);
  ...
});
```

This will keep things simple on the UI side and not require any extensions to our form system, which is difficult to maintain and refine given our accessibility requirements.

Aside from that, one UX change: I think I told you to put the fields into the Email form. But now that I'm looking at it, I think these two fields are best put under a new form in Settings > Workflow > Submission. Add a new tab there, "Notifications", with a form with these two fields.

**Comment by henriqueramos** [comment]
Fresh pull request changes to be review @NateWr!

https://github.com/pkp/ops/pull/143
https://github.com/pkp/omp/pull/957
https://github.com/pkp/ojs/pull/3102
https://github.com/pkp/pkp-lib/pull/6933

Also the evidence of new tab

![Screenshot from 2021-04-12 14-05-17](https://user-images.githubusercontent.com/1243634/114434415-5eefaf80-9b99-11eb-8ab8-78d9d3be22bd.png)

**Comment by NateWr** [comment]
All merged to `main`. @asmecher I notice that this was pegged to 3.3.1, but since we're less likely to put out a 3.3.1 soon, now, is it ok to leave this in `main` only?

**Comment by asmecher** [comment]
Yes, I've moved it off to 3.4.

**Comment by marcbria** [comment]
Sorry a lot to arrive late to this issue.

Reading is not clear to me if @twakeford proposal was taken in consideration.

Moving all notifications to email_templates also sounds a good idea to me.
It also opens the door to a "disable this template" feature to give much more control over notifications.

Take care,
m.

**Comment by NateWr** [comment]
@marcbria which proposal are you referring to? If you're talking about user control over notifications, they can opt out of this in their user profile. We hope to improve the opt-in/out UI as part of our work on emails in 3.4.

**Comment by marcbria** [comment]
Hi Nate,

I was talking about this: https://github.com/pkp/pkp-lib/issues/6272#issuecomment-782887303

Some notifications are not email_templates yet (are regular translation strings).

If they all are moved to email_templates, we got some benefits:
a) A centralized place to find and understand them all (email_templates include a nice searcher, an explanation...)
b) Journals will be able to modify those notifications without touching translation files.
c) If a "disable this template" feature is implemented someday, we will get an easy way to disable notifications of some kind (to let journals reduce the amount of message OJS is sending).

If you think c) make any sense I can open a feature request to keep the track.

**Comment by NateWr** [comment]
@marcbria I think this email is already an email template `SUBMISSION_ACK` that can be modified from the email templates list under Settings > Workflow > Emails.

**Comment by marcbria** [comment]
You are right Nate. I mixed this SUBMISSION_ACK with the "A new article has been submitted to which an editor needs to be assigned" notification, that (as far as I can see in 3.2.1-4) is not yet an email_template:

![imagen](https://user-images.githubusercontent.com/2779168/120202310-bec41780-c226-11eb-82f0-73061f0b4b05.png)

My journals reported this message to be annoying because they don't expect to be notified each time a new article arrives.
And yes, I fixed this adding a fake user as a section editor, but I feel this is not the clean way.

Do you feel this also need to be a email_template or is ok as is now?

Cheers,
m.

**Comment by NateWr** [comment]
Hi @marcbria, your editors should be able to opt out of this notification by going to their user profile > Notifications. This email uses the generic "Notifications" template, which I think we'll endeavour to replace with proper editable email templates. But if you'd like to file an issue for this I can assign it to our emails project.
