### ISSUE TITLE
Add an option to enable/disable categories in submission workflow

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#6306]
**Describe the problem you would like to solve**
Some journals use categories to organize/index their content, and want those categories to be assigned by editors, not by authors during submission. At this time there is no option to hide categories from submission which is inconsistent with the other metadata fields that can be enabled or disabled during submission. 

**Describe the solution you'd like**
Add "Categories" as an option that JM/JE can enable/disable/made required in submission metadata.

**Who is asking for this feature?**
Community - https://forum.pkp.sfu.ca/t/how-to-hide-categories-from-authors-at-the-submission-stage/63327 
Also, PKP|PS.

**Comment by amandastevens** [comment]
+1 from another PKP|PS hosted client.

**Comment by ajnyga** [comment]
Note that @NateWr idea of moving towards SubmissionGroups class that would be a parent of both Categories and Sections/Series would solve this as well. In Sections you can make such a distinction. Just saying that maybe we should put our efforts to that bigger overhaul instead of patching up smaller issues. 

See https://github.com/pkp/pkp-lib/issues/4415

**Comment by NateWr** [comment]
I think we'll probably aim to address something like this as part of our submission wizard refactor in 3.4. We're doing that for accessibility work, but we'll probably aim to make it more easily configurable.

**Comment by librariam** [comment]
+1 from PKP|PS

**Comment by suburban-journal** [comment]
+1. We use the category system of OJS very intensively for displaying our contributions sorted by topics ([have a look](https://zeitschrift-suburban.de/sys/index.php/suburban/catalog/category/schwerpunkt)). From our point of view, there should be a setting that the categories are exclusively handled by the journal manager or journal editor and hidden for authors when submitting, because the multitude of choices is very confusing for them:
![Screenshot 2022-07-04 161557](https://user-images.githubusercontent.com/62378218/177172809-1568467d-cc1c-4d13-bd46-c2e0877c4047.jpg)

**Comment by NateWr** [comment]
Nice browsing-by-category there, @suburban-journal. :+1:

**Comment by denismaier** [comment]
Another +1! That feature would be highly appreciated.

**Comment by maraab23** [comment]
We at [JFR](https://ubp.uni-bamberg.de/jfr/index.php/jfr) would also very much appreciate having the option to adjust the appearance of categories in the submission process. Ideally, it would be just as fine-tuned as the handling of sections, providing the option to decide for each specific category if we want to allow authors making new submissions to it.

For sections, the respective option is indicated with the following check-box
>Deactivate this section and do not allow new submissions to be made to it.

Would be great to have this feature for categories, too

**Comment by CathJex** [comment]
+1 from GEUS Bulletin (hosted client). Agree, 100%. We too use a lot of categories. We’d like to use this feature more for highlighting special collections, which we don’t want authors to have to wade through when making an initial submission.

**Comment by NateWr** [comment]
The following PRs add an option to Settings > Workflow > Submission > Metadata to enable or disable categories in the new submission wizard.

![categories](https://user-images.githubusercontent.com/2306629/214912958-3b29096a-ae81-42b4-863e-b05884248d47.png)

PRs:
https://github.com/pkp/pkp-lib/pull/8578
https://github.com/pkp/ojs/pull/3730
https://github.com/pkp/omp/pull/1313
https://github.com/pkp/ops/pull/450

**Comment by NateWr** [comment]
All merged to `main`. This feature will be available in 3.4. Go to Settings > Workflow > Submission > Metadata to enable or disable categories in the submission wizard.

All installs that upgrade from a previous version will have categories enabled in the submission wizard by default, so that the existing behaviour doesn't change unexpectedly. However, all new installs will have categories disabled in the submission wizard by default.
