### ISSUE TITLE
Remove script host from smarty variables

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6344]
**Describe the bug**
URL  Link function  in the wysiwig editor tinymce , automatically adds a relative path for a non-url link.
This function generates  wrong links, when combined with smarty variables.
Therefore, a custom fallback function was added to  enable correct handling of smarty variables.

**To Reproduce**

https://github.com/pkp/orcidProfile/issues/122

**What application are you using?**
 OJS, OMP or OPS 

**PRS**

stable-3_2_1 : https://github.com/pkp/ui-library/pull/123
master : https://github.com/pkp/ui-library/pull/125

FYI @NateWr

**Comment by NateWr** [comment]
Merged! Thanks @withanage.

**Comment by marcellamonrealesns** [comment]
Hello,
I've an OJS installation version 3.2.1.3.
Looking at the email template for ORCID plugin I see the string "management/settings" is still append before {$authorOrcidUrl}.

This is a problem because we cannot link teh author ORCID id since the link send trough the mail is not valid.

How can I fix this?
At the moment I cannot upgrade to a version greater than 3.2.

Thanks a lot,
Marcella

**Comment by asmecher** [comment]
@marcellamonrealesns, I'd recommend posting your question at https://forum.pkp.sfu.ca rather than adding a comment -- this issue is already closed.

**Comment by marcellamonrealesns** [comment]
OK, sorry about this.
I'll create a post in the pkp forum.
