### ISSUE TITLE
[OJS] Different headers in Section elements on Landing Page and Current Issue

### ISSUE THREAD

**Issue by GrazingScientist** [pkp/pkp-lib#6369]
I just updated to OJS 3.2.1.2 .

Since I had to adapt some CSS, I realized that both the landing page and the current issue have a very comparable structure. However, in the Current Issue page, there is something like `sections > section > h2`, while on the landing page the structure is like `sections > section > h3`. This is despite the content is (at least in my use cases) always the same.

Is this a bug or a feature?

Thanks a lot! 😄 

Cheers,
Adrian

**Comment by asmecher** [comment]
I think this is related to https://github.com/pkp/pkp-lib/issues/5178 -- @NateWr, is this intentional behaviour?
(@GrazingScientist, the support forum https://forum.pkp.sfu.ca is probably the best place to ask questions, but we'll tackle this one here.)

**Comment by NateWr** [comment]
This is intentional because the sections occur at different places in the heading structure on each page.

Homepage: Journal Name (H1) > Current Issue (H2) > Section (H3)
Current Issue: Current Issue (H1) > Section (H2)

This change was made in response to our accessibility audit. See https://github.com/pkp/pkp-lib/issues/5178

**Comment by GrazingScientist** [comment]
Okay! Thanks for the insight! :)
