### ISSUE TITLE
Clear DOI action does not refresh related form

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6444]
**Describe the bug**
Clear DOI action does not refresh related form

**To Reproduce**
1. Go to Issues > Issue
2. Click on Issue > Edit
3. Go to Identifiers tab
4. If a DOI is assigned, click "Clear DOI"
5. The action works properly but the UI does not refresh.

**What application are you using?**
 OJS, OMP 3.3

**Comment by NateWr** [comment]
@asmecher I can not seem to get this form to refresh. The problem lies in the fact that this button is a LinkAction which fires a RemoteConfirmationAction inside of the form. So any events that are passed back do not cause the form to reload. Can you remember if there is any way to trigger a form reload from a child element of the form?

I tested and this is also in `stable-3_2_1`. I'm hesitant to do any re-engineering of the JS handlers this late in RC2. If there's not a standard way, should we defer this to 3.3.1 and redo the form a bit?

This also effects the Clear Issue Objects DOIs button.

**Comment by asmecher** [comment]
There are other areas that are affected too -- look for `issuesTabs` in `IssueGridHandler.inc.php`. (These are the only current uses of `containerReloadRequested` that I can spot, so that can be fixed/removed as desired when cleaning up these cases.)

You can cause a tab to reload using [`$( ".selector" ).tabs( "load", "#foo" );`](https://api.jqueryui.com/tabs/#method-load) -- and a quick place to add that would be in an event binding on SiteHandler, and on the PHP side, `$json.setEvent('boundEventName', $eventData);`

I'll tackle this tomorrow if nobody else gets there first.

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/ojs/pull/3012/files
- https://github.com/pkp/pkp-lib/pull/6665/files
- OMP and OJS will just need the JS recompiled and DropdownHandler removed; I can do that once this has an OK.

@NateWr, could you have a quick look at these?

**Comment by asmecher** [comment]
Committed (and also removed missing file from OMP and OPS JS build lists).
