### ISSUE TITLE
3.3 - Author Dashboard results in HTTP 500 error after a decision

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6471]
**Describe the bug**
Not really sure if this is a bug or a DB issue, but after a decision has been recorded as Revision Required or Declined by an editor at the Review stage, the author is unable to access the submission dashboard for the manuscript (HTTP 500 error). This issue doesn't occur if the manuscript is accepted or declined from the Submission tab or accepted in the Review stage.

**What application are you using?**
 OJS 3.3 rc1 and rc2

**Additional information**
As a JM I also tried the login as a function for authors, section, editors, etc. issue seems to just affect the author, accessing using direct URL. The issue was present in both rc1 and rc2.

**Comment by ewhanson** [comment]
I also came across this. Seems to be caused by a deprecated helper `array_last` method from Laravel that was removed in Laravel 6.0 here: https://github.com/pkp/pkp-lib/blob/9578d9a11756f655ff406510d10d22ff6ea179ce/pages/authorDashboard/PKPAuthorDashboardHandler.inc.php#L163

I tried it out and got it working by replacing `array_last($editorDecisions)` with `end($editorDecisions)`.

@asmecher, I can also make a pull request for this.

**Comment by asmecher** [comment]
Please do, thanks for tracking this down! (We recently updated our Laravel libraries and missed this one.)

**Comment by ewhanson** [comment]
Done!

PR:
#6475

**Comment by NateWr** [comment]
Thanks @ewhanson!
