### ISSUE TITLE
3.3 Drag and drop Reviewer file upload (Further testing required)

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6484]
**Describe the bug**
As per my discussion with Nate, this may not be a bug but a hidden feature that requires further testing.

![3 3 Reviewer drag and drop](https://user-images.githubusercontent.com/50342731/102124686-71c9c180-3dfd-11eb-84c0-4bc07b39e96d.gif)

**To Reproduce**
Steps to reproduce the behaviour:
In 3.3. rc2 it seems that the reviewer also has the ability to use the multi-file drag and drop function introduced in the submissions for this version. 

**What application are you using?**
OJS 3.3 rc2

**Additional information**
If a user were to change the file name in Step 3 it only affects the last file in the batch upload. I was able to attach and send the file to an author with the editorial decision without issue.

**Comment by NateWr** [comment]
It looks like the Reviewer Attachments work ok because there is no genre selection that occurs during upload. So although the UI doesn't make much sense the uploads don't cause problems.

However, we need to test what happens in other instances of the file upload, like Review Files / Copyedited / Discussions / Galleys to make sure there are no bugs that occur when multiple files are dragged and dropped into the file upload wizard.

**Comment by NateWr** [comment]
I tested this today and it looks like this is ok. For things like Review Files / Copyedited files, as well as for Discussions, multiple files are uploaded and assigned to the correct genre. When uploading a revision of an existing file, or uploading a file to a galley, only one file in the group is uploaded.

So I think we're ok on this. Let's call it a hidden, undocumented feature. ;)
