### ISSUE TITLE
OJS 3.3rc - Error key with no message when layout editor tries to schedule an article to an issue

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#6574]
**Describe the bug**
This is for OJS 3.3rc testing instance. When a layout editor tries to schedule an article to an issue, they get an error saying they don't have access - as they should. The problem is that the error shows the key, not the message.

This issue appeared after yesterday's upgrade of 3.3rc testing instance - I saw the proper error message pre-upgrade. @israelcefrin said he could not find the key in the translation project.

**To Reproduce**
1. Log in as a layout editor assigned to a submission
2. Go to the Publication tab
3. Attempt to schedule an article into an issue
4. See the error on top right

![image](https://user-images.githubusercontent.com/45104797/104329117-92e40780-54ba-11eb-96b2-2a463cb3d1cd.png)

**What application are you using?**
 OJS 3.3rc testing

**Comment by NateWr** [comment]
Thanks @librariam!

@asmecher it looks like some translation updates from weblate got merged back in for `en_US` and removed locale keys: https://github.com/pkp/pkp-lib/commit/50391bfe2915d1f7a620fc46ab297b1e76cf0893#diff-cf438054f827419632df838470fe2bd8050c822674dd59b4d27f84b62a3638dc

It looks like this happened for [OJS](https://github.com/pkp/ojs/commits/master/locale/en_US) and [OMP](https://github.com/pkp/omp/commits/master/locale/en_US), but not OPS. As far as I can tell there was no data loss in those commits. It may be possible to just revert those commits.

The following PR restores the missing locale keys in pkp-lib. Since some of them had been re-added, I couldn't just revert the commit.

PR:
https://github.com/pkp/pkp-lib/pull/6579

Tests:
https://github.com/pkp/ojs/pull/2987

**Comment by NateWr** [comment]
> they get an error saying they don't have access - as they should.

Sorry, @librariam, I forgot to respond to this part. I think this is probably related to the metadata editing permission on the stage assignment. As a manager/editor, go to the submission, find the Participants list, and edit the layout editor assignment. There's a checkbox to allow the user to edit metadata. Try checking that and then see if the layout editor can edit.

**Comment by asmecher** [comment]
> ...it looks like some translation updates from weblate got merged back in for en_US and removed locale keys...

Tracked this down to a malformed `api.po` after a non-Weblate commit -- it looks like Weblate responded by axing the rest of the file! Please go ahead and re-add those keys, @NateWr.

**Comment by NateWr** [comment]
Merged!
