### ISSUE TITLE
Subscription Notification emails are never sent out

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6596]
When creating a new Individual Subscription in OJS 3.2.1, there is an associated `SUBSCRIPTION_NOTIFY` email that should be sent to the user receiving the subscription.  However, the `IndividualSubscriptionForm.inc.php` class tests for a `notifyEmail` form field that is not present on the template:

```
if ($this->_data['notifyEmail'] == 1) {
}
```

The `payments/individualSubscriptionForm.tpl` template needs a checkbox to add this field.

**Comment by crowesn** [comment]
OJS 3.2.1.1  - We are encountering the same behavior. No message is generated on a new subscription. Switching of SMTP, there are no errors encountered in the mail logs.

**Comment by withanage** [comment]
@ipula from TIB will look into this

**Comment by asmecher** [comment]
I see that @Vitaliy-1 mentioned this issue as part of his work on #7286; it's "below the fold" so copying it here for easier reading:
![image](https://user-images.githubusercontent.com/200411/223544276-4c0cd162-86d8-46eb-bf4b-0f54cbd773db.png)
@Vitaliy-1, does this issue still need testing/implementation since #7286 was merged?

**Comment by asmecher** [comment]
@withanage / @ipula, I think this means that @Vitaliy-1 is working on it!

**Comment by withanage** [comment]
@Vitaliy-1  do you also look for 3.3 too? If it is not the case, we can look for 3.3?

**Comment by Vitaliy-1** [comment]
Yes, planning to fix for the stable branch too

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and `main`. Thanks @Vitaliy-1!
