### ISSUE TITLE
ONIX export only includes the last selected submission from among potentially several

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6609]
The ONIX export plugin allows several submissions to be selected for export. However, when several are selected, only one is ever included in the export XML.

This is because the list `$submissions` is assembled, but only `$submission` (the variable in the foreach loop) is ever used: https://github.com/pkp/omp/blob/stable-3_2_1/plugins/importexport/onix30/Onix30ExportPlugin.inc.php#L145..L150

**Comment by asmecher** [comment]
Apparently will also be addressed by https://github.com/pkp/pkp-lib/issues/6610#issuecomment-762695114

**Comment by defstat** [comment]
@asmecher 

**PR**
[OMP]: pkp/omp#917

This is also added to #6490 (see https://github.com/pkp/omp/pull/901/commits/bfaf1748eccf0745ce4b8e8503f100870d0637f4)

**Comment by asmecher** [comment]
Added some review comments to pkp/omp#917, thanks!

**Comment by asmecher** [comment]
Merged, thanks!

**Comment by defstat** [comment]
I am reopening this because I have stumbled into a problem regarding the ONIX export filter.

There are two Filters with the same name trying to be added to the db.

The one is https://github.com/pkp/omp/blob/master/plugins/importexport/native/filter/filterConfig.xml#L72 and is checked against https://github.com/pkp/omp/blob/master/plugins/importexport/native/filter/filterConfig.xml#L76 xsd. Those are defined in the import/export plugin

The other is https://github.com/pkp/omp/blob/master/plugins/importexport/onix30/filter/filterConfig.xml#L16 and is checked against https://github.com/pkp/omp/blob/master/plugins/importexport/onix30/filter/filterConfig.xml#L20 xsd (different than the previous one). Those are defined in the ONIX plugin. 

The two different filters are using the same name, which results only one to be added to the DB. 

I will prepare a PR that proposes that the native filter will remain as is (`monograph=>onix30-xml`), and the ONIX one will change to `monographs=>onix30-xml` instead of `monograph=>onix30-xml`

**Comment by defstat** [comment]
@asmecher 

Fixing:
- Multiple filters with same name
- `audience, audienceRangeQualifier, audienceRangeExact, audienceRangeFrom, audienceRangeTo` fields attached to submission
- Missing `PublicationFormat`->`identificationCode` or `doi` results to xsd validation failure - Custom identification (the Id of the PublicationFormat) added in case of no other identification present. 

**PR**
[OMP]: pkp/omp#921

**Comment by asmecher** [comment]
Thanks, @defstat, that makes sense. The tests were failing, but that appears to be due to a missing submodule update in `master` which I'm fixing and verifying separately.

**Comment by defstat** [comment]
Reopening that to fix a bug

**PR**
[OMP]: pkp/omp#922

**Comment by asmecher** [comment]
Merged that fix -- thanks, @defstat!
