### ISSUE TITLE
Ordering of sidebar blocks changed upon visiting the settings form

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6683]
This is a new version of the same bug that was previously filed and closed here: https://github.com/pkp/pkp-lib/issues/4896

Found in stable-3_2_1

The `PKPAppearanceSetupForm `class loads the stored sidebar setting from the context, but does not sort the presented values in the management form according to it.

`$sidebarOptions` here needs to be sorted:

https://github.com/pkp/pkp-lib/blob/master/classes/components/forms/context/PKPAppearanceSetupForm.inc.php#L44-L51

Saving the form without noticing that the blocks have returned to a default order resets any previous ordering done when viewed on the front end.

**Comment by NateWr** [comment]
Sorry @jnugent, I'm just seeing your commit now. Are you able to work that up into a PR? If so, the only change is that we need to check if `isset($plugins[$plugin])` before calling it on this line: https://github.com/jnugent/pkp-lib/commit/7a7d0529420c748366bf3bb9f1fb5f4459cdf70d#diff-4edc3b79468efaa5f9cb90fd67b416f05ea5181b98b30aaa1e211bba54418006R55. Otherwise, we'll get a fatal error when a journal disables a block plugin.

If you're busy at the moment, I can try to work this in next week.

**Comment by jnugent** [comment]
Hi @NateWr  sure, I'll get something to you in a bit.  And I actually hit that isset issue and forgot to update my local fork!

**Comment by NateWr** [comment]
Thanks @jnugent. I've just ported your commits over to a new PR that's staged against `stable-3_3_0` so I can test against the stable version. Once the tests pass I'll merge and cherry-pick forward.

PR:
https://github.com/pkp/pkp-lib/pull/6964 (`stable-3_3_0`)

Tests:
https://github.com/pkp/ojs/pull/3110
