### ISSUE TITLE
Upgrade to 3.3: default database engine doesn't support foreign key constraint

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6732]
**Describe the bug**
Related forum thread: https://forum.pkp.sfu.ca/t/updating-problem-from-3-2-1-3-to-3-3-0-2/65621/9 
Upgrades from 3.2.1 to 3.3.0.
Users report Upgrade failure with the message:
```
ERROR: Upgrade failed: DB: SQLSTATE[HY000]: General error: 1005 Can’t create table ojs_database.submission_files (errno: 150 “Foreign key constraint is incorrectly formed”) (SQL: alter table submission_files add constraint submission_files_file_id_foreign foreign key (file_id) references files (file_id))
``` 
Although I cannot be sure about the causes, it seems that such an error can occur if the table's storage engine doesn't support foreign key constraints. E.g., `files` table is created using something different from `InnoDB`

**To Reproduce**
I'm unable to reproduce the problem but can emulate by explicitly passing `MyISAM` as a default engine to Laravel's database connector

**Additional information**
According to reports from users, it's relevant for MariaDB, at least versions 10.3.24 and 5.5.60. It seems that forcing to
use `InnoDB` engine by passing additional setting to a database connection (`'engine' => 'InnoDB'`) solves the issue.

**Comment by asmecher** [comment]
@Vitaliy-1, one possible cause for this error is an attempt to form a foreign key constraint when one table uses MyISAM and the other uses InnoDB.

**Comment by Vitaliy-1** [comment]
I'm still unable to reproduce this issue. For those 2 users, who reported it, explicitly stating to use InnoDB engine, solved the issue. Hence, I'm assuming that you are correct and problem is that there are old installs of MySQL/MariaDB that still use other than InnoDB engine as a default. It quite possible that during the upgrade they may not update default, at least I'm experiencing the same with some default parameters on my MySQL instance, e.g., default collation.   

One user reported that `submission_files` table was using `MyISAM` and directly altering the table before upgrade had helped.

**Comment by semteacher** [comment]
Hello. Just faced this issue during my 3.1.1.4 -> 3.3 upgrade preparations.
I realized that my 3.1.1.4 test DB was entirely MyISAM (despite server's default engine - InnoDB). 
During upgrade one table become converted to InnoDB and referred - remains MyISAM (exactly as suggested https://github.com/pkp/pkp-lib/issues/6732#issuecomment-775474500) 
Obviously, update failed. 
I restore DB from backup and alter all tables to use InnoDB
After that update passed without any issue.
So, is it might be possible to add some tests and automatically convert entirely DB to InnoDB BEFORE starting of actual DB update process?

**Comment by Vitaliy-1** [comment]
@semteacher, thanks for pointing to the possible cause of the problem.  

I'm not sure if this should be managed from OJS. This is a database-specific setting and I don't think that creating additional restrictions here, like forcing to use only InnoDB, would be beneficial. @asmecher, what do you think?

**Comment by asmecher** [comment]
@semteacher, we support both MySQL and PostgreSQL, so this would need to be something that only runs with MySQL platforms. We do that for a few special cases but generally try to keep the code from favouring one DBMS over the other.

I agree with @Vitaliy-1 that the choice of storage engine should be left to the administrator, rather than forcing one over the other, and that is something far enough below the level of the application that it is outside OJS's responsibility. This has probably been a common misconfiguration for OJS users that started with MySQL < 5.5 and upgraded to 5.5 but hasn't shown up yet because we only just started using `FOREIGN KEY` constraints. (MySQL 5.5 was released 10 years ago so this is an oooold change!)

I can see 3 viable approaches:
1. Automatically fix the problem (i.e. adapt mismatched tables).
2. Present a warning during the upgrade to help users find the message more clearly. (This doesn't solve anything and is only a convenience in helping users identify the underlying problem; they will still need to restore from backup and fix before trying again.)
3. Present an error and abort the upgrade. (If checked early, this will save users having to restore from backup before re-running the upgrade.)

We can tackle approach 1 by listing tables for which the default storage engine doesn't match a table's engine:
```
SELECT t.table_name, t.engine AS table_engine, e.engine AS default_engine FROM information_schema.tables AS t, information_schema.engines AS e WHERE t.table_schema = 'database-name-here' AND e.support='DEFAULT' AND e.engine <> t.engine;
```
...and run a query to adapt each to the `default_engine`:
```
ALTER TABLE my_table ENGINE = InnoDB;
```
I am on the fence about whether to do this -- it would need to be introduced into the next `stable-3_3_0` release to be effective, and is a little invasive in my opinion. It might also require MySQL permissions that we haven't normally needed; I'm not sure about that off the top of my head. Opinions?

**Comment by mfelczak** [comment]
My vote would be to flag it for users as output during the upgrade process with a link to a page that contains a detailed explanation. And possibly as a check before the upgrade process is actually started so that users can confirm whether they'd like to continue with the upgrade or abort and review the issue.

**Comment by semteacher** [comment]
Based on my experience I think that 
- (3) (present error and abort) should be the best option IF it will be done BEFORE actual DB modifications.  

PS: My further investigations found another sort of problems in case if collation inconsistences  occurred. So it would be not bad at least notify admin if different types of collation in ojs DB being found with link to pages like https://github.com/kaitlinnewson/ojs-tools/blob/master/fix-database-encoding.md

**Comment by Vitaliy-1** [comment]
PR pkp/lib: https://github.com/pkp/pkp-lib/pull/8630
tests: https://github.com/pkp/ojs/pull/3760

**Comment by Vitaliy-1** [comment]
@asmecher, I think it's ready for a review, it doesn't seem that the the tests error in statistics is somehow related. I've tested the upgrade locally with own dataset.

**Comment by asmecher** [comment]
Just one comment added to the pkp-lib PR; otherwise this looks good to me, thanks!
