### ISSUE TITLE
[OJS 3.3] List of journals inside the Dashboard in unsorted

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#6747]
The journals are unsorted on the left top menu selector inside the Dashboard after the upgrade.

![image](https://user-images.githubusercontent.com/18707781/107564389-1a5b8e00-6bc1-11eb-9ec1-4b0f4a9fda75.png)

**Comment by NateWr** [comment]
What sort would you like? Alphabetical or when they were created?

**Comment by luizbgomide** [comment]
Like they were before, Alphabetical. Right know I think it is in order of creation, which doesn't say much for any kind of user.

**Comment by librariam** [comment]
+1 from a large multi-journal install. The order was not alphabetical pre-3.3, rather it reflected the set order of hosted journals

**Comment by asmecher** [comment]
Applying https://github.com/pkp/pkp-lib/commit/d7c2716d2cb940f79189619449b1ad1ea9290beb in `lib/pkp` should fix it.

**Comment by NateWr** [comment]
@asmecher the original request here was for the journals to be ordered alphabetically, and I think that is the way it should be done in the backend. The `seq` column should only be used for the homepage, I think.

**Comment by librariam** [comment]
@NateWr I'd like to add a few words about our context at U of T. Our instance has about 80 journals, of them about 60 are active/public and the rest are archived/setting up/etc. We have all active ones moved to the top of the list and sorted alphabetically - both in the homepage sort and back-end list. Those are the ones I as admin access most frequently and I don't need to scroll through the entire list to get to them. I see some advantages to sorting the back-end list alphabetically, but it would also add quite a bit of scrolling for me to get to the active journals then.

**Comment by luizbgomide** [comment]
@librariam, did you sorted the journals on dropdown menu on your end??

I can only sort them on the initial page of the journal, everywhere else it sorts by the order they were created (their ID).

**Comment by asmecher** [comment]
@luizbgomide, you would need to apply [the change described here](https://github.com/pkp/pkp-lib/issues/6747#issuecomment-861023070) first.

@NateWr and @librariam, in my opinion if there's an ordering option it should apply throughout (i.e. both to the homepage and the dropdown) but that's only a vague preference.

@luizbgomide, I see you originally asked for alphabetical ordering, but would user-specified ordering suit your needs?

**Comment by luizbgomide** [comment]
@asmecher sure thing. Even better.

**Comment by NateWr** [comment]
@librariam thanks that's helpful. I think we have two issues here. One is that the journal switcher is not fit for purpose for large instances (see also https://github.com/pkp/pkp-lib/issues/7052). We need a better, alternative approach to journal switching. Mariya, would it work for you if there was a quick search of the list available (ie - type a few letters and see options to switch)?

![journal-switcher](https://user-images.githubusercontent.com/2306629/122189406-ce7b6700-ce88-11eb-8af7-13a401bd33bd.png)

The second is the ordering. From a UX perspective, I strongly favour an order that can be understood intuitively. The manual order works for you, @librariam, because your brain has learned the order from repeated use. But it's a frustrating approach for someone new to the system, or someone who is not used to working with a particular instance (eg - a PS staff that may manage dozens of different multijournal installations). They'll basically have to scan every item to find what they are looking for.

**Comment by librariam** [comment]
@NateWr re order - this makes sense - my mental model is currently the same for front-end and back-end order, but an alphabetized list is a more generally intuitive mental model for most.

Re journal switcher - a search would actually work even better than the current list. Like many university instances, we have a bunch of journals beginning with "University of X Journal of ...." with the important distinguishing bit not visible in the list. And #7052 is also an issue for us on 3.3...
