### ISSUE TITLE
[OJS v3.3] Non-HTTP(S) links entered into rich editor fields become page-relative

### ISSUE THREAD

**Issue by davidjb** [pkp/pkp-lib#6761]
**Describe the bug**
When creating a link in a rich-text editor, creating a link (either via the Insert Link button or by entering raw HTML) with a non-HTTP(S) protocol, such as `mailto:` or `ftp://` creates the link relative to the current page in the management website.  This prevents use of other types of links that aren't http:// or https://, which prevents email links or links to data files stored on a server).

I had expected these links to remain as they are when they were entered and not have been prefixed with a URL such as `https://example.edu/example/management/settings/website#appearance/setup`

**To Reproduce**
1. Go to any rich text field (such as Website > Settings > Footer)
2. Click on Insert/Edit Link button on toolbar
3. Enter details for the link, such as `mailto:hello@example.com` or `ftps://user:pass@example.com/path/to/files`
4. Click OK.
5. Note that the URL has just become relative to the current page you're on and hardcoded in the HTML:

  ```html
  <a href="https://example.edu/example/management/settings/website#appearance/setup/mailto:hello@example.com">Test</a>
  ```

**What application are you using?**
OJS 3.3.0_3

**Additional information**
Interestingly, this issue also affects a raw HTML link too, if entered by hand as `<a href="mailto:hello@example.com">Test</a>` - as soon as one clicks OK in the source code editor, the href of this link gets rewritten.

Updating the field's values directly in the database stores and displays them fine, but only until a manager goes and updates the content on the same management screen, meaning the issue is related to the TinyMCE rich text editor adding it client-side.

**Comment by NateWr** [comment]
Thanks for the report, @davidjb. Looks like when we extended the URL handling in TinyMCE to support template variables (like `{$submissionUrl}`) we clobbered some of the default URL handling from TinyMCE. The following PR should restore TinyMCE's URL handling in all cases except where `{$...}` is used.

@withanage can you take a look at this and let me know if it looks alright? I got rid of the absolute URL check because it seemed like TinyMCE does this already.

PR:
https://github.com/pkp/ui-library/pull/144

Tests:
https://github.com/pkp/ojs/pull/3057

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `main`.

**Comment by davidjb** [comment]
Thank you @NateWr -- tested and working well in OJS 3.3.0.  Very much appreciated!

**Comment by gabriele-h** [comment]
Since the subject includes the version I am not sure whether it is better to add my comment here or open a new issue. Please let me know if you would prefer a new bug-report altogether referring to this one.

We are seeing the same issue as described here, but in OJS version 3.2.1-3 - since the data structure was changed from 3.2 to 3.3 I can't just implement the code changes from the PR's commit.

**Comment by NateWr** [comment]
Hi @gabriele-h, it should be possible to apply [this change](https://github.com/pkp/ui-library/pull/144/files) to the same file in [stable-3_2_1](https://github.com/pkp/ui-library/blob/stable-3_2_1/src/components/Form/fields/FieldRichTextarea.vue#L173).

However, because it's the UI Library, you will need to recompile the JavaScript file from the source. Our dev docs include some guidance on [running and building from source](https://docs.pkp.sfu.ca/dev/documentation/en/getting-started). The key difference is that you'll need to make to be on the `stable-3_2_1` branch for OJS, pkp-lib and ui-library before compiling the JS.

**Comment by gabriele-h** [comment]
No composer, no fix, then. We can't recompile the JavaScript and I guess we will have to live with this issue until we switch to 3.3 - Thank you for your input, though!
