### ISSUE TITLE
[OJS] Access denied for journal editor when adding new file in Request revisions dialog

### ISSUE THREAD

**Issue by jmvezic** [pkp/pkp-lib#6762]
**Describe the bug**
When a journal editor tries adding a new file as part of a "Request Revisions" step under Review phase, they get "Access denied". There is a workaround by adding that file via "Upload/select files" under "Review Files", and then later checking it in the "Request Revisions" dialog under "Select review files to share with the author(s)".

**To Reproduce**
1. Be journal editor
2. Go to review phase of submission
4. Click Request Revisions
5. Click "Upload file" under "Select review files to share with the author(s)"
6. Get "Access denied."

![chrome_twYUFazrUq](https://user-images.githubusercontent.com/8355671/108059331-a3594600-7055-11eb-889f-8b43f580763c.png)

**What application are you using?**
 OJS 3.2.1-2

**Additional information**
Didn't see this issue in the changelog for 3.2.1-3 or 3.2.1-4, or under existing open issues, but maybe I missed it.

Edit: Issue also present in 3.2.1-4.

**Comment by seisense** [comment]
Having the same issue in OJS 3.2.1.3 as well.

**Comment by asmecher** [comment]
Can you double-check your server's logs to see whether the request is being denied by mod_security or another similar tool?

**Comment by jmvezic** [comment]
@asmecher nothing in the Apache's error.log

**Comment by jmvezic** [comment]
I should also point out this happens on a stock configuration of Debian 10, MariaDB and Apache2. All latest versions.

**Comment by jmvezic** [comment]
Now also managed to produce another error, when clicking the "Upload/Select Files" under "Review Files". Error reads "Failed Ajax request or invalid JSON returned".

From the error log:

``
 PHP Warning:  Declaration of ManageSubmissionFilesForm::execute($stageSubmissionFiles, $fileStage = NULL) should be compatible with Form::execute(...$functionArgs) in /var/www/html/journal1/lib/pkp/controllers/grid/files/form/ManageSubmissionFilesForm.inc.php on line 19, referer: http://192.168.0.19/journal1/index.php/demo/workflow/index/2/3
``

**Comment by asmecher** [comment]
@jmvezic, that warning message is cosmetic, but might interfere if you've got your PHP configured to send errors/warnings to the browser.

@NateWr, could you take a look at the issue first reported? This appears to have been caused by https://github.com/pkp/pkp-lib/issues/6057; in particular [this comment](https://github.com/pkp/pkp-lib/blob/3_3_0-3/classes/security/authorization/internal/SubmissionFileStageAccessPolicy.inc.php#L56) doesn't look accurate, since it does not grant access when the current user is an assigned manager.

The file stage in question is `SUBMISSION_FILE_ATTACHMENT` (13); the use case is described here: https://github.com/pkp/pkp-lib/issues/2438#issuecomment-455006867

**Comment by NateWr** [comment]
I suspect that this is going to be related to the query args that are sent by the grid. Each grid needed to be updated separately and I may have missed this one. Has anyone managed to reproduce this in 3.3? It may only be a 3.2.x issue.

**Comment by jmvezic** [comment]
@NateWr I can try today if you want, I've got a quick-setup script for installing any OJS version.

**Comment by NateWr** [comment]
Yes, please. Thanks!

**Comment by jmvezic** [comment]
So, @NateWr , I installed from source from GH main branch (latest tag seems to be 3.4.0.0?) and the problem is still there as described above. However, this time it gives the error:

`You are not allowed to add and edit these files`

Is this right? Why wouldn't the journal editor assigned to the submission be able to add and edit them? And besides, if they shouldn't be able to do that for some reason, why does the "Upload file" even appear in that case?

Maybe I missed some discussion on this between 3.1, 3.2 and 3.3, or maybe it's a bug, but I think the journal editor should be allowed to add files to share with the author regarding request for revisions. Not to mention since they can do that with the workaround of first adding the file under "Review Files" and then checking it up on "Request revisions", so I assume this is a bug.

Screenshot:

![chrome_KYe67FGDIt](https://user-images.githubusercontent.com/8355671/108781174-c5792980-7569-11eb-8e3f-39d434bd80a2.png)

**Comment by NateWr** [comment]
Thanks @jmvezic! This is a bug. The right error message for the wrong error. :joy: I've got it on my list to investigate soon.

**Comment by NateWr** [comment]
Uff, so it looks like this came from me misunderstanding the `SUBMISSION_FILE_ATTACHMENT` file stage. I even documented this stage as [unused](https://docs.pkp.sfu.ca/dev/documentation/en/submission-files#file-stages)!

@asmecher I was able to fix the authorization issue with [minimal impact](https://github.com/pkp/pkp-lib/pull/6792). But fixing the source of the misunderstanding -- that these files [don't appear in the UI](https://github.com/pkp/pkp-lib/issues/2438#issuecomment-455006867) -- is trickier. I tried to get the files grid shown to authors to load from both file stages, but that proved difficult too.

I'm worried from a UX perspective about confusion from this behaviour in the request revisions UI. It's not clear which files remain available to the author and which are disposed of after an attachment (I found that the editor attachments can be recovered from the submission's activity log, but there's no indication where these came from). Ultimately, I think that the files need to be kept together as email attachments and either all shown in the UI or all not shown (ie - only available from the email).

I can think of two ways to address this:

1. When a `SUBMISSION_FILE_REVIEW_ATTACHMENT` is selected to be shared with the author, the system could create new files (`SUBMISSION_FILE_ATTACHMENT`) for each one. Then the author grid shows all of the `SUBMISSION_FILE_ATTACHMENT` files. Pros: one bucket for all attachments. Cons: if editor deletes a review attachment, the author will still have access to the attachment version of it. Maybe an ok thing since they'll have access from the email attachment anyway.

2. Only include these files as email attachments, and don't show them to the author in the author's dashboard. Pros: one source of files. Cons: if the email gets lost there's no way to recover the attachments.

Do you have any thoughts about either of these approaches? I'll probably plan to leave the functionality as is for 3.x and address the UX problem as part of our email work in 3.4.

**Comment by NateWr** [comment]
The following PRs fix the auth issue.

PRs:
https://github.com/pkp/pkp-lib/pull/6796 (`stable-3_3_0`)
https://github.com/pkp/pkp-lib/pull/6792 (`stable-3_2_1`)

Tests:
https://github.com/pkp/ojs/pull/3055 (`stable-3_3_0`)
https://github.com/pkp/ojs/pull/3053 (`stable-3_2-1`)

**Comment by asmecher** [comment]
Thanks, @NateWr -- and agreed that this should be definitively fixed when we rework email composition.

Then, I think it may be worth implementing email attachments outside of `submission_files`. The email log toolset is already capable of being used outside of submission-related emails, and this would circumvent the problem of the submission file framework needing files to be associated with a workflow stage (which doesn't necessarily apply to email attachments). We can still use the `files` table (if we like), and if someone wants to bring an email attachment into a specific piece of the submission workflow, then can do that (resulting in a `submission_files` entry).

I don't think we should support deleting entries from the email log at all, unless someone has a really compelling reason.

**Comment by jmvezic** [comment]
@NateWr I assume this is safe to patch in 3.2.1, from what I can see in the commit? I can test this a bit in 3.2 since it's a pretty important issue for me to fix at work. What's the "minimal impact" you mention?

**Comment by NateWr** [comment]
@jmvezic It looks like the 3.2.x tests have passed, so you should be safe to patch it. I'm waiting for the 3.3.x tests to pass before merging everything. By "minimal impact" I mean that the code changes required to fix this were small and so less likely to have unexpected side effects.

**Comment by NateWr** [comment]
Merged to `stable-3_2_1` and `stable-3_3_0` and cherry-picked to `main`. I've filed the technical improvements for 3.4 at https://github.com/pkp/pkp-lib/issues/6805.

**Comment by Lucas-Carrizo** [comment]
Hi @NateWr, how are you? I am experimenting the same issue that is described above. I have a 3.2.1.2 OJS version and I am trying to apply the changes that are described but I found that I dont have any of the files (SubmissionFileDAO and PKPFileUploadWizardHandler). What should I do? I create the files with the same names in the same route and I paste the code inside them but It didn´t work. Am I missing something? Am I doing the things wrong? Please help me

**Comment by jmvezic** [comment]
@Lucas-Carrizo perhaps you're confusing the base OJS directory (https://github.com/pkp/ojs) with the pkp/lib directory (this repo)? They have similarly named subdirectories. You should be updating the files from the lib/pkp path.

**Comment by Lucas-Carrizo** [comment]
Hi @jmvezic, thank you for taking the time to respond. I do really apreciate that. Yes, my bad. I confussed the routes. Now, I have already changed the values at "SubmissionFileDAO.inc.php", "PKPFileUploadWizardHandler.inc.php" and also delete the line number 62 in "PKPString.inc.php", but I am having the same problem. Do I need to restart? Am I missing something?

**Comment by NateWr** [comment]
@Lucas-Carrizo These are the only changes you should make on 3.2.x: https://github.com/pkp/pkp-lib/pull/6792/files

**Comment by Lucas-Carrizo** [comment]
Hi @NateWr! Thanks for respond. I took a look at the link that you share and I put "PKPString.inc.php" like it was previous. Then "SubmissionFileDAO" and "PKPFileUploadWizardHandler" were with the changes that you recommend. It didn´t work, but something strange happened: if I go to "Users and Roles", then "Tasks" and I disable "revision" option for author, it works. Do you recommend me to upload to a new version? Everything else in the OJS enviroment works fine.

**Comment by Clairoouh** [comment]
Dear all,
I am the editorial manager of OENO One journal (OJS 3.2.1.3). I am not a web developer and don't have any skills.

Very often, during the review process, the associate editors have to modify the reviewers' files (e.g. to make them anonymous or to add a note) before sending them to authors. Here, uploading is impossible. Associate editors have to contact me so that I can upload the files for them. This complicates the review process and slows down the monitoring of articles. 

How can we do to allow an associate editor to upload a file from his computer ? It was working before with our last version of OJS. Now, they have this error message: 

![Capture d’écran 2021-04-21 à 15 32 47](https://user-images.githubusercontent.com/82953556/115564424-bb994b80-a2b8-11eb-83c4-03cf653d6d7a.png)

Thank you very much for your help,
Regards,
Claire Guyot

**Comment by asmecher** [comment]
@Clairoouh, the issue you're describing looks the same as the one described in this entry, so it should be resolved by applying the changes introduced here. Specifically, those are [these code changes](https://github.com/pkp/pkp-lib/pull/6792/files) in the `lib/pkp` submodule. Unfortunately it's inherently a technical (web admin) matter to apply these changes so you may need to get some outside assistance. Alternately -- but also technical -- you can resolve this by upgrading to a later release of OJS.

**Comment by Clairoouh** [comment]
Dear @asmecher,
Thank you very much for your time and assistance.
I will contact the web admin and see what we can do :)
Have a nice day,
Claire

**Comment by jmvezic** [comment]
@asmecher I'm aware this is a fixed issue but I'm not entirely sure if it's part of a stable release yet? I don't see it in the release notes for 3.2, is there a 3.2.1-5 planned for this?

**Comment by asmecher** [comment]
@jmvezic, the fix is first included in OJS 3.3.0-4 (we use the Milestone drop-down for this, see top right).
The latest 3.2.1-x release is 3.2.1-4, released February 5, 2021, but the fix for this issue was merged into `stable-3_2_1` on March 1st, so it isn't included in any 3.2.1-x release package. If there ever is a 3.2.1-5 release it'll be included there, but we aren't releasing from older branches unless motivated by something like a critical security issue.

So if you're using 3.2.1-4 and want a fix for this, you'll need to apply https://github.com/pkp/pkp-lib/pull/6792/files manually.
