### ISSUE TITLE
Author self-registration option not showing up despite being selected in User & Roles settings

### ISSUE THREAD

**Issue by rcgillis** [pkp/pkp-lib#6765]
**Describe the bug**
When the option to allow users to self-register as author is selected, the author opiton is not showing up in list of available roles to self-register.

**To Reproduce**

1. When logged in as JM, go to "Users and Roles" 
2. Edit the Author settings.
3. Select the Self-registration option.
4. Check the registration options when registering (when not logged into the site) and author does not appear.

**What application are you using?**
OJS 3.3.0.1

**Additional information**
Please see forum post here: https://forum.pkp.sfu.ca/t/no-option-to-sign-in-as-author/65957/3

**Comment by asmecher** [comment]
The registration form only lists the option to self-register as a reviewer (when enabled). Both author and reader self-registration are implicit when registering within a journal/press/preprint server's site -- reader registration is automatic for the journal/press that is being registered into, and author self-registration occurs when a submission is initiated. For finer-grained control over which roles are self-registered, see your user profile. Site-wide registrations provide a full selection of roles for self-registration since many possible journals/presses/preprint servers are listed in that case. This was introduced with OJS 3.0; see https://github.com/pkp/pkp-lib/issues/1443#issuecomment-219802606 for details.
