### ISSUE TITLE
[OJS 3.3.03]  Upgrade from 3.2 to 3.3, All Journal custom block become same from last journal custom block

### ISSUE THREAD

**Issue by rahmanramsi** [pkp/pkp-lib#6772]
**Describe the bug**
My OJS have 6 Journals.
I successfully upgrade OJS from version 3.2.1.3 to 3.3.03, but from all journal on Custom Block Manager plugins all block content become same as from last journal i created.

**What application are you using?**
 OJS 3.3.03

**Additional information**
Before Upgrade
![WhatsApp Image 2021-02-19 at 8 49 41 AM](https://user-images.githubusercontent.com/48276043/108441198-99228c00-728f-11eb-8b43-ff705827747d.jpeg)

After Upgrade
![WhatsApp Image 2021-02-19 at 8 50 35 AM](https://user-images.githubusercontent.com/48276043/108441230-ab9cc580-728f-11eb-9637-212af3e093e7.jpeg)

**Comment by NateWr** [comment]
Another report of this in the [forum](https://forum.pkp.sfu.ca/t/upgrade-to-ojs-3-3-0-5-plugin-settings-error/67028/4).

**Comment by asmecher** [comment]
@NateWr, I suspect this is related to #5619 -- do you have time to take a look?

**Comment by NateWr** [comment]
This turned out to be related to the serialize-to-array conversion in https://github.com/pkp/pkp-lib/issues/5772. A plugin setting in one context will override the same setting in another context when the `setting_type` is `object`.

The Custom Block Manager is the only plugin I could find with these types of settings. However, you can check your own system by running the following SQL query:

```sql
select plugin_name,context_id from plugin_settings where setting_type='object' and context_id != 0;
```

If you see any plugins listed in the result, they may have settings that were overridden during the upgrade to 3.3.

@mfelczak or @janiosarmento, would it be feasible to run this query across your hosted instances to identify other plugin settings with potential upgrade problems? I'd like to know how widespread this may be. My local dev database probably doesn't have settings configured for many plugins.

PRs:
https://github.com/pkp/ojs/pull/3106
https://github.com/pkp/omp/pull/959
https://github.com/pkp/ops/pull/145

**How to fix if you have already upgraded your production site**
To fix this, you will need a backup of the database before it was upgraded. Before applying the fix below, be sure to **test it on a copy of your database** before applying it to your live site.

 Use the following SQL to see the custom blocks for each journal:

```
select context_id,setting_value from plugin_settings where plugin_name="customblockmanager" and setting_name="blocks";
```

The `setting_value` will look something like this:

```
a:2:{i:0;s:27:"second-latest-journal-block";i:1;s:20:"latest-journal-block";}
```

Change that to a JSON array:

```
["second-latest-journal-block","latest-journal-block"]
```

Then update the matching row in your live database. If you host many journals, you may want to write a `CLITool` to do this for you.  If you do so, please share your code here.

**Comment by Vitaliy-1** [comment]
Citation Style Language plugin settings may also be affected

**Comment by NateWr** [comment]
Thanks @Vitaliy-1, I've added that to the info above.

**Comment by mfelczak** [comment]
Hi @NateWr, we've identified the following plugins from installs that have been upgraded to OJS 3.3.0:

browseplugin
citationstylelanguageplugin
plnplugin
shariffplugin
sponsors
twitter

**Comment by NateWr** [comment]
Thanks @mfelczak! I've added that to the info above.

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and cherry-picked to `stable-3_3_1` and `main`.
