### ISSUE TITLE
File downloads always use most recent revision

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6819]
**Describe the bug**
Downloading revisions only ever downloads the most recent file.

**To Reproduce**
1. Upload a revision of a a file (e.g. in the submission files list)
2. Click on 'More Information' beside the file to view the submission file log
3. Find the original version of the file
4. Download the file. The resulting file will be the new revision, not the original as expected.

**What application are you using?**
OJS 3.3.0

**Comment by asmecher** [comment]
@NateWr, could you have a look at this PR? https://github.com/pkp/pkp-lib/pull/6820

**Comment by NateWr** [comment]
Oh good spot! I had to look up how that bug got in there because I can clearly remember testing that during my work on the submission files, but thankfully it just went in a week ago: https://github.com/pkp/pkp-lib/commit/3bd2b27a72856d794801de1de6c4475d6bba823c#diff-4a6e50bebe3498ce57d021ca979a92697521eeccacace513a925ea8d0de5fd4dL116. My bad on the code review. :)

**Comment by Vitaliy-1** [comment]
Thanks! Missed that.

**Comment by asmecher** [comment]
Great, and glad to hear it doesn't affect any released software! Merged and cherry-picked forward to `main`. Thanks to you both.
