### ISSUE TITLE
Migrate TinyMCE to 5.x

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6826]
We currently use TinyMCE 4.x, but the support window for that line has recently closed:
https://www.tiny.cloud/blog/tinymce-4-support-window/

- Adapt to TinyMCE 5.x
- For bonus points, stop shipping two copies (one in `pkp-lib`'s `composer.json`, another in the app's `package.json` using NPM)

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/6827
- https://github.com/pkp/ojs/pull/3065
- https://github.com/pkp/ui-library/pull/146
- https://github.com/pkp/tinymce/pull/84

**Comment by asmecher** [comment]
@NateWr, could you review the attached PRs? Also, what do you think about dropping one or the other TinyMCE packages -- I guess we should probably keep the one installed via NPM?

**Comment by NateWr** [comment]
> Also, what do you think about dropping one or the other TinyMCE packages

I think I tried to do this before but ran into problems. We need the one in UI Library to bundle and serve with our Vue.js stuff. The other one loads up in the old forms. I can't remember the details but I think it's not straightforward to get the old forms loading off the new package, maybe because the bundling doesn't expose TinyMCE globally. I agree it's pretty ugly.

**Comment by NateWr** [comment]
Code looks good to me. I haven't loaded it up to see if there are any style changes from removing `theme: main`. But if there are I'll have plenty of time to adapt it for 3.4.

**Comment by asmecher** [comment]
I forgot to double-check the pkpWordcount plugin -- that's the only outstanding item here.
