### ISSUE TITLE
Tool to convert old and apache log files into new format 

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#6849]
Previously the stats framework used Apache-style logs to handle both internal processing of log events generated by OJS, and retroactive processing of log files from another source (like the web server), e.g. for when it was necessary to reconstruct or rebuild the logs.

We are moving away from the internal use of Apache-style log files in order to reduce complexity around resolving actions based only on URLs. However, it would still be good to have a way to ingest Apache logs to rebuild the stats in some fashion.

Proposal: Put together a command-line tool to process Apache logs by matching against a set of URL pattern regular expressions using a configuration like...

```
; {$contextPath} matches context (e.g. journal) URL path
; {$submissionId} matches numeric submission ID
; {$submissionUrlPath} matches textual URL slug
; {$publicationId} matches publication ID
; {$currentPublicationId} matches submission's current publication ID
submission "/{$contextPath}/article/view/{$submissionId}$"
submission "/{$contextPath}/article/view/{$submissionUrlPath}$"
submission "/{$contextPath}/article/view/{$submissionUrlPath}/{$currentPublicationId}"
publication "/{$contextPath}/article/view/{$submissionId}/{$publicationId}$"
publication "/{$contextPath}/article/view/{$submissionUrlPath}/{$publicationId}$"
...
```
...where `submission` and `publication` define the type of stats event the match will map to.

The user will be able to feed logs into the tool using something like:
```
cat /path/to/access_log | php lib/pkp/tools/processUsageLog.php
```
...and the tool will do its best to ingest the events, providing warnings where e.g. a `{$submissionUrlPath}` doesn't match anything because an editor has changed it.

1. PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/8271
ojs: https://github.com/pkp/ojs/pull/3594 (only submodule update)
omp: https://github.com/pkp/omp/pull/1235 (only submodule update)
ops: https://github.com/pkp/ops/pull/382 (only submodule update)

2. PRs:
https://github.com/pkp/pkp-lib/pull/8467
https://github.com/pkp/ojs/pull/3644
https://github.com/pkp/omp/pull/1262 (only submodule update)
https://github.com/pkp/ops/pull/404 (only submodule update)

**Comment by asmecher** [comment]
@NateWr and @bozana, from our meeting today -- just a suggestion for the implementation based on what I was picturing during the meeting, details are all up for discussion!

**Comment by bozana** [comment]
PR:
pkp-lib: https://github.com/pkp/pkp-lib/pull/8271

**Comment by bozana** [comment]
@asmecher, could you please review the PR?
I did not use the regex, but the code that was used in usageStats plugin -- the code should work with our internal log files as well as apache log files -- it worked earlier, so... The URLs from our internal log files could eventually be caught with the regex -- because we always saved the canonical URL -- but I do not think the apache ones could -- those could be different i.e. with `disable_path_info = On`, if `index.php` is removed or different journals have different domains...
I have tested it with my local old OJS usageStats plugin log files. I will do the same with OMP and OPS, but once we have a release candidate I would maybe like to test it with some real data. I noted it in the issue that keeps the list of functionality to test (https://github.com/pkp/pkp-lib/issues/8236).
Thanks a lot!!!

**Comment by bozana** [comment]
Hi @ctgraham, @withanage, @marcbria 

I first now saw your comments in the Technical Committee List -- sorry for that :-(
So maybe here I can explain how it will work -- it is maybe easier to discuss it here...
In 3.4 we will only have internal log files, with our own log file format. These log files are automatically anonymized i.e. the IP address is hashed.
This tool here, from this GitHub issue, will only enable a conversion of an old log file format into the current/new format. It is based on the code of the usage stats plugin so that it should support both, our old internal log file format as well as apache. If an apache log file should be converted the regex used for the parsing in the tool will eventually need to be adapted -- The usage stats plugin (and thus this tool too) supported apache log files in combined format. Any other format will require the adaptation of the regex.
Once the old log file is converted to the new format, it can be reprocessed, if needed. There is another tool that allows the reprocessing of the old log files, s. https://github.com/pkp/pkp-lib/blob/main/tools/reprocessUsageStatsMonth.php. (Currently only reprocessing of the log files for a whole month is supported -- because we now aggregate stats monthly for Geo and COUNTER R5. But there is one more issue left and coming: https://github.com/pkp/pkp-lib/issues/8293.)

Thus:
@ctgraham, I hope these two tools -- for log file format conversion and log file reprocessing -- should enable user to reprocess all the older log files.
@withanage, yes, this conversion tool first extracts the Geo data and hashed the IP address. Both, the hashed IP and Geo data are part and saved in the current log file format. The old log files will not be changed -- a new file for the new log file format is generated.
@marcbria, the old stats should actually not be removed, and the old log files only, only, only in very rare and special cases of need reprocessed. For the IP anonymization we use a hash with daily changed Salt, so that one the IP address is anonymized it is not possible to get the Geo data any more. This is however not necessary needed, because the Geo data is also calculated and saved in the new file format, before the IP is anonymized. It could only be that one would maybe later like to use a better/more precise Geo-IP DB, but...

@ctgraham, because (only) you have already used the apache log files for usage stats: Did/do your apache log files contain only access for one day? What is the `load_id` in the DB table metrics for those log files? -- I maybe have a problem: I assume one log file is for one day, and check the date accordingly, to know if it is an old log file the (monthly) usage stats already exists for... So it will maybe be a requirement that one file contains only the accesses of one day... :thinking:

**Comment by ctgraham** [comment]
In our past usage, the `load_id` was the filename of the Apache log.  This could cover an arbitrary time period; in our case this was commonly a week or a month.

**Comment by marcbria** [comment]
Thanks for the detailed feedback Bozana. 

So, if I understood you correctly, all will work transparently except if the log was processed using regular expressions, isn't it?

If so, I think you are offerin a backwards compatibility of 90ish % and seems very reasonable to me.

Just to keep it in mind: I think it is important to explain these changes in a) the release notes b) the dev mailing list c) the stats documentation maintained by the DIG.

Cheers,
m.

**Comment by asmecher** [comment]
(@bozana, I see conversation is continuing -- is this still in progress or shall I review the PR linked above?)

**Comment by bozana** [comment]
You can review it @asmecher. This tool is finished -- I just answered some questions how it all works now...

**Comment by bozana** [comment]
Hi @marcbria,
This conversion tool will work for all log files in the format that matches this regex: `/^(?P<ip>\S+) \S+ \S+ "(?P<date>.*?)" (?P<url>\S+) (?P<returnCode>\S+) "(?P<userAgent>.*?)"/`.
These are our old usage stats log files, but also apache access log files in combined format.
If someone has apache access log files in a different format, the regex in the tool can be adapted/changed so that it matches that different format (and those files can be converted as well). 
It also seems that apache log files are very rarely, if at all, used with usage stats plugin.
Thus I think the backward compatibility for the conversion to the new format is given. 

And yes, the documentation is still to come... :-) (s. https://github.com/pkp/pkp-lib/issues/8014 and https://github.com/pkp/pkp-lib/issues/7953)
Thanks a lot!

**Comment by bozana** [comment]
I've just added two more changes, that consider these two issues:
https://github.com/pkp/pkp-lib/issues/6611 and https://github.com/pkp/pkp-lib/issues/6573.

**Comment by bozana** [comment]
Phew... This turned out to be much more complicated than I first thought. :-\
I needed to consider log files from the release 2.x that were slightly different.
Because Apache URLs are different, e. g. they can contain either IDs or URL paths, I separated the conversion of Apache and usage stats plugin's log files. Thus, now there is a tool for Apache log file and a tool for internal usage stats log files.
I also separated the function `setAssoc` for OJS, OMP and OPS, to clearly see what is possible where (especially in Apache log files). Also, the way we get different representations (galley an publication format) from the DB and find the relation between them and submission files are different.
I hope I have considered all the cases and documented them in the code.
I removed the tool `copyAccessLogFile` because I considered the functionality in the new tool `convertApacheAccessLogFile`.
Here, I also separate the Apache log file by day - for log file reprocessing it is needed that the log files are per day and with the name containing the day at the end '_YYYYMMDD.log'.
Only a conversion of one log file at the time is possible - so that admins can immediately see and check the result.
I haven't used the locale keys for logs, warnings and errors - those tools will not be used regularly, so maybe no need to translate them?
And finally, OJS HTML viewer plugin does not use the 3. parameter `submissionFileId` for the download function. I changed that i. e. I added that 3. `submissionFileId` parameter, OK?

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/8467
https://github.com/pkp/ojs/pull/3644
https://github.com/pkp/omp/pull/1262 (only submodule update)
https://github.com/pkp/ops/pull/404  (only submodule update)

**Comment by bozana** [comment]
Hi @asmecher, see my comment above, what everything I needed to consider in this tool too: https://github.com/pkp/pkp-lib/issues/6849#issuecomment-1337282047.
Could you then take a look at the new PRs above?
Thanks a lot!

**Comment by bozana** [comment]
@asmecher, closely connected with this issue is the following: https://github.com/pkp/pkp-lib/issues/8508. Thus, after you have seen this one, you can then take a look at that other one...

**Comment by bozana** [comment]
@asmecher, now for real, I think I considered everything :-D
