### ISSUE TITLE
Galleys listed out of order on article landing page

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6878]
**Describe the bug**
On the issue table of contents, galleys for published articles are fetched in the template with a call to `$article->getGalleys()` which correctly sorts galleys according to sequence value.  On the article landing page however, galleys are displayed based on an iteration of `$primaryGalleys`, which is set in `ArticleHandler.inc.php` via a call to `$publication->getData('galleys')` instead.  This is sorted according to galley id.

I assume the reason for this is to ensure that versioning works correctly on the article details page, so the publication object is used instead. In that case, can the galleys in the publication be sorted according to sequence as well?

**To Reproduce**
1. Create and publish a submission with several galleys
2. Order the galleys in an arbitrary way where they are not in order of galley id
3. View the submission in the issue TOC, and the article landing page.

**What application are you using?**
 stable-3_2_1

**Comment by NateWr** [comment]
This is fixed in 3.3.0.x and 3.2.x can be patched by making the following change: https://github.com/pkp/ojs/commit/863fbbc22f4ee3c0a2c7aad69134f586669838f3#diff-f0a370f9d9f43bdbdd9872fab84ce6c65907dd0ef818b53df010e94e37aeddcc. I'll close this since I don't think we're going to do small bug fixes like this on the 3.2 branch, but if you'd like to create a PR against `stable-3_2_1` I'd be happy to merge it in.
