### ISSUE TITLE
REVIEW_REQUEST_REMIND_AUTO & REVIEW_REMIND_AUTO

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#6904]
Hello,

I'm not sure, but when there is a REVIEW_REQUEST_REMIND_AUTO on a review assignment, REVIEW_REMIND_AUTO will never send, because dateReminded is already set.
(https://github.com/pkp/pkp-lib/blob/stable-3_3_1/classes/task/ReviewReminder.inc.php#L138) 

If I'm not wrong, maybe documentation should be updated, or for our case, dateReminded should be reset when reviewer accepts the review request.

Regards,
Sim

**Comment by asmecher** [comment]
Hi @forgive38 -- good spotting!

In OJS 2.x, the reminder date [was reset to `null`](https://github.com/pkp/ojs/blob/857b5bbcd68f74c28b4659a97a8bc4313f5f2091/classes/submission/reviewer/ReviewerAction.inc.php#L62) when the submission was accepted, so the same column could be re-used for the overdue review reminder. When the `ReviewerAction.inc.php` class was moved to https://github.com/pkp/pkp-lib, that part was removed (probably because the reminder code was being rewritten).

The commit https://github.com/pkp/pkp-lib/commit/14f904468134c8780d470e36bba9f7f63ff4055c should fix it.
