### ISSUE TITLE
[OJS] Delete plugin does not remove versions entries

### ISSUE THREAD

**Issue by pablovp86** [pkp/pkp-lib#6906]
Tried to reinstall and older version of a plugin, since OJS doesn't permit downgrades. To do that, I followed the steps bellow:

1) deleted the plugin (version 1.0.1.0)
2) uploaded the plugin (version 1.0.0.0)
3) upload process took longer than usual, and the plugin panel on the admin dashboard stopped working:
![Captura de tela de 2021-04-01 15-00-23](https://user-images.githubusercontent.com/26493682/113337129-ba9a7d00-92fd-11eb-8a4c-3c8e5c09d934.png)

On the PHP logs, the following error is displayed:

`ojs2: You are trying to downgrade the product "signWriting" from version [1.0.1.0] to version [1.0.0.0]. Downgrades are not supported.`

The plugin is wiped of the filesystem, but the versions table still have entries for the deleted plugin:

+-------+-------+----------+-------+---------------------+---------+-----------------+-------------+--------------------+-----------+----------+
| major | minor | revision | build | date_installed      | current | product_type    | product     | product_class_name | lazy_load | sitewide |
+-------+-------+----------+-------+---------------------+---------+-----------------+-------------+--------------------+-----------+----------+
|     1 |     0 |        0 |     0 | 2021-03-11 21:07:05 |       0 | plugins.generic | signWriting | SignWritingPlugin  |         1 |        0 |
|     1 |     0 |        1 |     0 | 2021-04-01 17:24:55 |       1 | plugins.generic | signWriting | SignWritingPlugin  |         1 |        0 |
+-------+-------+----------+-------+---------------------+---------+-----------------+-------------+--------------------+-----------+----------+

Tried with other plugins, like the lensGalley shipped with OJS, and the behavior is the same.

Reproduced on OJS version: 3.3.0.3

**Comment by asmecher** [comment]
@pablovp86, that is currently intentional behaviour -- as the error says, downgrades are currently not supported. Some plugins install/create database tables, scheduled tasks, etc., and we make no guarantee that it'll be possible to move from a newer plugin version to an older plugin version (and removing the plugin does not remove these additional elements). So for now, you'll need to intervene in the `versions` table if you want to force a plugin downgrade.

This may evolve in the future, but at the moment it's intentional, so I'll close the issue. However, if you think this is an area you can contribute code, we'd be happy to review it.
