### ISSUE TITLE
Show exception error message when a plugin migration fails

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6921]
When a plugin migration fails, the exception error message is not shown, so there is no way to know why it failed.

**Comment by NateWr** [comment]
@asmecher is this safe to show? I am assuming that whoever is doing the installation process will have privileges to see the full exception. But can a plugin migration error show up during plugin install/uninstall?

PR:
https://github.com/pkp/pkp-lib/pull/6922

Tests:
https://github.com/pkp/ojs/pull/3098

**Comment by sujit-jaunjal** [comment]
@NateWr Hello, I know this is not a right way to communicate to someone but I'm in little urgency, I was doing a project for organization and their demand is to integrate pkp like ojs into organization's framework, I went through many searches but couldn't find a way or tutorial to do so...can you pleaseeee help me ?

**Comment by sujit-jaunjal** [comment]
Like how am I supposed to integrate framework and use pkp ojs plugins or functionalities in backend ?

**Comment by sujit-jaunjal** [comment]
Please reply asap, you can contact me here, here's my mail - jaunjalsujit@gmail.com ,  please help me with a little guidance

**Comment by asmecher** [comment]
@NateWr, yes, I think that's safe to show, since it can only arise during a privileged user's interaction with the system. It can show up during plugin install/uninstall, e.g. if a migration attempts to create a table that already exists.

@sujit-jaunjal, the best place to ask general questions is the support forum: https://forum.pkp.sfu.ca

**Comment by NateWr** [comment]
Merged!
