### ISSUE TITLE
Dashboard tabs label function

### ISSUE THREAD

**Issue by ronniebrito** [pkp/pkp-lib#6942]
hi, 

this is not really a bug , but just a help we need:

we are developing a translation plugin for OJS to SignLanguages and we need to load HTML into the Dashboard tabs.

the original function that load these labels (My Queue, Unassigned, All, etc..) escapes HTML and the content isnt showing as we need to display written signs 

so I ask you what function we need to overrride to disable HTML escaping

below there are images that illustrate our problem

thank you

![image](https://user-images.githubusercontent.com/1824263/114450890-f3174200-9bac-11eb-9340-1138f9dc4de7.png)

![image](https://user-images.githubusercontent.com/1824263/114451437-9c5e3800-9bad-11eb-9882-b9feb216e523.png)

**Comment by NateWr** [comment]
Hi @ronniebrito,

Unfortunately, I don't think this will be possible without overwriting the UI completely. The HTML escaping is a core part of our template as a security best practice. Although it is possible to permit HTML to be injected at particular places, it is not generally available. If it were possible to override this in some way, it would quickly become a security risk because user-provided data could be used to inject malicious code.

**Comment by ronniebrito** [comment]
thanks @NateWr , undesrtand
we'll try another aproach :)

**Comment by ronniebrito** [comment]
thanks @NateWr , undesrtood :)
we'll try another aproach
