### ISSUE TITLE
mEDRA Export: PHP Fatal error after upgrade

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#6956]
**Describe the bug**
After upgrade from OJS 3.2.1-3 to 3.3.0-4 mEDRA Export has stopped working (blank page: 500 internal server error).
I upgrade mEDRA plugin (DOI to mEDRA xml export and registration plugin) to version 3.0.0.1.
When export the log is:

`PHP Fatal error:  Uncaught Error: Call to a member function setDeployment() on null in /home/ojs/ojs-3.3.0-4/classes/plugins/PubObjectsExportPlugin.inc.php:388\nStack trace:\n#0 /home/ojs/ojs-3.3.0-4/classes/plugins/PubObjectsExportPlugin.inc.php(196): PubObjectsExportPlugin->exportXML()\n#1 /home/ojs/ojs-3.3.0-4/classes/plugins/PubObjectsExportPlugin.inc.php(171): PubObjectsExportPlugin->executeExportAction()\n#2 /home/ojs/ojs-3.3.0-4/classes/plugins/DOIPubIdExportPlugin.inc.php(29): PubObjectsExportPlugin->display()\n#3 /home/ojs/ojs-3.3.0-4/lib/pkp/pages/management/PKPToolsHandler.inc.php(94): DOIPubIdExportPlugin->display()\n#4 /home/ojs/ojs-3.3.0-4/lib/pkp/classes/core/PKPRouter.inc.php(395): PKPToolsHandler->importexport()\n#5 /home/ojs/ojs-3.3.0-4/lib/pkp/classes/core/PKPPageRouter.inc.php(246): PKPRouter->_authorizeInitializeAndCallRequest()\n#6 /home/ojs/ojs-3.3.0-4/lib/pkp/classes/core/Dispatcher.inc.php(144): PKPPageRouter->route()\n#7 /home/ojs/ojs-3.3.0-4/lib/pkp/classes/core/PKPApplication.inc.php(364): Dispatcher->dispat in /home/ojs/ojs-3.3.0-4/classes/plugins/PubObjectsExportPlugin.inc.php on line 388, referer: https://URL/management/importexport/plugin/MedraExportPlugin`

**To Reproduce**
1. Go to Tools -> mEDRA Export ->Articles then select some 
2. Click on Export
3. See error above

**What application are you using?**
 OJS 3.3.0-4

**Comment by bozana** [comment]
Hi @eniocarboni,
In the 3.3.0 the medra plugin was removed from core to the plugin gallery. Thereby we needed to remove the filters used by the medra plugin in the upgrade script (s. https://github.com/pkp/ojs/blob/stable-3_3_0/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php#L43-L46).
How did you do the medra plugin update? -- I would think that you would need to install the plugin anew. By the installation all the necessary filters would be installed (again).

**Comment by eniocarboni** [comment]
Yes, from the plugin gallery, I did the upgrade directly as the installation was not possible. 
Thank you very much, looking forward to how to fix this.

**Comment by bozana** [comment]
@asmecher, when I moved the medra plugin to its own repository and made it available via plugin gallery, I removed the scheduled task and filters, but not the entries in the DB table versions. This way the plugin gallery offers the user to update the plugin, but that way the filters will not be (re-)installed. Should I also remove the medra entries from the DB table versions during the 3.3.0 upgrade here https://github.com/pkp/ojs/blob/stable-3_3_0/classes/migration/upgrade/OJSv3_3_0UpgradeMigration.inc.php#L43-L46? -- Then the plugin gallery would offer the plugin install, right? -- I assume the new installation would be the correct action/solution, because we removed the plugin code...
If so, could you please double check the PR:
stable_3_3_0: https://github.com/pkp/ojs/pull/3108

**Comment by eniocarboni** [comment]
Hi @bozana in my test env I execute:
**test 1:**
1.1 - `DELETE from versions WHERE product_type='plugins.importexport' AND product='medra';`
1.2 - reload the gallery plugins. 
1.3 - the problem **is not solved**
**test 2:**
2.1 - `DELETE from versions WHERE product_type='plugins.importexport' AND product='medra';`
2.2 - rm -rf plugins/importexport/medra
2.3 - In Gallery Plugins I install medra 
2.4 - test export **article OK**

The only thing I notice is that in the "versions" table the previous versions of the mEDRA plugin are lost with the relative installation dates.

If you don't see any collateral issues I would upgrade my production environment as I did for test 2.

**Comment by bozana** [comment]
Hi @eniocarboni, yes, the test 2 is the way to fox the upgrade -- the execution of the SQL statement that deletes the entries in the DB table versions as well as the removal of the plugin folder is needed.
The earlier plugin versions track is not necessary needed.
Is the situation on your production environment the same -- did you upgrade to 3.3.0.4 and update the mEDRA plugin? If so, then you can execute those test 2 steps there too. Else, if you did not upgraded to 3.3.0.4 yet, you can adapt that upgrade script as in the PR above before you upgrade to 3.3.0.4. This would then allow you to install (instead of update) the new medra plugin via the plugin gallery.
Thanks a lot!

**Comment by eniocarboni** [comment]
Perfect! thank you successfully applied test 2 also at the production site.

**Comment by bozana** [comment]
PR:
stable_3_3_0: pkp/ojs#3108

**Comment by bozana** [comment]
@asmecher, just a quick look? :point_up_2: :pray: :-)

**Comment by asmecher** [comment]
That's fine -- please go ahead, thanks!

**Comment by asmecher** [comment]
@bozana, I took the liberty of merging the PRs for `stable-3_3_1` and `main` (the `stable-3_3_0` one was already merged) -- let me know if that wasn't the plan!
