### ISSUE TITLE
[OMP] Unable to create press in a certain condition

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6957]
**Describe the bug**
When creating a new press, if there's just one language and the user press "Save" without selecting one, the primary locale will accuse an error, which is not possible to fix (selecting the language doesn't let me proceed).

**To Reproduce**
- Ensure the installation has just one locale
- Create a new press
- Leave the language unselected
- Save

**What application are you using?**
OMP /master

**Additional information**
![image](https://user-images.githubusercontent.com/361921/115124745-877a0e00-9fcc-11eb-9051-c51e8d45f44b.png)

**Comment by NateWr** [comment]
Ah yeah, good catch. So when only one language is supported we should pre-set these fields or just set them automatically on save.

**Comment by NateWr** [comment]
For the stable branches, I've just added a small bit of code to `AddContextForm.vue` so that changes to the `supportedLocales` will clear that error. For the `main` branch, I've removed language selection from the form when only one language is available.

PRs:
https://github.com/pkp/ui-library/pull/154 (`stable-3_3_0`  to be cherry-picked to `stable-3_3_1`)
https://github.com/pkp/ui-library/pull/155 (`main`)
https://github.com/pkp/pkp-lib/pull/6980 (`main`)

Tests:
https://github.com/pkp/ojs/pull/3115 (`stable-3_3_0`)
https://github.com/pkp/ojs/pull/3116 (`main`)

**Comment by asmecher** [comment]
@NateWr, does someone need to review these before merging?

**Comment by NateWr** [comment]
Merged to `stable-3_3_0` and `main` and cherry-picked to `stable-3_3_1`.
