### ISSUE TITLE
Payments records are not moved to target user when merging 

### ISSUE THREAD

**Issue by beghelli** [pkp/pkp-lib#705]
See: http://forum.pkp.sfu.ca/t/previous-payment-transactions-are-missing/3756/3

**Comment by asmecher** [comment]
Just a couple of comments -- but I think the majority of this code is already in the master codebase, so it should be ported there rather than leaving the bug to be rediscovered later. You'll have to modernize some of the reference use -- pretty much all references can be removed -- but otherwise it shouldn't be any different. Mind forward-porting as well? OMP and OJS master.
