### ISSUE TITLE
PKPFileService::download() calls exit function

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#7094]
OJS Version 3.3.x

File: PKPFileService.inc.php

At the end of the download() function exit() is called interrupting execution.

See: https://github.com/pkp/pkp-lib/blob/e6494e1b6c1798aa1d8e791e25f0df03a5733cef/classes/services/PKPFileService.inc.php#L159

Expected behaviour: Execution status is returned and script execution continues.

**Comment by asmecher** [comment]
@ronste, that's a long-standing behaviour; can you write a little more about what you're trying to do that this is blocking?

**Comment by ronste** [comment]
We use the download functionality for the export function of the DNB plugin. A temporary zip file is created that needs to be removed after successful download. Up to now (I'm working on the upgrade for OJS 3.3) we used the FileManager class to implement the download functionality. The FileManger does return execution to the calling script. I just wanted to follow the recommendations from the developer docs and stumbled across this issue.

**Comment by ronste** [comment]
By the way, what is the reason for exiting after the download?

**Comment by NateWr** [comment]
> By the way, what is the reason for exiting after the download?

We are preparing OJS to support third-party file systems, such as AWS, Azure or other cloud providers. In the future, a file download may result in a URL redirection to a remote service, so we want to enforce the behaviour that a download request is the end of the operation. In some ways, the design is intended to catch use cases like yours so that we can get them migrated to something new.

For 3.3, I recommend you us the ScheduledTasks system to regularly clear out these zip files. From 3.4, we are introducing a [job queue system](https://github.com/pkp/pkp-lib/issues/4622). That should make it easy to offload long-running tasks in jobs, and schedule jobs to clean up these files later. You may want to consider pivoting to that model, especially if DNB exports are potentially long-running tasks.

**Comment by ronste** [comment]
ScheduledTask doesn't seem to be an option for our plugin. In particular because there are OJS admins around that don't have administrative access to the hosting server to set up cronjobs. The plugin has to work without administrative access to the server.

For now I rather just copy the appropriate functions from FileManager to the plugin. With 3.4 I will consider the job queue system.
