### ISSUE TITLE
OMP 3.3.0.6 - OAI - Relation links broken

### ISSUE THREAD

**Issue by ohilbig01** [pkp/pkp-lib#7133]
Hi @asmecher and @NateWr ,

I noticed an error in the oai interface:
The 'Relation'-links are almost all broken.
Both in my own installation and in the PKP demo installation.

**To Reproduce**
1. Go to 
 https://demo.publicknowledgeproject.org/omp3/demo/index.php/aup-demo/oai?verb=ListRecords&metadataPrefix=oai_dc
2. Click on the Relation URL

**What application are you using?**
 OMP version 3.3.0.6

**Comment by ohilbig01** [comment]
Hi @NateWr ,

thank you very much.
In my case I have submissions with many publication formats, and the URL of the OAI_DC-Relation contains always the Id of the first publication format.
So, if I have ten pubFormats, one of the Relation links is okay, the other nine are all wrong.
I think at least in my installation there is no connection with versioning. I don't know, maybe we mean the same thing.

**Comment by asmecher** [comment]
@withanage, this appears to be caused by https://github.com/pkp/omp/commit/9f8b67d3173d368ee1dcd45faf6b7df3e02c5a78; the `$pubFormatFiles` list needs to be limited to files that are associated with that publication format, but instead all files are included for each publication format. (Was there a github issue associated with that addition? I don't see one.)

**Comment by dagosalas** [comment]
I have the same problem, I only have one language, but I publish in several formats (PDF, epub, mobi) and only the PDF URL works (which is the first one). 

Mi OMP:
https://libros.uanl.mx/index.php/u/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libros.uanl.mx:publicationFormat/1

**Comment by withanage** [comment]
Sorry, that was a bug I introduced as  @asmecher  mentioned here in  https://github.com/pkp/pkp-lib/issues/7133#issuecomment-864245940

I have sent a PR  for restricting the files.  https://github.com/pkp/omp/pull/988 in the OJS 3.3.0 branch

I have locally tested with several publication formats.

But @ohilbig01  and @dagosalas , if you could   confirm the fix  in your installations, will be very thankful!

**Comment by dagosalas** [comment]
Hi @withanage,

I applied the patch, and now it only shows a single entry in the Relation metadata, thanks.

But I have a doubt, in my case I publish three different formats for each book (epub, pdf and mobi).
Isn't it better to show all three formats in only one Relation metadata instead of to have three Record Headers?

For example, this is my book in OMP: https://libros.uanl.mx/index.php/u/catalog/book/89

And these are the three OAI record headers (one for each book format):
https://libros.uanl.mx/index.php/u/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libros.uanl.mx:publicationFormat/118

https://libros.uanl.mx/index.php/u/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libros.uanl.mx:publicationFormat/118

https://libros.uanl.mx/index.php/u/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:libros.uanl.mx:publicationFormat/120

This makes that when using a meta search engine, you get also three records. (example with another book):
https://rediab.uanl.mx/Search/Results?lookfor=El+Topo+Chico%3A+su+historia%2C+su+gente%2C+sus+manantiales&type=AllFields&limit=20

**Comment by withanage** [comment]
@dagosalas 

the use case what you are adressing is a general restriction in the OAI interface, cause the central distinguishing piece is the publication format in the OAI.

I think the reason for having separate entries for that was, that you can add  extensive metadata in publication format level. For your use case it may be not optimal solution. As you see, there is also onix metadata  related to a publication format. If we had to put all that information in a single entry, it would be very  messy.

**Comment by ohilbig01** [comment]
Hi @withanage,
 I can confirm the bugfix is working. There is only one relation link now and it works.

**Comment by withanage** [comment]
@ohilbig01  and @dagosalas 
Thank you both !  Appreciate your reporting and testing !
