### ISSUE TITLE
Errors after update OJS 3.2.1-4

### ISSUE THREAD

**Issue by diegomejia071** [pkp/pkp-lib#7169]
Hi,

I just updated the OJS version to 3.2.1-4, and activated some plugins and when trying to deactivate these I get the following error and the plugin does not deactivate:

`PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'PKPComponentRouter' does not have a method 'getRequestedPage' in /lib/pkp/classes/core/PKPRequest.inc.php on line 760, referer: /management/settings/website
`

Also when trying to load the main page of the magazine it shows me the following:

` PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 266240 bytes) in /lib/pkp/classes/db/DAO.inc.php on line 87, referer: http://xxxxxxxxxx/index.php/index
`

Also when I try to configure the settings of the Custom Header plugin, it shows me the following error.

`Declaration of CustomHeaderSettingsForm::execute($request, ...$functionArgs) should be compatible with Form::execute(...$functionArgs) in /plugins/generic/customHeader/CustomHeaderSettingsForm.inc.php on line 0, referer: /management/settings/website
`

![image](https://user-images.githubusercontent.com/21009904/124322811-c3416000-db45-11eb-941c-951acaee02e4.png)

The same goes for the AddThis plugin:

`PHP Warning:  Declaration of AddThisSettingsForm::fetch($request) should be compatible with Form::fetch($request, $template = NULL, $display = false) in /plugins/generic/addThis/AddThisSettingsForm.inc.php on line 0, referer: /management/settings/website`

And so it happens with different plugins, when I try to configure the settings.

**Comment by asmecher** [comment]
@diegomejia071, it looks like you're already working to resolve these issues in the forum:
- https://forum.pkp.sfu.ca/t/ojs-3-1-2-4-php-warning-declaration-of-journalsitesettingsform-execute-should-be-compatible-with-form-execute-functionargs-in-var-www-ojs-controllers-grid-admin-journal-form-journalsitesettingsform-inc-php-on-line-18/58415/2
- https://forum.pkp.sfu.ca/t/ojs-3-2-1-4-error-trying-to-disable-a-plugin/68628/3

I'll close this issue in favour of those discussions. It's better to keep a particular question to just one place -- otherwise it divides our support efforts.

**Comment by diegomejia071** [comment]
what happens is that in the forum nobody helps me with these problems

**Comment by asmecher** [comment]
Those posts are only an hour old :) If your post hasn't been answered after a week and you want to draw attention to them, post a follow-up reminder on the same thread.
