### ISSUE TITLE
Total count of API results incorrect

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7197]
**Describe the bug**
When the `/submissions` API endpoint returns the `itemsMax`, the `count` and `offset` restrictions are not being removed. That means the `itemsMax` will not show the true count of all possible items (for pagination).

This effects all three entities that have been converted to use a `Collector`: submissions, publications and announcements.

**What application are you using?**
3.4 pre-release

**Comment by NateWr** [comment]
This was fixed by adding a method, `unlimited()`, to each `Collector` that removes the `count` and `offset` restrictions.

PR:
https://github.com/pkp/pkp-lib/pull/7198

Tests:
https://github.com/pkp/ojs/pull/3163

@asmecher can I ask you to take a look at the `getCount()` method for the Submission and Announcement DAOs? Laravel's `count()` method was not working as I expected on the query. It would always return `1`. So the following:

```
$collector->getQueryBuilder()->get(); // 27 or whatever
$collector->getQueryBuilder()->count(); // always 1
```

I fixed it by getting a row of ids and counting the rows:

https://github.com/pkp/pkp-lib/pull/7198/files#diff-e0f5df881d7a428b58d510cf3358490b782570a02877a6e9ba5bd69fdb4c4875R92-R96

But I don't understand why Laravel's `count()` method isn't working. I think it's something to do with the grouping?

**Comment by NateWr** [comment]
Merged to `main`.

**Comment by asmecher** [comment]
@NateWr, the counting problem is an SQL one, not a Laravel one. The query you're writing is doing this roughly:
```
SELECT COUNT(*) FROM (SELECT s.* FROM submissions s LEFT JOIN publications p ON (s.submission_id = p.submission_id) GROUP BY s.submission_id);
```
The `COUNT` aggregate function and `GROUP BY` will interact in ways you don't want and can't change.

What you're looking for (and what ADODB used to do) is this:
```
SELECT COUNT(*) FROM (SELECT s.* FROM submissions s LEFT JOIN publications p ON (s.submission_id = p.submission_id) GROUP BY s.submission_id) AS count_query;
```
However, neither of those is very efficient because of the combinatorial explosion of the query followed by the `GROUP BY` sweeping-under-the-rug. I think the best solution will be to rewrite the query to avoid `GROUP BY`, which will as a side-effect cure the interaction between `COUNT` and `GROUP BY`, permitting `->count()` to function as expected.

I documented this in Slack, but I'll adapt it here so it doesn't go away when we hit the Slack event horizon:

> Please try to avoid using GROUP BY clauses (or equivalently SELECT DISTINCT) unless they're really necessary. We haven't used them much before, but I think we can use constructions like
>
> ```
> SELECT u.* FROM users u nWHERE user_id IN (SELECT user_id FROM user_settings WHERE setting_value LIKE '%search%')
> ```
> ...rather than...
> ```
> SELECT DISTINCT u.* FROM users u JOIN user_settings AS us ON (u.user_id = us.user_id AND us.setting_value LIKE '%search%')
> ```
>
> I'm trying out a construction that does this fairly cleanly using the query builder and will drop a link here once I've pushed it up.

See the (currently WIP) users collector class for an example of a complex query builder that does not depend on `GROUP BY`:
https://github.com/pkp/pkp-lib/pull/7170/files#diff-1d3de820df407fc981c2a64acb5970be700de5a01a087ad65eab5719d7fdb133
