### ISSUE TITLE
[OJS 3.1.2.1] How to close add discussion option to authors if the article was rejected

### ISSUE THREAD

**Issue by elenacn** [pkp/pkp-lib#7252]
The text is rejected and the corresponding authors can consult it and try to resubmit in the discussions. That's impossible. There is some option to put a lock so when the manuscript was rejected they can no longer resubmit the manuscript.

![image](https://user-images.githubusercontent.com/50058327/131754774-eacb6ee1-d8c1-43f8-92c1-017c7731de3e.png)

I try used the “Closed” button, but I read that flag is purely informational.

I have OJS 3.1.2.1

Thank you for all.

Regards,
Elena Cruz.

**Comment by NateWr** [comment]
Hi @elenacn, there's no support for locking discussions after a submission is rejected. I think we would hesitate to add this feature, because it is common enough for authors to need a way to contact editors after rejection (for example, in case the submission was mistakenly rejected).

Are you getting a lot of inappropriate follow-up from authors? If so, you can try to unassign editors from a declined submission or in extreme cases disable the offending user.

I'm going to close this issue because we're not likely to change this behaviour. But feel free to reply if you want to make the case that we should.
