### ISSUE TITLE
Error on sending an email

### ISSUE THREAD

**Issue by engahmed** [pkp/pkp-lib#7255]
When I send an email I got this erro.
From Administration> gosted journal> choose any journal> users> select any user> Email
When I send an email to any user I get this error
![image](https://user-images.githubusercontent.com/25064051/131813841-3130bd0c-388c-4806-afac-717dfff305b2.png)

**Comment by asmecher** [comment]
@engahmed, could you post your question on the PKP support forum (https://forum.pkp.sfu.ca) along with details: What version of OJS are you using? Is there anything in your PHP error log? What is your email sending configuration from `config.inc.php` (not including passwords)?

If it turns out to be a bug rather than a misconfiguration, we can re-open this issue.
