### ISSUE TITLE
Handle email template localization more gracefully

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7258]
**Describe the problem you would like to solve**
Email template data should have a fallback locale if the one requested isn't available. 

The current approach is to load template variables in all available locales and then the default logic is to load needed localization by the current application locale. It's possible to override this behaviour but if the specified locale isn't available, the fatal error is thrown during template variables compilation. Consider a fallback locale for this case. 

**Describe the solution you'd like**
Define a locale before or when the Mailable is instantiated in opposite to it's handled now (during template compilation). Use `getLocalizedData()` method on the associated object in places, where variable values are retrieved.  

**Who is asking for this feature?**
Discussion: https://github.com/pkp/pkp-lib/pull/7221#discussion_r685919973

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by NateWr** [comment]
@Vitaliy-1 as part of my work on email sending, I've put together a possible solution to this. You can see the changes to the Mailable and Mailer classes in this commit: https://github.com/NateWr/pkp-lib/commit/4c668d05d5de9d0fef1449989822223a2f626497

The way this works is that `*****MailVariable` classes are instantiated and stored in the `Mailable` itself. Then we ask each `****MailVariable` class for its `viewData` right before we send the email: https://github.com/NateWr/pkp-lib/commit/4c668d05d5de9d0fef1449989822223a2f626497#diff-00fb1a0fb904225cb23b33d685076986ce722d63171edcbf085b62a7b8fee74bR108-R112

Mailables now have a `setLocale()` method to specifically set the locale:

```php
$mailable = new MyMailable($context, $submission);
$mailable->setLocale($locale);
Mail::send($mailable);
```

If `setLocale()` is not called, it will default to the current locale:

```php
$mailable = new MyMailable($context, $submission);
Mail::send($mailable); // sends using AppLocale::getLocale()
```

Finally, and this is the key part that I needed for the email sending UI, you can get the email template data for any locale on demand:

```php
$mailable = new MyMailable($context, $submission);
$variables = $mailable->getData('en_US');
// [
//  'submissionTitle' => 'The title in English',
// ]
```

This allows me to load separate variables for each locale into the browser, so when the user wants to send an email in a different locale, we can load those variables in:

```php
$variables = [];
foreach ($this->locales as $locale) {
    $variables[$locale] = $mailable->getData($locale);
}
```

Can you take a look at this and see if you can think of any problems from this? 

The one thing I can think of is that it may not be performant to compile variables for each locale, if compiling the variables requires a run to the database. In such cases, I think the `****MailVariable` should get all the data it needs in the constructor, so that when `->values()` is called, no additional database requests need to be made. For example, the `StageAssignmentEmailVariable` could look like this:

```php
class StageAssignmentEmailVariable extends Variable
{
    protected array $decidingEditors;

    public function __construct(StageAssignment $stageAssignment)
    {
        $editorsStageAssignments = /* ... */
        foreach ($editorsStageAssignments as $editorsStageAssignment) {
            if (!$editorsStageAssignment->getRecommendOnly()) {
                continue;
            }
            $this->decidingEditors = Repo::user()->get($editorsStageAssignment->getUserId());
        }
    }

    public function values(string $locale): array
    {
        return
        [
            self::DECISION_MAKING_EDITORS => $this->getEditors($locale),
        ];
    }
    
    protected function getEditors(string $locale): string
    {
        foreach ($this->decidingEditors as $decidingEditor) {
            $editorNames[] = $decidingEditor->getFullName(true, false, $locale);
        }

        return join(__('common.commaListSeparator', [], $locale), $editorNames);
    }
}
```

**Comment by NateWr** [comment]
@Vitaliy-1 here are some PRs to handle this. Can you take a look and let me know what you think? Here are the key parts.

When a mailable is created, the `PKP\mail\Variable` objects are stored in the mailable:

https://github.com/pkp/pkp-lib/pull/7476/files#diff-879db820d1028315db1fda7368be897c3e3acfa0cac69c703df33ba6744a63c7R216-R228

The values are compiled right before the mailable is sent:

https://github.com/pkp/pkp-lib/pull/7476/files#diff-00fb1a0fb904225cb23b33d685076986ce722d63171edcbf085b62a7b8fee74bR104-R110

We can ask the mailable to get us the data for a specific locale even if we're not sending it:

https://github.com/pkp/pkp-lib/pull/7476/files#diff-879db820d1028315db1fda7368be897c3e3acfa0cac69c703df33ba6744a63c7R111-R132

In the code, that would look like this:

```php
$mailable = new ExampleMailable($context);
$data = [];
foreach ($locales as $locale) {
    $data[$locale] = $mailable->getData($locale);
}
```
 In order to support this, the `PKP\mail\Variable::values()` method has been made public and it also receives a locale. The values are then returned for that specific locale.

https://github.com/pkp/pkp-lib/pull/7476/files#diff-5cfbae7764be51ef5f41f84fc06dc0928f1075cd2dcc9b6ecbaabebad1bcb25bR47-R52


PRs:
https://github.com/pkp/pkp-lib/pull/7476
https://github.com/pkp/ojs/pull/3236

**Comment by NateWr** [comment]
All merged to `main`.
