### ISSUE TITLE
TypeError on getFileCache

### ISSUE THREAD

**Issue by thisnugroho** [pkp/pkp-lib#7262]
**Describe the bug**
TypeError when calling method `getFileCache` from class `CacheManager` which is referer to GenericCache, the problem is on third parameter (fallback) in `getFileCache` it's expect an callback function so when it's null,it's causes TypeError like the picture i attach,it's happend on `KeywordCloudBlock` plugin

**To Reproduce**
1. Install `KeywordCloudBlock` plugin
2. Enable it

**What application are you using?**
 OJS  3.3.0.8

**Additional information**
![image](https://user-images.githubusercontent.com/49790011/132315175-c9030d2d-41ce-4dee-ae6e-a6dd8cb96749.png)

**Comment by asmecher** [comment]
@thisnugroho, I think this might be a problem in the keyword cloud code rather than pkp-lib; when using a cache, there should always be a fallback function.

**Comment by thisnugroho** [comment]
> @thisnugroho, I think this might be a problem in the keyword cloud code rather than pkp-lib; when using a cache, there should always be a fallback function.

Thank you for your response, so better way to do it is create a function that return null instead put null directly as a parameter ?

**Comment by asmecher** [comment]
@thisnugroho, I suppose you're using the Lepidus fork of keywordCloud? If so, the problem is this line of code:

https://github.com/lepidus/keywordCloud/blob/26a2c39c5d8934b280471e7effaf3184e0be749c/KeywordCloudBlockPlugin.inc.php#L61

The 3rd parameter should be a callback, not `null`. I'm not quite sure what that code is doing with the cache tools, but passing in `null` in place of a callback isn't right. It might be that a function returning `null` will do the trick; I'd recommend working through it at https://github.com/lepidus/keywordCloud/issues/16 with the plugin author.

**Comment by thisnugroho** [comment]
> @thisnugroho, I suppose you're using the Lepidus fork of keywordCloud? If so, the problem is this line of code:
> 
> https://github.com/lepidus/keywordCloud/blob/26a2c39c5d8934b280471e7effaf3184e0be749c/KeywordCloudBlockPlugin.inc.php#L61
> 
> The 3rd parameter should be a callback, not `null`. I'm not quite sure what that code is doing with the cache tools, but passing in `null` in place of a callback isn't right. It might be that a function returning `null` will do the trick; I'd recommend working through it at https://github.com/lepidus/keywordCloud/issues/16 with the plugin author.

Yes,i understand now, thank you so much.
