### ISSUE TITLE
Can't upgrade to 3.2.x on PHP 8 due to use of get_magic_quotes_runtime

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7275]
**Describe the bug**
Although 3.3 is compatible with PHP 8, when upgrading from 3.1.x the `get_magic_quotes_runtime` function is called. This causes a fatal error and the upgrade does not complete.

The `get_magic_quotes_runtime` method has been removed from PHP 8, but it is still used by ADODB.

**To Reproduce**
1. Upgrade from 3.1.x to 3.3.x on PHP

**What application are you using?**
3.3

**Additional information**
Here is the error message provided in the [forum](https://forum.pkp.sfu.ca/t/error-when-upgrading-ojs-on-php8/69717).

```
PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_runtime() in /var/www/ojs/lib/pkp/lib/vendor/adodb/adodb-php/adodb-xmlschema.inc.php:1307
Stack trace:
#0 /var/www/ojs/lib/pkp/classes/install/Installer.inc.php(364): adoSchema->__construct()
#1 /var/www/ojs/lib/pkp/classes/install/Installer.inc.php(251): Installer->executeAction()
#2 /var/www/ojs/lib/pkp/classes/install/Installer.inc.php(174): Installer->executeInstaller()
#3 /var/www/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(89): Installer->execute()
#4 /var/www/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(65): UpgradeTool->upgrade()
#5 /var/www/ojs/tools/upgrade.php(22): UpgradeTool->execute()
#6 {main}
  thrown in /var/www/ojs/lib/pkp/lib/vendor/adodb/adodb-php/adodb-xmlschema.inc.php on line 1307
```

**Comment by NateWr** [comment]
Actually, this may not be an issue. It sounds like the upgrade process might succeed if all dependencies are updated: https://forum.pkp.sfu.ca/t/error-when-upgrading-ojs-on-php8/69717/2?u=natewr

**Comment by OyvindLGjesdal** [comment]
Sorry for confusing the matter, the error is still present. I updated with composer and thought we might have had just old vendor files, since we had accidentally skipped the update step. 

But `composer.json` in pkp-lib for adodb points to  `dev-v5.20.18-mods` and this contains the `get_magic_quotes_runtime` which I think is here https://github.com/asmecher/ADOdb/blob/v5.20.18-mods/adodb-xmlschema.inc.php#L1307

Could maybe just lines 1307 to 1310 be removed, since the php_ini which is set also looks like it was removed a long time ago?

```
magic_quotes_runtime | "0" | PHP_INI_ALL | Removed in PHP 5.4.0.
-- | -- | -- | --
```

from https://www.php.net/manual/en/info.configuration.php

**Comment by asmecher** [comment]
This was removed from ADODB starting with 5.21: https://github.com/ADOdb/ADOdb/issues/674

As you've noted, we're still on a fork of 5.20.18, and there have been enough changes in the meantime that rebasing our modifications onto v5.21.2, or cherry-picking https://github.com/dregad/ADOdb/commit/faf71c5f3ef8823328f4f98e4562744ff04632ee, are not trivial.

Our ADODB support is "deprecated" and it is only used for upgrades involving OJS prior to 3.3.0. So I'm leaning towards not changing the ADODB version, and instead just truncating calls to the `magic_quotes` stuff in the least risky way possible.

@OyvindLGjesdal, could you try applying 
https://github.com/asmecher/ADOdb/commit/f845db84fbd17e50c5682e1575ac1fb136160148 to your ADODB (that'll be in `lib/pkp/lib/vendor/adodb/adodb-php/` in your OJS directory) before re-running the upgrade process? If you can confirm that this resolves the problem, I can commit it for the next OJS/OMP/OPS release.

**Comment by OyvindLGjesdal** [comment]
The upgrade goes further, but then fails. I can't tell if the next error is also related to changes in php8, but there are many warnings in the terminal. See attached log. 

[upgrade_output.txt](https://github.com/pkp/pkp-lib/files/7139845/upgrade_output.txt)

**Comment by OyvindLGjesdal** [comment]
Next output and error after applying `ALTER TABLE journal_settings ALTER COLUMN setting_type DROP NOT NULL;` and rerunning upgrade attached 
[upgrade_output2.txt](https://github.com/pkp/pkp-lib/files/7139941/upgrade_output2.txt)

**Comment by asmecher** [comment]
@OyvindLGjesdal, those repeated warnings can be cleaned up with https://github.com/asmecher/ADOdb/commit/228c62019235f0c640b866c37a5aa3c19e6c714d. They are cosmetic, but I'll wrap them in as well.

The next relevant issue you're hitting is this one:
```
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /var/www/ojs/lib/pkp/classes/core/DataObject.inc.php:133
Stack trace:
#0 /var/www/ojs/lib/pkp/classes/db/DAO.inc.php(494): DataObject->setData()
#1 /var/www/ojs/lib/pkp/classes/user/UserDAO.inc.php(239): DAO->getDataObjectSettings()
#2 /var/www/ojs/lib/pkp/classes/db/DAOResultFactory.inc.php(94): UserDAO->_returnUserFromRowWithData()
#3 /var/www/ojs/lib/pkp/classes/install/Installer.inc.php(991): DAOResultFactory->next()
#4 /var/www/ojs/lib/pkp/classes/install/Installer.inc.php(444): Installer->setStatsEmailSettings()
#5 /var/www/ojs/lib/pkp/classes/install/Installer.inc.php(251): Installer->executeAction()
#6 /var/www/ojs/lib/pkp/classes/install/Installer.inc.php(174): Installer->executeInstaller()
#7 /var/www/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(89): Installer->execute()
#8 /var/www/ojs/lib/pkp/classes/cliTool/UpgradeTool.inc.php(65): UpgradeTool->upgrade()
#9 /var/www/ojs/tools/upgrade.php(22): UpgradeTool->execute()
#10 {main}
  thrown in /var/www/ojs/lib/pkp/classes/core/DataObject.inc.php on line 133
```
I suspect this is due to entries in the `user_settings` table that are expected to be multilingual (i.e. the `locale` column should be set for each entry) but for which there is missing `locale` data. But that's a different issue -- could you pursue it on the support forum (https://forum.pkp.sfu.ca) with all the relevant details? I'll close this entry.

**Comment by OyvindLGjesdal** [comment]
Thank you fix! I've rebuilt against the stable branch in pkp lib, and get to the same error message. I will follow it up in the forum.
