### ISSUE TITLE
[OPS] Ability for authors to inform "version notes"

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#7280]
**Describe the problem you would like to solve**
When a new version of a preprint is created, it is unclear from a reader's point of view what has changed between the previous version to the new version.

**Describe the solution you'd like**
Some servers (like ChemRxiv, see example [here](https://chemrxiv.org/engage/chemrxiv/article-details/61172e5745805d0dd3870af8) under "Version Notes") collect notes from authors when they are creating a new version.

The field can be optional or mandatory (up for discussion). In ChemRxiv, it is optional.

**Who is asking for this feature?**
This is helpful for both Admins (so that we know if a new version was created for the right reasons) and for readers.

**Comment by asmecher** [comment]
This sounds like a good idea, @alexxxmendonca. Could you foresee a role for both public and private notes (those shown to readers, and those kept privately for administrative purposes)? I would expect admins to assume notes are private and maybe be surprised by their publication.

**Comment by alexxxmendonca** [comment]
@asmecher I don't see a reason to collect private and public notes. I think most times authors would have to copy and paste the same contents on both fields.

In the spirit of open science, this would give some light and reasoning for creating a new version for both Admins and the community.

_I would expect admins to assume notes are private and maybe be surprised by their publication._

This is a valid concern and in order to make things right, there should be a note saying that the contents would be displayed publicly. 

In fact, there is also the matter of multilanguism but I assume this would be covered by default?

**Comment by asmecher** [comment]
Ah, I see you're thinking about OPS, when I was mostly thinking about OJS. I think the issue of private vs. public notes might be more prominent in OJS. I would favour an approach that doesn't introduce two fields, if that's acceptable for editors -- I suppose they could use the existing editorial notes feature for private notes if a public field isn't appropriate.

I don't think we can expect authors (or even editors) to translate notes into multiple languages, but the usual approach of providing a multilingual option and only requiring the primary language seems workable here.

**Comment by alexxxmendonca** [comment]
@asmecher yeah, I was thinking mostly about OPS.

I can see how it would be important to keep in mind the issue of private vs. public notes within the journal context.

**Comment by NateWr** [comment]
We've done some research around this when we first implemented versioning. This problem overlaps a little bit with the minor vs major version distinction, as well as questions about how to represent versions in downstream providers. You can find those details filed in https://github.com/pkp/pkp-lib/issues/4860.

The conclusion there was to add a `publicationDateType` field to match the JATS specification and a `publicationSummary` that acted as a short, human-facing description of the changes (like a commit message).

Unfortunately, the JATS `publicationDateType` does not support a distinction between major vs minor versions. That's why we abandoned the work at the time. But I think we could introduce a distinction in the meantime in the hopes that we can eventually  map it to an appropriate specification in JATS or Crossref.

This would not account for private notes. But I wonder if we can just encourage editors to use discussions for this purpose and keep the publication object simple (and public).

**Comment by NateWr** [comment]
I've converted this to a [feature request](https://forum.pkp.sfu.ca/t/add-support-for-version-notes-or-a-summary-of-changes/74210) on the forum. Please add your thoughts and suggestions there.
