### ISSUE TITLE
EntityDAO input sanitization does not allow nullable int columns

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7325]
When a `INT` table column handled by an EntityDAO is sometimes nullable, operations on it can pass in `null`.
However, this is passed upstream from `EntityDAO::getPrimaryDbProps` to `lib/pkp/classes/db/DAO.inc.php`'s `convertToDB` function, which will cast it to `int` regardless of its `nullable` status.

When `null` values are passed in and the column is nullable, EntityDAO::getPrimaryDbProps` should respect it.

**Comment by asmecher** [comment]
This can be worked around with:
```diff
diff --git a/classes/core/EntityDAO.inc.php b/classes/core/EntityDAO.inc.php
index 871842c83..b81d3a7ff 100644
--- a/classes/core/EntityDAO.inc.php
+++ b/classes/core/EntityDAO.inc.php
@@ -285,7 +284,11 @@ abstract class EntityDAO
         $primaryDbProps = [];
         foreach ($this->primaryTableColumns as $propName => $columnName) {
             if ($propName !== 'id' && array_key_exists($propName, $sanitizedProps)) {
-                $primaryDbProps[$columnName] = $this->convertToDB($sanitizedProps[$propName], $schema->properties->{$propName}->type);
+                if ($schema->properties->{$propName}->type == 'integer' && in_array('nullable', $schema->properties->{$propName}->validation) && $sanitizedProps[$propName] === null) {
+                    $primaryDbProps[$columnName] = null;
+                } else {
+                    $primaryDbProps[$columnName] = $this->convertToDB($sanitizedProps[$propName], $schema->properties->{$propName}->type);
+                }
                 // Convert empty string values for DATETIME columns into null values
                 // because an empty string can not be saved to a DATETIME column
                 if ($primaryDbProps[$columnName] === ''             if ($primaryDbProps[$columnName] === ''
```
...but this is messy.

@NateWr, I wasn't sure about the status of `deprecatedDao` in general -- would you mind taking a look at this? Maybe it's a better time to remove that class entirely?

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/7334
- https://github.com/pkp/ojs/pull/3190 (tests only)

**Comment by NateWr** [comment]
Yeah, `null` values (and removing an existing value) have been a bit tricky to handle. Are you sure that this case only applies to a nullable `int` column on the primary db? If so, then I think your solution is the most appropriate. However, it won't apply to any properties not in the primary database (ie - those in the _settings table).

If this really only applies to the primary table, I wonder if it makes sense to check the table schema directly, instead of the entity schema. The entity schema can be modified by a plugin, so may be the "higher" source of truth. But the table schema is the rightful authority regarding whether the column accepts a null value.

Is this definitely related to the DAO? Or is it possible that this is originating in API requests. There is some special handling there to convert http request data (strings) into the appropriate types:

https://github.com/pkp/pkp-lib/blob/main/classes/handler/APIHandler.inc.php#L298-L313

> I wasn't sure about the status of deprecatedDao in general -- would you mind taking a look at this? Maybe it's a better time to remove that class entirely?

I think we're still going to need that class for a while, unless we're prepared to rewrite a fair chunk of code. The "deprecated DAO" is really just `lib/pkp/classes/db/DAO.inc.php`. It's an instance of the "old" DAO that we can use to run old `retrieve()` and `retrieveRange()` calls on. We could remove it, but there are a few places where there are complex SQL calls we'd need to reconstruct (eg - pub ID exports). When the SQL was complex and related to a UI component that we will eventually refactor, I have been recommending to leave it along and use the deprecated DAO.

**Comment by asmecher** [comment]
I took another look at this to find a less kludgy solution. The main impediment was the `DataObject::setData('xyz', null)` behaviour, which has been [interpreted as an `unset`](https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/core/DataObject.inc.php#L119). This means the following...
```php
$dataObject->setData('myNullableColumn', null);
```
...removes `myNullableColumn` from `$dataObject->_data` entirely, instead of adding it to the array as a key with a `null` value. Which means that `EntityDAO` cannot distinguish between
- calling code that expects it to leave a column to the database default (desirable for almost all `INSERT calls where some columns are not specified), and
- calling code that expects it to update a column's value to `NULL`.

The real solution for this IMO is to allow `null` values to be stored in `DataObject::$_data` when using `setData`, to properly distinguish between "I didn't specify a value for this column" and "I want this column to be null". It leaves error handling up to the database, as you suggested, Nate -- when a column is given with a `null` where a `null` is not allowed, it will cause an exception, regardless of whether the schema allows `nullable` or not.

This means we have to be a little more careful about passing `null` data into `setData` -- see e.g. https://github.com/pkp/ojs/pull/3190/commits/b65d2ee5d739c25730d4b21f30bb5d6632bd3285. But I think that is a relatively small price to pay.

I also added some tests, which should demonstrate the problem when run on the codebase without the pkp-lib changes in place.

**Comment by NateWr** [comment]
I have a memory of you making this change to `DataObject::setData()` and it causing problems before. Do you remember that? Maybe this is different...

**Comment by asmecher** [comment]
@NateWr, yes, we discussed it here: https://github.com/pkp/pkp-lib/issues/5740#issuecomment-629548502

We ended up agreeing that the change would be better made "later" as part of a major release (at the time meaning 3.3.0), but 3.4.0 suits well too, I think.

**Comment by asmecher** [comment]
Merged!
