### ISSUE TITLE
Set httpOnly flag on session cookie

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#7373]
The session cookie should be sent with the httpOnly flag in order to reduce the risk of session highjacking via a client-side script injection.

Original report: https://huntr.dev/bounties/bbe8d92d-0c70-4dca-b076-350bcb4df403/

**Comment by asmecher** [comment]
Also back-ported to `stable-3_3_0`.

**Comment by fradeve** [comment]
@asmecher one of our customers has found a little issue with the fix for this issue.

The problem is that the `HTTPOnly` flag is set on the cookie only _after_ login, but not before.
Vulnerability scans are highlighting this as an issue.

I have checked this personally and can confirm the problem on `OJS 3.3.0-13`, even when `force_ssl = On`.
Is there any chance that we could set the `HTTPOnly` flag on the cookie _before login_ as well?

I will also flag this to @salmanm2003 so that we address this on the (similar) issue he is working on, #6340.
