### ISSUE TITLE
Review Report contains duplicate rows

### ISSUE THREAD

**Issue by kaitlinnewson** [pkp/pkp-lib#7377]
**Describe the bug**
When exporting the Review Report in OJS 3.3.0-6/8, many of the rows are duplicated.

**To Reproduce**
1. Download the Review Report in Statistics > Report.
2. Open the downloaded CSV file.
3. Review the file to note duplicated rows. If in Excel, the "Remove Duplicates" feature can also be used to indicate how many duplicates there are.

**What application are you using?**
 OJS version 3.3.0-6 & 3.3.0-8

**Comment by asmecher** [comment]
@kaitlinnewson, I'm afraid I can't replicate this locally; can you contact me privately with details about where you're seeing it?

**Comment by asmecher** [comment]
I've confirmed that this is https://github.com/pkp/pkp-lib/issues/7167; there is a (long) SQL query that can resolve the issue here: https://github.com/pkp/pkp-lib/pull/7414#issuecomment-961857377

Please make sure to take a good database backup before executing it!

**Comment by DigitalCardigan** [comment]
This is listed as closed, but we are having this issue of duplicated rows in reports in OJS 3.3.0.12. Is there a way to correct this? I see there is a suggested SQL fix in a related thread, however, that's an old thread specific to 3.3.0 and we are not having the slow user search issue described in that thread. 
My editors want to be able to use this report feature but it is just rows and rows of repeated data.

**Comment by jonasraoni** [comment]
@DigitalCardigan We don't run database updates on minor OJS upgrades, so if your installation is older than the fix, it's expected to have the problem.

And for the same reason, that we don't upgrade the database, it should be ok to run the query while you're under 3.3.0-X :)

About the slow user search, it should happen once you have a considerable number of users in the system.

**Comment by jonasraoni** [comment]
@DigitalCardigan The code you've linked is the one supposed to just improve the speed :)

Back to the topic, the issue happens at upgrade time, when you're moving from an older version (e.g. 3.2.x) to 3.3.0, the fix is here: https://github.com/pkp/pkp-lib/pull/7472/files, but it will just address systems which **didn't** upgrade yet.

---

If you've upgraded, then you need to run this query: https://github.com/pkp/pkp-lib/pull/7414#issuecomment-961857377

Also, this script will be executed automatically once you upgrade to OJS 3.4.0 (we're on the testing phase, so it's going to be released soon).
