### ISSUE TITLE
Error message after sign-in when not forcing site wide ssl 

### ISSUE THREAD

**Issue by wopsononock** [pkp/pkp-lib#7445]
With the following configuration:

OJS 3.3.0.6
**Config.inc.php**
`
; Force SSL connections site-wide
force_ssl = Off

; Force SSL connections for login only
force_login_ssl = On
`
I'm tunnelling to my OJS VM's localhost port 443
Logging in redirects to a plain http url like this:
http://mysite:4443/index.php/GL/login/signIn

Status 400 message about https:
Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.

**Comment by asmecher** [comment]
@wopsononock, I think this is a configuration problem rather than an OJS bug. Could you post your question on the support forum   (https://forum.pkp.sfu.ca/) instead of Github?

**Comment by ctgraham** [comment]
The problem is here:
https://github.com/pkp/pkp-lib/blob/834e3935050174a7a12b1a143ae4e32a6bf85a7f/pages/login/LoginHandler.inc.php#L143-L146

If only `force_login_ssl` is set, the user is actually forced back to a non-SSL connection, regardless of whether they came from SSL or non-SSL, prior to the login.

So, if someone has connected securely to the site, then logs in, they will be redirected to HTTP (nonsecure).
