### ISSUE TITLE
Reviewer Search: Display email address for unambiguous identification

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#7455]
**The Problem**
We have had a request that it is hard for our editors/section editors to unambiguously identify reviewers when inviting them. Currently the 'Advanced Search Reviewer Form', the grid shown when clicking "Add Reviewer", only displays full name, affiliation, and some review-related information.

The email address can be accessed fairly easily when clicking on "Activity log" but only after the invitation has already be sent. This is problematic when having hundreds of possible reviewers as in our case as the name of a person is not unique and can cause confusion.

**Analysis**
I was checking the code to see if I can find a quick solution. The information is fetched via an ajax request (grid built via jQuery) in `lib/pkp/controllers/grid/users/reviewer/form/AdvancedSearchReviewerForm.inc.php`, around line 30 `pkp.registry.init('select-reviewer-{$uuid}', 'Container', {$selectReviewerListData|@json_encode});`. `$selectReviewerListData` is the response from the REST API (`api/v1/users/reviewers`) which does not contain the email address of the reviewer. May be fine and by purpose in case this is to protect the email address of the reviewers. However ...

... when clicking on "Enroll an Existing User as Reviewer" we get a list of users with name and email (not via API?). While (1) our editors cannot see the email of those willing to be reviewers, they (2) do get the email address of our authors or readers fairly easily. If (1) has been put in place for data privacy I wonder why (2) works.

**Describe the solution you'd like**
For practical reasons it would be great to show the email address (`john.doe@example.com`) to avoid mistakes/confusion. 

**Additional information**
Same for version `3.3.0-7` and "`3.4`" (`main` branch fetched today).

**Screenshot**
Screenshot (OJS version `main` development branch). Left: "Add Reviewer" grid, right "Enrolll Existing User" dropdown menu.

![reviewer_email](https://user-images.githubusercontent.com/13628564/141519924-d3c5d57d-b649-42c3-ada3-93c8dffd5c1e.png)

**Comment by NateWr** [comment]
Hi @retostauffer, thanks for the report and for linking back to the original user request. As you noticed, the "Locate a Reviewer" and "Enroll an Existing User as Reviewer" forms operate independently. We've updated the "Locate a Reviewer" form to use the new REST API and our UI Library. We plan to update the other form, but due to GDPR concerns, we first need to implement support to [invite a user](https://github.com/pkp/pkp-lib/issues/3022) without automatically opting a user into a role they didn't sign up for.

In the meantime, here are a couple of things that might help regarding the "Locate a Reviewer" form:

1. It is possible to search by email address. Whatever you put into the search field will be matched against a user's email address.

2. Each reviewer has a dropdown panel that shows more information. I'd be open to a PR that added the email address to the `ReviewerListItem`, similar to how reviewer interests and biography are shown in the [example list item](https://docs.pkp.sfu.ca/dev/ui-library/dev/#/component/ListPanel/components/SelectReviewerListPanel).

**Comment by jonasraoni** [comment]
This will be handled by the #6675, therefore I'm closing this issue.
