### ISSUE TITLE
Cannot read review

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#749]
It's no longer possible to read a review. See the screenshot attached to a related problem:
https://github.com/pkp/pkp-lib/commit/2fbdfcc52c3b2e0aee63c4e49b51732d87dc629a#commitcomment-13275645

There's an `<a>` element with no text contents that used to have a CSS-defined icon; the new layout did away with icons attached to (some? many?) link actions, including the note ones used by the Review link action. (Implemented in `ReviewNotesLinkAction.inc.php`.)

**Comment by NateWr** [comment]
Ahh woops. Should have referenced this issue in [this PR](https://github.com/pkp/pkp-lib/pulls). This issue should now be fixed, though I've switched to text instead of icons for now. Some improvements suggested in #759.

This isn't the only place icons went missing. I think the file read/unread status indicator is also gone. Probably some more elsewhere. Please keep an eye out and let me know.

**Comment by NateWr** [comment]
I'm going to close this as it overlaps with #758.
