### ISSUE TITLE
Allow editors to decline submissions from the submissions list

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7492]
**Describe the problem you would like to solve**
Some journals, presses and preprint servers receive a large number of submissions that they must decline or remove. These may be very low quality, duplicate submissions, or spam. Managing editors must go into the submission workflow for each submission to record a decline decision. And this must be completed before the submission can be removed.

**Describe the solution you'd like**
Allow editors to decline submissions directly from the submissions list. A button could be added that takes the editor to the decline submission decision workflow. This should only appear for submissions in the submission stage and should take the editor to the Initial Decline decision.

**Who is asking for this feature?**
This has not been identified as a specific priority, but fits the broader feedback we have that managing editors want to do more from the submissions list when they manage a large number of submissions.

**Comment by Devika008** [comment]
Since "declining" a submission is a primary editorial decision, most users in our 2022 user testing felt that this action should be located on the submission workflow page rather than the dashboard. This placement emphasizes the intentional nature of the decision and reduces the risk of editors clicking the button unintentionally.

Moving the submission workflow to the side panel, streamlined the process while maintaining this intentional decision-making. This adjustment keeps primary editorial actions deliberate and accessible, without adding extra clicks to access the submission.
