### ISSUE TITLE
Merge ORCID metadata and authorization into core OJS/OMP/OPS

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7500]
**Describe the problem you would like to solve**
The ORCID plugin is widely used to manage and authenticate author records, and deposit contributor data to ORCID. The plugin works hard to integrate with the author forms and and author grid in publication details. This makes the code harder to write and harder to maintain.

**Describe the solution you'd like**
Integrate the features of the ORCID plugin into the core application. Journals should be able to enable or disable their support for ORCID. Any login or authentication features can be built into the standard registration and login forms. 

As part of this process, the ORCID features should undergo a discovery and design process to make sure that working with ORCIDs is clear for all users.

**Who is asking for this feature?**
This work is part of the integrity initiative. As we expand our integration with ORCID in order to authenticate and verify journal records, it will be easiest to do this work if the ORCID metadata and authorization is a part of the core application.

**Comment by amandastevens** [comment]
Does this include users being able to log into OJS/OPS/OMP with their ORCID ID?  We receive this request often from PKP|PS clients and potential clients. One explained as follows: "Our members say it is difficult to track passwords for all the journals they submit to and review for. Therefore, many use ORCID as a login tool. For example, [Open Science Framework](http://osf.io/), allows you to login with your ORCID rather than creating a unique login. Something similar to their setup would be great and I think improve our member's experience."

**Comment by NateWr** [comment]
@amandastevens no, this is just about authenticated ORCIDs for author records so authorship data can be deposited with ORCID. 

Logging in with ORCID is possible with the [OpenID plugin](https://github.com/leibniz-psychology/openid).

**Comment by bozana** [comment]
@ewhanson, this issue can then be closed, no?

**Comment by ewhanson** [comment]
Yes, closing as it was completed in #9771.
