### ISSUE TITLE
Consider how to handle items with no DOIs when depositing all

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7524]
**Describe the problem you would like to solve**
When I clicked Deposit All in the new DOI management page (#6062), I expected all Unregistered items to be switched to Submitted. However, one of them did not because it did not have a DOI assigned. This makes sense in hindsight, but it was confusing in the UI and at first I thought something was broken.

**Describe the solution you'd like**
I think we need a way to indicate whether a submission has a DOI assigned or not. I suggest the following reorganisation of the filters in the DOI list. This separates the filters to track two statuses: 1) the item's status and 2) the DOI's deposit status.

![doi-filters](https://user-images.githubusercontent.com/2306629/144418143-f064dbea-51b6-4a6d-95b8-c20009411a82.png)

The first set of statuses would indicate how ready a submission is to be registered:

- Unpublished = article can not be registered
- Needs DOI = article could be registered but needs a DOI
- DOI Assigned = article can be registered and may or may not be

The second set of statuses specifically track the registration status. They are the same as before, but I've changed a couple of the names of filters. Error is now Has Error and Stale is now Needs Sync. These changes only need to occur in the UI, not in the names of the statuses in the code base.

**Who is asking for this feature?**
This is part of #6062.

**Additional information**
cc @ewhanson

**Comment by ewhanson** [comment]
Hey @bozana, would you be able to take a look at these? It makes some of the filters more specific as well as groups them differently as described above. Thanks!

PRs:

- `pkp-lib`: #8622
- `ui-library`: pkp/ui-library#256
- `ojs`: pkp/ojs#3755
- `omp`: pkp/omp#1334
- `ops`: pkp/ops#469

**Comment by bozana** [comment]
Hi @ewhanson, just two comments/questions :-) Else, ready for merging...

**Comment by ewhanson** [comment]
Thanks, @bozana. Merged!

**Comment by ewhanson** [comment]
Hey @NateWr, thanks for catching the different ordering. That one slipped through! By different ordering, did you mean "Unpublished" and "Needs DOI" being flipped?

I know we'd previously talked about the need to identify which items had DOIs missing, but I don't recall if we went into detail about the filters specifically.

I agree that we can probably drop "Unpublished." I think the more important thing that was missing previously was identifying which items did not have DOIs assigned, but that's covered now. I also didn't like how "Unpublished" and "Unregistered" had a conflicting filter, so that would solve that neatly.

The text changes look good to me as well. I'll get those updated and post the PRs here.

**Comment by ewhanson** [comment]
Hey @NateWr, here are the PRs removing the "unpublished" filter and updating the working in the help text. Thanks!

PRs:

- #8688 
- pkp/ui-library#263
- pkp/ojs#3794
- pkp/omp#1351
- pkp/ops#483

**Comment by NateWr** [comment]
Looks good, I didn't do a manual test but the code changes all look clean enough. When the tests pass feel free to merge.

(This is a one line change you might want to chuck into this PR: https://github.com/pkp/pkp-lib/issues/8677).

**Comment by ewhanson** [comment]
Merged!
