### ISSUE TITLE
Crossref deposits fail when surname is missing

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#7528]
**Describe the problem you would like to solve**
There are three issues with Crossref deposits that require some reconfiguration of how we map name metadata to their schema.

1. Crossref requires a surname but this is optional in OJS.
2. The Crossref deposit plugin may write an empty `<surname>` tag to the export XML, which will lead to a validation error on Crossref's end.
3. We should add support for preferred name via the `<alt-name>` element.

**Describe the solution you'd like**
1.  we could either swap which field is required on our end, or..._when the only field filled out is "given name"_, just write that to the surname element. 
2.  remove the empty tags from the XML and deposit them manually. 
3. The following is some example XML:

```xml
                    <person_name contributor_role="author" sequence="first" language="en">
                        <given_name>Andrew</given_name>
                        <surname>Kerr</surname>
                        <alt-name>Andy Kerr</alt-name>
                    </person_name>
```

**Who is asking for this feature?**
Crossref asked specifically about the surname requirement. The other two have come up on the hosting side a number of times.

**Comment by AhemNason** [comment]
Oh, I should note too that <alt-name> is supported in the schema version we're using 4.3.6. Once Crossref has added ROR to their schema in early 2022, we should probably consider just fully updating the schema we write to in our exports to accommodate.

**Comment by NateWr** [comment]
I've flagged this as a bug and assigned it to the 3.3.0-9 milestone for the problems with the surname field. The preferred name feature should be split to a new issue and only implemented for a future version.

**Comment by NateWr** [comment]
> we could either swap which field is required on our end

Just a note that we can't/won't do this. "Surnames" are a western thing and "Family Names" (the term we use) do not exist in all languages/cultures.

**Comment by AhemNason** [comment]
Right, so in the Crossref schema, they made the decision to support single-name deposits as well. But, they just went with the other name field. 

```
<person_name contributor_role="author" sequence="first" language="en">
    <surname>Andrew</surname>
</person_name>
``` 

This is facet valid and expected in the schema. I know it seems a little weird, but I suspect it's because of the expected placement of a person's name in like... citations. Surname is usually listed first, so that's likely the logic here. In any event the recommendtions is that if we just have a single given name, we write it to Crossref's schema in the surname field.

**Comment by NateWr** [comment]
Ok that makes sense, thanks.

**Comment by NateWr** [comment]
See also https://github.com/pkp/pkp-lib/issues/6863

**Comment by mpbraendle** [comment]
The Crossref schema has an "anonymous" element (as subelement of contributors) that should be used in such a case.

**Comment by AhemNason** [comment]
Anonymous in the Crossref schema is for an anonymous author, not for situations where one of two name elements is missing.

**Comment by mpbraendle** [comment]
@AhemNason This is correct, but not the point.

We simply can't deposit (or redeposit) articles that have no author in Crossref, because the anonymous element hasn't been implemented in the OJS CrossrefXMLExport plugin - which in my opinion is wrong. If you wish that I create a new issue for this, let me know. But I think placing a comment here was correctly if one starts bug fixing for missing or semi-missing author names. 

For a large journal that we are currenly migrating over from another host to OJS, there are several (in the range of 100-400) articles that don't have an author, but were registered with Crossref and that we currently can't redeposit so that the DOI points to the OJS site. Whether it makes sense to register articles that don't have an author is not to be discussed here. The DOIs exist for these articles, and they should resolve again.

**Comment by AhemNason** [comment]
@mpbraendle That's correct, but this ticket is about one missing name, not anonymous authors. I mentioned this in another ticket but please see: #5955 filed against the issue of anonymous and corporate names.

**Comment by ifarley** [comment]
Hi @AhemNason and @NateWr. As Mike said above: "I know it seems a little weird, but I suspect it's [Crossref selecting surname as the default for contributors with a single name] because of the expected placement of a person's name in like... citations." 

That's exactly right. We're focused on that citation matching, and that's why we decided to use the <surname> element in the XML as the required field. Some of those citation styles we support and match on only require surname or family name within the citation, so our decision was based upon matching as many citations as we could for these contributors.

**Comment by ajnyga** [comment]
So I came across this in OMP where I have my won Crossref plugin.

@NateWr are you thinking of solving this by using the firstname in the `surname` field in the Crossref export xml, like this:

```
<person_name contributor_role="author" sequence="first" language="en">
    <surname>Andrew</surname>
</person_name>
```

**Comment by NateWr** [comment]
> are you thinking of solving this by using the firstname in the surname field in the Crossref export xml

Yes, but we do not have a "first name". We have a "given name" and a "family name". If only a "given name" is provided, then we will put that into the only required field in Crossref.

**Comment by asmecher** [comment]
Here is a contributed pull request for this issue: https://github.com/pkp/crossref-ojs/pull/11

**Comment by NateWr** [comment]
@ewhanson can you do the code review on this PR?

**Comment by bozana** [comment]
Currently: if family name in submission locale (the data are exported in) is missing, the author full name is exported in the element `surname`, s. https://github.com/pkp/ojs/blob/stable-3_3_0/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php#L154. 
The function `getFullName` considers the UI locale first, which I think is not correct. I would then change it so that the `getGivenName` funciton (with the submission locale) is used and that given name exported in the element `surname`.

@AhemNason, the support for alt-name was added here: https://github.com/pkp/ojs/commit/92b3e7445e1759e9074e3286981ecb220659d733. Thus, the author names in other languages are exported in `alt-name` element. We could see if this is OK so and if not open a new issue for that...

**Comment by bozana** [comment]
I've just realized this Bug in the stable version: https://github.com/pkp/pkp-lib/issues/8202.
This can lead to some wrong metadata -- it could be that a given name does not exists in the submission locale :-(
I just hope that the case when UI in which a new submission is started and the actual submission locale differ is very rare, so that we will not have much support cases...

**Comment by bozana** [comment]
PRs:
ojs stable-3_3_0: https://github.com/pkp/ojs/pull/3508

**Comment by bozana** [comment]
@NateWr, could you review the PR? It uses the given name in the submission locale, if family name does not exist. getFullName would first consider the UI locale, which is not correct -- all metadata are exported/registered in the submission locale...

**Comment by NateWr** [comment]
Looks good to me, @bozana.
