### ISSUE TITLE
HTML styling removed from announcement

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#7532]
**Describe the bug**
Hosted journal using OJS 3.3 + Text editor Extras Plugin for the announcement page has noted that the Source code styling they added for their image gets removed once it has been saved.

On the backend view it appears to be formatted properly. 
![image](https://user-images.githubusercontent.com/50342731/145109804-02100538-1286-4db0-89d6-8b35efbc6b3a.png)

**To Reproduce**
1. Add announcement
2. Add image
3. Add HTML code to wrap text
4. Front end view does not display this

![Announcement_image003](https://user-images.githubusercontent.com/50342731/145109689-eb1f636b-a93d-44c4-90cb-ee10aaace662.png)

**Comment by NateWr** [comment]
What is the HTML code that you added to wrap text around the images? And what theme are you using? Our themes won't just adapt magically to any HTML. And I'm not sure that we plan to add support for wrapped images. Wrapped images look ok in large screens but typically do not work well on small screens.

**Comment by pmangahis** [comment]
I think the client and I both used `align="left" ` on a Manuscript Theme (OJS 3.3.0.7)

**Comment by NateWr** [comment]
I think I'm going to recommend that we don't support this. I had a look at what TinyMCE supports in an official way, and it looks like there is a general content formatting option that adds a `style` attribute with alignment, but there is no support for floating images (to get the wrapped text feature). For that reason, anything we would do would have to be a custom implementation. 

Since we probably should discourage people from using wrapped text, in order to better support small screens, I'm leaning towards not implementing it. If we see a lot of use of this in the wild, then we can maybe consider supporting it as a content formatting option in the TextEditorExtras plugin. But I'd prefer not to offer it as a core feature in order to encourage people to write content that reads appropriately on small screens. (Floated text does not, for example, support captions or other usability/accessibility features.)
