### ISSUE TITLE
Supplementary material could have their own DOI

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#7570]
**Describe the problem you would like to solve**
Supplementary material are becoming more common, as a way of reducing article length and associated typesetting costs. It is difficult to link to supplementary material in the body of the article in a robust way without a specific DOI, though. 

**Describe the solution you'd like**
Fortunately, CrossRef already supports DOIs for components of an article. Furthermore, the OJS CrossRef plugin already supports DOIs for galleys. So, ideally the current support for galley-specific DOI would be generalized for component-specific DOI.

**Who is asking for this feature?**
Journal Editor.

**Additional information**
Assigning DOIs to supplemental materials associated with journal articles can be done using CrossRef's component content type:
https://www.crossref.org/documentation/content-registration/structural-metadata/components/

**Comment by NateWr** [comment]
In OJS, supplementary material is published as a galley, so it can already have its own DOI. What part of this can't be done already?

**Comment by fgnievinski** [comment]
I guess it's more of a UX issue. After enabling support for galleys' DOI in the CrossRef plugin, then even the article main text galleys will receive a DOI by default, separate from the article landing page DOI. The usual workflow in other manuscript handling systems that I'm used to is: only galleys for supplementary materials would create additional DOIs. Would it make sense to distinguish between supplementary galleys and article main text galleys? Then, the article main text galleys wouldn't be assigned a DOI separate from the article landing page DOI by default. In the usage case that I have in mind, supplementary materials would be mentioned by title and DOI within the article main text, without a formal citation and reference.

**Comment by NateWr** [comment]
> only galleys for supplementary materials would create additional DOIs. Would it make sense to distinguish between supplementary galleys and article main text galleys?

That sounds like a reasonable configuration, but it is not the way that everyone in our community uses DOIs. For better or worse, some people do want separate DOIs for every galley, even two versions of the same article, separate from the article landing page.

I recommend following the UI/UX work that is going into https://github.com/pkp/pkp-lib/issues/6062. From 3.4, DOI management will be handled at journal-level instead of on the submission workflow page. This will not, necessarily, address the primary/supplementary file distinction that you want to make. But future changes are going to be built around this approach rather than the way DOIs are set in 3.3.

**Comment by NateWr** [comment]
@fgnievinski I'm going to close this issue for now. But please feel free to continue this discussion once you've had a chance to look at DOI management in 3.4. I'm happy to file an issue with a more specific proposal that addresses this need. (It may be as simple as adding some configuration settings for what kind of files get auto-generated DOIs).
