### ISSUE TITLE
Fix the PHPDoc declarations to improve the type hinting

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7577]
**Describe the problem you would like to solve**
The code editor is unable to understand some of the type hints that we've already added to the code base due to invalid declarations.

**Describe the solution you'd like**
Fix the doctype declarations.

Given the next steps are error-prone/herculean, we'll probably be working on them on-demand:
- Ensure the type hints are accessible (e.g. the type exists and it's not missing its namespace)
- Add types wherever we can (e.g. class properties, arguments, return types, etc.).

**Who is asking for this feature?**
Developer

PRs
[pkp-lib](https://github.com/pkp/pkp-lib/pull/7584)
[OJS](https://github.com/pkp/ojs/pull/3266)
[OMP](https://github.com/pkp/omp/pull/1047)
[OPS](https://github.com/pkp/ops/pull/213)

**Comment by asmecher** [comment]
Just a note that this might also be a good time for a switch from Doxygen (see docs/dev/ojs2.doxygen) to something else, or at least a review of the Doxygen configuration.

**Comment by jonasraoni** [comment]
I was inspecting alternatives and didn't find many active/maintained options, the best were:
- https://github.com/phpDocumentor: [Demo](https://demo.phpdoc.org)
- https://phpdox.net: [Demo](https://phpdox.net/demo/phpDox/index.xhtml)

I didn't inspect them much, besides the demos, but I doubt there will be hidden gems... So, in case there's nothing against Doxygen, I think it's ok to keep it and just review the configurations/bump the version. It's possible to improve its interface as well (e.g. https://jothepro.github.io/doxygen-awesome-css/).

**Comment by jonasraoni** [comment]
I've added the PRs to the issue description.

I thought about committing directly to `/main`, but as there are many files, I decided to create a PR to run the tests.

Here I basically:
- Reversed the declarations from `@tag $param type` to `@tag type $param`
- Added missing types/param names (e.g. `@param type` / `@param $name`)
- Normalized primitive types (e.g. from `integer/boolean/String/Array/callback` to `int/bool/string/array/callable`)
- Minor fixes

**Comment by jonasraoni** [comment]
Hi @asmecher! Just wanted to confirm if I can merge this.
Then I'll proceed with another set of trivial fixes in order to decrease the review surface of the #6328.

**Comment by asmecher** [comment]
@jonasraoni, what IDE are you using? Does it pick up on the differently-formatted hints (in particular the `/** @var $varName VarType */`?
(I'm using vim, so it's not relevant to me, but I know others have depended on these in their current form -- using vscode, I think.)

Longer-term, I'd rather we relied on actual PHP type hints rather than doxygen-style self-documentation, and in cases where PHP type hints are provided, we *remove* the self-documentation rather than having to maintain and synchronize duplicate info. The self-doc would gradually dwindle to just the comments, e.g. parameter descriptions. But we can't batch migrate self-documentation type hints into PHP type hints because we have generally not been fastidious about e.g. `int` vs. `actually-a-string-but-contains-a-number` and would need to work through these one at a time.

**Comment by jonasraoni** [comment]
@asmecher I can confirm that this format doesn't work in my vscode, other popular IDEs (e.g. [PhpStorm](https://phpstorm.tips/tips/20-generate-docblocks/)) are also using the standard format.

Yeah! For the long-term that's the path we should follow to decrease surprises with broken promises. It's really not possible to batch migrate at this moment, unless we had a high code coverage in the tests. I created a side-issue to help with the "batch migration" (https://github.com/pkp/pkp-lib/issues/7591).

Soooo, as there's nothing against, I'll check if there's something else to update and merge.
