### ISSUE TITLE
Add ability to include user/context with CLI request

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7604]
**Describe the problem you would like to solve**
As the CLI tools are operating in a server context and do not originate from a request initiated by the browser/user, they do not include some pieces of data (e.g. a user object or a context) that parts of the application expect to be there. This typically happens when a user or context is retrieved from the request, e.g. `$request->getUser()->getUsername()` or `$request->getContext()->getId()` (see #7603). Reaching these parts of the application result in a fatal error, e.g. `PHP Fatal error:  Uncaught Error: Call to a member function getUsername() on null`.

**Describe the solution you'd like**
It would be useful to be able to specify these at the time of running the tool, along the lines of including these options as flags, e.g.:
```bash
php importExport.php --user=username --context=journalPath NativeImportExportPlugin import [...]
```

This option assumes the tool is operating in an environment in which it's safe to assume whoever is running the tool should be able to act as any user just by specifying a username. Another option would be to specify the user by API key.

**Who is asking for this feature?**
This has arisen from needs of the PKP hosting team, but would be applicable to journal administrators working with CLI tools.

**Comment by ewhanson** [comment]
@asmecher, what's your take on this, and what do you think of a (user-facing) approach like the one I've suggested? In terms of testing implementation strategies, I've successfully added users to the request as a temporary workaround (`Registry::set('user', $user)`) as well as by adding an API key to the request, but haven't had any success with attaching a context yet.

**Comment by asmecher** [comment]
We have a lot of clean-up to do with our long-standing practices of deep-passing objects like `$request` (and sometimes `$user`), or jamming things into pseudo-globals like `Registry` and `Application::get`, rather than better practices like dependency injection (which we're starting to make better use of).

Meanwhile the fatal errors are actually helpful in determining where we're making assumptions about data being available. In the example you point out (https://github.com/pkp/pkp-lib/issues/7603).

So for the short term I support your proposal, but for the `main` branch it might be worth disabling that behaviour when using strict mode (see `config.inc.php`).

**Comment by jonasraoni** [comment]
Hi!
Last time I used the `NativeImportExportPlugin` I had some issues, which I've shared here: https://github.com/pkp/pkp-lib/issues/7143#issuecomment-952174311

**Comment by jonasraoni** [comment]
We can start by unifying our containers (at this moment we have the Registry, Pimple, Laravel and Singletons). I was going to create an issue for it, but I saw we have this one: https://github.com/pkp/pkp-lib/issues/7131, so perhaps it can be extended.
Then it would be possible to setup a `context` object in the Laravel's container and have it injected.

**Comment by jnugent** [comment]
Just adding another use case for this, in that I had written a CLI tool for deleting a context and it was generating a fatal error because the submission file logging service dies since it was also having problems with the Request/User environment:

'username' => Application::get()->getRequest()->getUser()->getUsername(),

**Comment by asmecher** [comment]
In the interests of getting a fix into `stable-3_3_0`, I just added a check to see whether `$request->getUser()` returned anything, and if not, used `null` for `$user->getUsername`. These cases are all for logging, and we can interpret an empty username in the log entry as a CLI-based action for the time being.
