### ISSUE TITLE
Emails go to submitting author rather than principal contact for editorial correspondence

### ISSUE THREAD

**Issue by griffithepress** [pkp/pkp-lib#763]
When I designate a principle contact (PC) who is not the submitting author and then invoke an Editor->Author email (for example during review acceptance or copy editing), the submitting author always seems to be in the To: field, and the new PC is not included. This is listed as RESOLVED FIXED in 2.3 as per http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=4856 but it isn't working in our 2.4.2 installation. Should we try running the patch or is this a new issue?

**Comment by asmecher** [comment]
@griffithepress, the linked entry is something slightly different.

In OJS 2.x, there is a distinction between user records (who you log in as) and author records (who gets credit for the author). The "principal contact" designation goes against the author record, but this designation doesn't actually apply to the workflow process in OJS, because OJS depends on user records, not author records. Currently the user who submits the article receives all correspondence regarding the workflow and the "principal contact" designation is more informational/metadata than active in the workflow.

For OJS 3.0, we've changed this somewhat to permit multiple authors to interact with the workflow on their articles, not just the submitting author. This will provide a lot more flexibility in who receives contact information from the journal.
