### ISSUE TITLE
upgrade to 3.3 from 3.0.2 fails because submission_galley_settings table already exists

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7642]
**Describe the bug**
If you run an upgrade to OJS 3.3 from OJS 3.0.2, the upgrade fails with:

`ERROR: Upgrade failed: DB: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'submission_galley_settings' already exists (SQL: CREATE TABLE submission_galley_settings AS SELECT * FROM article_galley_settings WHERE setting_name <> 'excludeDoi' AND setting_name <> 'excludeURN')`

This table already exists in 3.0.2:

https://github.com/pkp/ojs/blob/ojs-stable-3_0_2/dbscripts/xml/ojs_schema.xml#L593

So I think maybe one of the conditions in the upgrade XML is wrong or else there needs to be a table check before running the CREAT TABLE command.

**To Reproduce**
1. Install 3.0.2
2. Attempt to upgrade to 3.3 using the 3.0.2 database

**What application are you using?**
OJS 3.3.0.8

**Comment by asmecher** [comment]
This already appears to be reported in the forum:
- https://forum.pkp.sfu.ca/t/ojs-upgrade-from-3-0-2-to-3-3-0-7-fails-because-a-database-table-already-exists
- https://forum.pkp.sfu.ca/t/upgrade-error-from-ojs-3-0-2-0-to-ojs-3-3-0-8
- https://forum.pkp.sfu.ca/t/upgrade-ojs-3-1-2-1-to-3-2-1-4-successfully-upgraded

**Comment by jnugent** [comment]
Hi @asmecher 

Just because I am looking at another upgrade today I investigated this a bit.  I believe that the root cause of this is that when this block in upgrade.xml runs:

```
        <upgrade minversion="3.0.0.0" maxversion="3.1.9.9">
                <data file="dbscripts/xml/upgrade/3.2.0_preupdate_versioning_articleGalleySettings.xml" condition="return $installer->tableExists('article_galley_settings');"/>
        </upgrade>
```

which in theory should not run since the modifier checks to see if the article_galley_settings table already exists, and that table shouldn't exist at the same time the submission_galley_settings table exists.  Unfortunately the submission_galley_settings table has existed since the beginning of OJS3:

https://github.com/pkp/ojs/blob/ojs-stable-3_0_0/dbscripts/xml/ojs_schema.xml#L598
https://github.com/pkp/ojs/blob/ojs-stable-3_0_0/classes/install/Upgrade.inc.php#L1327

and my memory is hazy on this part but I don't think there's any code until 3.2.0 that removes the article_galley_settings table although there is code to rename the article galleys table:

https://github.com/pkp/ojs/blob/ojs-stable-3_0_2/dbscripts/xml/upgrade/3.0.0_preupdate.xml

I think that at this point you'd have a situation where the article_galley_settings table existed along side the submission_galley_settings table.

**Comment by asmecher** [comment]
Here's a proposed solution; I'd love feedback on whether it works for someone else's upgrade: https://forum.pkp.sfu.ca/t/upgrade-ojs-3-1-2-1-to-3-2-1-4-successfully-upgraded/69850/11

**Comment by asmecher** [comment]
I ended up with a slightly different implementation than @murilodbva's very welcome suggestion -- this extends an existing table existence check to include `submission_galley_settings` as well. The reason this issue was so arcane is that we (I) [rearranged existing upgrade scripts](https://github.com/asmecher/ojs/commit/215d71c9fae814e26f42218048feeb3f593a147b) a few releases after they were first written, which we rarely do. Yet another problem that moving to migrations will rid us of!

Fix: https://github.com/pkp/ojs/commit/5b228f900460f9030f3b32efd538feca75211198
