### ISSUE TITLE
Fatal error when trying to load PKPXMLParser

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7651]
**Describe the bug**
The following error occurs when trying to reload scheduled tasks from the acron plugin.

```
PHP Fatal error:  Uncaught Error: Class 'PKPXMLParser' not found in /home/nate/Projects/pkp/ojs-main/lib/pkp/plugins/generic/acron/PKPAcronPlugin.inc.php:308
```

The class needs to use the namespace in this file and `NavigationMenuItemDAO.inc.php`.

**To Reproduce**
1. Go to Settings > Website > Plugins.
2. Find the Acron plugin and click the "Reload scheduled tasks" button.

**What application are you using?**
`main` branch (3.4 pre-release)

**Comment by touhidurabir** [comment]
@asmecher should I make pull requests for the fix the issue for `ops` and `omp` both stable and other main branches as I only did for the `pkp-lib` and `ojs` `stable-3_3_0` branch ?

**Comment by asmecher** [comment]
@touhidurabir Don't worry about it in this case, as the fix was pretty close to trivial and the only application-related changes were the submodule updates. For more complicated fixes, it's helpful to send in submodule update PRs for all applications, if only for the sake of Travis testing -- but if the submodule on the `main` branch gets a little stale, it's not a problem. We make sure everything is up to date around release time.

**Comment by jonasraoni** [comment]
@asmecher I guess this one can be closed, right? Just saw it while searching for another issue 😁

**Comment by asmecher** [comment]
Correct, @jonasraoni -- thanks!
