### ISSUE TITLE
In OPS, allow the option to disable the configuration options when you add a galley

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#7652]
**Describe the problem you would like to solve**
In OJS/OPS/OMP when you upload a new galley file there are options to check off "This galley will be available at a separate website" and to add a URL path. These options make sense to include in OJS and OMP when it is editors and journal managers who are uploading galleys and understand the options. However, it is risky to include them in OPS when authors are uploading galleys and will likely not understand the options. They may erroneously check off a box or add a path that could create problems.

**Describe the solution you'd like**
I don't know if it would be best to remove these altogether from OPS or to make it optional for the Preprint Server Manager to be able to disable or hide them. Or there may be another way to make these not available to the author. Perhaps even make it clear on the interface that these options are usually not checked off or filled in.

**Who is asking for this feature?**
OPS users have requested this feature. It was initially mentioned in [this issue](https://github.com/pkp/pkp-lib/issues/5622).

**Comment by NateWr** [comment]
I'm not totally convinced about this. As soon as we remove it someone will ask for it to be supported, and since OPS sites tend to be large aggregators, it's far more likely they will want to support remote galleys as they grow and serve more scholars doing a wider variety of things. Galleys like source data often need to be hosted elsewhere (like a data repository) due to their size.

What about suggesting a new text label that helps clarify the checkbox? Something like:

> This galley will be available at a separate website. Instead of uploading a file, you will be asked to provide a link where the galley can be accessed.

**Comment by devinberg** [comment]
In thinking a little more about this, I had the realization that the limitation I described really only applies to the preprint text document (primary document) and allowing remote files for supplementary materials would be desirable, as @NateWr pointed out. Perhaps make the option configurable based on galley type. For me personally, I would want remote files disabled for the "Preprint text", but enabled for other galley types.

**Comment by NateWr** [comment]
On the subject of DOIs, I think the changes we're bringing in #6062 will give a little more control over what DOIs you mint. There's also https://github.com/pkp/pkp-lib/issues/7666 with a request to configure what kinds of files are automatically assigned DOIs.

> For me personally, I would want remote files disabled for the "Preprint text", but enabled for other galley types.

This is a tricky one for us, because the types you describe apply to files, not galleys. A remote galley is created without ever uploading a file, so no type like "Preprint Text" is ever defined. In other words, the galley "type" is inherited from the file, and since remote galleys don't have files we can't define their type. 

In practice, we treat remote galleys as primary files. This is because remote galleys were introduced to support work published in new mediums -- videos, multimedia, podcasts, etc -- that were typically the primary output of the published work.

The relationship between submission files, galleys and publication formats (OMP) is pretty complicated, because each of our applications (OPS, OJS, OMP) treats these objects differently. In the long-run, we hope to address this by refactoring this relationship (see #6702). But in the meantime it's unlikely that we'll find a good way to address your use case.

I'm going to close this, because I don't think we'll take any action right now. But feel free to continue the discussion here. 

In the meantime, for 3.3.0-x, a simple plugin could be used to block remote URLs for galleys across the application. That might prevent your authors from causing data problems with DOIs until you can find a better way to support remote files.

**Comment by devinberg** [comment]
Ok.

I did have one of the PKP devs show me that it was possible to disable remote files across all galleys as you suggested. However, I do think there is value in authors being able to link to data and other supplementary files from their preprint pages.

I think for now then my solution will have to be to reject any submissions that do not include an uploaded primary file.

**Comment by NateWr** [comment]
@devinberg if you're able to write little plugins, another option you can do is add a [pre-publication check](https://forum.pkp.sfu.ca/t/what-pre-publication-checks-would-you-like-to-see/59163) (from 3.3.0-x on). The pre-publication check could make sure that there is at least one galley with a file that is a primary file type ("genre") in our terms.

If that sounds interesting I can throw some sample code together to get you started.

**Comment by devinberg** [comment]
@NateWr well, I'm not really much of a developer, but perhaps I will be able to find someone who would know what they were doing.

**Comment by diegoabadan** [comment]
The [SciELO Screening Plugin](https://github.com/lepidus/scieloScreening
) is more complex than you might want, but it can serve as an example for the developer.

**Comment by ewhanson** [comment]
That looks great @diegoabadan, thanks for sharing!
