### ISSUE TITLE
Primary author error when posting preprint

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7680]
**Describe the bug**
When publishing/posting a preprint, a fatal error may occur if the preprint does not have a primary author.

**To Reproduce**
1. Add a preprint
2. Add at least one author and make sure no author is set as the primary author.
3. Post/publish the preprint

**What application are you using?**
OPS 3.4 pre-release (`main`). This does not effect 3.3.x.

**Additional information**
This occurs because of this line: https://github.com/pkp/ops/blob/main/classes/publication/Repository.inc.php#L197

```
'authorPrimary' => $submission->getPrimaryAuthor()->getFullName(),
```

**Comment by NateWr** [comment]
@asmecher this is a PR which catches this fatal error. But should it be possible to have contributors with no primary author specified? Or should we change this so that the first author added to a publication is automatically made the primary author?

PR:
https://github.com/pkp/ops/pull/231

**Comment by asmecher** [comment]
I think there should always be a primary author -- but this change adds resiliency against fatal errors without any real downside, so please proceed. I would prefer this to just picking the 1st author because it's a lot easier to notice/fix missing data when it's not masked, both for users and for us should it become a problem down the line.

**Comment by NateWr** [comment]
Ok, makes sense. Merged this fix in.
