### ISSUE TITLE
Categories are re-sorted upon editing 

### ISSUE THREAD

**Issue by rcgillis** [pkp/pkp-lib#7697]
**Describe the bug**
When attempting to re-order categories, when you go to edit a category, it then resets the order of the categories. 

Reported here: https://forum.pkp.sfu.ca/t/error-in-ordering-categories/71916

**To Reproduce**
1. Go to Journal - Categories
2. Create categories, or if they already exist, click on order and re-order them.
3. Edit one of the categories.
4. Categories then automatically re-order despite having set an order previously.

**What application are you using?**
3.3.0-8

**Additional information**

**Comment by NateWr** [comment]
I was unable to reproduce this on `stable-3_3_0` or the test drive install. Can you provide more detailed reproduction steps, including the exact category names you create, the order you set, what information you edit on the category, and the wrong order that results?

**Comment by suburban-journal** [comment]
I can confirm this error with OJS version 3.3.0.10. We have created two Parent Categories with numerous subcategories. When I create a new subcategory or edit it, the order of all subcategories changes. Not only those that belong to the Parent Category, but all subcategories. 

The order of the Parent Categories has not changed in our case. Of course, since we only created two, this could be a coincidence.

**Alphabetical sorting (created manually), before editing a subcategory:**
![categories_beforeediting](https://user-images.githubusercontent.com/62378218/161697687-6cb5d31e-a184-45d3-bd18-720e81482b47.jpg)

**After editing one subcategory, the subcategories are no longer sorted:**
![categories_afterediting](https://user-images.githubusercontent.com/62378218/161697704-132cc996-68e5-4137-aa79-244724dbfa55.jpg)
