### ISSUE TITLE
Files not selected for promotion by default

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7705]
**Describe the bug**
When recording an editorial decision to move a submission from one stage to another, the editor is asked if they want to promote files from one stage to another. In 3.2.1, these files are selected by default. In 3.3, they are not. They should be pre-selected so that the editor does not have to select them manually.

**To Reproduce**
1. Go to a submission in the Submission stage
2. Make sure at least one file is uploaded to the Submission Files area.
2. Click on Send to Review
3. Click Next: Select Files
4. The files are not pre-selected but they should be.

**What application are you using?**
OJS/OMP/OPS 3.3.0-8

**Additional information**
The following decisions should show pre-selected files:

| Decision | Pre-selected files |
| --- | --- |
| Send to Review | Submission Files |
| Accept and Skip Review | Submission Files |
| Accept | Revisions |
| Send to Production | Copyedited Files |

**Comment by asmecher** [comment]
@jnugent, this issue is currently scheduled for 3.3.0-11.

**Comment by Tyl13** [comment]
The Submissions seem to be not selected because of this line `$row->addFlag('selected', (bool) $grid->isDataElementSelected($row->getData()))`. 

The `$grid` is the class `SelectableFileListGridHandler` and the function `isDataElementSelected` in that class calls `getViewable` on the class `SubmissionFile` which is deprecated. 

The `setViewable` is also deprecated, so the class is never getting `viewable` to be set to true. 

It returns null all the way back to the `(bool) $grid->isDataElementSelected($row->getData())` and the null is converted to a false. 

What seems to be the simplest and quickest fix is to `return true;` in the `isDataElementSelected` function in `SelectableFileListGridHandler`. This causes the submissions to be selected here, but I don't know if it causes issues anywhere else.

**Comment by asmecher** [comment]
Also reported on the forum here: https://forum.pkp.sfu.ca/t/files-for-review-checked-by-default/74256

**Comment by asmecher** [comment]
I can confirm that @Tyl13's proposal has the desired effect; thanks, Tyler, I'll commit this for release in 3.3.0-12!
