### ISSUE TITLE
Allow for plugins to describe support for fuzzy or wildcarded versions

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#7793]
**Describe the problem you would like to solve**
In the Plugin Gallery, plugin developers are currently required to explicitly name every application version which the plugin version supports.  This means that new assertions must be added even after patch releases.  The version contract should, however, allow us to forecast version support, promising (for example) for a plugin to work in 3.3.0-_anything_, or even 3.3._anything_-_anything_.

**Describe the solution you'd like**
Allow for plugin version support to be specified in plugins.xml as wildcards, or as partial versions.  See also: https://github.com/pkp/pkp-lib/issues/7531 for parallel discussion.

**Who is asking for this feature?**
Plugin developers

**Additional information**
The limiter seems to be here: https://github.com/pkp/pkp-lib/blob/087819073c4d323dc4d7c4d06eba8a793c4d3ad0/classes/plugins/PluginGalleryDAO.inc.php#L308-L342

**Comment by Tyl13** [comment]
While I have been doing work on this, I was wondering. Should the user be explicit about the version that he is wild carding? For example, I consider `3.3.*-*` as explicit but that is technically the same as `3.3.*`  when we stop looking at the wild cards and only comparing the version specified. 

If the second version is allowed, then should I ignore any characters after the wild. For example, if a person placed `3.3*-10`. It doesn't make sense for that to be like that but it could have been a mistake and they forgot to specify the build version. In which case, we wouldn't want it to succeed because it could be not functional for the version it is being used on.

**Comment by ctgraham** [comment]
> There could be an issue where it works on 3.3 until 3.3.0-10. Then the plugin has to be changed to be explicit for all versions of 3.3.0 except for 3.3.0-10.

Yes, but according to semantic versioning, `-10` should not introduce a backwards incompatible change.  If the plugin introduces an incompatible change, it is up to the author to either redeclare the compatibility, or test for and address the version incompatibility in the plugin code.

Also, note that in the Plugin Gallery any more recent release overrides former releases.  So, if I promise compatibility with "3.3" in my plugin's "1.2", but "3.3.8" introduces backwards incompatible changes, I can release "1.3" and declare compatibility with "3.3" again.

**Comment by asmecher** [comment]
Hi all -- I'm bungee-jumping in without reading the whole thread, just to say that if it's possible to adopt patterns or even libraries/tools to make the version specifications compatible with e.g. what Composer uses, I'd recommend it.

**Comment by Tyl13** [comment]
Basic truncation works for version control, so 3.3 will match any 3.3 version. Wild cards are no longer in the code.

It seems like it may be possible to use composer's version control with https://github.com/composer/semver. Originally, Clinton and I were worried that the control structure that uses this is baked into composer. However, it may be possible that https://github.com/composer/semver/blob/main/src/VersionParser.php this is the control structure to get the right version.

**Comment by Tyl13** [comment]
Truncation is removed from this version but it does use Composer's version constrol system. If Semver returns false then I use version_compare to tell me the reason it was false, since the original version of compare returns 0 when equal, < 0 if this version is lower and > 0 if this version is higher. Semver only returns a bool on if the version passed the constraint or not. This requires the composer.json and composer.lock to include composer/semvar. I can upload my version of those two files, but I believe I required a little extra fiddling to get semvar installed.

**Comment by ctgraham** [comment]
I haven't looked at the specific code here, but aren't the questions of "is there an updated version?" and "is this version compatible?" independent facets?  

That is, every release plugin version will have a specific version number.  This version number needs to be comparable, so we can tell if a later version is available.

On the other hand, we want support assertions to be flexible.  If I don't want to support specific application versions in my plugin, and if we support composer formulations, my assertion could be "<3.2.1.-4 || >3.4 < 3.5".  This evaluation does not need to be comparable, only true or false.

**Comment by Tyl13** [comment]
Currently the code seems to do the same thing for both of those questions.
 It checks if this version is compatible in the PluginGalleryDAO, in the _handleCompatibility(), where it compares the application version to the each of the plugin versions. 
The getCurrentVersion() in GalleryPlugin compares the installed version to the most compatible version. 
As an aside, I don't believe these two should have the same value:
`define('PLUGIN_GALLERY_STATE_AVAILABLE', 0);
define('PLUGIN_GALLERY_STATE_INCOMPATIBLE', 0);`

I can separate out the compatibility, and leave the original compare to be used just for checking if there is an updated version or not.

**Comment by ctgraham** [comment]
PRs:

- stable: https://github.com/pkp/pkp-lib/pull/7809
- main: https://github.com/pkp/pkp-lib/pull/7876

Tests:
- https://github.com/pkp/ojs/pull/3377
- https://github.com/pkp/omp/pull/1107
- https://github.com/pkp/ops/pull/272

@asmecher, can we get merges and submodule bumps for these?

**Comment by asmecher** [comment]
Done, thanks!
