### ISSUE TITLE
Ensure ability to overwrite reviewer files by Editor

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#788]
Ensure there is the ability to overwrite files uploaded by peer reviewers.
Must be able to send redacted files to authors so integrity of “blind” or “double blind” review is maintained.
(Priority for SI)

**Comment by asmecher** [comment]
@bozana, could you take a look at this? Off the top of my head, what would be required is a way for the editor to edit and anonymize uploaded files, then upload a new revision of them.

**Comment by bozana** [comment]
@asmecher, I think that there are these two requirements, above all:
a) to be able to upload the original reviewer's file as editor -- in case when reviewer are not able to use the system, when the review takes place via e-mails and in order for these files to be in the system.
b) to be able to upload the anonymized reviewer's files

This issue mentions only the requirement b). Thus, maybe we don't have to implement both requirements now, but maybe to consider them both when thinking about a solution for this issue?

We could realize the requirement b) in two or three ways:
1. To extend the editor review attachment grid -- in the "Read Review" modal -- with the file upload possibility. But I think that this doesn't solve the requirement a) because it assumes that there is a review file in the system i.e. the "Read Review" function is only there if review is done in the system.
2. To add a new file grid 'Reviewed files' on the review pages, between the 'Reviewers' and 'Revisions' part/grid, that would function similarly to 'Review Files' and 'Revisions' part.
3. To somehow change the 'Reviewers' grid, so that editor can upload a file, but I don't know why would this be better than solution #2 above.

What would you suggest?

Thanks a lot!

**Comment by asmecher** [comment]
How about making the "read review" link more general -- i.e. just call it "Review"? And making it always present, not just when the review has been completed.

Then, when open, it could present general information on the review's status; if the review is completed, then it'll behave as it currently does, showing the review. If not, it can (eventually) satisfy requirement a) as well, by allowing the editor to enter the review.

I like the idea of presenting the review files grid, with the normal set of tools to add/revise. I'd suggest that the Editor's anonymized file be added as a new revision, and ensuring that Authors can only view the most recent revision.

Does that make sense?

**Comment by bozana** [comment]
Thus, we can assume that there will always be a reviewer in the system and added in the 'Reviewers' grid, also if the review is done via e-mail?
Concerning the last part/sentence: By making a decision, the editor has the possibility to select the review attachments for the author to see. Thus, maybe we can provide just a normal file upload for the editor and let him/her decide if it is a revision? -- Later the editor would then choose the file to be attached for the author.

**Comment by asmecher** [comment]
I mean that the "Review" link would appear as a row action for each reviewer in the reviewers grid. The Editor would be able to enter the review on the reviewer's behalf if it hasn't already been done.

Yes, I think your proposal for file uploads makes sense.

**Comment by bozana** [comment]
I solved it this way:

I leaved the link "Read New Review/Read Review" in the first row as it is -- because there could be also other actions like SendReminderLinkAction and it is useful to have it on the first glance. Additionally there is not the "Review" row action in the second row.
Example of a completed review by the reviewer and a not yet completed/started review:
![readnewreview_review](https://cloud.githubusercontent.com/assets/378421/12222521/1e2e4984-b7bf-11e5-907d-196a5f6094b4.png)

Example of completed and read reviews:
![reviewcomplete_thankreviewer](https://cloud.githubusercontent.com/assets/378421/12222524/27e989b6-b7bf-11e5-82ab-dee22e8945a0.png)


Example of the "Review" modal for a not completed review; as review status only the last date will be displayed (completed, confirmed, reminded, notified, assigned):
![uploadinsteadofreviewer](https://cloud.githubusercontent.com/assets/378421/12222527/345e85d4-b7bf-11e5-8e51-7e657f22c3e7.png)

Example of the same modal for a completed review by the reviewer -- e.g. to upload an anonymized review file:
![anonymizedreviewfileupload](https://cloud.githubusercontent.com/assets/378421/12222529/3e3171e8-b7bf-11e5-90f5-eda6e7d8d8d8.png)


The reviewer will also see the files uploaded by the editor.

I didn't add the option to revise a file, because it is already meant to be so, to make it easier for reviewers, s. https://github.com/pkp/pkp-lib/blob/master/controllers/wizard/fileUpload/form/PKPSubmissionFilesUploadBaseForm.inc.php#L142-L146.

When making a decision, the editor will see all the files i.e. also those (anonymized) uploaded by him/her.

If OK so, I would make a pull request :-)

**Comment by bozana** [comment]
One more thing: when an editor uploads a review file instead of the reviewer and presses "Confirm" button, the review assignment would be marked as completed i.e. dateCompleted is set. @asmecher, do you think this could be a problem on another place in the system, because dateConfirmed is missing?

**Comment by asmecher** [comment]
I'd suggest forcing the dateConfirmed to the date of upload, but also ensuring that the event log is clear about the Editor having uploaded the review.

**Comment by asmecher** [comment]
Walk us through this during next week's UI/UX call; @NateWr will probably have some quick thoughts on formatting the grid actions!

**Comment by bozana** [comment]
@asmecher, OK, thanks a lot! :-)

**Comment by NateWr** [comment]
@bozana If you want to catch me during sane European hours to walk through this just let me know.

**Comment by NateWr** [comment]
This is just a note to myself with a list of tasks to complete after Bozana's pull request is in:

- [ ] Style the notified/completed date that appears when viewing a review modal.
- [ ] Make the unassign reviewer the offset color
- [ ] Try out the usage of icons for new/completed reviews and sending emails to overdue reviews.

**Comment by bozana** [comment]
Shall all this be considered also in OJS master?

**Comment by asmecher** [comment]
Yes, OJS master should get the same functionality.

**Comment by bozana** [comment]
Hmmm... The test StaticPagesFunctionalTest::testStaticPages failed but I didn't change that :-O

**Comment by asmecher** [comment]
That one seems to be prone to race conditions. Don't worry about it. If it stays broken for more than a short time I'll look into it.

**Comment by asmecher** [comment]
(When you're ready for review/merge, post the PR URLs here, please! I wish github did this automatically, but...)

**Comment by bozana** [comment]
@asmecher, ready to merge...
S. https://github.com/pkp/pkp-lib/pull/1065
and 
https://github.com/pkp/omp/pull/197

**Comment by bozana** [comment]
S. PR https://github.com/pkp/pkp-lib/pull/1065 and
https://github.com/pkp/omp/pull/197

**Comment by asmecher** [comment]
Excellent -- merged for OJS master, OMP master, and pkp-lib. Thanks, @bozana.
