### ISSUE TITLE
Double-check file uploads in IE

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#789]
We have reports that plupload isn't working as integrated in OMP 1.1.1 in IE browsers.

**Comment by NateWr** [comment]
I was finally able to test this today but I wasn't able to reproduce the problem. I tested on a brand new installation of OMP 1.1.1-1 as well as OMP master, using a VM for Win7/IE10 and Win7/IE11. In all cases the `plupload` component loaded and I was able to upload files.

**Comment by asmecher** [comment]
@NateWr, can you check on the SI install? I'll send you credentials in a sec.

**Comment by NateWr** [comment]
I was able to reproduce this on the demo SI install using Win7/IE9. As far as I can tell, IE9 relies on the Flash component. So a few things to check:

1. Is the URL to the flash fallback correct in `uploadOptions` in the `UploadHandler.js`? And is the `.swf` file actually there?

2. Is `flash` one of the defined runtimes in `UploaderHandler.DEFAULT_PROPERTIES_`?

The plupload widget at http://plupload.com/examples/ui works in my Win7/IE9 VM, so the fallback should be working. And I tested elsewhere to see if Flash was loading in my VM and it is.

I will try again to see if I can reproduce the issue in my test install of OMP 1.1.1. My previous comment doesn't mention testing IE9, though I'm sure I must have. Maybe I didn't for some reason...

**Comment by NateWr** [comment]
Ok, after some testing I was able to reproduce with my local OMP 1.1.1 install and tracked down the problem to a missing `html4` runtime on [this line](https://github.com/pkp/pkp-lib/blob/a7879d98142e52c23af21a74201f160f48727d48/js/controllers/UploaderHandler.js#L128).

It looks like `html4` was removed in [this commit](https://github.com/pkp/pkp-lib/commit/e8ed551b2ead30726bee931dad2d0e132282d3ab#diff-8ee679708c98ab61fead741904c082ef) in order to fix a broken file uploader in IE8.

I went ahead and tested adding the `html4` runtime back in for IE8 and IE9 and it fixed the problem for me in both browsers. But it might be worth running it past @beghelli in case he remembers why it was removed initially.

**Comment by asmecher** [comment]
Merged and cherry-picked to `omp-dev-1_1` and `omp-stable-1_1_1`. Thanks, Nate!

**Comment by jalperin** [comment]
how is supporting IE still a thing in the world?

**Comment by NateWr** [comment]
@jalperin To be honest, not much longer. IE8 is nearing extinction and IE9 is almost out the door. Many people have dropped support already, but I suspect we'll need to hang on a bit longer since our user base is trapped in legacy IT departments. That said, IE 10/11/Edge are pretty good and Microsoft has finally gone to an automated update system. Safari is now the problem-kid in the browser family.
