### ISSUE TITLE
Submission wizard form allows entry in languages not supported by submissions

### ISSUE THREAD

**Issue by twakeford** [pkp/pkp-lib#7893]
**Describe the bug**
When a journal has multiple languages installed but only a single language enabled for submissions, the submitting author is presented with metadata fields in each language when inputting the contributor information. If the journal is not allowing submissions in multiple languages then the contributor forms should only be available in the submission language.

**To Reproduce**
1. Install multiple languages for a journal
2. Within Website > Setup > Languages enable only 1 language in the Submissions column
3. Start a new submission
4. In step '3. Enter Metadata' click on the 'Add Contributor' button
5. The data fields offer the submitting author entries into all languages that are installed

**What application are you using?**
 OJS 3.3.0-10

**Additional information**
We've updated to 3.3.0-10 and this update from https://github.com/pkp/pkp-lib/issues/7605 looks good, but I've discovered that whilst the '3. Enter Metadata' form is now fixed, the contributor forms are still asking for data in multiple languages even when the language for submissions has been disabled.

![Screenshot 2022-04-27 at 17 10 15](https://user-images.githubusercontent.com/15159847/165563503-a17b9826-04e7-41c5-8e2c-92cdfeba1f36.png)

Name
![Screenshot 2022-04-27 at 17 02 31](https://user-images.githubusercontent.com/15159847/165563003-d766ce63-2cbf-4d51-9094-7cb90667df4a.png)

Preferred name
![Screenshot 2022-04-27 at 17 02 40](https://user-images.githubusercontent.com/15159847/165563048-920fa4ce-d569-4449-81e0-54d6e617e91f.png)

Bio
![Screenshot 2022-04-27 at 17 04 46](https://user-images.githubusercontent.com/15159847/165563086-e1432112-d898-4b74-b17a-22993dd49077.png)

My guess is that the same fix needs to be applied to the contributor part of the submission form.

**Comment by twakeford** [comment]
Sure!

**Describe the bug**
When a journal has multiple languages installed but only a single language enabled for submissions, the submitting author is presented with metadata fields in each language when inputting the contributor information. If the journal is not allowing submissions in multiple languages then the contributor forms should only be available in the submission language.

**To Reproduce**
Steps to reproduce the behavior:
1. Install multiple languages for a journal
2. Within Website > Setup > Languages enable only 1 language in the Submissions column
3. Start a new submission
4. In step '3. Enter Metadata' click on the 'Add Contributor' button
5. The data fields offer the submitting author entries into all languages that are installed


**What application are you using?**
 OJS 3.3.0-10

**Additional information**
Screenshots in the original report above

**Comment by NateWr** [comment]
This only needs to be addressed in `stable-3_3_0` because it will be fixed in 3.4 as part of https://github.com/pkp/pkp-lib/issues/7191.

**Comment by defstat** [comment]
There are the following cases:

**Case 1: Only one language set for Forms and Submissions**
By using the following setting (only one Language set for Forms and Submissions) both Submission metadata fields (like title, description etc) and 
Contributor metadata fields (like Given Name, Family Name etc) are not localizable.
![Image Pasted at 2022-6-30 13-57](https://user-images.githubusercontent.com/560456/176667064-727341cd-c510-4b70-b71e-0102a4848b98.png)
![Image Pasted at 2022-6-30 14-00](https://user-images.githubusercontent.com/560456/176667077-7b9a889b-9235-4577-a11b-88573f7123ca.png)

**Case 2: More than one language set for Forms**
By using the following setting (More than one Language set for Forms) Submission metadata fields (like title, description etc) are not localizable but
Contributor metadata fields (like Given Name, Family Name etc) are localizable.
![Image Pasted at 2022-6-30 14-01](https://user-images.githubusercontent.com/560456/176667595-c8c0d497-cb94-4c6b-8ebc-206d264a303d.png)
![Image Pasted at 2022-6-30 14-03](https://user-images.githubusercontent.com/560456/176667596-d4c70ff2-74e8-44b8-b53c-2e6a9964744c.png)
![Image Pasted at 2022-6-30 14-032](https://user-images.githubusercontent.com/560456/176667604-194c514b-08b9-423e-8fd8-d7170266ab41.png)

This seems to be happening because Submission Metadata Form declares it's `supportedLocales` parameter with the code found in https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/submission/form/SubmissionSubmitForm.inc.php#L44, whether the Contributor's metadata form does not declare a specific `supportedLocales`, leaving the default `Form`  `supportedLocales` taken from here https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/form/Form.inc.php#L90
