### ISSUE TITLE
blank mail sent by system

### ISSUE THREAD

**Issue by groetz** [pkp/pkp-lib#7991]
I am new here.
OJS Current version: 3.2.1.4 en
Old: Open Journal Systems 2.4.8.1 en
Problem: When an author has submitted a paper, a mail is sent to the author with only the headers and my signature, but no content. After that another mail follows to the author with the submission confirmation and the text from the template. There is no empty template in the email template directory.
How can I prevent the empty mail?

![Leere_Mail_System](https://user-images.githubusercontent.com/106870728/171998882-04deb720-8c3e-4339-9619-4816b426c1d9.png)

many greetings
Helmuth

**Comment by jonasraoni** [comment]
Hi @groetz,

Thanks for the report. I would encourage you to post your problem in our [[support forum](https://forum.pkp.sfu.ca/c/questions/5)](https://forum.pkp.sfu.ca/c/questions/5), you will find more help there than we are able to provide here.

In order to submit an issue here, you should be able to come up with a step-by-step reproduction scenario, also we're not giving maintenance to the version 2.x (see more here: https://github.com/pkp/ojs/blob/main/SECURITY.md). So I'll close this issue for now.

Perhaps this link will be helpful: https://github.com/pkp/ojs/blob/main/docs/UPGRADE-UNSUPPORTED.md

Best,
Jonas
