### ISSUE TITLE
User locales property may be false when array is expected

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8023]
**Describe the bug**
The user has a property, `locales`, specifying their working languages. They can set this in their profile. The JSON spec for a user describes this field as an `array`, but it may return `false`.

**To Reproduce**
1. Find a user with a `null` value in the `locales` column of the `user` table.
2. Inspect this user with `print_r($user)`.
4. See that the `locales` property is `false` instead of an empty array or `null`.

**What application are you using?**
 `main` branch (3.4 pre-release)

**Additional information**
This will cause fatal errors when doing something like `in_array($locale, $user->getData('locales'))`. Also, because the schema says an array will be returned, the REST API documentation is probably wrong.

Ideally, the `DataObject` should only return an array when calling `$user->getData('locales')`. An empty array should be returned if no locales are set.

**Comment by asmecher** [comment]
@touhidurabir, could you take a look at this one?

**Comment by touhidurabir** [comment]
based on my digging, the cause of this issue lies in the following part

```php
case 'array':
    $decodedValue = json_decode($value, true);
    // FIXME: pkp/pkp-lib#6250 Remove after 3.3.x upgrade code is removed (see also pkp/pkp-lib#5772)
    if (!is_null($decodedValue)) {
        return $decodedValue;
    } else {
        return unserialize($value);
    }
    // no break
```

in the file https://github.com/pkp/pkp-lib/blob/main/classes/db/DAO.inc.php from the method `convertFromDB` . And the fix can be a simple as make sure when `unserialize`, check if that's an array or not and based on that return such as 

```php
$unserializeValue = unserialize($value);
return is_array($unserializeValue) ? $unserializeValue : [];
```

How ever this will not solve the core issue which actually originated form https://github.com/pkp/pkp-lib/blob/0fbea2d886892d79f2b8427d85669145cc1ac8e6/classes/core/EntityDAO.inc.php#L110 where it's implemented as 

```php
$object->setData(
    $propName,
    $this->convertFromDB($row->{$column}, $schema->properties->{$propName}->type, true)
);
```

Here we are always passing `true` as `NULLABLE` as the third param, the following line is always get true in the `classes/db/DAO.inc.php`. when the value of column is `null` which cause the return value not to respect the `JSON SCHEMA` . 

```php
if ($nullable && $value === null) {
    return null;
}
```

My proposal is what if we rather then passing `true` always in the following line 

```php
$this->convertFromDB($row->{$column}, $schema->properties->{$propName}->type, true)
```

we determined based on the `validation` keys defined in the json schema . it will be something like 

```php
$nullable = in_array(
    'nullable', 
    array_map(
        fn($value) => trim(strtolower($value)),
        Arr::wrap($schema->properties->{$propName}?->validation ?? [])
    )
);
$object->setData(
    $propName,
    $this->convertFromDB($row->{$column}, $schema->properties->{$propName}->type, $nullable)
);
```

based on the following rules 
1. if there is no `validation` defined any a element , we pass `NULLABLE` as `false`
2. if there is `validation` defined , we check if has any nullable in it's list . If so we pass `true` otherwise pass `false` .

that way we can have a return value that respect the JSON SCHEMA . 

while above implementation is a fix for the cases where the return value does not respect the JSON SCHEMA , we can also modify the user onboarding process where we set the `locales` value default to `EMPTY ARRAY` if none passed . I will make an issue for the and create a PR for that issue . 

@asmecher @NateWr feedback please on the proposed changes as I know this will have a lot of impact in many cases of which I am not aware of .

**Comment by jonasraoni** [comment]
This DAO class [might be used in other places](https://github.com/ulsdevteam/pkp-betterPassword/blob/193ee8c08e7a12ce5b4940e8d4125f3db08c15a9/classes/BadpwFailedLoginsDAO.inc.php#L12), so any change has the potencial of breaking one thing or another, but in my opinion that's the right thing to do, so I don't have anything against, especially if a fix is going to be applied just in `main`.

**Comment by asmecher** [comment]
> ...not trying to pass the buck...

Not a problem, I did touch this last :upside_down_face: 

> I think a first step is to uncover exactly where that was causing that bug...

The need for the fix in #7325 can be seen anywhere that a schema contains a combination of...
```json
  "type": "integer",
  "validation": [
    "nullable"
  ]
```
Without the fix, `convertToDb` would force an incoming `null` value to `(int) null` (therefore `0`). The fix prevents the cast, allowing the database to store both `0` and `null` as distinct values in the DB.

An important example is in the `announcements` table -- where `type_id` can be `null` when there is no announcement type, but `0` would be invalid because of the foreign key constraint. (Similarly: `categories.parent_id`.)

> We're very low in the system here, so I think we should try to be as robust as possible.

I agree, if the `nullable` flag is not set and `null` data is passed in, we should get a fatal error.

@NateWr, your note above:
> Looking at [DAO::convertFromDB()](https://github.com/pkp/pkp-lib/blob/1f64bda06d6b0ec675b02a2285b867b5413d9ffe/classes/db/DAO.inc.php#L311-L344) and [DAO::convertToDB()](https://github.com/pkp/pkp-lib/blob/1f64bda06d6b0ec675b02a2285b867b5413d9ffe/classes/db/DAO.inc.php#L384-L427), I can see a couple of problems:

I think you missed the checks at the top of both functions that solve the issues you pointed out:
```php
if ($nullable && $value === null) {
    return null;
}
```
These ensure that `null` data passed in, when `$nullable = true`, result in a `null` output as well.

> This is maybe an area where unit tests would really help us. It's not my area of expertise, but I imagine we could throw some bad data at the DAOs and make sure we like what comes back.

There is a unit test that covers this, fortunately (one of the few I've ever written)! See: https://github.com/pkp/pkp-lib/blob/main/tests/classes/core/EntityDAOTest.php

@touhidurabir, your approach makes sense to me. Could you open this as a pull request? I would recommend removing the `trim` / `strtolower` / `array_map` stuff -- we should expect the schema files to be written strictly, and I don't think we're making accommodations for whitespace or mixed case elsewhere.

**Comment by asmecher** [comment]
Actually, on second thought: you could also consider the `null` in the database to be the problem. If a field is not nullable according to the schema, the DB field should also be `not null`!

**Comment by NateWr** [comment]
> These ensure that `null` data passed in, when `$nullable = true`, result in a `null` output as well.

Yes, but the proposal here changes when `$nullable` will be `true`. So when an entity schema doesn't indicate that a field is `nullable`, the cases I outline will fail. 

Maybe that's ok and will help us tighten up our usage of the json schema. Maybe some exceptions should be thrown in `convertToDB()` and `convertFromDB()` to expose these problems?

**Comment by asmecher** [comment]
The more I think about this, the more the only real problem here is that the schema JSON (not nullable) disagrees with the database schema (nullable). It's the "illegal" `null` data in the `user.locales` column that's causing problems.

**Comment by touhidurabir** [comment]
@asmecher please review the PRs 

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#8023 Entity DAO update to respect the json schema](https://github.com/pkp/pkp-lib/pull/8096)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#8023 Submodule Update ##touhidurabir/i8023_main##](https://github.com/pkp/ojs/pull/3460)

I will forward port to OPS and OMP if all ok .

**Comment by asmecher** [comment]
@touhidurabir, stepping back from the "smarter" `$nullable` behaviour, would this issue not be solved by updating `user.locales` so that it is `NOT NULL`?

**Comment by asmecher** [comment]
We decided not to merge this at the moment, thinking it's better to have a tightly-defined data model and errors when those expectations are not met. But I may come back to this later!
