### ISSUE TITLE
Run more than one job per request

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8043]
**Describe the problem you would like to solve**
By default, the jobs queue is processed by running one job per request. This job is run as a shutdown function. However, in some circumstances, a large number of jobs may need to be processed at once. Processing one job per request may not work through these jobs quickly enough.

**Describe the solution you'd like**
When running jobs using the shutdown function, we should process more than one job at a time. The risk is that we try to run too many jobs at once and run out of memory. 

We should adopt an approach used by WooCommerce's [action scheduler](https://actionscheduler.org/). It is designed to process millions of jobs and they face similar hosting constraints as us (low-quality, shared hosting providers). The method they use is, in short:

> If there are actions to be processed, Action Scheduler will stake a unique claim for a batch of 25 actions and begin processing that batch. The PHP process spawned to run the batch will then continue processing batches of 25 actions until it uses 90% of available memory or has been processing for 30 seconds.

I think we don't need to use the batching that they describe, because Laravel's job queue will handle that. However, we should adopt their approach of monitoring the time and memory, and ending early when we exceed certain thresholds.

**Who is asking for this feature?**
No one yet, but this needs review before we ship the jobs queue in a production release.

**Comment by touhidurabir** [comment]
The PR made for the pkp/pkp-lib#7105 (check details at https://github.com/pkp/pkp-lib/issues/7105#issuecomment-1205015287) implement this feature . The mentioned PR handle queue job through cron and schedule task and continue process jobs one by one until there is no job left . 

> we should adopt their approach of monitoring the time and memory, and ending early when we exceed certain thresholds. 

 we are dispatching jobs via laravel workers where a default memory for 128M is set . But we can allow that to be configured if we allow any config options which can be helpful for low resourced servers . 

for time and max jobs execution at a time and to handle such criteria , my suggestion is that we set up a max run time and max job limit via config and the same config options can be used via a daemon . I can think of 2 possible options when running via cron or schedule task when the max run time or max job limit exceed

1. we kill the process and cron or schedule task will reinitiate the process again in next interval . 
2. when put it in sleep for a certain amount of time (say 10 seconds) so that in that mean time server can reallocated memories . 

Some good approach also mentioned here https://divinglaravel.com/rationing-your-laravel-queue-workers-memory-and-cpu-consumption . It's use the example of `daemon` process but same strategy can be applied for our cron/schedule task also .

**Comment by NateWr** [comment]
I think that when running a daemon process we don't need to worry about time and memory. My understanding is that the daemon is assigned a certain amount of memory and runs one job at a time, so time-outs are less of a problem.

The proposal to monitor time/memory is really for the situation where we are running jobs from the shutdown function. Those are the cases where we have two big problems:

1. We need to run multiple jobs per request, because there may not be enough requests to churn through jobs quickly.
2. We are going to face really strict limits from shared hosts about memory and time outs.

**Comment by touhidurabir** [comment]
> The proposal to monitor time/memory is really for the situation where we are running jobs from the shutdown function.

If we decide to remove that functionality totally and move to cron/schedule task/daemon, then we should not worry about it at all . The PR made for pkp/pkp-lib#7105 handle all these cases and has also turned off the `register_shutdown_function` feature .

**Comment by asmecher** [comment]
> If we decide to remove that functionality totally

My understanding is that once #7105 is merged, it'll add a new `scheduled_tasks` entry for a `ProcessQueueJobs` task. This will run tasks off the queue. So users who don't have either cron or a daemon running will still be able to process queued tasks via the acron plugin.

**Comment by touhidurabir** [comment]
@asmecher once the pkp/pkp-lib#7105 merge , we will have multiple options to run queue jobs 
1. via a worker daemon
2. via cron 
3. via acron if not cron available for some reason . 

And I thought about removing the option to run queue jobs via a `register_shutdown_function`. But what if some installation can not have due to some unforeseen reasons or decided not to enable the `acron` . As we are going to adopt queue jobs more in our system and our developers are going to have more queue jobs, those jobs will never get executed. It will just pile up and important tasks will never get done . 

what if we keep  this feature but by default turned it off . right now , it handled by following configuration in the config.inc.php file

```
; Do not run jobs on shutdown
; By default, jobs in the queue will be run during PHP's shutdown
; function. Disable this if you want to run jobs through a separate
; cron job or workers.
disable_jobs_run_at_shutdown = Off
```

the above configuration make it enable by default but we will disable it by default . Then rather then just processing one job per request , we can put following hard constrains 
1. max 10 seconds runtime
2. max 30 jobs at a time
3. set a max memory limit . Then check through `memory_get_usage ` and kill the job processing loop right before picking up another job. 

we will still strongly advice to set up via daemon/cron/acron but if some installation can not just have any of those 3, they can enable that option and have it process that way . 

Or may be I am over thinking it . question is if such scenario is possible for an installation where it can not have any of daemon, cron or acron enable .

**Comment by asmecher** [comment]
@touhidurabir, I'm comfortable with requiring users to be able to run one of the 3 mechanisms you list above. I can't think of a reason that the acron plugin wouldn't be a viable fallback, even though we would prefer a better mechanism.

**Comment by touhidurabir** [comment]
@asmecher make sense . In that case I will update the PR [pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8133 to fully remove the `register_shutdown_function` related functionality .

**Comment by NateWr** [comment]
@asmecher and @touhidurabir I'm happy to let you two settle on an approach here. But if we rely on cron/acron I worry that a lot of people will be caught out after upgrade. So far, cron has only been used to run daily jobs and our admin guide suggests a [daily  cron](https://docs.pkp.sfu.ca/admin-guide/en/statistics). To run the job queue on cron effectively someone would need to be triggering it every 60 seconds or so.

The `run_shutdown_function` approach was intended for anyone who doesn't update their cron settings.

**Comment by asmecher** [comment]
@NateWr I agree that some improvement will be required over what most users will currently have configured, but that problem isn't going to go away over time, and we'll just build a dependency on `run_shutdown_function` as a kludge that'll eat `cron` / worker thread's lunch as we gradually migrate more of our scheduled task toolset over to jobs and build new features on it.

Currently nobody will be using worker processes, some will be depending on Acron, and some will have cron set up to run daily per our documented recommendation. Some will have disabled acron and not configured cron, which is a misconfiguration.

What about if we document change in the 3.4.0 release notes -- that:
- Users who have cron configured should increase the frequency of its run to once per minute, and
- We recommend that users migrate away from cron and acron, and start adopting the worker process if available?

**Comment by NateWr** [comment]
Ok, that makes sense. I guess I thought that the `run_shutdown_function` was a _replacement_ for acron -- not a temporary fix that we would eventually deprecate. The `run_shutdown_function` and the acron plugin basically do the same thing, and it seems more appropriate to me to turn on/off this functionality from the `config.inc.php` file, rather than through the plugin interface.

**Comment by asmecher** [comment]
IMO both the existing jobs `run_shutdown_function` and acron are imperfect work-arounds for a lack of server-side job support. They will always be at risk of restrictive timeouts (e.g. execution time limits) and prone to bugs where we e.g. assume the current request's user and current job's user are the same.

In the medium term, I expect we'll replace the scheduled_tasks toolset with a Laravel-based scheduling tool, so everything will be running on the jobs toolset (rather than a mix of jobs and scheduled tasks, with jobs being executed by the `ProcessQueueJobs` task).

In the long-term, either via tools like CPanel standardizing it or by wider adoption of docker et al, we'll be able to pick a single off-the-shelf approach. But that depends on the ecosystem progressing considerably. (I suspect the need for things like websocket support in PHP environments will help drive this.)

**Comment by touhidurabir** [comment]
@NateWr as per some discussion with @asmecher, some modification made to the PR [pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8133 to handle when queue jobs dispatching done through acron at [c6591eb](https://github.com/touhidurabir/pkp-lib/commit/c6591eb61fee87909737b464e773ee4b5bc4e178) . 

Basically the `Acron` also use `run_shutdown_function` which is not much different than previous implementation . But in some weird case jobs may piles up (For example , installation don't have anything set up to handle jobs and several hundreds of jobs in waiting and then enable acron suddenly) and if all try to run one by one, that will be a heavy impact on the system . So we put a hard lime of `30 max jobs` and `30 seconds max run time` when running `off CLI` .

**Comment by touhidurabir** [comment]
@NateWr review the following commits 
[e7f21ba](https://github.com/touhidurabir/pkp-lib/commit/e7f21baa0e1c8da0c8c801cc4282996d2cda89c2)
[7645213](https://github.com/touhidurabir/ojs/commit/764521398508d69a63fa9dbc497b5572669bbf96)

it's as per the discussion that we have last time . This update add enhancements that mimics `WP Action Schedular` constrains when running jobs off `CLI` . The constrains are
1. Max jobs to process
2. Max job processing time limit
3. Max allowed memory 
4. Next job likely to run without exceeding max time limit

As I dig deeper into the `WP Action Schedular` code base, I found those 4 constraint along with another one that is related to `batch` but I dont think we need to be concerned with that one . 

It also require to update the config files with new following config options 

```
; run jobs jobs on shutdown
; Recommended approach to run jobs via worker or cron
; Enable this if you want to run jobs through PHP shoutdown function
; if worker or cron not available to set up in installation server
run_jobs_on_shutdown = Off

; Max jobs to process when run via PHP shutdown function
max_jobs_to_process_off_cli = 30

; Max jobs processing run time when run via PHP shutdown function
max_job_execution_time_off_cli = 30

; Max consumable memory to process jobs when run via PHP shutdown function
; Set the value as int to define the percentage of consumable memory defiend in .ini file
; or set the value in Megabytes to define specific memory
max_job_processing_memory_off_cli = 80
```

while the old one, `disable_jobs_run_at_shutdown = Off` removed as that was quite confusing . you can also check the full PR at https://github.com/pkp/pkp-lib/issues/7105#issuecomment-1228247646 .

**Comment by touhidurabir** [comment]
@NateWr updated commits 
[cbce04a](https://github.com/touhidurabir/pkp-lib/commit/cbce04ace7c926cb59ecbe713933cd32ae154461)
[8e33fed](https://github.com/touhidurabir/ojs/commit/8e33fed1fcad197461cf955a0c4abdfd4af24a89)

**Comment by NateWr** [comment]
Looks good @touhidurabir. :+1:

**Comment by NateWr** [comment]
Thanks @touhidurabir, looks good!

**Comment by touhidurabir** [comment]
@NateWr I think this can be closed as it's implemented at https://github.com/pkp/pkp-lib/issues/7105 .

**Comment by asmecher** [comment]
Closing, thanks!
