### ISSUE TITLE
Improve the default submission checklist

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8051]
**Describe the problem you would like to solve**
When submitting to OJS, OMP or OPS, an author must comply with a checklist of submission requirements. This list is installed by default and our default checklist hasn't been updated in 14 years! As a result, some of the items seem outdated, may be unnecessary or confusing, and may no longer follow best practices in publishing.

**Describe the solution you'd like**
Draft a new default checklist for our community of 25,000 journals, as well as appropriate language for our hundreds of monograph presses and preprint servers.

**Who is asking for this feature?**
This would be great to have alongside our #7191, as we improve the usability of our submission wizard for 3.4. But it's not been a major request because journals can configure their own checklist.

**Additional information**
Here is what the current default checklist says.

![submission-checklist](https://user-images.githubusercontent.com/2306629/176449612-0bbe4629-8c27-4a8a-983b-f1893c761305.png)

**Comment by NateWr** [comment]
Suggestions from a community member:

1. The manuscript meets the [aims and scope](#) of the journal. 
2. The title is concise, and the abstract is effective and can stand on its own. This will increase the likelihood of reviewers agreeing to review the paper.
3. The study design and research argument are structured and articulated properly.
4. The manuscript has been edited for grammar, spelling, consistency, and clarity.
5. All references have been checked for accuracy and completeness.
6. All references mentioned in the Reference list are cited in the text, and vice versa.
7. All tables and figures are referred to in the text
8. Figures and tables are numbered consecutively in the order in which they appear in the text.
9. All figures include figure captions.
10. All tables have a clear and concise title.
11. The text adheres to the stylistic requirements outlined in the [Author Guidelines](#).

**Comment by twakeford** [comment]
Definitely keep the 'The submission has not been previously published....' example in the top post.

Some of our template entries that may be useful:

1. All third-party-owned materials used have been identified with appropriate credit lines, and permission has been obtained from the copyright holder for all formats of the journal. Authors acknowledge their responsibility to gain all permissions prior to submission.
2. All authors qualify as authors, as defined in the authorship guidelines, and have given permission to be listed on the submitted paper.
3. Research has been approved by an appropriate ethics committee and in adherence to the legal requirements of the study country, with the name of the committee and reference number of approval included within the submitted file. Otherwise, a statement that ethics approval was not required has been added to the file.

Feedback from our authors/editors is that they don't want a long list of individual 'have you followed the author guidelines in this way?', 'what about this other way?' (e.g. figures, tables, font, paragraph spacing, references etc), as the list gets too long and authors start to just tick them all without really reading them. We have gone with a more complete:

_The text adheres to the stylistic and bibliographic requirements outlined in the Author Guidelines. Every effort has been made to ensure that the submission is ready for peer review according to the journal's review policy. The author acknowledges that they are responsible for blinding their files, should they wish to pursue a blind peer review process._

We also have items about patient consent, the use of ORCID and open data statements/availability, but these may be too subject/journal specific.

**Comment by NateWr** [comment]
The checklist is almost identical in OPS, but many of the requirements are probably not appropriate for preprints. An alternate list should be written for OPS.

**Comment by NateWr** [comment]
:wave: I did my best to try to reconcile the excellent list provided by @openacademia along with @twakeford's comment about keeping the list small. I decided to split this into two parts:

1. **Author Guidlines**: A general description of the expectations of the journal, including the editors' expectations and the author's ethical and legal obligations.
2. **Submission Checklist**: A shorter list of required things to check before submitting.

I re-ordered the submissions page, so that the author guidelines appear at the top, followed by the checklist. (Click to view full-size).

![submissions-page](https://user-images.githubusercontent.com/2306629/207636142-08ece7c4-cd44-41a7-8ea5-6acf9b4cc657.png)

Then the shorter checklist will appear when an author begins a submission.

![submission-checklist](https://user-images.githubusercontent.com/2306629/207636284-68fd9d3a-48a2-48b1-a11b-30da3515f9b4.png)

A reminder that these are just defaults. This will only effect new journals installed on OJS, and they can modify the text after install. We couldn't get too specific, but I think this is a good balance between specific enough to be useful but general enough to work for most journals. 

Thanks @openacademia and @twakeford for your help. There's still time to make adjustments if you think I've missed something important.

PRs:
- https://github.com/pkp/pkp-lib/pull/8497
- https://github.com/pkp/ojs/pull/3667

**Comment by NateWr** [comment]
I've merged the PRs to pkp-lib, OJS, OMP and OPS. The themes still have some problems with the tests to sort out. In addition, the OMP upgrade tests had failures. I think these are not related to this commit and fixed in https://github.com/pkp/omp/commit/5a7c4b9f2a48ff2527657318f6eb3e875a2043fa.

So the remaining PRs are:

- https://github.com/pkp/bootstrap3/pull/194
- https://github.com/pkp/classic/pull/105
- https://github.com/pkp/healthSciences/pull/224
- https://github.com/pkp/immersion/pull/78
- https://github.com/pkp/pragma/pull/88

**Comment by NateWr** [comment]
All theme PRs merged now. Closing.
