### ISSUE TITLE
DOI plugin references not removed after refactor

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#8098]
**Describe the bug**
References to the previous DOI plugin are [still present](https://github.com/pkp/ojs/blob/81664e142122e18afc5333eb9602d3e1ea48b2a3/classes/plugins/DOIPubIdExportPlugin.inc.php#L52-L54) in `DOIPubIdExportPlugin` and should be removed. There may be unintended consequences of simply removing the code, though, including the old DOI export plugin tools page becoming active again.

**To Reproduce**
1. See referenced code snippet above.

**What application are you using?**
 OJS `main` branch

**Additional information**
N/A

**Comment by asmecher** [comment]
It's worth checking any plugins that attempted to use `exportArticles` / `exportIssues` / `exportRepresentations`, as they wouldn't have been working with the plugin code checks in place. For example, I see that variable in:
- plugins/importexport/pubmed/PubMedExportPlugin.inc.php
- plugins/generic/crossref/templates/index.tpl
- plugins/generic/datacite/templates/settingsForm.tpl
- plugins/generic/datacite/templates/index.tpl

**Comment by ewhanson** [comment]
Hi @bozana, could you have a look at these? They should remove any remaining references to the now-deleted `DoiPubIdPlugin`. Thanks!

PRs:
- `pkp-lib`: #8535
- `crossref-ojs`: pkp/crossref-ojs#23
- `ojs`: pkp/ojs#3697
- `crossref-ops`: pkp/crossref-ops#20
- `ops`: pkp/ops#435

**Comment by bozana** [comment]
Hi @ewhanson, yes this all looks OK to me. It can be merged :-)

I have just noticed another thing/issue: we would at least need to remove DOI export plugins form Tools > Import/Export, right?  And I actually do not have overview what is really used from the DOIPubIdExportPlugin, PubObjectsExportPlugin and ImportExportPlugin in Crossref and Datacite... if this would still be necessary... or if we should provide a new structure/interface... because all (also future) DOI Export/Registration plugins should work in the similar way... Maybe you can help me get some overview there once?
But, I think, these things can be addressed in different issue(s)...
