### ISSUE TITLE
article DOI export (AJAX PUT request type) not working in Firefox

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8190]
**Describe the bug**
It seems that the AJAX PUT request type or X-Http-Method-Override (e.g. in article DOI export) is not always working. The Error "The requested URL was not recognized." appears. 
Tested with OJS and Firefox (103.0 (64-bit)): Inspect -> Network shows POST request type. 
Tested with OPS and Chrome (Version 103.0.5060.134 (Official Build) (64-bit)) is the same.

**To Reproduce**
1. Go to DOIs management page using Firefox (103.0 (64-bit))
2. Select an unregistered article
3. Choose Bulk Actions > Export
4. See error "The requested URL was not recognized."

**What application are you using?**
 OJS

**Additional information**
This problem does not appear when using OJS and Google Chrom :-O

**Comment by NateWr** [comment]
When using `X-Http-Method-Override`, the request will still be a `POST` request. This is because some servers don't support `PUT` requests. The `X-Http-Method-Override` header is interpreted by the API handler on the server. So the `HTTP` request is `POST` but the router will route it like a `PUT` request.

I suspect there's something else that's broken here.

**Comment by bozana** [comment]
I also had that problem with OPS and Chrom. When I then changed the method to POST in the API handler then it worked... :-O

**Comment by NateWr** [comment]
Hmm, let's hop on a call to debug when you get a chance. This approach (`POST` with `X-Http-Method-Override` for `PUT` and `DELETE`) is widely used in our production releases.

**Comment by bozana** [comment]
Also using AJAX?

**Comment by bozana** [comment]
ah, this is all my fault! :-(
I needed to clear cache in my browsers... :-P
