### ISSUE TITLE
Uncaught Error: Class "ReviewReminder" not found

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8249]
**Describe the bug**
I get the following error when running the `main` branch.

> PHP Fatal error:  Uncaught Error: Class "ReviewReminder" not found in /plugins/generic/acron/AcronPlugin.php:250

**To Reproduce**
Reproduction steps are hard to specify, because it happens with every page load. I assume it depends on what scheduled tasks are configured and when they were last run. However, this is what is in my `scheduled_tasks` table:

```
                    class_name                    |      last_run       
--------------------------------------------------+---------------------
 PKP\task\ReviewReminder                          | 2022-08-23 23:38:43
 PKP\task\StatisticsReport                        | 2022-08-23 23:38:43
 APP\tasks\SubscriptionExpiryReminder             | 2022-08-23 23:38:43
 PKP\task\DepositDois                             | 2022-08-23 23:38:43
 PKP\task\RemoveUnvalidatedExpiredUsers           | 2022-08-23 23:38:43
 PKP\task\EditorialReminders                      | 2022-08-23 23:38:43
 PKP\task\UpdateIPGeoDB                           | 2022-08-23 23:38:43
 APP\tasks\UsageStatsLoader                       | 2022-08-23 23:38:45
 lib.pkp.classes.task.StatisticsReport            | 2022-08-24 14:20:03
 classes.tasks.SubscriptionExpiryReminder         | 2022-08-24 14:20:04
 plugins.generic.usageStats.UsageStatsLoader      | 2022-09-12 13:36:17
 plugins.importexport.crossref.CrossrefInfoSender | 2022-09-12 13:36:17
 plugins.importexport.datacite.DataciteInfoSender | 2022-09-12 13:36:52
 plugins.importexport.doaj.DOAJInfoSender         | 2022-09-12 13:36:53
 plugins.importexport.medra.MedraInfoSender       | 2022-09-12 13:37:32
 lib.pkp.classes.task.ReviewReminder              | 2022-09-12 13:38:14
```

**What application are you using?**
3.4 pre-release (main branch)

**Additional information**
I believe I have run all the relevant migrations from #6091 and #7286. Looking particularly at the following, it seems like my database has been updated:

https://github.com/pkp/ojs/blob/main/classes/migration/upgrade/v3_4_0/I6091_AddFilterNamespaces.php#L54

@asmecher assigning this to you because I think it's related to #6091. Let me know if there is any more info I can provide.

**Comment by asmecher** [comment]
@NateWr, I think the issue is that you have *both* `PKP\task\ReviewReminder` and `lib.pkp.classes.task.ReviewReminder` in the `scheduled_tasks` table. Try removing `lib.pkp.classes.task.ReviewReminder`. The migration should've taken care of renaming so I'm not sure why you have both -- perhaps you ran OJS before I had some of the details nailed down? In any case, now that you do have both, the migration won't work as there's a unique key on the class name.

If it's not too big a headache I'd suggest grabbing a fresh copy of the data from the dataset, or just clearing out any tasks that are listed twice. I also see `classes.tasks.SubscriptionExpiryReminder` and `lib.pkp.classes.task.StatisticsReport`.

If you see this a second time, please flag it for me. But reviewing the codebase I think this is has already been resolved.

**Comment by NateWr** [comment]
Ah, right! Good spot. Ok, closing this but will keep an eye out.
