### ISSUE TITLE
Site-wide search returns results for journals that have publishing disabled

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8318]
**Describe the bug**
See https://forum.pkp.sfu.ca/t/articles-in-test-non-public-journals-appear-in-search/74953.

**To Reproduce**
1. Set up an installation with at least 2 journals.
2. For one that has published content, disable publishing for a journal in Setup > Distribution > Publishing Mode
3. Go to the site-wide search page
4. Search for content that exists in the journal configured above.
5. See a search result.

**What application are you using?**
OJS 3.3.0-8

**Additional information**
From the forum thread:
![image](https://user-images.githubusercontent.com/200411/194673368-f3d29bb8-ca34-4584-8568-db835fbe0c24.png)

---
**PRs**

Branch **`stable-3_3_0`**
OJS: pkp/ojs#3572
OPS: ~~pkp/ops#367~~ (not needed the option/setting should be removed)
OMP: Seems that it does not have the `Distribution > Publishing Mode` attribute

Branch **`main`**
OJS: pkp/ojs#3574
OPS: ~~pkp/ops#368~~ (not needed the option/setting should be removed)
OMP: Seems that it does not have the `Distribution > Publishing Mode` attribute

**Comment by defstat** [comment]
@asmecher @NateWr 

I have prepared the PRs for review for OJS and OPS, for `main` and `stable-3_3_0` branches.

Some comments on the code though:
1. The contexts do not have a `publishingMode` setting when they are initially created. I consider the content of contexts that don't have this setting eligible for search. 
2. It seems that OPS has the UI to declare a server's Publishing Mode, but the user selection is not retained after saving the form. I ported the same code as in OJS for OPS though.
3. It seems that OMP does not have the UI to declare the Publishing Mode. I have not ported the code to OMP because of that. Should I?

**Comment by NateWr** [comment]
@bozana do you have time to pick up this code review?

**Comment by bozana** [comment]
Hi @defstat, 
Regarding the questions:
1. I would say that we need to check if journal is enabled too -- if not already (I still haven't seen the code) -- and if enabled and the publishingMode is missing then yes, it can be searched.
2. That sounds good, I will take a look in the code...
3. I would say no need to port it to OMP -- but @asmecher or @NateWr have maybe different opinion...
Else, I will take a look at the code...

**Comment by bozana** [comment]
Hmmm... Somehow I do not see the site-wide search in the UI :-\ -- I know the path/URL, so I found it, but where in the UI is it? :-D

**Comment by bozana** [comment]
@defstat, could you please add the following to the schema/context.json in OPS:
```
"publishingMode": {
			"type": "integer",
			"validation": [
				"nullable",
				"in:0,1,2"
			]
		}
```
That should solve the problem of this option not being saved correctly...

**Comment by defstat** [comment]
> @defstat, could you please add the following to the schema/context.json in OPS:
> 
> ```
> "publishingMode": {
> 			"type": "integer",
> 			"validation": [
> 				"nullable",
> 				"in:0,1,2"
> 			]
> 		}
> ```
> 
> That should solve the problem of this option not being saved correctly...

@bozana thanks, I will add it to `schemas/context.json`. One question though: Should I leave all 3 options available for OPS? In the UI the users seems to be able to select only `0` and `2`. I added the above mentioned parameter as bellow, but will change it if you think I should.

```
"publishingMode": {
	"type": "integer",
	"validation": [
		"nullable",
		"in:0,2"
	]
}
```

**Comment by defstat** [comment]
@bozana I committed the PR review changes. I also added your suggestion made [here](https://github.com/pkp/pkp-lib/issues/8318#issuecomment-1277453225) - "I would say that we need to check if journal is enabled too"

I have 3 comments on this:
1. Those changes reflect on the individual Journal/Server search also. Should we consider something else/more because of that? 
2. It seems that the search is not working on OPS main branch. (generally it seems that it does not return results). Can you confirm that? If so should we file an other issue for that?
3. It seems that if we change the `publishingMode` for OPS to `PUBLISHING_MODE_NONE`, the content is still showing in the home page of the Server. (In OJS the context is not shown if this publishing mode is selected.) Should we file an other issue for that?

**Comment by bozana** [comment]
Hi @defstat, sorry for the delay... 
I will take a look at the first too, but regarding the third question I would need to ask...
Will come back to you soon... 
Thanks a lot!!!

**Comment by bozana** [comment]
Hi @defstat,
1. Everything OK, nothing else to consider, I think,
2. Yes, could you please file an issue for that?
3. It seems the Distribution > Access > Posting mode is not needed at all in OPS, so this setting (also in the UI) should be removed. Could you please file an issue for that too? 
Thus, no need to change anything in OPS for this issue, thus only the fix for OJS is needed.

**Comment by bozana** [comment]
OJS changes are merged, thus, the issue can be closed

**Comment by bozana** [comment]
I tested once again and now the search in the main branch works... :thinking:
