### ISSUE TITLE
Improve editorial decisions UI after usability tests

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8336]
**Describe the problem you would like to solve**
Our usability tests of the editorial decision UI (#7265) raised a few areas of confusion with the step instructions, email template finder, language switcher, and file attachments. 

**Describe the solution you'd like**
The following mockup from @Devika008 introduces the following recommended changes:

- Move the step description up so it is part of the vertical flow of reading and harder to skip.
- Improve the email templates UI to include a snippet of the email template.
- Change the icon and language of the insert content button.
- Move the attach file prompt up to the text control, so that it isn't confused for the file promotion action.
- Reposition the skip email and switch language buttons.
- Change the email step descriptions to indicate the email will be sent when the decision is recorded.

![editorial-decisions](https://user-images.githubusercontent.com/2306629/196149997-f7f12837-3628-49fc-83bf-a2984139e26a.png)

The following mockup introduces these changes:

- Add file uploaded by and date to the file promotion UI.
- Add more useful labels to the final record decision button.
- Make completed steps show a check.

![Send files- Accepting Submission in Review Stage ](https://user-images.githubusercontent.com/2306629/196150322-232483b5-6be7-4742-8b2d-fd7ebd7019cd.png)

**Who is asking for this feature?**
These suggestions come from usability tests conducted by @Devika008.

**Additional information**
See [all mockups](https://www.figma.com/file/Wf7sDlUg2372jaKKTJ0Mgz/OJS-3.4-3.5?node-id=52%3A2556). Other improvements came out of the usability tests. This issue is restricted to those changes we feel we can make for 3.4.

**Comment by NateWr** [comment]
@Devika008 we are a little constrained in which icons we can use for the buttons inside of the text editor and how well we can style. The icons seem a little too large for the text and I'm not sure they fit comfortably next to the text.

Here is what it looks like with the closest icons I could find:

![email-buttons-with-icons](https://user-images.githubusercontent.com/2306629/202517096-5d2668ca-741f-4d6f-91cb-240b1a2a92aa.png)

Here is what it looks like without icons:

![email-buttons](https://user-images.githubusercontent.com/2306629/202517122-e7b248cf-8c0f-4d34-b9e4-c2fa86cc1ba3.png)

And here is the list of icons we can choose from:

https://www.tiny.cloud/docs/advanced/editor-icon-identifiers/

Can you take a look and let me know whether you prefer with or without icons? And if you prefer it with icons, which icons should I use?

**Comment by NateWr** [comment]
@Devika008 I have implemented the new design for the steps component, using the :heavy_check_mark: to indicate complete steps. One thing that wasn't included in the mockups is how to handle cases where the user has navigated back to an older step that's already been completed.

In such cases, I chose to remove the :heavy_check_mark: and apply the "current step" style. Here is a short video showing what I mean. Does this look alright or did you want to suggest something different?


https://user-images.githubusercontent.com/2306629/203350741-e46b03ca-19a8-4161-88f2-c4fcbcfb53bd.mp4

**Comment by Devika008** [comment]
> @Devika008 I have implemented the new design for the steps component, using the ✔️ to indicate complete steps. One thing that wasn't included in the mockups is how to handle cases where the user has navigated back to an older step that's already been completed.
> 
> In such cases, I chose to remove the ✔️ and apply the "current step" style. Here is a short video showing what I mean. Does this look alright or did you want to suggest something different?
> 
>  steps-design-fixed.mp4

This seems perfect! Thank you Nate for bringing this edge case to my notice! Will include a variant of this in the design system

**Comment by Devika008** [comment]
> @Devika008 we are a little constrained in which icons we can use for the buttons inside of the text editor and how well we can style. The icons seem a little too large for the text and I'm not sure they fit comfortably next to the text.
> 
> Here is what it looks like with the closest icons I could find:
> 
> ![email-buttons-with-icons](https://user-images.githubusercontent.com/2306629/202517096-5d2668ca-741f-4d6f-91cb-240b1a2a92aa.png)
> 
> Here is what it looks like without icons:
> 
> ![email-buttons](https://user-images.githubusercontent.com/2306629/202517122-e7b248cf-8c0f-4d34-b9e4-c2fa86cc1ba3.png)
> 
> And here is the list of icons we can choose from:
> 
> https://www.tiny.cloud/docs/advanced/editor-icon-identifiers/
> 
> Can you take a look and let me know whether you prefer with or without icons? And if you prefer it with icons, which icons should I use?

@NateWr It is preferred if its with the icon because it increase accessibility for many users when translations fail to do justice.  Hence use the below svgs for the icons-

list-bull-default.svg - for bullet points
plus.svg - for insert content
upload.svg - for attach files

Also isnt there a way to include underline as well ? Or that is not possible?

I have updated the designs on figma and I think in the inspect mode youll be able to see the padding used. I think youll have to increase the spacing between the icon and the text for it to not look weird and even between the buttons in general.

**Comment by Devika008** [comment]
**Problem** as identified by @NateWr 

We are running into cases that might be a little confusing. For example, in the request revisions decision (see screenshot), the last step is to notify reviewers. But the button says "Request Revisions", which could be confusing since the user might wonder if revisions are being requested from reviewers instead of authors.
In the accept submission decision (see screenshot), the last step is to select files, so "accept submission" might be confusing. Using something else, like "Send files for copyediting", might also be confusing, because it doesn't mention the other actions that are taken (like notifying authors and reviewers). What could we do better to remove the ambiguity wrt to the CTAs on editorial decisions

**Possible Solution:**
In any applications we use on daily basis, an informative text or disclaimer is presented right before the submit button to reinstate with the user what will happen next if they click on a particular CTA and take action. In a similar way, I have removed the contextual CTAs in editorial decisions and made them consistent to "Record Decision" so as to remove any ambiguity. To inform the user the consequences of the decision, an informative alert message will be placed closer to the CTAs. Though this could cause repetition of information, but it would constantly reinforce to the editor the action they will be taking as many have pointed out that sometimes actions are taken and they do not know what is going to happen.

Exhibit A: Accepting submission in Review Stage
![image](https://user-images.githubusercontent.com/112014397/205048131-7396fe6f-7063-4031-933e-a3a01e50c606.png)

Exhibit B: Sending submission for review
![image](https://user-images.githubusercontent.com/112014397/205048253-0af3aaf0-e971-4221-9d7a-19c0f75065c1.png)

Exhibit C: Sending submission another round of review without peer review
![image](https://user-images.githubusercontent.com/112014397/205048345-92c17502-6829-4f4e-86e0-ea74f3aa8887.png)

Exhibit D: Sending submission another round of review with peer review
![image](https://user-images.githubusercontent.com/112014397/205048531-05d1b073-9127-4fc7-a7f8-c1a423bdba4e.png)

Exhibit E: Decline submission
![image](https://user-images.githubusercontent.com/112014397/205048620-bc9848a0-bd0d-4a7d-be7a-c783726cadd4.png)

**Comment by NateWr** [comment]
The following PRs implement most of the recommendations above:

- https://github.com/pkp/pkp-lib/pull/8461
- https://github.com/pkp/ui-library/pull/234
- https://github.com/pkp/ojs/pull/3640

@jonasraoni do you have time to do a code review?

@Devika008 the UI updates match the recommendations, with some exceptions that we've discussed (eg - use of all caps). There are three things that didn't get implemented:

1. Changes to the Record Decision button. e. I can handle these in a separate PR based on our discussion from above.
2. I didn't implement the changes to the switch language UI. In almost all cases (90+%), there will only be one other language to switch to. For there to be 2 or more, the journal would have to be working in 3 or more languages. I felt the heading with the items under it as in the mockups looked strange with just one language. It was a lot of valuable space on the screen for something small and, I think, not very frequently used. Also, the button doesn't really change the language of the email. It changes the language of the email templates that are loaded. It's maybe a small distinction, but I feel like it should be more closely related to the templates rather than the whole email. It won't, for example, change the recipient names or attached files or anything. I think it's ok as-is, but if you want to suggest another change let me know.
3. Finally, I modified the language a little where I thought it was appropriate. For example, instead of "Templates to get you started!" I left it at "Email Templates". When the user loads the screen, a template will already be loaded into the email composer, so it didn't sound right to say "get you started". If you want to suggest alternate language let me know.

Here's a short video illustrating out the changes that were made.

https://user-images.githubusercontent.com/2306629/205110219-a51d5675-3d7d-43e8-ac05-4098406e5a47.mp4

**Comment by Devika008** [comment]
> @Devika008 I'm a little confused about the mockups you posted. Several of them aren't the last step of the decision, so wouldn't say "Record Decision". Instead, they would say "Next" and no action is taken.
> 
> The extra text feels like clutter, and it kind of makes me less confident in the application. Like, I think, "Wait, why is it warning me about something?" We've already added extra explanatory text to the step description at the top.
> 
> ![notify-authors](https://user-images.githubusercontent.com/2306629/205099126-229a17dc-91a6-4135-a386-2a11fd1297b0.png)
> 
> I'm worried about overloading the page with explanatory text that can make the whole process just feel more cumbersome and less intuitive. Would it be better if we showed a confirmation pop-up when the user clicks "Record Decision"? Here is an example:
> 
> ![confirmation](https://user-images.githubusercontent.com/2306629/205098643-f142647d-1721-4abf-b18d-a674861d1ec5.png)

Im sorry if I wasn't clear enough! 
I do agree that adding that text seems cluttering. However, adding the pop-up seems like duplication of actions and too many confirmations. I agree with you and think that we could stick to record decision as the CTA for all the last steps. 

![image](https://user-images.githubusercontent.com/112014397/205110670-4badcb1a-602e-46db-af99-02bf90b14210.png)

However, I have noticed this functionality in other softwares in publishing where the confirmation comes as a new page versus a pop-up. Which I feel would be great with respect to scalability in the future wherein if we want to add more things to page we can. Hence I recommend the following with the option to undo the decision which sends them to the last step of editorial decision.

![image](https://user-images.githubusercontent.com/112014397/205111057-dc1a4286-a540-4209-b3e4-7841b027debc.png)

Let me know what you think

**Comment by NateWr** [comment]
I like the idea of a review step. However, there's no ability to undo a decision once it's taken. Part of the structure of the decision record is that a decision can not be revoked. There are a few reasons for this:

1. We don't want editors to be able to tamper with the editorial record. It's sometimes important to be able to audit the decisions taken and to have an accurate record of the actions.
2. Once the decision is recorded, emails are sent and they can't be withdrawn. They're "sent".
3. Once the decision is recorded, several actions have been taken that are hard to undo: files may be created, DOIs may be generated and assigned, etc. Building in an undo step would be difficult -- and particularly so for third-party integrations which may take actions we don't know about.

**Comment by Devika008** [comment]
> I like the idea of a review step. However, there's no ability to undo a decision once it's taken. Part of the structure of the decision record is that a decision can not be revoked. There are a few reasons for this:
> 
> 1. We don't want editors to be able to tamper with the editorial record. It's sometimes important to be able to audit the decisions taken and to have an accurate record of the actions.
> 2. Once the decision is recorded, emails are sent and they can't be withdrawn. They're "sent".
> 3. Once the decision is recorded, several actions have been taken that are hard to undo: files may be created, DOIs may be generated and assigned, etc. Building in an undo step would be difficult -- and particularly so for third-party integrations which may take actions we don't know about.

@NateWr 
1. With respect to the video you posted, everything looks great and I agree with all the points you put up. I will modify mu mockups to the same wrt to language. I have tweaked some text and language. Please review it once in my screenshots below
2. I did play around with the review step since building on our discussion the step for recording the decision is a crucial one and one where editors need to be sure of! Please view the options below and let me know what you think-

**Step 1:**
![image](https://user-images.githubusercontent.com/112014397/205124080-b4241a01-3267-436b-90c5-a7fa97221cba.png)

**Step 2:**
![image](https://user-images.githubusercontent.com/112014397/205124133-3a4d204f-14a0-4697-88a1-7c65abc9748b.png)

**Step 3:**
![image](https://user-images.githubusercontent.com/112014397/205124259-fd5519d1-3014-4ea1-b306-6e412c31d7a0.png)

Step 4 (Option **1):**
![image](https://user-images.githubusercontent.com/112014397/205124334-bcbb4585-e8b0-4e87-92bf-e30df81b81d3.png)

**Step 4 (option 2):**
![image](https://user-images.githubusercontent.com/112014397/205124411-64465034-931f-4dab-9728-41dad9f02cbf.png)

Success Pop-up:
![image](https://user-images.githubusercontent.com/112014397/205124486-6375ba1a-f527-4939-9163-26e586ceafa8.png)

**Comment by NateWr** [comment]
I think I'm going to suggest we postpone the review until the next version. Adding the review page will be a fair amount of work just in testing the 20-25 different decisions. Hope that's alright, @Devika008!

**Comment by Devika008** [comment]
> I think I'm going to suggest we postpone the review until the next version. Adding the review page will be a fair amount of work just in testing the 20-25 different decisions. Hope that's alright, @Devika008!

I think thats completely alright! however

1. I wanted to know your thought/ opinion about adding the review page?
2. I am OK with the CTAs being Record Decision however in the success pop-up please include the but that "if you have chosen to notify participants, emails have been shared with them?"

**Comment by NateWr** [comment]
I've merged the PRs above to `main`. Thanks for the review @jonasraoni.

@Devika008:
1. I like it! Might need to spend some time thinking through what/how to show for some edge cases. But we can do that later.
2. I've filed a separate issue for that here: https://github.com/pkp/pkp-lib/issues/8469
