### ISSUE TITLE
OJS ORCID plugin is not sending DOI information to author ORCID profile

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#8356]
**Describe the bug**
When an author is connecting his/her ORCID account to OJS to submit an article, information about the article is sent to his/her ORCID profil upon publication but article DOI is not used. Instead, OJS uses the article URL.

See example for this article https://doi.org/10.51657/ric.v6i2.51683

It appears in the ORCID page without DOI:  https://orcid.org/0000-0002-8183-6576

The article DOI is not sent, but the issue DOI is.

**Comment by mhvezina** [comment]
Hi @pilasou 
Interestingly, the article DOI is included within the ORCID record bibTeX citation, suggesting maybe it is transmitted but not displayed (?). See https://forum.pkp.sfu.ca/t/inital-article-for-title-and-doi-not-displayed-within-orcid-profile/76146

**Comment by mhvezina** [comment]
Thank you @withanage Since, as I mentionned in the [former post](https://github.com/pkp/pkp-lib/issues/8356#issuecomment-1375844762) the DOI from OJS does appear in the BibTeX citation in the ORCID Profile (indicating there is some sort of DOI support with the plugin, right?), is the fact that the DOI not displaying in the main upper part of the record in the ORCID profile due to the fact that the DOI is passed/send incorrectly or that, on the ORCID side, it is expected to display but for some reason is not ?

**Comment by pilasou** [comment]
Hi @withanage, were there any updates to the Plugin to solve this issue?

**Comment by mhvezina** [comment]
Bonjour @pilasou : Issue is solved with the latest version of the plugin : https://forum.pkp.sfu.ca/t/inital-article-for-title-and-doi-not-displayed-within-orcid-profile/76146/
