### ISSUE TITLE
Consider new DOI implementation in other parts of the code

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8369]
Consider new DOI implementation in other parts of the code:
- [x] DublinCoreMetaPlugin (s. https://github.com/pkp/pkp-lib/issues/8406) 
- [x] GoogleScholarPlugin (s. https://github.com/pkp/pkp-lib/issues/8478)
- [x] IssueNativeXmlFilter  
- [x] NativeXmlIssueFilter 
- [x] NativeXmlRepresentationFilter
- [x] NativeXmlSubmissionFileFilter
- [x] CounterReportAR1

PRs:
- https://github.com/pkp/pkp-lib/pull/8624
- ~https://github.com/pkp/orcidProfile/pull/234~ will be solved in another issue
- https://github.com/pkp/ojs/pull/3757
- https://github.com/pkp/omp/pull/1331
- https://github.com/pkp/ops/pull/466 (only submodule update)

**Comment by bozana** [comment]
Hi @ewhanson, could you please take a look at the PRs/changes above? Thanks a lot!

**Comment by ewhanson** [comment]
Hey @bozana, I had a look and only a few comments/questions. 

On the subject of DOI versioning with the native import export tools, I took a look and don't see any immediate issues. The DOIs are tied to versioned pubObjects, e.g. two publications on the same submission having two different DOIs would be updated the same way as if there were only one publication. This should give us the desired behaviour, but it's hard to say what edge cases there might be.

**Comment by ewhanson** [comment]
@bozana, another thought I had about DOI versioning (or rather, lack of DOI versioning) is what happens when say, a submission has two publication versions that are each assigned the same DOI? When the native import works through the second publication, it would try and create the same DOI again. Would it be best to assume that this is correct (that this publication should be assigned the same DOI), and instead of creating a new DOI object, just update the publication's `doi_id` to use the existing one?

**Comment by bozana** [comment]
Hi @ewhanson, yes, I would (as I thought here: https://github.com/pkp/pkp-lib/pull/8624#discussion_r1105862218) first check if the DOI exists and if it exists I would assign that DOIs ID to the object, else I would create a new one...
Thanks a lot!

**Comment by bozana** [comment]
@ewhanson, I have considered it... Could you please take another look, if so OK?

**Comment by ewhanson** [comment]
@bozana, looks good to me!

**Comment by bozana** [comment]
Thanks a lot @ewhanson!
