### ISSUE TITLE
OAI Error with full url query

### ISSUE THREAD

**Issue by alwathan** [pkp/pkp-lib#8399]
**OAI Error with full url Query**
OAI error when full query are set: 
[https://jurnal.inkadha.ac.id/index.php/kariman/oai?verb=ListRecords&metadataPrefix=oai_dc&set=kariman](https://jurnal.inkadha.ac.id/index.php/kariman/oai?verb=ListRecords&metadataPrefix=oai_dc&set=kariman)

but working without full url Query: 
[https://jurnal.inkadha.ac.id/index.php/kariman/oai?verb=ListRecords&metadataPrefix=oai_dc](https://jurnal.inkadha.ac.id/index.php/kariman/oai?verb=ListRecords&metadataPrefix=oai_dc)

also working with this url:
[https://jurnal.inkadha.ac.id/index.php/kariman/oai](https://jurnal.inkadha.ac.id/index.php/kariman/oai)

 OJS 3.3.0.10

![Desktop screenshot](https://user-images.githubusercontent.com/16916624/199616554-08197462-c790-4481-bedb-b5b19ecb9def.png)

**Comment by asmecher** [comment]
@alwathan, you can resolve this issue by either applying [this change](https://github.com/pkp/ojs/commit/ab4a557f68836117b00f8a6da43131ee1a6afcfa), or by changing your PHP configuration so that errors/warnings are not sent to the browser (see the PHP [display_errors](https://www.php.net/manual/en/errorfunc.configuration.php#ini.display-errors) setting), or both. It is never recommended to leave `display_errors` turned on in production!
