### ISSUE TITLE
Method Repo::author()->getSubmissionAuthors() is unnecessary

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8426]
**Describe the problem**
The method `Repo::author()->getSubmissionAuthors($submission)` is used in several places. However, this method duplicates the functionality of `$submission->getCurrentPublication()->getData('authors')`. Two minor problems:

1. `Repo::author()->getSubmissionAuthors($submission)` gets the authors from the database, but the authors are already attached to the current publication object when it is created from the database. So removing this will reduce the database queries.
2. If we introduce a new repository method in 3.4, it will be harder to remove it later. (This method does not exist in 3.3, so we can remove it now without any deprecation.)

**Describe the solution you would like**
Replace `Repo::author()->getSubmissionAuthors($submission)` with `$submission->getCurrentPublication()->getData('authors')` wherever it is used.

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
@asmecher this isn't strictly required but should be a quick clean-up and save us some deprecation work down the road. Feel free to remove the milestone if you don't want it scheduled against 3.4.

**Comment by asmecher** [comment]
@NateWr, for the sake of documentation: in the process of cleaning this up I took the liberty of removing some functions that have been deprecated since 3.2.0...
 - `Submission::getAuthorString` (use `Publication::getAuthorString` instead)
 - `Submission::getShortAuthorString` (use `Publication::getShortAuthorString` instead)
 - `Submission::getPrimaryAuthor` (use `Publication::getPrimaryAuthor` instead)
 
For themes that override `article_summary.tpl` (OJS), `monograph_summary.tpl` (OMP), or `preprint_summary.tpl` (OPS), this will likely mean a change like this in order to avoid a fatal error:

https://github.com/pkp/immersion/commit/a1f2e2bf1354db623e3329d87e0e27563dbfb828
