### ISSUE TITLE
Issue galleys do not use their original filenames when downloaded

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#8448]
**Describe the bug**
When you download a full issue galley, the galley file is saved with the server-generated filename, rather than the original upload name.  Patch to fix this incoming.

**What application are you using?**
OJS 3.3.0.13

**Comment by jnugent** [comment]
PR for `main`  https://github.com/pkp/ojs/pull/3631

**Comment by asmecher** [comment]
Merged because it's likely not to affect that many users, but in general I'm avoiding changes to filename management until we're able to do a broader check on what people expect. We've changed policies on this back and forth a few times in submission file downloads, each time with a subset of users expressing that they preferred how it was before.
