### ISSUE TITLE
consider mariaDB in Travis

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8490]
Add mariaDB tests in Travis

**Comment by bozana** [comment]
PRs:
https://github.com/pkp/pkp-lib/pull/8489
https://github.com/pkp/ojs/pull/3658

**Comment by bozana** [comment]
Maybe @asmecher or @jonasraoni would know more, what everything is needed for the tests to consider mariaDB. 
E.g. I do not know what mariaDB version we should consider in travis.yml. We use dist=bionic so maybe it needs to be "10.1"?

**Comment by asmecher** [comment]
That looks fine, @bozana, but how do you feel about maybe having the PHP8.0 test cover MariaDB and the PHP8.1 test cover MySQL? The two are similar enough that I don't think we need to multiply out our testing further (and cause additional loads on our Travis account).

It looks like the tests failed, but I suspect a rebase would fix that. Could you rebase and also port to OMP and OPS? If the tests pass, then this will be ready for merge, thanks!

**Comment by bozana** [comment]
There is one thing I do not understand: how does Travis know that the mariaDB should be used :-D -- the commands are the same as for mysql... :thinking:

**Comment by asmecher** [comment]
Just having MariaDB installed in place of MySQL should be enough -- the two live e.g. on the same TCP/IP port. You can see in the Travis log that when MariaDB is installed, apt/dpkg get rid of MySQL in the process:
![image](https://user-images.githubusercontent.com/200411/207908188-12b0cdbd-43eb-430d-a42e-05870c9507a4.png)

**Comment by bozana** [comment]
And does Travis know that it needs mariaDB for that test with PHP8.0 having only `env: TEST=mariadb`? :-\

**Comment by asmecher** [comment]
Ah, actually, the PR as it currently stands also replaces MySQL with MariaDB during the MySQL test. Rather than specifying MariaDB [in the global part of the `.travis.yml` config](https://github.com/pkp/ojs/pull/3658/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R23), you might need to run the appropriate `apt-get` commands directly in order to replace MySQL with MariaDB *only* when `$TEST` is `mariadb`. I'd suggest adding it in `lib/pkp/tools/travis/prepare-tests.sh` in a new clause like the others:
```bash
if [[ "$TEST" == "mariadb" ]]; then
    sudo apt-get install -q -y mariadb-server
    ...
```

**Comment by bozana** [comment]
OK, a new attempt... S. new PRs above (@asmecher)

**Comment by asmecher** [comment]
@bozana, you'll also need to add `SAVE_BUILD: true` to the MariaDB build, so that we start collecting datasets in https://github.com/pkp/datasets that include MariaDB as well. (This is probably an easy way to check whether the Travis test actually did run on MariaDB rather than MySQL.)

Why was it necessary to reinstall MySQL at the end of the test?

> how did Travis know that it needs mysql earlier?

I think Travis comes with MySQL by default, so it's already installed and running even though you didn't configure it anywhere. Not sure if that answers your question, though!

**Comment by bozana** [comment]
> @bozana, you'll also need to add `SAVE_BUILD: true` to the MariaDB build, so that we start collecting datasets in https://github.com/pkp/datasets that include MariaDB as well. (This is probably an easy way to check whether the Travis test actually did run on MariaDB rather than MySQL.)

Hmmm... I think I did this for mariadb but not for mysql... Does it mean that it is not working as it should :thinking: I'll add for mysql too...

> 
> Why was it necessary to reinstall MySQL at the end of the test?

I did not know that Travis comes with it by default. I will remove it to see what is happening... 

> 
> > how did Travis know that it needs mysql earlier?
> 
> I think Travis comes with MySQL by default, so it's already installed and running even though you didn't configure it anywhere. Not sure if that answers your question, though!

Yes, that answers it! :-) Thanks a lot!

**Comment by asmecher** [comment]
Hi @bozana! Is this waiting for a review, or are you still working on it?

**Comment by asmecher** [comment]
@bozana, you're just running this from pull requests so far, right? Until it's merged into one of the formal PKP branches, no dataset will get uploaded. It's the check for `$TRAVIS_PULL_REQUEST` that does it:

https://github.com/pkp/pkp-lib/blob/main/tools/travis/run-tests.sh#L23

**Comment by bozana** [comment]
@asmecher, hihihihi, yes, that makes sense... crazy me... hihihihi :-D
So, then, it is/was ready for the (final) review :-)

**Comment by asmecher** [comment]
@bozana, those look good to me, thanks -- please merge and let's see if the MariaDB datasets start showing up!
