### ISSUE TITLE
Journal Statistics DAO cross product is too large

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#856]
The cross product of articles and users in the Journal Statistics DAO
https://github.com/pkp/ojs/blob/a9459eb851921827e34402a321ff206422f34a34/classes/journal/JournalStatisticsDAO.inc.php#L31-L45
is causing problems with very large selects.

See:
http://forum.pkp.sfu.ca/t/error-in-stats-reports-page/4683/2

This would probably be cleaner and faster as two selects.

**Comment by asmecher** [comment]
@beghelli, could you take a look?

**Comment by beghelli** [comment]
This is working for me, reviewed and had just one comment. Will wait for the forum user feedback to see if that solves his problem.

**Comment by ctgraham** [comment]
Looking at prior interactions, @ birkok may or may not be comfortable with the technical aspects of applying a patch.
http://forum.pkp.sfu.ca/t/upgraded-to-2-4-6-and-submission-acknowledgement-email-is-not-sent-anymore/798/6

We may not get direct feedback from the forum.

**Comment by beghelli** [comment]
Ok, I will test with the largest database I have here and compare the execution time. I think that this is enough to merge.

**Comment by beghelli** [comment]
Tested here, but my largest database doesn't have enough records to even get close to my max_join_size, that is 18446744073709551615. The speed is the same using a single query and two. Will merge since it can avoid problems with people that has sql_big_selects disabled, although I think that other parts of the system could have problems with that in this case...
