### ISSUE TITLE
zsh: no such file or directory: pkp-lib/classes/services/queryBuilders/SubmissionStatisticsQueryBuilder.inc.php

### ISSUE THREAD

**Issue by Hmidw** [pkp/pkp-lib#8606]
**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**

**What application are you using?**
 OJS, OMP or OPS version X.X.X

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by asmecher** [comment]
@Hmidw, this isn't enough information to understand what's happening. I'd suggest posting on our community forum (https://forum.pkp.sfu.ca) with as much detail as you can provide about what you're trying to do. Include information about which of our applications you're running, what version, and how to reproduce the problem you're encountering. If it turns out to be a bug, we can re-open this issue.
