### ISSUE TITLE
Forward-port site identifier

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#871]
Foward-port the site identifier (used for statistics, but also the beacon)

**Comment by beghelli** [comment]
Unique site id is already implemented by the usage event plugin, that's already in both OMP and OJS dev and master branches. If you had problem trying to retrieve it might be because the unique id setting is only created when the usage event plugin build an usage event. That might not happen before the VersionCheck tries to use it. Does that makes sense @asmecher ?

**Comment by asmecher** [comment]
Yes, thanks!
