### ISSUE TITLE
Using lang_COUNTRY locale causes HTTP 500 error

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#8718]
**Describe the bug**
During OJS 3.4 testing, found that the option for lang_COUNTRY and lang are still presented as options when installing locales. However, using the locale - lang_COUNTRY results in HTTP 500 error when a user toggle to this locale

![image](https://user-images.githubusercontent.com/50342731/222587532-918b96a3-f07e-4ba9-b5ca-510e621f2ac7.png)

**To Reproduce**
1. Install  lang_COUNTRY (e.g., de_DE or da_DK)
2. Enable language toggle block
3. Change language to de_DE or de_DK

**What application are you using?**
Error was seen on OJS and OMP

**Additional information**
Error also occurs when changing locale on backend. 
 
As an aside, wondering if journals using a lang_COUNTRY locale in older versions of OJS will encounter any issues with the locale naming change once they upgrade.

**Comment by NateWr** [comment]
> As an aside, wondering if journals using a lang_COUNTRY locale in older versions of OJS will encounter any issues with the locale naming change once they upgrade.

Just to say that we will have guidance on this in the Release Notebook for admins who are upgrading.

**Comment by asmecher** [comment]
I believe a fresh check-out of all repos will cause this to go away. The Acron plugin included old-style (e.g. `de_DE`) locale codes, thus these were being included in the installer but would cause an error because they don't exist in the application. I've since converted the codes in the acron plugin over, and the submodule update has been applied.
