### ISSUE TITLE
OMP 3.4 - Series editor cannot send to review if only allowed to recommend an editorial decision

### ISSUE THREAD

**Issue by kshuttle** [pkp/pkp-lib#8719]
**Describe the bug**
This bug is being reported as part of OJS 3.4 testing.

When a series editor is assigned to a submission and their assignment privileges are set to "This participant is only allowed to recommend an editorial decision and will require an authorized editor to record editorial decisions," they are not able to move the submission to peer review. 

If another user (like the Press Editor) sends the book to review, then the Series Editor can recommend a decision (revisions, accept, decline). 

**To Reproduce**
1. Create a submission and assign a series editor
2. Check off the "only allowed to recommend an editorial decision" setting during the series editor assignment stage
3. Login as the series editor and look at the submission in the submission stage
4. The series editor is unable to take any action on the submission until someone else sends it to review.

**What application are you using?**
OMP 3.4

**Additional information**
This is what the series editor sees in the submission stage when they are only allowed to recommend editorial decisions. They cannot move the submission to review.
![image](https://user-images.githubusercontent.com/59741486/222613186-4a20fbc1-15d7-4301-8f73-54344d4491fb.png)

-----------------------------------------------------------------
**PRs**

OJS: pkp/ojs#3906
OMP: pkp/omp#1401
OPS: pkp/ops#530
PKP-LIB: #8997

**Comment by kshuttle** [comment]
Hi @NateWr,
Thanks for confirming that this is working as intended. Can you confirm that this is a planned change from OJS / OMP 3.3? In 3.3 a section editor / series editor with "recommend only" permissions can send to review, but they don't have other options (like recommend a decline or accept without review decision), as described in [this issue](https://github.com/pkp/pkp-lib/issues/6987).

**Comment by NateWr** [comment]
Thanks @kshuttle. If this is a change from 3.3 then that's unintended. The general problem is that recommending editors are only intended to be used in the review stage, but we haven't specified that anywhere. So we have no use cases for recommending editors in other stages or any understanding of how such a configuration should work. For that reason, leaving things as they were in 3.3 is best until we have a clear direction.

**Comment by kshuttle** [comment]
Thanks @NateWr.
Confirming with screenshots (in case it helps) what I see in 3.4 (logged in as a section editor with "recommend-only" privileges)
![image](https://user-images.githubusercontent.com/59741486/223778685-5d4d2382-3d61-485d-8823-b8dbd2c34cc5.png)
vs the same in 3.3
![image](https://user-images.githubusercontent.com/59741486/223778760-885309ea-28af-4d8b-964a-70008b24da46.png)

**Comment by defstat** [comment]
@NateWr @Vitaliy-1 

In `stable-3_3_0` branch  (https://github.com/pkp/omp/blob/stable-3_3_0/classes/workflow/EditorDecisionActionsManager.inc.php#L126) the code seems to "hard code" the `SUBMISSION_EDITOR_DECISION_INTERNAL_REVIEW` in the available editor decisions. Here (https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/workflow/PKPEditorDecisionActionsManager.inc.php#L80) it also seems that the `SUBMISSION_EDITOR_DECISION_EXTERNAL_REVIEW` is being "hard coded" - The code does not check for `makeDecission` or anything else to add it to the available decisions.

The `main` branch does not seem to have a similar mechanism that takes into account the `makeDecission` in order to return the available decisions. It returns all available decisions depending on the stage, and then in the `editorialLinkActions.tpl` it shows the decisions if `canRecordDecision` is `true`. 

We could add something like 
```
if $makeRecommendation and in WORKFLOW_STAGE_ID_SUBMISSION show only the review related decisions if available 
```
if we want to have the same results in the main branch, but I am not sure that is the correct approach - should we perhaps make a backoffice function that checks that and returns the available decisions taking into account the stage and the user?

**Comment by NateWr** [comment]
I think the fix here is in `APP\pages\workflow\WorkflowHandler::getStageRecommendationTypes()`. The editorial decisions missing from the submission stage should be added there, so that they appear to recommending editors.

I'd suggest adding a comment to the method's docblock that explains that recommending editors are allowed to take decisions in the submission stage, something like:

```php
/**
 * Add allowed decision types for recommending editors
 *
 * Recommending editors are allowed to send a submission to review
 * as though they were deciding editors.
 */
```

@kshuttle based on your screenshot, it seems that a recommending editor is allowed to send the submission to review, but not allowed to accept or decline it. Can you confirm that is the case in 3.3? If so, @defstat, only the send to review decision should be added for recommending editors.

**Comment by Vitaliy-1** [comment]
Thanks, @defstat 

I left a couple of comments. In general, it looks like the behaviour is nevertheless changed from 3.3 - the editor with the `only recommend` flag can send submission to review only when deciding editor is also assigned to this submission.

From what I see, to change this behaviour, `DecisionAllowedPolicy` should be modified somewhere [around here](https://github.com/pkp/pkp-lib/blob/28e263473248403bd33668c378cbe0095fec73bb/classes/security/authorization/internal/DecisionAllowedPolicy.php#L71). I can't tell exactly the scope of the changes needed here.

**Comment by defstat** [comment]
@Vitaliy-1 thanks for reviewing this.

I am working on ojs 3.3.0-14 (for example) and I am getting the following behaviour:

**Image 1**
![image](https://github.com/pkp/pkp-lib/assets/560456/a864ff16-ddb1-49f4-9f37-4cbb8318d717)

**Image 2**
![image](https://github.com/pkp/pkp-lib/assets/560456/344a28f0-0403-494c-98ae-4e0c4cdc53f0)

There is only one editor for which I have assigned only the "This participant is only allowed to recommend an editorial decision" option (see Image 1). It seems to me that there is no other "Deciding Editor" assigned to this submission. After that I signin as him and he is allowed to "Send to Review" (see Image 2). I tried to have the same behaviour for the fix of that issue.

I am, thus, confused - Am I missing something?

**Comment by Vitaliy-1** [comment]
Yes, I meant that if apply the PR to the main branch, the editor with `only recommend` flag cannot send the submission to the review stage without deciding editor assigned.
![editor](https://github.com/pkp/pkp-lib/assets/20665587/d17ce0cc-d4eb-4bac-9642-67deb6516d16)

**Comment by Vitaliy-1** [comment]
Thanks, @defstat. Looks good and is ready to be merged!

**Comment by asmecher** [comment]
Thanks, both! All merged.
