### ISSUE TITLE
UI routing by URL hash not working

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8743]
**Describe the bug**
After entering in a URL such as `/management/settings/website#plugins`, the interface was expected to go to the "Plugins" tab, but it's not working.

**What application are you using?**
OJS 3.4

**Comment by asmecher** [comment]
This does appear to be a regression since 3.3.0-x.

**Comment by asmecher** [comment]
This is caused by the shift of the `Page.vue` code that handles hashes from `mounted()` (when the tabs will already be ready to go) to `created()` (before the tabs have a chance to register listeners on the event bus):

https://github.com/pkp/ui-library/commit/467034aa4171bca0c46fa9e0e4b8b8dcdaa7cee2#diff-a43214ebfa7ff300633b73811ee18822910c08f67fa37ae5a0b2a13b1998fcd7L110-R119

@NateWr, was that change done for a particular purpose, or can I revert it?

**Comment by NateWr** [comment]
PR:
https://github.com/pkp/ui-library/pull/268

Tests:
https://github.com/pkp/ojs/pull/3841

**Comment by NateWr** [comment]
I went ahead and merged because I'm pretty confident the two test failures are related to https://github.com/pkp/pkp-lib/issues/8841 and not this change.
