### ISSUE TITLE
Installed plugins section headers spill across right border

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#8815]
**Describe the bug**
In FF v110, the installed plugins section headers spill across the right border.

**To Reproduce**
1) Go to Settings > Website > Plugins > Installed Plugins

**What application are you using?**
OPS 3.4 RC1

**Additional information**
Screenshot below.
![Screen Shot 2023-03-15 at 6 43 43 PM](https://user-images.githubusercontent.com/200793/225460049-cdfccb47-36f1-4819-b514-bf48e49a0ebb.png)

**Comment by NateWr** [comment]
This effects `stable-3_3_0` and only happens when there is a very long unbroken word. For me, it happened because at least one plugin didn't have a translated title, so the resulting title was a locale key:

```
##some.very.long.locale.key.that.goes.on.and.on##
```

I've pushed a small style change which will help reduce this problem. But a table will always do this when the width gets too small. After the change, I encounter the problem at about 530px width. There's no good way around this other than to refactor away from the old grid tables, so hopefully this will do for now.
