### ISSUE TITLE
Workflow Production tab empty for new submission

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#8820]
**Describe the bug**
After an author completes a submission in OPS, the Workflow > Production tab does not include any details for the submission when accessed by a Preprint Server Manager.

**To Reproduce**
1) Complete a test submission as an Author
2) Click on View for the submission as a Preprint Server Manager.

**What application are you using?**
OPS 3.4 RC1

**Additional information**
Screenshot below.

![Screen Shot 2023-03-15 at 7 32 29 PM](https://user-images.githubusercontent.com/200793/225467097-16aa5717-4c4c-433d-a315-e277f141010c.png)

**Comment by NateWr** [comment]
I was unable to reproduce this on the `main` branch with the `main` dataset. I suspect you have a misconfigured install -- either the database, javascript or something else is not synced -- because the tests would fail if the production tab wasn't loading However, if you can find reproduction steps from the `main` branch on the `main` [dataset](https://github.com/pkp/datasets/tree/main/ops/main), I'll reopen.
