### ISSUE TITLE
Email template text displayed only in primary locale

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#8821]
**Describe the bug**
With multiple locales enabled, email template text is only displayed in the primary locale.

**To Reproduce**
1) Enable multiple locales
2) Go to Workflow > Emails > Add and edit templates
3) Filter templates by System
4) Click on Edit for Password Reset Confirm
5) Click on the non-primary locale to display the email template text

**What application are you using?**
OPS 3.4 RC1

**Additional information**
Screenshot below.

![Screen Shot 2023-03-15 at 7 39 45 PM](https://user-images.githubusercontent.com/200793/225468570-8ce98f33-1a28-4e04-996a-271a318bf839.png)

**Comment by NateWr** [comment]
Unable to reproduce in `main` with the `main` dataset. I see a subject and body (see screenshot). The name is missing because the locale key has not yet been translated into Fench.

![email-template](https://user-images.githubusercontent.com/2306629/225575505-99a693f3-8281-47b3-a84a-31eb0cc463bc.png)
