### ISSUE TITLE
Use jobs to fix the old region codes after the upgrade

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8866]
Currently the following two upgrade scripts should fix the old region codes:
- https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/I6782_RegionMapping.php
- https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/I6782_FixRegionCodes.php

We have not included them into upgrade to 'shorten' the upgrade. They were thought to be applied manually by admins, if needed.

This solution will use jobs that will then fix the region codes after the upgrade, if needed (= if region exists). The upgrade script will dispatch a job per country. This way I hope that the job processing will not take too long.
I didn't come up with the better separation of jobs, than per country. -- I think it does not make sense to separate the jobs by certain number of rows to fix, because in that case the whole FIPS to ISO mappings would needed to be loaded into the temporary database, or some not convenient searches would be needed, which would also take time i.e. be less performant.

PRs:
- https://github.com/pkp/pkp-lib/pull/8878
- https://github.com/pkp/ojs/pull/3869
- https://github.com/pkp/omp/pull/1389
- https://github.com/pkp/ops/pull/513

**Comment by bozana** [comment]
@touhidurabir, may I ask you to take a look at this upgrade script: https://github.com/bozana/pkp-lib/blob/8866/classes/migration/upgrade/v3_4_0/I8866_DispatchRegionCodesFixingJobs.php.
It dispatches this job https://github.com/bozana/pkp-lib/blob/8866/classes/migration/upgrade/v3_4_0/jobs/FixRegionCodes.php for each country. The job that considers the last country from the list is considered as 'last job' and in that case the job will remove the temporary table and indexes. If for some reason a job (for a country) fails, the 'last job' will eventually not be the last -- admin could re-run the failed job, that could be then the last job. Thus, I was thinking if I should double check/check differently if job is the last one in order to remove the temporary table and indexes. This actually is probably a VERY RARE case, so I am not sure if I should consider that case at all :-\ The job is not unique job, so, if I should check if it is the last job somehow differently, I would probably prefer to just 'take a look' in the DB tables 'jobs' and 'failed jobs'...
And it is supposed to be run after the upgrade, thus I seems to be OK to be run as the other jobs, or?

**Comment by bozana** [comment]
@asmecher could you take a look at the PRs here? 
There is one problem: When a job for the last country is dispatched, the job is 'defined' as last job and that 'last job' will remove the temporary DB table and indexes. If however a previous job - for a previous country - failed, it is possible that it will be executed again later - and this will work fine, there are no dependencies - but that 'last job' is then actually not the last, and thus, the temporary table and indexes will remain (because they are created again by that failed job that was executed once again).
Thus, I do not know how can I exactly know if a job is the last one executed (considering also the failed jobs that can be executed again) so that the temporary table and indexes are removed :thinking:

**Comment by asmecher** [comment]
@bozana, please go ahead (and sorry for the wait). I don't mind if we leave temporary tables over after an unusual quirk during the upgrade process -- they are harmless and can be cleaned up manually.

**Comment by touhidurabir** [comment]
@bozana Sorry I missed it as was in parental leave for last 2 weeks . I see that it has already merged so may be no modification required . BTW I have gone through the implementation and have few suggestions for future modifications(if we need to)
1. instead of dispatch jobs one by one , it best suited to have dispatch as a `Batch` job . 
2. To handle the leftover table , the below implementation can be considered a more laravel suggested approach 
```php
Bus::batch($jobs)
    ->then(function (Batch $batch) {    
        // All jobs completed successfully...
        // Better the handle the table/index removal here
    })
    ->onQueue('queuedTestJob')
    ->dispatch();
```
the `then` block only get to execute when all the jobs in a `batch` get done successfully  and no failure . And from previous comments it seems thats what we want . 

3. 
> it is supposed to be run after the upgrade, thus I seems to be OK to be run as the other jobs

if these jobs does not need to run immediately, then fine . But my thought was that if we continue to add such upgrade jobs, best to push to to a a specific queue (may be named `upgrade`) and add the queue run command(i.e. `php lib/pkp/tools/jobs.php run --queue=upgrade`) to the upgrade script to execute those at the end of upgrade process .

**Comment by bozana** [comment]
@touhidurabir, thanks a lot!
I can change it to use Batch job -- I haven't checked that we have already using it -- I remember we mentioned it in the dev call but I did not know it is ready to be used :-P :-D :+1: 
In that case I can remove some code from the job class:
https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/jobs/FixRegionCodes.php#L50-L73
and 
https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/jobs/FixRegionCodes.php#L121-L141
and put that code in the upgrade script (the code form the second link in `then` loop).
Would that Batch job i.e. `then` loop also know/be executed if a job failed, admin run it again, and the job then completed successfully?
Thanks a lot!!!

**Comment by touhidurabir** [comment]
@bozana If this is working fine with no issue, may be there is no need to update it . If you want to update it using batch jobs, perhaps the following approach will be suitable
1. These codes in upgrade script https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/jobs/FixRegionCodes.php#L50-L73 as we only need to have the temp table and index set once
2. dispatch the jobs as batch
3. put these https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/jobs/FixRegionCodes.php#L121-L141 in the batch `then` block where we need to drop the temp indexes and table . 

> Would that Batch job i.e. then loop also know/be executed if a job failed, admin run it again, and the job then completed successfully?

The batch `then` block only get executed when all jobs in the batch executed successfully. even if one failed , it will not be executed. But if admin redispatch the failed jobs from our UI and it executed successfully, that is `All jobs in the batch executed successfully` , it will then execute . This basically remove/drop the temp index and table at the end of all jobs in the batch execute successfully .

**Comment by bozana** [comment]
Hi @touhidurabir, thanks!
This "But if admin redispatch the failed jobs from our UI and it executed successfully, that is All jobs in the batch executed successfully , it will then execute." is great and worth changing the code... :+1: :-)

**Comment by jnugent** [comment]
Hi everyone,

We've been upgrading some very large clients to 3.4, from 3.3.  We appreciate that some of these very time consuming queries have been moved into jobs after the upgrade.  However, in 3.4.0.9 the FixRegionCodes job never runs to completion and just gets killed by the queue when it hits timeout.

In an installation with originally 4.7 million records in the metrics table, we end up seeing these jobs fail. At which point they get rescheduled to run again.  For a brief period, then, load returns to normal in the 3.4 install, and then performance takes a huge hit as they try to run a second and a third time.  Eventually they just stop being tried and at that point I don't really know what the database looks like. Do we then have a mix of two and four character region codes?

The queue looks like this, at the moment.  These have been tried twice, and will fail again, even though the timeout in `BaseJob.php` has now been set to 1000.

<img width="1005" height="851" alt="Image" src="https://github.com/user-attachments/assets/216acd0b-9d50-447b-9814-eaacc37b7961" />

Failed jobs:

<img width="1051" height="900" alt="Image" src="https://github.com/user-attachments/assets/7b65888d-1a60-43b0-8f7e-8cf69696a43f" />

The query that seems to time out is this one:

<img width="1332" height="59" alt="Image" src="https://github.com/user-attachments/assets/a4a784bb-6309-4dad-8ae8-b60a9f5e4602" />

the detailed error message in the failed job are e.g. things like 

General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: insert into `region_mapping_tmp` (`country`, `fips`, `iso`) values (PY, 01, 10))

We're seeing MySQL CPU consumption of 200-300% when these jobs are running, and in this case this is the only installation on this server.   This upgrade has now essentially been running for 36 hours and once these remaining jobs fail for the third time we'll have to figure out some way to run the queries outside of the queue.  The client is fairly displeased with performance right now, despite this being temporary.

**Comment by bozana** [comment]
Hi @jnugent, one problem could maybe be that region_mapping_tmp is not cleared when a job fails, so it grows and grows, which then would lead to further jobs to fail. Could you maybe double check what is in that table? (That table should always be filled with the entries for only one country when the job starts and then cleared at the end of the job.)
Also, are those jobs run in parallel? I am wondering why that Lock wait timeout happens... 🤔 
Would there be a possibility for you to clear the region_mapping_tmp table and try to run only one job, to see if that would work?
Maybe also double check that no process currently locks the table... 🤔 Maybe this happens because one job that failed is locking the table, so the other are failing because of that -- the other are not even able to write the country codes into that table...

**Comment by jnugent** [comment]
Hi @bozana the processes are not running in parallel.  The jobs queue tries to run these one at a time.  
How do I just run a single one of these jobs?  I've truncated the _tmp table which had 7000 records in it.

The problem is that after the upgrade completes and we bring the site back online (which causes the jobs to queue and run) the site is now live and getting a lot of traffic.

**Comment by bozana** [comment]
Hi @jnugent, if I understand correctly the site is now online/in production, correct?
Have in the meantime all those jobs failed?
I thought: to clear the table region_mapping_tmp, to make sure no old process is locking that table, and then to do "Try Again" for only one such failed job. But it would be good to try it when no other such a job is in the queue -- if all of them are now failed. And maybe also in a time when there is not that much traffic.
If not all jobs are failed, maybe to see what will happen now with those still queued, after you cleared the tmp table (and assuming no old process is blocking anything).
Is there a temporary index on the columns country and region in the tables metrics_submission_geo_daily and metrics_submission_geo_monthly (created here: https://github.com/pkp/pkp-lib/blob/stable-3_4_0/classes/migration/upgrade/v3_4_0/I8866_DispatchRegionCodesFixingJobs.php#L45 (and removed after all those jobs have successfully finished))?

EDIT: the tmp table should have always a few entries, maybe max around 100 - 200

**Comment by jnugent** [comment]
Hi @bozana yes, all of these jobs have failed and the site is now in production.  It has been in production for nearly two weeks now.

I cleared the _tmp table and rescheduled one of the tasks but it now fails immediately with

```
2025-08-26 14:41:57][8334] Processing: PKP\migration\upgrade\v3_4_0\jobs\FixRegionCodes
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'usage_events_20230911.log-1-1279-KH-11-Phnom Penh-2023-09-11' for key 'metrics_submission_geo_daily.msgd_uc_load_context_submission_c_r_c_date' in www/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:545
```

**Comment by bozana** [comment]
Hi @jnugent, oh, it seems the jobs actually cannot be processed more then once, because it could happen that some entries are already replaced and some are not :-( For KH, for example, s. lib/pkp/lib/regionMapping.php:
  'KH' => [
    '02' => '3',
    '03' => '4',
    '04' => '5',
    '05' => '6',
    '07' => '8',
    '08' => '9',
    '09' => '10',
    '10' => '11',
    '12' => '15',
    '13' => '13',
    '14' => '14',
    '17' => '19',
    '18' => '20',
    '19' => '21',
    '21' => '7',
    '22' => '12',
    '23' => '16',
    '24' => '17',
    '25' => '1',
    '26' => '23',
    '27' => '22',
    '28' => '18',
    '29' => '2',
    '30' => '24',
    '31' => '25',
  ],

09 could be replaces by 10. If then the job fails, and is then re-tried again, the 10 will be tried to be replaced by 11, which in this case is not correct.
It seems all these countries contain such a 'recursive' codes: 
BH
BT
CG
CU
CY
CZ
DO
DZ
FI
FJ
HR
IR
JM
JP
KE
KH
KP
LC
LT
MK
MM
MT
MY
NO
PA
PT
PY
SA
SC
TH
TN
TO
TR
TZ
UA
VN

hmmm... 
So, it seems to me, that then the only possibility to fix it is to take the old DB dump on another, test system, to apply the migration script and run the jobs there, and then to replace the old entries in the current production system with those that are fixed in the test system :-( 
Eventually, it could be tried to fix the other countries -- that would work -- in the production system, but it seems easier and cleaner to just fix all the old entries on a test system and then replace all of them in the current system.

For the code, I could add that those jobs should be executed only once and if they fail, not to try to execute them again. Also, I can clear the tmp table also at the beginning of each job -- in case the previous job failed and the tmp table has not been cleared.
I am not sure if it is worth to try to separate the jobs even further, e.g. to separate them first somehow by number of lines and then also by countries... 🤔 
Would there be other huge installations that use region codes to upgrade?

Do you maybe have another idea and/or suggestion?

🤔

**Comment by jnugent** [comment]
Hi @bozana the issue here then becomes that if any of these jobs fail even once, they will automatically be re-queued to run again, up to a maximum of three times before needing to be manually re-queued by an admin.  This suggests that if even one out of the 100 or so jobs fails even once, the data becomes corrupt when that task tries to run again.

This is a problematic scenario for any OJS installation hosted in an environment where users are either not technical or do not have access or the ability to create test systems.  What does this migration change within the database? 

We have a large number of sites now looking to upgrade to 3.4 and 3.5, many with millions of records within the metrics tables. We've also completed at least a dozen large sites now, some many months ago, that may now have incorrect data.  We may also find ourselves receiving migrations already on 3.4 who may have incorrect data and no longer possess old copies of their 3.3 database.

**Comment by jonasraoni** [comment]
I think this condition is also possible, right?
- Upgrade jobs failed
- New records were inserted into the table with the right IDs
- Jobs are retried
- Right IDs are turned into wrong IDs

**Comment by jnugent** [comment]
@jonasraoni yes, if the jobs are retried after a new usage stats file was processed.

**Comment by jonasraoni** [comment]
If what I wrote before is a possible condition, then I think these actions shouldn't be executed as post-upgrade jobs. Moving the code out of the job would also handle the problem (i.e. the upgrade would fail and would need to be retried).

Otherwise... I think it might be ok to keep it as a post-upgrade job, to speed up the upgrade process (but as it's important, its failure should lead to a notification for the sysadmin). Covering the `foreach` of the job with a transaction should address the `recursivity` problem you've mentioned (i.e. all of them will either work or fail).

How many records might be affected on these updates? If the number is unknown, another thing that we need to start doing is to avoid such large updates (e.g. UPDATE submissions SET x = y` seems to be simple, but if the table has millions of records it will create problems), they might timeout or exhaust server resources. We need to chunk the updates.

About the broken data in production, I hope these region codes are not that important, as things will be a bit messed up and difficult (not worth?!) to fix properly without a backup.

**Comment by jnugent** [comment]
Thinking a bit about how to fix this if these records are important, I came up with

1. Re-run the upgrade for the last backup of the 3.3 install.  
2. Run the tasks to fix the region codes
3. Since the live site has been collecting data this whole time, we'd have to replace the metrics in the live site with what is now in the test upgrade and re-process any accumulated usage stats logs since the live site was originally upgraded.
4.  This may be tricky since I believe the new usage stats system processes a month at a time.  In 3.3 you could just move one log file to the staging directory and reload it.  Since it is unlikely that the live site was upgraded at the beginning or end of a month, some logs from 3.3 would need to be converted to the 3.4 format before being reprocessed.

**Comment by bozana** [comment]
Phew... 🙈 🙈 🙈 🙈 🙈 🙈 🙈 🙈 🙈 🙈 
Sorry for all this :-(
The sites already migrated that have no backup cannot be repaired any more.
The wrong entries are for the old data (coming from an older release) and for one next day (after the upgrade) or so, if the jobs have failed and re-tried -- the jobs do not run for a long time, I think.
So yes, the steps that @jnugent listed would be correct, except that log reprocessing would be needed 'only' for the first few days (for the actual installation from this month) or the first month (for older upgrades) after the upgrade happened, if they were not manually re-tried.

**Comment by bozana** [comment]
Now I am not sure what is the best solution in general: it seems these actions should not be in jobs -- even if they are not automatically tried to be re-run after they failed once -- because a user could manually re-run them.
Maybe, as actually first thought, they could be applied manually by admins after the upgrade, if needed. But how to inform the users/admins that they would need to run the scripts directly after the upgrade, so that they for sure know about it and do it?

**Comment by bozana** [comment]
@jonasraoni, I am not sure if I understand this correctly: "Covering the foreach of the job with a transaction should address the recursivity problem you've mentioned (i.e. all of them will either work or fail).". The recursivity is currently within one job, withing one country. So if one job fails, it does not matter for the next job -- only that same job should not be re-run again. Or do you mean to have something like a DB transaction, so that if the job fails nothing is committed/applied to the DB? 🤔 If this would be possible, then maybe the actions could stay as jobs... 🤔 Does transactions/rollbacks work on such a huge tables?

**Comment by bozana** [comment]
Hmmm... It seems to me that we actually need some kind of marks, so that we know what has been already updated and what still needs to be updated. Else, jobs as well as post-upgrade script could lead to the same problem.
E.g. to have a prefix inserted for the region codes that needs to be fixed... 🤔 
So maybe solution with jobs, but first adding a prefix to the region codes that needs to be fixed, and doing updates in chunks would be a good solution? Having that prefix would solve that 'recursion' problem. And doing updates in chunks would solve time out problem. And the jobs could be re-tried again.
How could I best do that chunk update, do you have a suggestion? -- Oh, I see the tables have ids, so I could use them...
