### ISSUE TITLE
Not possible to edit rich text fields (TinyMCE) such as submission title and abstract

### ISSUE THREAD

**Issue by saalam** [pkp/pkp-lib#8901]
**Describe the bug**
Title Field is locked and can't type anything when I try to insert title 
**To Reproduce**
1. Go to 'Submissions'
2. Click on 'New Submission'
3. Scroll down to 'Title'

**What application are you using?**
 OJS version 3.4.0 PHP version 8.0.28

**Additional information**
![image](https://user-images.githubusercontent.com/16186009/230697010-446d74e3-3560-47bf-9aa3-070818eb5051.png)

**Comment by Vitaliy-1** [comment]
Hi @saalam,

Are there any related errors in the browser console?

**Comment by NateWr** [comment]
Yes, I strongly suspect this is a problem with the TinyMCE editor. It could be the built JavaScript in the release package or something. The error will most likely be detectable through an error in the browser's console.

There are several related issues. I'm going to keep this and close the others.

**Comment by saalam** [comment]
Hi @Vitaliy-1 To be honest I went through only PHP error log and I saw nothing about it in the error log file. 
Hi @NateWr Regarding your question I'm using  Windows OS with Chrome Browser.

**Comment by NateWr** [comment]
Looks like this is a build error. @asmecher I didn't realize that `lib/ui-library` was excluded from the release package. With the latest updates to TinyMCE, I chose to house some files in `lib/ui-library/public/styles/tinymce/` to prevent duplication.

In hindsight, the decision to exclude `lib/ui-library` from the release package seems more sensible. In the PRs below, I've added a step to webpack so that it will copy the files from the tinymce directory in ui-library into `lib/pkp/styles/tinymce`. Then the applications load them from there, rather than the UI Library.

This fixed the problem for me, but can you test a release package?

One last decision to be made: these files will be copied whenever someone runs `npm run dev` or `npm run build`. In my view, these are build files, so we shouldn't commit them. That way they are always built from the correct branch of `lib/ui-library`. If you're happy with that (rather than committing them), let me know and I'll add this directory to the `.gitignore` file for each app.

PRs:
https://github.com/pkp/pkp-lib/pull/8904
https://github.com/pkp/ojs/pull/3871
https://github.com/pkp/omp/pull/1388
https://github.com/pkp/ops/pull/512

**Comment by asmecher** [comment]
@NateWr, those are sensible decisions. If you're ready to merge these, please go ahead; I'll build a new RC3 package and test it manually before making it available.
