### ISSUE TITLE
Missing Email Templates related localisations in OMP

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8911]
**Describe the bug**
Warning during OMP upgrade regarding missing locale keys
```
[migration: APP\migration\upgrade\v3_4_0\I5716_EmailTemplateAssignments]
Missing locale key "mailable.decision.reviewAck.name" for the locale "en"
Missing locale key "mailable.layoutComplete.name" for the locale "en"
Missing locale key "emails.editorAssignReview.body" for the locale "en"
Missing locale key "emails.editorAssignProduction.body" for the locale "en"
```

**To Reproduce**
Run an upgrade to 3.4

**What application are you using?**
OMP 3.4

**Additional information**
`mailable.decision.reviewAck.name` was renamed to `mailable.reviewAcknowledgement.name`
`mailable.layoutComplete.name` missing during refactoring  
`emails.editorAssignReview.body` and `emails.editorAssignProduction.body` were introduced after dividing `EDITOR_ASSIGN` template into 3 depending on a submission's stage

**Comment by Vitaliy-1** [comment]
The last 2 localizations were commented in this commit: https://github.com/pkp/omp/commit/3bcd14e06cc22367cecae0210fb6834a79c98991#diff-9edf1d1e74f0af64c9ee7152c7a234f90cbe3fd874ca897dfae22240eb5d48d5 (at the end of `email.po`). @asmecher, was this done deliberately?

**Comment by asmecher** [comment]
@Vitaliy-1, thanks -- not sure what happened on that commit, but it was put together by the summit tools. I'll watch closely next time I run those to see if I can track it down. Meanwhile, I've merged your PR and uncommented some of the commented translations in other locales; please let me know if I jumped the gun on this, otherwise I'll close the issue.
