### ISSUE TITLE
Remove deprecated fields

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9039]
**Describe the bug**
- The commit https://github.com/pkp/pkp-lib/commit/d8f65209a582465a191624d38ebff3980ff597a9 ended up cancelling the removal of two fields: 
  - `user_settings.assoc_id`
  - `user_settings.assoc_type`

  It's needed to recover this behavior, but extra care should be taken when doing it: The update must be done after the migration that recreate indexes, because these fields used to be part of an index (and removing a field that has dependencies might fail).

- The field `review_assignments.reviewer_file_id`, which should probably become a foreign key if kept, isn't referenced nowhere in the code.

- On OMP there's a `publication_formats.submission_id` which has been deprecated at the OJS 2 upgrade.

**What application are you using?**
OJS 3.4.0rc3

**Additional information**
Source: https://github.com/pkp/pkp-lib/issues/8929

**Comment by asmecher** [comment]
PRs:
- https://github.com/pkp/pkp-lib/pull/9051
- https://github.com/pkp/ojs/pull/3931
- https://github.com/pkp/omp/pull/1415
- https://github.com/pkp/ops/pull/536

I have just [one comment on the OMP PR](https://github.com/pkp/omp/pull/1415#discussion_r1213740277), otherwise they all look fine, thanks!
