### ISSUE TITLE
OJS 3.0b2: Creating New Journals Hangs

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#904]
When creating new journals, I find that after hitting save, the page hangs...

Getting out requires hitting 'cancel'. However, if you refresh the page, it turns out that you have successfully created a new journal.

Refer to this screencast to see what I did: https://youtu.be/PmwPVoNq9iE

**Comment by asmecher** [comment]
Hi @nmpx -- were you able to track down the PHP error log? That probably contains something relevant.

**Comment by nmpx** [comment]
Subsequent attempts to reproduce the error aren't panning out. Closing issue.

**Comment by martinpub** [comment]
I'm experiencing the same issue, but with OJS 3.1.0. There is nothing in the PHP error log ...

Happy for further advice on how to troubleshoot.

**Comment by martinpub** [comment]
Update: this also happens when trying to save/close any upload dialog on [journal_root]/management/settings/website. Any ideas @asmecher?

**Comment by asmecher** [comment]
@martinpub, something should definitely be appearing in the PHP error log for this; are you sure you're checking the right log?

**Comment by martinpub** [comment]
@asmecher, I managed to identify the error through Firebug, and it was a permissions issue, apparently the web server didn't have writing permissions to public/.

**Comment by asmecher** [comment]
OK, glad to hear it's resolved!

**Comment by asmecher** [comment]
(I suspect you have PHP error messages configured to go to the browser rather than the log -- I'd suggest sending messages to the log only. Check your php.ini.)

**Comment by martinpub** [comment]
Thanks @asmecher! (In php.ini, I have "error_log = /tmp/php_errors.log", however I see now that I have "html_errors = On" too, are they conflicting? log_errors is "On".)

**Comment by asmecher** [comment]
Typically `display_errors` should be `Off`,
`error_reporting` would be `E_ALL & ~E_DEPRECATED & ~E_STRICT` or similar,
`html_errors` would be `On`,
`log_errors` would be `On`, and
`error_log` would be a filename or `syslog`.

If you were seeing PHP errors through firebug, then `display_errors` was probably set to On; OTOH your errors should have been getting logged in `/tmp/php_errors.log`, but it's better to send them there only rather than through the browser where they can interfere with AJAX requests and potentially reveal sensitive information about your server.

Don't forget that you may need to restart your web server process after adjusting these, depending on your SAPI.

**Comment by martinpub** [comment]
Thanks @asmecher!
