### ISSUE TITLE
OJS 3.0b2: UI problem with 'switch journals'

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#910]
When in the administrative backend, there is an option in the left sidebar to 'switch journals' (which I think is a great idea, btw). 

I guess my problem with how this works is that it takes you to the front page of the journal, rather than the dashboard. I find this behaviour counter-intuitive.

Expected behaviour: that switching journals in the admin backend would take you to the dashboard of the selected journal.

**Comment by nmpx** [comment]
Update: Also just noticed that the menu, if you have too many journals, that it only shows four with no discernible way to access the other journals.

**Comment by asmecher** [comment]
@NateWr, the "Switch Journals" sidebar extends below the bottom of the screen when the list of journals is long.

As for having it take users between similar pages on different journals, we'd need to consider cases where the user doesn't have access to that area, which will be common. I'd suggest always presenting the list of journals, but if the user doesn't have access, the resulting page bounces them somewhere logical. This would mean adding a URL parameter or something so that the normal behavior for an "access denied" page -- which is good behavior in most cases -- doesn't apply here.

**Comment by NateWr** [comment]
I've updated the *Switch Journals* link ([commit](https://github.com/NateWr/pkp-lib/commit/b482eb6ad9994f021f1429a350e77d5968f2fe62)) so that it points to the backend dashboard on each journal's site. That makes more sense so we're not switching backend-to-frontend.

Working on the links opening off-canvas now.

**Comment by NateWr** [comment]
[Now](https://github.com/NateWr/pkp-lib/commit/705a6451b7eabe84805c1433600eee4262c9af16) menus won't stray off-screen. Woot!

![long-nav-menus](https://cloud.githubusercontent.com/assets/2306629/11662403/5abdd5e6-9dce-11e5-8ec6-a2004d8a4848.gif)

**Comment by NateWr** [comment]
[PR here](https://github.com/pkp/pkp-lib/pull/951)
