### ISSUE TITLE
Typo in ReviewAssignmentFileWritePolicy which permits managers file access when assigned to a submission

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9131]
**Describe the bug**
See https://github.com/pkp/pkp-lib/blob/abe282d110b5cd32f78d13e30b0f4af54932fabc/classes/security/authorization/ReviewAssignmentFileWritePolicy.php#L85
```php
if (empty($stageAssignments)...
```
Should be replaced with
```php
if (empty($assignedStages)...
```

As `stageAssignment` variable is always empty, I'm assuming that admin/managers have access to files even if assigned in a lower-level roles.

**To Reproduce**
1. Create a user and assign roles of journal editor and layout editor
2. Make a submission and it to the review stage, assign a reviewer and make a decision on it
3. Pass submission to the production stage and assign a user created in a step 1 as a layout editor
4. log in as this user, go to the review stage, click on Review Details and upload a file

Expected behaviour - the user shouldn't have access either for review file upload, nor to all other stages except production

**What application are you using?**
 OJS, OMP  from version stable 3.3.0

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib main: https://github.com/pkp/pkp-lib/pull/9135
tests: https://github.com/pkp/ojs/pull/3963

Requires porting to stable branches

**Comment by Vitaliy-1** [comment]
@asmecher, can you take a look at this PR. I've applied here a general solution to the issue with dual assigned users with manager roles and related bugs. This solves also following issues:
https://github.com/pkp/pkp-lib/issues/9127
https://github.com/pkp/pkp-lib/issues/9104
And likely other related problems, e.g., described here: https://github.com/pkp/pkp-lib/issues/9104#issuecomment-1604571431

**Comment by asmecher** [comment]
@Vitaliy-1, rather than coding to `main` and then back-porting to `stable-3_4_0` and `stable-3_3_0`, could you first code to `stable-3_4_0` and (when ready) forward-port from there? That'll help reduce the chances of a regression on a stable branch, plus I'd like to run the proposal past both @ajnyga (who worked on the original multiple-assignment logic) and the PKP|PS team (who have been encountering problems) for validation; they'll be working with `stable-3_3_0` installs.

**Comment by asmecher** [comment]
@ajnyga, would you mind reviewing the PRs against `stable-3_3_0` linked [here](https://github.com/pkp/pkp-lib/issues/9131#issuecomment-1624174708)? As @Vitaliy-1 [notes](https://github.com/pkp/pkp-lib/issues/9131#issuecomment-1624193003), this resolves pkp/pkp-lib#9131, https://github.com/pkp/pkp-lib/issues/9127, and https://github.com/pkp/pkp-lib/issues/9104. Tagging you because you're familiar with the interlocks for users who are active in multiple roles on a submission/context.

@mfelczak, if the hosting team could give the linked PRs a crack against the use cases they've had raised, that would help validate the logic behind the change!

**Comment by jnugent** [comment]
Hi @asmecher @Vitaliy-1 @mfelczak @librariam  I've applied this PR to 3.3.0.16 install and I *think* things are working correctly.  Is this the intended workflow?

1.  A user who has JM and JE and PE roles but is not assigned to a submission attempts to e.g. unpublish it.  They receive a "you do not have access to that stage of the workflow"
2.  Because they are a JM and JE, they can assign themselves to the submission as a JE. 
3.  Once added as a JE, they can unpublish/republish the submission.  This works even if they have the PE role.

Does this sound right to everyone?  If so, it's probably good to go.

**Comment by librariam** [comment]
@jnugent sorry I'm confused. Is this related to #9104 ? 
There the issue was that pre-3.3.0.14 a JM/JE/PE was able to make publication changes without being assigned. Assigning them is how the "you don't have access" issue is currently fixed, so at least in that aspect what you're describing doesn't appear to be a change...

**Comment by jnugent** [comment]
hi @librariam I think there was another issue where even if you were assigned as a JE, you couldn't do anything in a publication if you had a lesser role for your user account?  The test here is that I was able to assign a JE and do things to a submission even though I had a production editor role too.

**Comment by librariam** [comment]
@jnugent No, the lesser role only interferes when a JE is unassigned. So the current solution is either to assign the JE to a submission as a JE (no need to remove lesser roles) OR to keep the JE unassigned and remove the lesser role and then they get full access.

**Comment by jnugent** [comment]
@librariam  ah, right!  thank you!

**Comment by Vitaliy-1** [comment]
> A user who has JM and JE and PE roles but is not assigned to a submission attempts to e.g. unpublish it. They receive a "you do not have access to that stage of the workflow"

@jnugent, does the PR changes this behaviour or is it something that is present in stable 3.3.0 and should be addressed also?

**Comment by Vitaliy-1** [comment]
This looks like related issue with manager with dual role of section editor, but in scenario assigned as a section editor: https://github.com/pkp/pkp-lib/issues/6875

**Comment by Vitaliy-1** [comment]
Looking closer at it, this issue is a regression caused by the fix of for #6875. Nate gives a detailed explanation in [this comment](https://github.com/pkp/pkp-lib/issues/6875#issuecomment-1387294977). Unfortunately, fixing this for managers with dual role as a section editor assigned to the submission, introduces the same problem for managers with section editor role NOT assigned to the submission...

**Comment by Vitaliy-1** [comment]
Besides this one, the PR fixes also the following issues related to managers with additional roles:

- https://github.com/pkp/pkp-lib/issues/9127
- https://github.com/pkp/pkp-lib/issues/9104
- And the regression from https://github.com/pkp/pkp-lib/issues/6875, where managers with lower-level role, e.g., section editor, not assigned to the submission unable to conduct publication related actions.

@ajnyga, do you have an opportunity to look at the PR?

**Comment by ajnyga** [comment]
oh man this permission stuff makes my head spin, but I will give it a go

**Comment by Vitaliy-1** [comment]
Thanks! Merged
