### ISSUE TITLE
[Beacon] Missing uniqueSiteId on new installations

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9136]
**Describe the bug**
The `uniqueSiteId`, which is used for disambiguation purposes on the Beacon, comes from the `UsageEventPlugin`.
The statistics code, which used to be centralized on this plugin, suffered a major rewrite in the latest release, and the code which sets the `uniqueSiteId` is probably unreachable by now.

On a sidenote, is the `UsageEventPlugin` plugin even needed at this point?

**Solution:**
- The Beacon must be updated to accept an empty installation ID and any requirement over this ID must be relaxed in order to avoid losing input.
- Migrate existing `uniqueSiteId` settings to the `site_settings` table.
- Implement its retrieval through a getter (`Application::getGUID()`?!), which should set a new value if empty.
- Old values must be kept unchanged, new ones can make use of the `PKPString::generateUUID()` (and close this discussion: https://github.com/pkp/pkp-lib/discussions/7988).
- Given the Beacon is a global setting, inspect the feasibility of forwarding also the OAI URL for the whole installation.
- We have indirect dependencies over the package `ramsey/uuid`, we can promote it to a direct dependency, and call it at the `PKPString::generateUUID()` to get rid of some code.

**To Reproduce**
1. Access a fresh installation installed from zero
2. Create a context
3. Run the query `SELECT * FROM plugin_settings WHERE setting_name = 'uniqueSiteId'`
4. There will be an empty `uniqueSiteId` setting (which comes from the `version.xml`).

**What application are you using?**
OJS 3.4.0-1

<hr>

PRs:

stable-3_4_0:
- https://github.com/pkp/pkp-lib/pull/9229 
- https://github.com/pkp/ojs/pull/4005
- https://github.com/pkp/omp/pull/1442
- https://github.com/pkp/ops/pull/556

main:
- https://github.com/pkp/pkp-lib/pull/9232
- https://github.com/pkp/ojs/pull/4007
- https://github.com/pkp/omp/pull/1443
- https://github.com/pkp/ops/pull/557

**Comment by asmecher** [comment]
@bozana, could you have a look at this? Essentially we used to have a site setting called `uniqueSiteId` that was used to disambiguate installations for stats purposes, but was also provided to the beacon to help with disambiguation there. It's no longer showing up with the beacon since the stats rewrite happened.

**Comment by bozana** [comment]
Hi all, the `uniqueSiteId` is provided by UsageEventPlugin, that I have not changed at all. Thus, I'll try to figure out what is happening with that...

**Comment by bozana** [comment]
Oh, yes, I see... that ID was created only when an usage event is built and this was only happening when UsageStatsPlugin called it... So, because UsageEventPlugin is not used any more this `uniqueSiteId` could and maybe should be created somewhere else. (I see the UsageEventPlugin as deprecated -- only there if used by some other external plugin -- thus maybe at some point we can remove it.)
I agree to the points @jonasraoni listed above - how to create, store and retrieve the site ID. Maybe to already create it during the installation? 
The two last points from Jonas I do not understand completely i.e. someone else (@asmecher) would need to decide it... 
I can gladly work on it, just let me know...

**Comment by bozana** [comment]
Hihihihi... :-) I see I am assigned to this issue, so yes I will work on it... :-)

**Comment by bozana** [comment]
@jonasraoni, could you please review the PRs above? I assume nothing differently expects me in OMP and OPS, so when these changes are OK, I will add OMP and OPS PR. 
If the library should be used maybe @asmecher can decide... I assume this can then also happen later...? It would then be used instead of PKPString::generateUUID, right?

**Comment by jonasraoni** [comment]
Yeah, about the package, it can be done later :)

**Comment by asmecher** [comment]
Agreed, let's fix the missing ID and consider the package or another approach in the discussion separately. :+1:
