### ISSUE TITLE
Inconsistent seq values in database affecting journals ordering 

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9191]
**Describe the bug**
When new Journal is added, ordering gets recalculated incorrectly.

**To Reproduce**
If I create consequently 4 journals. They will have following values in `seq` column in the `journals` table:
```
1
1
3
3
```

Expected is
```
1
2
3
4
```

After reordering - it creates correct seq values. But goes wrong again after adding new journal.

**What application are you using?**
OJS 3.4

**Comment by asmecher** [comment]
(Added to the 3.3.0-18 milestone, but the issue hasn't yet been replicated there.)

**Comment by taslangraham** [comment]
I've reproduced the inconsistent ordering on OJS.3.3, with a slight difference in ordering. After creating 4 consecutive records, they have the following values in the `seq` column in the `journals` table:
3
3
1
1

**Comment by jonasraoni** [comment]
Another relevant comment is that such type operation should be atomic, especially now that we support APIs and people might call them in parallel. We can't grab a "last ID", then do further operations assuming that the database still has the same state.

**Comment by asmecher** [comment]
@jonasraoni, true, but note that this isn't an ID column -- it's a sequence column. We never get values by sequence, we only use it for ordering, so the impact of a collision would just be that two items will jostle for position until a resequencing happens.

@taslangraham, not that it's any better, but we do have an existing pattern you could follow in order to stay consistent; see:

https://github.com/pkp/pkp-lib/blob/87db0786c680408d0dab0ccc56e6e750f159e748/controllers/grid/settings/category/form/CategoryForm.inc.php#L244..L246

I'd suggest following that pattern for `stable-3_3_0` (and probably `stable-3_4_0`); if you'd like to follow a different pattern for `main`, feel free to propose something -- but be prepared to have to apply it to a few spots in the codebase :)

**Comment by asmecher** [comment]
(In fact, there already is a `resequence` function for this purpose in `lib/pkp/classes/context/ContextDAO.php` in `ojs-main`, and `.inc.php` in `stable-3_3_0`.)

**Comment by jonasraoni** [comment]
No worries, just offering some ideas to improve, it's also possible to avoid the resequencing (I've shared a link with Erik) 😁

**Comment by jardakotesovec** [comment]
Did not expect this issue to get so much attention :-D

**Comment by asmecher** [comment]
@jonasraoni, I am open to new patterns on this -- what's the link you shared with Erik?

**Comment by taslangraham** [comment]
In the mean time, I've opened a PR for this
PR - https://github.com/pkp/pkp-lib/pull/10047

Description
- Sets the `seq` value when creating the Context.
- Updated the `resequence` method to fix two issues I observed:
   - The `seq` was being incremented by 2
   - Every other record was skipped during resequencing.

**Comment by asmecher** [comment]
Thanks, @taslangraham! I've merged your PR for `stable-3_3_0`; would you mind forward-porting to `stable-3_4_0` and `main`?

**Comment by taslangraham** [comment]
@asmecher sure thing!

**Comment by asmecher** [comment]
All merged -- thanks, @taslangraham!
