### ISSUE TITLE
Invitations backoffice support added

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#9197]
**Describe the feature**
By extending the `access keys` schema and functionality, we should add a new feature that allows users to get custom/specific invitations which will be resolved using a common back-office flow, but having specific accept/decline invitation functions.    

----------

**PRs**
PKP-LIB: #9200
OJS: pkp/ojs#3992
OMP: pkp/omp#1454
OPS: pkp/ops#566

**Comment by defstat** [comment]
@asmecher I added the working PRs [here](https://github.com/pkp/pkp-lib/issues/9197#issue-1828637326). Those PRs contain the following:

1. Change `AccessKey` infrastructure and backoffice to support `Invitations`
2. Remove `AccessKey`, `AccessKeyDAO`, `AccessKeyManager` in favor of the Invitations infrastructure/backoffice
3. Add Migrations and backward compatibility

**Comment by asmecher** [comment]
@defstat, I've been working on a few changes that might better illustrate what I was suggesting...
- Split the migrations into separate install and upgrade; remove the old `access_keys` schema management:
  - https://github.com/asmecher/ojs/commit/737fce090b08ee9fa82f1a94604e7e407882219b
  - https://github.com/pkp/pkp-lib/commit/ee369fe3ce597572124e56e0845890c2b0aa9a22
- Rearrange the storage into `invitations` rather than `access_keys`: https://github.com/pkp/pkp-lib/commit/47e200ff5bde3a8a8173a42af2eb0ec1c81f441c
- Clean up some additional data that doesn't need to be in the payload: https://github.com/pkp/pkp-lib/commit/2f17754d2e959b4f7b5ab73237fc4468ad6bbe33
- Improve data access conventions; simplify storage/recreation of invitation: https://github.com/pkp/pkp-lib/commit/fbd3b4d66243559f80d6212569d19d75422ef155

I was hoping to get a little further on this tonight, but the next place I was going to look at was the relationship between the BaseInvitation (and subclasses) and Invitation Eloquent model. I see what you're saying about using the extensions of BaseInvitation as repository classes that handle the business logic, and keeping the Eloquent model for pure data storage -- I like that approach. I'd like to remove the aspects of the BaseInvitation that wander into data storage -- the use of attributes to form the payload, for example. I think a `getPayload()` function in the subclass would be a tidier way of doing this; you would be able to use member attributes without worrying about which do and don't get encoded into the payload for example.

**Comment by asmecher** [comment]
@defstat, I took a last spin through the PRs for general cleanup and found a few small issues. Please look those over, and then port to OMP and OPS as well. Then I think we'll be ready for merge!

**Comment by asmecher** [comment]
All merged -- thanks, @defstat! :fireworks:
