### ISSUE TITLE
UI Design Suggestions: Dashboard

### ISSUE THREAD

**Issue by willinsky** [pkp/pkp-lib#941]
- [x] “My Authored” might be better as third in this list. It is very much the least likely to be used, and hits one with this blank space that says you haven’t authored anything! Having Unassigned at the top is a reminder or reassurance that is in hand.
- [ ] I think we can title our pages with more precision. I’d propose “Editorial Dashboard” rather than generic dashboard, and as we have other dashboard-like pages. (I propose below to change the Editorial stage to the more precise Copyedit stage.) 
- [ ] ~~The second tab “Active” might be more clear as “All Active,” as Submissions certainly includes active submissions.~~ [DONE] In fact, I’d suggest -- because the first three tabs are all submission tabs -- the following (and because My Submissions includes those that are mine to assign):
		My Submissions    All Active    Archives    Catalog Management

![screen shot 2015-12-01 at 10 53 56 pm](https://cloud.githubusercontent.com/assets/10342108/11524287/75501f86-987e-11e5-973c-406121dec9ca.png)

- [x] Throughout the pointer > could be a tad larger in relation to the font size as, for me at least. it is barely perceptible.
- [ ] I like the use of gray file number tags used to identify file numbers, as the tags clearly speak to identification, and perhaps we can use a version of the tag in another color for the Submission ID, and then use the submission ID (or the last three digits, as the numbers grow larger) as part of the file idea.
- [x] The “Book Title” column title should perhaps be “Author; Book Title”
- [x] If it’s “15 of 22 items” (no capital on “items” please), how do we access the rest? #955

![screen shot 2015-12-01 at 10 57 35 pm](https://cloud.githubusercontent.com/assets/10342108/11524347/f23fce9c-987e-11e5-8e12-b96f8142352c.png)

**Comment by asmecher** [comment]
John, to your last point, if you scroll the list to the bottom, it should load more entries. (This is becoming a reasonably standard approach for accessing long lists in web apps.)

**Comment by willinsky** [comment]
Then perhaps it is not working, as I did scroll down to the bottom again to no effect.

**Comment by NateWr** [comment]
@willinsky Regarding “Editorial Dashboard”: what are the other dashboards we have?

**Comment by willinsky** [comment]
Yes, you are right, we have no other "Dashboard" per se. My thinking: we have "Website Settings," "Press Settings," etc., that refer to the domain to which they apply, while Dashboard does not. And they have tabs and settings, and look much like the dashboard, apart from the submissions. I understand that we have multiple settings and thus need to identify them further and only one dashboard, but what domain warrants a "dashboard" is not obviously editorial workflow.

**Comment by NateWr** [comment]
The size of the grid row toggle caret (>) was increased in 99beb0ca3807232042dfeb23e1a8d899ccb51dbe.

**Comment by NateWr** [comment]
I've filed a specific issue on the grid scroll-for-more stuff. #955.

**Comment by asmecher** [comment]
On "Dashboard" -- it's ambiguous whether this refers to the tabbed interface with the submission lists, or to the back-end homepage as a whole (with links to Administration, Setup, etc). To me, it applies to the whole backend homepage, which is more than the editorial tools. That's bolstered by the "Dashboard" link from front-end that you click to get there.

**Comment by NateWr** [comment]
Ok, so this touches on something that's been nagging me for a while. @willinsky and @asmecher, you're both right, I think, that there is some ambiguity around the "Dashboard". WordPress has the same ambiguity, where "dashboard" is commonly used to refer to the entire backend, but also represents a specific navigation item within the backend.

The difference for us, I think, is that our navigation item called dashboard is not just an overview. It's the only access point for all of our content management. I don't think I appreciated this when I scaffolded the initial redesign of the backend. As a result, we end up with only one item on the primary navigation menu for almost all of our users.

![admin-dashboard-contexts](https://cloud.githubusercontent.com/assets/2306629/11781326/e5aeef64-a260-11e5-9d88-76b10cb655b7.png)

![admin-dashboard-empty-nav](https://cloud.githubusercontent.com/assets/2306629/11781330/ef05800a-a260-11e5-8ae5-70f1c1bea93a.png)

That's a lot of screen real estate for a navigation menu that really only operate as a "home" button (assuming we found a different place for tasks to live).

WordPress has a global "admin bar" which I've been thinking about as a possible resolution to this "context" problem. The idea would be to have a context switcher up top which would both allow you to switch journal contexts as well as toggle between editorial/administrative contexts. Here's a quick illustration:

![context-view](https://cloud.githubusercontent.com/assets/2306629/11781396/82eb5970-a261-11e5-8df7-e3a4970c46b4.png)

I'm not sure that this really solves our problem, though, as we'd still have an empty primary navigation menu for most users most of the time (editorial mode). We could split out the dashboard items into top-level menu items then, which would give them more visibility.

![admin-bigger-menu](https://cloud.githubusercontent.com/assets/2306629/11781477/133e518a-a262-11e5-8ea1-d5f23c16c763.png)

But I'm not convinced this is really better than the tabbed approach we have now.

I've so far kept this all to myself because I've been hoping that I would hit on a great idea. I don't really have one yet, but I suspect it would take some re-thinking about the dashboard setup as we have it (submissions, active, archived, catalog/journal). And I don't think it's the right time to be doing that now that we're rushing towards 1.2/3.0.

So the short summary of my long post is that: a) I don't think the ambiguity is a critical problem that needs to be solved now and b) to the extent that the problem exists, I think it requires a more wide-ranging solution. We'll probably be better informed to find the right solution after users have really stress-tested our navigation patterns in every-day use and can give us more valuable feedback.

**Comment by beghelli** [comment]
@NateWr I like the suggestion you've made: move everything to the top. We tried to do like that previously, as you remember, but the way you did now it's much cleaner. 

Do you think we have the need for a side bar menu? The problem you pointed (the menu is not much useful to users, since they will almost click in one item only) is true, I agree. And it's much worst when that's always on the sidebar, taking up so much space for almost nothing.

Why not do what you did in you suggestion, but moving also the tasks to the top? So it would be something like: 

Tasks | Press switcher -> Editorial Dashboard - Administrative                                        view site   User

That way tasks could be global, and the other items context related. And we could get rid of the side bar, which would giving much more space for us to design the workflow pages (maybe even using a sidebar, but page related only.

**Comment by NateWr** [comment]
@beghelli Those are exactly the kind of ideas that have been bouncing around in my head since I mocked that up a couple hours ago. It's quite a drastic change, but it's definitely worth thinking about when we have some time after 3.0...

**Comment by NateWr** [comment]
@willinsky Bruno and I are taking another pass at the grids where you can scroll to load more items, to see if we can improve the problem you identified where it's not clear how to get more items. If you get a chance, can you take a look at the animated image in [this comment](https://github.com/pkp/pkp-lib/issues/955#issuecomment-164725499) and let us know if you think the new "Load more" link solves the problem?

**Comment by NateWr** [comment]
@willinsky PRs [here](https://github.com/pkp/pkp-lib/pull/971) and [here](https://github.com/pkp/omp/pull/182) address a few of the problems you identified:

- Submission grid column title switched from "Book Title" to "Author; Book Title".
- My Submissions moved to bottom of dashboard
- "Active" tab now called "All Active"

I'd like some more feedback before switching "Submissions" to "My Submissions". I'm a bit nervous it could be confusing to someone brand new to the system, who might skip past it looking for someone else's submission they've been assigned. But I'm not against the idea and I agree Submissions is a bit general considering what's in the other tabs. I'm wondering if something like "My Submission Queue" might be better?

This tab is really the only thing that plays the traditional role of a user dashboard of providing an overview of items-of-concern. But that just lands back on our general dashboard problem as already discussed.

**Comment by willinsky** [comment]
Agreed that My Submissions is ambiguous and like queue because it allows for "my authored" and for "unassigned."  Consider if only for a moment that if the page was designated the Editorial Dashboard or the Submissions Dashboard, then we could go with the tab: My Queue - All Active - Archive - Catalog Management. Catalog is a bit out of place, admittedly but it is the submissions catalog. (On the naming of the dashboard, it strikes me that we also manage users with a similar dashboard layout).

**Comment by NateWr** [comment]
Actually, I really like your idea of using the word Submissions. What if we dropped "Dashboard" altogether, since it seems to be the source of confusion?

You're right that everything in the current dashboard reflects submissions, except for Catalog in OMP and Issues in OJS. Let's take a look at those tabs:

![ojs-subtabs](https://cloud.githubusercontent.com/assets/2306629/11819475/ed6c5ed8-a357-11e5-9c58-2b1d71f39a9c.png)

![omp-subtabs](https://cloud.githubusercontent.com/assets/2306629/11819476/ed794f44-a357-11e5-934e-9dc3e598967c.png)

This makes me think that these tabs are just begging to be split out into their own screen (I think I just heard Alec sobbing). We've got plenty of room in the main navigation menu on the left:

![ojs-expanded-menu](https://cloud.githubusercontent.com/assets/2306629/11819593/a50f2cb4-a358-11e5-845c-d6983ffbbca1.png)

![omp-expanded-menu](https://cloud.githubusercontent.com/assets/2306629/11819594/a5256b0a-a358-11e5-859e-32dd65559c3c.png)

Then the sub-tabs we have in the issues and catalog pages could be raised up to top-level tabs (only OJS example because OMP still needs lots of work):

![ojs-issues](https://cloud.githubusercontent.com/assets/2306629/11819636/d32c2296-a358-11e5-9eba-54bff3a0de1f.png)

This change strikes me as something that will help users find things in almost all cases, it solves large chunks of our problem with the "dashboard" terminology, and I don't think it'd be terribly difficult to implement.

Thoughts?

**Comment by beghelli** [comment]
@NateWr Issue management was already like you propose here, outside the dashboard and having it's own menu entry. But I think we decided to move them to the dashboard trying to centralize all editorial information there, so editors could use that as an start point to everything.

Tabs inside tabs is a problem spread throughout the system, but worst than having this is the feeling that we are trying to force content to stay together to justify the existence of a concept like the dashboard. As we are experiencing now, this concept doesn't clarify much things for users and we are having a hard time to adjust content on it.

Anyway, I like having the left side menu the way you designed in the last screenshot.

**Comment by willinsky** [comment]
Agreed with @NateWr and @beghelli. Drop dashboard by all means as I believe we're not using it consistently (re: users, for example). And while Catalog and Issues are all about the management of submissions, I do like the setting off of Submissions and Issues, as different levels of operation. The only thing is that journals are moving away from quarterly Issues (Numbers), and publishing articles continuously in Volumes, with a few using only the date and DOI and dropping Volume and Number. Which is only to say that this second level, after Submissions, needs to be configurable, with Issue, the default, Volume an option, and nothing an option as well.

**Comment by asmecher** [comment]
Scheduling this for OMP 1.2 while the discussion is so active. @NateWr, I'll let you take the lead on this, with @willinsky's guidance; let me know if you want me to jump in.

**Comment by asmecher** [comment]
@willinsky and @NateWr, just summarizing what's already been covered:

- Pretty much all the specifics are implemented in the original entry.
- There's some good dashboard revamping discussion but no conclusions yet.

Any objections if I file a new entry against OJS 3.0 (for now) to consider a dashboard revamp, referring to the conversation here, and close this issue?

**Comment by NateWr** [comment]
@asmecher I think we've already got the dashboard change filed at #985. Further considerations are in place with #987 and #986.

**Comment by asmecher** [comment]
Great, thanks -- closing this one.
