### ISSUE TITLE
Issues while updating OJS (db import) from version 3.2.1.2 to 3.3.0.15

### ISSUE THREAD

**Issue by SamJohnSocial129** [pkp/pkp-lib#9412]
We are updating our current OJS version 3.2.1.2 to 3.3.0.15. There is a huge difference between old and new ojs database tables. Manually changing table properties/columns requires a lot time and R&D.
Is there any way to update ojs without losing data?
Attache is OJS database difference between 3.2.1.2 and 3.3.0.15. (from old db to new)
[difference.txt](https://github.com/pkp/pkp-lib/files/12903739/difference.txt)

**Comment by jonasraoni** [comment]
Hi @SamJohnSocial129, you shouldn't be updating the database manually, the software has an upgrade process, see: https://docs.pkp.sfu.ca/dev/upgrade-guide/en/

I'll close this issue, because we're reserving GitHub for technical issues. If the link I provided isn't enough or if you've got other doubts, you can try to get more help at the forum: https://forum.pkp.sfu.ca/c/questions/5
