### ISSUE TITLE
[OMP] It's possible to assign DOIs to chapters without own landing page

### ISSUE THREAD

**Issue by nongenti** [pkp/pkp-lib#9468]
**Describe the bug**
If you assign DOIs to an submission, all chapters getting DOIs. Also those chapters, that have no landing page.

**To Reproduce**
1. Go to 'DOIs'
2. Choose a submission
3. Click on 'Bulk Actions'
4. Click on 'Assign DOIs'

**What application are you using?**
 OMP version 3.4.0

**Additional information**
This is critical in combination with the 'Automatic Deposit' functionality. Deposit chapters without landing page produces DOIs with dead links. It is possible to catch this cases in the registration agency plugins, but this wouldn't be transparent for users. So it shouldn't be possible to assign DOIs to chapters without own landing page. 

PRs:
stable-3_4_0: 
- https://github.com/pkp/ui-library/pull/384
- https://github.com/pkp/pkp-lib/pull/10212
- https://github.com/pkp/omp/pull/1622
- https://github.com/pkp/ojs/pull/4405 (only submodule update)
- https://github.com/pkp/ops/pull/753 (only submodule update)

main: 
- https://github.com/pkp/ui-library/pull/397
- https://github.com/pkp/pkp-lib/pull/10334
- https://github.com/pkp/omp/pull/1679
-

**Comment by bozana** [comment]
@ewhanson, could you take a look at this?

**Comment by bozana** [comment]
Hi @nongenti, 
Why do you not have a landing page for some chapters? Because the editor forgot it or for another reason?
Also, what registration agency do you use? How do you register the DOIs? We currently do not support any registration agency in OMP.
Would/could the solution be to register the chapter landing page URL and if there is no landing page then book landing page? Have you maybe spoken with your registration agency about it, if it would be possible?

**Comment by bozana** [comment]
Hi @nongenti, thanks a lot for the explanation!
Hmmm...
I see some difficulties there:
I think there are presses that use an older OMP version, that did not support chapter landing pages, and they have DOIs for chapters.
Earlier, we had a checkbox in the object form that would allow to exclude an object from getting a DOI. But in 3.4 we intentionally moved the whole DOI management at one place in the system, so that everything would needed to be done there, at one place -- thus, having a checkbox on the chapter form is not a solution, I think.
The chapter landing page can be selected/deselected also after DOI assignment to a submission. 
Differently to the possibility to select submissions that need to get DOIs assigned we do not have this possibility for subobjects, in this case chapters, which seems to be the problem. It seems to me that the actual feature we need it the possibility to mark what chapter need i.e. does not need a DOI.

Hmm... 
Let me discuss all this with @ewhanson. 
And lets also see if maybe other OMP DOI users would have a comment on this, based on their usage...

**Comment by nongenti** [comment]
I understand the problems. Maybe it could be a solution to add a second level of checkboxes. Then the user could select what needs a DOI and what not. 

![doi-form-1](https://github.com/pkp/pkp-lib/assets/78475910/e781887f-b4f5-41a9-b57e-8295ac3557fb)
![doi-form-2](https://github.com/pkp/pkp-lib/assets/78475910/7dac5d75-f67f-4df5-8a10-e858b33c4e91)

**Comment by nils-stefan-weiher** [comment]
Hi @bozana ,

did you find the time to discuss the issue with @ewhanson ?

Our colleagues regularly have issues using the new DOI assignment interface, because we can only assign DOIs for all subordinate items at once.

**Comment by bozana** [comment]
Hi @nils-stefan-weiher,
Yes, I think we decided to do it as you suggested -- to assign the DOIs only to the chapters that have a landing page and vice versa -- the chapters that has a DOI will automatically have a landing page.

**Comment by bozana** [comment]
Hi @nils-stefan-weiher, 
We haven't managed to do it till now, but will try to finish it till the next release 3.4.0.6...

**Comment by bozana** [comment]
@ewhanson, the PR above contains the minimal changes needed for this issue.
Currently all chapters are listed on the DOI management page regardless whether they have a landing page, however when using the Bulk action "Assign DOIs", the DOIs will be assigned only to the chapters with the landing page. 
The JM can manually edit a DOI for the chapter without the landing page. It is not a huge problem, because the landing page for a chapter with a DOI will be automatically considered and display -- also because the landing page chapter setting is a checkbox that could theoretically be deselect later, after a DOI has been assigned. 
Maybe a visual hint for the chapters without landing page on the DOI management page would be nice to have (also for the JM to know why DOIs are not assign to those chapters)? Would you have a suggestion for that? 
Or is there an easy way to disable the editing for the DOIs of the chapters without the landing page?
Or do you think it would be better not to list the chapters that neither have the landing page nor the DOI?
Any further suggestions are very welcome!
Thanks a lot!

**Comment by ewhanson** [comment]
@bozana, those are good questions...

I think the best option would be to either completely hide or disable editing for chapters without landing pages. I think both would roughly require the same amount of work since we'd need to pass that data to the front end in either case.

@Devika008, I'm curious what you think the best approach in a situation like this is: On the DOI assignment page for OMP, all chapters are currently included. We are planning on making it so only chapters that have a dedicated landing page for them can be assigned DOIs. Do you think it would be better to remove chapters without landing pages from the DOI assignment UI all together or would it be better to include the chapters without landing pages but disable DOI assignment/editing and include some other text/indicators as to why they cannot be edited?

Thanks!

**Comment by bozana** [comment]
Hi @ewhanson, I changed the DOIListPanel so that the chapters without landing page and without a DOI are not displayed at all. Could you please review the PRs above? I hope I have considered all relevant places in the code :thinking:

**Comment by Devika008** [comment]
Hello @ewhanson and @bozana 

If you ask me, the second option—showing the chapters without landing pages but disabling DOI assignment/editing and including text/indicators explaining why they can't be edited—is the best way forward.

This approach aligns with UX heuristic rules, which are design principles based on empirical and research-informed best practices. Two key rules are **Visibility of System Status** and **Recognition Rather than Recall**. These principles emphasize that the design should always keep users informed about what's going on through appropriate feedback and help users recognize information rather than recall it. By displaying the chapters and explaining why they are disabled, we can reduce the learning curve for users and streamline the process.

**Comment by bozana** [comment]
Thanks a lot @Devika008!
I will then try to disable the fields (instead of not displaying them at all). Thus, @ewhanson please wait with the second review :-)

**Comment by bozana** [comment]
Hi @ewhanson, I tried to disable the input fields for chapter DOIs when the chapter does not have a landing page and a DOI. Could you please review the PRs?
I added OMP specific function to the DoiListItem.vue. If you have other idea how to solve it I am glad to improve it. Also, if you have any suggestion about styling for the text explanation, I am glad to improve that too.
Thanks a lot!

**Comment by ewhanson** [comment]
Hi @bozana, I've had a look and aside from a few minor things, looks good! 👍

I also did some thinking about the presentation of the chapters that cannot be edited and wasn't sure what the beset approach would be. @Devika008, given the current state of things below, do you have any recommendations for displaying/drawing attention to this information?

The case is that only chapters with landing pages can have DOIs assigned to them. Per your recommendation, we've kept them in the list, but make them uneditable with a note indicating why. I've included a short screen recording of this state. Do you have any recommendations on how to make it clear which ones will be able to be edited vs not edited (all of the input fields are disabled while not editing so it's not obvious from that alone). Thanks!


https://github.com/user-attachments/assets/41119509-1e70-4a82-8e6e-13f7f270cbec

**Comment by bozana** [comment]
Thanks a lot @ewhanson!
I considered you comments. Could you please take another look into the ui-library PR? -- I moved the function containsDisabled() into the OMP specific file...
Else, lets see what @Devika008 says...

**Comment by Devika008** [comment]
Hi @bozana  and @eirikhanssen,

The screen recording looks great! Here are two suggestions to indicate that certain chapters can't be edited:

We could use the color #4E4F4F for the chapter name, as it’s our standard color for indicating something is disabled and uneditable.
2. Another option is to add a small tag (like the one in the attached image) next to or below the chapter name. We already use similar tags to indicate file types, so this could work well to show the chapter’s status too.
![image](https://github.com/user-attachments/assets/0065d513-3805-4086-86e1-6837c612c666)

**Comment by ewhanson** [comment]
@Devika008, I think both of those suggestions sound good! Though you probably meant to tag me 😅

**Comment by Devika008** [comment]
Hahahah yeah! those cold medications do a good number on one :p

**Comment by bozana** [comment]
Hi @ewhanson and @Devika008, if no objections I would use the color #4E4F4F for the chapter title -- it is a little bit easier for me and maybe less overloaded.
Here is how it now looks like:
![Screenshot from 2024-08-14 11-42-30](https://github.com/user-attachments/assets/39f90046-d9b9-4640-9559-f31404b480de)

OK so?

**Comment by ewhanson** [comment]
@bozana, looks good to me! 👍

**Comment by bozana** [comment]
Hi @ewhanson, could you please review my last commits where I adapted the tests. If OK and no objections, I would proceed and merge then...

**Comment by touhidurabir** [comment]
@bozana I have check and seems all ok to me . Seems there have been a detail review done on it already and all suggestions are considered . So I have approved the PRs .

**Comment by ewhanson** [comment]
All looks good to me, @bozana! It looks like the tests for OJS and OPS are failing, but it seems you traced that to a schema file throwing a 503 from Crossref. Assuming everything sorts it self out with that, I think it's ready for merge. I'm also guessing this should be forward-ported to `main` as well?

**Comment by bozana** [comment]
Yes, I need to port it to main too :-)
Thanks a lot!

**Comment by bozana** [comment]
Hi @ewhanson, I ported the changes to main. Would you like to take a look?

**Comment by bozana** [comment]
@ewhanson, I have also merged the changes for main, but, so that I can close the issue, so that a new 3.4.0.7 can be released... but I will consider all your comments later then...

**Comment by ewhanson** [comment]
Thanks @bozana. Everything on `main` looks good to me!

**Comment by bozana** [comment]
Hi @nils-stefan-weiher and @nongenti, I would love to hear more about your DataCite plugin for OMP. Are you already using it and are you maybe planing to provide it in the GitHub or plugin gallery for the others?
Thanks a lot!

**Comment by nongenti** [comment]
Hi @bozana,
yes we're using it since around one year and it  works well. Sometimes we got an issue that a DOI wasn't registered and reason was always that the jobs worker service was stopped. Restart this service solves this issue. The plugin provides DOIs for mongraphs, chapters, publication formats and files. We published it in Dulips datacite plugin repo.  
You can find it here: [https://github.com/withanage/datacite/tree/stable-3_4_0](https://github.com/withanage/datacite/tree/stable-3_4_0)

**Comment by bozana** [comment]
Thanks a lot @nongenti!
