### ISSUE TITLE
Bug in recommendByAuthor plugin - it returns whole statistics data instead of recommended articles in some cases

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [pkp/pkp-lib#9512]
**Describe the bug**
Here's the issue: When none of the authors of an article have been published previously, the recommendByAuthor plugin ends up showing all publications from the statistical data due to a bug in the code.

Take a look at this section of the code

https://github.com/pkp/ojs/blob/715d3e7fdee2a2e3430eee5dbb0b6b799e0ea81d/plugins/generic/recommendByAuthor/RecommendByAuthorPlugin.php#L118-L123

When empty `$results` are passed, the `getTotals` function retrieves all the data from statistics, failing to limit the result by the submission IDs - it seems like empty array is treated as `any`.

**What application are you using?**
OJS 3.4.0.3, plugin version: 1.0.0.1

**Comment by mariuszsienkiewicz** [comment]
If someone needs a fast fix then you could just fix it like that:

```php
if (!empty($results)) {
    // Order results by metric.
    $filters = [
        'contextIds' => [$displayedArticle->getData('contextId')],
        'submissionIds' => $results,
        'assocTypes' => [Application::ASSOC_TYPE_SUBMISSION, Application::ASSOC_TYPE_SUBMISSION_FILE]
    ];
    $statsReport = Services::get('publicationStats')->getTotals($filters);
} else {
    $statsReport = [];
}
```

**Comment by mariuszsienkiewicz** [comment]
@asmecher Thank you for addressing this issue. I have a question: do you have plans to modify the `Services::get('publicationStats')->getTotals($filters)` function in the future so that it doesn't return the entire dataset when `$results` is empty? I've noticed the changes made in the commit, but I'd like to make a comment on this. It appears that it might be more efficient not to execute `Services::get('publicationStats')->getTotals($filters)` when it isn't necessary. After all, what's the benefit of retrieving, for instance, 3,000 records from the database if we won't be using them? This approach seems detrimental in terms of performance and results in unnecessary heavy queries.

**Comment by asmecher** [comment]
@mariuszsienkiewicz, you're right, that would be a more efficient fix -- but I think this is only an issue that occurs when previewing an unpublished article, right? Only editors can do that, so the extra overhead won't really matter.

I opted for a quick/easy fix here because we already have better replacement patterns for the service classes that more cleanly account for the distinction between no filter being applied (`null`) and a filter with no candidates (`[]`). These are in the collector classes (e.g. https://github.com/pkp/pkp-lib/blob/main/classes/submission/Collector.php); see e.g. the use of strict tests in [this line of code](https://github.com/pkp/pkp-lib/blob/e4c79fcd08511142bb6be1d4143fed352a3f8e7f/classes/submission/Collector.php#L627). We'll be refactoring service classes (and other legacy DAO code) to the collector pattern over time.

**Comment by mariuszsienkiewicz** [comment]
@asmecher No, this issue occurs every time when none of the authors of the article have been published in the journal before. Our client sometimes encounters situations where they release an issue with articles featuring completely new contributors for the journal, and I was pointed out that some articles in the 'Most read articles by the same author(s)' section have over 150 pages of pagination 😅 so you probably see that it noticeably slows down the loading of this page. But this is just for your information.

Regarding refactoring, I'm really glad about it and I'm looking forward to when plugins will also start utilizing these methods. Thank you for sharing this information! 🫡

**Comment by asmecher** [comment]
@mariuszsienkiewicz, thanks, that makes sense. I've tweaked the above fix to move the fetch into the conditional. Thanks for the clear report!
