### ISSUE TITLE
Consider renaming "Discussions" in workflow

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#960]
The "Discussions" tool (primarily used for Copyediting and Proofreading processes but also appearing e.g. in Submission as a pre-review tool) could use a better name.

Suggestion from @willinsky: Prefix name of stage. "Copyediting Discussion"; "Production Discussion".

Suggestions from SI: Stage Management; Production Stage Management; Process Management; Procedure Management; Administration; Execution
("Management" and "Administration" would be problematic, since they're already used in other contexts.)

Also curious what Free University Berlin (@bozana?) and Heidelberg (@withanage) think.

**Comment by asmecher** [comment]
@NateWr, FYI, moved the discussion here.

Personally, I think @willinsky's suggestion is workable, but I think SI's issue was specifically with the word "Discussion", which would still be used.

**Comment by NateWr** [comment]
I never really understood the problem with Discussions, but since everyone who has looked at it has wanted something different I'm clearly wrong here. I suspect the problem is that people recognize fairly quickly that the discussions tool is going to be where they do a lot of the work.

@willinsky's suggestion makes the most sense to me.

Surely there's some fairly trivial way for people to change strings on a site-by-site basis?

**Comment by withanage** [comment]
Thanks @asmecher  for inclusion:

In the scientific advisory board, we were even asked , if we could even have the "discussions" section  without the other  omp backend ui elements.  So  e.g. professors, who want to  give an opinion on the book, can direclty log into the discussions sections.

I agree completely with @NateWr 
"discussions tool is going to be where they do a lot of the work."
Even to the extent, it is the only place,  where some users will see omp.

I think form @willinsky's suggestion  
"Copyediting Discussion" suits more than the "production discussion". The reason is that copyedting says   exactly, what it does and the production seems  general for me. I have looked  some other tools and they use words  like "chat" or "collaboration" too. but  the word "discussion" makes more sense to me.

**Comment by asmecher** [comment]
For per-site customization I'll be forward-porting the "custom locales" plugin, which allows targeted overrides to locale file strings without requiring filesystem changes (e.g. to XML files).

**Comment by asmecher** [comment]
I've renamed the discussion tools to (depending on workflow stage)...

- Pre-Review Discussions (on the submission stage, before it's sent to review)
- Copyediting Discussions (where copyediting happens)
- Production Discussions (where layout editing happens)

Objections?

**Comment by asmecher** [comment]
None heard!
