### ISSUE TITLE
XSS attack 3.5 

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/pkp-lib#9698]
**Describe the bug**
I was able to execute script in reader interface, when submitting following prefix in submission: 
```
<img src="invalid-url" onerror="alert('XSS Attack prefix')" />
```

**To Reproduce**
1. Create new submission
2. Insert malicious prefix, either by editor, or it can be done by submitter using API
```
<img src="invalid-url" onerror="alert('XSS Attack prefix')" />
```

3. Publish submission
4. Go to reader interface, select the issue you used to publish it.
5. alert should show up 

**What application are you using?**
 OJS, OMP or OPS version 3.5

**Additional information**
This seems to be regression from https://github.com/pkp/pkp-lib/issues/7916

**Comment by jardakotesovec** [comment]
@touhidurabir Hi Touhidur, tagging you as you worked on the issue.

**Comment by touhidurabir** [comment]
@jardakotesovec https://github.com/pkp/pkp-lib/issues/7916 is still an ongoing issue and WIP . The initial implementation does not handle all possible cases and need more fine tuning . there are few possible enhancement we are thinking about but also having some performance issue with those . 

I think we can keep it open for now or moved the details form here(and close it) to https://github.com/pkp/pkp-lib/issues/7916 so that we can get back to it later to know that it's still not resolved yet .

**Comment by jardakotesovec** [comment]
@touhidurabir Maybe lets keep this one opened as well for better awareness if someone runs into it like me :-). Also its bigger chance that these particular steps won't get lost in 7916.

**Comment by touhidurabir** [comment]
Resolved by latest implementation of https://github.com/pkp/pkp-lib/issues/7916 .
