### ISSUE TITLE
Failed Ajax request or invalid JSON returned. - When trying to add a reviewer to a submission.

### ISSUE THREAD

**Issue by nev888** [pkp/pkp-lib#9724]
**Describe the bug**
When I click on 'Add Reviewer' button to add a reviewer to a submission the browser shows a pop box with 'Failed Ajax request or invalid JSON returned.' message

In the OJS log the following fatal errors appear:
`[11-Feb-2024 12:33:58 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedData() on null in **/lib/pkp/controllers/grid/users/reviewer/form/ReviewerForm.php:482
Stack trace:
#0 **/lib/pkp/controllers/grid/users/reviewer/form/AdvancedSearchReviewerForm.php(253): PKP\controllers\grid\users\reviewer\form\ReviewerForm->getEmailTemplates()
#1 **/lib/pkp/controllers/grid/users/reviewer/form/ReviewerForm.php(264): PKP\controllers\grid\users\reviewer\form\AdvancedSearchReviewerForm->getEmailTemplates()
#2 **/lib/pkp/controllers/grid/users/reviewer/form/AdvancedSearchReviewerForm.php(238): PKP\controllers\grid\users\reviewer\form\ReviewerForm->fetch(Object(APP\core\Request), NULL, false)
#3 **/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php(1092): PKP\controllers\grid\users\reviewer\form\AdvancedSearchReviewerForm->fetch(Object(APP\core\Request))
#4 **/lib/pkp/classes/controllers/grid/users/reviewer/PKPReviewerGridHandler.php(353): PKP\controllers\grid\users\reviewer\PKPReviewerGridHandler->_fetchReviewerForm(Array, Object(APP\core\Request))
#5 [internal function]: PKP\controllers\grid\users\reviewer\PKPReviewerGridHandler->showReviewerForm(Array, Object(APP\core\Request))
#6 **/lib/pkp/classes/core/PKPRouter.php(334): call_user_func(Array, Array, Object(APP\core\Request))
#7 **/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#8 **/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#9 **/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#10 **/index.php(21): PKP\core\PKPApplication->execute()
#11 {main}
  thrown in **/ib/pkp/controllers/grid/users/reviewer/form/ReviewerForm.php on line 482
`

**To Reproduce**
1. Go to 'Submissions' section
2. Choose a submission in 'Review' stage
3. Click 'Add Reviewer'
4. A pop box should appear with the error message.

**What application are you using?**
OJS: 3.4.0-4
OS platform: Linux
PHP version 8.2.13

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
<img width="1440" alt="Screenshot 2024-02-11 at 13 41 58" src="https://github.com/pkp/pkp-lib/assets/33160852/db7925f1-e962-4726-bd59-6aa130328577">

**Comment by nev888** [comment]
Realised this issue caused by some corruption in the table (email_templates_default_data) which holds the email templates. I think the issue appeared after OJS upgrade done in this order (3.4.0.4   <--   3.4.0.3  <--   3.4.0.0   <--    3.3.0.15 )
This was fixed by importing a this table from a correct working system.

**Comment by asmecher** [comment]
Thanks for following up with the solution, @nev888!

**Comment by Vitaliy-1** [comment]
@nev888,

It looks that `REVIEW_REQUEST` email template is missing from the OJS instance. Can you track down when it got removed?

**Comment by Faujinurdin** [comment]
I have The Same Problems  When I click on 'Add Reviewer' button to add a reviewer to a submission the browser shows a pop box with 'Failed Ajax request or invalid JSON returned.' message    only in several journals have this problems  ... because we have about  16 Jurnal  and the other journal is Fine  How To Fix it ..? any Suggestion  @Vitaliy-1  @asmecher @nev888 

this is the error log : 

#0 /home/ummf7485/public_html/ejournals/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\plugins\generic\orcidProfile\OrcidProfilePlugin->register()
#1 /home/ummf7485/public_html/ejournals/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\plugins\PluginRegistry::register()
#2 [internal function]: PKP\plugins\PluginRegistry::PKP\plugins\{closure}()
#3 /home/ummf7485/public_html/ejournals/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive()
#4 /home/ummf7485/public_html/ejournals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#5 /home/ummf7485/public_html/ejournals/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch()
#6 /home/ummf7485/public_html/ejournals/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
[23-Jun-2025 07:58:48 UTC] ojs2: 404 Not Found
[23-Jun-2025 07:58:52 UTC] Exception: The ORCID plugin is enabled, but its settings are invalid. In order to fix, access the plugin settings and try to save the form in /home/ummf7485/public_html/ejournals/plugins/generic/orcidProfile/OrcidProfilePlugin.php:106
Stack trace:
#0 /home/ummf7485/public_html/ejournals/lib/pkp/classes/plugins/PluginRegistry.php(76): APP\plugins\generic\orcidProfile\OrcidProfilePlugin->register()
#1 /home/ummf7485/public_html/ejournals/lib/pkp/classes/plugins/PluginRegistry.php(121): PKP\plugins\PluginRegistry::register()
#2 [internal function]: PKP\plugins\PluginRegistry::PKP\plugins\{closure}()
#3 /home/ummf7485/public_html/ejournals/lib/pkp/classes/plugins/PluginRegistry.php(121): array_walk_recursive()
#4 /home/ummf7485/public_html/ejournals/lib/pkp/classes/core/Dispatcher.php(155): PKP\plugins\PluginRegistry::loadCategory()
#5 /home/ummf7485/public_html/ejournals/lib/pkp/classes/core/PKPApplication.php(395): PKP\core\Dispatcher->dispatch()
#6 /home/ummf7485/public_html/ejournals/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}


 i found that the journal with Problem adding reviewer  doesnt have email template 

![Image](https://github.com/user-attachments/assets/adda33b7-f04c-4868-b339-b299824d1c73)


and the other journals ( can add reviewer)  have a email template ...

![Image](https://github.com/user-attachments/assets/e4a78856-7b53-4a3c-b4c0-63e3a4801542)

**Comment by bangkoor** [comment]
We have similar problem here. We have no clue until now. According to @nev888 answer, what is the "correct working system" mean? Any suggestion @asmecher ?

> Realised this issue caused by some corruption in the table (email_templates_default_data) which holds the email templates. I think the issue appeared after OJS upgrade done in this order (3.4.0.4 <-- 3.4.0.3 <-- 3.4.0.0 <-- 3.3.0.15 ) This was fixed by importing a this table from a correct working system.
