### ISSUE TITLE
The plugin gallery isn't visible at the site settings

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9812]
**Describe the bug**
At the site settings, it's possible to view, enable and also install plugins from a package, but I'm unable to access the plugin gallery.

**To Reproduce**
1. Access the menu Administration > Site Settings

**What application are you using?**
OJS 3.3

**Additional information**
Site Settings
![image](https://github.com/pkp/pkp-lib/assets/361921/338b2561-0390-4d9d-9680-db6fe2858aa0)

Website Settings
![image](https://github.com/pkp/pkp-lib/assets/361921/a462aa08-21c0-4515-ab0d-f3f6ca6af8c6)

**Comment by kaitlinnewson** [comment]
PR for review @asmecher and will forward-port once approved:

- pkp-lib 3_3_0: https://github.com/pkp/pkp-lib/pull/10240

This PR adds the plugin gallery to `/index/admin/settings#plugins`. 

As I was testing I noticed that the plugin gallery in the settings wizard (e.g. `/index/admin/wizard/1#plugins`) redirects the user to the website settings after installing a plugin. I left this behaviour as it is but can file an issue for this unless it's intentional.

**Comment by asmecher** [comment]
Thanks, I added a review! https://github.com/pkp/pkp-lib/pull/10240#pullrequestreview-2194890597

**Comment by asmecher** [comment]
Thanks! This took a lot less code than I was expecting.
