### ISSUE TITLE
[OMP] Add cover image to ONIX export data

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#9927]
The book cover image is not currently included in the ONIX extract; DOAB would like it to be added.

DOAB suggests we use the following ONIX field(s):

> CollateralDetail/SupportingResource/ResourceVersion/ResourceLink

**Comment by kaitlinnewson** [comment]
Ready for review @asmecher

PRs:

- OMP 3_3_0: pkp/omp#1583
- OMP 3_4_0: pkp/omp#1589
- OMP main: pkp/omp#1590

This adds a link to the ONIX export metadata for the cover image URLs. Something to note is that because OMP uses a default placeholder image if no cover is added, the placeholder will be linked to when no cover was uploaded.

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson! Just [one thing](https://github.com/pkp/omp/pull/1583/files#r1636739720) to change.

**Comment by kaitlinnewson** [comment]
@asmecher Ready for a second look in https://github.com/pkp/omp/pull/1583

**Comment by asmecher** [comment]
That looks great! Could you sync the changes to the other PRs for the other branches?

**Comment by asmecher** [comment]
Thanks, @kaitlinnewson, I've merged all 3! :fireworks:
