### ISSUE TITLE
OJS 3.0: searching doesn't search article titles

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#994]
Searching an author's name will bring up a result but not searching a word in the title of that result.

**Comment by asmecher** [comment]
@NateWr, the attached patch should fix the problem for expedited submissions. Note that search results by keyword are cached at the PHP level. To clear the cache, either use the "clear data cache" tool in site administration, or...

    rm -rf cache/_db/??

Otherwise, can you clarify how you created/published the submission?

**Comment by NateWr** [comment]
That's probably it. I'll test when I'm back in action after Christmas.
