### ISSUE TITLE
Enhance submission schema with review assignment data

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9965]
- [x] Reviewer name
- [x] Review method
- [x] Anonymize review assignment data for blind reviews

**Comment by Vitaliy-1** [comment]
PRs
pkp-lib: https://github.com/pkp/pkp-lib/pull/9984
OJS: https://github.com/pkp/ojs/pull/4289

**Comment by Vitaliy-1** [comment]
@bozana, can you take a look at these PRs? This solves the problem of showing additional review data on the new submissions list. I've added it to the submission schema, so it's available also from `submission` API endpoint for authors and reviewers, which means that sensitive data should be anonymized if review isn't open.

**Comment by bozana** [comment]
Hi @Vitaliy-1, the PRs look good to me! Please, go ahead...

**Comment by Vitaliy-1** [comment]
@jardakotesovec, I've updated the PR according to our discussion regarding the `_submissions/assigned` endpoint for authors, can you take a look?

**Comment by jardakotesovec** [comment]
@Vitaliy-1 Here is idea..  likely naive as I am still trying to grasp how the permissions/access are handled, but here we go..

We already have challenge on multiple API endpoints - where if user has multiple roles (reviewer/author/editor), we might return more data than we want - like incorrect dashboard views, or incorrect result to particular dashboard view.

So how about if we introduce more general concept where I can set in the API (probably via query param) that I want to reduce the roles - some top layer would reduce the roles I am accessing the system with and than the API would have easier time to reason about things, if they for example think I am just author - it won't lead any additional data, just because I happen to also be editor.

With that - would not be possible to have just simple implementation for review assignment on the submissions schema, where it would anonymise them based on 'having just author role and review assignment is not open'?

**Comment by jardakotesovec** [comment]
Hmm.. this probably would not work..   Because I guess that some editor roles can't access all submissions unless they are assigned to them, right?

So when API would be used directly - than theoretically editor who is also author could access more than he should
